### ISSUE TITLE
How to create a schema migration with existing records

### ISSUE THREAD

**Issue by lianshen-vineti** [ent/ent#1033]
Use Case:
I'm trying to add a new required field to an existing table with existing records.

How would I run my migration to add the new field to my table, as well as backfill my existing records?

When I run `err := client.Debug().Schema.Create(context.Background(), migrate.WithGlobalUniqueID(true), migrate.WithDropIndex(true), migrate.WithDropColumn(true))`, I get an error 
```
{"severity":"fatal","error":"sql/schema: alter table \"{table_name}\": pq: column \"uuid\" contains null values","@timestamp":"2020-12-11T15:05:43.440429-08:00","message":"failed creating schema {table_name}"}
```

**Comment by a8m** [comment]
Hey @lianshen-vineti,
Just to make sure I understand your use case, do you try to add a UUID field with default value on PostgreSQL? 

What database version do you use? Thanks

**Comment by lianshen-vineti** [comment]
Hi @a8m 
I'm working with v12.1 in PostgreSQL. I've tried a few separate ways to create/update to a UUID field in a table with existing records:
1. change the existing PK ID field to a UUID type, no default --> does not change the field type
2. change the existing PK ID field to a UUID type, with default as uuid.New() --> does not change the field type
3. add a new field as a UUID type, no default --> error in migration
4. add a new field as a UUID type, with default as uuid.New() --> I had hoped this would auto-generate uuid's for the existing records, but I get the same error as 3 related to null values.
5. add a new field as a UUID type, with default as uuid.New() and optional --> this works, but existing records' UUID field is null.

I might be using `Schema.Create()` in a way that it's not designed for. Does another feature work for what I'm trying to do? The way I see around this would be to make UUID an optional column, migrate the existing records, then make uuid column required, but that step-by-step process seems like it should be handled by a separate migration script.

**Comment by arielitovsky** [comment]
Is there any resolution to this? I'm seeing the exact same issue when trying to add a required Boolean with a default value. It does not use the default value, so it's unable to migrate:

Adding

field.Bool("newField").Default(false),

And then running migrate with these options:

	opts := []schema.MigrateOption{
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
		migrate.WithForeignKeys(true),
		migrate.WithFixture(true),
	}

Yields: 

[ERROR] ent migrations: failed creating schema resources: sql/schema: alter table "reservation_options": pq: column "newField" contains null values

**Comment by Guiren** [comment]
Hi. We're having the same issue when trying to add a `created_at` column, with `Default(time.Now())`.

The issue here is that both `Default` and `UpdateDefault` use custom Go code to handle this in PostgreSQL, but the database itself has no idea what the default value should be, which makes the `ALTER TABLE` query fail.  
  
I believe ent should be able to set DEFAULT values at least on the schema.

**Comment by a8m** [comment]
Hey all and thanks for reporting these issues.

The boolean problem was addressed in previous PRs (it was actually a problem with "falsy" values). 

Default values that are generated by the database (like `CURRENT_TIMESTAMP` and `uuid_generate_v4()`) or other SQL-specific expressions can be added to the `DEFAULT` clause using the `entsql.Annotation` - https://github.com/ent/ent/pull/1420. 

```go
field.Time("created_at").
	Default(time.Now).
	Annotations(&entsql.Annotation{
		Default: "CURRENT_TIMESTAMP",
	})
```

The `ON UPDATE`  clause will be added to this annotation in the upcoming days as well.

Please let me know if you have any troubles with it. Thanks 🙏
