### ISSUE TITLE
 Can I write the following SQL in ent?

### ISSUE THREAD

**Issue by shuogawa** [ent/ent#1040]
My schema is below.

Post O2M Comment

 Can I write the following SQL in ent?
```
SELECT
	posts.*,
	(
	SELECT
		COUNT(*) 
	FROM
		comments 
	WHERE
		posts.id = comments.post_id 
	) AS comment_count 
FROM
	posts 
ORDER BY
	comment_count DESC
```

**Comment by a8m** [comment]
Hey @shuogawa,  I can help with that.

Do you try to scan the returned records to a custom struct (e.g. `T{Post, Count int}`)?

**Comment by shuogawa** [comment]
@a8m 
Thank you very much!
I will try and report.

**Comment by a8m** [comment]
Hey, closing since there's no update since last comment.
Please feel free to reopen if you still need help with this 🙏
