### ISSUE TITLE
how to get fk field when i use sql to select table？？？

### ISSUE THREAD

**Issue by G-Bruin** [ent/ent#1047]
![image](https://user-images.githubusercontent.com/20853074/102215486-bdbb5a00-3f14-11eb-9d82-9ce480f09617.png)

`parent_id`  has many organization_id

```
organization.go

func (Organization) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", Organization.Type).
			StorageKey(edge.Column("parent_id")).
			From("organization_parent").
			Unique(),
	}
}

```

i use sql by `select * from organization`

```
	ctx := context.Background()
	// run the auto migration tool
	if err := client.Schema.Create(ctx, migrate.WithForeignKeys(false)); err != nil {
		log.Fatalf("failed creating schema resources:%v", err)
	}
	or, err := client.Organization.
		Query().
		All(ctx)
	if err != nil {
		fmt.Println(err)
	}
```
![image](https://user-images.githubusercontent.com/20853074/102216137-adf04580-3f15-11eb-8bc7-92d76b583b33.png)

The result does not contain a parent_id

**Comment by G-Bruin** [comment]
@a8m Is there any special consideration?

**Comment by fangniu** [comment]
+1

**Comment by a8m** [comment]
Hey all, this functionality was added in v0.7.0. Please see [our blog post](https://entgo.io/ja/blog/2021/03/12/announcing-edge-field-support/) and the [documentation](https://entgo.io/ja/docs/schema-edges/#edge-field) if you want to use this feature.

Closing. Thanks for opening this issue and feel free to ping me on [ent Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) if you need any help with it. Thanks
