### ISSUE TITLE
GoType not generating predicates

### ISSUE THREAD

**Issue by JamesHovious** [ent/ent#1051]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Using a custom struct as below does not generate the expected predicates in `where.go`. (note I'm not sure that the Scan/Value code is even correct since I am not able to get to a phase to test it).
```
field.String("custom").
  Unique().
  GoType(&Custom{}),

type Custom struct {
	F1    string
	F2    string
}


func (c *Custom) Scan(value interface{}) (err error) {
	switch v := value.(type) {
	case nil:
	case []byte:
		err = json.Unmarshal(v, c)
	case string:
		err = json.Unmarshal([]byte(v), c)
	default:
		err = fmt.Errorf("unexpcted type %T", v)
	}
	return
}

func (c Custom) Value() (driver.Value, error) {

	if c == (Custom{}) {
		return nil, nil
	}

	out, err := json.Marshal(c)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, string(out[:]))

	return b.String(), nil
}

```

## Expected Behavior 🤔

filtering predicates should be generated in the appropriate `where.go`

## Steps to Reproduce 🕹

Steps:

1. create a `field.String` field and add a custom struct to it using `GoType`
2. compile with entc

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15  |
| Ent         |  v0.5.3   |
| Database    | sqlite   |
| Driver      | github.com/mattn/go-sqlite3       |

tagging @a8m

**Comment by a8m** [comment]
Hey @JamesHovious - this issue should be fixed in the latest master version. You can update as follows:

```
go get -u entgo.io/ent@master
```

Please reopen this issue or tag me if you still have trouble with it. Thanks 🙏
