### ISSUE TITLE
Is edge weights a supported concept?

### ISSUE THREAD

**Issue by kingledion** [ent/ent#1061]
My team has a project starting up where we intended to use Gremlin on AWS Neptune to build a relationship table with a recommendation engine. Seeing that the blog here states that the creators moved from that exact stack to create this, I thought I should make a demo and check it out.

One thing that is baffling me is the lack of information attached to the edges. Example, let say we have user and product nodes and review edges. The review edges should hold a weight indicating the strength of the review. I don't see an out-of-the-box way to put that data onto the edge.

Seems like the way I should structure the data is to make reviews their own node, and define separate edge relationships between user and review and review and product. Is that how ent is supposed to be used?

**Comment by a8m** [comment]
Hey @kingledion!

Yeah, we originally built our service (and this framework) on top of Gremlin, but decided to add support for SQL and switched our database to relational database. I wrote about this in a few issues here, and you're welcome to search (e.g. https://github.com/facebook/ent/issues/452#issuecomment-619430120). 

> One thing that is baffling me is the lack of information attached to the edges. Example, let say we have user and product nodes and review edges. The review edges should hold a weight indicating the strength of the review. I don't see an out-of-the-box way to put that data onto the edge.

We don't support this at the moment, but we plan to address it before V1 (see our [roadmap](#46)). Basically, we want to make it possible for users to define fields/properties on edges as follows:

```go
edge.To("friends", User.Type).
    Fields([]ent.Field{
        field.Time("since").
            Default(time.Now), 
    })
```

Leaving this issue open to collect more thoughts and suggestions for this API.

**Comment by dilipkk-foyernet** [comment]
@a8m 
```
        edge.To("friends", User.Type).
            // Set the join-table, and the column names for a M2M relationship.
            StorageKey(edge.Table("friends"), edge.Columns("user_id", "friend_id")),
```
In the above code sample, what happens if add few more columns to `edge.Columns("user_id", "friend_id","xyz", "abc")`. Can we access them using ent framework?

**Comment by a8m** [comment]
> @a8m
> 
> ```
>         edge.To("friends", User.Type).
>             // Set the join-table, and the column names for a M2M relationship.
>             StorageKey(edge.Table("friends"), edge.Columns("user_id", "friend_id")),
> ```
> 
> In the above code sample, what happens if add few more columns to `edge.Columns("user_id", "friend_id","xyz", "abc")`. Can we access them using ent framework?

No, but I'm going to add support for this after finishing https://github.com/ent/ent/pull/1793.

**Comment by dilipkk-foyernet** [comment]
Thanks for a quick response.

**Comment by FingerLiu** [comment]
Hi, may I ask when will this release?
This is a very common usage~

**Comment by oSethoum** [comment]
Any updates about this issue ?

**Comment by bbkane** [comment]
From https://entgo.io/blog/2022/01/20/announcing-new-migration-engine :

I know we took a while to get this release out the door, but the next one is right around the corner. Here's what's in store for v0.11:

-   Add support for edge/relation schemas - supporting attaching metadata fields to relations.

**Comment by tsingsun** [comment]
How do you feel about  #2540 ?

**Comment by a8m** [comment]
Hey all 👋 

The feature was added to Ent and available under the [Edge Schema](https://entgo.io/docs/schema-edges#edge-schema) section on our website. Please, give it a try and let us know if you need any support with it. We're available in our [Discord server](https://discord.gg/qZmPgTE6RX).

**Comment by frederikhors** [comment]
@a8m I think we should update accordingly the text here: https://entgo.io/docs/schema-edges/#edge-field:

![image](https://user-images.githubusercontent.com/41120635/171665500-577f0d81-6f0e-4aec-a089-abcd4bbdce53.png)
