### ISSUE TITLE
Postgres Composite Types Support

### ISSUE THREAD

**Issue by aight8** [ent/ent#1063]
When I using Postgres Composite Types, some features of ent does not working. But a lot does.

- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

https://www.postgresql.org/docs/current/rowtypes.html
```sql
CREATE TYPE myid AS
(
    field1 TEXT,
    field2 TEXT,
    field3 TEXT,
    field4 TEXT
);

CREATE TABLE mymodel
(
    id	   myid PRIMARY KEY GENERATED ALWAYS AS ((field1,field2,field3,field4)) STORED,
    field1 TEXT,
    field2 TEXT,
    field3 TEXT,
    field4 TEXT
);
```

```sql
/* INSERT works without type cast */
INSERT INTO mymodel (field1, field2, field3, field4)
VALUES
('aaa', 'aaa', 'aaa', 'aaa'),
('bbb', 'bbb', 'bbb', 'bbb')
RETURNING *;

-- Ent Generates for Select Queries:
-- SELECT DISTINCT id FROM mymodel WHERE id = ('aaa', 'aaa', 'aaa', 'aaa');
-- Query Error: error: cannot compare dissimilar column types text and unknown at record column 1
-- Should be:
SELECT DISTINCT id FROM mymodel WHERE id = ('aaa', 'aaa', 'aaa', 'aaa')::myid;

-- Ent Generates for Select Queries:
-- DELETE FROM mymodel WHERE id = ('aaa', 'aaa', 'aaa', 'aaa');
-- Query Error: error: cannot compare dissimilar column types text and unknown at record column 1
-- Should be:
DELETE FROM mymodel WHERE id = ('aaa', 'aaa', 'aaa', 'aaa')::myid;
```

```go
package schema

import (
	"github.com/facebook/ent"
	"github.com/facebook/ent/dialect"
	"github.com/facebook/ent/schema/field"
)

type TestModel struct {
	ent.Schema
}

func (TestModel) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").SchemaType(map[string]string{
			dialect.Postgres: "myid",
		}).GoType(new(MyID)),
	}
}

func (TestModel) Edges() []ent.Edge {
	return []ent.Edge{
	}
}

func (TestModel) Indexes() []ent.Index {
	return []ent.Index{
	}
}

// --------------------------------------------------------------------------------

//var _ driver.Valuer = new(MyID)
//var _ sql.Scanner = new(MyID)
type MyID struct {
	Field1 string
	Field2 string
	Field3 string
	Field4 string
}

// ...
```

## Motivation 🔦

Would solve some issues and limitations with NOT so big changes, definitely a hot feature.
#400 - Feature: Multi-Key Primary

**Comment by cliedeman** [comment]
Leaving a note here for myself because I am interested in a particular use case. A composite timestamp + timezone field

**Comment by aight8** [comment]
https://github.com/facebook/ent/blob/24f6975b9a84b26be9bead1a484bda431cf4d286/dialect/sql/builder.go#L2091-L2108

Quickfix solution:

```go
type ICastDataType interface {
	CastDataType() string
}

// Arg appends an input argument to the builder.
func (b *Builder) Arg(a interface{}) *Builder {
	if r, ok := a.(*raw); ok {
		b.WriteString(r.s)
		return b
	}
	b.total++
	b.args = append(b.args, a)
	switch {
	case b.postgres():
		// PostgreSQL arguments are referenced using the syntax $n.
		// $1 refers to the 1st argument, $2 to the 2nd, and so on.
		if v, ok := a.(ICastDataType); ok {
			b.WriteString("CAST($" + strconv.Itoa(b.total) + " AS " + v.CastDataType() + ")")
		} else {
			b.WriteString("$" + strconv.Itoa(b.total))
		}
	default:
		b.WriteString("?")
	}
	return b
}
```

However there is a problem with this too:
Fields (except the ID field) with a defined GoType convert the argument to string when the ```String()``` method is implemented in all predicates. If I remove the ```String()``` only the IsNotNil and IsNil predicates are generated for the field.

**Comment by vojta001** [comment]
Sorry to be annoying, but ent is otherwise so awesome I cannot resist. It am soooooo looking forward to see #400 implemented and this issue is a prerequisite.

How is it currently going?

**Comment by a8m** [comment]
Hey @vojta001, there are a few stuff before this (e.g. migration), but we'll get to it. I'll try to come up soon with some time estimation for this.

**Comment by vojta001** [comment]
You're awesome! Thanks

**Comment by aight8** [comment]
I currently have forked ent with enables pgx support and support for db site native composite and also enum types.
However I use a generated ID field, which constructs the value by 4 other fields.
The most important thing is the knowledge of the db type which a type represents as string representation.
It is required for various SQL statements to cast a anonymous ROW (this is how a composite type is written) to the target field type. This is somehow not auto recognized - except sometimes (for example in an INSERT statement). I don't know the exact reason for this.
So a composite type value can be noted as:
```ROW('fuzzy dice', 42, 1.99)``` or in certain condition ```('', 42, NULL)```

which results often to an error:
```ERROR:  input of anonymous composite types is not implemented```

It must be:
```ROW('fuzzy dice', 42, 1.99)::mycomptype``` or in certain condition ```('', 42, NULL)::mycomptype``` (pg syntax)
or in SQL standard syntax:
```cast(row('fuzzy dice', 42, 1.99) as mycomptype)``` or in certain condition ```cast(('', 42, NULL) as mycomptype)```
when using params:
```cast($1 as mycomptype)``` or in certain condition ```cast($1 as mycomptype)```

**Comment by a8m** [comment]
Closing, as we rely on Atlas for managing composite types (and any other custom database objects). See: https://entgo.io/docs/migration/composite-types
