### ISSUE TITLE
[Question] Implementation for GraphQL nested pagenation

### ISSUE THREAD

**Issue by touyu** [ent/ent#1180]
Hello, Thanks for this useful library.

I have a question about the combination with gqlgen.

I want to accept query like below
```graphql
{
  users(first: 10) {
    edges {
      node {
        id
        name
        items(first: 10) {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

The schema of `user` and `item` is the following code
```go
type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("items", Item.Type).
			Annotations(entgql.Bind()).
	}
}
```

```go
type Item struct {
	ent.Schema
}

func (Item) Fields() []ent.Field {
	return []ent.Field{
		field.String("title").
	}
}

func (Item) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
                         Ref("items")
			Annotations(entgql.Bind()).
			Unique(),
	}
}
```

Is it possible to avoid the N+1 issue and implement this?
Or should I use a dataloader like [`vektah/dataloaden`](https://github.com/vektah/dataloaden) ?

I read docs about the [Field Collection](https://entgo.io/docs/graphql/#fields-collection).

**Comment by a8m** [comment]
Hey @touyu 😃 

This option is not supported by default, but I think I can come up with something in the upcoming days. I'll give it a look and update you.

**Comment by touyu** [comment]
Hello @a8m 

Is there any progress on this? 🙂

**Comment by henrywoody** [comment]
Also interested in this, but with filtering support as well (just to expand the scope a bit here). API I'm going for is that all connection-type queries have the same interface regardless of nesting. So I'd have something like this:

```
{
  users(first: 10, filter: {emailHasSuffix: "@example.com"}) {
    edges {
      node {
        id
        name
        items(first: 10, filter: {categoryEQ: "example"}) {
          edges {
            node {
              id
              title
            }
          }
        }
      }
    }
  }
}
```

**Comment by aakashkharwar** [comment]
[smdms
](url)

**Comment by frederikhors** [comment]
@a8m, what is the priority of this in your plans?

**Comment by a8m** [comment]
Hey! Thanks for the reminder, I forgot to update this issue. It's actually been supported by entgql for a few months (check out the latest release). 

Just note that there's an issue with aliases + when the same edge is loaded more than once and it's tracked in https://github.com/ent/ent/issues/2755. This issue should be handled by @giautm and myself in the upcoming days.

Closing 😃

**Comment by frederikhors** [comment]
Is there any docs for this? It seems I cannot find any of it.

**Comment by frederikhors** [comment]
Specifically I need to order sub-queries and I cannot find any docs about it. I'm using gqlgen too.

**Comment by giautm** [comment]
> Specifically I need to order sub-queries and I cannot find any docs about it. I'm using gqlgen too.

No doc is needed because it is working based on preload edges. https://entgo.io/docs/tutorial-todo-gql-field-collection

**Comment by frederikhors** [comment]
Sorry, I was confused. That's not what I was trying to do. This works good.

By the way, maybe there are old issues like this that can be closed. Kind of like I did for gqlgen.
