### ISSUE TITLE
proposal: mysql full-text index surport

### ISSUE THREAD

**Issue by haoxf** [ent/ent#1182]
Hello,
Is there a simple way to support MySQL full-text index.
Thanks

**Comment by a8m** [comment]
Hey @haoxf and sorry for the delayed response 😃 

> Is there a simple way to support MySQL full-text index.

Not at the moment, but we can add support for this. I'll try to give it a look soon.

**Comment by haoxf** [comment]
@a8m Thanks, expect new features to come.

**Comment by a8m** [comment]
Hey @haoxf 👋 

Custom index type support was added a long time ago and I forgot to update this issue. Please, see https://entgo.io/docs/schema-indexes#atlas-support and let me know if you need any help with it:

```go
func (User) Indexes() []ent.Index {
    return []ent.Index{
        index.Fields("c1").
            Annotations(entsql.IndexType("HASH")),
        // Enable FULLTEXT search on MySQL,
        // and GIN on PostgreSQL.
        index.Fields("c2").
            Annotations(
                entsql.IndexTypes(map[string]string{
                    dialect.MySQL:    "FULLTEXT",
                    dialect.Postgres: "GIN",
                }),
            ),
    }
}
```
