### ISSUE TITLE
Why are indexes on string/text columns longer than 255 prohibited?

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [ent/ent#1193]
The entc generator code at https://github.com/facebook/ent/blob/master/entc/gen/type.go#L499-L501 prohibits creating indexes on textual columns that can hold more than 255 chars (`schema.DefaultStringLen`).

Git history suggests that this is old code, and doesn't indicate the motivation for this code.

AFAIK all the dialects ent supports permit indexes on long (even unbounded length) strings, certainly PostgreSQL & SQLite do.

Is this a bug, or simply an oversight?

**Comment by a8m** [comment]
Hey @mgabeler-lee-6rs,
This check was added ~18 month ago, before we actually supported PostgreSQL (and before we had annotations).

The plan is to improve the index API in ent/schema in the future, and add support for dialect-specific features like [full-text](#1182) indexes and index prefixes.

**Comment by mgabeler-lee-6rs** [comment]
In the meantime, then, would it be reasonable to at least raise, if not remove this limitation?

If there is concern about unwittingly creating "naive" indexes for large text columns, perhaps could gate this tolerance behind a schema config field?

FWIW, this is relatively easy to work around for now using `SchemaType` to override the `varchar(255)` to `text`, it just seemed like an oddly arbitrary constraint since the underlying DBs generally have little or no problem indexing these fields.

**Comment by giautm** [comment]
I ran into the same issue when trying to create a unique index on the column with `varchar(1024)` data type.

**Comment by a8m** [comment]
Hey @giautm, I'll add the option to add column-prefix to indexes this week, and then we can remove this limitation. I will update you once this issue is addressed.
