### ISSUE TITLE
Custom ValueScanner string type isn't evaluated

### ISSUE THREAD

**Issue by clalos** [ent/ent#1198]
Hello, first of all, thanks for the amazing work!
I'd like to use a custom type to escape/unescape strings from/to the database. The Scan function doesn't seem to work. Below the details.
Thanks in advance for your help. 

Custom type:
```
var (
	escapeReplacer = strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		"\"", "&quot;",
		"'", "&#039;",
	)

	unescapeReplacer = strings.NewReplacer(
		"&amp;", "&",
		"&lt;", "<",
		"&gt;", ">",
		"&quot;", "\"",
		"&#039;", "'",
	)
)

type EscapedString string

func (e *EscapedString) Scan(src interface{}) error {
	var output string

	switch src := src.(type) {
	case nil:
		return nil
	case string:
		output = unescapeReplacer.Replace(src)
	case []byte:
		output = unescapeReplacer.Replace(string(src))
	default:
		return errors.New("incompatible type for EscapedString")
	}

	*e = EscapedString(output)

	return nil
}

func (e EscapedString) Value() (driver.Value, error) {
	return escapeReplacer.Replace(string(e)), nil
}
```

Example entity:
```
type Example struct {
	ent.Schema
}

func (Example) Fields() []ent.Field {
	return []ent.Field{
		field.String("dirty_string").Default("").GoType(EscapedString("")),
	}
}

func (Example) Edges() []ent.Edge {
	return nil
}
```

Example usage:
```
test, err := client.Example.Get(context.Background(), 1)
if err != nil {
	log.Fatal(err)
}
escapedString := string(test.DirtyString)
fmt.Println(escapedString) // <-- This should be the Scan() output. It contains the original DB value instead.
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The custom type doesn't override the database's original value. I can see the Scan() function is been executed correctly but it's not reflected in the final result.

In the generated code the  `scanValues` maps the field to `sql.NullString` instead. I'm not sure if it's related.
```
func (*Example) scanValues() []interface{} {
	return []interface{}{
		&sql.NullString{},        // dirty_value
	}
}
```

## Expected Behavior 🤔

The query output reflects the Scan() output.

**Comment by a8m** [comment]
Thanks @clalos, I'll give it a look and update you.

**Comment by a8m** [comment]
Hey @clalos, just checked this and it doesn't work because the type for `GoType` doesn't implement the `ValueScanner` interface (because the `Scan` method gets a pointer receiver).  The schema is valid because the GoType is convertible to `string`. 

You can solve this now by changing your type to `type EscapedString struct {String string}`, and we can work on adding support for this use case.

**Comment by clalos** [comment]
Thanks for your reply.

> You can solve this now by changing your type to `type EscapedString struct {String string}`, and we can work on adding support for this use case.

This would produce a compilation error in the generated files.
For example, the `runtime.go` would try to directly convert to a `string` type, which is clearly not possible. This happens even if I don't specify a default value for the field.
```
func init() {
...
example.DefaultValue = EscapedString(exampleDescValue.Default.(string))
...
}
```

**Comment by a8m** [comment]
>  This happens even if I don't specify a default value for the field.

Are you sure about this? There are many examples in the integration-tests that work great without any issue:
https://github.com/facebook/ent/blob/8420a64be3cdc52d16e1ce8ff1fceed678d7a789/entc/integration/ent/schema/fieldtype.go#L74-L102

I'll check the default-value case.

**Comment by clalos** [comment]
@a8m My bad, it works by using `type EscapedString struct {String string}`. I had to remove the `.Default()` from the other schemas too. I will use `DefaultFunc()` instead for such cases.
Thanks!

**Comment by clalos** [comment]
In addition, the above solution brings me to issue #1051. How can I filter by a custom type? 🤔️

**Comment by YujiShen** [comment]
> it works by using `type EscapedString struct {String string}`

@clalos Could you elaborate how to make this work?

**Comment by clalos** [comment]
> @clalos Could you elaborate how to make this work?
 
The field declaration looks like this:
```
field.String("name").GoType(&adapter.EscapedString{}).DefaultFunc(func() adapter.EscapedString {
 return adapter.EscapedString{String: "default name"}
}),
```
The above solution doesn't generate the `where` predicates so to query I do this:
```
client.MyEntity.Query().Where(func(selector *sql.Selector) {
   selector.Where(sql.EQ(MyEntity.FieldName, "Foo Bar"))
}
```
Hopefully that answers your question.

**Comment by YujiShen** [comment]
@clalos Thanks for elaborations. 

I am trying to implement ValueScanner for my type based on bigquery.NullDateTime (I want to store value from BigQuery into database via Ent), in my case the `where` still generated and gives error in generated code said `Cannot convert expression of type 'schema.DateTime' to type 'Time'`. 

Here is my code for type and ValueScanner implementation:
```go
type DateTime struct {
	DateTime bigquery.NullDateTime
}

func (d DateTime) Value() (driver.Value, error) {
	datetime := d.DateTime
	return time.Date(
		datetime.DateTime.Date.Year,
		datetime.DateTime.Date.Month,
		datetime.DateTime.Date.Day,
		datetime.DateTime.Time.Hour,
		datetime.DateTime.Time.Minute,
		datetime.DateTime.Time.Second,
		datetime.DateTime.Time.Nanosecond,
		time.UTC), nil
}

func (d *DateTime) Scan(value interface{}) error {
	if value == nil {
		d.DateTime = bigquery.NullDateTime{
			DateTime: civil.DateTime{},
			Valid:    true,
		}
		return nil
	}
	var str string
	switch v := value.(type) {
	case string:
		str = v
	case []byte:
		str = string(v)
	case time.Time:
		d.DateTime = bigquery.NullDateTime{
			DateTime: civil.DateTimeOf(v),
			Valid:    false,
		}
		return nil
	default:
		return fmt.Errorf("scan datetime failed, unknown type %T", value)
	}
	if str != "" {
		x, err := civil.ParseDateTime(str)
		if err != nil {
			return err
		}
		d.DateTime = bigquery.NullDateTime{
			DateTime: x,
			Valid:    false,
		}
	}
	return nil
}
```

**Comment by a8m** [comment]
Hey @clalos and @YujiShen - this issue should be fixed in the latest master version. You can update as follows:

```
go get -u entgo.io/ent@master
```

But note that this will require you to change the schema as follows because #1428 changes the GoType to use the real Go type.

```diff
field.String("name").
-	GoType(&adapter.EscapedString{})
+	GoType(adapter.EscapedString{})
```

You can leave it as-is if you prefer to use `*adapter.EscapedString` instead of `adapter.EscapedString` in your codebase.

Also, note that your first example should also work (with `type EscapedString string`). 

@YujiShen - your use-case should also work now. Please reopen this issue or tag me if you still have trouble with it. Thanks 🙏

**Comment by pzeinlinger** [comment]
Hey @a8m, after this merge, there seems to be a problem scanning nil strings from the database to custom gotypes.
Nil values in db are not unmarshaled as nil pointers but as zero values.

Quick demo: https://github.com/pzeinlinger/ent-nil-demo

**Comment by a8m** [comment]
> Hey @a8m, after this merge, there seems to be a problem scanning nil strings from the database to custom gotypes.
> Nil values in db are not unmarshaled as nil pointers but as zero values.
> 
> Quick demo: https://github.com/pzeinlinger/ent-nil-demo

I'll give it a look. Thanks for letting me know this.
