### ISSUE TITLE
Privacy layer filterFunc "or"

### ISSUE THREAD

**Issue by BitPhinix** [ent/ent#1220]
Hi there,

I've been playing around with the new privacy layer inside ent over the weekend and could not figure out how to filter based on a or condition for the root type. (`.Where` only accepts ent.P in this context).

Thanks for this awesome ORM 🙌 !

**Comment by a8m** [comment]
Hey @BitPhinix and thanks for the feedback.

Can you elaborate a bit more about the type of predicate you want to apply on the query? OR between what predicates?
You can share raw SQL query or some dummy code based on the examples in the `examples` directory.

**Comment by BitPhinix** [comment]
I basically want to do something like this (using a privacy filter based on 2 or more relations):

```
privacy.FilterFunc(func(ctx context.Context, f privacy.Filter) error {
		ec := ectx.MustGet(ctx)

		tf, ok := f.(AccountsFilter)
		if !ok {
			return privacy.Denyf("unexpected filter type %T", f)
		}

		tf.Where(
                     account.WhereHasGroupMembershipWith(
                         groupmembership.HasGroupWith(group.IDEQ(ec.GroupID)), 
                         account.WhereHasRelationshipWith(relationship.HasSomeField("something")),
                     ),
               )

		return privacy.Skip
	})
```

**Comment by a8m** [comment]
Hey @BitPhinix, and sorry for the delayed response. Can you explain why do you use the generic privacy-filter and not the `AccountQueryRuleFunc` if you need to change specific type? 

```go
func BoringAccountFilter() privacy.QueryRule {
	return privacy.AccountQueryRuleFunc(func(ctx context.Context, q *ent.AccountQuery) error {
		q.Where(account.Or(
			account.WhereHasRelationshipWith(relationship.HasSomeField("something")),
			account.WhereHasGroupMembershipWith(groupmembership.HasGroupWith(group.IDEQ(ec.GroupID))),
		))
		return privacy.Skip
	})
}

```

**Comment by BitPhinix** [comment]
Ohh didn't notice that was a thing, sorry about that 😅

**Comment by a8m** [comment]
Sure, feel free to re-open if you have any troubles with it 😃
