### ISSUE TITLE
How do I use postgresql schema?

### ISSUE THREAD

**Issue by MrParano1d** [ent/ent#1252]
This is my entity

```
type Country struct {
	ent.Schema
}

func (Country) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "tournament.countries"},
	}
}

// Fields of the Country.
func (Country) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("name").Optional().Nillable(),
		field.String("code").Optional().Nillable(),
		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now),
		field.Time("deleted_at"),
		field.Int("version"),
		field.Bytes("country_flag").Optional().Nillable(),
	}
}
```

But `go generate ./ent/` generates invalid code.

The `./ent/migrate/schema.go` looks like this:

```
var (
		// Tournament.countriesColumns holds the columns for the "tournament.countries" table.
		Tournament.countriesColumns = []*schema.Column{
				{ Name: "id", Type: field.TypeInt, Increment: true,},
				{ Name: "name", Type: field.TypeString, Nullable: true,},
				{ Name: "code", Type: field.TypeString, Nullable: true,},
				{ Name: "created_at", Type: field.TypeTime,},
				{ Name: "updated_at", Type: field.TypeTime,},
				{ Name: "deleted_at", Type: field.TypeTime,},
				{ Name: "version", Type: field.TypeInt,},
				{ Name: "country_flag", Type: field.TypeBytes, Nullable: true,},
		}
```

Which results in an `\ent\migrate\schema.go:25:13: expected ';', found '.' (and 1 more errors)` error during code generation.

How do I use postgres schema with ent?

**Comment by a8m** [comment]
Hey @MrParano1d and sorry for the delayed response. 

Please use the [sql/schemaconfig](https://entgo.io/docs/feature-flags/#schema-config) feature-flag in order to use alternate SQL database/schema for the different tables.

If all your tables reside on the same schema/database, add the database to the connection string as follows:

```go
c, err := ent.Open(dialect.Postgres, "postgresql://<user>:<pass>@<host>/<database>")
```

Closing, but feel free to re-open if you still have troubles with it. Thanks

**Comment by Deme94** [comment]
> Hey @MrParano1d and sorry for the delayed response.
> 
> Please use the [sql/schemaconfig](https://entgo.io/docs/feature-flags/#schema-config) feature-flag in order to use alternate SQL database/schema for the different tables.
> 
> If all your tables reside on the same schema/database, add the database to the connection string as follows:
> 
> ```go
> c, err := ent.Open(dialect.Postgres, "postgresql://<user>:<pass>@<host>/<database>")
> ```
> 
> Closing, but feel free to re-open if you still have troubles with it. Thanks

It works for the queries, but the tables are still created in the schema public when migration is run

**Comment by francisconunesribeiro** [comment]
> > Hey @MrParano1d and sorry for the delayed response.
> > Please use the [sql/schemaconfig](https://entgo.io/docs/feature-flags/#schema-config) feature-flag in order to use alternate SQL database/schema for the different tables.
> > If all your tables reside on the same schema/database, add the database to the connection string as follows:
> > ```
> > c, err := ent.Open(dialect.Postgres, "postgresql://<user>:<pass>@<host>/<database>")
> > ```
> > 
> > 
> > Closing, but feel free to re-open if you still have troubles with it. Thanks
> 
> It works for the queries, but the tables are still created in the schema public when migration is run

Hello, have you found a solution to this problem, or did you drop multi-schema?

**Comment by nadeemc** [comment]
You can also use the `sql/schemaconfig` feature flag to [customize this](https://entgo.io/docs/feature-flags/#schema-config).

```bash
go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/schemaconfig ./schema
```

That does not let you configure a schema for all tables, just each individual one. Using the `reflect` package, you can set a default schema other than public, e.g. an `app` schema:
```go
// set the default schema to "app" for all tables
sc := ent.SchemaConfig{}

v := reflect.ValueOf(&sc).Elem()
for i := 0; i < v.NumField(); i++ {
	field := v.Field(i)
	if field.Type().Kind() == reflect.String {
		field.SetString("app")
	}
}}

// customize schema for specific tables that aren't in "app", e.g. if you had an "other.logs" table.
sc.Logs = "other"
```
