### ISSUE TITLE
Sorting by nested fields

### ISSUE THREAD

**Issue by darestrepov7** [ent/ent#1256]
Good day,

We need to apply a way to order ents by edges and not just by fields (to be exact by some field of the ent that the edge point to). It appears to be a gap in the schema. 

We appreciate any help to achieve this goal.

Thanks. 

CC: @mescorci

**Comment by a8m** [comment]
Hey @darestrepov7 and thanks for raising up this issue. I need to add this question to our website documentation.

> We need to apply a way to order ents by edges and not just by fields (to be exact by some field of the ent that the edge point to).

The way I do it in ent, is by starting the traversal from the edge (I want to order by), apply the ordering, and then jumping to the neighbours (target type). For example:

```go
a8m := c.User.Create().SetName("Ariel").SaveX(ctx)
nati := c.User.Create().SetName("Neta").SaveX(ctx)
c.Pet.Create().SetName("Xabi").SetOwner(a8m).SaveX(ctx)
c.Pet.Create().SetName("Luna").SetOwner(nati).SaveX(ctx)

names := c.User.Query().
	Select(user.FieldName).
	StringsX(ctx)
fmt.Println(names)
// Output: [Ariel, Neta]

// Order by the "pets" edge.
names = c.Pet.Query().
	Order(ent.Asc(pet.FieldName)).
	QueryOwner().
	Select(user.FieldName).
	StringsX(ctx)
fmt.Println(names)
// Output: [Neta, Ariel]
```
 
Please let me know if it helps, and of course, we open for suggestions to improve the API. Thanks 🙏

**Comment by darestrepov7** [comment]
Ariel, we have seen the examples that you gave us, and definetely it is a field to explore. However, there is something important we'd like to comment related with the cursors we have in Symphony pages. 

We had also the idea of querying and sorting after the query based on the result, but we have to clarify the cursor is an impediment. Do you have an idea if we can attack this issue with your recommendation based on the fact we have cursors and pagination involved? 

Thanks!!

**Comment by a8m** [comment]
Hey @darestrepov7, let's continue the discussion privately on [Slack](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) or in Symphony repository as it's something specific to Symphony. Thanks 

cc @noamsch

**Comment by a8m** [comment]
@darestrepov7, I added the example above to the website btw - https://entgo.io/docs/paging/#edge-ordering

**Comment by darestrepov7** [comment]
@a8m could you please send us an invitation for the Slack workspace to manuel.alejandro.escorcia.jimenez@everis.com and diego.andres.restrepo.vera@everis.com?

Thanks

**Comment by a8m** [comment]
> @a8m could you please send us an invitation for the Slack workspace to [manuel.alejandro.escorcia.jimenez@everis.com](mailto:manuel.alejandro.escorcia.jimenez@everis.com) and [diego.andres.restrepo.vera@everis.com](mailto:diego.andres.restrepo.vera@everis.com)?
> 
> Thanks

Done
