### ISSUE TITLE
Generates failing query for SQLite in the presence of a self join + order

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [ent/ent#1265]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If I use a custom predicate to add filters based on a self-join (or really any table with overlapping column) and also do an order by, the generated query is perceived as valid by PostgreSQL, but not by SQLite.

## Expected Behavior 🤔

Column names in generated SQL should always be properly qualified so as to be unambiguous.

## Steps to Reproduce 🕹

Steps:

1. Define a model with, at minimum, an ID, a self-referential foreign key, and some other column that can be used for an `order by` clause
2. Run a query that uses a custom predicate joining across this foreign key
3. ... with an order by clause on that other column
4. ... on SQLite

My custom predicate looks roughly like this:
```go
func(s *sql.Selector) {
	t := sql.Table(myentity.Table).As("other")
	s.LeftJoin(t).On(s.C(myentity.OtherID), t.C(myentity.FieldID))
	s.Where(sql.Or(
		sql.IsNull(s.C(myentity.OtherID)),
		sql.NotNull(t.C(myentity.FlagColumn)),
	))
}
```
(semantically: looking for instances of my entity that either have no referenced other instance, or whose referenced instance has a flag value set. In reality the self-referential FK is representing a dependency chain among instances of the entity, and the flag column is indicating completion of the dependee)

The generated SQL looks roughly like this, reformatted for readability:
```sql
SELECT DISTINCT
  `myentity.id`.`id`,
  -- rest of the columns
FROM `myentity` LEFT JOIN `myentity` AS `other` ON `myentity`.`other_id` = `other`.`id`
WHERE (`myentity`.`other_id` IS NULL OR `other`.`flag` IS NOT NULL)
ORDER BY `some_other_column` ASC
LIMIT 1
```

PG is fine with this, but SQLite complains: `ambiguous column name: some_other_column`.

I tried to replace `Order(ent.Asc(myentity.SomeOtherColumn))` with `Order(ent.Asc(myentity.Table + "." + myentity.SomeOtherColumn))` to get it to generate `ORDER BY myentity.some_other_column ASC`, but that then just has ent telling me that the qualified column name is invalid.

Why am I doing this with a custom predicate like this, and not something more like `HasOtherWith(myentity.FlagIsNotNil())` ... well, because `HasRelationWith` generates an incredibly inefficient query, that looks like: `where myentity.other_id in (select id from myentity where flag is not null)` -- note that, despite this being a O2O relation, it doesn't use that fact to optimize the sub-select. It instead instructs the DB to query every possible instance that has the flag set. This results in something akin to a huge cross-join that is quite unnecessary.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.6.0   |
| Database    | SQLite   |
| Driver      | https://github.com/mattn/go-sqlite3        |

**Comment by mgabeler-lee-6rs** [comment]
Workaround: pass my own `func` to `Order` that does the same thing as `ent.Asc`, but without the column name verification, and with the manual table name qualification.

**Comment by a8m** [comment]
Hey @mgabeler-lee-6rs, this issue was fixed with https://github.com/ent/ent/pull/1404.

Just note that the signature of your custom order function should be changed from `func (*sql.Selector, func() bool)` to `func (*sql.Selector)`.

Closing, but please reopen if you still have issues with it. Thanks for reporting this 🙏

**Comment by mgabeler-lee-6rs** [comment]
Actually in my case I can get rid of the custom ordering func and just use `ent.Asc` :grinning:

Thanks!

**Comment by a8m** [comment]
Great. Thanks again for the detailed reporting 😃
