### ISSUE TITLE
can ent support for go build tags

### ISSUE THREAD

**Issue by godcong** [ent/ent#1266]
I use remote and local databases to manage my data.
Some of these data sheets are the same, some are different.
If ent can support go's `build tags`, so I can directly compile the client and server through the `build tags`

- [X ] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

If I add a `tag` used `ent init`, the generated code should be commented accordingly.
```go
//+build tags
package xxx
....
```

## Motivation 🔦

I want to manage both local and remote data tables, but now I don't know how to do it.

**Comment by a8m** [comment]
Hey @godcong 😃 

Build tags are not support atm, but I'm pretty sure we can support this. Can you elaborate more on your use case? Are we talking about build-tags on the schema package or on the generated assets?

**Comment by godcong** [comment]
We are used a distributed system
Our architecture is that the server and the client use the same set of codes
But the server will be marked in the node
Sometimes the client will request some data from the server
```go
type Information struct {
  //xxx
}

//only server has this table
type NodeInformation struct{
  ClientID int
  InformationID int
  //xxx
}
```
`Information` are both in server and client
`NodeInformation` was only created on the server
The server manages the `Information` that the client can obtain
`NodeInformation` needs to be managed separately on the server, but these tables do not need to be created on the client

I hope there is a way to distinguish between server and client
Not necessarily `go build tag`, but I think `go build tag` can solve my current problem very well

**Comment by godcong** [comment]
now, i had other ways to resolved this.

**Comment by a8m** [comment]
The issue was resolved with https://github.com/ent/ent/pull/2801. 

Thanks for suggesting this, @godcong.
