### ISSUE TITLE
create field with mysql point type data type

### ISSUE THREAD

**Issue by dara-na** [ent/ent#1269]
hello
one of my table fields type is Mysql 'point' type (location),
how can I define it with ent.Field ?

**Comment by 201RichK** [comment]
we don't quite understand your question, be clearer.

**Comment by Siceberg** [comment]
Spatial Data Types?
[https://dev.mysql.com/doc/refman/5.7/en/spatial-type-overview.html](url)

**Comment by a8m** [comment]
Hey all,
I created a sample repository to show how to use MySQL spatial data types with ent. I'll add this to our website, but for now, please see https://github.com/a8m/entspatial. TL;DR, you define a new type that implements the `ValueScanner` interface, and use it in your schema. For example:

A schema usage:
```go
// ent/schema/location.go

// Fields of the Location.
func (Location) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.Other("coords", &Point{}).
			SchemaType(Point{}.SchemaType()),
	}
}
```

And an implementation example: 
```go
// ent/schema/point.go

package schema

import (
	"database/sql/driver"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/paulmach/orb"
	"github.com/paulmach/orb/encoding/wkb"
)

// A Point consists of (X,Y) or (Lat, Lon) coordinates
// and it is stored in MySQL the POINT spatial data type.
type Point [2]float64

// Scan implements the Scanner interface.
func (p *Point) Scan(value interface{}) error {
	bin, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("invalid binary value for point")
	}
	var op orb.Point
	if err := wkb.Scanner(&op).Scan(bin[4:]); err != nil {
		return err
	}
	p[0], p[1] = op.X(), op.Y()
	return nil
}

// Value implements the driver Valuer interface.
func (p Point) Value() (driver.Value, error) {
	op := orb.Point{p[0], p[1]}
	return wkb.Value(op).Value()
}

// FormatParam implements the sql.ParamFormatter interface to tell the SQL
// builder that the placeholder for a Point parameter needs to be formatted.
func (p Point) FormatParam(placeholder string, info *sql.StmtInfo) string {
	if info.Dialect == dialect.MySQL {
		return "ST_GeomFromWKB(" + placeholder + ")"
	}
	return placeholder
}

// SchemaType defines the schema-type of the Point object.
func (Point) SchemaType() map[string]string {
	return map[string]string{
		dialect.MySQL: "POINT",
	}
}
```

Closing, but please reopen if you need further help with this. Thanks 🙏

**Comment by dara-na** [comment]
> Hey all,
> I created a sample repository to show how to use MySQL spatial data types with ent. I'll add this to our website, but for now, please see https://github.com/a8m/entspatial. TL;DR, you define a new type that implements the `ValueScanner` interface, and use it in your schema. For example:
> 
> A schema usage:
> 
> ```go
> // ent/schema/location.go
> 
> // Fields of the Location.
> func (Location) Fields() []ent.Field {
> 	return []ent.Field{
> 		field.String("name"),
> 		field.Other("coords", &Point{}).
> 			SchemaType(Point{}.SchemaType()),
> 	}
> }
> ```
> 
> And an implementation example:
> 
> ```go
> // ent/schema/point.go
> 
> package schema
> 
> import (
> 	"database/sql/driver"
> 	"fmt"
> 
> 	"entgo.io/ent/dialect"
> 	"entgo.io/ent/dialect/sql"
> 	"github.com/paulmach/orb"
> 	"github.com/paulmach/orb/encoding/wkb"
> )
> 
> // A Point consists of (X,Y) or (Lat, Lon) coordinates
> // and it is stored in MySQL the POINT spatial data type.
> type Point [2]float64
> 
> // Scan implements the Scanner interface.
> func (p *Point) Scan(value interface{}) error {
> 	bin, ok := value.([]byte)
> 	if !ok {
> 		return fmt.Errorf("invalid binary value for point")
> 	}
> 	var op orb.Point
> 	if err := wkb.Scanner(&op).Scan(bin[4:]); err != nil {
> 		return err
> 	}
> 	p[0], p[1] = op.X(), op.Y()
> 	return nil
> }
> 
> // Value implements the driver Valuer interface.
> func (p Point) Value() (driver.Value, error) {
> 	op := orb.Point{p[0], p[1]}
> 	return wkb.Value(op).Value()
> }
> 
> // FormatParam implements the sql.ParamFormatter interface to tell the SQL
> // builder that the placeholder for a Point parameter needs to be formatted.
> func (p Point) FormatParam(placeholder string, info *sql.StmtInfo) string {
> 	if info.Dialect == dialect.MySQL {
> 		return "ST_GeomFromWKB(" + placeholder + ")"
> 	}
> 	return placeholder
> }
> 
> // SchemaType defines the schema-type of the Point object.
> func (Point) SchemaType() map[string]string {
> 	return map[string]string{
> 		dialect.MySQL: "POINT",
> 	}
> }
> ```
> 
> Closing, but please reopen if you need further help with this. Thanks

thanks that worked pretty good
