### ISSUE TITLE
go generate ./... does not generate graphql files

### ISSUE THREAD

**Issue by 201RichK** [ent/ent#1270]
by following the 3 steps mentioned in the documentation,
after having typed the command go generate ./... according to the docs we should have the different gqlgen files, which is not the case.

in my case I followed the different steps of the docs in particular the three steps mentioned to activate the extension entc.

after the command go generate ./... we must have the different files of the graphql module which is not the case.

I followed these three steps

1. Create a new Go file named ent/entc.go, and paste the following content:
2. Edit the ent/generate.go file to execute the ent/entc.go file
3. Run codegen for your ent project

## Your Environment 🌎 windows 10

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.?  |
| Ent         | 0.6.0   |
| Database    | Postgresql|

**Comment by a8m** [comment]
Hey @201RichK, can you please share a temporary repository for checking your issue? You can also give a look to the [graphql todo example](https://github.com/ent/contrib/tree/master/entgql/internal/todo) and see if that works for you.

**Comment by 201RichK** [comment]
here is my code [https://github.com/201RichK/graphql_test](https://github.com/201RichK/graphql_test),  what I also noticed is that after typing the command go generate it doesn't import the files automatically, I mean gqlgen, so I have to type the command go mod tidy afterwards.

**Comment by a8m** [comment]
The repository looks fine except a few things that are missing - [GraphQL schema](https://github.com/ent/contrib/blob/master/entgql/internal/todo/todo.graphql), the [gqlgen config file](https://github.com/ent/contrib/blob/master/entgql/internal/todo/gqlgen.yml), and [another file](https://github.com/ent/contrib/blob/master/entgql/internal/todo/gen.go#L17) for telling `go generate` to execute gqlgen. 

Let me know if you still need help with this or I can close this issue.

**Comment by 201RichK** [comment]
that work, thanks for your answer
