### ISSUE TITLE
how store uuid.hex (string) rather than uuid 

### ISSUE THREAD

**Issue by Ackerr** [ent/ent#1272]
I try to add a UUID field to my schema
```
func (Demo) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("uuid", uuid.New()).Default(uuid.New)
	}
}
```
After migrate，I find the field  is uuid type. But I want  string type, store uuid.hex.

Now I change field schema like this `field.String("uuid")`，But it cant use `Default(uuid.NewString)`, I must use `SetUUID(string)` when create.

Is there a better way to solve this?

**Comment by a8m** [comment]
Hey @Ackerr, you can use the `DefaultFunc` option in this case. Please see the [doc](https://entgo.io/docs/schema-fields/#default-values) or use this example:

```go
func (T) Fields() []ent.Field {
	return []ent.Field{
		field.String("uuid").
			DefaultFunc(uuid.NewString),
	}
}
```
