### ISSUE TITLE
question: order by json path

### ISSUE THREAD

**Issue by wroge** [ent/ent#1273]
Is there a way to sort on a JSON Path?

`SELECT id, name, age, meta FROM users ORDER BY meta ->> ? DESC`

```
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.Int("age"),
		field.JSON("meta", map[string]string{}),
	}
}

client.User.Query().Order(func(s *sql.Selector, check func(string) bool) {
  s.OrderBy(...)
})
```

Thanks!

**Comment by wroge** [comment]
Sooo... I think it doesn't work with ent because you can't pass arguments to order..!?
```
type Selector struct {
	...
	order    []string
	...
}
```

**Comment by a8m** [comment]
Hey @wroge, and thanks for reporting this issue.

I'll give it a look.

BTW, this related to https://github.com/ent/ent/issues/1365

**Comment by a8m** [comment]
> Sooo... I think it doesn't work with ent because you can't pass arguments to order..!?

What database are you using? I'm not sure parameterized values are allowed for JSON path expressions in ORDER BY. 
Can you provide a raw SQL query (with `sql.DB`) that works for you?

**Comment by wroge** [comment]
I mostly use Postgres with pgx. I hope this example works for you.

```go
// docker run -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 postgres

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v4/pgxpool"
)

func main() {
	ctx := context.Background()

	pool, err := pgxpool.Connect(ctx, fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable",
		"localhost", "5432", "postgres", "mysecretpassword", "postgres"))
	if err != nil {
		panic(err)
	}
	defer pool.Close()

	_, err = pool.Exec(ctx, `CREATE TABLE IF NOT EXISTS my_table (id serial primary key, data jsonb);`)
	if err != nil {
		panic(err)
	}

	_, err = pool.Exec(ctx, `INSERT INTO my_table (data) VALUES ('{"hello":"world"}'),('{"hello":"earth"}');`)
	if err != nil {
		panic(err)
	}

	rows, err := pool.Query(ctx, `SELECT data FROM my_table ORDER BY data -> $1`, "hello")
	if err != nil {
		panic(err)
	}

	for rows.Next() {
		d := map[string]interface{}{}

		err = rows.Scan(&d)
		if err != nil {
			panic(err)
		}

		fmt.Println(d)
	}
}


// Output:
// map[hello:earth]
// map[hello:world]
```

**Comment by a8m** [comment]
Hey @wroge and thanks for sharing this example.

I've added a change (https://github.com/ent/ent/pull/1404) that should simplify the API for writing custom ordering functions.
I test your example on this repository and it works without any problems:

```go
client.User.Query().
	Unique(false).
	Order(func(s *sql.Selector) {
		s.OrderExpr(sql.Expr("t -> $1", param))
	}).
	AllX(ctx)
```

Closing this issue, but feel free to reopen it if you still have troubles with it. Thanks 🙏
