### ISSUE TITLE
Abbreviation of entity collides with id variable in query edge function

### ISSUE THREAD

**Issue by SogoCZE** [ent/ent#1276]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I have `ItemDocument` and `Item`, and the product can have many documents. So I have edge O2M (on `Item`). And the generator generate function `QueryItem` on **ItemDocumentClient** struct that function have a parameter `id *ItemDocument` and **id** is an abbreviation for **ItemDocument** but this collides with `id` variable in the function body. Causing rewriting of original ItemDocument (id) to database id (`id.ID`) which causes an error of undefined method on `id.driver.Dialect()`.

Generated function:

```go
// QueryProduct queries the product edge of a ItemDocument.
func (c *ItemDocumentClient) QueryItem(id *ItemDocument) *ProductQuery {
	query := &ItemQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := id.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(itemdocument.Table, itemdocument.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, itemdocument.ItemTable, itemdocument.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(id.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}
```

error: 

```
ent/client.go:405:32: id.driver undefined (type int has no field or method driver)
```

## Expected Behavior 🤔

abbreviation of entity struct won't collide with the id variable in `Query[Entity]` function.

## Steps to Reproduce 🕹

Steps:

1. define `Item` entity with an edge to entity `ItemDocument`

```go
[...]

// Edges of the Item.
func (Item) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("documents", ItemDocument.Type),
	}
}
```

2. define `ItemDocument` entity with an edge to `Item`

```go
[...]

// Edges of the ItemDocument.
func (ItemDocument) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("item", Item.Type).Ref("documents").Unique(),
	}
}
```

3. generate

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16 |
| Ent         | 0.6.0   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @SogoCZE and thanks for reporting this.

https://github.com/ent/ent/pull/1281 should solve the issue.
