### ISSUE TITLE
Does ent team consider to support the raw sql query or update?

### ISSUE THREAD

**Issue by EndlessIdea** [ent/ent#1277]

**Comment by a8m** [comment]
Hey @EndlessIdea,
Can you elaborate what do you mean by "raw query/statement", or provide some examples that are not supported and can't be implemented with [custom templates](https://entgo.io/docs/templates/)? Thanks 🙏

**Comment by Ackerr** [comment]
A example: https://github.com/ent/ent/issues/1278#issuecomment-787595034

**Comment by DanielTitkov** [comment]
Also interested in this. It could help with bulk upsert.

**Comment by owen-gxz** [comment]
@Ackerr @a8m Is there any way to solve it?



> sql like
> 
> ```
> update demo set code=CONCAT('9',  LPAD(type, 2, 0), LPAD(id, 12, 0)) where key='key'
> ```
> 
> 1.Does ent can use mysql buildin func like CONCAT，LAPD?
> 2.Is there any way to directly execute raw sql like sql.DB().Exec('sql')

**Comment by shenghui0779** [comment]
Also interested in this.

**Comment by a8m** [comment]
Hey all, this question was answered before in https://github.com/ent/ent/issues/708 and https://github.com/ent/ent/issues/85.

Please let me know if there's anything else we can help with.

**Comment by a8m** [comment]
Hey! I forgot to update this issue, but it was solved a long time ago. 
You can now use [SQL modifiers](https://entgo.io/docs/feature-flags#custom-sql-modifiers) or the [raw API](https://entgo.io/docs/feature-flags#sql-raw-api) to implement these use cases. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this 🙏
