### ISSUE TITLE
overriding primary_key column name

### ISSUE THREAD

**Issue by dara-na** [ent/ent#1282]
how to rename the "id" column name, provide my own PK column name?

**Comment by a8m** [comment]
Hey @dara-na 😃 

You can use the [field.StorageKey](https://entgo.io/docs/schema-fields/#storage-key) option. Please see an example in integration tests: 
https://github.com/ent/ent/blob/31ec081b0e0bb935626a7bbec6eebbaf4306cdce/entc/integration/config/ent/schema/user.go#L38-L39

Would you mind adding this question to the [FAQ page](https://entgo.io/docs/faq/) in our website? Thanks 🙏

**Comment by dara-na** [comment]
Sure ... That would be a pleasure
