### ISSUE TITLE
proposal: Protobuf + gRPC <> Ent interop

### ISSUE THREAD

**Issue by rotemtam** [ent/ent#1283]
Allow for interoperability between ent and protobuf/gRPC:
* Generation of `.proto` files from an `ent` schema 
* Generation of a gRPC service definition for a basic CRUD server using the generated protobuf messages
* Generate a go implementation of the gRPC service
* Generation of `ent` schema from  `.proto` files

- [X] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Status
This is a WIP. I've started working on the implementation of `.proto` file generation and looking for feedback. Will update the design on the other parts soon. 

## Summary 💡

1. Implement a new cli tool `entproto` under [ent/contrib](https://github.com/ent/contrib) that takes an `ent` schema directory as an input and outputs `.proto` files. In a new package `entproto` add new annotations to provide necessary mappings between ent and proto (defining stable field numbers, for example). 
2. Add to `entproto` the capability to output a gRPC service definition with basic `Add`, `Delete`, `Get`, `Put`, and `List` methods.
3. Create a tool (TBD whether code gen or a runtime library) to generate a golang gRPC
4. Implement a protoc plugin `protoc-gen-ent` ([example](https://medium.com/@tim.r.coulson/writing-a-protoc-plugin-with-google-golang-org-protobuf-cd5aa75f5777)) that outputs `.go` files with `ent.Schema`s representing the input proto files. 

## Motivation 🔦
Many organizations use protobuf as their IDL. gRPC is becoming increasingly popular as an RPC transport due to its efficiency and code-generation capabilities. Data access in the protobuf/gRPC world is currently the wild west. Allowing programmatic interoperability between ent and proto/gRPC would open up many possibilities for both ecosystems.

### .proto file generation

By default, `entproto` will skip all schemas, unless they explicitly opt-in for proto file generation:
```go
type User struct {
	ent.Schema
}

func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{entproto.Message()}
}
```
By default the proto package name for the generated files will be `entpb` but it can be specified using a functional option:
```go

func (MessageWithPackageName) Annotations() []schema.Annotation {
	return []schema.Annotation{entproto.Message(
		entproto.PackageName("io.entgo.apps.todo"),
	)}
}
```

#### Field Annotations
All fields must be annotated with `entproto.Field` to specify their proto field numbers
```go
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").Annotations(entproto.Field(2)),
	}
}
```
The ID field is added to the generated message as well, in the above example it is implicitly defined, but `entproto` will respect explicitly defined ID fields as well. The above schema would translate to:
```proto
message User {
  int32 id = 1;
  string name = 2
}
```
Field type mappings:

Ent Type | Proto Type | More considerations
-- | -- | --
TypeBool | bool |  
TypeTime | google.protobuf.Timestamp |  
TypeJSON | X |  
TypeUUID | X |  
TypeBytes | bytes |  
TypeEnum | Enum | Proto enums like proto fields require stable numbers to be assigned to each value. Therefore we will need to add an extra annotation to map from field value to tag number.
TypeString | string |  
TypeOther | X |  
TypeInt8 | int32 |  
TypeInt16 | int32 |  
TypeInt32 | int32 |  
TypeInt | int32 |  
TypeInt64 | int64 |  
TypeUint8 | uint32 |  
TypeUint16 | uint32 |  
TypeUint32 | uint32 |  
TypeUint | uint32 |  
TypeUint64 | uint64 |  
TypeFloat32 | float |  
TypeFloat64 | double |  
  |   |  

Validations:
* Field number 1 is reserved for the ID field
* No duplication of field numbers (this is illegal protobuf)
* Only supported ent field types are used

#### Edges
Edges are annotated in the same way as fields: using `entproto.Field` annotation to specify the field number for the generated field. Unique relations are mapped to normal fields, non-unique relations are mapped to `repeated` fields. 
For example:
```go
func (BlogPost) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("author", User.Type).Unique().Annotations(entproto.Field(4)),
		edge.From("categories", Category.Type).Ref("blog_posts").Annotations(entproto.Field(5)),
	}
}

func (BlogPost) Fields() []ent.Field {
	return []ent.Field{
		field.String("title").Annotations(entproto.Field(2)),
		field.String("body").Annotations(entproto.Field(3)),
	}
}
```
Is transformed to:
```proto
message BlogPost {
  int32 id = 1;
  string title = 2;
  string body = 3;
  User author = 4;
  repeated Category categories = 5;
}
```

Validation:
Cyclic dependencies are not supported in protobuf - so back references can only be supported if both messages are output to the same proto package. (In the above example, `BlogPost`, `User` and `Category` must be output to the same proto package).

### gRPC service definition 
To facilitate simple bootstrapping of application servers from the proto schema, `entproto` should support generation of a CRUD gRPC `service` definition from each `ent.Schema`. To request the generation of a gRPC service definition, a developer would annotate the schema with:
```go
func (BlogPost) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(
			entproto.GenerateService(),
		),
	}
}
```
The proto generation creates a service named `BlogPostService` with 4 methods:
```proto
service BlogPostService {
  rpc Create ( CreateBlogPostRequest ) returns ( BlogPost );

  rpc Get ( GetBlogPostRequest ) returns ( BlogPost );

  rpc Update ( UpdateBlogPostRequest ) returns ( BlogPost );

  rpc Remove ( RemoveBlogPostRequest ) returns ( google.protobuf.Empty );
}
```
and generates the supporting input/output message types: 
```proto

message CreateBlogPostRequest {
  BlogPost blog_post = 1;
}

message GetBlogPostRequest {
  int32 id = 1;
}

message UpdateBlogPostRequest {
  BlogPost blog_post = 1;
}

message DeleteBlogPostRequest {
  int32 id = 1;
}
```
The type of the `id` field for `Get` and `Delete` requests is determined from the `gen.Type.ID` field type. 

### gRPC service implementation
TBD

### proto -> ent import
TBD

**Comment by kayamax** [comment]
implementation of interface hooks for pre and post crudl to add custom handling will be great.
fyi. https://github.com/infobloxopen/protoc-gen-gorm

**Comment by tmc** [comment]
I'd consider using the https://google.aip.dev/133 standards for method naming here.

**Comment by rotemtam** [comment]
Thanks @tmc and @kayamax . I will definitely look into this

**Comment by tmc** [comment]
I'm interested in this sort of interoperability. There's been a bit of discussion on slack and I'd love to have more.

**Comment by a8m** [comment]
@rotemtam, can we close this issue?
