### ISSUE TITLE
Cannot add a field type of float with 0 as default value

### ISSUE THREAD

**Issue by HarikiRito** [ent/ent#1284]
- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Add a field type of float with 0 as the default value make the migration fail. 

## Expected Behavior 🤔

It's should migrate with no problem

## Steps to Reproduce 🕹

Steps:

1. Add a float field `field.Float("point").Default(0)`
2. Run `go run entgo.io/ent/cmd/ent generate --feature privacy ./ent/schema`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.5  |
| Ent         | 0.6.0   |
| Database    | Postgres   |

**Comment by rotemtam** [comment]
Hey @HarikiRito,
I tried reproducing this on my local machine and it seems to work fine. Can you share more details on the current behavior? Specifically a stack trace on the error, and if you can share an example schema it will also be helpful.

**Comment by HarikiRito** [comment]
@rotemtam I believe the cause of this problem is when schema generate it doesn't have a "Default" field. And I'm using postgres:13.1 docker container
![post](https://i.imgur.com/qPVvhRI.png)
![post](https://i.imgur.com/2UEzZ4c.png)

Here is the error message when I run the app

`alter table "posts": ERROR: column "actual_point" of relation "posts" contains null values (SQLSTATE 23502)`

**Comment by a8m** [comment]
Thanks for reporting this @HarikiRito 🙏 

#1287 fixed the issue. Closing
