### ISSUE TITLE
[Regression] Cannot specify primary id as a foreign key

### ISSUE THREAD

**Issue by marwan-at-work** [ent/ent#1288]
I have two tables: users and metadata. There's a one-to-one relationship between the two tables. However, the foreign key is the primary ID itself. So for example, a user with ID = 4 corresponds to a metadata row with id = 4 as well.

This is how I've described it in ent schema: 

```golang
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("name"),
	}
}
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("metadata", Metadata.Type).
			Unique().
			StorageKey(edge.Column("id")),
	}
}

func (Metadata) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.Int("age"),
	}
}
func (Metadata) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", PkgVersion.Type).
			Ref("metadata").
			Unique(),
	}
}
```

There are a couple of issues here: 

1. The migration tries to specify the "id" column twice ending up in an error of trying to create two columns with the same name.
2. Querying User or Metadata and calling the eager loading method such as `.WithMetadata()` ends up with the following error: https://github.com/ent/ent/blob/31bee1094209138372c85a02b1c8b9fd388c6114/entc/gen/template/dialect/sql/query.tmpl#L351 (this used to work before but it has regressed in the latest version from master.) 

Personally, I am more blocked by issue 2 since we manage our own migrations at my company. 

For issue 2, digging through the code, I see that it thinks a foreign key should be a separate column so when the "id" column goes through the loop of `scanValues`  and `assignValues` methods of a type, the foreign key gets skipped. 

Thanks!

**Comment by a8m** [comment]
Hello @marwan-at-work 👋 
Thanks for reporting this. It's a bit surprising to hear that it was supported before.

https://github.com/ent/ent/pull/1289 should solve the problem, but probably need more coverage.

**Comment by a8m** [comment]
@marwan-at-work, #1289 was merged. Please update your version to latest and let me know if that solves your problem. 
Keeping it open for now.

**Comment by marwan-at-work** [comment]
Thanks @a8m for the fix. Here's a similar issue that I've ran into: https://github.com/marwan-at-work/entrepro/tree/actor

It ends up creating Go code that doesn't compile. You can try to run `go build ./...` in the branch above to see the error. 

Thanks!

**Comment by a8m** [comment]
Talked to @marwan-at-work and issue was resolved.

Closing. Thanks @marwan-at-work for reporting this issue and helping designing a clean solution for it.
