### ISSUE TITLE
how to use buildin function like Date()

### ISSUE THREAD

**Issue by Ackerr** [ent/ent#1292]
example sql like 
```
SELECT (Date(created_at)) AS `date`, COUNT(id) AS count FROM demo WHERE uid IN (1,2,3) GROUP BY (Date(created_at));
```
And is there any way to directly execute raw sql like sql.DB().Exec('sql')

**Comment by masseelch** [comment]
I do not think it is possible. You can open a connection with standard `sql` package and afterwards hook that up with ent. Raw sql can then be run against the db like you usually do.

```go
import "entgo.io/ent/dialect/sql"

driver, err := sql.Open("mysql", util.MysqlDSN())
if err != nil {
	panic(err)
}
defer driver.Close()

driver.DB().Exec('sql')
```
