### ISSUE TITLE
StructTag("") no longer removes the comment entirely.

### ISSUE THREAD

**Issue by imle** [ent/ent#1294]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using `StructTag("")` prior to v0.6.0, this would remove the struct tag entirely.

## Expected Behavior 🤔

Struct tag is set to the default `` `json:"thing,omitempty"` ``

## Steps to Reproduce 🕹

Steps:

1. run `ent init Thing`
2. add `[]ent.Field{field.String("thing")}` to Fields
3. run `go generate ./ent`
4. view `./ent/thing.go`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.0  |
| Ent         | 0.6.0   |
| Database    | Postgres   |
| Driver      | https://github.com/lib/pq        |

**Comment by imle** [comment]
I realize now that specifying `` `json:"-"` `` would be more correct for the behavior I am looking for, however, this was previously something you could do.

**Comment by a8m** [comment]
Hey @imle and thanks for reporting this issue. 
I'm not able to reproduce this issue on v0.5.0 and v0.6.0, but like you said, the `json:"-"` option is the right way to go, if you want to explicitly remove the field from marshal/unmarshal.

**Comment by a8m** [comment]
Any update on this @imle? Can we close this issue?

**Comment by imle** [comment]
Good to close this, sorry for not doing so when I made the second comment. I think I may have been misremembering, the previous code I wrote that did that was likely not functioning as expected.

**Comment by a8m** [comment]
> Good to close this, sorry for not doing so when I made the second comment. I think I may have been misremembering, the previous code I wrote that did that was likely not functioning as expected.

👍
