### ISSUE TITLE
[question] Define unidirectional O2M

### ISSUE THREAD

**Issue by masseelch** [ent/ent#1301]
Is this possible? Docs don't say anything about it. 

```go
// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Media holds the schema definition for the Media entity.
type Media struct {
	ent.Schema
}

// Edges of the Media.
func (Media) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type)}
}

```
returns `entc/gen: missing reference name for inverse edge: Media.user`. So i guess this is not possible.

**Comment by a8m** [comment]
Hey @masseelch. It's great to see you here again 😃 

`edge.To("user", User.Type)` should solve the problem. Let me know if I can close the issue.

**Comment by masseelch** [comment]
Yes, this does solve the problem. However, this makes a bidirectional 02M-relation out of this. This does indeed include the requested unidirectional relation. Still, i was wondering if i can create a unidirectional relation. I might never ever use the reverse edge, so why define it?

**Comment by a8m** [comment]
> However, this makes a bidirectional 02M-relation out of this. 

This doesn't create an inverse edge (the back reference). Hence, it's one direction edge.

**Comment by masseelch** [comment]
Ha! `To`, not `From`. I see. Thank you very much :+1:
