### ISSUE TITLE
Default json-Tag on Edges field

### ISSUE THREAD

**Issue by masseelch** [ent/ent#1302]
- [x ] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Following #910 and the PR #1204 there are now default json tags on the edges struct. However a default `json:"edges,omitempty"` is still missing from the generated entity. I believe to have consistent behaviour this needs to be added. 

I removed the generated comments from the example to make it more clear.
```go
// Display is the model entity for the Display schema.
type Display struct {
	config `groups:"-" json:"-"`

	ID string `json:"id,omitempty"` // <- tag is added by default

	Edges          DisplayEdges  // <- I am missing a default tag for this field.
	group_displays *int
	group_media    *int
}

// DisplayEdges holds the relations/edges for other nodes in the graph.
type DisplayEdges struct {

	Group *Group `json:"group,omitempty"` // tag is added by default (since PR 1204)

	loadedTypes [1]bool
}
```

## Motivation 🔦

Reduce boilerplate.

**Comment by a8m** [comment]
Hey @masseelch, this can be done with the [`edge.Annotation`](https://pkg.go.dev/entgo.io/ent@v0.6.0/schema/edge#Annotation) option. Please see this example: https://github.com/ent/ent/blob/31bee1094209138372c85a02b1c8b9fd388c6114/entc/integration/ent/schema/card.go#L23-L25

**Comment by masseelch** [comment]
Yes i know. But like in #910 I propose to add this tag by default. If there is too much to do on other stuff i can try to implement it and file an PR.

**Comment by a8m** [comment]
Yeah, but this was added. See my comment - https://github.com/ent/ent/issues/910#issuecomment-766165744

Do I miss something?

**Comment by masseelch** [comment]
Your PR (#1204 ) adds default tags to the fields on an edge. 

```go
type DisplayEdges struct {
	Group *Group `json:"group,omitempty"` // <- This tag is added by the PR #1204 
}
```

There is no default tag on the `Edges` field on the generated Entity. 

```go
type Display struct {
	Edges DisplayEdges  // <- This field does not have a default json tag. 
}
```

So, this:

```go
type Display struct {
	ent.Schema
}

// Edges of the Display.
func (Display) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("group", Group.Type).
			Ref("displays").
			Unique(),
	}
}
```

should generate this:
```go
type DisplayEdges struct {
	Group *Group `json:"group,omitempty"`
}

type Display struct {
	Edges DisplayEdges `json:"edges,omitempty"`
}
```

**Comment by a8m** [comment]
What version do you use? See example in the repo:

https://github.com/ent/ent/blob/dd4792f5b30bdd2db0d9a593a977a54cb3f0c1ce/examples/start/ent/car.go#L30

**Comment by masseelch** [comment]
Version:
![image](https://user-images.githubusercontent.com/12862103/109832589-c7657b80-7c40-11eb-9aac-dee47f422025.png)

-----

### Found the error now! 

When defining my schema like this:

```go
type Display struct {
	ent.Schema
}
func (Display) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").StructTag(`foo:"bar"`),
	}
}
func (Display) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("group", Group.Type).Ref("displays").Unique().StructTag(`foo:"bar"`),
	}
}
func (Display) Annotations() []schema.Annotation {
	return []schema.Annotation{
		edge.Annotation{
			StructTag: `foo:"bar"`,
		},
	}
}
```
This gets generated:
```go
type Display struct {
	Name string `json:"name,omitempty" foo:"bar"` // <- There is a json tag
        Edges          DisplayEdges `foo:"bar"` // <- Here the StructTag annotation removes the default json-tag
}
type DisplayEdges struct {
	Group *Group `json:"group,omitempty" foo:"bar"` // <- json tag is here
}
```
There always is a `json`-tag on schema-fields and edge-fields. Adding an `edge.Annotation` removes the json-tag.

**Comment by a8m** [comment]
Yes. The `StructTag` annotation overrides the default struct-tag because it's static for the `Edges` struct field.

**Comment by masseelch** [comment]
Is this behavious changeable to match that of the fields?

**Comment by a8m** [comment]
Can you elaborate what are you trying to achieve?

**Comment by masseelch** [comment]
I think its counter intuitive that the `StructTag` annotation behaves differently than the `StructTag()`-method on `ent.Field` and `ent.Edge`. 

So i propose to make all 3 `StructTag`s behave the same. Either all override the default tag or all of them merge the given tag with the default `json`-tag. 

I don't know if this counts as BC (but i think it does), but it is confusing, especially for new users.

**Comment by a8m** [comment]
Fixed with #1315.

Thanks @masseelch for suggesting this change 🙏

**Comment by masseelch** [comment]
Ah nice! Thanks for the fast implementation! 

No problem. I will continue to suggest things i find unclear or missleading :wink:

**Comment by masseelch** [comment]
I still have one suggestion though.

In my case i strip down the queried entities by some serilization groups. Meaning in my case the `EntityEdges`-field on a `Entity`-Schema can be a `zero-value` / `nil`. So i need the `json`-tag to be `json:"edges,omitempty"`. 

Currently `ent` generates `json:"edges"` only. This is indeed more correct than `json:"edges,omitempty"`, since the `Edges` field cannot be zero / nil in the generated struct. 

On the other hand the `json:"edges,omitempty"` does not hurt, other than being redundant in most cases. What is your opinion on this?

**Comment by a8m** [comment]
> On the other hand the json:"edges,omitempty" does not hurt, other than being redundant in most cases. What is your opinion on this?

I'm not sure I understand why, because the `omitempty` option will never omit the `Edges` field, since it will never have the zero value. Do I miss something? 

BTW, if you want to drop this field in JSON marshalling, you can use `json:"-"` in the annotation.

**Comment by masseelch** [comment]
I want to conditionally marshal some of the edges of an entity. I walk down the tree and starting form the leafs remove everything not needed based on some condition. The result is a big anonnymous struct with its fields and `json`tags inherited by the orignal tree.

That struct is then marshalled.

Sometimes i end up with an Entity where there are no edges left to marshal I still end up with this in my JSON: `"{"id":1,"edges":{}}"` even though `edges` has no loaded entites attached. 

I can easily go around this with the `edge` Annotation. But this might be a very special case and most of the users will never need it.
