### ISSUE TITLE
Unable to use field.Other and entgql.OrderField annotation together

### ISSUE THREAD

**Issue by enjoylife** [ent/ent#1303]
With the introduction of the `OtherField` type in #1218, it opens up custom types and works well, but doesn't yet compose well with the entgql annotations. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Unable to use `field.Other` and `entgql.OrderField` annotation, due to the `Comparable` method not respecting `TypeOther`.  Digging into the codebase shows that the annotation, [checks](https://github.com/ent/contrib/blob/6623819401500db45747a2419172963217cef619/entgql/template/pagination.tmpl#L217) if the type is comparable. This [method](https://github.com/ent/ent/blob/3ee6621194709db97e53f8ee6888593e156acc5e/schema/field/type.go#L126) doesn't have a case for handling these custom types. 

What happens is the codegen fails

```
running ent codegen: execute template "pagination": template: template/pagination.tmpl:218:6: executing "pagination" at
 <fail (printf "annotated field %s.%s must be comparable" $node.Name $f.Name)>: error calling fail: annotated field Thing.custom_created_time must be comparable
exit status 1
```
## Expected Behavior 🤔
The other codegen completes when using `field.Other(...).Annotations(entgql.OrderField(...))` . Perhaps it requires an interface the `otherType` neees to satisfy but nonetheless I would hope we could combine these two features, `field.Other` and `entgql.OrderField`.

## Steps to Reproduce 🕹

Steps:

1. Use an other field with the order field   annotation: `field.Other("custom_field", pkg.CustomType).  Annotations(entgql.OrderField("CUSTOM_FIELD"))`
2. run go generate

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.5  |
| Ent         | 0.6   |
| Database    | Postgres   |

**Comment by a8m** [comment]
Thanks @enjoylife for reporting this issue. I'll comment on #1304
