### ISSUE TITLE
Dependency injection for privacy rules

### ISSUE THREAD

**Issue by dilipkk-foyernet** [ent/ent#1306]
Hi,

How do we inject dependencies into privacy rules?  We want to call some external services ([casbin](https://github.com/casbin/casbin)) from the rule functions. How to do that? One approach we can find is putting them to the context object but that is a bit cumbersome process.

Thanks,
Dilip

**Comment by rotemtam** [comment]
Hey @dilipkk-foyernet,
Can you explain a bit more about what you're trying to do? It sounds like you could use closures ([example](https://gobyexample.com/closures)) to return a function that has access to `casbin`, but if you share a code example of where you're stuck it will be easier to assist.

**Comment by dilipkk-foyernet** [comment]
Thanks @rotemtam  for the quick response. Yes, I am aware of the closures but the problem here is ent is injecting privacy rules into ent/runtime/runtime.go while generating the code from schema so injecting static dependencies should be possible but my dependencies will be available when the app starts so I am too sure how to approach this.

```go
// Rule
func FilterProjectRule() privacy.QueryRule {
	type ProjectFilter interface {
		WhereHasProjectWith(...predicate.Project)
	}
	return privacy.FilterFunc(func(ctx context.Context, f privacy.Filter) error {
		userScope := ctx.Value(constants.UserScopeContextKey).(types.UserAuthScope)
		tf, ok := f.(ProjectFilter)
		if !ok {
			return privacy.Denyf("unexpected filter type %T", f)
		}
		tf.WhereHasProjectWith(project.IDEQ(userScope.ProjectID.ID))
		return privacy.Skip
	})
}


// Policy of the project-mixin.
func (ProjectMixin) Policy() ent.Policy {
	return privacy.Policy{
		Query: privacy.QueryPolicy{
			rule.FilterProjectRule(),
		},
		Mutation: privacy.MutationPolicy{
			rule.MutationProjectRule(),
		},
	}
}
```
This statically generates right? how can inject dynamic dependencies here into tule functions?

**Comment by a8m** [comment]
Hey hey @dilipkk-foyernet. It's great to see you here again 😃 

Like you mentioned above, you can pass these dependencies on the `context.Context`, or you can attach them to all generated builders using templates. I created an example commit to show how to do it (https://github.com/ent/ent/commit/a21d8fe3b60643bb1cbea5df23d49b7035c101a1) - I actually use it as well.

In short, the usage is as follows:

```go
c, err := ent.Open(..., ent.Casbin(...), ent.Cache(...), /* additional options */ )
// Then, you can access it from the privacy rules as follows:

// UseCasbinEnforcer is an example for a usage of casbin enforcer in a privacy policy rule.
func UseCasbinEnforcer() privacy.QueryRule {
	return privacy.UserQueryRuleFunc(func(ctx context.Context, q *ent.UserQuery) error {
		_ = q.Enforcer
		return privacy.Skip
	})
}
```

Let me know if you need more help with this.

**Comment by dilipkk-foyernet** [comment]
Thanks a lot @a8m, I am also delighted to explore more features of this awesome package. Thanks a lot for your efforts on this.

**Comment by dilipkk-foyernet** [comment]
@a8m One small issue I am facing with this now, we are using github.com/casbin/casbin/v2 but in the generated file it is taking v1. Is there a workaround for it?

**Comment by a8m** [comment]
You can tell ent (goimports) what packages to import using the same technique. I've updated the branch, see https://github.com/ent/ent/commit/626b577b9f7aaf6067b54810d3f2cfc8c2c370e1

We need to add this to our FAQ page with some example. Feel free to contribute this, or I'll add this later this week.

**Comment by dilipkk-foyernet** [comment]
Worked like charm, Thanks again. I will add this to FAQ soon.

**Comment by dilipkk-foyernet** [comment]
https://github.com/ent/ent/pull/1308
