### ISSUE TITLE
Use hook and mixin together causing cycle import

### ISSUE THREAD

**Issue by HarikiRito** [ent/ent#1307]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Go complain about cycle import when I use mixin with hook

## Expected Behavior 🤔

Should be used normally. Working on `github.com/facebook/ent v0.5.3`

## Steps to Reproduce 🕹
[Example repo here](https://github.com/HarikiRito/ent.go-error)
Steps:

1. Run `go run entgo.io/ent/cmd/ent init Test`
2. Create a mixin
3. Run `go:generate go run entgo.io/ent/cmd/ent generate ./schema`
4. Run `main.go`

## Your Environment 🌎
| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.5  |
| Ent         | 0.6.0   |
| Database    |   |
| Driver      |     |

**Comment by rotemtam** [comment]
Hey @HarikiRito ,
Thanks for this detailed issue report. I've tried to run generate locally on your repo but I'm getting:
```console
go: git.ntq.solutions/sayang-app/protos@v1.4.161: reading git.ntq.solutions/sayang-app/protos/go.mod at revision v1.4.161: unknown revision v1.4.161
```
I'm assuming this is a private repo that I don't have access to. Can you modify the repo so it only has public dependencies? 

In addition, can you please update your issue to include the error+stacktrace message you get when you hit this issue? 

Thanks

**Comment by HarikiRito** [comment]
@rotemtam 
I have updated the repo. Please check again.
Here is the stack trace I got
![abc](https://i.imgur.com/hpP1Ge3.png)

**Comment by rotemtam** [comment]
@HarikiRito , thanks for the quick response.
I'm able to reproduce it locally now, looking into it.

**Comment by rotemtam** [comment]
@HarikiRito ,

I think you omitted the registration of the hook from the CommonMixin, If I add it:
```go
func (CommonMixin) Hooks() []ent.Hook {
	return []ent.Hook{
		SampleHook(),
	}
}
```
and rerun `go generate ./...` , I see that some generated code changes significantly. I'm no expert on this, but I think the codegen deals with some runtime issues by using the list of registered hooks. This also changes `ent/test/test.go` to include this block:
```diff
+// Note that the variables below are initialized by the runtime
+// package on the initialization of the application. Therefore,
+// it should be imported in the main as follows:
+//
+//     import _ "abc/ent/runtime"
+//
 var (
+       Hooks [1]ent.Hook

```
As described in the docs for schema hook registration, https://entgo.io/docs/hooks/#hooks-registration, to make this work you need to import the runtime package to actually register all of this stuff. 

Let me know if this solves your issue

**Comment by HarikiRito** [comment]
@rotemtam Follow your instruction it's working but I encounter another problem. Should I open a new issue or just update this?

**Comment by HarikiRito** [comment]
My environment:
| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.5  |
| Ent         | 0.6.0   |
| Database    |  Postgres (docker postgres:13.1)  |
| Driver      |  [https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql](https://entgo.io/docs/sql-integration/#use-pgx-with-postgresql)   |



I have updated my code to perform a simple insert with Postgres and it's failed. Here is the stack trace.

<pre>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11cb710]

goroutine 1 [running]:
abc/ent.(*TestCreate).defaults(0xc0000703c0)
        /Users/hau.nghiem/Documents/code/abc/ent/test_create.go:116 +0xf0
abc/ent.(*TestCreate).Save(0xc0000703c0, 0x14d68c0, 0xc0000a2000, 0xc00008e058, 0x0, 0x0)
        /Users/hau.nghiem/Documents/code/abc/ent/test_create.go:74 +0x65
main.main()
        /Users/hau.nghiem/Documents/code/abc/main.go:16 +0xcd
<pre>

**Comment by a8m** [comment]
Hey @HarikiRito, adding the following line to your imports (in `db/db.go`) should solve the problem:

```go
_ "abc/ent/runtime"
```

Please see the docs for [hooks/privacy registration](https://entgo.io/docs/hooks/#hooks-registration), but I agree that the panic/error message can be friendlier.

**Comment by HarikiRito** [comment]
It's working. I'll test my current project to see if anything happens. Thanks for your support.

**Comment by a8m** [comment]
Great.

Closing, but feel free to open if you need further help with it.
