### ISSUE TITLE
doc/website: add Crowdin support

### ISSUE THREAD

**Issue by uta-mori** [ent/ent#1322]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Set up ent document website built with docusaurus v1 so that it can be translated by **Crowdin**

> https://docusaurus.io/docs/en/translation

## Motivation 🔦

Translation of documents is in demand.(#1264  have already added Chinese translations)
I would also like to help translate it into Japanese.
However, Translation document in git is a lot of work, including keeping up with updates to the main doc.
Crowdin makes the work easier for both maintainers and contributors

**Comment by a8m** [comment]
Thanks @uta-mori for opening this issue.

I plan to start pushing it next week. I'll update then.

**Comment by uta-mori** [comment]
supported with #1391
