### ISSUE TITLE
question: edger-loading json omitempty

### ISSUE THREAD

**Issue by maxiloEmmmm** [ent/ent#1323]
@a8m  hello
with v0.6.0
eager-loading empty values will miss

```golang
//O2M M2M
WithX() 
// if not empty
{edges: {x: [{....}]}}
// if empty
{edges: {}}

// want
// if empty
{edges: {x: []}}
```

i see logic code
https://github.com/ent/ent/blob/c0fd7c1305f32af722041278277a85a4d4237304/entc/gen/type.go#L1487-L1491

how to generate code default without `omitempty`?
must i edit `StructTag(`json:"x"`)` on edges?

_Originally posted by @maxiloEmmmm in https://github.com/ent/ent/issues/790#issuecomment-793473761_

**Comment by a8m** [comment]
Hey @maxiloEmmmm,
If you eager-load the edges, their values won't be nil, even if no edges were found. For example:

```go
u := client.User.Query().FirstX(ctx)
fmt.Println(u.Edges.Pets == nil) // true.
u = client.User.Query().WithPets().FirstX(ctx)
fmt.Println(u.Edges.Pets == nil) // false.
```

However, according to the `encoding/json` GoDoc:

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string. 

That means, if you want to change this behaviour, you'll need to define the `json` struct-tag to all edges. You can do it in the schema like your mentioned or use a [codegen-hook](https://entgo.io/docs/code-gen/#code-generation-hooks) for adding it to all edges at once. 

Let me know if it helped and I can close this issue. Thanks

**Comment by maxiloEmmmm** [comment]
@a8m hi
i want `array` for frontend on O2M and M2M instead of `undefined` by default
i find `codegen-hook` can satisfy me that's great, thanks, but i think `omitempty` on O2M and M2M is superfluous

**Comment by a8m** [comment]
Thanks for the feedback 😃
