### ISSUE TITLE
Sorting by nested edges with pagination involved

### ISSUE THREAD

**Issue by darestrepov7** [ent/ent#1329]
Currently it is possible to order by a nested esdge like in the example above:

users, err := client.Pet.Query().
    Order(ent.Asc(pet.FieldName)).
    QueryOwner().
    All(ctx)

It is also possible to order by an edge when there is pagination involved. However, the functionality of sorting by a nested edge when there is pagination is not being covered. 

For example, if I want to sort the users owners by the Pet edge and I have a pagination defined in the execution of the query, ent is not allowing it.

**Comment by rotemtam** [comment]
@darestrepov7 i see a similar discussion was started on #1256 , is this the same question? 

Also, can you give an example of what you're trying to do and the error message you are receiving?

Thanks 🙏

**Comment by darestrepov7** [comment]
@rotemtam @a8m Yes it is the same functionality. We are trying to implement a sort in the View of projects in Symphony, but not by a project attribute, but by a project property. The limitation is the structure of the Pagination on that view.

![image](https://user-images.githubusercontent.com/70981298/111069334-92f08b80-849a-11eb-9703-d02f5099c172.png)

We have identified in the model that the properties are nodes nested to the projects by an edge:

![image](https://user-images.githubusercontent.com/70981298/111069470-30e45600-849b-11eb-828f-e34ea9d848b8.png)

We have found the specification of the entities Connection, used for Pagination in graphQL for ent, where it is clear that the ordering can only be defined on ent fields (no edges) [https://github.com/ent/ent/blob/41c3445b951e70e44a3914edf35b9e8ad2be1301/doc/md/graphql.md].

Hence, currently we have this coverage:

- Sorting by ent fields with Pagination. 
- Sorting by nested edge fields without pagination.

Gap: Sorting by nested edge fields with Pagination.

Thanks.

**Comment by frederikhors** [comment]
@darestrepov7, can I ask you how are you filtering rows with that bar in the screen? Is user typing something?

**Comment by a8m** [comment]
Hey! The issue was resolved. Check out [the announcement](https://twitter.com/entgo_io/status/1648035851085946880?s=20).


You can upgrade `ent/contrib` to v0.4.1 and check out the docs for examples: https://entgo.io/docs/tutorial-todo-gql-paginate#order-by-edge-count.
