### ISSUE TITLE
It is up to the caller to determine the query field

### ISSUE THREAD

**Issue by Naist4869** [ent/ent#1342]
thanks a lot for your work.

I'm using GORM currently.When I try to implement the interface, I don't know how to keep the correct In this situation.

For gorm. It is up to the caller to determine the query field
![image](https://user-images.githubusercontent.com/37408934/111436587-1c26ed00-873d-11eb-8adf-d17c2c8eb42c.png)

For ent. I should find all the use cases that call this function
![image](https://user-images.githubusercontent.com/37408934/111436627-2812af00-873d-11eb-8322-1f3ceed2a61c.png)

**Comment by a8m** [comment]
Hey @Naist4869

> I'm using GORM currently.When I try to implement the interface, I don't know how to keep the correct In this situation.

I'm not sure I really understand your question. From looking at your code, it looks fine. Can you elaborate on what are you missing there, or what's not working for you?

In ent, you don't get a `ent.NotFoundError` error if no records were found, you just get an empty list. However, you get such an error if you use `Only/First`, but you can check it with the `ent.IsNotFound` helper.

**Comment by Naist4869** [comment]
> Hey @Naist4869
> 
> > I'm using GORM currently.When I try to implement the interface, I don't know how to keep the correct In this situation.
> 
> I'm not sure I really understand your question. From looking at your code, it looks fine. Can you elaborate on what are you missing there, or what's not working for you?
> 
> In ent, you don't get a `ent.NotFoundError` error if no records were found, you just get an empty list. However, you get such an error if you use `Only/First`, but you can check it with the `ent.IsNotFound` helper.
Thanks @a8m 
![image](https://user-images.githubusercontent.com/37408934/111439023-e3d4de00-873f-11eb-88fe-27dc9db12954.png)

For Gorm. It will automatically ignore zero-valued fields build WHERE.
For Ent. I can only use a different method to set fields build WHERE.

I want the query field defined by the user like graphql in ent

**Comment by a8m** [comment]
OK, I got it. There 2 options on how to do it, because you don't want always to ignore the zero values on predicate (0, false, etc). Maybe using a pointer it's preferred here.

The first option is to check it in your GraphQL resolvers and just do it by yourself:

```go
var ps []predicate.ChannelConfig
if id := input.AppID; id != "" {
    ps = append(ps, channelfconfig.AppID(id))
} 
// ...
configs, err := client.ChannelConfig.Query().Where(ps...).All(ctx)
// ...
```

The second option is to use [external-templates](https://entgo.io/docs/templates/) to generate an API for accepting nil/zero values in the predicates and add them to the `Where` clause only if they are valid. 

If want to give a try to the second version, ping me on our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) and I can help you with this.

**Comment by Naist4869** [comment]
Yes, it seems that only the external-templates is what I want without reflection.
I'm English is not good. So I will try to solve it myself,And ask for help from the channel after failure.
Thank you very much.

**Comment by a8m** [comment]
Please don't hesitate to ping me privately on Slack.
