### ISSUE TITLE
Migration DROP INDEX, CREATE INDEX cycle

### ISSUE THREAD

**Issue by henrywoody** [ent/ent#1344]
I've noticed with a (unique) index on multiple fields that the migration code generated by ent continually cycles between dropping the index and creating the index. After creating the table/index, the next migration includes a line to drop the index. After dropping the index, the next migration includes a line to create the index the same as before. And so on.

I've noticed that this only seems to happen when supplying a custom table name for the model and specifically when that table name is just the singular form of the model name (as opposed to the plural form that ent produces by default). Without a custom table name or with a custom table name that is not just the singular form, the issue is not encountered.

Of course there may be other cases where the same behavior occurs, but this is what I've narrowed down so far.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Described above, but the generated migration code alternates between dropping and creating (unique) indices on multiple fields for a model when the model has a custom table name that is the singular form of the model name.

## Expected Behavior 🤔

Expect the migration code to contain a command to create the index and not contain commands to drop the index right after.

## Steps to Reproduce 🕹

Reproduction repo: https://github.com/henrywoody/ent-index-migration-test

Steps:

1. Create a model with a few fields and a unique index on those columns.
2. Give the model a custom table name that is the singular form of the model name (using `Config` method).
3. Generate migration (write to file).

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.6  |
| Ent         | 0.7.0   |
| Database    | Postgres   |
| Driver      | github.com/lib/pq |

**Comment by a8m** [comment]
I checked it on your example repository btw and it was fixed.

Please let me know if you still have any issue with it.

**Comment by henrywoody** [comment]
@a8m just tested it out and yeah works fine now, thanks for the quick turnaround!

Also your note that the issue pattern is just when the type name and table name match (ignoring case) makes much more sense. Found that the same issue would happen even without a custom table name supplied if the plural and singular of the model name match (e.g. Sheep).
