### ISSUE TITLE
can ent close the global json struct tag omitempty?

### ISSUE THREAD

**Issue by godcong** [ent/ent#1354]
- [X] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

When I generate go code, the json tag will automatically bring `emitempty`
Unless I specify `StructTag`
```
// Fields of the Scrap.
func (Scrape) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.Bool("check").Default(false).StructTag(`json:"check""`),  //<- specify struct tag
		field.String("comment").Default(""),
	}
}
```

```
type Example struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	Check bool `json:"check""`
	// Comment holds the value of the "comment" field.
	Comment string `json:"comment,omitempty"`
}
```

## Motivation 🔦

When I send a string of JSON data to the web side, some may have no value, but the field must exist.
The `omitempty` of json will cause the fields with no value to not be displayed. Although each field can be modified manually, it is very time-consuming.
Is there an option to turn off `omitempty` globally?

**Comment by a8m** [comment]
Hey @godcong! It's great to see you here again 😃 

There's no option to remove the `omitempty` tag using configuration, but you can use [codegen hooks](https://entgo.io/docs/code-gen/#code-generation-hooks) to modify all fields globally as follows:

```go
// +build ignore

package main

func main() {
	err := entc.Generate("./schema", &gen.Config{
		Hooks: []gen.Hook{TagFields("json")},
	}, opts...)
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}

// TagFields tags all fields defined in the schema with the given struct-tag.
func TagFields(name string) gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			for _, node := range g.Nodes {
				for _, field := range node.Fields {
					field.StructTag = fmt.Sprintf("%s:%q", name, field.Name)
				}
			}
			return next.Generate(g)
		})
	}
}
```

I added a working example to our repository https://github.com/ent/ent/pull/1356. Let me know if it does solve your problem.

**Comment by godcong** [comment]
Thank you, I have mastered a new piece of knowledge.
:)

**Comment by a8m** [comment]
😃 

Would you mind adding this question to our [FAQ page](https://entgo.io/docs/faq/)? Code is [here](https://github.com/ent/ent/blob/master/doc/md/faq.md). Thanks 🙏
