### ISSUE TITLE
Optional Scan Error

### ISSUE THREAD

**Issue by Naist4869** [ent/ent#1355]
```go
	field.Time("notify_time").Optional(),
	field.Uint32("fail_times").Optional(),
```

![image](https://user-images.githubusercontent.com/37408934/111761140-845f0580-88da-11eb-8cdb-252595900680.png)
### When I set optional fields, an error occurs when I go to Select And Scan
1. fail: sql/scan: failed scanning rows: sql: Scan error on column index 3, name "fail_times": converting NULL to uint32 is unsupported details = []
2. fail: sql/scan: failed scanning rows: sql: Scan error on column index 0, name "notify_time": unsupported Scan, storing driver.Value type <nil> into type *time.Time details = [] 

Does it mean that I should not use the optional options and should use the default values?
```go
		field.Time("notify_time").Default(func() time.Time {
			return time.Time{}
		}),
		field.Uint32("fail_times").Default(0),
```

**Comment by a8m** [comment]
Hey @Naist4869, you defined your fields twice: 


1\.
```go
field.Time("notify_time").
	Optional(),
field.Uint32("fail_times").
	Optional(),
```
2\.
```go
field.Time("notify_time").
	Default(time.Time)
field.Uint32("fail_times").
	Default(0)
```

Did you run the schema-migration after migrating from 1 to 2? BTW, can you please use latest master and report if you still get this:

```go
go get -u entgo.io/ent@master
```

**Comment by Naist4869** [comment]
Version : ![image](https://user-images.githubusercontent.com/37408934/111771697-f76e7900-88e6-11eb-9e42-dbf538ac6152.png)

migrate: ![image](https://user-images.githubusercontent.com/37408934/111772036-5d5b0080-88e7-11eb-906b-d946139aea04.png)

![image](https://user-images.githubusercontent.com/37408934/111772666-14577c00-88e8-11eb-9463-363cb379a06e.png)

**Comment by a8m** [comment]
Can you please provide a test repository to check this? Optional fields are working without any issues for me on the latest version.

**Comment by Naist4869** [comment]
How was your vacation? @a8m 
Here is a warehouse that reproduces the problem I encountered
[issue1355](https://github.com/Naist4869/awesomeProject1)
And a cute bug. lol 
![image](https://user-images.githubusercontent.com/37408934/111934945-67eee300-8afd-11eb-8714-eed1989dfcc1.png)

**Comment by a8m** [comment]
Hey @Naist4869,
I looked at your code and in [this line](https://github.com/Naist4869/awesomeProject1/blob/main/main.go#L44), you should either call `All(ctx)`, and ent will fill only the fields that were asked in `Select`. Or, use `sql.Null<T>` types, because some values are optional and can be "NULL" in the database. 

Besides this, everything works as expected. Let me know please if I can close this issue.
Thanks

**Comment by Naist4869** [comment]
![image](https://user-images.githubusercontent.com/37408934/112611624-09a56580-8e59-11eb-90b2-b4eb2e0561fe.png)
![image](https://user-images.githubusercontent.com/37408934/112611752-30639c00-8e59-11eb-89d6-cf0e14dd1f66.png)
I think the second is cooler than the first... But it work.
Thank you very much 谢谢
