### ISSUE TITLE
entgql order by ID

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1359]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```go
type IDMixin struct {
	mixin.Schema
}

func (IDMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").Unique().Immutable().Annotations(
			entgql.OrderField("Id"),
		),
	}
}
```

## Expected Behavior 🤔

Generate order by Id, but no

![image](https://user-images.githubusercontent.com/1777211/111871377-9cab4f00-89c4-11eb-94c6-6e6d6797b821.png)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.?  |
| Ent         | v0.7.0   |
contrib | v0.0.0-20210317163310-9c7274f43c18
| Database    | Mysql   |
| Driver      | n/a        |

**Comment by a8m** [comment]
Thanks for reporting this @wenerme.

I'll check this.

**Comment by a8m** [comment]
Thanks @alexsn for the fix ❤️
