### ISSUE TITLE
Bug: uuid.New as Default causing schema creation to fail

### ISSUE THREAD

**Issue by TomOperator** [ent/ent#1361]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

We use UUIDs as PKs within our schema like so:
```go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New). // <-- ISSUE
			Unique(),
	}
}
```

We then attempt to output the SQL for the above like so:
```go
if err := store.Client.Schema.WriteTo(context.Background(), os.Stdout, migrate.WithGlobalUniqueID(true)); err != nil {
	log.Fatalf(err)
}
```

Which ends up with the following error in our logs:
```
sql/schema: unsupported default type: [16]byte
```

It seems like `.Default(uuid.New)` is causing the issue. The `uuid.New` function returns a `[16]byte` UUID, which seems to be an issue when building the schema, resulting in the above error.

## Expected Behavior 🤔

We expect the SQL to be generated, appropriately representing the above data type for our ID.

## Steps to Reproduce 🕹

Above code sample should suffice to reproduce.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.2  |
| Ent         | 0.7.0   |
| Database    | Postgres   |
| Driver      | github.com/lib/pq        |

**Comment by TomOperator** [comment]
Minor note that everything else works with the above, and we're extremely grateful to @a8m for this package.

**Comment by a8m** [comment]
Hey @TomOperator and thanks for reporting this issue.
I created an example in integration-tests that works with UUID fields as unique identifiers without any issues. See https://github.com/ent/ent/pull/1362

However, note that [migrate.WithGlobalUniqueID(true)](https://entgo.io/docs/migrate/#universal-ids) was created for numeric-type identifiers and shouldn't be used in this example.

If this still doesn't work for you, please create an example repository to simulate this bug and paste here a link for it.


> Minor note that everything else works with the above, and we're extremely grateful to @a8m for this package.

Thanks for the kind words 🙏

**Comment by TomOperator** [comment]
Thanks @a8m - we removed the default, and for some reason still getting the same error. We'll investigate it further; closing this ticket.

**Comment by a8m** [comment]
Thanks for the update @TomOperator.
Please join our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) and feel free to ping me there privately if you have any troubles with it.
