### ISSUE TITLE
entproto: wrong codegen

### ISSUE THREAD

**Issue by egorsmkv** [ent/ent#1375]
entproto generates an incorrect field names for `user_id` field defined in `Fields()` function:

```go
// Fields of the Account.
func (Account) Fields() []ent.Field {
	return []ent.Field{
		field.Int("user_id").
			Unique().
			Annotations(
				entproto.Field(2),
			),
		field.String("code").
			Unique().
			Annotations(
				entproto.Field(3),
			),
	}
}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

entproto makes `UserId` field name in type definition but in functions it is `UserID`. Look on the following:

```go
type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code   string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
}
```

```go
// toProtoAccount transforms the ent type to the pb type (TODO: complete implementation)
func toProtoAccount(e *ent.Account) *Account {
	return &Account{
		Code:   string(e.Code),
		Id:     int32(e.ID),
		UserID: int32(e.UserID),
	}
}
```

## Expected Behavior 🤔

Correct codegen.

## Steps to Reproduce 🕹

1. Add `user_od` field
2. Run `go generate ./...`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.2  |
| Ent         | 0.7.0   |
| Database    | SQLite3   |
| Driver      | github.com/mattn/go-sqlite3        |

**Comment by rotemtam** [comment]
Thanks for reporting this, @egorsmkv !
I will look into this soon 🙏

**Comment by rotemtam** [comment]
@egorsmkv this is fixed on https://github.com/ent/contrib/pull/52, will be merged soon.

**Comment by egorsmkv** [comment]
Thanks for the bugfix!
