### ISSUE TITLE
entql FieldIn operation failed

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1376]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```go
query := client.User.Query()
query.Filter().Where(entql.FieldIn("username", "ROOT"))
fmt.Println(query.AllX(ctx))
```

__error__

```
    dialect.go:79: driver.Query: query=SELECT DISTINCT `username` FROM `users` WHERE `username` IN ? args=[ROOT]
--- FAIL: TestEntDBFunc (0.01s)
panic: near "?": syntax error [recovered]
	panic: near "?": syntax error
```

## Expected Behavior 🤔

works

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.7   |
| Database    | sqlite & pg   |

**Comment by a8m** [comment]
Thanks for reporting this @wenerme 🙏 

I sent a patch to fix this - see #1377.
