### ISSUE TITLE
json in mariadb migration

### ISSUE THREAD

**Issue by AnnatarHe** [ent/ent#1395]
create a column as `JSON` type in schema.go

and do migration in mariadb 10.3 twice

it will throw error like:
`failed creating schema resources: sql/schema: changing column type for "xxxxxxx" is invalid (json != longtext)`

I think it's a mariadb issue but ent framework should deal with it.

ref:
https://mariadb.com/kb/en/json-data-type/

And I think we should change those lines to fix this issue:
https://github.com/ent/ent/blob/b4ad29f7f3970687d4e583eb643356ea23a83f03/dialect/sql/schema/schema.go#L193

**Comment by rotemtam** [comment]
@AnnatarHe , what version of ent are you using? Can you supply a complete `schema` file and the code you're using to run the migration? 
I'm not sure also that 10.3 is supported by ent, afaik two latest versions are supported, @a8m ?

**Comment by AnnatarHe** [comment]
ent version:
entgo.io/ent v0.7.0

code:
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type AssetBundleContains struct {
	ent.Schema
}

// Fields of the AssetBundleContains.
func (AssetBundleContains) Fields() []ent.Field {
	return []ent.Field{
		field.Int("foo"),
		field.JSON("id_list", []int{}),
		field.Int("bar"),
	}
}

// Edges of the AssetBundleContains.
func (AssetBundleContains) Edges() []ent.Edge {
	return nil
}
```

**Comment by a8m** [comment]
Hey @AnnatarHe,
Can you please paste here the exact MariaDB version? You can get it by running:

```console
show variables like 'version';
```

> I'm not sure also that 10.3 is supported by ent, afaik two latest versions are supported, @a8m ?

@rotemtam, we run our integration-tests on `mariadb:10.2.32` as well, and there's a code that should handle these MariaDB versions in [schema/mysql.go](https://github.com/ent/ent/blob/305edd0/dialect/sql/schema/mysql.go#L560-L603).

**Comment by AnnatarHe** [comment]
hi @a8m ,
the result is: `10.3.13-MariaDB-log`

**Comment by a8m** [comment]
Hey @rotemtam and @AnnatarHe, some update before I'm adding a workaround for this. I found an issue in `MariaDB-10.3.13`. Please see the attached screenshots:

`MariaDB-10.3.13`
![image](https://user-images.githubusercontent.com/7413593/112851030-3f458b00-90b3-11eb-8710-dc2fe8d96df2.png)

`MariaDB-10.3.28`
![image](https://user-images.githubusercontent.com/7413593/112851141-5d12f000-90b3-11eb-8d1b-35f3e7748a16.png)

**Comment by AnnatarHe** [comment]
Hi @a8m,
when we can release this bugfix? it bother me for more than 2 weeks.
thank you.

**Comment by a8m** [comment]
Hey hey @AnnatarHe, I'm going to write a release note and release a new version next week. But for now, you can update to the latest master as follows:

```
go get -u entgo.io/ent@master
```

BTW, if you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏
