### ISSUE TITLE
"has one of" relation

### ISSUE THREAD

**Issue by pontaoski** [ent/ent#1397]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Ent has relations like "one has one", "many has one", etc. But what it doesn't have is a "has one of" relation, where one object can have only one of a set of possible edges to other options.

Usage would be something like: `edge.OneOf("content", TextMessage.Content, PhotoMessage.Content, FilesMessage.Content, ...)`. For queries, there could be a "get specific variant or return not found error" query or a query that returns a closed interface to allow for type-switching.

## Motivation 🔦

For https://github.com/harmony-development/legato, we have multiple message content types for the chat protocol we're implementing. Essentially, our message type looks like this in pseudo-Go:

```go
type Message struct {
    From author
    SentAt time.Time

    Content textMessage or photoMessage or filesMessage or embedMessage
}
```

This is already technically possible with Ent, but requires writing validation code boilerplate to ensure we don't accidentally have two edges set, and an extra tag field to keep track of which edge should be valid; where it would be nicer to just have a "one of" edge type available.

**Comment by rotemtam** [comment]
Hey @pontaoski ,
I've seen a type of psuedo polymorphism in ORMs in the past which was implemented using inheritance - that wasn't great. What you're describing exists in protobuf and works well there . In the context of ent, wouldn't it make sense to have:
- a message metadata type
- The content types have a many bto one relations with the metadata?

**Comment by a8m** [comment]
Hey @pontaoski and sorry for the delay. 

This feature was proposed in https://github.com/ent/ent/issues/1048. Let's continue the discussion there?

**Comment by pontaoski** [comment]
> Hey @pontaoski and sorry for the delay.
> 
> This feature was proposed in #1048. Let's continue the discussion there?

sure

**Comment by a8m** [comment]
@pontaoski, great. Closing
