### ISSUE TITLE
edge: multiple storage-keys defined for edge on O2M same type

### ISSUE THREAD

**Issue by nilpntr** [ent/ent#1399]
Go the following error when creating a 02M relation on the same type if a storage_key:
```go
edge.To("children", CompanyUnit.Type).
	StorageKey(edge.Column("parent_id")).
	From("parent").
	Unique(),
```
`entc/gen: set "CompanyUnit" foreign-keys: "parent" edge: multiple storage-keys defined for edge "parent"<->"children"`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.7.0   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by rotemtam** [comment]
Hi @nilpntr , thanks for your query. 
Can you please supply an entire schema that reproduces the issue so it's easier to debug exactly what's going on? The full definition isn't necessary just a minimum to reproduce.
Thanks!

**Comment by nilpntr** [comment]
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// CompanyUnit holds the schema definition for the CompanyStructure entity.
type CompanyUnit struct {
	ent.Schema
}

// Fields of the CompanyUnit.
func (CompanyUnit) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Optional().
			Nillable(),
		field.Bool("is_deleted").
			Default(false),
	}
}

// Edges of the CompanyUnit.
func (CompanyUnit) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("company", Company.Type).
			Ref("company_unit").
			Unique(),
		edge.To("person_company_unit", PersonCompanyUnit.Type).
			StorageKey(edge.Column("company_unit_id")),
		edge.To("children", CompanyUnit.Type).
			StorageKey(edge.Column("parent_id")).
			From("parent").
			Unique(),
		edge.To("person_compare_company_unit", PersonCompareCompanyUnit.Type).
			StorageKey(edge.Column("company_unit_id")),
	}
}

// Mixin of the CompanyUnit.
func (CompanyUnit) Mixin() []ent.Mixin {
	return []ent.Mixin{
		TimeMixinWQB{},
	}
}
```

**Comment by rotemtam** [comment]
@nilpntr, thanks for the quick response. What you sent references other types that aren't defined here.
It will help me to assist if you just provide a minimal example that reproduces the issue
Many thanks

**Comment by nilpntr** [comment]
They other relations in the edges don't care because when I run an example from the entgo docs I get the same error so let me give you this example:
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Node holds the schema definition for the Node entity.
type Node struct {
	ent.Schema
}

// Fields of the Node.
func (Node) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
	}
}

// Edges of the Node.
func (Node) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", Node.Type).
			StorageKey(edge.Column("parent_id")).
			From("parent").
			Unique(),
	}
}
```
Error:
`entc/gen: set "Node" foreign-keys: "parent" edge: multiple storage-keys defined for edge "parent"<->"children"`

**Comment by rotemtam** [comment]
@nilpntr , I've managed to reproduce your issue locally and I think if you modify your schema like below you will get what you want:
```go

// CompanyUnit holds the schema definition for the CompanyStructure entity.
type CompanyUnit struct {
	ent.Schema
}

// Fields of the CompanyUnit.
func (CompanyUnit) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Optional().
			Nillable(),
		field.Bool("is_deleted").
			Default(false),
		field.Int("parent_id").Optional(),
	}
}

// Edges of the CompanyUnit.
func (CompanyUnit) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", CompanyUnit.Type).
			From("parent").
			Field("parent_id").
			Unique(),
	}
}

```
Notice I've defined the parent_id field on the fields list and am referencing it using the .Field() modifier from the edges list.

**Comment by nilpntr** [comment]
Thanks that works

**Comment by rotemtam** [comment]
Happy to hear, closing.
