### ISSUE TITLE
How to add more columns in pivot table

### ISSUE THREAD

**Issue by TawsifKarim** [ent/ent#1400]
I have created a pivot table named `category_products` that has this two column `product_id` and `category_id` as shown in the docs. I want to know if i can add more columns to this pivot table like when was this relationship created.. eg
`id|product_id|category_id|created_at|creator_id` etc etc ...

**Comment by rotemtam** [comment]
Hey @TawsifKarim 
Thanks for your question. AFAIK, there currently isn't support for adding columns to m2m edges, but this is definitely something @a8m has mentioned in one of our conversations as relevant for the future of ent.

Just out of interest, how would you expect such a feature to work?

**Comment by TawsifKarim** [comment]
I have recently started to learn golang and was exploring various features of this ORM before jumping into production with one of our projects. I work mostly with Laravel(PHP framework), and i started to miss some of the features of Eloquent ORM which is insanely easy and flexible to use provided by the framework.. They provide schema per table. So you can design your pivot table as you wish and add relationship between them later on. So an additional feature like this would surely reduce a lot of complexities.. after all I know that these two languages are different from each other. So the implementation will surely differ. Hoping for the best and thanks for responding.

**Comment by a8m** [comment]
Thanks for proposing this feature @TawsifKarim. 

As mentioned in the roadmap, we plan to add this feature in the upcoming versions. You can see the proposed implementation for it in https://github.com/ent/ent/issues/1061 and share your feedback there. Thanks 🙏
