### ISSUE TITLE
Does ent grpc now support UUID primary keys?

### ISSUE THREAD

**Issue by godcong** [ent/ent#1402]
When i run generate  `entproto -path ./ent/schema`
The command line returned me an error message:
```
entproto: failed generating protos: entproto: failed parsing some schemas: unsupported field type "TypeUUID"
```

my schema:
```
// Fields of the InformationV1.
func (InformationV1) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New).Annotations(
			entproto.Field(1),
		),
		field.String("root"),
	        ...
	}
}

func (InformationV1) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(),
	}
}
```

**Comment by rotemtam** [comment]
Hey @godcong , thanks for your query. 
As you can see in the README for entproto, [currently TypeUUID isn't supported](https://github.com/ent/contrib/tree/master/entproto#field-annotations).

I want to add support for it and wanted to ask, how would you expect this field translation to work? 
* What would be the proto field type? `repeated bytes`, `string`, a new custom message type with two int64 fields for most sig/least sig bytes [as discussed in this thread](https://github.com/protocolbuffers/protobuf/issues/2224)?

**Comment by godcong** [comment]
RFC 4122 seems to have the best performance.
It allows UUID to be encoded in binary (as opposed to text)
The String() method can completely solve the string display problem
So I think bytes should be a better choice
