### ISSUE TITLE
Naming conflict on generated structs

### ISSUE THREAD

**Issue by gsoec** [ent/ent#1408]
Some structs are overridden by ent's internal template.

- [✓] The issue is present in the latest release.
- [✓] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
```go
// Collection.go in ent/schema/
type Collection struct {
  ent.Schema
}

// Transaction.go in ent/schema/
type Transaction struct {
  ent.Schema
}
```
The generated `Collection.go` and `Transaction.go` in `ent/` do not contain `type Collection struct` and  `type Transaction struct`.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.?  |
| Ent         | 0.5.?   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by rotemtam** [comment]
Hey @gsoec ,

I've tried to reproduce on latest v0.7.0 - it seems to work. For instance in `ent/collection.go`:
```go
// Collection is the model entity for the Collection schema.
type Collection struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}
```

Can you try with the latest version and verify that this bug reproduces? 

Thanks
R

**Comment by rotemtam** [comment]
@gsoec are you using the GraphQL integration?

**Comment by gsoec** [comment]
@rotemtam Yes, i'm using the GraphQL integration with latest release version of ent. Seems enabling GraphQL plugin  make this happen.

**Comment by a8m** [comment]
Hey @gsoec, the GraphQL plugin templates generate a file named `collection.go` that overrides your file. We should fix this by prefixing all GraphQL files with `gql` (e.g. `gql_collection.go`). 

Please use a different name until we add a fix for it. If you need to control the database-table, use the [entsql.Annotation](https://entgo.io/docs/schema-annotations/#custom-table-name) for this.

**Comment by yonidavidson** [comment]
@gsoec Hi, if you have any issues with the fix please update me.
