### ISSUE TITLE
Struct's name with "Create/Update/Delete" suffix confuses gqlgen's autobind

### ISSUE THREAD

**Issue by gsoec** [ent/ent#1409]
Struct's name with "Create/Update/Delete/Query" suffix generated by ent's internal templates confuses gqlgen's autobind when schema.graphql contains
```graphql
# schema.graphql
type Product {
  id: ID!
  description: String!
}

type ProductCreate {
  product: Product
  error: Error
}

type Mutation {
  productCreate(description: String!): ProductCreate
}
```

- [✓] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

gqlgen's autobind may work better with putting "Create/Update/Delete/Query" generated files elsewhere.

**Comment by a8m** [comment]
Hey @gsoec and thanks for opening this issue. 

We have nothing to do with it actually. One option is to not use `autobind` and map your models [using an inline directive](https://gqlgen.com/v0.13.0/config/#inline-config-with-directives) in your GraphQL schema, and the second option is to tell gqlgen to ignore specific models in `autobind`-mode using some configuration. I'm not sure gqlgen supports the second option, but it can be a nice addition to this framework. 

Closing, but please let me know if I can help somehow and feel free to share with us your solution 🙏
