### ISSUE TITLE
Failed to generate O2O Edge Field

### ISSUE THREAD

**Issue by touyu** [ent/ent#1417]
Hello, Thanks for the useful libraries.

I'm having a problem with an error when trying to create an O2O Edeg Field.
If I'm doing something wrong, please let me know.

`ent/schema/room.go`
```go
package schema

import (
	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Room holds the schema definition for the Room entity.
type Room struct {
	ent.Schema
}

// Fields of the Room.
func (Room) Fields() []ent.Field {
	return []ent.Field{
		field.Int("promotion_id").
			Optional(),
	}
}

// Edges of the Room.
func (Room) Edges() []ent.Edge {
	return []ent.Edge{
               edge.To("promotion", Promotion.Type).
			Field("promotion_id").
			Unique().
			Annotations(entgql.Bind()),
	}
}
```

`ent/schema/promotion.go`
```go
package schema

import (
	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Promotion holds the schema definition for the Promotion entity.
type Promotion struct {
	ent.Schema
}

// Fields of the Promotion.
func (Promotion) Fields() []ent.Field {
	return []ent.Field{}
}

// Edges of the Promotion.
func (Promotion) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("room", Room.Type).
			Ref("promotion").
			Unique().
			Annotations(entgql.Bind()),
	}
}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
$ go generate ./ent
```

I receive the following error message.

```
2021/04/01 16:45:55 running ent codegen: entc/gen: set "Room" foreign-keys: edge "promotion" has a field "promotion_id" but it is not holding a foreign key
```

## Expected Behavior 🤔

Created successfully.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.14.1  |
| Ent         | 0.7   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by rotemtam** [comment]
Seems like room.go is missing  an edge.To call, no?

**Comment by touyu** [comment]
@rotemtam I'm sorry, that was a mistake. In fact it is written. 
I fix sample code.

**Comment by a8m** [comment]
On my phone atm, so I’ll comment in more details tomorrow. 

I’m pretty sure replacing the “room” edge to be edge.To, and the “promotion” edge to be edge.From should solve the issue.

**Comment by rotemtam** [comment]
@a8m i can confirm that works. I must say I'm a bit confused as to why? Also perhaps we can hint at this in the error message.

**Comment by a8m** [comment]
> @a8m I can confirm that works. I must say I'm a bit confused as to why? 

In O2O relationship, the FK (foreign-key) needs to be stored in one of the tables (`rooms` or `promotions`), and ent stores it on the table with the inverse-edge (`edge.From`). This allows some flexibility to change the relationship to `O2M` in the future if necessary (this can be done by removing the `Unique()` call in the `edge.To` side).

The new schema-versioning feature will give users the freedom to choose where the FK will reside. It should be added in the upcoming versions.

> Also perhaps we can hint at this in the error message.

I agree. 

@touyu, I hope it helped. Please let me know if I can close this issue. Thanks 🙏

**Comment by touyu** [comment]
@a8m and @rotemtam Thank you for your kind support!
I understood it.
This problem was solved.

**Comment by ji21** [comment]
I'm finding myself in a similar situation, but with a O2M Edge field.

I ran "go generate ./ent"  and got this error: set "App" foreign-keys: edge "creator" has a field "creator_id" but it is not holding a foreign key

The Code:

ent/schema/user.go
`
package schema

import (
    "entgo.io/ent"
    "entgo.io/ent/schema/field"
	"entgo.io/ent/schema/edge"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("email").Unique(),
		field.Ints("created_apps_ids"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("created_apps", App.Type).Field("created_apps_ids"),
	}
}

`

ent/schema/app.go

`
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/edge"
)

// App holds the schema definition for the App entity.
type App struct {
	ent.Schema
}

// Fields of the App.
func (App) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.Int("creator_id"),
	}
}

// Edges of the App.
func (App) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("creator", User.Type).Ref("created_apps").Field("creator_id"),
	}
}
`

This only happened when I set the field on the edge.

**Comment by gonnafaraway** [comment]
When you need to use O2M, use M2M instead, it mitigates incorrect work of ent.
See some help here https://github.com/gonnafaraway/ent-troubleshooting
