### ISSUE TITLE
entproto doesn't handle booleans

### ISSUE THREAD

**Issue by Bladrak** [ent/ent#1421]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I'm trying to generate a Protobuf service using the following code:
```.go
package schema

import (
	"entgo.io/contrib/entproto"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Dependency holds the schema definition for the Dependency entity.
type Dependency struct {
	ent.Schema
}

// Fields of the Dependency.
func (Dependency) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Annotations(entproto.Field(2)),
		field.String("source").
			Annotations(entproto.Field(3)),
		field.String("version").
			Annotations(entproto.Field(4)),
		field.Bool("deprecated").
			Default(false).
			Annotations(entproto.Field(5)),
	}
}

// Edges of the Dependency.
func (Dependency) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("projects", Project.Type).
			Ref("dependencies").
			Annotations(entproto.Field(6)),
	}
}

func (Dependency) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(),
		entproto.Service(),
	}
}
```

Upon running `go generate ./...` I have the following error:
```
--entgrpc_out: entproto: no mapping for pb field type "TYPE_BOOL"
ent/proto/entpb/generate.go:2: running "protoc": exit status 1
```

## Expected Behavior 🤔

Generation should proceed normally

## Steps to Reproduce 🕹

Steps:

1. Create a new ent project with the schema above (remove the Dependency part)
2. Run `go generate ./...`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.7   |
| Ent contrib         | v0.0.0-20210401190451-976dee512d7a    |
| Database    | Sqlite   |

## Debug leads

Upon investigating the code, I don't see `TYPE_BOOL` in the switch here:  https://github.com/ent/contrib/blob/0bc3089cabc9790b6e957390c915fee94c98cc7b/entproto/cmd/protoc-gen-entgrpc/cast.go#L28

**Comment by rotemtam** [comment]
Thanks for reporting . Will send a patch in the next few days. If you have time to submit something I'll gladly review it

Cheers
