### ISSUE TITLE
Foreign key name

### ISSUE THREAD

**Issue by michaelkub** [ent/ent#1423]
Hello everyone ,

Is it possible to provide foreign key name ?

As I saw it is autogenerated by the following pattern:
`Symbol:     fmt.Sprintf("%s_%s_%s", owner.Name, ref.Name, e.Name)`
but sometimes it is required to provide own name

**Comment by a8m** [comment]
Hey @michaelkub! It's great to hear from you 😃 

There's no way to configure it in the schema atm, but I can add it to the edge annotation later today and tag you. If you're looking for a workaround, you can use a [migration-hook](https://entgo.io/docs/migrate#migration-hooks) to change the foreign-key symbol and remove this workaround after we add this option.

```go
client.Schema.Create(
    ctx,
    schema.WithHooks(func(next schema.Creator) schema.Creator {
        return schema.CreateFunc(func(ctx context.Context, tables ...*schema.Table) error {
            tables[i].ForeignKeys[j].Symbol = "<symbol>"
            return next.Create(ctx, tables...)
        })
    }),
)
```

BTW, I'd be happy to share with you my work on the new migration API. Feel free to join our [Ent Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) and ping me privately if you're interested 🙏
