### ISSUE TITLE
Simple update mutation with GraphQL

### ISSUE THREAD

**Issue by yeyep** [ent/ent#1429]
Hello guys,
I am following the GraphQL tutorial and am excited about the integration. 
However, I am not sure how best to handle update mutations. 
Since we have a separate set method for each field in ent, we can't use the way suggested by 99design:
https://gqlgen.com/reference/changesets/

Is there already a generator template for this? I couldn't find a matching topic in the issues unfortunately.
Using a template would probably be the right approach for ent, right?

Thanks for the help.

Many greetings,
Daniel

**Comment by a8m** [comment]
Hey @yeyep and thanks for opening this issue.

I usually prefer to use a `ChangeSet` struct instead of a map, because it's more efficient and explicit. For example, given the example from the `gql` website, let's say the `name` field is required (can't be cleared), and the `email` is an optional field. Then, a custom template will generate a struct as follows:

```go
type UserChangeSet struct {
	// Field changes:
	Name       string
	Email      string
	ClearEmail bool
	// Edge changes:
	AddGroupIDs   []int
	ClearGroupIDs []int
	SpouseID       int
	ClearSpouseID  bool
}

// Mutate applies its changes on UserUpdate, UserUpdateOne and UserCreate builders.
func (u *UserChangeSet) Mutate(ent *UserMutation) error {
	// ...
}
```

And then, in your resolver, you can use it as follows:

```go
func (r *resolver) UpdateUser(ctx context.Context, id int, c *ent.UserChanges) (*ent.User, error) {
	u := r.Client.UpdateOneID(id)
	if err := c.Mutate(u.Mutation()); err != nil {
		return nil, err
	}
	return u.Save(ctx)
}
```

If you still prefer the map version, that's also fine. I can help either way. Just let me know what version works better for you and I can help you with the template (I already have something that I use in my project, and can change it a bit and add it to our website).

**Comment by yeyep** [comment]
Hi @a8m 

Thanks for your quick reply.
Your proposed solution with a struct instead of a map is the solution I would prefer.
Especially when it even takes into account optional and required fields, like in your example. 

I will be happy if you post an example on the website. 
I think it would make the tutorial even more complete :)

Have a good day,
Daniel

**Comment by wenerme** [comment]
My solution is generate create input and update input then use like this

```go
func (r *mutationResolver) CreateAccount(ctx context.Context, input ent.CreateAccountInput) (*ent.CreateAccountPayload, error) {
	return r.Client.Account.Create().CreateFromInput(ctx,&input)
}

func (r *mutationResolver) UpdateAccount(ctx context.Context, input ent.UpdateAccountInput) (*ent.UpdateAccountPayload, error) {
	return r.Client.Account.UpdateOneID(input.ID).UpdateFromInput(ctx, &input)
}

func (r *mutationResolver) DeleteAccount(ctx context.Context, input ent.DeleteAccountInput) (*DeleteAccountPayload, error) {
	err := r.Client.Account.DeleteOneID(input.ID).Exec(ctx)
	return &DeleteAccountPayload{ClientMutationID: input.ClientMutationID}, err
}
```

```go
func (ac *AccountCreate) CreateFromInput(ctx context.Context, input *CreateAccountInput) (payload *CreateAccountPayload, err error) {
	ac.SetCreateInput(input)
	payload = &CreateAccountPayload{
		ClientMutationID: input.ClientMutationID,
	}
	payload.Account, err = ac.Save(ctx)
	return
}

func (ac *AccountCreate) SetCreateInput(input *CreateAccountInput) *AccountCreate {
	ac.SetNillableCustomerRelationType(input.CustomerRelationType)
	ac.SetNillableIndustry(input.Industry)
	ac.SetNillableCompanySize(input.CompanySize)
	ac.SetNumberOfEmployees(input.NumberOfEmployees)
	ac.SetNillableUniformCreditCode(input.UniformCreditCode)
	return ac
}
```

The generated schema like

```gql
type UpdateAccountPayload {
	clientMutationId: String
	account: Account
}
input DeleteAccountInput {
	clientMutationId: String
	id: ID! @possibleTypes(concreteTypes: ["Account"])
}
type DeleteAccountPayload {
	clientMutationId: String
}
extend type Mutation {
	createAccount(input: CreateAccountInput!): CreateAccountPayload
	updateAccount(input: UpdateAccountInput!): UpdateAccountPayload
	deleteAccount(input: DeleteAccountInput!): DeleteAccountPayload
}
```

The graphql is usage based, no standard, still working on more way to use graphql.

**Comment by a8m** [comment]
Thanks for sharing with us your example @wenerme.

I'm working on adding such an example to our website and updating [my GraphQL example](https://github.com/a8m/ent-graphql-example) with it. Maybe you can write about your use-cases/solutions in the Ent's blog -  ping me on Slack if you're interested.

**Comment by wenerme** [comment]
@a8m I want to make some of my work public, but before that, I may send some pr for entc, reusing the Generator can make a lot things easier.

**Comment by a8m** [comment]
Hey @wenerme and @yeyep,
The tutorial is available now at https://entgo.io/docs/tutorial-todo-gql-mutation-input. Feel free to read it and propose improvements.

**Comment by giautm** [comment]
Hey @a8m, I just try to copy the template and apply it to my current project. When I run `go generate ./...`, it says:
```
2021/04/19 10:31:13 running ent codegen: execute template "mutation_input": template: mutation_input.tmpl:68:19: executing "mutation_input" at <"Clear">: can't give argument to non-function "Clear"
exit status 1
```
