### ISSUE TITLE
Ability to tell whether the update/mutation is dirty (has changed fields)

### ISSUE THREAD

**Issue by jbub** [ent/ent#1436]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Say i have a `Payment` entity with many columns.

Now i want to update the payment with some data:

```golang
update := client.Payment.Update()
if req.Description != nil {
    update.SetDescription(*req.Description)
}
if req.Source != nil {
    update.SetSource(*req.Source)
}
// ... other columns are set here

// it would be nice to have some api to know whether we changed any fields
if !update.HasChanges() {
    // do some logic here, like error out with invalid request or something
}
```

I was not able to find such method, maybe it would be a good addition to the update/mutation API ?

## Motivation 🔦

I want to avoid running updates that do not change any fields.

Thanks for open sourcing this great project.

Many greetings,
Juraj

**Comment by a8m** [comment]
Hey @jbub and thanks for opening this issue.

> I want to avoid running updates that do not change any fields.

I have a quick question before - currently, when you try to apply an empty update mutation, ent will not execute any UPDATE operation on the database. It works for both `Update` and `UpdateOne`:

https://github.com/ent/ent/blob/c53b45ddb02a6ac1ddc24c623d8d04f32f9ed6b8/dialect/sql/sqlgraph/graph.go#L726


https://github.com/ent/ent/blob/c53b45ddb02a6ac1ddc24c623d8d04f32f9ed6b8/dialect/sql/sqlgraph/graph.go#L664

Also, in some cases, your mutation can be dirty but don't change any row on the database. For example:

```go
client.Pet.Create().SetName("A").SaveX(ctx)
client.Pet.Update().SetName("A").ExecX(ctx)
```

If you still need this API, I can help to generate it using a custom template, or you can use something as follows:

```go
func IsDirty(m ent.Mutation) bool {
	if m.Op().Is(ent.OpCreate | ent.OpDelete | ent.OpDeleteOne) {
		return true
	}
	return len(m.Fields()) > 0 || len(m.AddedFields()) > 0 || len(m.ClearedFields()) > 0 ||
		len(m.AddedEdges()) > 0 || len(m.ClearedEdges()) > 0 || len(m.RemovedEdges()) > 0
}
```

**Comment by jbub** [comment]
Hello, thanks for the info, that is all i need, i did not know there is actually a check for this, i guess i was not looking deep enough :) Thank you, we can close this one :)

**Comment by a8m** [comment]
Sure, happy to help 😃 


Please feel free to join our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) in the Gophers Slack. Also, if you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏
