### ISSUE TITLE
how could i build json_overlaps

### ISSUE THREAD

**Issue by YaaMe** [ent/ent#1439]
how could i build this sql for now? in mysql case
```sql
select * from apps where JSON_OVERLAPS(app_tags, '{"key_2": "value_2", "key_3": "value_3"}'); 
```

I couldn't find usage about `FieldJSON predicate` about query on [docs](https://entgo.io/docs/predicates) . So I follow the [tests](https://github.com/ent/ent/blob/master/dialect/sql/sqljson/sqljson_test.go) and know how to build `JSON_CONTAINS`, but I still lost [JSON_OVERLAPS](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-overlaps). I guess it's WIP...

**Comment by a8m** [comment]
Hello @YaaMe, the [sqljson](https://pkg.go.dev/entgo.io/ent/dialect/sql/sqljson) package provides the common JSON predicates for all supported dialects (MySQL, MariaDB, PostgreSQL, SQLite). 

However, the `JSON_OVERLAPS` predicate is not there. But, you can write manually as follows:

```go
client.User.Query().
	Where(func(s *sql.Selector) {
		s.Where(overlaps(user.FieldTags, `{"tag": "foo"}`))
	}).
	AllX(ctx)
// driver.Query: query=SELECT ... FROM `users` WHERE JSON_OVERLAPS(`tags`, ?) args=[{"tag": "foo"}]

// overlaps generates the JSON_OVERLAPS predicate for the given parameters. 
func overlaps(column, value string) *sql.Predicate {
	return sql.P(func(b *sql.Builder) {
		b.WriteString("JSON_OVERLAPS").Nested(func(b *sql.Builder) {
			b.Ident(column).Comma().Arg(value)
		})
	})
}
```

Let me know if can close this issue. Thanks

**Comment by YaaMe** [comment]
@a8m , thanks, i got it and succeed.but I'm still filled with curiosity: why the `JSON_OVERLAPS` is not there?

**Comment by rotemtam** [comment]
@YaaMe software engineering and particularly library designs is a balancing art of compromise, requirements, available resources, constraints and putting a cap on emerging complexity must all be considered when deciding what to include, what to exclude, what to include, and what to postpone. Ent is a community, open source project. If you think something is missing you are welcome to start a discussion and file a PR. I hope this resolves your curious out !

**Comment by a8m** [comment]
@YaaMe, if you're interested to contribute this functionality to the `sqljson` package, please ping me in our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53), and I'll be happy to help with that 🙏
