### ISSUE TITLE
clear edge field by id not works

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1445]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```go
acc.Update().ClearOwnerID().ClearOwningUserID().SaveX(ctx)
```

Issued

```
UPDATE `accounts` SET `owner_id` = NULL, `updated_at` = ? WHERE `id` = ?
```

The ClearOwningUserID not set field to null.

The field is defined like

```go
field.String("owningUserID").GoType(models.ID("")).Optional().Nillable()
```

## Expected Behavior 🤔

field set null

## Steps to Reproduce 🕹

[wenerme/ent-demo](https://github.com/wenerme/ent-demo/blob/fe3a4c794a2a2ade8927a5ed11feaeb407a32473/test/demo_test.go#L12)

```go
log.Println("clear user id")
petA.Update().ClearOwningUserID().SaveX(ctx)
log.Println("clear user")
petA.Update().ClearOwningUser().SaveX(ctx)
```

clear id not works

```
2021/04/09 21:10:16 clear user id
    dialect.go:79: driver.Tx(25e5d935-f52d-42b7-b175-c9d56ea6e900): started
    dialect.go:79: Tx(25e5d935-f52d-42b7-b175-c9d56ea6e900).Query: query=SELECT `id`, `owner_id`, `owner_type`, `owning_user_id`, `name` FROM `pets` WHERE `id` = ? args=[1]
    dialect.go:79: Tx(25e5d935-f52d-42b7-b175-c9d56ea6e900): committed
2021/04/09 21:10:16 clear user
    dialect.go:79: driver.Tx(f4252fc7-84b5-4dbe-9371-2edc4ddf1368): started
    dialect.go:79: Tx(f4252fc7-84b5-4dbe-9371-2edc4ddf1368).Exec: query=UPDATE `pets` SET `owning_user_id` = NULL WHERE `id` = ? args=[1]
    dialect.go:79: Tx(f4252fc7-84b5-4dbe-9371-2edc4ddf1368).Query: query=SELECT `id`, `owner_id`, `owner_type`, `owning_user_id`, `name` FROM `pets` WHERE `id` = ? args=[1]
    dialect.go:79: Tx(f4252fc7-84b5-4dbe-9371-2edc4ddf1368): committed
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.7.?   |
| Database    | sqlite   |
| Driver      | n/a       |

**Comment by a8m** [comment]
Hey @wenerme and thanks for reporting this issue. 

Before I'm giving it a look, just to make sure I understand it - it doesn't work for [edge fields](https://entgo.io/docs/schema-edges/#edge-field)?

**Comment by a8m** [comment]
Found the issue. I'll send a patch soon.

**Comment by wenerme** [comment]
@a8m would you mind to release a new version ?

**Comment by a8m** [comment]
> @a8m would you mind to release a new version ?

Done, https://github.com/ent/ent/releases/tag/v0.8.0
