### ISSUE TITLE
How to remove the association relationship between table records?

### ISSUE THREAD

**Issue by dybxin** [ent/ent#1448]
eg:  one table name is `user` , other table name is  `role`,  `user ` and `role ` relationship is M2M.

user:
|  ID   | Name  |
|  ----  |  ----  |
| 1 | name1 |
| 2  | name1 |
| 3  | name3 |
| 4  | name4 |
| 5  | name5 |

role:
|  ID   | Name  |
|  ----  |  ----  |
| 1 | role1 |
| 2  | role1 |
| 3  | role3 |
| 4  | role4 |
| 5  | role5 |

user_roles:
|  user_id   | role_id  |
|  ----  |  ----  |
| 1 | 1 |
| 2  | 1 |
| 3  | 2 |
| 4  | 2 |
| 5  | 2 |

Is there a method to delete the relationship in user_roles table(user_id = 1 and role_id = 1)?

**Comment by a8m** [comment]
Hey @dybxin,
Are you trying to update this table directly? Because this is possible today like this:

```go
client.User.UpdateOneID(1).RemoveRoleIDs(1).SaveX(ctx)
```

**Comment by dybxin** [comment]
@a8m yes, thanks a lot.

**Comment by a8m** [comment]
Sure, happy to help!


Please feel free to join our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) in the Gophers Slack. Also, if you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏 

Closing.

**Comment by dybxin** [comment]
@a8m im sorry, i can't join the slack invitation link , please sure the link correct?

**Comment by a8m** [comment]
> @a8m im sorry, i can't join the slack invitation link , please sure the link correct?

This is the link to the Slack channel - https://app.slack.com/client/T029RQSE6/C01FMSQDT53

**Comment by a8m** [comment]
> @a8m im sorry, i can't join the slack invitation link , please sure the link correct?

This is the link to the Slack channel - https://gophers.slack.com/archives/C01FMSQDT53

**Comment by dybxin** [comment]
@a8m thanks a lot.
