### ISSUE TITLE
How to represent a blob field for mysql database?

### ISSUE THREAD

**Issue by sistecma** [ent/ent#1454]
Hello,

My use case requires to store blob in a mysql database. I've checked the documentation but I don't see where / how to do it. Perhaps with the "Other" type?, Can you please point a short fragment of code?

**Comment by a8m** [comment]
Hey @sistecma, you can use the `field.Bytes` type as follows:

```go
func (T) Fields() []ent.Field {
	return []ent.Field{
		field.Bytes("blob").
			Optional(),
	}
}
```

**Comment by a8m** [comment]
Closing, but please reopen if you still need help with this. 

Also, you're welcome to join our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) in the Gophers Slack. If you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏

**Comment by sistecma** [comment]
Excellent , thanks for the quick feedback. I already subscribed to the slack and newletter. 

Saludos,
