### ISSUE TITLE
How add check and unique Constraints?

### ISSUE THREAD

**Issue by wahello** [ent/ent#1459]
#### How to add check constraint and unique constraint?

**Comment by a8m** [comment]
Hey @wahello and thanks for opening this issue.

Are you talking about [CHECK constraints](https://www.postgresql.org/docs/9.4/ddl-constraints.html)? Regarding the unique constraint, you can use the [`Unique()`](https://entgo.io/docs/schema-fields/#uniqueness) option or define a [unique-index](https://entgo.io/docs/schema-indexes) on the field.

**Comment by wahello** [comment]
[Unique()](https://entgo.io/docs/schema-fields/#uniqueness) works on unique Constraints.
#### How about two columns or more in CHECK constraint?

**Comment by a8m** [comment]
2 or more columns can be added with [custom index](https://entgo.io/docs/schema-indexes) as follows:

```go
 index.Fields("first_name", "last_name").
            Unique(),
```

Regarding the `CHECK` constraint, can you elaborate on what type of CHECK are you trying to add? Maybe provide an SQL example.

We can support adding custom CHECK clauses using the `entsql.Annotation`. It's actually an easy task, so let me know if you're interested to contribute this feature.

**Comment by wahello** [comment]
Not that simple, such as table as following:
`
SomeTable struct {
   ID 
   A  string
   B string
}
`
Just make sure when A is null, B not null, and A is not null, b is null.

And there are many other applications like that.

**Comment by rotemtam** [comment]
@wahello I'll leave it to @a8m to answer if it's possible to set these constraints on the database DDL statements, but have you considered doing this applicatively using [Schema Hooks](https://entgo.io/docs/hooks#schema-hooks)?

**Comment by wahello** [comment]
@rotemtam  I'll try it. Thanks.

**Comment by rotemtam** [comment]
Perfect, please share your experience with it afterward!

**Comment by a8m** [comment]
Issue resolved. Please see https://entgo.io/docs/faq#how-to-add-check-constraints-to-table.

**Comment by tony-pond** [comment]
@wahello  @a8m 

Using Postgresql, unique indexes are created correctly, but the unique constraint doesn't get created - which is a blocker for Hasura GraphQL and their implementation of onConflict update.
To fix this issue, you can simply do:

```go
if err := sqlClient.Schema.Create(ctx,
		schema.WithHooks(func(next schema.Creator) schema.Creator {
			return schema.CreateFunc(func(ctx context.Context, tables ...*schema.Table) error {

				err :=  next.Create(ctx, tables...)
				if err !=nil {
					panic(err)
				}
				// Run custom code here.
				for _, table := range tables {
					for _, index := range table.Indexes {
						if index.Unique {
							if _, err := db.Exec(fmt.Sprintf("ALTER TABLE %s " +
								"ADD CONSTRAINT %s " +
								"UNIQUE USING INDEX %s", table.Name, index.Name+"_unique", index.Name)); err !=nil {
								panic(err)
							}
						}
					}
				}
				return nil
			})
		}),
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true)); err != nil {
		log.Panicf("Error persisting DB schema : %v", err)
	}
```

**Comment by ivanvanderbyl** [comment]
@a8m I feel like this requires more attention. In Postgres, in order to use a unique index as a unique constraint in an Upsert operation, it must be created or altered with the `CONSTRAINT` keyword (As @tony-pond mentioned above). I think it would make sense to add an annotation for this in Ent. What do you think?

Something like:

```go 
index.Edges("user", "profile").Unique().Annotations(index.Annotation{UsingConstraint: true})
```
