### ISSUE TITLE
0.8 custom id generate invalid code

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1465]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

in sqlAll

![image](https://user-images.githubusercontent.com/1777211/115054497-d82d3080-9f12-11eb-8203-9b4b3c72da16.png)

the id type is

```go
type ID string
```

## Expected Behavior 🤔

working

## Steps to Reproduce 🕹

WIP

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.?  |
| Ent         | 0.8.?   |
| Database    | -   |
| Driver      | -        |

**Comment by wenerme** [comment]
BTW, code in 0.7

![image](https://user-images.githubusercontent.com/1777211/115054808-3c4ff480-9f13-11eb-96cc-378557df6a40.png)

**Comment by a8m** [comment]
Thanks for reporting this @wenerme. This happens also in v0.7.0, right?

**Comment by wenerme** [comment]
@a8m no, v0.7 is working, rollbacked to v0.7, the `&sql.NullString{}` syntax is ok

**Comment by a8m** [comment]
Hey @wenerme, the issue was fixed and works fine now in master (see example in https://github.com/ent/ent/pull/1470).

Thanks for reporting this issue 🙏
