### ISSUE TITLE
entgql: Expose `ToCursor` methods on mutated objects

### ISSUE THREAD

**Issue by timoha** [ent/ent#1467]
## Summary 💡

Relay [supports](https://relay.dev/docs/guided-tour/list-data/updating-connections/#using-declarative-directives) `@appendEdge` and `@prependEdge` directives in order to seamlessly update connections after mutations are committed. It would be great to expose `ToCursor` method on a node in order to construct edges from the saved mutations responses.

## Motivation 🔦

Currently I have to assume implementation by looking up what `pager.toCursor(node)` is doing for my node type. It would be great to hide implementation details of how cursors are created.

**Comment by a8m** [comment]
Hey @timoha and thanks for proposing this. I'm tagging @alexsn and we'll discuss it after the weekend.

**Comment by giautm** [comment]
Hey @timoha, Are you looking for this? Just need to call ToEdge to creare edge with correct order.

https://github.com/ent/contrib/pull/24

entgql/template/pagination.tmpl

**Comment by timoha** [comment]
> Hey @timoha, Are you looking for this? Just need to call ToEdge to creare edge with correct order.
> 
> https://github.com/ent/contrib/pull/24

Yup, that pretty much addresses my use case, didn't realize to check contrib repo, thanks you!

Don't know if there's some other good use case for exposed ToCursor api. Please feel free to close the issue.
