### ISSUE TITLE
How to set members's value in one batch?

### ISSUE THREAD

**Issue by wahello** [ent/ent#1475]
Like User table:

```

type User struct {
	ent.Schema
}
func (User) Fields() []ent.Field {

	return []ent.Field{
		field.String("user_name").Unique().NotEmpty().Immutable(),
		field.String("password").Sensitive().NotEmpty(),
		field.String("first_name").Default(""),
		field.String("last_name").Default(""),
		field.String("real_name").Default(""),
		field.String("email").Default(""),
		field.String("phone").Default(""),
	}

}
```

And create one record.

```
// 
client.User.Create().
SetAge(22).
SetFirstName("tom").
SetLastName("Green")

```
It's not a good idea set members' value one by one.

**Comment by a8m** [comment]
Hey @wahello, you can extend the code-generator to accept custom input types for the different builders.

It's already asked here a few times, and I added a section for it in the [FAQ](https://entgo.io/docs/faq#how-to-create-an-entity-from-a-struct-t) page on our website. Also, a new tutorial for creating such input-types is going to be uploaded to our website today (see https://github.com/ent/ent/pull/1476). 

Please let me know if you need help with adding this to your project.

**Comment by wahello** [comment]
@a8m Yes, I need an example as mentioned. Thanks.

**Comment by a8m** [comment]
We upload a new tutorial to our website on how to do it. You're welcome to go over it [here](https://entgo.io/docs/tutorial-todo-gql-mutation-input) and reopen the issue if you have any troubles with implementing this. 

Thanks 🙏

**Comment by wahello** [comment]
[This example](https://github.com/a8m/ent-graphql-example.git) is great, and show be highlighted. 
And more
`
entc generate ./xxxx/schema--template ./xxxx/schema/template --target ./xxxx/gen/ent
`
for Makefile.
