### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by michaelkub** [ent/ent#1484]
Hi, 
I needed to perform case insensitive search, I didn’t find generated predicate for this, but because I am using mariadb, I used the following approach :
`field.String("name").SchemaType(
			map[string]string{
				dialect.MySQL: "varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL",
			}),`
and it worked great. 
So, is this approach will continue to work and won't be remove in next versions or it maybe it will be replaced ?

**Comment by a8m** [comment]
Hey @michaelkub and it's great to see you here again :)

Ent generates case-insensitive predicates for string fields named `<F>ContainsFold` and `<F>EqualFold`. Don't you see thse predicates in your project?

**Comment by a8m** [comment]
Closing, but please feel free to reopen if you didn't find those methods or you have some trouble generating them. Thanks 🙏

**Comment by a8m** [comment]
Hey @ppphp,
Functional indexes are not supported atm, but they can be added like #1545. However, I think the current code can be replaced with something as follows: `where <column> COLLATE utf8mb4_general_ci = <value>`. Pretty sure it's more efficient, but didn't test it tbh. Do you want to contribute this?

This code:
https://github.com/ent/ent/blob/6d3df1469c831c26fc09f39c3417b0254911e2c7/dialect/sql/builder.go#L1350-L1359

Should be replaced with something as follows:

https://github.com/ent/ent/blob/6d3df1469c831c26fc09f39c3417b0254911e2c7/dialect/sql/builder.go#L1378-L1381
