### ISSUE TITLE
using ptr for uuid will import wrong path

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1485]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

define schema using 	"github.com/google/uuid", generated using 	"github.com/xtgo/uuid", when running the cast will failed

```go
pet.DefaultUID = petDescUID.Default.(func() *uuid.UUID)
```

## Expected Behavior 🤔

using correct import

## Steps to Reproduce 🕹

https://github.com/wenerme/ent-demo

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.8.1   |
| Database    |  -   |
| Driver      | - |

**Comment by wenerme** [comment]
```go
// not ok
field.UUID("uid_bad", new(uuid.UUID)).Default(func() *uuid.UUID {
  u := uuid.New()
  return &u
}).Optional(),
// ok
field.UUID("uid", uuid.New()).Default(uuid.New).Optional(),
```

but the second case will cause db contain 

![image](https://user-images.githubusercontent.com/1777211/115422629-aaf0c300-a22f-11eb-94d3-7363fab327e1.png)

**Comment by a8m** [comment]
Hey @wenerme, the difference comes from the `new(uuid.UUID)` declaration. Why do you use it this way? If you want to have a pointer for null values, use the `Nillable()` option instead.

The imports still need to be resolved for pointers. I'll send a patch for it later.

**Comment by wenerme** [comment]
@a8m UUID do not have Nillable, 
![image](https://user-images.githubusercontent.com/1777211/115503837-a49f2d00-a2a9-11eb-8f1d-e82e78b2e4ac.png)

**Comment by a8m** [comment]
Good it. So, it needs to be added.
Do you want to contribute this change?

**Comment by wenerme** [comment]
@a8m OK

**Comment by a8m** [comment]
@wenerme - let me know if you need help with this, or if you want me to take this. Thanks 🙏

**Comment by wenerme** [comment]
@a8m I'll do this late this week, kinda busy these two days

**Comment by pzeinlinger** [comment]
@wenerme, @a8m 

It seems that db null values are not correctly scanned to a nil pointer.
This means that a nillable UUID field does not behave the same as a nillable string.
I had a quick skim through the implementation of the UUID field and I'm not sure how to procede. 

We could explicitly handle nillable uuids in entc/gen/type or implement field.UUID differently. What's your opinion?

**Comment by wenerme** [comment]
@pzeinlinger this works for me, but I got the new problem, https://github.com/ent/ent/pull/1537 need @a8m  to take a look.

handle nillable uuid should be the sql.Value's job, how you define a uuid is nil or not is controlled by uuid.UUID `Value() (driver.Value, error)`, maybe override this can solve the problem for you ?

**Comment by a8m** [comment]
Hey @pzeinlinger, https://github.com/ent/ent/pull/1538 should solve the issue - see the test case there.

> handle nillable uuid should be the sql.Value's job, how you define a uuid is nil or not is controlled by uuid.UUID Value() (driver.Value, error), maybe override this can solve the problem for you ?

We wrap custom (not part of std) nillable `sql.Scanner` types with [`sql.NullScanner`](https://github.com/ent/ent/blob/master/dialect/sql/driver.go#L155-L157). This makes it possible to check if the value is NULL in the database or not.
