### ISSUE TITLE
`Default` annotation is ignored for IDs

### ISSUE THREAD

**Issue by vojta001** [ent/ent#1488]
The `Default` field annotation is silently ignored for fields named `id`.

For this entity definition
```go
func (Answer) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.Nil).
			Annotations(&entsql.Annotation{
			Default: "'uuid_generate_v4()'",
		}),
		field.UUID("notid", uuid.Nil).
			Annotations(&entsql.Annotation{
				Default: "uuid_generate_v4()",
			}),
		field.Time("somethingelse").Immutable(),
	}
}

func (Answer) Annotations() []schema.Annotation {
	return []schema.Annotation{}
}
```

the following schema is created
```go
AnswersColumns = []*schema.Column{
	{Name: "id", Type: field.TypeUUID},
	{Name: "notid", Type: field.TypeUUID, Default: "uuid_generate_v4()"},
	{Name: "somethingelse", Type: field.TypeTime},
}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
The field named `id` has no SQL default.

## Expected Behavior 🤔
The field named `id` has the specified SQL default.

## Steps to Reproduce 🕹

Steps:

1. Create an entity similar to the above
2. Run `go generate` or `go run entgo.io/ent/cmd/ent generate`
3. Inspect `ent/migrate/schema.go` or run the migration and inspect the created table

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.3  |
| Ent         | 0.8.0   |
| Database    | postgres   |
| Driver      | https://github.com/lib/pq        |

**Comment by a8m** [comment]
Hey @vojta001 and thanks for reporting this.

We should fix this and your contribution is more than welcome 😃 

The logic should be copied from here:

https://github.com/ent/ent/blob/91dda6230f8e765c7610b829956b0930f79332d6/entc/gen/type.go#L1155-L1157

To the `PK` method:

https://github.com/ent/ent/blob/91dda6230f8e765c7610b829956b0930f79332d6/entc/gen/type.go#L1185
