### ISSUE TITLE
Question: How to separate the table query?  (Horizontal table query)

### ISSUE THREAD

**Issue by 1211ciel** [ent/ent#1506]
Hello, teams :)
thank you for working hard for the awesome project.

I encountered a big problem, how to separate the table query?  (Horizontal table query)
I want to curd opreation just Like table
user_0
user_1
user_2
```
select * from user_0
```

**Comment by rotemtam** [comment]
Hi @1211ciel 
Thanks for reaching out. I'm not sure I understand what you are trying to achieve. Can you elaborate more about your use case? What are you trying to do ?

**Comment by 1211ciel** [comment]
User table, sub-table operation
If there is only one user table, store the three user information in one table.

But I want to divide the user table into 3 tables based on user ID and store them in 3 tables.
E.g:

User_0
User_1
User_2

If the user ID is 1, then
1%3 = 1 stores the user in the user_1 table.

Therefore, when querying, you need to specify the number of the table to be checked.

**Comment by rotemtam** [comment]
I see. I'm not sure ent has such facilities for entity level sharding at the moment (cc @a8m).

**Comment by 1211ciel** [comment]
Thank you for your answer~

**Comment by a8m** [comment]
Hey @1211ciel,
There's no built-in option to change the table dynamically for queries/mutations, but you can add it to your project using [external templates](https://entgo.io/docs/templates/). Be aware that some queries/mutations require more than one table (e.g. updating or querying associations).

You can use the [sql/schemaconfig](https://entgo.io/docs/feature-flags#schema-config) feature-flag as a referenced implementation, that allows storing and querying models across multiple schemas/databases.

```go
c, err := ent.Open(dialect, conn, ent.AlternateSchema(ent.SchemaConfig{
    User: "usersdb",
    Car: "carsdb",
}))
c.User.Query().All(ctx) // SELECT * FROM `usersdb`.`users`
c.Car.Query().All(ctx)  // SELECT * FROM `carsdb`.`cars`
```

Please feel free to tag me (or send me a message in [our Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53)) if you need help with this.

**Comment by 1211ciel** [comment]
Surprised, it can be done like this...
```
	wallet, err := d.DB.WaWallet.Query().Where(func(s *sql.Selector) {
		s.Where(sql.EQ(wawallet.FieldUID, uid)).
			From(sql.Table("wa_wallet_0")).Select("*")
	}).Only(context.Background())
	if err != nil {
		return nil, err
	}
	fmt.Println(wallet)
```
```
=== RUN   TestTestLogic_Test
WaWallet(id=4294967296, uid=3, username=ciel3, created_at=Sat Apr 24 18:47:35 2021, updated_at=Sat Apr 24 18:47:35 2021)
uid:3
--- PASS: TestTestLogic_Test (0.01s)
PASS
```

**Comment by 1211ciel** [comment]
Thank you~ @a8m

**Comment by a8m** [comment]
Great, closing. Ping me if you need any help with this.
