### ISSUE TITLE
Custom Entity For Join Table

### ISSUE THREAD

**Issue by birwin93** [ent/ent#1517]
Is it possible to declare the join table for a M2M relationship as its own entity? Something like this

```
// User
type User struct {
	ent.Schema
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("stores", User.Type).StorageKey(edge.Table("employees")),
	}
}

// Store
type Store struct {
	ent.Schema
}

func (Store) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("users", User.Type).StorageKey(edge.Table("employees")),
	}
}

// Custom Join Table for User <> Store
type Employee struct {
	ent.Schema
}

func (Employee) Fields() []ent.Field {
	return []ent.Field{
		field.Bool("is_owner"),
	}
}
```

When I run `go generate ./ent` then migrate, it complains that it creates duplicate `Employee` tables

**Comment by a8m** [comment]
Hey @birwin93,
Are you looking to add additional fields to the relationship, right?

It's possible to do it manually today as I did [here](https://github.com/ent/ent/pull/1518), but you can't configure the primary key on the relationship columns. Instead, you need to create an index to enforce uniqueness on the relationship columns (see my example) and the relationship table will have an additional column named `id`. 

However, this is going to be fixed soon after we'll add support for https://github.com/ent/ent/issues/400.

**Comment by a8m** [comment]
The issue was resolved with [edge schema](https://entgo.io/docs/schema-edges/#edge-schema). Thanks for the feedback @birwin93 🙏
