### ISSUE TITLE
Custom XID ID type and contrib graphql generation unexpected list of pointers.

### ISSUE THREAD

**Issue by shanna** [ent/ent#1526]
Hi, as explained on Slack I've been playing with a custom XID https://github.com/rs/xid type for Ent using the graphql contrib templates. Everything appears fine at first glance but I noticed in the graphql resolver my node IDs are a slice of pointers not a slice of values like the todo, todouuid and todopulid example so I'm worried my XID implementation may cause other generation issues in the future if it's not following Ent conventions.

Example ent + xid + graphql repo is here:
https://github.com/shanna/entxid-test

The generated code that differs is here:
https://github.com/shanna/entxid-test/blob/master/graph/schema.resolvers.go#L32

My xid wrapper type that implements the graphql interfaces is here:
https://github.com/shanna/entxid-test/blob/master/xid/xid.go

Cheers.

**Comment by alexsn** [comment]
The code in question is generated by gqlgen and I guess they use pointers for [struct types](https://github.com/shanna/entxid-test/blob/master/xid/xid.go#L17) and values for primitives. The signature in this case makes little sense as the nodes query is defined as `nodes(ids: [ID!]!): [Node]!` so clearly `ids` is a non nullable array of non nullable ids.

I'm sure this works as expect but this [pointers to values loop](https://github.com/shanna/entxid-test/blob/master/graph/schema.resolvers.go#L35-L38) is unnecessary. I suggest you open an issue with the `gqlgen` project as there's little we can do on our end.

**Comment by alexsn** [comment]
One thing you can try to avoid using a struct meaning turn:
```go
type ID struct {
	rsxid.ID
}
```
into:
```go
type ID rsxid.ID
```

**Comment by shanna** [comment]
👍 Thanks for taking a look I'll log something with gqlgen.

I started with that `type ID rsxid.ID` but Go won't delegate the `sql.Scanner` and `driver.Valuer` interfaces to the underlying type unless it's a struct so I'd have to write my own rather than use the existing implementation in the underlying library. The trade-off as you noticed is that awkward conversion from the slice of points to the slice of values copy I need to make since gqlgen generates the `[]*xid.ID` while ent generates `[]xid.ID` here: https://github.com/shanna/entxid-test/blob/0647a056d15c332228cf80833d7c5f0b8cef501e/ent/node.go#L144

**Comment by a8m** [comment]
Hey @shanna, you don't need to wrap the `xid.ID` type in order to implement the gqlgen interfaces. Instead, define the `MarshalID` and `UnmarshalID` in your `xidgql` package as follows:

```go
package xidgql

import (
	"fmt"
	"io"
	"strconv"

	"github.com/rs/xid"
	"github.com/99designs/gqlgen/graphql"
)

func MarshalID(id xid.ID) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		 _, _ = io.WriteString(w, strconv.Quote(id.String()))
	})
}

func UnmarshalID(v interface{}) (id xid.ID, err error) {
	s, ok := v.(string)
	if !ok {
		return id, fmt.Errorf("invalid type %T, expect string", v)
	}
	return xid.FromString(s)
}
```

```yaml
models:
  ID:
    model:
      - github.com/shanna/entxid-test/xidgql.ID
```

Then, the generated resolvers will look as follows:

```go
func (r *queryResolver) Node(ctx context.Context, id xid.ID) (ent.Noder, error) {
	panic(fmt.Errorf("not implemented"))
}

func (r *queryResolver) Nodes(ctx context.Context, ids []xid.ID) ([]ent.Noder, error) {
	panic(fmt.Errorf("not implemented"))
}
```

Please let me know if it does solve your problem, and if not, give me permission to your repository and I'll send you a patch.

**Comment by shanna** [comment]
Yep that works. I had no idea you could do that with gqlgen since I'm using both ent and gqlgen for the first time. Thanks for the help.

**Comment by a8m** [comment]
> Yep that works. I had no idea you could do that with gqlgen since I'm using both ent and gqlgen for the first time. Thanks for the help.

Great, would you mind adding this to our [FAQ page](https://github.com/ent/ent/blob/master/doc/md/faq.md)?
