### ISSUE TITLE
Selector should gather all errors or propagate inner error

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1529]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```go
func ApplyQuery(node *sqlgraph.Node, query string) func(s *sql.Selector) {
  return func(s *sql.Selector) {
    s.Where(sql.P(func(b *sql.Builder) {
            // this error is ignored - should just panic ?
	    b.AddError(errors.New("ERR"))
  }))
}
```

The error in Builder will just ignored.

In `func (b *Builder) join(qs []Querier, sep string) *Builder` error is ignored,
so in `func (s *Selector) Query() (string, []interface{})` all error is ignored.

Maybe `Builder.Join` also collect Querier's error ?

## Expected Behavior 🤔

select error out

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.7   |
| Database    | -   |
| Driver      | -     |

**Comment by a8m** [comment]
Agree. You're welcome to contribute this change.

Thanks 🙏
