### ISSUE TITLE
schema/field: support setting field collation 

### ISSUE THREAD

**Issue by mahmud2011** [ent/ent#1540]
Is there any way to set `Collation` for all tables at once rather than creating a `Mixin` and include it? I need to set the default `Collation` to `utf8mb4_unicode_ci` instead of `utf8mb4_bin`.

**Comment by rotemtam** [comment]
Hi
Thanks for reaching out.
You can use codegen hooks to run arbitrary logic at codegen:

https://entgo.io/docs/code-gen/

**Comment by a8m** [comment]
Hey @mahmud2011, another option is to use a [migration-hook](https://entgo.io/docs/migrate/#migration-hooks) for adding such annotation to all tables. For example:

```go
package main

import (
    "context"
    "log"

    "<project>/ent"
    "<project>/ent/migrate"

    "entgo.io/ent/dialect/sql/schema"
)

func main() {
	client, err := ent.Open("mysql", "root:pass@tcp(localhost:3306)/test")
	if err != nil {
		log.Fatalf("failed connecting to mysql: %v", err)
	}
	defer client.Close()
	ctx := context.Background()
	// Collation configuration for all tables.
	ant := &entsql.Annotation{Collation: "utf8mb4_unicode_ci"}
	// Run migration.
	err = client.Schema.Create(
		ctx,
		schema.WithHooks(func(next schema.Creator) schema.Creator {
			return schema.CreateFunc(func(ctx context.Context, tables ...*schema.Table) error {
				for _, t := range tables {
					if t.Annotation == nil {
						t.Annotation = ant
					} else {
						t.Annotation.Merge(ant)
					}
				}
				return next.Create(ctx, tables...)
			})
		}),
	)
	if err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}
}
```

Closing, but please feel free to continue the discussion or reopen if you have troubles with it. Thanks 🙏

**Comment by mahmud2011** [comment]
But it overrides all `Collation` even inline!

```go
field.String("test").
	Immutable().Annotations(entsql.Annotation{Collation: "utf8mb4_bin"})
```

The above `Collation` should override all others (Default and Hooks).

**Comment by a8m** [comment]
> But it overrides all `Collation` even inline!

That's because we don't support this option on column definition, although it's simple to add.
Do you need support for this?

**Comment by mahmud2011** [comment]
I don't need support for this in my current project but I saw this kind of inline `Collation` in other projects. I accidentally found this issue while using your migration hooks solution.

**Comment by a8m** [comment]
I can address it, but if you're interested in contributing this, the change is really small and I can guide you. Thanks

**Comment by mahmud2011** [comment]
> I can address it, but if you're interested in contributing this, the change is really small and I can guide you. Thanks

Sure

**Comment by a8m** [comment]
Great.

1. Add a `Collation` field to the `schema.Column` struct: https://github.com/ent/ent/blob/0bfaa11e2f887fa6a957d51077c3d4e0f33d57c2/dialect/sql/schema/schema.go#L167-L169
2. Set the collation field in codegen: https://github.com/ent/ent/blob/0bfaa11e2f887fa6a957d51077c3d4e0f33d57c2/entc/gen/type.go#L1155-L1157
  https://github.com/ent/ent/blob/0bfaa11e2f887fa6a957d51077c3d4e0f33d57c2/entc/gen/template/migrate/schema.tmpl#L42
3. Set it in the schema builder: https://github.com/ent/ent/blob/0bfaa11e2f887fa6a957d51077c3d4e0f33d57c2/dialect/sql/schema/mysql.go#L278

4. Add tests for it in `dialect/sql/schema/mysql_test.go`.
