### ISSUE TITLE
delete field on migrate

### ISSUE THREAD

**Issue by godcong** [ent/ent#1544]
- [X ] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I added some fields.
But I don't use it now.
And we are running in a distributed environment.
I cannot directly manipulate the database.

## Motivation 🔦

`Migrate` does not seem to deal with deleted fields.
Sometimes I delete some unnecessary fields.
Whether it is possible to add a `delete` mark in the Field or where.
Then remove these marked fields when synchronizing the database on migrate.

like this:
```
// Fields of the Favorite.
func (Favorite) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("update").Delete(),
	}
}
```

when i running `Schema.Create`
the `update` field will delete.

**Comment by a8m** [comment]
Hey @godcong,
The migration runs by default in an append-only mode. This makes it possible to rollback changes easily. 
However, when you need to delete resources (e.g. columns or indexes), you can simply pass the `migrate.Drop<T>` option. See the [docs](https://entgo.io/docs/migrate#drop-resources) for more info, or use this example:

```go
func main() {
    client, err := ent.Open("mysql", "root:pass@tcp(localhost:3306)/test")
    if err != nil {
        log.Fatalf("failed connecting to mysql: %v", err)
    }
    defer client.Close()
    ctx := context.Background()
    // Run migration.
    err = client.Schema.Create(
        ctx, 
        migrate.WithDropIndex(true),
        migrate.WithDropColumn(true), 
    )
    if err != nil {
        log.Fatalf("failed creating schema resources: %v", err)
    }
}
```

**Comment by godcong** [comment]
@a8m Thanks, i tried it.
