### ISSUE TITLE
Improve entgql

### ISSUE THREAD

**Issue by cliedeman** [ent/ent#1555]
Reduce the amount of hand written .graphql files that need to be generated

- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

* Auto generate Relay Connection types
* Auto generate Graphql object types
* Investigate auto generating resolvers
* Auto bind enums
* Generate sorting type

## Motivation 🔦

Improve the ent + gqlgen experience

First branch here: 
https://github.com/ent/contrib/pull/75/files

Without plugin:
https://github.com/ent/contrib/blob/master/entgql/internal/todo/todo.graphql
https://github.com/ent/contrib/blob/master/entgql/internal/todo/gqlgen.yml

With plugin:
[gqlgen.yml](https://github.com/ent/contrib/pull/75/files#diff-4baff3a530ed86a3187adab5a92b77418485513ec6621bee5769a9edb979ae69)
[todo.graphql](https://github.com/ent/contrib/pull/75/files#diff-0cd22c00c8955e2afeb9fdc100cd19dd7481a171f8da6f1b19bd67abe234e900)

**Comment by cliedeman** [comment]
The [PR](https://github.com/ent/contrib/pull/78) is coming along nicely

Updated samples:
[todo.graphql](https://github.com/ent/contrib/pull/78/files#diff-0cd22c00c8955e2afeb9fdc100cd19dd7481a171f8da6f1b19bd67abe234e900)
[gqlgen.yml](https://github.com/ent/contrib/pull/78/files#diff-4baff3a530ed86a3187adab5a92b77418485513ec6621bee5769a9edb979ae69)

**Comment by yonidavidson** [comment]
@cliedeman can you  split your PR into smaller parts that solve each issue?

@cliedeman maybe close this issue and split it to smaller issues?

I think that working on smaller tasks at a time we can get the easier parts faster.

**Comment by yonidavidson** [comment]
Having a look, thanks
