### ISSUE TITLE
question:Edges associates two tables with respect to the id field. 

### ISSUE THREAD

**Issue by lenuse** [ent/ent#1561]
I have three tables, I want to put the data of the three tables into a structure 

<details>
  <summary>Table defined</summary>
  <p>
CREATE TABLE "pms_brand" (
    "id" int4 NOT NULL DEFAULT nextval('pms_brand_id_seq'::regclass),
    "name" varchar NOT NULL DEFAULT ''::character varying,
    "first_letter" varchar NOT NULL DEFAULT ''::character varying,
    "sort" int4 NOT NULL DEFAULT 0,
    "factory_status" int2 NOT NULL DEFAULT 0,
    "show_status" int2 NOT NULL DEFAULT 0,
    "product_count" int4 NOT NULL DEFAULT 0,
    "product_comment_count" int4 NOT NULL DEFAULT 0,
    "created_at" timestamptz,
    "updated_at" timestamptz,
    "is_del" bool NOT NULL DEFAULT false,
    PRIMARY KEY ("id")
);

CREATE TABLE "pms_brand_attr" (
    "id" int4 NOT NULL DEFAULT nextval('pms_brand_attr_id_seq'::regclass),
    "brand_id" int4,
    "login" varchar,
    "big_pic" varchar,
    PRIMARY KEY ("id")
);

CREATE TABLE "pms_brand_story" (
    "id" int4 NOT NULL DEFAULT nextval('pms_brand_story_id_seq'::regclass),
    "brand_id" int4,
    "story" text,
    PRIMARY KEY ("id")
);
</p>
</details>

The brand_id field points to the id field in the pms_brand table 

<details>
  <summary>Brand schame is defined as follows: </summary>
  <p>
type Brand struct {
	ent.Schema
}

// Fields of the Brand.
func (Brand) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("name"),
		field.String("first_letter"),
		field.Int("sort"),
		field.Int16("factory_status"),
		field.Int16("show_status"),
		field.Int("product_count"),
		field.Int("product_comment_count"),
		field.Bool("is_del"),
	}
}

func (Brand) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixins.DefaultMixin{},
	}
}

// Edges of the Brand.
func (Brand) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("stories", BrandStory.Type).Unique(),
		edge.To("attrs", BrandAttr.Type).Unique(),
	}
}

// Annotations of the Areas, custom table name
func (Brand) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "pms_brand"},
	}
}
 </p>
</details>

<details>
  <summary>BrandAttr schame is defined as follows: </summary>
  <p>
type BrandAttr struct {
	ent.Schema
}

// Fields of the Brand_attr.
func (BrandAttr) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.Int("brand_id").Optional(),
		field.String("login"),
		field.String("big_pic"),
	}
}

// Edges of the Brand_attr.
func (BrandAttr) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("attrbody", Brand.Type).Ref("attrs").Field("brand_id").Unique().Required(),
	}
}

func (BrandAttr) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("brand_id"),
	}
}

// Annotations of the Areas, custom table name
func (BrandAttr) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "pms_brand_attr"},
	}
}
 </p>
</details>

<details>
  <summary>BrandStory schame is defined as follows: </summary>
  <p>
type BrandStory struct {
	ent.Schema
}

// Fields of the BrandStory.
func (BrandStory) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.Int("brand_id").Optional(),
		field.String("story"),
	}
}

// Edges of the BrandStory.
func (BrandStory) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("storybody", Brand.Type).Ref("stories").Field("brand_id").Unique().Required(),
	}
}

func (BrandStory) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("brand_id").
			//Edges("storybody").
			Unique(),
	}
	//return nil
}

func (BrandStory) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "pms_brand_story"},
	}
}
 </p>
</details>

Such a schema reports an error when the code is generated:
```sh
entc/gen: set "Brand" foreign-keys: mismatch optional/required config for edge "storybody" and field "brand_id"
exit status 1
ent\generate.go:3: running "go": exit status 1 
```
How should schame be defined in this situation ？

**Comment by rotemtam** [comment]
Hi @lenuse ,
Thank you for reaching out. 
Either remove the `.Optional()` from the edge fields (`brand_id`) or remove the `.Required()` modifier from the edge definitions. Since they are describing the same thing they must be compatible.
Please let me know if this resolves your issue!

**Comment by lenuse** [comment]
Thank you for your answer. I have tried both methods and can generate code. Thanks again.

**Comment by rotemtam** [comment]
You're welcome. Feel free to subscribe to our [newsletter](https://www.getrevue.co/profile/ent) to get more updates and information about the project in the future!

Closing.
