### ISSUE TITLE
How to set timezone of field default value which type is time

### ISSUE THREAD

**Issue by shallowman** [ent/ent#1567]
Mixin time fields defined as below.

```
func (TimeMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Time("created_at").Immutable().Default(NowOfGMT8),
		field.Time("updated_at").Default(helpers.NowOfGMT8).UpdateDefault(NowOfGMT8),
	}
}
```

```
func NowOfGMT8() time.Time {
	return time.Now().In(time.FixedZone("GMT", 8*3600))
}
```

Database is MySQL, ent driver is MySQL.
MySQL version is 8.0.

The fields created_at and updated_at default value are always UTC timezone datetime.
My computer and mysql server timezone are also GMT+8.
![WX20210518-150830](https://user-images.githubusercontent.com/46313752/118607287-faa0bb00-b7ea-11eb-8cd8-855e09eea7c4.png)
![54670D39-BA86-4206-AB11-3A45520C5D7C](https://user-images.githubusercontent.com/46313752/118607420-202dc480-b7eb-11eb-8eeb-168dd086ed62.png)

How can I solve this problem？

**Comment by a8m** [comment]
Hey @shallowman,
I think this is a MySQL driver configuration issue. Did you try using https://github.com/go-sql-driver/mysql#loc?

**Comment by shallowman** [comment]
> Hey @shallowman,
> I think this is a MySQL driver configuration issue. Did you try using https://github.com/go-sql-driver/mysql#loc?

Thank you very much. Slove it now.
