### ISSUE TITLE
Enum with GoType that are not strings doesn't work

### ISSUE THREAD

**Issue by naormatania** [ent/ent#1575]
Let's say I define a type that is backed by int and fulfils `ValueScanner` interface:
```golang
type Animal int

const (
	Dog Animal = iota
	Cat
)

var (
	animals = [...]string{"Dog", "Cat"}
)

func (a Animal) String() string {
	return animals[p]
}

// Value implements database/sql/driver.Valuer
func (a Animal) Value() (driver.Value, error) {
	return animals[p], nil
}

// Scan implements database/sql.Scanner
func (a *Animal) Scan(src interface{}) error {
	srcStr, ok := src.(string)
	if !ok {
		return errors.New("wrong src type")
	}
	i, ok := utils.Find(animals[:], srcStr)
	if !ok {
		return fmt.Errorf("animals is invalid: %s", srcStr)
	}
	*a = Animal(i)
	return nil
}

// Values is part of `field.EnumValues` interface in ent package
func (Animal) Values() []string {
	return animals[:]
}
```

And then I define enum field based on it:
```golang
func (Pet) Fields() []ent.Field {
	return []ent.Field{
		field.Enum("type").
			GoType(animal.Dog),
         }
}
```

The code generation works but the code doesn't compile due the following function that is created:
```golang
func AnimalValidator(a animal.Animal) error {
	switch a {
	case "Dog", "Cat":
		return nil
	default:
		return fmt.Errorf("pet: invalid enum value for type field: %q", a)
	}
}
```

According to documentation `GoType` can be either string type or any type that implements `ValueScanner` like I did. Is there any way to support such enums ?

- [ x] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by a8m** [comment]
Hey @naormatania! It's great to hear from you again 😃 

Enums are stored as strings in the database, and therefore need to be string-ish types atm. You can see an example for custom enum type here - https://github.com/ent/ent/blob/master/entc/integration/ent/schema/fieldtype.go#L212-L214

> According to documentation GoType can be either string type or any type that implements ValueScanner like I did. Is there any way to support such enums ?

I'll be happy to support this as the change is not so big according to your bug report (only the validator, right?). Do you want to contribute this change? 

---
The code that needs to be changed:

https://github.com/ent/ent/blob/0bfaa11e2f887fa6a957d51077c3d4e0f33d57c2/entc/gen/template/meta.tmpl#L132-L139


Something is follows:
```go
switch {{ $receiver }}{{ if not $f.IsString }}(){{ end }} {
```
