### ISSUE TITLE
multiple `and` condition concat generate incorrect sql

### ISSUE THREAD

**Issue by AnnatarHe** [ent/ent#1579]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

build a query with multip `where and` condition and it will output the wrong SQL

## Expected Behavior 🤔

right SQL to run

## Steps to Reproduce 🕹

1. create multip column in one table
2. create a query with many column conditions. like this:
```go
service.EntClient.Debug().Task.Query().Where(task.And(
	task.GameName("hello"),
	task.ChannelEQ(task.ChannelFoo),
	task.HasArchivesWith(archive.And(
		archive.IDGT(3),
		archive.Size(400),
	)),
	task.ArchivesCount(10),
	task.BeginAt(time.Now()),
)).All(ctx)
```

3. check the sql
```sql
SELECT DISTINCT
	`tasks`.`id`,
	`tasks`.`deleted_at`
FROM
	`tasks`
WHERE (((`tasks`.`game_name` = ?
			AND `tasks`.`channel` = ?)
		AND `tasks`.`id` IN(
			SELECT
				`archives`.`task_archives` FROM `archives`
			WHERE
				`archives`.`id` > ?
				AND `archives`.`size` = ?))
	AND `tasks`.`archives_count` = ?)
AND `tasks`.`begin_at` = ?
```
4. expect SQL like:
```sql
SELECT DISTINCT
	`tasks`.`id`,
	`tasks`.`deleted_at`
FROM
	`tasks`
WHERE
	`tasks`.`game_name` = ?
	AND `tasks`.`channel` = ?
	AND `tasks`.`id` IN(
		SELECT
			`archives`.`task_archives` FROM `archives`
		WHERE
			`archives`.`id` > ?
			AND `archives`.`size` = ?)
	AND `tasks`.`archives_count` = ?
	AND `tasks`.`begin_at` = ?
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.3  |
| Ent         | 0.8.0   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

---------

My English not so good. I hope you can understand this bug. feel free to edit my sentence in this issue.

**Comment by lenuse** [comment]
Hi @AnnatarHe 
I found the code for the problem you described in https://github.com/ent/ent/blob/master/dialect/sql/builder.go#L1462。I remember using the same design in laravel to distinguish between AND and OR

**Comment by a8m** [comment]
Thanks for reporting this @AnnatarHe. I’m giving it a look

**Comment by a8m** [comment]
Gave it a look now. Can you please explain why the SQL is incorrect? There are extra parens in the `WHERE` clause, but the query is valid.

**Comment by AnnatarHe** [comment]
sorry. I just want to simply the SQL, but leak the important information. 😂
the real SQL is:

```sql
SELECT
	COUNT(DISTINCT `tasks`.`id`)
FROM
	`tasks`
WHERE ((((`tasks`.`package_name` = ?
				AND `tasks`.`id` IN(
					SELECT
						`task_collected_by`.`task_id` FROM `task_collected_by`))
			AND `tasks`.`begin_at` >= ?)
		AND `tasks`.`begin_at` <= ?)
	AND `tasks`.`id` IN(
		SELECT
			`task_game_infos`.`task_game_info` FROM `task_game_infos`
		WHERE
			`task_game_infos`.`key` = ?
			AND JSON_CONTAINS(`values`, ?, "$") = ?))
AND `tasks`.`id` IN(
	SELECT
		`task_game_infos`.`task_game_info` FROM `task_game_infos`
	WHERE
		`task_game_infos`.`key` = ?
		AND JSON_CONTAINS(`values`, ?, "$") = ?)
```

I want is (`game_info.key` is *foo* and the value contains 1 **and** `game_info.key` is *bar* and the value contains 2)
but the SQL generated doest not respect `and`. the last `and` does not check `package_name` and something above.

**Comment by AnnatarHe** [comment]
```go
tasksQuery := service.EntClient.Debug().Task.Query()
var taskPredicates []predicate.Task
taskPredicates = append(taskPredicates, task.PackageNameEQ(*args.PackageName))

taskPredicates = append(
	taskPredicates,
	task.BeginAtGTE(startAt),
	task.BeginAtLTE(endAt),
)

var predicates []predicate.Task
for _, gi := range gameInfoList {
	if len(gi.Values) == 0 {
		continue
	}
	predicates = append(predicates, task.HasGameInfoWith(taskgameinfo.And(
		taskgameinfo.Key(gi.Key),
		func(s *sql.Selector) {
			for _, v := range gi.Values {
				s.Where(
					sqljson.ValueContains(
						taskgameinfo.FieldValues, int(v), sqljson.DotPath(""),
					),
				)
			}
		},
	)))
}
taskPredicates = append(taskPredicates, predicates...)

tasksQuery.Where(task.And(taskPredicates...)).Count(ctx)
```

**Comment by AnnatarHe** [comment]
oh, I found the bug. I should set the `predicates` type to `[]predicate.TaskGameInfo` instead `[]predicate.Task` and merge predicates by `taskGameInfo.And`. 😂

**Comment by a8m** [comment]
Great! You're welcome to join our [Slack channel](https://entgo.io/docs/slack) in the Gophers Slack. Also, if you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏
