### ISSUE TITLE
How to config two or more sql.DB separation read sql.DB or write sql.DB

### ISSUE THREAD

**Issue by dangerous1990** [ent/ent#1580]
Tx  Update Delete operate router to write DB
Query router to read DB
sorry my english is poor   hope you can understand my question .

**Comment by a8m** [comment]
Hey @dangerous1990, you can wrap the `dialect.Driver` with your own driver and implement this logic. Here's a toy example of how to achieve something like this:

```go
func main() {
	// ...
	wd, err := sql.Open(dialect.MySQL, "root:pass@tcp(<addr>)/<database>?parseTime=True")
	if err != nil {
		log.Fatal(err)
	}
	rd, err := sql.Open(dialect.MySQL, "readonly:pass@tcp(<addr>)/<database>?parseTime=True")
	if err != nil {
		log.Fatal(err)
	}
	client := ent.NewClient(ent.Driver(&multiDriver{w: wd, r: rd}))
	defer client.Close()
	// Use the client here.
}


type multiDriver struct {
	r, w dialect.Driver
}

var _ dialect.Driver = (*multiDriver)(nil)

func (d *multiDriver) Query(ctx context.Context, query string, args, v interface{}) error {
	return d.r.Query(ctx, query, args, v)
}

func (d *multiDriver) Exec(ctx context.Context, query string, args, v interface{}) error {
	return d.w.Exec(ctx, query, args, v)
}

func (d *multiDriver) Tx(ctx context.Context) (dialect.Tx, error) {
	return d.w.Tx(ctx)
}

func (d *multiDriver) BeginTx(ctx context.Context, opts *sql.TxOptions) (dialect.Tx, error) {
	return d.w.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
}

func (d *multiDriver) Close() error {
	rerr := d.r.Close()
	werr := d.w.Close()
	if rerr != nil {
		return rerr
	}
	if werr != nil {
		return werr
	}
	return nil
}
```

You can extend it, add support for multiple read replicas and add some load-balancing magic. 

Closing, but please feel free to continue the discussion or reopen if you have any trouble with it. Thanks 🙏

**Comment by a8m** [comment]
Please feel free to join our [Slack channel](https://entgo.io/docs/slack) in the Gophers Slack. Also, if you're interested to get ~monthly updates on our new releases and features, subscribe to our [newsletter](https://www.getrevue.co/profile/ent) 🙏

**Comment by dangerous1990** [comment]
@a8m Thanks you very much~~~

**Comment by a8m** [comment]
@dangerous1990, would you like to contribute this example to our [FAQ page](https://entgo.io/docs/faq/)? Thanks

cc @zeevmoney

**Comment by clalos** [comment]
Besides switching connections based on the query type, would it be possible to **manually** change the driver before running a query? There're cases where you want a read query to run on the writer database, for example, to avoid replication lags. Do you have any suggestions? Thanks

**Comment by a8m** [comment]
I'll suggest using the `context.Context` for that (as it's used in [entcache](https://github.com/ariga/entcache)). For example:


User code:
```go
// Go to read replica by default.
client.T.Query.All(ctx)

// Tell the driver to run the query on primary.
client.T.Query.All(multidrv.SkipReplica(ctx))
```

Then, on the driver code, I'd implement it as follows:

```go
package multidrv

// ...

func (d *Driver) Query(ctx context.Context, query string, args, v interface{}) error {
	c, ok := ctx.Value(ctxOptionsKey).(*ctxOptions)
	if !ok || !c.skipReplica {
		return d.r.Query(ctx, query, args, v)
	}
	return d.w.Query(ctx, query, args, v)
}
```

**Comment by clalos** [comment]
Looks great, thanks for the help! Will look into entcache as well, very promising.
