### ISSUE TITLE
execute SQL

### ISSUE THREAD

**Issue by bluegrasses** [ent/ent#1583]
How to execute SQL, such as executing TRUNCATE operation

**Comment by lenuse** [comment]
I have the same question, how do I need to execute `select ... for update`?

**Comment by a8m** [comment]
Thanks for the help @lenuse. 

@bluegrasses, you can also use the same approach mentioned in https://github.com/ent/ent/issues/85#issuecomment-542194059.


Closing, but please feel free to continue the discussion or reopen if you have any troubles with it 🙏
