### ISSUE TITLE
FR: PluckID

### ISSUE THREAD

**Issue by kyfk** [ent/ent#1593]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

```
client.SomeEnt.Query().Where(someent.IDIn(list.PluckID()...))
```

## Motivation 🔦

When I use the Where clause with xxx.IDIn, I write PluckID function every time for each entity.

```
func PluckID(list []SomeEnt) []int {
  ids := make([]int, 0, len(list))
  for _, e := range list {
    ids = append(ids, e.ID)
  }
  return ids
}
```

So I think if there's a function something like the above in the generated codes, it's helpful.

**Comment by a8m** [comment]
Hey @kyfk and thanks for proposing this feature.

You can generate this method with the following [template](https://entgo.io/docs/templates):

```go
{{ define "model/additional/pluck" }}
	{{ $slice := plural $.Name }}
	func ({{ $.Receiver }} {{ $slice }}) PluckIDs() []{{ $.ID.Type }} {
		ids := make([]{{ $.ID.Type }}, len({{ $.Receiver }}))
		for _i := range {{ $.Receiver }} {
			ids[_i] = {{ $.Receiver }}[_i].ID
		}
		return ids
	}
{{ end }}
```

And then, you can use it as follows:

```go
users := ent.Users{...}
ids := users.PluckIDs()

// Or convert a slice that was returned from ent call.
ids := ent.Users(users).PluckIDs()
```

If you are not familiar with the templates option, read about it on our website - https://entgo.io/docs/templates.

Closing, but please feel free to reopen or join our [Slack](https://entgo.io/docs/slack) channel if you need help with it. Thanks
