### ISSUE TITLE
Query in array of objects with Postgres backend

### ISSUE THREAD

**Issue by wzyjerry** [ent/ent#1594]
Hey,

I use ent with Postgres backend, and the table structure is defined as follows:

``` yaml
id: string
info[]:
  url: string
  count: int
```

Where info is an array of objects, containing two fields url and count. Now I want to query all data which url equals "x.com", the corresponding SQL is:

``` sql
SELECT * FROM tb WHERE info @> '[{"url":"x.com"}]'
```

So, I wrote the following ent query:

``` go
items, err := client.Debug().TB.Query().Where(func(s *entsql.Selector) {
  s.Where(sqljson.ValueContains(TB.FieldInfo, []interface{}{map[string]interface{}{"url", "x.com"}}))
}).All(ctx)
```

But I didn't get the desired result. I found that when using the Postgres backend, the "sqljson.ValueContains" function will call "normalizePG", which will serialize "arg" into a string when "arg" is a custom type. Next, "arg" will be serialized another time when the actual "Arg" assignment is performed, resulting in the arg of custom type in the query parameters actually sent to the database being serialized twice.
``` go
// ValueContains return a predicate for checking that a JSON
// value (returned by the path) contains the given argument.
//
//	sqljson.ValueContains("a", 1, sqljson.Path("b"))
//
func ValueContains(column string, arg interface{}, opts ...Option) *sql.Predicate {
	return sql.P(func(b *sql.Builder) {
		...
		switch b.Dialect() {
		...
		case dialect.Postgres:
			opts, arg = normalizePG(b, arg, opts)
			path.Cast = "jsonb"
			path.value(b)
			b.WriteString(" @> ").Arg(marshal(arg)) // <=== marshal twice here
		}
	})
}

// normalizePG adds cast option to the JSON path is the argument type is
// not string, in order to avoid "missing type casts" error in Postgres.
func normalizePG(b *sql.Builder, arg interface{}, opts []Option) ([]Option, interface{}) {
	if b.Dialect() != dialect.Postgres {
		return opts, arg
	}
	base := []Option{Unquote(true)}
	switch arg.(type) {
	case string:
	case bool:
		base = append(base, Cast("bool"))
	case float32, float64:
		base = append(base, Cast("float"))
	case int8, int16, int32, int64, int, uint8, uint16, uint32, uint64:
		base = append(base, Cast("int"))
	default: // convert unknown types to text.
		arg = marshal(arg) // <=== This line
	}
	return append(base, opts...), arg
}
```
In my example, deleting the default "marshal" in the "normalizePG" function can get the desired result. Now I want to know, is this the expected behavior? If so, how should I implement the requirements in the example?
Thanks for any suggestions!

**Comment by a8m** [comment]
Thanks for reporting this @wzyjerry. 

You're right. The `default` clause should be removed from this switch case:
https://github.com/ent/ent/blob/dd4792f5b30bdd2db0d9a593a977a54cb3f0c1ce/dialect/sql/sqljson/sqljson.go#L442-L444

Would you like to contribute this change?

**Comment by a8m** [comment]
Fixed with https://github.com/ent/ent/pull/1621.
