### ISSUE TITLE
How to get the executing sql statements?

### ISSUE THREAD

**Issue by wahello** [ent/ent#1610]
#### When executing .Save(), or Exec(),  how to get the generated sql statements? Sometimes,  SQL statements are need for optimization.

**Comment by a8m** [comment]
Hey @wahello, use the `client.Debug()` option to get a debug client. For example:

```go
client.Debug().User.
	Create().
	SetName(..).
	Save(ctx)
```

Closing, but please feel free to continue the discussion or join our [Slack channel](https://entgo.io/docs/slack) if you have more questions. Thanks 🙏
