### ISSUE TITLE
make Float column unsigned

### ISSUE THREAD

**Issue by mahmud2011** [ent/ent#1626]
Is there any way to make `float` column unsigned in generated sql?

```go
field.Float("amount").
    SchemaType(map[string]string{
        dialect.MySQL: "decimal(20,4)",
    }).
    Immutable(),
```

For `int` field making the field `uint` make the field `INT UNSIGNED` in SQL. How can I make field `decimal(20,4) UNSIGNED`?

**Comment by a8m** [comment]
Hey @mahmud2011, can you please try setting the `SchemaType` to `decimal(20,4) unsigned` and report if it works for you? Thanks

```go
field.Float("amount").
    SchemaType(map[string]string{
        dialect.MySQL: "decimal(20,4) unsigned",
    }).
    Immutable(),
```

**Comment by a8m** [comment]
I've added a test case for it [here](https://github.com/ent/ent/pull/1628/files) and it seems to work, so I'm closing it, but please feel free to reopen if you have any trouble with it. Thanks

**Comment by mahmud2011** [comment]
It worked. Thanks.
