### ISSUE TITLE
how atomic decrement uint64 field value

### ISSUE THREAD

**Issue by Ackerr** [ent/ent#1630]
The generated func `AddField` is useful for atomic modify field value，but if the field type is uint，this func cant use subtraction

Is there any other way to do it. Thanks

**Comment by giautm** [comment]
It's math; You can call `AddField("test", value * -1)`

**Comment by Ackerr** [comment]
Find a way

a := int64(-2)
b := uint64(a)

Then use AddField(b) to decrement value

**Comment by jesson1** [comment]
use field.Int64
