### ISSUE TITLE
How to create an entity from a struct T?

### ISSUE THREAD

**Issue by dybxin** [ent/ent#1636]
in gorm have this create operate:

```
user := User{Name: "Jinzhu", Age: 18, Birthday: time.Now()}

result := db.Create(&user)
```
have the  same operate in ent ? current i only see the following operate.

```
client.User.Create().SetName().SetAge().Save(ctx) 
```

**Comment by alexsn** [comment]
Yes, by design on mutations fields needs to be explicitly set. You can write a template transforming one to the other though dealing with zero values might be problematic (i.e. does zero values means update or don't touch).

**Comment by a8m** [comment]
These links will be useful for you, if you want to implement this:

https://entgo.io/docs/faq#how-to-create-an-entity-from-a-struct-t

https://entgo.io/docs/tutorial-todo-gql-mutation-input

**Comment by dybxin** [comment]
@alexsn @a8m thanks a lot.
