### ISSUE TITLE
Length validation counting bytes not characters, problems with unicode characters

### ISSUE THREAD

**Issue by pepusz** [ent/ent#1637]
when you are creating a field with MinLen or MaxLen attributes, the validation is calculating with the
`len(v)` is counting the bytes and with the Unicode characters, it is calculating 2 bytes. 

Suggesting to use the utf8.RuneCountInString instead of len. 

Thanks

**Comment by a8m** [comment]
Hey @pepusz and thanks for raising up this issue.

There's an example for it on our website - https://entgo.io/docs/schema-fields#validators.

```go
// MaxRuneCount validates the rune length of a string by using the unicode/utf8 package.
func MaxRuneCount(maxLen int) func(s string) error {
    return func(s string) error {
        if utf8.RuneCountInString(s) > maxLen {
            return errors.New("value is more than the max length")
        }
        return nil
    }
}

field.String("name").
    Validate(MaxRuneCount(10))
field.String("nickname").
    Validate(MaxRuneCount(20))
```

**Comment by pepusz** [comment]
thanks for the quick response
