### ISSUE TITLE
Generate pointer bool field types possible?

### ISSUE THREAD

**Issue by jljucutan** [ent/ent#1638]
I'm using a framework alongside Entgo that requires bool fields to be pointer; otherwise, the field will not be recognized. Is there any way that we can generate field type that is `*bool`? Or is there anything that I have missed. Thanks in advance.

**Comment by jljucutan** [comment]
Nevermind, it worked for some reason. How do I delete this?

**Comment by a8m** [comment]
For future readers, the [Nillable](https://entgo.io/docs/schema-fields/#nillable) option configures the field to be generated as a pointer.
