### ISSUE TITLE
Can I set the global delete method?

### ISSUE THREAD

**Issue by chenhl05** [ent/ent#1641]
In my entities, there are two fields "is_del" and "delete_time". When I delete a row, I don't really delete it, but update these two fields. 
In the query, the conditions "is_del" and "delete_time" are added automatically.
Is there any good way to implement this?

**Comment by a8m** [comment]
Hey @chenhl05 and thanks for opening this issue.

This is a duplicate of https://github.com/ent/ent/issues/252 and therefore I'm closing it. The plan is to support soft-deletion in the near future - there are a few workarounds for it suggested by ent users in the issue tracker, but we'll get to it after interceptor-hooks and the new migration framework will be added to ent. Thanks 🙏

**Comment by syssam** [comment]
@a8m any news?

**Comment by mirusky** [comment]
I'm trying the same thing, look at what I did as so far: https://github.com/ent/ent/issues/2850
