### ISSUE TITLE
CHECK constraint not working

### ISSUE THREAD

**Issue by arielitovsky** [ent/ent#1644]
After add a CHECK constraint annotation on a table does not result in the CHECK expression being added to a POSTGRES databased. I've blasted the databased to make sure it's not a migration, and can confirm the CHECK expression does not appear on the table schema.

This is what my schema looks like:

```
// Fields of the TravelNotification.
func (TravelNotification) Fields() []ent.Field {
	return []ent.Field{
		field.String("destination_country_id").MaxLen(31).NotEmpty().Comment("edge field to join destination country").Optional().Nillable(),
		field.String("destination_region_id").MaxLen(31).NotEmpty().Comment("edge field to join destination region").Optional().Nillable(),
		field.String("origin_country_id").MaxLen(31).NotEmpty().Comment("edge field to join origin country").Optional().Nillable(),
		field.String("origin_region_id").MaxLen(31).NotEmpty().Comment("edge field to join origin region").Optional().Nillable(),
	}
}


// Edges of the TravelNotification.
func (TravelNotification) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("destinationCountry", Country.Type).Unique().Field("destination_country_id").Annotations(entgql.Bind()),
		edge.To("originCountry", Country.Type).Unique().Field("origin_country_id").Annotations(entgql.Bind()),
		edge.To("destination_region", Region.Type).Unique().Field("destination_region_id").Annotations(entgql.Bind()),
		edge.To("origin_region", Region.Type).Unique().Field("origin_region_id").Annotations(entgql.Bind()),
	}
}

func (TravelNotification) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Check: "(destination_country_id IS NOT NULL AND origin_country_id IS NOT NULL) OR (destination_region_id IS NOT NULL AND origin_region_id IS NOT NULL)"},
	}
}

```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

After dropping the database and running migrations, the table schema like this:
```
create table travel_notifications
(
	id varchar not null
		constraint travel_notifications_pkey
			primary key,
	created_at timestamp with time zone not null,
	updated_at timestamp with time zone not null,
	status varchar default 'pending'::character varying not null,
	scheduled_date date not null,
	sent_at timestamp with time zone,
	sent_to_users jsonb,
	destination_country_id varchar
		constraint "travel_notifications_countries_destinationCountry"
			references countries
				on delete set null,
	origin_country_id varchar
		constraint "travel_notifications_countries_originCountry"
			references countries
				on delete set null,
	destination_region_id varchar
		constraint travel_notifications_regions_destination_region
			references regions
				on delete set null,
	origin_region_id varchar
		constraint travel_notifications_regions_origin_region
			references regions
				on delete set null
);
```

## Expected Behavior 🤔

Schema above should have the following statement included:

`CHECK (destination_country_id IS NOT NULL AND origin_country_id IS NOT NULL) OR (destination_region_id IS NOT NULL AND origin_region_id IS NOT NULL)
`

It seems like this statement does appear in schema.go:
`
"annotations":{"EntSQL":{"check":"(destination_country_id IS NOT NULL AND origin_country_id IS NOT NULL) OR (destination_region_id IS NOT NULL AND origin_region_id IS NOT NULL)"}}`

## Steps to Reproduce 🕹

1. Create file with schema above include the CHECK statement
2. Add complex CHECK statement with parenthesis (as above)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | v0.8.1-0   |
| Database    | Postgres  13.2 |
| Driver      |

**Comment by a8m** [comment]
Hey @arielitovsky and thanks for reporting this issue.

I added https://github.com/ent/ent/pull/1645 and https://github.com/ent/ent/pull/1646 which should solve this issue (+ another annotation was added named `Checks`).

But note, the current implementation creates the CHECK constraints only on table creation and it doesn't support the current migration (adding/removing constraints to/from existing tables). That's because we're writing a migration framework from scratch and don't want to invest too much time in the current implementation - I added these 2 patches to unblock you, and I hope it helped. 

Please, let me know if I can close the issue. Thanks 🙏

**Comment by arielitovsky** [comment]
@a8m thank you so much for the quick fix! 

Yes, that unblocked me. Feel free to close it.
