### ISSUE TITLE
what's wrong?

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#1682]
Dear,all

when i followed the doc to start my first ent project.
Error occued.
`go generate ./ent`
`load schema dir: missing package information for: schema
exit status 1
ent/generate.go:3: running "go": exit status 1
`
best wishes.

**Comment by a8m** [comment]
Hey @CNTWDev,
What’s your Go version? Do you have any schema files under the “ent/schema” package/directory?

**Comment by allanwakes** [comment]
My Go version is 1.16.5, and yes, I got schema file under the “ent/schema” package/directory, I've got the same problem as CNTWDev did.

**Comment by allanwakes** [comment]
Wired, I rerun `go generate ./ent`, but before that, I run `go mod tidy` first, and this time it worked. But I have no clue why `go mod tidy` was needed.

**Comment by a8m** [comment]
Hey! I think we can close this issue. Please, reopen if you still face such problems with it.
