### ISSUE TITLE
Edge field makes required field nullable in database

### ISSUE THREAD

**Issue by naormatania** [ent/ent#1688]
Before adding edge field, the required field was defined as `NOT NULL`
However once I added a required edge field for this field (https://entgo.io/docs/schema-edges#edge-field) the field was changed to be of type `NULL` which is incorrect

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Define the following schema:
```
// Fields of the Post.
func (Post) Fields() []ent.Field {
    return []ent.Field{
        field.Int("author_id"),
    }
}

// Edges of the Post.
func (Post) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("author", User.Type).
            // Bind the "author_id" field to this edge.
            Field("author_id").
            Required(),
    }
}
```

Database migration code is:
```
CREATE TABLE IF NOT EXISTS "post"(
  "author_id" BIGINT NULL,
  PRIMARY KEY("id")
);
```

## Expected Behavior 🤔

The database migration code should be:
```
CREATE TABLE IF NOT EXISTS "post"(
  "author_id" BIGINT NOT NULL,
  PRIMARY KEY("id")
);
```

## Your Environment 🌎

I also ran the migration with `WithForeignKeys(false)`

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | 0.8   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx        |

**Comment by a8m** [comment]
Hey @naormatania 👋
Sorry for the delay, but the issue was resolved with #1703 - Thanks to [github.com/atlas/ariga](https://github.com/atlas/ariga). That means if you're using MySQL and need to migrate existing columns, you should use the [`WithAtlas`](https://entgo.io/docs/migrate#atlas-integration) option.

cc @rotemtam

**Comment by naormatania** [comment]
Hey @a8m !
Would it work if I'm using Postgres ?

**Comment by a8m** [comment]
Yes.

**Comment by iwata** [comment]
@a8m Are you planning to release a new version v0.10.1?
