### ISSUE TITLE
how to check the sql error:table is locked?

### ISSUE THREAD

**Issue by godcong** [ent/ent#1695]
now i have used sqlite3.
when i insert some data into table `pins`.
the table was locked.
```
{"errors": "insert node to table \"pins\": database table is locked: pins"}
```
i want check this error, and do some processing.
ent has `NotFoundError`,But i didn't find the anything about `Locked` error.

**Comment by alexsn** [comment]
ent wraps underlying database errors so you can extract and check for those using `errors.Is` / `errors.As`.

**Comment by a8m** [comment]
Thanks, Alex ❤️ 

@godcong, if you're using `mattn/go-sqlite3`, please see: [sqlite3.Error](https://pkg.go.dev/github.com/mattn/go-sqlite3#Error) and [error number variables](https://pkg.go.dev/github.com/mattn/go-sqlite3#pkg-variables).

**Comment by a8m** [comment]
Closing, but please feel free to reopen if you have more questions. 

You're also welcome to join our [Slack channel](https://entgo.io/docs/slack/) 😃
