### ISSUE TITLE
Edges field with inconsistent string types

### ISSUE THREAD

**Issue by RobinCodeX** [ent/ent#1699]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

After the creation of the following table, Order's id is `char(12)`, **order_id** type is `varchar(12)`, **order_id** should also be `char(12)`, whether I think it might be a bug?

Order Table:
```go
func (Order) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").MinLen(12).MaxLen(12).
			SchemaType(map[string]string{
				dialect.MySQL: "char(12)",
			}),
	}
}

func (Order) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("refund_order", RefundOrder.Type).Unique(),
	}
}
```
RefundOrder Table:
```go
func (RefundOrder) Fields() []ent.Field {
	return []ent.Field{
		field.String("order_id").MinLen(12).MaxLen(12).Optional().
			SchemaType(map[string]string{
				dialect.MySQL: "char(12)",
			}),
	}
}

func (RefundOrder) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("order", Order.Type).
			Ref("refund_order").
			Field("order_id").
			Unique(),
	}
}
```

I tried using StorageKey with the same result.
```go
func (Order) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("refund_order", RefundOrder.Type).StorageKey(edge.Column("order_id")).Unique(),
	}
}
func (RefundOrder) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("order", Order.Type).
			Ref("refund_order").
			Unique(),
	}
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.4  |
| Ent         |  v0.8.1-0.20210702044153-1e90c51eb58f   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this issue @RobinCodeX 🙏 

https://github.com/ent/ent/pull/1701 fixed the issue, and you're welcome to update to `master` and reopen if you have any other problems with it. 

You're also welcome to join our [Slack channel](https://entgo.io/docs/slack/) 😃
