### ISSUE TITLE
go vet fails: node.go:727:7: load passes lock by value: x/y/z.tables contains sync.Once contains sync.Mutex

### ISSUE THREAD

**Issue by advanderveer** [ent/ent#1700]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When running `go vet ./...` on the generated code results in the following error: ```model/node.go:727:7: load passes lock by value: github.com/crewlinker/gql/model.tables contains sync.Once contains sync.Mutex```

this is the part in node.go that it is talking about 
```
....

func (tables) load(ctx context.Context, drv dialect.Driver) ([]string, error) {
	rows := &sql.Rows{}
	query, args := sql.Dialect(drv.Dialect()).
		Select("type").
....
```

## Expected Behavior 🤔
Generated code should pass `go vet checks`

## Steps to Reproduce 🕹

I currently don't have time to make a minimal repo, but I think it happens whenever the Grapqhl Node generation functionality is enabled. This is how my generate looks like: 

```
package main

import (
	"log"
	"os"
	"path/filepath"

	"entgo.io/contrib/entgql"
	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

// main will generate the code required for Ent while integrating with glqgen
func main() {
	wd, _ := os.Getwd()
	log.Printf("workdir: %s", wd)
	if err := entc.Generate(filepath.Join(wd, "domain", "schema"), &gen.Config{
		Package: "github.com/crewlinker/gql/model",
		Target:  filepath.Join(wd, "model"),
		Features: []gen.Feature{
			gen.FeaturePrivacy,
			gen.FeatureEntQL,
			gen.FeatureSnapshot,
		},

		// Enable Deep integration for GraphQL standards
		Templates: entgql.AllTemplates,
	}); err != nil {
		log.Fatalf("running ent codegen: %v", err.Error())
	}
}
```

## Your Environment 🌎

Go mod `go.mod`: 

```
module github.com/crewlinker/gql

go 1.16

require (
	entgo.io/contrib v0.0.0-20210503071007-94b55dee6550
	entgo.io/ent v0.8.0
	github.com/99designs/gqlgen v0.13.0
	github.com/caarlos0/env/v6 v6.6.2
	github.com/hashicorp/go-multierror v1.1.1
	github.com/jackc/pgx/v4 v4.11.0
	github.com/lestrrat-go/jwx v1.2.1
	github.com/mattn/go-sqlite3 v1.14.6
	github.com/rs/cors v1.7.0
	github.com/stretchr/testify v1.7.0
	github.com/vektah/gqlparser/v2 v2.1.0
	github.com/vmihailenco/msgpack/v5 v5.3.4
	go.uber.org/fx v1.13.1
	go.uber.org/zap v1.17.0
	golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9
)
```

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.5  |
| Ent         | see go.mod exert   |
| Database    | Postgres/Sqlite   |
| Driver      | see go.mod        |

**Comment by a8m** [comment]
Thanks for reporting this @advanderveer. The receiver is not used in this function, but it still needs to be changed to a pointer receiver. Would you like to contribute a fix?

https://github.com/ent/contrib/blob/5fd78e4/entgql/template/node.tmpl#L341

**Comment by advanderveer** [comment]
Thank you for the quick response @a8m a colleague of mine contribute the fix. Possibly today, else next week

**Comment by a8m** [comment]
Sure, the fix is super simple, but you're (or your colleague) more than welcome to join our [Slack channel](https://entgo.io/docs/slack/) and ping me if you have any questions 😃

**Comment by akfaew** [comment]
@a8m There we go: https://github.com/ent/contrib/pull/105

**Comment by a8m** [comment]
Thanks, @akfaew! Please see my comment https://github.com/ent/contrib/pull/105#issuecomment-877173374

**Comment by a8m** [comment]
Closing as https://github.com/ent/contrib/pull/105 fixed the issue. Thanks, @akfaew! 🙏 

@all-contributors please add @akfaew for code
