### ISSUE TITLE
Auto-Rollback in Tests

### ISSUE THREAD

**Issue by mvrahden** [ent/ent#1707]
Hi all and thanks for maintaining this project.

I might have overseen it in the docs or turorials, but I'm missing an auto-rollback option (cleanup hook or something?) for tests.
I've also searched this repo, but wasn't able to find anything related.

I followed the tutorial and expanded now to my own use case.
So far I liked what I'm seeing.
But after adding more test cases I observe that state is being transferred from one test case to another.
I'm using a test container for my db in my setup and would enjoy an option to undo the state changes – to not work with a dirty db.

Is there a simple built-in way to achieve this?

P.S: I'd be happy to contribute!

**Comment by mvrahden** [comment]
From slack [thread response](https://gophers.slack.com/archives/C01FMSQDT53/p1626006022090100) the recommended way is to use sqlite as in-memory db for unittests and test containers with temporary named schemas for integration tests (cleaning up the named schemas afterwards).

**Comment by arielitovsky** [comment]
A another option to consider is to use https://github.com/cockroachdb/copyist although we've had mixed results with it (could just be our implementation, though)
