### ISSUE TITLE
UpdateDefault func was not supported without Time

### ISSUE THREAD

**Issue by godcong** [ent/ent#1718]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Due to time zone issues, I use `Int64` to save the time.
But I found that Int64 has no `UpdateDefault` function.

## Motivation 🔦

I hope this function can be used in scenarios other than Time.
After looking at the implementation, it doesn't seem to be complicated, but I don't know if it will affect other functions.

otherwise, `DefaultFunc` now used interface{} as a parameter
Whether to change to use the corresponding type is more convenient to use
like:
```go
func (b *int64Builder) DefaultFunc(fn interface{}) *int64Builder {
	b.desc.Default = fn
	return b
}
```
=>
```go
func (b *int64Builder) DefaultFunc(fn func()int64) *int64Builder {
	b.desc.Default = fn
	return b
}
```

**Comment by a8m** [comment]
Hey @godcong, and thanks for proposing this.

I don't mind adding it, but if you want to contribute this change, I'll be happy to support you if you need any help. 

BTW, if you're blocked on this atm, you can use [ent/hooks](https://entgo.io/docs/hooks/#schema-hooks) for setting this field for you until the `DefaultFunc` option will be supported.

**Comment by godcong** [comment]
The last version implements this.
i think this can be closed?

**Comment by a8m** [comment]
Yes!  This is actually a really useful feature. I already use it in a few places.

Thanks again for your contribution @godcong.
