### ISSUE TITLE
I have some problems when I want to query through groupby

### ISSUE THREAD

**Issue by owen-gxz** [ent/ent#1719]
When I do statistics, for example

```
sql: 
SELECT
    count(*) as count,
    sum(price) as price,
    DATE(created_at) createTime
FROM
    xxx
where created_at between '2021-06-01' and '2021-06-31' and state in ('2','3')
GROUP BY
    DATE(created_at)
ORDER BY
    DATE(created_at) DESC;

code: 
  data:=make(map[string]interface{})
  err:=db.xxxx.Query().Where(xxxx.CreatedAtLT(end),xxx.CreatedAtGT(nt)).select("DATE(created_at) as data").
    Order(ent.Desc("DATE(created_at)")).GroupBy("DATE(created_at)").Aggregate(ent.Count(),ent.Sum("price")).Scan(context.Background(),&data)
```
I found it wrong

**Comment by owen-gxz** [comment]
@a8m can you help me?

**Comment by a8m** [comment]
Hey @owen-gxz and thanks for tagging me. I missed this issue.

Regarding `BETWEEN` and `NOT BETWEEN`, they are both equivalents to `a >= x AND a <= y` and `a < x OR a > y`, so I didn't see any reason to add them to the API. However, you can still use the `BETWEEN` operator using a [custom predicate](https://entgo.io/docs/predicates/#custom-predicates).

Regarding your query - use the [`sql/modifier` feature flag](https://entgo.io/docs/feature-flags/#custom-sql-modifiers) to customize the executed query as follows:

```go
var v []struct {
    Count     int       `json:"count"`
    Price     int       `json:"price"`
    CreatedAt time.Time `json:"created_at"`
}
client.User.
    Query().
    Where(
        user.CreatedAtGTE(x),
        user.CreatedAtLTE(y),
        user.StateIn("2", "3"),
    ).
    Modify(func(s *sql.Selector) {
        s.Select(
            sql.As(sql.Count("*"), "count"),
            sql.As(sql.Sum("price"), "price"),
            sql.As("DATE(created_at)", "created_at"),
        ).
        GroupBy("DATE(created_at)").
        OrderBy(sql.Desc("DATE(created_at)"))
    }).
    ScanX(ctx, &v)
``` 

Please, see the full doc here: https://entgo.io/docs/feature-flags/#custom-sql-modifiers

**Comment by a8m** [comment]
Closing, but please reopen if you still have troubles with it, or join our [Slack channel](https://entgo.io/docs/slack) and feel free to ask questions there.

**Comment by owen-gxz** [comment]
sorry!  @a8m  After I modified generate.go, I didn't find the modifier method. Why?
```
package ent
//go:generate go run  -mod=mod entgo.io/ent/cmd/ent generate --feature sql/modifier ./schema
```

**Comment by a8m** [comment]
Please update to the latest master using `go get entgo.io/ent@master` and re-run codegen.
