### ISSUE TITLE
get constraint failed error when use 02M with edge.To specifies Field

### ISSUE THREAD

**Issue by godcong** [ent/ent#1728]
refer to: https://entgo.io/docs/schema-edges/#o2m-same-type, and wrote the 02M relationship table。
all test was done。
then，i added `Field("parent_id")` 。
finally，i failed to insert data successfully。

```
// AdminSysMenu holds the schema definition for the AdminSysMenu entity.
type AdminSysMenu struct {
	ent.Schema
}

// Fields of the AdminSysMenu.
func (AdminSysMenu) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Unique(), //ID
		field.UUID("parent_id", uuid.UUID{}).Optional(),        
		field.String("name").Default(""),                                             
	}
}

// Edges of the AdminSysMenu.
func (AdminSysMenu) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", AdminSysMenu.Type).
			From("parent").
			Unique().
			Field("parent_id"),
	}
}
```

test code:
```
func TestMenu(t *testing.T) {
	r := admindb.AdminSysMenu.Create().SetAdminSysMenu(&ent.AdminSysMenu{
		Name: "root",
	}).SaveX(context.TODO())
	t.Logf("%+v", r)

	m1 := admindb.AdminSysMenu.Create().SetParent(r).SetAdminSysMenu(&ent.AdminSysMenu{
		Name: "m1",
	}).SaveX(context.TODO())
	t.Logf("%+v", m1)
	m2 := admindb.AdminSysMenu.Create().SetParent(r).SetAdminSysMenu(&ent.AdminSysMenu{
		Name: "m2",
	}).SaveX(context.TODO())
	t.Logf("%+v", m2)

}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
error:
```
panic: ent: constraint failed: insert node to table "admin_sys_menus": Error 1452: Cannot add or update a child row: a foreign key constraint fails (`testcenter2`.`admin_sys_menus`, CONSTRAINT `admin_sys_menus_admin_sys_menus_children` FOREIGN KEY (`parent_id`) REFERENCES `admin_sys_menus` (`id`) ON DELETE SET NULL) [recovered]
```

## Expected Behavior 🤔

The data is successfully inserted and the relationship is established.

## Steps to Reproduce 🕹

Steps:

1. generate the code.(OK)
2. run data migration，`Schema.Create(
		context.TODO(),
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
	)`（OK）
3. run the test.(Failed)

different with two insert:
assigned Field("parent_id")
```
INSERT INTO `admin_sys_menus` (`name`, `icon`, `slug`, `url`, `active`, `description`, `sort`, `parent_id`, `id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) args=[root      0 00000000-0000-0000-0000-000000000000 f1565394-20f9-4499-8d52-7e14619787e6]
```

not assigned
```
INSERT INTO `admin_sys_menus` (`name`, `icon`, `slug`, `url`, `active`, `description`, `sort`, `id`) VALUES (?, ?, ?, ?, ?, ?, ?, ?) args=[root      0 64cea14c-5298-4008-bdb9-9388ec24b802]
```

ps: i changed `id`,`parent_id` to int,get the same faild.
then i added `Nillable()` to `parent_id`, all test was done.

i search the issue ,found #1681 can set uuid as `nil`.
but, the last release version `uuid` can't set `Nillable()`. when can add it with release?
and ,this is different from the example:
https://entgo.io/docs/schema-edges/#o2m-same-type.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.6  |
| Ent         | 0.8.0   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this @godcong. I think it's related to https://github.com/ent/ent/issues/1723, but I'll give it a look and update you, thanks.

**Comment by a8m** [comment]
Hey @godcong, I was not able to reproduce this issue (this functionality is basic, and it's cover in our integration tests). I'm pretty sure I know what's the reason for this.

Can you try running your example as follows:

```go
func TestMenu(t *testing.T) {
	r := admindb.AdminSysMenu.Create().
		SetAdminSysMenu(&ent.AdminSysMenu{
			Name: "root",
		}).
		SaveX(context.TODO())
	t.Logf("%+v", r)

	m1 := admindb.AdminSysMenu.Create().
		SetAdminSysMenu(&ent.AdminSysMenu{
			Name: "m1",
		}).
		SetParent(r).
		SaveX(context.TODO())
	t.Logf("%+v", m1)
	m2 := admindb.AdminSysMenu.Create().
		SetAdminSysMenu(&ent.AdminSysMenu{
			Name: "m2",
		}).
		SetParent(r).
		SaveX(context.TODO())
	t.Logf("%+v", m2)
}
```

As you can see, I replaced the order of `SetAdminSysMenu` and `SetParent`, and I think that your custom function `SetAdminSysMenu` overrides the edge-field with zero IDs (see the args in your logs above).

**Comment by godcong** [comment]
@a8m 
I commented out the optional parameters.
all test was ok.
