### ISSUE TITLE
How to update int column increase by 1.

### ISSUE THREAD

**Issue by wahello** [ent/ent#1748]
### How to update int column increase by 1 or some.

**Comment by wahello** [comment]
Just like SQL `UPDATE users set age=age+1 where id=100000`

**Comment by a8m** [comment]
Hey @wahello, use the `Add<Field>` setter. For example:

```go
t = t.Update().AddPriority(1).SaveX(ctx)
```

**Comment by a8m** [comment]
Closing, but please feel free to reopen if you still need help, or join our [Slack channel](https://entgo.io/docs/slack/). Thanks 🙏
