### ISSUE TITLE
Specifying ORDER BY with UNION results in an sql syntax error

### ISSUE THREAD

**Issue by timoha** [ent/ent#1754]
- [ ] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When doing `sql.Select().From(tableA).Union(tableB).OrderBy()` the `ORDER BY` clause is appended to `tableA`'s select instead of on the entire union (at the end of the SQL query).

## Expected Behavior 🤔

`OrderBy()` should be applied on the entire union.

## Steps to Reproduce 🕹

Steps:

1. Place into `dialect/sql/builder_test.go`:
```
func TestSelector_UnionOrderBy(t *testing.T) {
	table := Table("users")
	query, _ := Dialect(dialect.Postgres).
		Select("*").
		From(table).
		Where(EQ("active", true)).
		Union(Select("*").From(Table("old_users1"))).
		OrderBy(table.C("whatever")).
		Query()
	require.Equal(t, `SELECT * FROM "users" WHERE "active" = $1 UNION SELECT * FROM "old_users1" ORDER BY "users"."whatever"`, query)
}
```
2. go test -run TestSelector_UnionOrderBy

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          |  1.16.5  |
| Ent         | v0.8.1-0.20210719122135-201c7301aa86   |
| Database    | PostgreSQL   |
| Driver      | github.com/jackc/pgx/v4/stdlib        |

**Comment by a8m** [comment]
Thanks for reporting this @timoha. The UNION clause needs to be moved before the ORDER BY according to the PostgreSQL syntax. Please, feel free to send a patch https://github.com/ent/ent/blob/master/dialect/sql/builder.go#L2327-L2340

**Comment by squarebat** [comment]
Seems straight forward. I can take this up.

**Comment by a8m** [comment]
Good ahead, and please ping me on our [Slack channel](https://entgo.io/docs/slack/) if you need any support with this. Thanks 🙏
