### ISSUE TITLE
Annotation override of default ignored for ID field

### ISSUE THREAD

**Issue by captainbeardo** [ent/ent#1759]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When defining a schema that overrides the ID field to make it a UUID, using an Annotation to override the default does not work:

```
type Entity struct {
	ent.Schema
}

func (Entity) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New).Annotations(&entsql.Annotation{
			Default: "gen_random_uuid()",
		}),
		field.UUID("not_id", uuid.UUID{}).Default(uuid.New).Annotations(&entsql.Annotation{
			Default: "gen_random_uuid()",
		}),
	}
}
```

Generated SQL has the correct default for `not_id` but not for `id`:

```
BEGIN;
CREATE TABLE IF NOT EXISTS "entities"("id" uuid NOT NULL, "not_id" uuid NOT NULL DEFAULT gen_random_uuid(), PRIMARY KEY("id"));
COMMIT;
```

## Expected Behavior 🤔

I would expect the generated SQL to include the `DEFAULT gen_random_uuid()` for the `id` field.

## Steps to Reproduce 🕹

Steps:

1. Define schema as above
2. Examine SQL generated with `client.Schema.WriteTo`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.6  |
| Ent         | 0.8.0  |
| Database    | Postgres   |
| Driver      | github.com/lib/pq        |

**Comment by a8m** [comment]
Hey @captainbeardo, the issue was fixed with https://github.com/ent/ent/pull/1492. Updating to the latest master using `go get entgo.io/ent@master` will solve the problem. 

Closing, but please reopen if you have any issues with it. You're also welcome to join our [Slack channel](https://entgo.io/docs/slack/) :shipit:

**Comment by captainbeardo** [comment]
Thanks for the quick response @a8m.
