### ISSUE TITLE
I want to know the usage scenarios of "edge.To" and "edge.From" so that I can better understand how to use it correctly。

### ISSUE THREAD

**Issue by TNED** [ent/ent#1776]
The description of the document is not convenient for me to understand, I don't understand when I should use `edge.From` instead of `edge.To`. Because you can establish a relationship using `edge.To`.

**Comment by rotemtam** [comment]
Hi @TNED ,

Thanks for reaching out. 

In general, `edge.To` is the "owner" of the edge, and `edge.From` is not mandatory, provides a "virtual" backreference that is very convenient to use.  With O2M, relations for example, the entity that has the `.To` side of the edge will have the FK column.

You can find the full documentation including full examples on how to establish relations between two entities in the [Edge Relationships Guide](https://entgo.io/docs/schema-edges/#relationship).

Let me know if this answers your question or if you need any more assistance.
