### ISSUE TITLE
Create fails on long field names

### ISSUE THREAD

**Issue by PlusMinus0** [ent/ent#1777]
Ent generated a very long column name for one of my tables. This appears to confuse `Schema.Create()`, at least in combination with postgresql.

```
2021/07/28 08:49:21 Tx(a3419283-17c0-4624-a24e-23d82ff11237).Exec: query=ALTER TABLE "process_step_references" ADD COLUMN "workpiece_type_process_step_reference_list_process_step_reference" bigint UNIQUE NULL args=[]
2021/07/28 08:49:21 Tx(a3419283-17c0-4624-a24e-23d82ff11237): rollbacked
2021/07/28 08:49:21 sql/schema: alter table "process_step_references": ERROR: column "workpiece_type_process_step_reference_list_process_step_referen" of relation "process_step_references" already exists (SQLSTATE 42701)
```

I am assuming, `Schema.Create()` checks, if _very_long_column_name_ (>64) exists (client side, maybe) - it does not, because it is named _very_long_column_na_ (cut after 64 characters). Then it tries to create it, psql trims it, says the column exists and create throws an error.

Workaround: Use shorter column names.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
`Schema.Create()` does not try to alter the table by creating the very long column name.

## Expected Behavior 🤔
`Schema.Create()` tries to alter the table by creating a column with a very long name, but fails, because a shortened version of this column exists

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.6  |
| Ent         | 0.8.0   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/jackc/pgx      |

**Comment by a8m** [comment]
Hey @PlusMinus0 and thanks for reporting this. As you mentioned, one option is to use shorter field names, but another option is to define a custom storage key (column name) with a shorter version of the field. For example:

```go
field.String("workpiece_type_process_step_reference_list_process_step_reference").
	StorageKey("shorter_name")
```

Closing, but please feel free to reopen if you still have questions, or join our [Slack channel](https://entgo.io/docs/slack).
