### ISSUE TITLE
Failed to start gremlin container

### ISSUE THREAD

**Issue by seiichi1101** [ent/ent#1807]
Gremlin container failed to start when I run command like below. 

```
docker-compose -f ./entc/integration/compose/docker-compose.yaml up --build gremlin
```

I think the settings are not correct to the latest image of `tinkerpop/gremlin-server`

If `ent` is intended to work with Amazon Neptune, fixing the gremlin version `3.4.11` would be better.
Because Amazon Neptune latest engine version still supports `3.4.11`.

https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.0.5.0.html

And in version `3.4.11`, both docker and test code work well.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I got errors.

```
gremlin_1     | [ERROR] GremlinServer - Configuration file at conf/gremlin-server.yaml could not be found or parsed properly. [Cannot create property=scriptEvaluationTimeout for JavaBean=org.apache.tinkerpop.gremlin.server.Settings@42e99e4a
gremlin_1     |  in 'reader', line 18, column 1:
gremlin_1     |     host: 172.20.0.2
gremlin_1     |     ^
gremlin_1     | Unable to find property 'scriptEvaluationTimeout' on class: org.apache.tinkerpop.gremlin.server.Settings
gremlin_1     |  in 'reader', line 20, column 26:
gremlin_1     |     scriptEvaluationTimeout: 30000
gremlin_1     |                              ^
gremlin_1     | ]
compose_gremlin_1 exited with code 0
```

## Expected Behavior 🤔

Gremlin container can run.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go version |
| Ent         | master(6e48129b2974c1bfa14d4efcd182ed5bcc5c7256)   |

**Comment by a8m** [comment]
Thanks for sending a patch for this @seiichi1101 

@alexsn, would you mind adding me to the [entgo org](https://hub.docker.com/u/entgo) at Dockerhub? Thanks 🙏

**Comment by alexsn** [comment]
> @alexsn, would you mind adding me to the [entgo org](https://hub.docker.com/u/entgo) at Dockerhub? Thanks 🙏
sure, what's your docker id?

**Comment by seiichi1101** [comment]
Any updates?
@a8m, are you still going to use Docker Hub?

**Comment by a8m** [comment]
> > @alexsn, would you mind adding me to the [entgo org](https://hub.docker.com/u/entgo) at Dockerhub? Thanks 🙏
> 
> sure, what's your docker id?

mashraki. Thanks @alexsn

**Comment by alexsn** [comment]
> > > @alexsn, would you mind adding me to the [entgo org](https://hub.docker.com/u/entgo) at Dockerhub? Thanks 🙏
> > 
> > 
> > sure, what's your docker id?
> 
> mashraki. Thanks @alexsn

Added.

**Comment by yonidavidson** [comment]
I updated the image in docker-hub to be 3.4.11 
![image](https://user-images.githubusercontent.com/5472778/131691486-2cfbd3ff-9319-461c-a80d-ee2c7ecd8347.png)

[dockerhub entgo/gremlin-server](https://hub.docker.com/repository/docker/entgo/gremlin-server)

All that is left now is just to update the integration test (update the dockerfile in the integration test).
@seiichi1101 can you please update your PR just to update that?
Thanks.

**Comment by a8m** [comment]
Thanks @yonidavidson, @alexsn, and @seiichi1101 🙏
