### ISSUE TITLE
field.Time("updated_at").Default(time.Now)  time.now timezone

### ISSUE THREAD

**Issue by febelery** [ent/ent#1812]
my time.now is eg: `2021-08-06 11:12:56.274314815 +0800 CST m=+0.570271470`
bu insert to sql time is: `2021-08-06 03:12:56`, i want to set `2021-08-06 11:12:56`

how to set **timezone** ?

**Comment by MaxToby** [comment]
```
  field.Time("updated_at").Default(func() time.Time {
      l, _ := time.LoadLocation("America/Adak")
      return time.Now().In(l)
  })
```

**Comment by a8m** [comment]
Hey @febelery!

I think it can be done with MySQL driver configuration. Can you please try the suggestion mentioned in https://github.com/ent/ent/issues/1567#issuecomment-842952403 and report if it solves the issue? Thanks

> I think this is a MySQL driver configuration issue. Did you try using https://github.com/go-sql-driver/mysql#loc?

**Comment by febelery** [comment]
thank you, problem solved
