### ISSUE TITLE
MySQL: Does ent support query tags in struct?

### ISSUE THREAD

**Issue by wangqi811** [ent/ent#1823]
In database the column is named "name"
entity fields:
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").MaxLen(50),
}
 but when I do the specific query and want to fetch the data with the key "product_name"
type Item struct {
        ProductName string `json:"product_name"`
}
the query is like below:
client.Query().Select(product.FieldName).Scan(ctx, &item)

Then an error(sql/scan: missing struct field for column: name (name)) occurs.

How can I solve the problem? Thanks!

**Comment by a8m** [comment]
Hey @wangqi811, you can solve it using the `sql` struct-tag. For example:

```go
var v []struct {
	ProductName string `json:"product_name" sql:"name"`
}
client.Query().Select(product.FieldName).Scan(ctx, &v)
```

Closing, but please feel free to reopen if you still need help with that. You're also welcome to join our [Slack channel](https://entgo.io/docs/slack/) 😃

**Comment by wangqi811** [comment]
Thanks @a8m I will be glad if the document has more specific information about this. I didn't see it from the document~

**Comment by a8m** [comment]
👍 

Would you like to contribute this documentation change to ent? It can be added to https://github.com/ent/ent/blob/master/doc/md/crud.md#field-selection

**Comment by wangqi811** [comment]
My pleasure! I'll do this on weekends~

**Comment by a8m** [comment]
Reminder.

@zeevmoney, @yonidavidson - you're also welcome to take this issue. Thanks 🙏
