### ISSUE TITLE
OnConflict cannot get correct ID and ForUpdate return error on sqlite

### ISSUE THREAD

**Issue by godcong** [ent/ent#1830]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

Because sqlite3 often has lock table problems.
So I want to streamline my Insert code as much as possible.
I don't know if this is a database problem or ent needs to be fixed

## Steps to Reproduce 🕹

this is the two failed case:
1:    ForUpdate error: near "UPDATE": syntax error
```
	all, err := m.Pin.Query().ForUpdate().All(ctx)
	if err != nil {
		return nil, err
	}
```

2:    OnConflictColumns get 0 with id，
I checked the db and confirmed that the value `rid` related value has been successfully updated:
```
create := m.Pin.Create().SetPin(p)
	create.OnConflictColumns(pin.FieldRid).Update(func(upsert *ent.
		PinUpsert) {
                //do dosomthing
	})
	first, err := create.Save(ctx)
	if err != nil {
		return nil, err
	}
        //first.ID is 0

      or

	create := m.Pin.Create().SetPin(p)
	id, err := create.OnConflictColumns(pin.FieldRid).Update(func(upsert *ent.
	PinUpsert) {
		upsert.SetRid(p.Rid)
		upsert.SetStatus(p.Status)
		upsert.SetStep(p.Step)
		upsert.SetPriority(p.Priority)
		upsert.SetRelate(p.Relate)
		upsert.SetUpdatedUnix(p.UpdatedUnix)
		upsert.SetComment(p.Comment)
	}).ID(ctx)
        //id is 0
```
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.6  |
| Ent         | 0.9.0   |
| Database    | sqlite3 |
| Driver      | https://github.com/mattn/go-sqlite3 1.14.8 |

**Comment by rotemtam** [comment]
Hey @godcong ,

Thanks for reporting this. I'm looking into it

**Comment by rotemtam** [comment]
Hi @godcong,

I am able to reproduce the first issue. Indeed, "FOR UPDATE" isn't supported in SQLite and the generated SQL is invalid in this case. I'm thinking out loud, should a special error type for unsupported featured be returned here? (cc @a8m )

Regrading your second case, I'm tried to reproduce it with a test, but I haven't been able to do so:

```go
func TestSqlLite(t *testing.T) {
	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	ctx := context.TODO()
	id := client.User.Create().
		SetEmailAddress("rotem@entgo.io").
		SetFullName("Rotem Tamir").
		OnConflictColumns(user.FieldEmailAddress).
		Update(func(upsert *ent.UserUpsert) {
			upsert.SetEmailAddress("y")
		}).IDX(ctx)
	fmt.Println(id)
	if id == 0 {
		t.Fatalf("returned ID should not be zero")
	}
}
```
Output:
```
=== RUN   TestSqlLite
1
--- PASS: TestSqlLite (0.00s)
PASS
```

Can you provide a more complete example?

**Comment by godcong** [comment]
> Hi @godcong,
> 
> I am able to reproduce the first issue. Indeed, "FOR UPDATE" isn't supported in SQLite and the generated SQL is invalid in this case. I'm thinking out loud, should a special error type for unsupported featured be returned here? (cc @a8m )
> 
> Regrading your second case, I've tried to reproduce it with a test, but I haven't been able to do so:
> 
> ```go
> func TestSqlLite(t *testing.T) {
> 	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
> 	ctx := context.TODO()
> 	id := client.User.Create().
> 		SetEmailAddress("rotem@entgo.io").
> 		SetFullName("Rotem Tamir").
> 		OnConflictColumns(user.FieldEmailAddress).
> 		Update(func(upsert *ent.UserUpsert) {
> 			upsert.SetEmailAddress("y")
> 		}).IDX(ctx)
> 	fmt.Println(id)
> 	if id == 0 {
> 		t.Fatalf("returned ID should not be zero")
> 	}
> }
> ```
> 
> Output:
> 
> ```
> === RUN   TestSqlLite
> 1
> --- PASS: TestSqlLite (0.00s)
> PASS
> ```
> 
> Can you provide a more complete example?

i think, the case 2 must run on have duplicate `FieldEmailAddress`
if not it only run create,will not go to `OnConfict` case.

**Comment by rotemtam** [comment]
Hey @godcong ,

I've modified my test to first create the entity:
```go
func TestSqlLite(t *testing.T) {
	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	ctx := context.TODO()
	u := client.User.Create().
		SetEmailAddress("rotem@entgo.io").
		SetFullName("Rotem Tamir").
		SaveX(ctx)
	fmt.Println(u.ID)
	if u.ID == 0 {
		t.Fatalf("returned ID should not be zero")
	}
	id := client.User.Create().
		SetEmailAddress("rotem@entgo.io").
		SetFullName("Rotem Tamir").
		OnConflictColumns(user.FieldEmailAddress).
		Update(func(upsert *ent.UserUpsert) {
			upsert.SetEmailAddress("z")
		}).IDX(ctx)
	if id == 0 {
		t.Fatalf("returned ID should not be zero")
	}
	fmt.Println(id)
}
```
Running:
```
=== RUN   TestSqlLite
1
1
--- PASS: TestSqlLite (0.00s)
PASS
```

Can you try to create a minimal reproducible example that includes a minimal schema and a test?

**Comment by godcong** [comment]
> Hey @godcong ,
> 
> I've modified my test to first create the entity:
> 
> ```go
> func TestSqlLite(t *testing.T) {
> 	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
> 	ctx := context.TODO()
> 	u := client.User.Create().
> 		SetEmailAddress("rotem@entgo.io").
> 		SetFullName("Rotem Tamir").
> 		SaveX(ctx)
> 	fmt.Println(u.ID)
> 	if u.ID == 0 {
> 		t.Fatalf("returned ID should not be zero")
> 	}
> 	id := client.User.Create().
> 		SetEmailAddress("rotem@entgo.io").
> 		SetFullName("Rotem Tamir").
> 		OnConflictColumns(user.FieldEmailAddress).
> 		Update(func(upsert *ent.UserUpsert) {
> 			upsert.SetEmailAddress("z")
> 		}).IDX(ctx)
> 	if id == 0 {
> 		t.Fatalf("returned ID should not be zero")
> 	}
> 	fmt.Println(id)
> }
> ```
> 
> Running:
> 
> ```
> === RUN   TestSqlLite
> 1
> 1
> --- PASS: TestSqlLite (0.00s)
> PASS
> ```
> 
> Can you try to create a minimal reproducible example that includes a minimal schema and a test?

the memory mode look have some bugs...
```
	rand.Seed(time.Now().UnixNano())
	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	ctx := context.TODO()
	id := client.Pin.Create().
		SetRid("rotem@entgo.io").

		//SetFullName("Rotem Tamir").
		OnConflictColumns(pin.FieldRid).
		Update(func(upsert *ent.PinUpsert) {
			upsert.SetRid("s" + strconv.Itoa(int(rand.Int31n(3))))
		}).IDX(ctx)
	fmt.Println(id)
	id = client.Pin.Create().
		SetRid("rotem@entgo.io2").

		//SetFullName("Rotem Tamir").
		OnConflictColumns(pin.FieldRid).
		Update(func(upsert *ent.PinUpsert) {
			upsert.SetRid("s" + strconv.Itoa(int(rand.Int31n(3))))
		}).IDX(ctx)
	fmt.Println(id)
	id = client.Pin.Create().
		SetRid("rotem@entgo.io").

		//SetFullName("Rotem Tamir").
		OnConflictColumns(pin.FieldRid).
		Update(func(upsert *ent.PinUpsert) {
			upsert.SetRid("s" + strconv.Itoa(int(rand.Int31n(3))))
		}).IDX(ctx)
	fmt.Println(id)
	if id == 0 {
		t.Fatalf("returned ID should not be zero")
	}
```
```
=== RUN   TestSqlLite
1
2
2
--- PASS: TestSqlLite (0.00s)
PASS
```

**Comment by a8m** [comment]
Hey @godcong and thanks for reporting this issue 🙏  (and thanks @rotemtam for #1847).

What's your ent version? Can you please update to v0.9.1 and report if it still happens? Thanks

**Comment by godcong** [comment]
@a8m 
I tried it on 0.9.1.
The problem did not reappear.

**Comment by rotemtam** [comment]
Good to hear! Closing this. Let me know if there are any outstanding issues
