### ISSUE TITLE
How to calculate in `Order By`？

### ISSUE THREAD

**Issue by SuzurikawaChihiro** [ent/ent#1833]
I don't know how to write the following query in ent

```sql
SELECT * FROM spots
ORDER BY (
  SQRT(
    POWER(ABS(35.6811164 - spots.latitude), 2.0) + POWER(ABS(139.7670766 - spots.longitude), 2.0)
  )
) ASC;
```

This wasn't going to work.
```go
stpos, err := ctrl.db.Spot.
     Query().
     Order(func(s *sql.Selector) {
          s.OrderExpr(sql.Expr("SQRT(POWER(ABS(? - spots.latitude), 2.0) + POWER(ABS(? - spots.longitude), 2.0)", params.Latitude, params.Logitude))
     }),
     All(ctx)
```

**Comment by a8m** [comment]
Hey @SuzurikawaChihiro, do you use PostgreSQL? If so, use the `sql.ExprFunc` instead, and please let me know if you need more help with that:

```go
client.Spot.
	Query().
	Order(func(s *sql.Selector) {
		s.OrderExpr(sql.ExprFunc(func(b *sql.Builder) {
			b.WriteString("SQRT(POWER(ABS(").Arg(35.6811164).WriteOp(sql.OpSub).Ident(spot.FieldLatitude)
			// ...
		}))
	}).
	All(ctx)
```

**Comment by SuzurikawaChihiro** [comment]
I'll give it a try.👍

**Comment by a8m** [comment]
Great. Closing, but please feel free to reopen if you still need help, or you're also welcome to join our [Slack channel](https://entgo.io/docs/slack/) 😎

**Comment by henrywoody** [comment]
@a8m I'm working on something similar and have this as an example:

```go
client.Employee.
	Query().
	Order(func(s *sql.Selector) {
		s.OrderExpr(sql.ExprFunc(func(b *sql.Builder) {
			b.WriteString("LOWER(").Ident(employee.FieldFirstName).WriteString(")")
		}))
	}).
	All(ctx)
```

which, unless I am missing something obvious, is roughly equivalent to the solution you've provided. My real example involves a more complex calculation for searching models, but this one gets the same error and is much simpler.

The above Go code produces the SQL query:

```sql
SELECT DISTINCT "employee"."id", "employee"."first_name", "employee"."last_name", "employee"."job_title"
FROM "employee"
ORDER BY LOWER("first_name")
```

Which is what I'm going for, however this query results in the error:

```
pq: for SELECT DISTINCT, ORDER BY expressions must appear in select list
```

If I were writing this query in SQL directly, I could do

```sql
SELECT DISTINCT "employee"."id", "employee"."first_name", "employee"."last_name", "employee"."job_title", LOWER("first_name") AS _order_field
FROM "employee"
ORDER BY _order_field
```

But I'm not sure how to do this with `ent` or if there is another/better way to accomplish what I'm after.

Alternatively I can remove the `DISTINCT`, which I've seen by calling `.Unique(false)` (or something to that effect) on the query, however I'm assuming that the `DISTINCT`s are in there for a reason and do not want to just remove them for all queries just to support this case.

Any thoughts or guidance on this?

I am using PostgreSQL by the way.

**Comment by SuzurikawaChihiro** [comment]
Thank you for @a8m 
I could run this query with this code. 👍

```sql
SELECT * FROM spots
ORDER BY (
  SQRT(
    POWER(ABS(35.6811164 - spots.latitude), 2.0) + POWER(ABS(139.7670766 - spots.longitude), 2.0)
  )
) ASC;
```

```go
spots, err := controller.db.Spot.
    Query().
    Order(func(s *sql.Selector) {
        s.OrderExpr(sql.ExprFunc(func(b *sql.Builder) {
            b.WriteString("SQRT(POWER(ABS(").Arg(params.Latitude).WriteOp(sql.OpSub).Ident(spot.FieldLatitude).WriteString("), 2.0)").
                WriteOp(sql.OpAdd).WriteString("POWER(ABS(").Arg(params.Logitude).WriteOp(sql.OpSub).Ident(spot.FieldLongitude).WriteString("), 2.0))")
        }))
    }).
    Unique(false).
    All(ctx)

```
