### ISSUE TITLE
sql   count(1) 

### ISSUE THREAD

**Issue by NengNgg** [ent/ent#1834]
I don 't know how to implement SQL “count ( 1 )”  functionality through  ent

**Comment by godcong** [comment]
client.Table.Query().Count(ctx)

**Comment by a8m** [comment]
Thanks for helping @godcong 🙏. 

@NengNgg, please let us know if it answers your question and we can close this issue. Thanks

**Comment by a8m** [comment]
Closing, but please reopen if you still need help or join our [Slack channel](https://entgo.io/docs/slack/).
