### ISSUE TITLE
fetching records returns an empty slice due to usage of time.Time with mysql schema type

### ISSUE THREAD

**Issue by sadmansakib** [ent/ent#1838]
**So, i have created this `Person`  Schema with following properties:**

`
field.String("first_name"), field.String("last_name"), field.String("email"),
field.Time("birth_date").SchemaType(map[string]string{
     dialect.MySQL: "date",
}), field.String("phone").Match(reg),
field.Enum("gender").Values("male", "female"),
field.String("password").Sensitive(),
`

**Then i tried to execute the following query:**
` client.Person.Query().Select(person.FieldID,
			person.FieldFirstName,
			person.FieldLastName,
			person.FieldBirthDate,
			person.FieldEmail,
			person.FieldGender,
			person.FieldPhone).All(ctx)
 `

This query generates the following sql query which works fine while testing manually: 
``
 SELECT DISTINCT `persons`.`id`, `persons`.`first_name`, `persons`.`last_name`, `persons`.`birth_date`, `persons`.`email`, `persons`.`gender`, `persons`.`phone` FROM `persons`
``

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

ent returns an empty slice

## Expected Behavior 🤔

ent should return a slice of records with selected fields

## Steps to Reproduce 🕹

Steps:

1. Add any time field with schema type set to Mysql
2. try to query database with selected fields

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.7  |
| Ent         | 0.9.0   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @sadmansakib and thanks for opening this issue. Any chance you forgot adding the [parseTime](https://github.com/go-sql-driver/mysql#parsetime) option in your MySQL DSN?

**Comment by sadmansakib** [comment]
Thanks! Looks like i had issues on DSN and adding parseTime fixes the issue
