### ISSUE TITLE
Question: How to disable foreign key creation on single field

### ISSUE THREAD

**Issue by maxifom** [ent/ent#1839]
I want to disable only 1 FK, but not for all of my migration as per #751 , how can I do that?

**Comment by a8m** [comment]
Hey @maxifom and thanks for opening this issue. You can disable the foreign-key creation of one edge using a [Migration Hook](https://entgo.io/docs/migrate/#migration-hooks) by deleting it from the table before executing the migration. For example:

```go
if err = client.Schema.Create(
	ctx,
	schema.WithHooks(func(next schema.Creator) schema.Creator {
		return schema.CreateFunc(func(ctx context.Context, tables ...*schema.Table) error {
			petFKs := tables[0].ForeignKeys
			// Delete the first foreign-key of the pets table.
			tables[0].ForeignKeys = petFKs[1:]
			if err := next.Create(ctx, tables...); err != nil {
				return err
			}
			// Restore back the pets table foreign-keys.
			tables[0].ForeignKeys = petFKs
			return nil
		})
	}),
); err != nil {
	log.Fatalf("failed creating schema resources: %v", err)
}
``` 

We can consider adding this functionality in the future using a custom `entsql` annotation if we'll see more need for this. 

Closing, but please feel free to reopen if you still need help. You're also welcome to join our [Slack channel](https://entgo.io/docs/slack/). Thanks 🙏
