### ISSUE TITLE
MaxLen Validator failed with non-ASCII characters

### ISSUE THREAD

**Issue by zhyon404** [ent/ent#1856]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Define a field where maxlen setting to 3 for example.
`field.String("text").Default("").MaxLen(3)`

than set non-ASCII to this field.
`create.SetText("😯")`

it will report `value is greater than the required length`		

I think it cause by `if len(v) > i {`.

## Expected Behavior 🤔

From what I know, MySQL and PostgreSQL varchar define char length.
Should we change the above behavior to validate char length?

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.?  |
| Ent         | 0.5.?   |
| Database    | Mysql   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by zhyon404** [comment]
I can help with this if you want

**Comment by masseelch** [comment]
I'd say add a validator `RuneCount()` instead and mention the difference in the docs. 

I have a case where I'm interested in the byte length of a string and your proposal will break that for me. I will follow this thread.

**Comment by giautm** [comment]
Hi @zhyon404, please see comment from https://github.com/ent/ent/issues/1637#issuecomment-859854768

**Comment by zhyon404** [comment]
@giautm 
I've considered this option
I think another role of MaxLen is to change the size of the varchar.
And the assignment to size needs to go through desc.
Something like
```
f:=field.String("name").
    Validate(MaxRuneCount(10))

f.desc.Size=10
```
Writing this break builder pattern and I think is a little annoying?

direct change is backward incomplete, of course,  so do you think it's a good idea to add a new method like `MaxRuneLen`?

**Comment by giautm** [comment]
`f.desc.Size=10` why you need this statement?

I think you have wrong charset when creating the table, [it should be `utf8mb4` or `utf8mb3`](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html) to storing Unicode character.

**Comment by zhyon404** [comment]
> `f.desc.Size=10` why you need this statement?
> 
> It should be:
> 
> ```go
> field.String("name").
>     MaxLen(10).
>     Validate(MaxRuneCount(10))
> ```
The above code `MaxLen ` call should be here?

https://github.com/ent/ent/blob/f326c7dfd088f112d0bc3150161862115d6fff63/schema/field/field.go#L211-L221

which add validator,

so if I want to change size without adding a validator, I need this `f.desc.Size=10` if I'm understanding correctly.

**Comment by giautm** [comment]
Yah, sorry about wrong reference code. 🥲 

If you want change Size only, you can use `entsql.Annotation`

```go
import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/field"
)

field.String("name").
	Annotations(entsql.Annotation{Size: 21})
```

**Comment by zhyon404** [comment]
@giautm that's very helpful. thanks.
