### ISSUE TITLE
Clarify ent enum usage

### ISSUE THREAD

**Issue by maxifom** [ent/ent#1864]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
I guess we should clarify on https://entgo.io/docs/schema-fields/ that we can use field.Enum() with GoType OR with Values(), but not together, also it would be useful to clarify that in case of GoType enum, values for validation is taken from .Values() method. 

Maybe it will be better to create additional chapter on this page about Enum as it's not as simple as it seems?

**Comment by a8m** [comment]
Fixed with #1886. Thanks @yonidavidson and @maxifom 🙏

**Comment by maxifom** [comment]
@a8m I guess my point about that we cannot use enum with Values and with GoType at the same time is important to clarify, that there is 2 ways to create enum with values, and they cannot be combined.

**Comment by yonidavidson** [comment]
@maxifom have a look at the new Enum section in the docs.

**Comment by maxifom** [comment]
@yonidavidson yeah, I saw it, I guess its encoded inside code block under "Combining it all together:", which shows 3 ways to create enum, I guess that's ok then
As a second thought it would be nice to disable creating enum with Values and GoType at the same time at the code level, but I guess it's too much work, and user will see error anyway during code generation.
