### ISSUE TITLE
How to calculate distance and get it?

### ISSUE THREAD

**Issue by MatsuoTakuro** [ent/ent#1866]
As an additional question to the issue(https://github.com/ent/ent/issues/1833), I would also like to calculate the distance between my current location and a spot, define it as `distance`, and get it in `ent.go`.
How can I write it in that?

(Expressed in `PostgreSQL`, it is as follows.)
```
SELECT 	*,
        SQRT(
          POWER(ABS(33.6257537 - spots.latitude), 2.0) + POWER(ABS(130.446075 - spots.longitude), 2.0)
        ) as distance
FROM spots    
ORDER BY (distance) ASC
LIMIT 5 OFFSET 0;　
```

**Comment by a8m** [comment]
Hey @MatsuoTakuro and thanks for opening this issue. 

You can use the [sql/modifier](https://entgo.io/docs/feature-flags/#custom-sql-modifiers) API to write such queries, but note that you need to `Scan` the result to a custom struct. For example:

```go
client.Spot.Query().
	Modify(func(s *sql.Selector) {
		s.AppendSelect(sql.As("SQRT(POWER(....), 2.0))", "distance"))
		s.OrderBy("distance").Limit(1)
	}).
	ScanX(ctx, &xs)

// Or:

client.Spot.Query().
	Modify(func(s *sql.Selector) {
		s.Select("*", sql.As("SQRT(POWER(ABS(....), 2.0))", "distance"))
		s.OrderBy("distance").Limit(1)
	}).
	ScanX(ctx, &xs)
``` 

Closing, but please let me know if you need additional help with that 🙏
