### ISSUE TITLE
v0.9.1 does not check if driver is sqlite, and concatenates RETURNING to insert clause

### ISSUE THREAD

**Issue by catlee993** [ent/ent#1873]
v.0.9.1 `InsertBuilder.Query()` doesn't check for sqlite driver prior to concatenating `RETURNING`. Although sqlite 3.35.0 does support `RETURNING`, the primary driver (`github.com/mattn/go-sqlite3`) referenced in the docs hasn't been updated to support this (at least for its latest release). For convenience to the user it may be good to check against this condition.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When testing using sqlite and v9.1.0, a `RETURNING` clause is appended to the builder, which is not currently supported by `github.com/mattn/go-sqlite3`

Builder:
https://github.com/ent/ent/blob/master/dialect/sql/builder.go#L983

Graph:
https://github.com/ent/ent/blob/master/dialect/sql/sqlgraph/graph.go#L1288

## Expected Behavior 🤔

Ideally, a `RETURNING` clause should not be appended as per v9.0.0. 
v.9.0.0 originally performed the above actions if it was postgres rather than checking specifically for mysql

## Steps to Reproduce 🕹

going by the docs, then creating an entity (assuming built schemas) via docs https://entgo.io/docs/testing/
```go
package main

import (
    "context"
    "testing"

    "<project>/ent/enttest"

    _ "github.com/mattn/go-sqlite3"
)

func TestXXX(t *testing.T) {
    client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
    defer client.Close()
   _ = entClient.User.Create().SaveX(context.Background())
}
```
productes a panic of 
```go
panic: insert node to table "users": near "RETURNING": syntax error [recovered]
	panic: insert node to table "users": near "RETURNING": syntax error
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.2 |
| Ent         | 0.9.1   |
| Database    | sqlite   |
| Driver      | github.com/mattn/go-sqlite3   |

**Comment by a8m** [comment]
Hey @catlee993 and thanks for reporting this issue. 

> Although sqlite 3.35.0 does support RETURNING, the primary driver (github.com/mattn/go-sqlite3) referenced in the docs hasn't been updated to support this (at least for its latest release)

The latest `mattn/go-sqlite3` version ([v1.14.8](https://github.com/mattn/go-sqlite3/releases/tag/v1.14.8)) was released last month and the version of its underlying SQLite database is [3.36.0](https://github.com/mattn/go-sqlite3/commit/cba6eaee486f22a1b0f3208b145673ed951cb840). Updating the `mattn/go-sqlite3` module should solve your problem. 

Please let me know if we can close the issue 🙏

**Comment by catlee993** [comment]
Ah, thank you! We can close this!

**Comment by a8m** [comment]
😃 

Please, feel free to join our [Slack channel](https://entgo.io/docs/slack/) and ping me if you have additional questions.
