### ISSUE TITLE
Feature request: A simpler way to add additional structure fields

### ISSUE THREAD

**Issue by rehth** [ent/ent#1875]
I hope there is an easier way to add structure field, wanted to add database fields as convenient, but not this [way](https://entgo.io/docs/schema-fields/#additional-struct-fields),this is a disaster for adding fields to many structures

**Comment by khanakia** [comment]
I need also to add some NON Database fields for e.g. I use Apollo Graphql and it requires `typename`  fields to be sent  so other go ORM allows you to add fields like this like `gorm.io` you can add fields like this.

**Comment by khanakia** [comment]
Is there any way to add Custom methods to the generated Struct ? I can see we can add custom Static Fields using templates.
But how to add custom methods ?

**Comment by masseelch** [comment]
You can achieve that with templates. Have a look at [this example](https://github.com/ent/ent/blob/dd4792f5b30bdd2db0d9a593a977a54cb3f0c1ce/examples/entcpkg/ent/template/debug.tmpl). 

```

{{ define "user_methods" }}

{{/* Add the base header for the generated file */}}
{{ $pkg := base $.Config.Package }}
{{ template "header" $ }}

{{/* Look for User */}}
{{ range $n := $.Nodes }}
	{{ if eq $.Name "User" }}
		func (u User) Fullname() string {
			return u.FirstName + " " + u.LastName
		}
	{{ end }}
{{ end }}

{{ end }}
```

Have a look at [gen package](https://pkg.go.dev/entgo.io/ent/entc/gen) to know what the `Graph` struct given to the templates look like.
