### ISSUE TITLE
Specifying table level collation in postgres?

### ISSUE THREAD

**Issue by Liooo** [ent/ent#1888]
First of all thanks for the great library.
Seems like postgres dialect doesn't accept table level collation (?), and after my shallowest look on the code I'm wondering if adding [this mysql tBulider chunk](https://github.com/ent/ent/blob/master/dialect/sql/schema/mysql.go#L188-L199) to [postgres part](https://github.com/ent/ent/blob/master/dialect/sql/schema/postgres.go#L310) does the job, in which case I'm happy to send a PR.

**Comment by Liooo** [comment]
was my misunderstanding, probably we can't set table level, sorry.

**Comment by a8m** [comment]
> was my misunderstanding, probably we can't set table level, sorry.

Right, but you can configure it per column. For example:

```sql
CREATE TABLE t (c text COLLATE "es_ES")
```
