### ISSUE TITLE
Suggestion: Add .gitattributes ignore rules to getting started content

### ISSUE THREAD

**Issue by tmc** [ent/ent#1890]
I've seen several folks recently mention/complain that the generated code makes code review more difficult.

I'd suggest we include a suggestion to exclude the generated parts of the ent subdirectory as described in https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/customizing-how-changed-files-appear-on-github

**Comment by tmc** [comment]
Actually, as the ent-generated files use the typical generated header this probably isn't actually accomplishing anything. Perhaps we should close.

**Comment by a8m** [comment]
> Actually, as the ent-generated files use the typical generated header this probably isn't actually accomplishing anything. Perhaps we should close.

OK, thanks @tmc.

Closing, but we should reopen and address this issue if users will complain again.

**Comment by thuan1412** [comment]
Hi, how do we exclude (auto collapse) generated files by using `.gitattributes`? 
I don't know how to exclude all folders except `ent/schema` :smile:

**Comment by thuan1412** [comment]
Can we add a custom postfix/prefix for generated files? So that the config for ignoring will be more simpler? Moreover, it will help us omit generated files when searching text inside the project.
