### ISSUE TITLE
How to specify a primary key as another field.

### ISSUE THREAD

**Issue by a245589351** [ent/ent#1902]
In my table, the primary key is cc_ id

**Comment by a8m** [comment]
Hey @a245589351, as mentioned in the [ID field](https://entgo.io/docs/schema-fields#id-field) documentation, you can configure the storage key (column name) of a field as follows: 

```go
func (T) Fields() []ent.Field {
    return []ent.Field{
        field.Int("id").
            StorageKey("cc_id"),
    }
}
```

**Comment by a8m** [comment]
Closing, but please reopen or join our [Slack channel](https://entgo.io/docs/slack) if you still need help. Thanks 🙏

**Comment by a245589351** [comment]
It is helpful. Thanks..
