### ISSUE TITLE
add last func when query

### ISSUE THREAD

**Issue by xushuhui** [ent/ent#1907]
## Summary 💡

I only use it when I query last row
```go
client.User.Query().Order(ent.Desc(user.FieldID)).First(ctx)
```
I think it simple and elegant 
```
client,User.Query().Last(ctx)
```

thank your work

**Comment by a8m** [comment]
Thanks, @xushuhui for suggesting this feature. As I commented in https://github.com/ent/ent/issues/1027#issuecomment-741843635:

> Regarding this new API, since it doesn't require any runtime-specific logic, I think it's better to create a plugin for it in a different repo for now (and maybe mentioning it in our website) and possibly adding it to the core features if we'll see big adoption for this.
> 
> I encourage our internal users to go through the same process as well. They start with custom templates for such proposals and we consider adding them to the framework only after we have some experience with it - because once you add it, you can't go back.

If you want to generate this new API with the codegen, please use the [external templates](https://entgo.io/docs/templates/) option.

Closing, but please reopen or ping me on our [Slack channel](https://entgo.io/docs/slack) if you need any help with that. Thanks 🙏
