### ISSUE TITLE
MaxLen for Non-English strings not working correctly with postgres

### ISSUE THREAD

**Issue by maxifom** [ent/ent#1914]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I am developing application, where primarily all of the names are in Russian. As we know non-English characters in UTF-8 are 2 or more bytes long. If I try to insert 255 Russian characters I get a validation error, but if I try to do raw Postgres request, I get no error as `VARCHAR(255)` in Postgres related to number of characters, but not bytes. MaxLen validator on the other hand related to len(string) which is in bytes and incorrect.

## Expected Behavior 🤔

No validation error happens

## Steps to Reproduce 🕹
Reproduction repo: https://github.com/maxifom/ent-validation-bug

1. clone
2. docker-compose up -d 
3. go run main.go

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | v0.9.2-0.20210903142140-c511be69b68b  |
| Database    | postgres   |
| Driver      | 	github.com/lib/pq v1.10.3|

**Comment by masseelch** [comment]
Please have a look at the custom validator example in the [docs](https://entgo.io/docs/schema-fields#validators).

**Comment by maxifom** [comment]
Ent generates migration varchar length based on maxlen validator, or it's not the case? If so it's incorrect in Postgres

**Comment by masseelch** [comment]
Please have a look at [this comment](https://github.com/ent/ent/issues/1856#issuecomment-902591844). 

You can change the length by the use of an Annotation.

**Comment by giautm** [comment]
Hi @masseelch I think we should update the example in the document with entql.Annotation.

**Comment by masseelch** [comment]
> Hi @masseelch I think we should update the example in the document with entsql.Annotation.

Agreed! There are a lot of questions / issues regarding this. I'll do a PR on Monday (not near laptop) or you do, as you like 😊

@maxifom Is your issue resolved?

**Comment by maxifom** [comment]
Yeah, I guess so

**Comment by a8m** [comment]
Closing via #1915
