### ISSUE TITLE
switch to go install according to  golang.org/doc/go-get-install-deprecation

### ISSUE THREAD

**Issue by JackLeeHal** [ent/ent#1921]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

switch to go install according to 
golang.org/doc/go-get-install-deprecation

## Motivation 🔦

> Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.
> 
> In a future Go release, go get will no longer build packages; it will only be used to add, update, or remove dependencies in go.mod. Specifically, go get will act as if the -d flag were enabled.

golang.org/doc/go-get-install-deprecation

https://github.com/ent/ent/pull/1920

**Comment by a8m** [comment]
Hey @JackLeeHal, thanks for opening this issue and contributing a fix.

The Ent project supports the last 2 Go versions (e.g. 1.17 and 1.16), and therefore, we'll need to wait with this change to version 1.18.

I'm closing this issue now, but please feel free to reopen it or send a patch when 1.18 will release. Thanks 🙏
