### ISSUE TITLE
GQL Where clause generates invalid handler

### ISSUE THREAD

**Issue by delaneyj** [ent/ent#1925]
If you use a `field.Uint64`  the generate code incorrectly uses a `int`.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When using gqlWhereFeature the `graph/generated/generated.go` becomes

```
...
	case "xbp":
			var err error

			ctx := graphql.WithPathContext(ctx, graphql.NewPathWithField("xbp"))
			it.Xbp, err = ec.unmarshalOInt2ᚖint(ctx, v)
			if err != nil {
				return it, err
			}
...
``` 
for all `Neq,In,NotIn,Gt,Gte,Lt,Lte...` variants

## Expected Behavior 🤔

Unmarshal to a uint64

## Steps to Reproduce 🕹

Steps:

1.  add `field.Uint64("xbp").Default(100000),` to a ent.Schema
2. use gql extension with `	entgql.WithWhereFilters(true),` 
3. look at `generated.go` for errors

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.7  |
| Ent         | 0.9.1   |
| Ent/Contrib         | 0.1.1   |

**Comment by a8m** [comment]
Hey @delaneyj and thanks for opening this issue.

The built-in scalar types in GraphQL are `Int`, `Float`, `String`, `Boolean`, and `ID` (see [documentation](https://graphql.org/learn/schema/#scalar-types)). Hence, if you want to use a custom scalar, you should define it in your GraphQL schema.

Fortunately,  `gqlgen` supports all Go built-in types, so the only changes you need to do are:
1. Add the custom scalar `Uint64` type to your GraphQL schema.
   ```graphql
   scalar Uint64
   ```
2. Tell `gqlgen` how does the `Uint64` type is implemented (i.e. `(Un)Marshaller`).
    ```yaml
    models:
      Uint64:
        model:
          - github.com/99designs/gqlgen/graphql.Uint64
    ```
3. And last, tell `entgql` that the GraphQL type in the generated schema is custom.
    ```go
    field.Uint64("xbp").
        Default(100000).
        Annotations(
            entgql.Type("Uint64"),
        )
    ```

I created an [example PR](https://github.com/ent/contrib/pull/137) for this use case, so please give it a look and feel free to reopen if you still need help with that. You're also welcome to join our [Slack channel](https://entgo.io/docs/slack/) 😎

**Comment by delaneyj** [comment]
:fireworks:  thank you
