### ISSUE TITLE
How to skip generating GraphQL WhereInput type to some schemas

### ISSUE THREAD

**Issue by delaneyj** [ent/ent#1927]
When using the GQL extension input types are generated for all schema types in the database, not just the ones exposed in a .graphqls which causes compile errors.  How do you limit what whereinputs get generated?   Especially in the case where not everything in the DB will be exposed via GQL.

Thanks

**Comment by a8m** [comment]
Hey @delaneyj, use the `entgql.Skip()` annotation for types/fields you want to skip in the extension. Please use the following example:

```go
func (T) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.Skip(),
	}
}
```

[Link to source code](https://github.com/ent/contrib/blob/4d454b12b029089bcc94d2218caddf4f244bba06/entgql/internal/todo/ent/schema/verysecret.go#L37-L39).

**Comment by delaneyj** [comment]
Thank you so much!  Especially grateful to the fast response times.
