### ISSUE TITLE
custom default clause to id field

### ISSUE THREAD

**Issue by msonawane** [ent/ent#1932]
given following mixin fields

```
// Fields of the AuditMixin.
func (AuditMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").
			Positive().
			Unique().
			StructTag(`json:"id"`).
			Immutable().
			Annotations(entsql.Annotation{
				Default: "id_generator",
			}),
		field.Time("created_at").
			Immutable().
			Default(time.Now),
		field.Int64("created_by").
			Optional(),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
		field.Int64("updated_by").
			Optional(),
		field.Time("deleted_at").
			Optional(),
		field.Int64("deleted_by").
			Optional(),
	}
}
```

DDL generated is 

`2021/09/09 12:01:20 Tx(d15e7de9-b694-4965-b09d-d5d47e9c6f26).Exec: query=CREATE TABLE IF NOT EXISTS "users"("id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL DEFAULT 'id_generator', "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "name" varchar NOT NULL DEFAULT 'unknown', "user_name" varchar UNIQUE NOT NULL, "password_hash" varchar NOT NULL, "active" boolean NOT NULL DEFAULT true, "created_by" bigint UNIQUE NULL, "updated_by" bigint UNIQUE NULL, "deleted_by" bigint UNIQUE NULL, PRIMARY KEY("id")) args=[]`

which leads to migration error

`
sql/schema: create table "users": pq: both default and identity specified for column "id" of table "users"
`

**Comment by wenerme** [comment]
This should works now

https://github.com/wenerme/ent-demo/blob/283783e0751c2f890a4f1e0852a17d4fe3530999/ent/schema/mixin_id.go#L77-L89

**Comment by locnguyen** [comment]
Linking a related conversation in the atlas Discord: https://discord.com/channels/930720389120794674/933360123357839360/1041217177598038036

**Comment by a8m** [comment]
Hey all! The issue was addressed with https://github.com/ent/ent/pull/3089. 

Using the new annotation API, you can also define a default-value expression per dialect, and [Atlas](https://github.com/ariga/atlas) should handle the migration for them. Please, see these examples:

```go
// Default expression/function (not literal).
field.Int("id").
	Annotations(
		entsql.DefaultExpr("id_generator()"),
	)

// Expression per dialect.
field.Int("id").
	Annotations(
		entsql.DefaultExprs(map[string]string{
			dialect.MySQL:    "floor(rand() * ~(1<<31))",
			dialect.SQLite:   "abs(random())",
			dialect.Postgres: "floor(random() * ~(1<<31))",
		}),
	)
```
