### ISSUE TITLE
error querying the time fields 

### ISSUE THREAD

**Issue by ankitpatial** [ent/ent#1935]
I created an entity with some time fields
```go
func (Entity) Fields() []ent.Field {
	return []ent.Field{
		field.Time("created_at").
			Default(time.Now).
			Immutable(),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
		field.Time("deleted_at").
			Optional().
			Nillable(),
	}
}
```
all is going well, I can migrate schema, I can insert ok. But if I try to Get or Query on Entity it gives me following error.

```text
Scan error on column index 1, name "created_at": unsupported Scan, storing driver.Value type []uint8 into type *time.Time
``` 

I also tried with mixin.Time and custom mixin, result is same.

I am not sure if I am missing some settings for MySql Dialect?

**Comment by a8m** [comment]
Hey @ankitpatial 👋🏻

Any chance you forgot to add the “parseTime” parameter in the connection string? Please see https://github.com/ent/ent/issues/1893#issuecomment-911230858

**Comment by yonidavidson** [comment]
Hi, if you can create an example repo and share a link it will be very help helpful.  Can you please  write down an example  query? Thanks

**Comment by ankitpatial** [comment]
Thank you for the quick reply.  YES! I missed to set `parseTime=true`
