### ISSUE TITLE
disable snake_case naming convention

### ISSUE THREAD

**Issue by lacendarko** [ent/ent#1943]
Hello,
Is there any way to disable the default naming convention: snake_case? I have an existing database with a different naming convention and I don't want to add .StorageKey() option for every field.

**Comment by a8m** [comment]
Hey @lacendarko and thanks for opening this issue.

Using `snake_case` names for `ent.Field`s is optional, but you can also use `snake_case` fields and add the `StorageKey` option to all of them using [codegen hooks](https://entgo.io/docs/code-gen#code-generation-hooks).

**Comment by lacendarko** [comment]
Thanks! That's exactly what I was looking for 😄
