### ISSUE TITLE
group by and order by

### ISSUE THREAD

**Issue by lhg814385644** [ent/ent#1944]
I have 2 table  O2M
I want realization effect 

SELECT hp.HangerID, MAX(hp.EnterTime) AS LastTime FROM Hangers as hg

RIGHT JOIN HangerProcesses as hp

ON hg.ID = hp.HangerID

WHERE hg.`Code` LIKE '%YJ%' AND hp.EnterTime IS NOT NULL

GROUP BY hp.HangerID

ORDER BY LastTime DESC

**Comment by yonidavidson** [comment]
Hi, did you read the chapter about graph traversal? https://entgo.io/docs/traversals/

For more help, if you have a small project you can share it will help a lot.

**Comment by a8m** [comment]
Thanks for the help @yonidavidson 🙏 

Hey @lhg814385644, please give a look at the [SQL modifier feature-flag](https://entgo.io/docs/feature-flags/#custom-sql-modifiers) (see examples in the link). Enabling this feature flag will help you to execute this custom SQL statement and scan it into a slice of structs.

Feel free to ping us in Slack/Discord if you need further help with that.
