### ISSUE TITLE
Weird changes in  schema after migration to 0.9.1

### ISSUE THREAD

**Issue by michaelkub** [ent/ent#1945]
After migrating to new version 0.9.1, default values has changed in database

## Current Behavior 😯

this is field definitions:

``` 
field.Time("created_at").
			Immutable().
			Default(time.Now),
field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
```
This is how fields look now in database:
```  
`created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00', 
```

## Expected Behavior 🤔

- First of all we aren't expected to any schema changes when just migration to new version, or at least should be some release notes
- Second, this change look like a bug

## Steps to Reproduce 🕹

Migrate to new version from 0.8 to 0.9.1

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.4  |
| Ent         | 0.9.1   |
| Database    | mariadb   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hi @michaelkub and thanks for reporting this issue.

The fields above should not configure any `DEFAULT` on the database, and we didn't add any specific code for it in v0.9.*

What is your MariaDB version? I'll try to reproduce it now.

**Comment by a8m** [comment]
#1946 should address this issue (see attached screenshot). Would you mind ping me on Slack/Discord and discuss how we can avoid issues like this with MariaDB in the future?  

![image](https://user-images.githubusercontent.com/7413593/133235151-a623b35b-0a80-4187-953b-a621dfac874b.png)

**Comment by syssam** [comment]
expected
`created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`
`updated_at TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP`
