### ISSUE TITLE
proposal: add support for relation/edge schema

### ISSUE THREAD

**Issue by a8m** [ent/ent#1949]
This is a feature that I have wanted to add for a long time to ent, and will be happy to get feedback, suggestion for improvements or just hear your thoughts before I create a proper PR for it.

The idea is instead of adding a completely new API for adding [fields for edges](https://github.com/ent/ent/issues/1061) (columns for join tables), [configure their indexes](https://github.com/ent/ent/issues/1845), hooks, privacy, etc, or even support [multi-column PKs](https://github.com/ent/ent/issues/400), we'll add 2 new small changes for the ent/schema for supporting all those issues.

### `field.ID` Annotation

A new `field.ID` option will be added to the `schema/field` package, and this will allow configuring multi-column PKs, but more than that, it will make it possible to configure relation/edge schema manually. For example:

```go
// UserGroup defines the UserGroup relation schema.
type UserGroup struct {
	ent.Schema
}

func (UserGroup) Annotations() []schema.Annotation {
	return []schema.Annotation{
		// This will generate the following struct:
		//
		//	type UserGroupID struct {
		//		UserID, GroupID int
		//	}
		//
		field.ID("user_id", "group_id"),
	}
}

func (UserGroup) Fields() []ent.Field {
	return []ent.Field{
		field.Int("user_id"),
		field.Int("group_id"),
		field.Time("created_at").
			Immutable().
			Default(time.Now),
	}
}

func (UserGroup) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("user", User.Type).
			Unique().
			Field("user_id"),
		edge.To("group", Group.Type).
			Unique().
			Field("group_id"),
	}
}
```

Indexes, hooks, privacy, and all other options will also be available for this type of schema, but in order to add a user to a group, the flow is a bit longer:

```go
a8m := client.User.Create().SetName(..).SaveX(ctx)
hub := client.Group.Create().SetName(..).SaveX(ctx)
// Instead of calling hub.AddGroups(a8m), the API is:
client.UserGroup.Create().SetUserID(a8m.ID).SetGroupID(hub.ID).ExecX(ctx)
client.UserGroup.GetX(ctx, ent.UserGroupID{UserID: a8m.ID, GroupID: hub.ID})
```

We can bypass this long flow by providing an additional config option for edges:

### The `edge.Through` Option

The `Through` option is supported by other frameworks and has already been proposed here before. The idea is to allow schemas that use the relation/edge-schema to CRUD directly their relations. However, I have an open question (atm) regarding the design of the generated code.

The configuration looks as follows:

```go
func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("users", User.Type).
			Through(UserGroup.Type),
	}
}
```

And the generated API is as follows:

```go
a8m := client.User.Create().SetName(..).SaveX(ctx)
hub := client.Group.Create().SetName(..).AddUsers(a8m).SaveX(ctx)
```

An open question I have is on how do we set/update relation-schema fields in case they don't have default values or hooks configured on their ent/schema.

Thoughts?

**Comment by rotemtam** [comment]
Cc @tarrencev

**Comment by tarrencev** [comment]
This works great for my use case! Maybe it makes most sense to start with the field.ID annotation and then work on the Through api? For now we could use the more verbose code

**Comment by marwan-at-work** [comment]
Looks great. I like the `through` option because it feels intuitive and many people coming from the Rails and other domains will find it natural.

**Comment by Vilsol** [comment]
This would be an amazing addition. Would be the last piece of the puzzle to be able to switch to `ent`.

Regarding the defaults in the through tables. Would it maybe be possible to detect if a table is referenced to as a "through" table, and then check if any non-default fields are missing, then panic/error out?

A potential issue/feature that should be considered: When creating the annotation `field.ID("user_id", "group_id")` it would be great if it also supported the case where `user_id` was a string, but `group_id` was an int (or other type combos).

**Comment by e48** [comment]
```go
a8m := client.User.Create().SetName(..).SaveX(ctx)

// UserGroupThrough has setters for fields except "group"
thr := client.UserGroup.Through.
	SetUser(a8m).
	SetCreatedAt(time.Now)

hub := client.Group.Create().SetName(..).AddUsersThrough(thr).SaveX(ctx)
```

**Comment by masseelch** [comment]
Any particular reason this is added as annotation and not as part of the schema methods?

**Comment by tankbusta** [comment]
This would solve the issue I’m running into now as well. The changes to API flow isn’t a big deal because now that logic can be customized for upserts.

**Comment by panakour** [comment]
Any update on this?

**Comment by euskadi31** [comment]
Any update on this?

**Comment by a8m** [comment]
While I started implementing, I started to think of a different approach. Defining a new schema type named `edge.Schema` feels better to me. Please, see the following example: 

```go
// Tweet schema.
type Tweet struct {
	ent.Schema
}

func (Tweet) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("users_liked", User.Type).
			// Through allows defining M2M (join tables) explicitly using edge.Schemas.
			// The first argument ("likes") allows interacting with the join table by its name. 
			Through("likes", TweetLike.Type),
	}
}

// TweetLike schema (the join table).
// See the edge.Schema below.
type TweetLike struct {
	edge.Schema
}

// Additional fields.
func (TweetLike) Fields() []ent.Field {
	return []ent.Field{
		field.Time("timestamp").
			Default(time.Now),
	}
}

func (TweetLike) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tweet", Tweet.Type).
			Unique(),
		edge.To("user", User.Type).
			Unique(),
	}
}
```
In the above example, there's no need/way to define the PK explicitly. It's always set to the foreign keys (as it is today). Composite PKs can be added, but I feel it's not really part of this feature. 

Usage API:

Keep the generated code the same as it's today and provide extended API to allow query M2M edges (with Throught) in 2 flavors:

```go
// Query without going through the join-table explicitly. 
tweer.QueryUsersLiked().All(ctx)

// Query through.
tweer.QueryLikes().Where(tweetlike.TimestampGT(...)).QueryUsers().All(ctx)
```

Thoughts?

**Comment by euskadi31** [comment]
I have little experience with Entgo, but it sounds good to me!

**Comment by masseelch** [comment]
`ent.Schema` and `edge.Schema` are hard to distinguish. Can we call it `ent.Edge`? Or maybe `ent.Pivot`?

I like! 💯

**Comment by gmhafiz** [comment]
Laravel uses the `Pivot` vocab, fwiw.

**Comment by thmeitz** [comment]
Each framework has its own specialized language, syntax and semantics. All I need as a user is a good introduction to the framework in the documentation. 

We could call it `ent.Join` (which I think describes it best for developers working with SQL databases) or `ent.Pivot`.

**Comment by a8m** [comment]
Thanks all for the feedback. I need to digest it a bit and come up with a final naming proposal. 

`ent.Edge` is already taken and represents an edge in ent. `Pivot`/`Join` are too SQL-ish, and we support more database types atm, and plan to support more in the future.

`edge.Schema` is like an `ent.Schema`, you can attach policy, hooks, annotations, other edges, etc., but it represents an edge and not a node.

**Comment by thmeitz** [comment]
Interestingly, however, you described it exactly this way, so that we understand it: **(the join table)** 

`// TweetLike schema (the join table)`

**Comment by tonyabracadabra** [comment]
> 

❤️  love the example here and it would be a new milestone for ent to support this! One question, would there be any workaround (probably a less messy one) while we wait for this great addition to ent?

**Comment by tonyabracadabra** [comment]
> While I started implementing, I started to think of a different approach. Defining a new schema type named `edge.Schema` feels better to me. Please, see the following example:
> 
> ```go
> // Tweet schema.
> type Tweet struct {
> 	ent.Schema
> }
> 
> func (Tweet) Edges() []ent.Edge {
> 	return []ent.Edge{
> 		edge.To("users_liked", User.Type).
> 			// Through allows defining M2M (join tables) explicitly using edge.Schemas.
> 			// The first argument ("likes") allows interacting with the join table by its name. 
> 			Through("likes", TweetLike.Type),
> 	}
> }
> 
> // TweetLike schema (the join table).
> // See the edge.Schema below.
> type TweetLike struct {
> 	edge.Schema
> }
> 
> // Additional fields.
> func (TweetLike) Fields() []ent.Field {
> 	return []ent.Field{
> 		field.Time("timestamp").
> 			Default(time.Now),
> 	}
> }
> 
> func (TweetLike) Edges() []ent.Edge {
> 	return []ent.Edge{
> 		edge.To("tweet", Tweet.Type).
> 			Unique(),
> 		edge.To("user", User.Type).
> 			Unique(),
> 	}
> }
> ```
> 
> In the above example, there's no need/way to define the PK explicitly. It's always set to the foreign keys (as it is today). Composite PKs can be added, but I feel it's not really part of this feature.
> 
> Usage API:
> 
> Keep the generated code the same as it's today and provide extended API to allow query M2M edges (with Through) in 2 flavors:
> 
> ```go
> // Query without going through the join-table explicitly. 
> tweer.QueryUsersLiked().All(ctx)
> 
> // Query through.
> tweer.QueryLikes().Where(tweetlike.TimestampGT(...)).QueryUsers().All(ctx)
> ```
> 
> Thoughts?

❤️  love the example here and it would be a new milestone for ent to support this! One question, would there be any workaround (probably a less messy one) while we wait for this great addition to ent?

**Comment by nshaphan** [comment]
Hey,
Any progress on this issue? I want to add additional fields to the pivot table. any idea?

**Comment by fgm** [comment]
The `edge.Schema` approach seems more intuitive indeed, and you might want to rename `ent.Schema` to `field.Schema` for consistency (and probably keep `ent.Schema` as a deprecated alias to `field.Schema` for some releases).

**Comment by fgm** [comment]
Issue #400 looks like it's closely related to this, as these "edge with fields" tables would normally have such a composite PK instead of an ID.

**Comment by CNTWDev** [comment]
> A new `field.ID` option will be added to the `schema/field` package, and this will allow configuring multi-column PKs, but more than that, it will make it possible to configure relation/edge schema manually.

when i user Field.ID，error occurred.

how can i user the options.

**Comment by CNTWDev** [comment]
`func (TweetLike) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("tweet", Tweet.Type).
			Unique(),
		edge.To("user", User.Type).
			Unique(),
	}
}`

why define unique?
one person like one tweet?

**Comment by CNTWDev** [comment]
`go run entgo.io/ent/cmd/ent generate --feature privacy,entql,multi-column ./ent/schema
entc/load: load schema dir: /Users/shituanwei/Desktop/project/src/dailybible/ent/schema/accountchurch.go:23:9: ID not declared by package field
exit status 1
`

**Comment by CNTWDev** [comment]
`func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("users", User.Type).
			Through(UserGroup.Type),
	}
}`

prefer this way.
it's smooth, and much more stable.

**Comment by a8m** [comment]
Hey all! The initial support was added, and it's in review atm. See https://github.com/ent/ent/pull/2560 and please feel free to share your thoughts/feedback before it's merged.

**Comment by JamesHovious** [comment]
Is the `Edges` function required on the relation schema? 
	i.e. would a use case of wanting to add properties to the relation necessitate creating both a `Fields` and `Edges` on that schema, or could I just have `Fields` serving as the property for something like `created_at` ?

Will this feature be available for other relation types in addition to M2M ?

Can mixins work for the Fields of the relation just like they already exist?

The privacy policy on this is a really nice feature ;)

**Comment by a8m** [comment]
> Is the `Edges` function required on the relation schema?

Yes, the `Edges` is required as mentioned in https://github.com/ent/ent/pull/2560. Ent needs those fields/edges in the generated entities and their builders, and the idea here is to be explicit and consistent. If there's an edge or a field in the generated type, it must be part of the schema. 

> Will this feature be available for other relation types in addition to M2M?

Yes, it's mentioned in the docs.

> Can mixins work for the Fields of the relation just like they already exist?
> 
> The privacy policy on this is a really nice feature ;)

All features of regular schemas are supported. e.g. Mixin, Hooks, and Privacy.

**Comment by a8m** [comment]
Closed with https://github.com/ent/ent/pull/2560. Thank you all for the feedback.
