### ISSUE TITLE
Are there any reasons why enum values can't contain spaces?

### ISSUE THREAD

**Issue by theterminalguy** [ent/ent#1960]
Hi there! :wave: 

I get this error when trying to generate assets for fields with Enum value containing space.

![Screenshot from 2021-09-18 08-57-56](https://user-images.githubusercontent.com/17008072/133889595-a1123b0e-9907-4d5f-becf-5aae771c0d63.png)

Possible cause, this line [here](https://github.com/ent/ent/blob/430a3ee8b3334722f6f0062a9bb7257b6afb9c5b/entc/gen/type.go#L1380).

Any reasons why I can't have space for Enum values?

**Comment by a8m** [comment]
Hey @theterminalguy 👋 
No real reason. We can support this (and also #1961). I'll try to send a patch soon and will tag you. Thanks

**Comment by theterminalguy** [comment]
Thank you
