### ISSUE TITLE
ent non-string column not works with expression default

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1962]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```sql
alter table my_resources
  alter column tenant_id set default current_setting('tenant.id')::bigint;
```

```
sql/schema: scanning int value for column \"tenant_id\": converting driver.Value type string (\"(current_setting('tenant.id\") to a int64: invalid syntax
```

## Expected Behavior 🤔

ent work with expression default

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.9.1   |
| Database    | postgresql   |
| Driver      | pgx      |

**Comment by a8m** [comment]
Thanks for reporting this @wenerme. I submitted a fix for this https://github.com/ent/ent/pull/1967.

**Comment by wenerme** [comment]
Hi @a8m , problem still exists

https://github.com/ent/ent/blob/073215901e0c033898e79baf7ad1f6bc732cf196/dialect/sql/schema/schema.go#L236-L286

Column.ScanDefault will error out
