### ISSUE TITLE
How can I custom error message?

### ISSUE THREAD

**Issue by Macrow** [ent/ent#1963]
I seen some codes auto generated in ```ent.go```

```go
// Error implements the error interface.
func (e *NotFoundError) Error() string {
	return "ent: " + e.label + " not found"
}
```

When some errors raised, it throw some message like
```go
ent: user not found
```

How can I custom this error message? Just for I18n, more friendly message, etc...

Thanks!

**Comment by rotemtam** [comment]
Hi @Macrow,
Currently, there isn't a built-in way to customize the error message. It is expected to be done on the calling application side (inspect the error and wrap/modify it before passing back to users.) For example:

```go

if ent.IsNotFound(err) {
  return fmt.Errorf("a custom error message!")
}

```

**Comment by godcong** [comment]
Hi @rotemtam,
I have an idea.

**Comment by Macrow** [comment]
Hi @rotemtam  @godcong , thanks for sharing.
