### ISSUE TITLE
How to set field to null during upsert?

### ISSUE THREAD

**Issue by e48** [ent/ent#1979]
```go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Unique(),
		field.Int("age").
			Optional(),
		field.Time("created_at").
			Default(time.Now),
	}
}
```
```go
err := client.User.
	Create().
	SetName("a8m").
	SetAge(30).
	Exec(ctx)            
	
err = client.User.
	Create().
	SetName("a8m"). 
	// SetAgeNull() // not exists
	OnConflict().
	UpdateNewValues().
	Exec(ctx)
```

I would like to set the age field to null during upsert.

**Comment by a8m** [comment]
Hey @e48 and thanks for opening this issue. It looks like we don't have an example for this use case on our website. 

You can clear [**optional fields**](https://entgo.io/docs/schema-fields#optional) on conflict as follows:

```go
client.User.Create().
	SetName("a8m").
	SetAge(30).
	OnConflict().
	Update(func(u *ent.UserUpsert) {
		u.ClearAge()
	}).
	ExecX(ctx)
```

Please, feel free to contribute documentation improvement for the [upsert section](https://github.com/ent/ent/blob/master/doc/md/crud.md#upsert-one). Closing 🙏

**Comment by e48** [comment]
Thank you for the answer. But what I'm actually would like to do is bulk upsert with null values. Like:

```go
up := []*ent.UserCreate{
	client.User.Create().SetName("john").SetAge(30).SetPetNull(),
	client.User.Create().SetName("tom").SetAgeNull().SetPet(dog),
	...
}
ent.User.CreateBulk(up...).OnConflict().UpdateNewValues().Exec(ctx)

```

**Comment by masseelch** [comment]
If you don't call `SetName` it will be null in the.

**Comment by a8m** [comment]
Optional fields don't have NULL-setters (`Clear<Field>`) on create. For example, if the `age` field is optional, and the `SetAge` setter is not called, then the `age` field is set to NULL implicitly (the `SetAgeNull` method does not exist).

Does it answer your question? Also, what database do you use?

**Comment by e48** [comment]
I use sqlite. When I run the code from first comment, age is not set to null.

**Comment by a8m** [comment]
Hey @e48, `age` is NULL after the second command, because when you use the `UpdateNewValues` modifier, ent updates the database values with the ones that were provided to the creator. If you want to clear the `age` field (set it to NULL), use the example in my first comment: 

```go
client.User.Create().
	SetName("a8m").
	SetAge(30).
	SetAddress("TLV").
	OnConflict().
	// Use the new values, but also clear the `age` field. 
	UpdateNewValues().
	Update(func(u *ent.UserUpsert) {
		u.ClearAge()
	}).
	ExecX(ctx)
```

The above commands generates the following SQL statement:

```sql
INSERT INTO `users` (`age`, `name`, ...) VALUES (?, ?, ...) ON CONFLICT DO UPDATE SET `age` = NULL, `address` = `excluded`.`address`, `name` = `excluded`.`name`, ... RETURNING `id`
```

The same behavior applies also to the `CreateBulk` option.

**Comment by e48** [comment]
That works for single record, but is there any way to do bulk upsert UserUpsertOne?

**Comment by e48** [comment]
This is what queries ent actually generates:
```go
client.User.Create().
		SetName("a8m").
		SetAge(30).
		ExecX(ctx)

	client.User.Create().
		SetName("a8m").
		OnConflict().
		UpdateNewValues().
		ExecX(ctx)
		// age is still 30
		// ent: INSERT INTO `users` (`name`, `created_at`) VALUES (?, ?) ON CONFLICT 
		// DO UPDATE SET `name` = `excluded`.`name`, `created_at` = `excluded`.`created_at` RETURNING `id` args=...

	client.User.CreateBulk(
		client.User.Create().
			SetName("a8m"),
	).
		OnConflict().
		UpdateNewValues().
		ExecX(ctx)
		// age is still 30
		// ent: INSERT INTO `users` (`created_at`, `name`) VALUES (?, ?) ON CONFLICT 
		// DO UPDATE SET `created_at` = `excluded`.`created_at`, `name` = `excluded`.`name` RETURNING `id` args=...
```
So ent does not set null fields implicitly.

**Comment by e48** [comment]
End up implemented Clean* method(edges, optional fields) for creator myown. If anyone interested c426683139d292f26fdff371e81bf085a15148a4

**Comment by a8m** [comment]
> So ent does not set null fields implicitly.

Optional fields are set to NULL implicitly by the database, and therefore, ent does not add them to the INSERT statement as it's redundant and will make the statement longer. Like I mentioned above, if you're interested in **clearing** optional fields in case of conflict, call `Clear<Field>` explicitly either on the builder itself or with a custom function. 

```go
client.User.Create().
	// ...
	OnConflict().
	// Custom update function.
	Update(func(u *ent.UserUpsert) {
		u.ClearAge()
	}).
	// Or on the builder.
	ClearAge().
	ExecX(ctx)
```

> End up implemented Clear* method(edges, optional fields) for creator myown. If anyone interested c426683139d292f26fdff371e81bf085a15148a4

I don't have access to it. Please paste here a link.
