### ISSUE TITLE
Why the unnecessary code generation?

### ISSUE THREAD

**Issue by theterminalguy** [ent/ent#1981]
I noticed anytime I do any of the following 

- Change the order of the fields defined in the schema (_Not any field related attributes, just the order_)
- Refactor common edges, indexes, and fields into mixins and reuse that mixin

Running `go generate ./ent` will regenerate the autogenerated files despite nothing significant changed except the reordering of the fields or extracting shared pieces of code into mixin. 

I think a regeneration should only happen if something significant changed. Like a field's datatype, type of indexes, etc. 

**P.S** _This question was asked out of mere curiosity. It is in no way intended to be a feature request_

## Screenshots

**Initial code structure**
<img width="584" alt="Screen Shot 2021-09-24 at 7 50 04 PM" src="https://user-images.githubusercontent.com/17008072/134750243-6bf65f18-199e-4d75-8ab7-3da5b403c405.png">

**Just switched lines: sometimes I do this just for formatting sake**
<img width="599" alt="Screen Shot 2021-09-24 at 7 50 18 PM" src="https://user-images.githubusercontent.com/17008072/134750247-d4a6620b-ff9f-4650-a088-cd94eea451d1.png">

**Running generate and doing a git diff**
<img width="916" alt="Screen Shot 2021-09-24 at 7 50 53 PM" src="https://user-images.githubusercontent.com/17008072/134750249-fb21c6d7-8a3c-420a-ad2d-61dc6c7587fb.png">

**Comment by aaahrens** [comment]
I don't think go generation detects file changes. i believe it just re outputs the same files.

Perhaps you're thinking of bazel?

**Comment by rotemtam** [comment]
Hi @theterminalguy ,
Thanks for reaching out!
I think the behavior you are describing is expected. 

As a user of Ent, I would expect that the result of code gen would be deterministic, that is, for any input state (schema definitions) the output (generated source code) would be identical. In fact, you can see that this is constantly checked by Ent's own CI - on every commit we rerun go generate and use diff to verify that no files have changed.

The reason you see source code changing when you change field order, is that you _are_ changing the input. Field order does have meaning. For example, it determines the order of the columns in the SQL tables generated by Ent's migration!

Does this answer your question?

**Comment by theterminalguy** [comment]
Yes it does @rotemtam , this makes sense now. Much appreciated.
