### ISSUE TITLE
Upserting a row with UUID as ID results in an error

### ISSUE THREAD

**Issue by 726b** [ent/ent#1985]
First of all let me just say THANK YOU to everyone's involved in this project.

I extremely appreciate all of your work.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I use UUIDs ([Google's package](https://github.com/google/uuid)) as primary keys, for example:
````go
func (Test) Fields() []ent.Field {
	return []ent.Field{
		field.UUID(`id`, uuid.UUID{}).Unique(),
		field.Int8(`count`).Min(0),
	}
}
````

If I insert new rows, everything works as expected without errors:
````go
err = r.client.Test.
	Create().
	SetID(id).
	SetCount(1).
	Exec(r.context)
````

But, if I try to upsert rows, even new ones:
````go
err = r.client.Test.
	Create().
	SetID(id).
	SetCount(currentCount + 1).
	OnConflictColumns(test.FieldID).
	UpdateCount().
	Exec(r.context)
````

I get the following error: `interface conversion: driver.Value is string, not uuid.UUID`

## Expected Behavior 🤔

I expect a new row to be updated if the ID exists or inserted if the ID does not exist, without any error.

## Steps to Reproduce 🕹

I think the above code should suffice to reproduce the issue.

## Some Notes

I tracked the issue to a method called `sqlSave` in the generated file `test_create.go`, to the following lines:
````go
if _spec.ID.Value != nil {
	_node.ID = _spec.ID.Value.(uuid.UUID)
}
````

I _believe_ the issue is related to the combination of Ent's upsert and Google's UUID Value method.

When just inserting a new row (without `OnConflictColumns`) the type definition `_spec.ID.Type` is `field.TypeUUID`, or `[16]byte` as you defined it, and the actual type of `_spec.ID.Value` is `uuid.UUID`.

But when upserting a row, while the type definition `_spec.ID.Type` remains the same `field.TypeUUID`/`[16]byte`, the actual type of `_spec.ID.Value` is `string`.

It looks like the function `sqlgraph.CreateNode` is doing something to `_spec`, because before it is called, `_spec.ID.Value`'s type is `uuid.UUID`, and after it's run the type changes to `string`.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.1  |
| Ent         | 0.9.1   |
| Database    | PostgreSQL   |
| Driver      | github.com/jackc/pgx/v4/stdlib        |

I hope I've been as helpful as possible, let me know if there's anything else I can do.

**Comment by a8m** [comment]
Thanks for reporting this @726b. I'll give it a look and update you.

**Comment by a8m** [comment]
Thanks again for reporting this. A patch was created to address this issue (see https://github.com/ent/ent/pull/1987) and should be land tomorrow.

**Comment by 726b** [comment]
Thank you @a8m for this package, again I extremely appreciate you and everyone else's work here.

**Comment by a8m** [comment]
Closed with https://github.com/ent/ent/pull/1987

Please update to the latest master version as follows:

```
go get entgo.io/ent@master
```

**Comment by shota-hizawa** [comment]
@a8m 
I'm using ent v0.10.1, but it seems like this issue still remain when I use custom IDs as ID.

To give an example, I use [ULIDs](github.com/oklog/ulid/v2) as primary keys.

```
func (Test) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			GoType(ulid.ID("")).
			DefaultFunc(func() ulid.ID { return ulid.New() }),
	}
}
```

if I try to upsert rows,

```
err := client.Test.Create().OnConflict(sql.ResolveWithNewValues()).Exec(ctx);
```

I get the following error: `unexpected Test.ID type: string`
