### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by wr125** [ent/ent#1991]
application want compile / seed the db 

- [ X] The issue is present in the latest release.
- [X ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior 🤔
error message

compile 
## Steps to Reproduce 🕹
Error message
go run server.go
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85d996]

goroutine 1 [running]:
github.com/wr125/auction_ent/ent.(*UserCreate).check(0xc000081720)
        /home/robert/go/src/github.com/wr125/auction_ent/ent/user_create.go:210 +0x56
github.com/wr125/auction_ent/ent.(*UserCreateBulk).Save.func1.1({0xa20a50, 0xc0000ac000}, {0xa2acb0, 0xc000108700})
        /home/robert/go/src/github.com/wr125/auction_ent/ent/user_create.go:377 +0x156
entgo.io/ent.MutateFunc.Mutate(0xc0000955c0, {0xa20a50, 0xc0000ac000}, {0xa2acb0, 0xc000108700})
        /home/robert/go/pkg/mod/entgo.io/ent@v0.9.2-0.20210822190728-d84ac191b1c7/ent.go:347 +0x3d
github.com/wr125/auction_ent/ent.(*UserCreateBulk).Save(0xc0000dce00, {0xa20a50, 0xc0000ac000})
        /home/robert/go/src/github.com/wr125/auction_ent/ent/user_create.go:412 +0x1a3
github.com/wr125/auction_ent/ent.(*UserCreateBulk).Exec(...)
        /home/robert/go/src/github.com/wr125/auction_ent/ent/user_create.go:430
main.UserFun({0xa20a50, 0xc0000ac000}, 0xc000097d40)
        /home/robert/go/src/github.com/wr125/auction_ent/ent/server/server.go:70 +0x3c5
main.main()
        /home/robert/go/src/github.com/wr125/auction_ent/ent/server/server.go:27 +0xc6
exit status 2
```

Steps:

1.make changes to schema
 2.drop db
3. migrate db
4. createBulk
5. using elk

## Your Environment 🌎
linux mint

deleted db in order to create new fields
. 
| Tech        | Version |
| ----------- | ------- |
| Go          | 1.15.?  | 1.17
| Ent         | 0.5.?   | latest
| Database    | Mysql   | mysql
| Driver      | https://github.com/go-sql-driver/mysql        |  "github.com/go-sql-driver/mysql"

**Comment by a8m** [comment]
Hey @wr125, can you please upgrade your Go and ent version and report if you still get these errors? Also, a code/repository example to reproduce this can help here.

**Comment by wr125** [comment]
Problem solved by elk

**Comment by a8m** [comment]
> Problem solved by elk

Thanks
