### ISSUE TITLE
Defining a O2M Edge with bytes array as ID results in an error

### ISSUE THREAD

**Issue by 726b** [ent/ent#1992]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Let's say I have a User entity and Session entity in a one to many relation:
````go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Unique(),
		field.String("name"),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("sessions", Session.Type),
	}
}
````

````go
func (Session) Fields() []ent.Field {
	return []ent.Field{
		field.Bytes("id").Unique(),
		field.Time("max_age"),
	}
}

func (Session) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).
			Ref("sessions").
			Unique(),
	}
}
````

After generating the code, I get the following 4 errors in `mutations.go`: `incomparable map key type []byte`
````go
session             map[[]byte]struct{}
removedsession      map[[]byte]struct{}
````
````go
func (m *UserMutation) AddSessionIDs(ids ...[]byte) {
	if m.session == nil {
		m.session = make(map[[]byte]struct{}) // <―
	}
	for i := range ids {
		m.session[ids[i]] = struct{}{}
	}
}
````
````go
func (m *UserMutation) RemoveSessionIDs(ids ...[]byte) {
	if m.removedsession == nil {
		m.removedsession = make(map[[]byte]struct{}) // <―
	}
	for i := range ids {
		delete(m.session, ids[i])
		m.removedsession[ids[i]] = struct{}{}
	}
}
````

## Expected Behavior 🤔

I know it's impossible to use `[]byte` as a map key.

I tried to use a custom type, but it's too much extra code and loses elegance. Surely there's something else we can do?

## Steps to Reproduce 🕹

I believe the above code should suffice to reproduce the issue.

## Some Notes

If I change the Session ID field type to something else, let's say `string`, everything works as expected:
````go
func (Session) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").Unique(),
		field.Time("max_age"),
	}
}
````

Another thing I noticed is that setting `Unique()` on the User's edge also "solves" the issue (I guess because now it has only one edge so it doesn't need the map).

Please let me know if there's anything else I can do.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.1  |
| Ent         | 0.9.2   |
| Database    | PostgreSQL   |
| Driver      | github.com/jackc/pgx/v4/stdlib       |

**Comment by a8m** [comment]
Hey @726b and thanks for reporting this. Using an ID of type `[]byte` is not "officially supported", although I know some folks here use it. 

I don't think it's a big deal to support it. I'll try to give it a look later and update you

**Comment by a8m** [comment]
OK, I gave it a try, but to be honest, adding support for non-comparable ID fields adds too much extra complexity (and magic) to the code generator which I don't like. I actually implemented it but decided to not merge it as this complexity can be avoided with less than 10 lines of code in the user's schema. 

An example of a comparable `field.Bytes` type can be a string, array of bytes/runes, or any other Go type that implements the `ValueScanner` interface (added another example in https://github.com/ent/ent/pull/1998).

I'm closing this for now, but I'll love to continue the discussion here or in [Slack](https://entgo.io/docs/slack/), and of course, feel free to reopen if you disagree with my conclusion. 

cc @rotemtam

**Comment by 726b** [comment]
First of all @a8m thanks for the effort. Like you, the last thing I want is to increase Ent's complexity.

It might be stupid, but if not, would you consider making a `FixedBytes` field? With a second parameter being size.

I'm not sure, but It seems like it might solve the problem for most use cases ― I just can't imagine a case where you'd have a variable-length _ID_ field ― but I don't know how much work is involved and how useful other users would find it.
