### ISSUE TITLE
expose `Add` helpers on `UpdateOneID`

### ISSUE THREAD

**Issue by tarrencev** [ent/ent#1995]
Currently, `UpdateOneID` does not support the `Add*` helpers for incrementing/decrementing numeric values. Could we add there there too?

**Comment by a8m** [comment]
Hey @tarrencev 👋
The `Add<F>` modifiers are added both to `Update` and `UpdateOne` builders. Please see an example in our integration tests:

https://github.com/ent/ent/blob/625e422a082c8743004ae92f128d11bdce7f8e9e/entc/integration/ent/user_update.go#L1379-L1383

I wonder why you can't see these methods in your generated code. Any chance you can provide a sample schema to reproduce this? Thanks

**Comment by tarrencev** [comment]
Hey! I have an field like:

```
field.Int("supply").
  GoType(BigInt{}).
  SchemaType(BigIntSchemaType).
  Immutable().
  DefaultFunc(func() BigInt {
  return NewBigInt(0)
  }),
```

I'm actually not seeing `SetSupply` or `AddSupply` on the `Update` or `UpdateOne` methods.

**Comment by tarrencev** [comment]
hey! I just realized the field is set to immutable 😅
