### ISSUE TITLE
Feature: add null check for strings

### ISSUE THREAD

**Issue by godcong** [ent/ent#1999]
Now, if you define the field as a `strings`
at query time, there won't be any available methods in `Where`

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

`strings` should have basic null or non-null checks.

## Motivation 🔦

I would like to be able to use a simple method to determine null or non-null.
But now I don't know how to check these empty data.
In the database it shows `null`, but he is not a null field.

**Comment by a8m** [comment]
Hey @godcong and thanks for opening this issue. The codegen generates today predicates for checking column nullability (`column` IS NULL). See [example](https://github.com/ent/ent/blob/master/entc/integration/ent/fieldtype/where.go#L5623-L5627) in our integration tests.

However, this does not work for checking JSON nullability (`null`). Is this what you are looking for?

**Comment by godcong** [comment]
@a8m 
Because I didn't write any data, but it's not `NULL` in the database, it's the string `null`.
I want to check there is no data whether it is `NULL` or `null`, but there seems to be no way to check that.
`StringsNotNil` can check the `NULL` in the database,But the database is `null` string, even though I haven't written any data.
