### ISSUE TITLE
using index.Fields().Unique() for single column causes DROP/CREATE INDEX migration cycle

### ISSUE THREAD

**Issue by Liooo** [ent/ent#2003]
- [x] The issue is present in the latest release. 
    - as of 87e21993097e
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.
    - https://github.com/ent/ent/issues/1344 was reporting the same phenomenon but different issue

## Current Behavior 😯

The following schema causes DROP/CREATE INDEX migration cycle. Though it is mentioned in the document to use `field.String().Unique()` for single column, I'm assuming this behavior is unintentional.

```go
// ent/schema/user.go

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
)

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("email"),
	}
}

func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("email").Unique(),
	}
}
```

`DROP INDEX` is happening here:

https://github.com/ent/ent/blob/master/dialect/sql/schema/migrate.go#L344

## Expected Behavior 🤔

either of the following:

- raise error when `index.Field(..).Unique()` with single column is used
- accept single column `index.Field(..).Unique()` and migration cycle does not happen

## Steps to Reproduce 🕹

Steps:

1. add the schema above
2. run ent auto migration

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16  |
| Ent         | v0.9.2-0.20210929153101-87e21993097e  |
| Database    | Postgres   |
| Driver      | 	github.com/jackc/pgx/v4 v4.13.0       |

**Comment by a8m** [comment]
Hey @Liooo and thanks for reporting this issue.

What's your PostgreSQL version? Thanks 🙏

**Comment by Liooo** [comment]
Hey @a8m thanks for the quick response 👍 

```
❯ postgres --version
postgres (PostgreSQL) 13.3
```

**Comment by a8m** [comment]
Hey @Liooo, I was able to reproduce this and submitted a patch #2004 

Please, update to the latest master version, and let me know if we can close this issue. Thanks 🙏

**Comment by Liooo** [comment]
@a8m that was the fastest fix I've seen in opensource 🚀 lol thanks so much, ill check later 🙏

**Comment by Liooo** [comment]
confirmed the fix, closing 👍
