### ISSUE TITLE
How to config Index fulltext in function Indexes() when use MySQL?

### ISSUE THREAD

**Issue by BeatsKitano** [ent/ent#2007]

**Comment by a8m** [comment]
Hey @HHHsiang and thanks for opening this issue 🙏 

Currently, Ent does not provide a way to configure the `Index` creation besides a few annotations. It's definitely something we plan to support in the migration. I'll keep this issue open and we'll update when it will be added.

**Comment by a8m** [comment]
The issue was resolved with Atlas. Please, see https://entgo.io/docs/schema-indexes#atlas-support. 

Thanks for the feedback 🙏
