### ISSUE TITLE
Fails to count unique field

### ISSUE THREAD

**Issue by naorsec** [ent/ent#2036]
Trying to count all distinct values of a field using the `Unique` identifier does not work.
If there is another way to perform it that I miss I would be happy to know :)

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

By https://entgo.io/docs/crud/#field-selection I can select all field names of pets using
```
names, err := client.Pet.
    Query().
    Unique(true).
    Select(pet.FieldName).
    Strings(ctx)
```
However, If I run 
```
names, err := client.Pet.
    Query().
    Unique(true).
    Select(pet.FieldName).
    Count(ctx)
```
The query returned is:
```
SELECT COUNT(DISTINCT "pets"."id") FROM "pets"
```

## Expected Behavior 🤔

The expected behavior for the last ent query was to run
```
SELECT COUNT(DISTINCT "pets"."name") FROM "pets"
```

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | v0.9.2-0.20210921174501-2b128340d3db   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx        |

**Comment by a8m** [comment]
Thanks for reporting this @naorsec. Giving it a look now.

**Comment by a8m** [comment]
Thanks for reporting this https://github.com/ent/ent/pull/2037 🙏
