### ISSUE TITLE
Question: about ent migrate on tidb failed

### ISSUE THREAD

**Issue by godcong** [ent/ent#2048]
Hi,all
I'm using tidb, but it has some compatibility issues with mysql,
is there any good suggestion to solve these issues?

https://docs.pingcap.com/tidb/stable/mysql-compatibility#ddl

```
Multiple operations cannot be completed in a single ALTER TABLE statement. For example, it is not possible to add multiple columns or indexes in a single statement. Otherwise, the Unsupported multi schema change error might be output.

ALTER TABLE in TiDB does not support the changes of some data types. For example, TiDB does not support the change from the DECIMAL type to the DATE type. If a data type change is unsupported, TiDB reports the Unsupported modify column: type %d not match origin %d error. Refer to ALTER TABLE for more details.
```
The main thing is these two issues

**Comment by godcong** [comment]
This issue looks like it will solve the problem at hand.
Waiting for a new version release
https://github.com/pingcap/tidb/issues/14766

**Comment by Thearas** [comment]
Hi @godcong, for now, the compatibility between ent and TiDB is not ideal.
I would choose not to run migration at online but [offline](https://entgo.io/docs/migrate#offline-mode), and print the migration SQLs to file for us to check and modify it.

**Comment by godcong** [comment]
Hi @Thearas.
We did not encounter any major problems with the basic usage.
Normally we would try it in `mysql` first and then update the fields in manually when we encounter a problem.

**Comment by hedwigz** [comment]
Hey @godcong  :smiley: 
With the new migration engine, `Atlas`, this is now resolved.  
Upgrade to `entgo.io/ent@master` and use `schema.WithAtlas(true)`
```go
client.Schema.Create(context.Background(), schema.WithAtlas(true))
```

**Comment by godcong** [comment]
@hedwigz Thanks,Let me try.

**Comment by godcong** [comment]
migration success.
close this.
