### ISSUE TITLE
Edge-related fields should be included in the json-marshallable model

### ISSUE THREAD

**Issue by idc77** [ent/ent#2091]
Hi,

I didn't create this issue as a bug or feature request, but I guess it is a feature request, or maybe I'm missing something.
Also there are so many pages of issues that I've only checked the first 5.

simple relation of Post and Comment

```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Post holds the schema definition for the Post entity.
type Post struct {
	ent.Schema
}

// Fields of the Post.
func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id"),
		field.Time("created_at"),
		field.Time("updated_at").Optional().Nillable(),
		field.String("subject_id"),
		field.String("username"),
		field.Text("content_raw"),
	}
}

// Edges of the Post.
func (Post) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("comments", Comment.Type),
	}
}
```

```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Comment holds the schema definition for the Comment entity.
type Comment struct {
	ent.Schema
}

// Fields of the Comment.
func (Comment) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id"),
		field.Time("created_at"),
		field.Time("updated_at").Optional().Nillable(),
		field.String("subject_id"),
		field.String("username"),
		field.Text("content_raw"),
	}
}

// Edges of the Comment.
func (Comment) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("post", Post.Type).Ref("comments").Unique(),
	}
}
```

I'm retrieving comment JSON from an endpoint
```go
func (h *Handler) CommentList(cx *gin.Context) {
	postID := cx.Query("post_id")
	if postID != "" {
		postID64, e := strconv.ParseInt(postID, 10, 64)
		if e != nil {
			cx.AbortWithStatusJSON(http.StatusBadRequest, gin.H{"error": e.Error()})
			return
		}
		ms, e := h.client.Comment.Query().Where(func(selector *sql.Selector) {
			selector.Where(sql.EQ("post_comments", postID64))
		}).All(context.Background())
		if e != nil {
			cx.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": e.Error()})
			return
		}
		cx.SecureJSON(http.StatusOK, ms)
	} else {
		ms, e := h.client.Comment.Query().All(context.Background())
		if e != nil {
			cx.AbortWithStatusJSON(http.StatusInternalServerError, gin.H{"error": e.Error()})
			return
		}
		cx.SecureJSON(http.StatusOK, ms)
	}
}
```

when querying the comments endpoint this is the JSON I get
```json
)]}',
[{"id":1,"created_at":"2021-10-27T14:05:24Z","subject_id":"4d1debda-3a29-4daf-9b7f-a8474041f6b6","username":"tester","content_raw":"No Comment No cry","edges":{}}]
```

On the client I use vuex-orm which is able to define relationships between data models. Example:
```js
import { Model } from '@vuex-orm/core'
import Comment from 'src/store/models/Comment'

export default class Post extends Model {
  static entity = 'post'

  static fields () {
    return {
      created_at: this.attr(null),
      updated_at: this.attr(null).nullable(),

      id: this.uid(),
      subject_id: this.string(''),
      username: this.string(''),
      content_raw: this.string(''),
      comments: this.hasMany(Comment, 'post_comments')
    }
  }
}
```
You see I can say `post_comments` is the "post_id" field of comments,
but... where is the field in the JSON representation?

Is there a way to include edge-related fields in the output of the model, without resorting to manual SQL querying and parsing?
And if not, why not? It should absolutely be included.

So while that's probably ok if you have classic server rendered websites it's unusable for RESTful APIs.
I have started working on an open source project, like a wordpress clone. The website will be rendered via Go but the backend (or admin ui) will use some js framework and REST. How can I use REST that returns JSON when the relationship fields aren't returned? I can't.

If you manually add a `field.Int64("post_id"),` you can't use edges because the generator creates a SetPostID method with the edge being set. You'll get a generation error.

There should be an `AllE()`or `Complete()` or `Full()` method in addition to `All()` and likewise for single entity results.

Providing a custom struct to marshall into is certainly **NOT** the proper way to handle this and can only serve as a temporary workaround.

**Comment by rotemtam** [comment]
Hey @idc77 
thanks for reaching out!
Does eager loading not work for you?

**Comment by rotemtam** [comment]
Also, if you don't want to write REST servers by hand, which is a tedious and boring task - I agree, I strongly suggest you look at @masseelch's brilliant work with https://github.com/masseelch/elk

**Comment by a8m** [comment]
Hey @idc77 👋,
Closing as this question was answered in https://github.com/ent/ent/issues/2092. Please, let me know if I can close https://github.com/ent/ent/issues/2092 as well. Thanks 😃
