### ISSUE TITLE
FR: include edge related fields in the default response or provide a WithEdgeFields() option

### ISSUE THREAD

**Issue by idc77** [ent/ent#2092]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Please see #2091 
## Motivation 🔦

I'm trying to return an entity including edge related fields example Post hasMany Comments, where Comment hold as reference to Post's ID. This reference is not returned by default and requires severe work-related overhead in almost each individual CRUD method, from manually providing all selectable fields to defining a custom struct and copying values from a response struct to a "return via JSON endpoint"-marhsallable struct.

**Comment by a8m** [comment]
Hey @idc77 👋, and thanks @crossworth and @masseelch for the support.

If you want to add the `PostID` field to the generated entity, please read the [edge-fields](https://entgo.io/docs/schema-edges/#edge-field) docs on our website, or see the [examples](https://github.com/ent/ent/blob/master/entc/integration/edgefield/ent/schema/pet.go#L21-L31) in the integration tests.

**Comment by idc77** [comment]
eager loading does not solve this.

With eager loading the related model is return in 
```json
{
   "id":1,
   "created_at":"2021-10-31T11:13:01Z",
   "subject_id":"4d1debda-2a29-4caf-9b7f-a8474051f6b6",
   "username":"a",
   "content_raw":"Post",
   "edges":{
      "comments":[
         {
            "id":1,
            "created_at":"2021-10-31T11:13:48Z",
            "subject_id":"4d1debda-2a29-4caf-9b7f-a8474051f6b6",
            "username":"a",
            "content_raw":"Comment",
            "edges":{
               
            }
         }
      ]
   }
}
```

This is from querying a single post.
I can't work with this.

Thanks for suggesting elk, but there needs to be some sanitation going as you can see from the 2091 handler.
Also I'm aware of privacy but some endpoints require fine grained decision making.

Best practice frontend you use a data store redux, vuex, ngrx, etc...
How do you update one comment, first of all you need to know which post it's associated with, but how can you know that when there is no info about the post's id provided by the backend?
Idk if you've ever done any frontend, if you did, this should be clear as day.

The irony is PostID is generated, but it's not in the Comment struct. You can even SetPostID() when you update, despite that the field is called post_comments in the database.

This is of course a simple 1:m relation
In m:m relations for instance one would also have to be able to access the m:m tables.

Imagine a list of all comments. They're all transferred to the client.
You take those comment entities and push them into the data store after normalization.
Now you'd like to filter those comments by post relationship.
You can't!
Where is the reference to post? It's not there.
```json
         {
            "id":1,
            "created_at":"2021-10-31T11:13:48Z",
            "subject_id":"4d1debda-2a29-4caf-9b7f-a8474051f6b6",
            "username":"a",
            "content_raw":"Comment",
            "edges":{
               
            }
```
There is no post id anywhere
You're thinking in GraphQL standards where you write queries in the client and put the burden on the server but claim you're an ORM, you're not or rather ent isn't an ORM if you can't provide related fields in the response.
I'm not aware of many clients able to deal with DDD type REST APIs.
vuex-orm with the vuex-orm-axios is one and the best.
There's ngrx-data but it can't handle relationships, you have to manually write selectors.
I'm not a React guy so I can't comment on redux-orm.
There is no orm I'm aware of for svelte or flutter.

I won't start a discussion about how wrong on every level GraphQL is but you can think your piece.

If you want this to be an ORM you have to provide related fields and tables, make them queryable. And if not and expect the user to manually do the work there are better libraries like sqlboiler, sqlc and so on, even gorm.

It's utopic to expect you can just generate your backend and never look back. If you expect that then you're lying to yourself.
Returning things in edge is the lazy way out.

ent, so far, is nice for schema generation and migration but gorm can do just as well.

Funny thing, again, the field already exists in the database, why isn't it exposed?
Doesn't make sense to me.

**Comment by a8m** [comment]
> Hey @idc77 👋, and thanks @crossworth and @masseelch for the support.
> 
> If you want to add the `PostID` field to the generated entity, please read the [edge-fields](https://entgo.io/docs/schema-edges/#edge-field) docs on our website, or see the [examples](https://github.com/ent/ent/blob/master/entc/integration/edgefield/ent/schema/pet.go#L21-L31) in the integration tests.

Hey @idc77, please read the above comment. What you are looking for is called "edge field" and exists on our website. Please see https://entgo.io/docs/schema-edges/#edge-field

**Comment by idc77** [comment]
@a8m thank you, my bad.

Sorry I sometimes get overemotional :D

**Comment by idc77** [comment]
But if you want to set StorageKey in the Edge definitions it won't work, because .StorageKey() isn't accepted there
