### ISSUE TITLE
M2M edge insertion logic ignores upsert conflict resolution options

### ISSUE THREAD

**Issue by edigaryev** [ent/ent#2093]
Hello! First of all, thanks for your work on this package.

I have the following schema:

```go
// user.go

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").Unique(),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("books", Book.Type),
	}
}
```

```go
// book.go

func (Book) Fields() []ent.Field {
	return []ent.Field{
		field.String("author"),
		field.String("title"),
	}
}

func (Book) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("user", User.Type).Ref("books"),
	}
}

func (Book) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("author", "title").Unique(),
	}
}
```

And the following code:

```go
// main.go

func main() {
	ctx := context.Background()

	client, err := ent.Open("postgres", "...")
	if err != nil {
		panic(err)
	}

	if err := client.Schema.Create(ctx); err != nil {
		panic(err)
	}

	userID, err := client.User.Create().
		SetName("John Doe").
		OnConflictColumns(user.FieldName).Ignore().
		ID(ctx)
	if err != nil {
		panic(err)
	}

	err = client.Book.Create().
		AddUserIDs(userID).
		SetAuthor("Arthur Conan Doyle").
		SetTitle("The Valley of Fear").
		OnConflictColumns(book.FieldAuthor, book.FieldTitle).Ignore().
		Exec(ctx)
	if err != nil {
		panic(err)
	}
}
```

The first execution succeeds, and creates the following entries:

```
postgres=# select * from users;
 id |   name   
----+----------
  1 | John Doe
(1 row)

postgres=# select * from books;
 id |       author       |       title        
----+--------------------+--------------------
  1 | Arthur Conan Doyle | The Valley of Fear
(1 row)
```

However, the second execution fails with `ent.ConstraintError` error (`add m2m edge for table user_books: pq: duplicate key value violates unique constraint "user_books_pkey"`), despite the fact that upsert was requested via `OnConflictColumns()`.

Looking deeper, it seems that M2M edge insertion logic completely ignores the existence of upsert:

https://github.com/ent/ent/blob/51b63c17c0185ff9f75c502e030ed38f3c025c10/dialect/sql/sqlgraph/graph.go#L1111-L1144

It would be nice if M2M edge conflicts would resolve automatically depending on the upsert options requested, or via a separate option.

**Comment by edigaryev** [comment]
> It would be nice if M2M edge conflicts would resolve automatically depending on the upsert options requested, or via a separate option.

Found https://github.com/ent/ent/issues/537#issuecomment-641894671 that proposes to add `Add<E>IfNotExist()` method to solve this:

> Maybe, we can add something like `Add<E>IfNotExist()` for edges, but I need to think about it - I'll create a separate issue for this if I'll think it's necessary.

**Comment by diazoxide** [comment]
@edigaryev agree with you. I think Upsert philosophy covered your mention. Hope that someone will add that functionality

**Comment by diazoxide** [comment]
@a8m maybe some recommendation?

**Comment by a8m** [comment]
Closed with https://github.com/ent/ent/pull/3108. Please, update to master to get this functionality. Thanks 🙏🏻
