### ISSUE TITLE
Option for entproto to Generate GetAll RPC for Services

### ISSUE THREAD

**Issue by JeremyV2014** [ent/ent#2107]
I would like the option to tell entproto to generate an additional "GetAll" RPC alongside the CRUD RPCs. This RPC would provide either all entities or all ids of entities of the particular type that exist.

- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Calling the GetAll RPC should return a message that either contains a repeated field of the particular entity type or a repeated field of ids that exist. For example:
```
/* user_group.go */
...

// Annotations of the UserGroup.
func (UserGroup) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(),
		entproto.Service(),
		entproto.GetAllService(), // Annotation telling protoc-gen-entgrpc to generate the GetAll RPC
	}
}

...


/* entpb.proto */
...

message UserGroupId {
  int32 id = 1;
}

message UserGroupIds {
  repeated UserGroupId user_group_ids = 1;
}

service UserGroupService {
  rpc Create ( CreateUserGroupRequest ) returns ( UserGroup );

  rpc Get ( GetUserGroupRequest ) returns ( UserGroup );

  rpc GetAll ( google.protobuf.Empty ) reutrns ( UserGroupIds );

  rpc Update ( UpdateUserGroupRequest ) returns ( UserGroup );

  rpc Delete ( DeleteUserGroupRequest ) returns ( google.protobuf.Empty );
}

...


/* gRPC Client Usage */
...

// Create a UserGroup service Client on the connection.
client := entpb.NewUserGroupServiceClient(conn)
ctx := context.Background()

// Gets ids of all user groups
get, err := client.GetAll(ctx, &emptypb.Empty{})

// Do something with this information
log.Println(get.UserGroupIds)

...
```

Generating the "GetAll" RPC could be supported through modifying `createServiceResources()` in `entproto/service.go` to add an additional 'get_all' method or a separate function could be defined for optionally generated service resources. Additionally, an `extractGetAllService()` function could be defined to extract the appropriate annotation. `entproto/adapter.go` could be modified to check for this annotation and either pass additional flag to `createServiceResources()` to generate the GetAll RPC or call a new function for handling this.

To generate the Go code, `entproto/cmd/protoc-gen-entgrpc/template/service.tmpl` could be modified to check for the "GetAll" method and call a new method, `method_getall`:

```
...
{{- if eq $methodName "Get" }}
    {{ template "method_get" (method .) }}
{{- else if eq $methodName "GetAll" }}
    {{ template "method_getall" (method .) }}
{{- else if eq $methodName "Delete" }}
    {{ template "method_delete" (method .) }}
{{- else if or (eq $methodName "Create") (eq $methodName "Update") }}
    {{ template "method_mutate" (method .) }}
{{- end }}
...
```
A new template `method_getall.tmpl` could be defined to generate the RPC implementation in Go (or method_get.tmpl could be modified, but I think the code would be dissimilar enough to warrant a new template).

## Motivation 🔦
Current generated Get RPC requires you to know the ID of the entity you would like to get information on. There are scenarios where getting a list of the IDs/entities that exist would be useful. For example, I have a list of globally-available assets that I want to populate with all the entities of a certain type. The gRPC client has no knowledge ahead of time of what the IDs of these entities might be so it has no way to populate this list using the generated gRPC services. Having a "GetAll" RPC, either returning the entities or just the IDs that could be used for the Get RPC, would enable this use case.

A separate service could manually be defined to support this, but changes to the schema would require updating this service which would become cumbersome and error-prone. It would be better if this were generated automatically by entproto,

As additional motivation, I have already been testing implementing this idea and have hacked it in so I know it's possible to implement and would be willing to contribute this feature. I would just like some feedback and design direction before committing the time to implement it properly. :grin:

**Comment by rotemtam** [comment]
Hi @JeremyV2014 
Thanks for reaching out and for the detailed issue 😍 

This is something I've considered adding in the past, and as you mentioned implementing it is straightforward. I'm leaning towards not adding it, and I will try to explain why

A GetAll method basically adds a full-table-scan operation to the API of a service. In anything other than a table that is guaranteed to remain tiny, it can be dangerous to expose to clients. The running time is O(n) as is the memory and network bandwidth required to satisfy it. `n` is only bound by the storage limitations of the host machine (and by some design decisions made by the implementors of various db engines) and therefore can be a very costly operation. On the client size, the payload size could easily be way more than the available RAM (consider an IoT device or basic mobile phone).

At the very minimum, such an API should impose hard maximum page size limits, and parameters to configure the desired page size for the client,  pagination controls, etc. 

When implementing the gRPC plugin, we tried to align ourselves with a group of Google specifications such as [AIP-131 Standard methods: Get](https://google.aip.dev/131).  I'm not 100% sure about it, but perhaps we can use [AIP-132 Standard methods: List](https://google.aip.dev/132) as a starting point for the design. Concepts don't map 1:1 to Ent (for example what is the `parent_id`?) so we need to think it through.

In addition, I think it would be cool to see (incrementally added) behavior similar to [Automatic GraphQL Filter Generation](https://entgo.io/blog/2021/07/01/automatic-graphql-filter-generation) to allow users to use more of Ent's querying capabilities through the gRPC extension. 

---

In the meantime, the way to add such an endpoint is as you suggested to create a new service with your custom methods and register it on your gRPC server as explained in [this issue](https://github.com/rotemtam/ent-grpc-example/issues/1)

**Comment by rotemtam** [comment]
In case I wasn't clear, this is an invitation to you to keep working together on designing this capability which I'm sure is desirable and useful to many users 😄

**Comment by JeremyV2014** [comment]
Hi @rotemtam ,

Thanks for the feedback!

Understood on the implications of implementing this. My particular use case is for something that is guaranteed to remain relatively small and I figured this would be useful for those in a similar situation. For this reason, I was thinking that making it an option you have to specify would be sufficient to ensure you actually want to expose this to a client. The way I was planning on accomplishing this was by modifying the Service annotation to accept options.
```
entproto.Service(entproto.OptionGenGetAll),
```

As I mentioned in my [discussion post](https://github.com/ent/ent/discussions/2089), I was thinking we could specify a maximum number of ids/entities to return. It seems like the List standard you mentioned matches up with this idea (and its better than calling it GetAll :grinning:). I agree 100% on the features the API would need to provide... though I'm not sure how to go about deciding what the hard limit on page size should be. This seems dependent on the particular use case; A reasonable limit for an IoT client might be artificially limiting for a client with greater bandwidth.

I see that AIP-132 mentions a `parent` is not required for top-level resources. I'm somewhat convinced we could forgo this field for Ent; It doesn't seem like the concept of a hierarchy maps very well to this use case. What do you think?

I also really like the idea of having greater querying capabilities through gRPC; it would make everything a lot more flexible. I'll have to spend some time thinking about what that would look like.

All that said, I think that a List API would be useful to have and relatively safe if we implemented it with page size limits. I understand your concerns with exposing this interface, but I think its safer than developers going off on their own to create a separate service to accomplish it without the rigor that the List specification would enforce. :grin: We could also still make it optional so its not generated by default for a service.

**Comment by rotemtam** [comment]
Another thing to consider, when adding pagination is that `LIMIT/OFFSET` based pagination is notoriously slow. 
Any implementation we suggest should use "KeySet" pagination.
Read: https://use-the-index-luke.com/no-offset

**Comment by JeremyV2014** [comment]
@rotemtam ,

This makes sense to me. My initial thought is to just use the primary key for this purpose. I can see it being more flexible, though, if we allowed the user to specify the fields they wanted to use to order by (take in options for the field annotation maybe?). The only catch is they need to specify a combination of fields that makes the row unique.

**Comment by rotemtam** [comment]
Hey @JeremyV2014,
Try to see what @a8m did with `entgql` and ordering fields: https://entgo.io/docs/graphql/#defining-order-fields-in-entschma

Also, yes, the PK field should be safe to use, afaik the id field gets `Increment` true at least for numeric fields. 
e.g. https://github.com/ent/ent/blob/dd6c034c2a3b0d911f6faf8567e69d1a73542f95/examples/start/ent/migrate/schema.go#L17

This happens here: https://github.com/ent/ent/blob/dd6c034c2a3b0d911f6faf8567e69d1a73542f95/entc/gen/type.go#L1198-L1205

**Comment by JeremyV2014** [comment]
@rotemtam ,

Let's focus on the descending order for primary key for now then. Here's how I imagine this would look:

## Schema Definition
### schema/user.go
```
...

// Annotations of the User.
func (User) Annotations() []schema.Annotation {
  return []schema.Annotation{
    entproto.Message(),
    entproto.Service(entproto.OptionGenList), // Generating the List RPC is optional
  }
}

...
```

## Generated Code
### proto/entpb/entpb.proto
```
// List input message type
message ListUserRequest {
  // page_size has some max value that will be documented in this comment
  int32 page_size = 1;

  // page_token is optional so we can get the first page for DESC order
  // ASC order would be a little easier because this could just be 0 to get the first page
  google.protobuf.Int32Value page_token = 2;
}

// List output message type
message UserList {
  repeated User user_list = 1;
  // should we add a boolean flag to indicate less entries returned than requested (e.g. last page)?
}

service UserService {
  ...
  
  // New RPC
  rpc List ( ListUserRequest ) returns ( UserList )
  
  ...
}

```

### proto/entpb/entpb_user_service.go
```
...

// List implements UserServiceServer.List
func (svc *UserService) List(ctx context.Context, req *ListUserRequest) (*UserList, error) {
  var (
    err error
    userList []*ent.User
    pageSize int
  )

  pageSize = int(req.GetPageSize())
  switch {
  case pageSize < 0: // return error as defined in AIP-132
    return nil, <INVALID_ARGUMENT error>
  case pageSize > MAX_PAGE_SIZE: // coerce page size below hard max
    pageSize = MAX_PAGE_SIZE
    // other option is to return an error if we don't want to coerce it
    // this might be the better option if we are letting the user determine last page based on
    // number of returned entities
  }

  listQuery := svc.client.User.Query().
    Order(ent.Desc(user.FieldID)).
    Limit(pageSize)

  // Use page token if we have one... otherwise... grab first pageSize entries
  if req.GetPageToken() != nil {
    userList, err = listQuery.
      Where(user.IDLT(req.GetPageToken().GetValue())).
      All(ctx)
  } else {
    userList, err = listQuery.All(ctx)
  }

  switch {
  case err == nil:
    return &UserList{
      UserList: userList,
    }, nil
  default:
    return nil, status.Errorf(codes.Internal, "internal error: %s", err)
}

...
```
## gRPC Client Implementation
```
...

// Request WITHOUT page token
userList, err := client.List(ctx, &entpb.ListUserRequest{
  PageSize: 10, // Get 10 user
})

...

// Request WITH page token
userList, err = client.List(ctx, &entpb.ListUserRequest{
  PageSize: 10, // Get 10 user
  PageToken: wrapperspb.Int32(15), // User ID < 15
})

...
```

The modifications to entproto would be very similar to the work I have already done. We would need to create a list method template, modify `service.tmpl` to use the new template, modify `adapter.go` to pass annotation options to `createServiceResources()`, and modify `service.go` to generate new proto messages for the input/output messages of the List RPC. We would also need to determine what `"MAX_PAGE_SIZE"` is (and also what to call it and where this constant will live) and obviously modify/create unit tests to verify everything.

**Comment by rotemtam** [comment]
Hey,
Thanks for the detailed design, great progress!

Here are some comments on it
>   // page_token is optional so we can get the first page for DESC order
  // ASC order would be a little easier because this could just be 0 to get the first page
  google.protobuf.Int32Value page_token = 2;

In [https://google.aip.dev/132](AIP-132) the page token is a string, which makes sense if you think about cases where the same field will be used for storing the page_token for ordered fields that aren't numeric. What I've seen in the past is that this is a string that _represents_ the page, not directly the id (remember you can theoretically have ordering on multiple columns together). 

>    entproto.Service(entproto.OptionGenList), // Generating the List RPC is optional
I don't like treating the `List` method in a special way just because it arrived last. I am in favor of adding a mechanism to control which methods are generated for a specific service. Something like:

```go
entproto.Service(
   entproto.Methods(entproto.MethodGet | entproto.MethodCreate | entproto.MethodList),
)
```
This would be a subject for a separate PR, though. 
I would rather release `List` method support after we add this type of control when configuring gRPC service code-generation. Let me know if you want to work on it with me as well. 

>   pageSize = int(req.GetPageSize())

A neat trick I've seen is that you query for N+1 resources, return only N, and if you have an extra one you know you have an additional page to display and should set the next page token. 

Consider from the AIP:
> The next_page_token field, which supports pagination, must be included on all list response messages. It must be set if there are subsequent pages, and **must not be set** if the response represents the final page. For more information, see AIP-158.

Something else that needs to be addressed is:
> The response should usually include fully-populated resources unless there is a reason to return a partial response (see AIP-157).

See [https://entgo.io/blog/2021/06/28/gprc-ready-for-use/](this announcement) about partial responses in the `Get` method, I think the caller should have the same level of control when asking for a list of resources as they have when they request a single request. If the caller is sensitive to bandwidth usage, this is exacerbated in a collection of entities compared to a single one.

**Comment by JeremyV2014** [comment]
> I don't like treating the List method in a special way just because it arrived last. I am in favor of adding a mechanism to control which methods are generated for a specific service.

I have no problem helping out with adding this feature so that we can add the List feature. Did you want to open another issue to discuss this?

Overall, I like your method of implementing this; it gives a lot of granular control. Would you suggest passing this information through to `genMethodProtos()`? One thing I wasn't sure of how to handle with this was protobuf dependencies. I see that `google/protobuf/empty.proto` is included for the `Delete` method in `adapter.go`:

https://github.com/JeremyV2014/contrib/blob/b95f6eded47690d7999b974e8688b2199e97e9f8/entproto/adapter.go#L157

To have optional fields for the List method messages, we need to include `google/protobuf/wrappers.proto` as well. The issue is, we don't need to import these files if the user doesn't want to generate any List/Delete methods. I think we could modify `serviceResources` struct to return an additional slice of strings for dependencies from `createServiceResources()` so we don't need to re-check the methods the user specified for the service in `adapter.go`.

```go
type serviceResources struct {
	svc         *descriptorpb.ServiceDescriptorProto
	svcMessages []*descriptorpb.DescriptorProto
	svcDependencies []string
}
```
One concern I have is that this might be a breaking change to entproto if we require the user to specify the methods they want generated for a service. Is this okay? Should we generate all services if the user doesn't specify any methods?


---
> In https://google.aip.dev/132 the page token is a string, which makes sense if you think about cases where the same field will be used for storing the page_token for ordered fields that aren't numeric. What I've seen in the past is that this is a string that represents the page, not directly the id (remember you can theoretically have ordering on multiple columns together).

I didn't see the Opacity section of [AIP-158](https://google.aip.dev/158) until now. I'm not sure I fully understand this paragraph:

> For page tokens which do not need to be stored in a database, and which do not contain sensitive data, an API may obfuscate the page token by defining an internal protocol buffer message with any data needed, and send the serialized proto, base-64 encoded.

What is the purpose of defining an internal protocol buffer message? My understanding is that the way you implement this is by defining a new protocol buffer, separate from the public API, with a page token message, serialize the protocol buffer message, base-64 encode it, and send it to the client as the page token. Is it irreversible (or at least difficult to reverse) because the client doesn't have the client stub for this message type?

If it is reversible, what is the advantage to doing that over using something like [gob](https://go.dev/blog/gob) to serialize a struct that contains the fields we need for ordering and then base-64 encode that? It seems a little excessive to define an entirely new protocol buffer just to generate page tokens...

---
> The next_page_token field, which supports pagination, must be included on all list response messages. It must be set if there are subsequent pages, and must not be set if the response represents the final page. For more information, see AIP-158.

I'll use your trick to address this. Thanks!

---
> I think the caller should have the same level of control when asking for a list of resources as they have when they request a single request.

I think we can re-use the same approach as Get with the View enum.

---
Should we add a field to the request message to specify ascending/descending order?

**Comment by JeremyV2014** [comment]
Resolved by https://github.com/ent/contrib/pull/162
