### ISSUE TITLE
Column with SchemaType mediumtext seems "unstable"

### ISSUE THREAD

**Issue by Luit** [ent/ent#2113]
I was trying out ent attempting to get an ent schema that works with my current DB schema, and was working on a table containing a mediumtext column. At first I couldn't get it to work at all because Go took version v0.9.1 which didn't have support for the column type, fixed in #1972 in master.

However, my goal was to get ent to not apply any schema changes, which worked for pretty much every column except the mediumtext ones. For those it seems to always want to `MODIFY COLUMN` for some reason.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

My field is defined as follows:

    field.Text("unstable").SchemaType(map[string]string{dialect.MySQL: "mediumtext",}),

With the first `client.Debug().Schema.Create(context.TODO())` it runs on a clean database:

    query=CREATE TABLE IF NOT EXISTS `somethings`(`id` bigint AUTO_INCREMENT NOT NULL, `stable` longtext NOT NULL, `unstable` mediumtext NOT NULL, PRIMARY KEY(`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin args=[]

The second run on that database, it runs this:

    query=ALTER TABLE `somethings` MODIFY COLUMN `unstable` mediumtext NOT NULL args=[]

## Expected Behavior 🤔

I expect there would be nothing to be done after a first `Schema.Create()`.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | master  |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this @Luit! 

Added a patch for fixing this https://github.com/ent/ent/pull/2115. I'll wait for the CI to be green and merge it.
