### ISSUE TITLE
Conversion error while working with UUID id field

### ISSUE THREAD

**Issue by naormatania** [ent/ent#2116]
Defining UUID while using only the default sql uuid generation fails with a conversion error.

The error happens when you define `id` as follows (postgres 13 or higher is required):
```
"github.com/google/uuid"

// Fields of the School.
func (School) Fields() []ent.Field {
	return []ent.Field{
            field.UUID("id", uuid.UUID{}).
	            Annotations(&entsql.Annotation{
		            Default: "gen_random_uuid()",
	            }),
         },
}
```
And create an entity of this type.

The received error is
```
panic: interface conversion: driver.Value is string, not *uuid.UUID [recovered]
	panic: interface conversion: driver.Value is string, not *uuid.UUID
```

It happens after the create query was executed during assigning back the id value:
```
func (sc *SchoolCreate) sqlSave(ctx context.Context) (*School, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = *_spec.ID.Value.(*uuid.UUID)
	}
	return _node, nil
}
```

Please note that running the following does work (probably because it uses the inserted default uuid and not the ID returned via the `RETURNING` clause.. but I am not sure):
```
field.UUID("id", uuid.UUID{}).
	Default(uuid.New).
	Annotations(&entsql.Annotation{
		Default: "gen_random_uuid()",
	}),
```

- [ X ] The issue is present in the latest release.
- [ X ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17  |
| Ent         | 0.9.1   |
| Database    | Postgres 1.3   |
| Driver      | github.com/jackc/pgx/v4        |

**Comment by a8m** [comment]
Thanks for reporting this @naormatania! Can you please upgrade your ent version to master and update if you still get this error?

**Comment by naormatania** [comment]
Yes I still get this error when I upgrade my ent version to master

**Comment by a8m** [comment]
> Yes I still get this error when I upgrade my ent version to master

Did you use `go get entgo.io/ent@master`?

**Comment by a8m** [comment]
Hey @naormatania, I tested your use case on #2117, and it fixes the issue.
Please upgrade to the latest master and report if you still face any issues with it. Thanks 🙏

**Comment by naormatania** [comment]
I've tested it now as well and the problem is solved. Thanks !
