### ISSUE TITLE
How to reuse privacy policy logic?

### ISSUE THREAD

**Issue by henrywoody** [ent/ent#2118]
Is there a recommended way of reusing privacy policy logic for one model on another model?

For example, say we have a `Post` model that has a O2M edge with a `Comment` model. In this example, I'd like to add a filter rule on the `Comment` that reuses the `Post`'s filter rule, so that if a user can see a particular post, then they can see the comments for that post, but no other comments. Basically the filter rule of the `Post` would extend to the `Comment` so that the user can see a `Comment` if that user can see the comment's `Post`.

The example above is quite simple, but I'm looking for a general approach that would be used in more complex cases where duplication of logic would be difficult to manage.

The example in the documentation ([Multi Tenancy](https://entgo.io/docs/privacy/#multi-tenancy))  shows using the same `FilterTenantRule` for multiple models but that only works because they all have a tenant edge. What I'm looking for is a way to use the filtering rule of a parent to apply to children (or similar relationship).

---

I've come up with an initial approach, in which the `CommentFilter` is wrapped (using the `CommentFilterWrapper` type) and passed to the post's filtering function (`FilterPostFunc`). But it requires writing filter rules in a more spread out way (separating the filtering function from the filter rule), and a lot of set up:

Post policy:

```go
func FilterPostRule() privacy.QueryRule {
	return privacy.FilterFunc(FilterPostFunc)
}

type PostIDFilter interface {
	WhereID(entql.IntP)
}

func FilterPostFunc(ctx context.Context, f privacy.Filter) error {
	pf, ok := f.(PostIDFilter)
	if !ok {
		return privacy.Deny
	}
	pf.WhereID(entql.IntEQ(1)) // simple example
	return nil
}
```

Comment policy:

```go
func FilterCommentRule() privacy.QueryRule {
	return privacy.FilterFunc(func(ctx context.Context, f privacy.Filter) error {
		cf, ok := f.(*gen.CommentFilter)
		if !ok {
			return privacy.Deny
		}

		wf := &CommentFilterWrapper{cf}
		return FilterPostFunc(ctx, wf)
	})
}

type CommentFilterWrapper struct {
	filter *gen.CommentFilter
}

func (f *CommentFilterWrapper) Where(p entql.P) {
	f.filter.Where(entql.HasEdgeWith("post", p))
}

// WhereID applies the entql int predicate on the id field.
func (f *CommentFilterWrapper) WhereID(p entql.IntP) {
	f.Where(p.Field(employee.FieldID))
}
```

---

Specifically, I'm working on history tracking for models. In this style, each model has a corresponding history model that has all the same fields plus a few extra like timestamp etc, and an edge to the original instance. I want the history records for an instance to be visible to the user if the instance itself is visible to that user.

---

Is there a more straightforward way to reuse filtering for privacy policies between models?

**Comment by yonidavidson** [comment]
Hi @henrywoody, usually for reusing schema properties I use Mixing https://entgo.io/docs/schema-mixin, 
This can allow you do define a mixin-type and apply on where I need the shared logic.
And example is seen here https://entgo.io/docs/privacy/
```go
// Policy for all schemas that embed TenantMixin.
func (TenantMixin) Policy() ent.Policy {
    return privacy.Policy{
        Query: privacy.QueryPolicy{
            rule.AllowIfAdmin(),
            // Filter out entities that are not connected to the tenant.
            // If the viewer is admin, this policy rule is skipped above.
            rule.FilterTenantRule(),
        },
    }
}```

**Comment by henrywoody** [comment]
@yonidavidson thanks for the response. I think that a mixin could be the right approach but will require a bit of tweaking because the two models in my example don't have the same fields/edges, but I want it so that a user can see a comment if the user can see the post that the comment is attached to.

A word that comes to mind is transitive. As in being able to see the post implies you can see any comment on the post.

For example, say the post's filter rule can be expressed as a single predicate, `postFilterRulePredicate`, then the comment's filter rule should be along the lines of `HasPostWith(postFilterRulePredicate)`.

**Comment by yonidavidson** [comment]
@henrywoody  if you need t reuse logic but with different fields, you can use a "factory function" to create those filters with the correct fields/edges names.

**Comment by henrywoody** [comment]
@yonidavidson That could work, haven't looked at this in some time so I will experiment a bit and report back, thanks.

**Comment by yonidavidson** [comment]
Hi @henrywoody can I close this issue?

**Comment by henrywoody** [comment]
@yonidavidson, yes.

For anyone wondering, current solution looks like this the below. I'll likely need to optimize this in the future, as it will probably break down with a lot of data.

```
func filterCommentRule() privacy.QueryRule {
	return privacy.CommentQueryRuleFunc(func(ctx context.Context, q *gen.CommentQuery) error {
		ids, err := q.NewPostQuery().IDs(ctx)
		if err != nil {
			return err
		}
		q.Where(comment.PostIDIn(ids...))
		return nil
	})
}
```

Also requires a small snippet in the `ent` package to define the `NewPostQuery` method on the `CommentQuery`:

```
func (q *CommentQuery) NewPostQuery() *PostQuery {
	return &PostQuery{config: q.config}
}
```
