### ISSUE TITLE
I have three tables: user, role, and user_role. The user_role table is the relationship between user and role. How should I configure Edges?

### ISSUE THREAD

**Issue by AllCute** [ent/ent#2120]
I have three tables: `user`, `role`, and `user_role`. The `user_role` table is the relationship between `user` and `role`. How should I configure Edges?
A user can have multiple roles, and a role can also have multiple users, so there is an association table.
---
我有三张表，分别是`user`、`role`、`user_role`，因为一个user能有多个role，所以有一张保存关联关系的`user_role`表，请问这种情况我应该怎么配置`Edges`呢？

### user
```
id、name、password...
```

### role
```
id、name、role_code...
```

### user_role
```
user_id、role_id
```

**Comment by lenuse** [comment]
User -1-> userRoles -m-> UserRole，Role -1-> userRoles -m-> UserRole
client.Debug().User.Query().Where(user.IDEQ(11)).QueryUserRoles().QueryRoles().AllX(ctx)

**Comment by yonidavidson** [comment]
Hi, this is a classic M2M relation. you can read all about it at https://entgo.io/docs/schema-edges#m2m-two-types

**Comment by li-xunhuan** [comment]
> Hi, this is a classic M2M relation. you can read all about it at https://entgo.io/docs/schema-edges#m2m-two-types

thx，I didn’t read it too well before, I seem to understand now, I’ll try.
