### ISSUE TITLE
Is there a way to get raw sql string from query builder for debuging purpose 

### ISSUE THREAD

**Issue by bandirsen** [ent/ent#2133]
For debugging purpose sometimes after bulding a query, I want check the raw sql
e.g :
```
u, err := client.User.
        Query().WithRoles().
        Where(user.Name("joe")).        
        Only(ctx)     
```
Is there away to get raw sql string from above query building ?

**Comment by yonidavidson** [comment]
Hi @bandirsen ,
ent has a built in Debugger just for hits:
u, err := client.User.Debug().
        Query().WithRoles().
        Where(user.Name("joe")).        
        Only(ctx)

have a look here https://entgo.io/docs/migrate/#offline-mode

**Comment by a8m** [comment]
Thanks for helping @yonidavidson. 

@bandirsen, let me know if we can close the issue. Thanks

**Comment by bandirsen** [comment]
@yonidavidson 
Thanks for your guide

@a8m
Sure, I'm closing this
