### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by zhqinux** [ent/ent#2136]
database version: mysql5.7
database code

`GRANT ALL PRIVILEGES ON dbName.* to 'username'@'%'

FLUSH PRIVILEGES;`

My go code 

      `properties := config.GetConfig()
	      dsn := fmt.Sprintf("%v:%v@tcp(%v)/%v?parseTime=true&loc=Local",
		      properties.Database.User,
		      properties.Database.Password,
		      properties.Database.Host,
		      properties.Database.DBName,
	      )

	client, err := ent.Open("mysql", dsn)
	if err != nil {
		log.Fatalf("failed connecting to mysql: %v", err.Error())
	}
	defer client.Close()

	ctx := context.Background()
	err = client.Debug().Schema.Create(
		ctx,
	)
	if err != nil {
		log.Fatalf("failed creating schema resources: %v", err.Error())
	}`

run `go run main.go` always get `Error 1045: Access denied for user ......`

So, what exactly does ent need permission to when schema.Create

**Comment by a8m** [comment]
Hey @zhqinux 👋 

> So, what exactly does ent need permission to when schema.Create

Permission for reading tables under the INFORMATION_SCHEMA, and creating resources on the schema it's connected to.

**Comment by a8m** [comment]
Closing, but feel free to reopen if you still have troubles or you need help.
