### ISSUE TITLE
Bump ent/contrib version

### ISSUE THREAD

**Issue by edigaryev** [ent/ent#2149]
Problem: currently the website documentation is misleading, because the changes made to it in #2009 reflect not-yet-released changes in the ent/contrib: https://github.com/ent/contrib/commit/c4b201d6d120fdee9f0de49759e213d81f530e85.

Solution: release ent/contrib version 0.2.0.

**Comment by a8m** [comment]
Hey @edigaryev 👋 

Thanks for raising up this issue. We're going to release a new version (with a proper release note) after https://github.com/ent/contrib/pull/162 is merged. If you're blocked, please use `go get entgo.io/contrib@master` to get the latest changes. 

cc @rotemtam, @JeremyV2014

**Comment by rotemtam** [comment]
Hey @edigaryev 

Just released `v0.2.0`, thanks for the suggestion 🚀
