### ISSUE TITLE
Always run migration on `datetime` column when using TiDB

### ISSUE THREAD

**Issue by Thearas** [ent/ent#2163]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Ent always run migration on `datetime` column when using TiDB, even if the schema in the database is already up to date.

## Expected Behavior 🤔

No migration.

## Steps to Reproduce 🕹

Steps:

1. Create a schema with fields `created_at datetime(6)`:
```go
// ent/schema/user.go
type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.Time("created_at").
		Immutable().
		Default(time.Now).
		SchemaType(map[string]string{
				dialect.MySQL: "datetime(6)",
		}),
	}
}
```
2. Generate DB migration in offline mode, and then apply the SQLs to TiDB:
```sql
BEGIN;
CREATE TABLE IF NOT EXISTS `users`(`id` bigint AUTO_INCREMENT NOT NULL, `created_at` datetime(6) NOT NULL, PRIMARY KEY(`id`)) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
COMMIT;
```
3. Repeat step 2. But every time I execute step 2, I got the same SQLs:
```sql
BEGIN;
ALTER TABLE `users` MODIFY COLUMN `created_at` datetime(6) NOT NULL;
COMMIT;
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.9.2   |
| Database    | TiDB v5.1.2   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by Thearas** [comment]
I may have found out why. The behavior of TiDB is different from MySQL.

1. When ent read column from my schema, because I specified `SchemaType` on field, so the `c.Nullable` is true <https://github.com/ent/ent/blob/v0.9.1/dialect/sql/schema/mysql.go#L207>
2. But when ent read column from DB, the `c.Nullable` will be false <https://github.com/ent/ent/blob/v0.9.1/dialect/sql/schema/mysql.go#L266>

I temporarily fixed it by skipping `2` on TiDB.
The fix <https://github.com/Thearas/ent/commit/ab0be5f573a7f2e36377858e382f0bb71f7076e0>.

**Comment by godcong** [comment]
Have you tried it under mysql?
If there is no such exception, it is possible that there is a compatibility issue with tidb.
(I am using the same environment as you: ent+tidb, :)

**Comment by Thearas** [comment]
> Have you tried it under mysql?

It works fine on MySQL 8.0.27.

**Comment by hedwigz** [comment]
Hey @Thearas :smile: 
With the new migration engine, `Atlas` this is now resolved.  
Upgrade to `entgo.io/ent@master` and use `schema.WithAtlas(true)`
```go
client.Schema.Create(context.Background(), schema.WithAtlas(true))
```

**Comment by Thearas** [comment]
Great! It works for me! @hedwigz

However, I found that `Atlas` does not support `WithForeignKeys(false)`:
```
ent/migrate: sql/schema: WithForeignKeys(false) does not work in Atlas migration
```
Any plans to support `WithForeignKeys(false)`?

**Comment by zeevmoney** [comment]
Hi @Thearas 👋🏻 

Soon this will be solved via https://github.com/ent/ent/pull/2404

**Comment by zeevmoney** [comment]
@Thearas updating you that the PR was merged :)
https://github.com/ent/ent/pull/2404
