### ISSUE TITLE
Nillable Optional Unique String Field with MinLen

### ISSUE THREAD

**Issue by idc77** [ent/ent#2182]
Ok in my usage of ent I came across this scenario

```go
field.String("text").Optional().Nillable().Unique(),
```
that I extend with
```go
field.String("text").Optional().Nillable().Unique().MinLen(14),
```

So I'd assume validation occurs if the field != nil, 
however validation occurs regardless and I have to do manual validation in the 
handler, which is no big deal but I'm not sure if this is the way it's intended.

I can't say if it's a bug or if that's the way you intend it to work, therefore I didn't use the bug template for issues here.

What should be happening:

MinLen validation does not occur if
```go
value := nil
// ...
.SetNillableText(value)
```
What is happening:

MinLen validation occurs if it's nil

**Comment by alexsn** [comment]
Assuming the above is true then it's a bug as nil values should be ignored by SetNillable<> setters.

**Comment by alexsn** [comment]
SetNillable<Field> setters are nops for nil values, see code [here](https://github.com/ent/ent/blob/6372263b990c51eb21576f79a96faa362654f0e2/entc/gen/template/builder/setter.tmpl#L39) and [here](https://github.com/ent/ent/blob/6372263b990c51eb21576f79a96faa362654f0e2/entc/gen/template/builder/setter.tmpl#L80).
Can you provide a repo reproducing this issue?

**Comment by idc77** [comment]
I can try to create a repo with minimal content for this issue alone, but it will take some time, maybe this week.
I'll get back to you.

**Comment by idc77** [comment]
False alarm.
That is really weird.
