### ISSUE TITLE
Unable to connect to a remote cloud hosted PostgreSQL database instance

### ISSUE THREAD

**Issue by ageeknamedslickback** [ent/ent#2194]
Creating my schema during migration to a Cloud SQL hosted Postgres database returns an issue `opening ent clientdial tcp: lookup peoject-id:region:instance: no such host`

- [ x ] The issue is present in the latest release.
- [ x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Currently i'm facing an issue  `opening ent clientdial tcp: lookup peoject-id:region:instance: no such host`

## Expected Behavior 🤔

Expected behavior is to connect to my remote database and run migrations successfully

## Steps to Reproduce 🕹

Steps:

1. Create a Cloud SQL instance and database
2. Connect the database using the `instance name` and run the client code to connect to the database

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.3  |
| Ent         | 0.9.2-0.20210821141344-368a8f7a2e9a   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/lib/pq        |

**Comment by rotemtam** [comment]
Hi @ageeknamedslickback ,
Thanks for reaching out. The error message suggests that you used the wrong connection string to your database. 

[This section](https://entgo.io/docs/crud/#create-a-new-client) in the documentation shows how to connect to a Postgres database. 

This line configures the connection string to the database:
```go
    client, err := ent.Open("postgres","host=<host> port=<port> user=<user> dbname=<database> password=<pass>")
```

To connect, replace host, port and the credentials with the values supplied by your cloud provider.

Hope this helps, and lmk if you need further assistance.

**Comment by a8m** [comment]
Looks like it's not an issue in ent.

Closing, but please feel free to continue the discussion if you need help or join our [Slack](https://entgo.io/docs/slack)/[Discord](https://discord.gg/qZmPgTE6RX) communities.

**Comment by dspacejs** [comment]
@rotemtam is it possible to connect to PostgreSQL with a map of options instead of a string?

**Comment by mztnnrt** [comment]
In fact, is it able to connect postgresql on cloud sql  with [Create A New Client](https://entgo.io/docs/crud/#create-a-new-client)
If we need additional option as like [gorm](https://entgo.io/docs/crud/#create-a-new-client) , i want someone to tell me

**Comment by a8m** [comment]
> @rotemtam is it possible to connect to PostgreSQL with a map of options instead of a string?

Yes. What database driver do you use? pg/pgx?

> In fact, is it able to connect postgresql on cloud sql with only [Create A New Client](https://entgo.io/docs/crud/#create-a-new-client) ? If we need additional option as like [gorm](https://gorm.io/docs/connecting_to_the_database.html#Customize-Driver-1) , i want someone to tell me

You can create an `*sql.DB` and then create an Ent driver (and client) from it. It's quite similar to the pgx example on the entgo.io website. See https://entgo.io/docs/sql-integration#use-pgx-with-postgresql and https://github.com/GoogleCloudPlatform/cloud-sql-go-connector#postgres-1.

**Comment by mztnnrt** [comment]
Thanks for your reply. i use driver `pg`

> You can create an *sql.DB and then create an Ent driver (and client) from it. It's quite similar to the pgx example on the entgo.io website. See https://entgo.io/docs/sql-integration#use-pgx-with-postgresql and https://github.com/GoogleCloudPlatform/cloud-sql-go-connector#postgres-1.

Though my understanding about driver, client was lacking,  I just solved based on your reply as like below.

<details>
<summary>just for reference 🙏</summary>

```go
dsn = "host=<project-id>:<region>:<instance-id> user=<user> dbname=<db> password=<pass> sslmode=disable"
dbConn, err := sql.Open("cloudsqlpostgres", dsn)
if err != nil {
	panic(err)
}

driver := entsql.OpenDB(dialect.Postgres, dbConn)
defer driver.Close()

opt := []ent.Option{ent.Driver(driver)}
client := ent.NewClient(opt...)
```

</details>

Thank you very much, this was a really big help

**Comment by a8m** [comment]
Great! Feel free to add it to our docs 🙏🏻
