### ISSUE TITLE
Default for field type Other 

### ISSUE THREAD

**Issue by shenghui0779** [ent/ent#2195]
### fields define

```go
func (Shop) Fields() []ent.Field {
    return []ent.Field{
        field.Other("longitude", decimal.Decimal{}).SchemaType(map[string]string{
	    dialect.MySQL: "decimal(12,8)",
        }).Default(decimal.NewFromInt(0)).Comment("经度"),
        field.Other("latitude", decimal.Decimal{}).SchemaType(map[string]string{
	    dialect.MySQL: "decimal(12,8)",
        }).Default(decimal.NewFromInt(0)).Comment("纬度"),
    }
}
```

### error

- runtime.go

```go
shop.DefaultLongitude = decimal.Decimal(shopDescLongitude.Default.(other))
shop.DefaultLatitude = decimal.Decimal(shopDescLatitude.Default.(other))
```

### expect

- runtime.go

```go
shop.DefaultLongitude = shopDescLongitude.Default.(decimal.Decimal)
shop.DefaultLatitude = shopDescLatitude.Default.(decimal.Decimal)
```

**Comment by a8m** [comment]
Hey @shenghui0779, and thanks for reporting this bug.

What version do you use? Can you please update to the latest master and report if you still get this failure? Thanks

```
go get entgo.io/ent@master
```

**Comment by shenghui0779** [comment]
v0.9.1

**Comment by shenghui0779** [comment]
@a8m the latest master is OK.

**Comment by shenghui0779** [comment]
@a8m When I use migration, the default value is not set.

```sh
Tx(77e76fcc-19db-45d2-ba99-85a8bd905010).Exec: query=ALTER TABLE `shop` ADD COLUMN `longitude` decimal(12,8) NOT NULL, ADD COLUMN `latitude` decimal(12,8) NOT NULL args=[]
```

**Comment by a8m** [comment]
> @a8m When I use migration, the default value is not set.

Yes, this issue is known, and it's going to be fixed soon with the new migration.  See https://github.com/ent/ent/issues/1758

> @a8m the latest master is OK.

Great, going to close this as the codegen problem was resolved in master. Thanks for reporting this @shenghui0779 🙏
