### ISSUE TITLE
proposal: store Columns as map for faster ValidColumn performance

### ISSUE THREAD

**Issue by HurSungYun** [ent/ent#2196]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

AS-IS
```go

// Columns holds all SQL columns for condition fields.
var Columns = []string{
	FieldID,
	FieldConditionGroupID,
	FieldProperty,
	FieldType,
	FieldOperator,
	FieldValue,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "conditions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"condition_group_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
```

TO-BE
```go

// Columns holds all SQL columns for condition fields.
var Columns = []string{
	FieldID,
	FieldConditionGroupID,
	FieldProperty,
	FieldType,
	FieldOperator,
	FieldValue,
}

var columnsMap = map[string]bool{
	FieldID: true,
	FieldConditionGroupID: true,
	FieldProperty: true,
	FieldType: true,
	FieldOperator: true,
	FieldValue: true,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "conditions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"condition_group_id",
}

var foreignKeysMap = map[string]bool{
	"condition_group_id": true,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	_, ok := columnsMap[column]
	if ok {
		return true
	}
	_, ok = foreignKeysMap[column]
	if ok {
		return true
	}
	return false
}

```

## Motivation 🔦

Currently, `Columns` is stored as slices and `ValidColumn` uses these slices to decide whether column is valid or not.

I'm not sure but I believe `ValidColumn` is a **hot function** and it takes O(n) time complexity now because it searches `Columns` slice linearly.

there might be a performance improvement when time complexity of `ValidColumn` becomes O(1).

Unfortunately, `Columns` is exported variable, so new redundant `columnsMap` should be needed for backward-compatibility.

**Comment by a8m** [comment]
Hey @HurSungYun and thanks for starting this discussion.

> I'm not sure but I believe ValidColumn is a hot function and it takes O(n) time complexity now because it searches Columns slice linearly.

It depends on what are you considering to be `N`. `ValidColumn` does not depend on the input size, so in the worst case, it has `K` iterations, where `K` is the number of columns in the table. Hence, the time complexity is constant (O(K) => O(1)), as it does not increase linearly with the size of the input.

Now, I think you've raised a good point, whether or not we should use a map over a slice of columns. I asked myself the same question some time ago, did a small analysis (using go bench), and found that for small sizes, using a slice is more efficient than a lookup-table for tables with `len(columns) <= 20`, assuming the columns/keys are selected with a uniform distribution (i.e. the probability of a column to be selected is 1/n). 

Please, if you want to come up with another analysis and help to improve the performance of this framework, this will be more than welcome. Thanks. 🙏 ❤️

**Comment by masseelch** [comment]
I did the same some time ago. One thing I noticed, is that the case @a8m describes is only valid for integer maps. If you bench with string maps / slices in my test map lookup became faster for `len() > 5`. This is because the go map (hardware-)hashes the keys, the string slice does not.

Taking my bench there is a motivation to change the lookup logic, since most tables will have > 5 columns. My 2 cents!

**Comment by a8m** [comment]
Thanks for sharing this with me @masseelch.

> https://gist.github.com/grahamking/dbc90cb3f45c8fea2ba6 <- bench I used

Not sure the benchmark represents the same case because it chooses 1 key to search in each test, and in my use case I assumed a uniform distribution. 

I just created a modified version of it (without *Item and randomness), used a few examples from the integration-test packages, and got better results for n=15, but the difference was super tiny.

**Comment by a8m** [comment]
Anyway, I'll be more than happy to get perf improvements to the framework, but I don't have the time to do these analyses atm, and prefer to get it with proper benchmark tests. The current 2 slices (`<pkg>Columns`, `<pkg>.ForeignKeys`) are needed in other areas when executing queries, so that means, new variables should be added to the generated code in addition to them. So, if anyone is willing to take this, they get my approval, but I need to make sure it does not cost too much memory, or the CPU reduction is worth it.

Closing as resolved, but @HurSungYun, you're welcome to ping me on Slack if you need guidance in contributing this.

**Comment by a8m** [comment]
Just came up with another idea for improvement. Sort the strings on codegen time, and use `sort.Search` (binary search).

**Comment by HurSungYun** [comment]
@a8m @masseelch Thank you for your kind answers.

I also modified @masseelch's benchmark code. In my case, I got better result for `n=12` or more.

https://gist.github.com/HurSungYun/ea3661011187d8cc948b40f8acf38abb

```
// n = 12
lambert@lambertui-MacBookPro slice_map % go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: example.com/m
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkBaselineKV-12          69405489                16.86 ns/op            0 B/op          0 allocs/op
BenchmarkStringSlice-12         30736887                39.04 ns/op            0 B/op          0 allocs/op
BenchmarkStringMap-12           32091962                37.09 ns/op            0 B/op          0 allocs/op
```

As you said, difference is tiny even if `n=20`.

```
// n = 20
go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: example.com/m
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkBaselineKV-12          70673880                16.79 ns/op            0 B/op          0 allocs/op
BenchmarkStringSlice-12         23222610                51.41 ns/op            0 B/op          0 allocs/op
BenchmarkStringMap-12           30921198                38.34 ns/op            0 B/op          0 allocs/op
```

build [Trie](https://en.wikipedia.org/wiki/Trie) based on columns may be the optimal solution for this use case, but I am not sure it would be a immature optimization.

**Comment by a8m** [comment]
Thanks for taking the time to write these tests @HurSungYun. It's really appreciated. I'm too busy with migration code atm.



What do you think about this?
> Just came up with another idea for improvement. Sort the strings on codegen time, and use `sort.Search` (binary search).

**Comment by HurSungYun** [comment]
> What do you think about this?
> >Just came up with another idea for improvement. Sort the strings on codegen time, and use sort.Search (binary search).

@a8m I think it's a good idea and I'll make another benchmark code for analysis.

btw, using Slack for discussing this issue is better for you? If so, i'll join ent Slack workspace :)

**Comment by masseelch** [comment]
Correct me if I am wrong, but considering we have `k` columns the worst case is `log k` iterations. The current way is `k`. Do we need a bench? The mathematical proof is pretty trivial, isnt it?

**Comment by HurSungYun** [comment]
https://gist.github.com/HurSungYun/c45603e681af5a074f5c6fee2968a9f5

`sort.Search` was worse in small numbers

`n=10` cases

```
// n = 10
lambert@lambertui-MacBookPro slice_map % go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: example.com/m
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkBaselineKV-12                  70136781                17.14 ns/op            0 B/op          0 allocs/op
BenchmarkLinearSearch-12                32402937                35.57 ns/op            0 B/op          0 allocs/op
BenchmarkLinearSearchSorted-12          32749596                35.81 ns/op            0 B/op          0 allocs/op
BenchmarkBinarySearch-12                23743033                48.49 ns/op            0 B/op          0 allocs/op
```

binary search is efficient when `n > 35`

```
// n = 35
lambert@lambertui-MacBookPro slice_map % go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: example.com/m
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkBaselineKV-12                  70128768                17.08 ns/op            0 B/op          0 allocs/op
BenchmarkLinearSearch-12                17439871                68.50 ns/op            0 B/op          0 allocs/op
BenchmarkLinearSearchSorted-12          17501342                68.86 ns/op            0 B/op          0 allocs/op
BenchmarkBinarySearch-12                17988530                67.19 ns/op            0 B/op          0 allocs/op
```

Of course, when `n > 100`, binary search has much better performance.

```
lambert@lambertui-MacBookPro slice_map % go test -bench=. -benchmem
goos: darwin
goarch: amd64
pkg: example.com/m
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkBaselineKV-12                  73333927                16.21 ns/op            0 B/op          0 allocs/op
BenchmarkLinearSearch-12                 7494325               157.6 ns/op             0 B/op          0 allocs/op
BenchmarkLinearSearchSorted-12           7050800               171.2 ns/op             0 B/op          0 allocs/op
BenchmarkBinarySearch-12                14665408                81.89 ns/op            0 B/op          0 allocs/op
```

By its implementation, I guess function call overheads affects a lot for small `N`s 😢

**Comment by a8m** [comment]
> btw, using Slack for discussing this issue is better for you? If so, i'll join ent Slack workspace :)

Yes, you're welcome. Thanks again for working on it, and sorry for the delayed response.
