### ISSUE TITLE
How to sort multiple field with entgql

### ISSUE THREAD

**Issue by touyu** [ent/ent#2198]
The following users table exists.
```golang
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Bool("is_verified").
			Default(false).
			Annotations(
				entgql.OrderField("IS_VERIFIED"),
			),
                 field.Time("created_at").
			Immutable().
			Default(time.Now).
			Annotations(
				entgql.OrderField("CREATED_AT"),
			),
		field.Time("updated_at").
			Default(time.Now).
			UpdateDefault(time.Now),
	}
}
```

I want to get the value by specifying descending order for both `created_at` and `is_verified`.
I recognize that the method to specify order with entgql is the following code.

```golang
client.User.Query().
	Paginate(ctx, after, first, nil, nil,
		ent.WithCuratorOrder(orderBy),
	)
```

However, with this, only one field can be specified.
Is there a way to specify multiple fields?

**Comment by alexsn** [comment]
No but implementing it shouldn't be too difficult. Feel free to give it a shot and tag me for a review.

**Comment by touyu** [comment]
@alexsn 
Thank you for your reply.
Am I correct in understanding that there is currently no way to solve this problem?

**Comment by alexsn** [comment]
Yes, it's currently not supported.

**Comment by sahmadreza** [comment]
There is no solution for multiple order?

**Comment by sarmad4444** [comment]
+1 for this. This is a must have feature for dynamic data fetching.

**Comment by a8m** [comment]
Issue resolved with https://entgo.io/docs/tutorial-todo-gql-paginate#order-by-multiple-fields.
