### ISSUE TITLE
How to create a table based on date?

### ISSUE THREAD

**Issue by sishui** [ent/ent#2204]
For example, create a table with the name test_2006_01_02 every day,  What should I do to achieve this function? THX!

**Comment by Yiling-J** [comment]
Hi @sishui, even if you find a way to do that, you still need some way to do CRUDs on that table. See https://github.com/ent/ent/pull/2020. So why you need to create  dynamic table? What's your use case for that?

**Comment by sishui** [comment]
Hi, @Yiling-J , My team has a requirement to store some logs (which are discarded after a period of time), one table per week, the table schema is the same, the table names are different, I think we need dynamic table names for better implementation

**Comment by Yiling-J** [comment]
@sishui It seems a little weird to save logs in relational database. Is it OK to store logs in elasticsearch or presto, which support datetime partition?

**Comment by Yiling-J** [comment]
@sishui I have an idea, first you keep the `test` table. BUT, every day at 24:00, run a script to create a new table `test_2021_12_08` and migrate your last day data to to that table. Not using ent, just some raw sql scripts. So you still writing data to the only `ent` table, no dynamic names.

**Comment by sishui** [comment]
@Yiling-J I have used ent's hook to dynamic create  table, but I don't know how to write records in the new table

**Comment by Yiling-J** [comment]
@sishui I mean don't write records to your dynamic table, just write to the `test` table and clean that table every day. Don't overcomplicated thing, is it feasible to create your new table after the day and run a migrate script?

**Comment by sishui** [comment]
@Yiling-J If that's not possible at the moment, I'll have to use the method you provided or find another way

**Comment by Yiling-J** [comment]
@sishui one last suggestion, you can also try 阿里云's PolarDB, according to their doc, billions data in one table works pretty good. Also I think they support one-click upgrade from your RDS to PolarDB.

**Comment by sishui** [comment]
Okay, my team will discuss what option to use instead, thank you
