### ISSUE TITLE
modernc.org/sqlite driver fails to migrate after the first migration

### ISSUE THREAD

**Issue by plunkettscott** [ent/ent#2209]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using the the [modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite) driver, the first SQLite `Schema.Create()` execution works properly and migrates the database. However, the second (and subsequent) times it fails on INTEGER columns, providing the following error message (with no changes to the schema between executions):

```
creating changeset for "discord_roles": invalid type "INTEGER" for column "color"
```

## Expected Behavior 🤔

Subsequent runs of `Schema.Create()` on startup should not produce an error, like the [github.com/mattn/go-sqlite3](https://pkg.go.dev/github.com/mattn/go-sqlite3) driver.

## Steps to Reproduce 🕹

https://github.com/plunkettscott/ent-sqlite-migration-bug

Steps:

1. Run `go test ./...`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.3  |
| Ent         | 0.9.1   |
| Database    | SQLite   |
| Driver      | [modernc.org/sqlite](https://pkg.go.dev/modernc.org/sqlite)       |

**Comment by plunkettscott** [comment]
Just an update to this, I dropped it down to `modernc.org/sqlite` @v1.14.1 (which uses SQLite 3.36.0) and this works correctly. It looks like a potential problem with SQLite v3.37.0 in Ent.

**Comment by a8m** [comment]
Thanks for reporting this @plunkettscott, I was able to reproduce this and found the issue.

It looks like SQLite changed the `table_info` output.

v3.36.0:

![image](https://user-images.githubusercontent.com/7413593/145677154-b38ed9bf-6e49-40a2-a06d-75176883c1a0.png)

v3.37.0:

![image](https://user-images.githubusercontent.com/7413593/145677166-07fba6a0-fe53-40f7-b04a-dc3cc8c3cf51.png)

We can easily support this if we [lowercase the type](https://github.com/ent/ent/blob/master/dialect/sql/schema/sqlite.go#L292) before we test it. Would you like to contribute a fix? Thanks 🙏

**Comment by m3hm3t** [comment]
I could not test with [repo](https://github.com/plunkettscott/ent-sqlite-migration-bug).

If you share me how, I can do that.

**Comment by a8m** [comment]
Hey @plunkettscott, please update to the latest master and reopen if you still have issues. Thanks 🙏

**Comment by plunkettscott** [comment]
Thanks for the fix, @m3hm3t and @a8m. I'll test this, but it looks like it should solve the problem.

**Comment by shahriar350** [comment]
to solve this issue, upgrade ent version to 0.10.0
