### ISSUE TITLE
proposal: supports custom index names

### ISSUE THREAD

**Issue by HurSungYun** [ent/ent#2215]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

it would be great to support custom index names using sql annotations like below.

```
// Indexes of the Car.
func (Car) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("owner_id").
			Annotations(
				entsql.IndexName("idx_owner_id"), // new API: entsql.IndexName or something else
			),
	}
}
```

index with custom names will be created when creating schema.

```
if err := client.Schema.Create(ctx); err != nil {
    log.Fatalf("failed creating schema resources: %v", err)
}
```

I guess this feature can be easily implemented, so I can take it if accepted.

## Motivation 🔦

In my company, we have strict naming conventions for indexes. However, ent does not support custom index names currently.

Because ent is schema-first ORM, I want to treat ent schema as the source or truth but lack of this feature make me to do another work to sync real database schema.

**Comment by Thearas** [comment]
I think `StorageKey()` meets your requirements.
e.g.
```go
func (Car) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("name").Unique().StorageKey("uniq_name"),
	}
}

```

**Comment by a8m** [comment]
Hey @HurSungYun 👋 

Thanks, @Thearas for the help! It's appreciated 🙏 
@HurSungYun, please let me know if it does solve your issue and we can close it.

**Comment by HurSungYun** [comment]
@Thearas @a8m Thank you all 👍 `StorageKey` worked well.

Btw, the fact that `StorageKey` can be used has not documented in [Index section](https://entgo.io/docs/schema-indexes), so it would be great to mention it.

May I add some documents there?

**Comment by a8m** [comment]
> Btw, the fact that `StorageKey` can be used has not documented in [Index section](https://entgo.io/docs/schema-indexes), so it would be great to mention it.
> 
> May I add some documents there?

Yes, please. Thank you 🙏🏻
