### ISSUE TITLE
Aggregate without GROUP BY

### ISSUE THREAD

**Issue by necryin** [ent/ent#2216]
Hi. 
I have a simple query in Postgres:
```
SELECT SUM(amount) AS sum FROM test
```

But I can't create query because Aggregate function is method of GroupByQuery and I have no GROUP BY here :(

Tried hack it like `GroupBy("FALSE")` but got  `invalid field "FALSE" for group-by`

**Comment by a8m** [comment]
Hey @necryin 👋 

Using a [custom modifier](https://entgo.io/docs/feature-flags#custom-sql-modifiers) should do the job here. Please, let me know if you still need help here.

**Comment by necryin** [comment]
@a8m thx a lot! 
It looks little bit clunky but it works

**Comment by a8m** [comment]
Hey! I just want to update you that the aggregation API was simplified, and you can read about it here https://twitter.com/entgo_io/status/1584091539479080960 and https://entgo.io/docs/aggregate.

Also, here's a small example:

```go
// Aggregate one field.
sum, err := client.Order.Query().
    Aggregate(
        ent.Sum(order.FieldPrice),
    ).
    Int(ctx)

// Aggregate multiple fields.
var v []struct {
    Sum, Min, Max, Count int
}
err := a8m.QueryOrders().
    Aggregate(
        ent.Sum(order.FieldPrice),
        ent.Min(order.FieldPrice),
        ent.Max(order.FieldPrice),
        ent.Count(),
    ).
    Scan(ctx, &v)
```
