### ISSUE TITLE
comments not working

### ISSUE THREAD

**Issue by guihouchang** [ent/ent#2217]
- [ √] The issue is present in the latest release.
- [ √] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
comment("this is a comments") not working

## Steps to Reproduce 🕹

Steps:

```
package schema

import (
	"party-assemble/app/user/service/internal/data/ent/schema/mixin"

	"entgo.io/ent/schema/index"

	"entgo.io/ent/schema/field"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("username").
			Unique().
			NotEmpty().
			Comment("this is a username").
			MinLen(6).
			MaxLen(128),
		field.String("password").Comment("this is a password").NotEmpty().MinLen(6).MaxLen(125),
		field.String("name").Comment("this is a nickname").Optional().MinLen(0).MaxLen(10),
	}
}

// Indexes 定义索引
func (User) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("name"),
	}
}

// Edges 定义模型关系
func (User) Edges() []ent.Edge {
	return nil
}

// Mixin 继承时间字段
func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixin.TimeMixin{},
	}
}

// Annotations 定义表名
func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "pa_user"},
	}
}

```
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.9.1   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @guihouchang 👋 

What do you mean by not working? You don't see it in the database? If so, it's a duplicate of https://github.com/ent/ent/issues/1546

**Comment by guihouchang** [comment]
@a8m thx

**Comment by a8m** [comment]
The issue was resolved with: https://entgo.io/docs/schema-annotations#database-comments.

Update your Ent version to master, and check out this tweet to see an example: https://twitter.com/entgo_io/status/1607394587009589248?s=46&t=lnMIxsxQpGOTMCpsp0yPBg
