### ISSUE TITLE
How to execute raw SQL with Tx ?

### ISSUE THREAD

**Issue by shenghui0779** [ent/ent#2221]
How to execute raw SQL with `*ent.Tx`, such as `TRUNCATE`

**Comment by a8m** [comment]
Hey @shenghui0779 👋 

There are a few ways how to get the `dialect.Driver` (or `dialect.Tx`) from `ent.Client` (or `ent.Tx`) and it's mentioned in https://github.com/ent/ent/issues/85. When working with a database driver (underlying connection), you can execute any statements, including `TRUNCATE`. Same as you can do with `sql.DB`.

If you work with `ent.Tx` or [transactional client](https://entgo.io/docs/transactions/#transactional-client), the connection is bound to a transaction, and all queries, including raw statements, are executed on the transaction connection.  

Please, let me know if it does answer your question and we can close the issue. Thanks 🙏 

P.S. great work on https://github.com/shenghui0779/goadmin

**Comment by shenghui0779** [comment]
Thanks a lot !

**Comment by a8m** [comment]
Hey @shenghui0779! I added a feature flag named [sql/execquery](https://entgo.io/docs/feature-flags#sql-raw-api) to simplify the process for those who need it.
