### ISSUE TITLE
ID's `StorageKey` not woking with edge.

### ISSUE THREAD

**Issue by Trim21** [ent/ent#2224]
I'm trying to migrating a old project to entgo, but I stack at schema defining. 

I have a main subject table called `subject` and a new table called `subject_fields` contains some extra fields for subject.

```go
type Subject struct {
	ent.Schema
}

func (Subject) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "subjects"},
	}
}

func (Subject) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").StorageKey("subject_id"),
		field.Text("name").StorageKey("subject_name"),
	}
}

type SubjectFields struct {
	ent.Schema
}

func (SubjectFields) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "subject_fields"},
	}
}

func (SubjectFields) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").StorageKey("field_sid"),
		field.Int("field_rank"),
	}
}
```

In my case the table `SubjectFields` has only a `field_sid` as primary key and no ID field, and it's not a foreign key.

I tried many way to define the Edges but I can't find a way to make it works except I manually edit the generated code.

```go
func (Subject) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("fields", SubjectFields.Type).
			Unique().
			StorageKey(edge.Column("id")),
	}
}

// Edges of the SubjectFields.
func (SubjectFields) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("subject", Subject.Type).
			Ref("fields").
			Unique().
			Required(),
	}
}
```

this generate the sql like this:

```SQL
SELECT DISTINCT `subject_fields`.`field_sid`, `subject_fields`.`field_rank`, `subject_fields`.`id` FROM `subject_fields` WHERE `id` IN (?) args=[8]
```

and raise an error `Error 1054: Unknown column 'subject_fields.id' in 'field list`

I also tried `StorageKey(edge.Column("field_sid"))`, But in generated code, ent try to get ID from `SubjectFields{}.field_sid` which is never assigned. and raise `foreign-key "field_sid" is nil for node`

generated code:
```go
// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubjectFields fields.
func (sf *SubjectFields) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subjectfields.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sf.ID = int(value.Int64)
		case subjectfields.FieldFieldRank:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field field_rank", values[i])
			} else if value.Valid {
				sf.FieldRank = int(value.Int64)
			}
		case subjectfields.ForeignKeys[0]: 
            <-- never get here because `subjectfields.ForeignKeys[0] = subjectfields.FieldID = "field_sid"`
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field field_sid", value)
			} else if value.Valid {
				sf.field_sid = new(int)
				*sf.field_sid = int(value.Int64) 
			}
		}
	}
	return nil
}
```

I'm not sure if I make any mistake or it's un-expected behavoir?

**Comment by ListerLee** [comment]
I had the same problem

**Comment by a8m** [comment]
Hey @Trim21 and @ListerLee, there’s example in our integration tests for this use case. See https://github.com/ent/ent/blob/master/entc/integration/edgefield/ent/schema/info.go#L30.

If you still have troubles defining your schema, please create an example repo using ent/bug and I’ll try to help.

**Comment by ListerLee** [comment]
> Hey @Trim21 and @ListerLee, there’s example in our integration tests for this use case. See https://github.com/ent/ent/blob/master/entc/integration/edgefield/ent/schema/info.go#L30
> 
> If you still have troubles defining your schema, please create an example repo using [ent/bug](https://github.com/ent/bug) and I’ll try to help.

problem solved, thank you so much.

**Comment by a8m** [comment]
Great! Closing the issue then. Please, feel free to reopen it if you still have troubles, and join our [Discord server](https://discord.gg/qZmPgTE6RX).
