### ISSUE TITLE
TimeMixin invalid

### ISSUE THREAD

**Issue by wnz27** [ent/ent#2228]
![截屏2021-12-21 20 53 08](https://user-images.githubusercontent.com/12094918/146933306-939f5e90-81e9-468a-99b4-badee4ad5226.png)
![截屏2021-12-21 20 54 05](https://user-images.githubusercontent.com/12094918/146933358-13b5e7e7-c5fa-43bd-83c8-496ccc196b53.png)
i use
![截屏2021-12-21 20 54 47](https://user-images.githubusercontent.com/12094918/146933471-03993379-36f4-48db-987a-f560a0c561fc.png)
but it did not take effect.

**Comment by a8m** [comment]
Hey @wnz27 👋 

Can you elaborate on what is not working? What does it mean _it did not take effect_? You're welcome to use https://github.com/ent/bug to provide a reproducible example for me to debug. 😊

**Comment by wnz27** [comment]
i fix it i use go-sql-driver i set loc and it fixed

**Comment by wnz27** [comment]
thank u, and im sorry for bother u,

**Comment by wnz27** [comment]
ps:
 if  u use datetime field, u should set `parseTime=true` for go-sql-driver's source

**Comment by wnz27** [comment]
> Hey @wnz27 👋
> 
> Can you elaborate on what is not working? What does it mean _it did not take effect_? You're welcome to use https://github.com/ent/bug to provide a reproducible example for me to debug. 😊

it mean if i not set the loc, i use ent save one entity 2 db the create_at or update_at is all UTC the `LocalEast8Now` func maybe not be called

**Comment by wnz27** [comment]
and then i use loc, i can't need the `LocalEast8Now` func, i use `time.Now` directly.
