### ISSUE TITLE
how to use DISTINCT with ent?

### ISSUE THREAD

**Issue by feeops** [ent/ent#2232]
raw sql is 

`select DISTINCT region_id,category,storage_type from aliyun_rds_price`

**Comment by a8m** [comment]
Hey @feeops 👋 

All fields are selected with `DISTINCT` by default when you query nodes (e.g. `All()`). However, if you can `Scan`/`Strings`/etc, you need to set `Unique` explicitly. See:

```go
client.User.Query().AllX(ctx)
// SELECT DISTINCT `users`.`id`, ... FROM `users`

client.User.Query().Select(user.FieldName).AllX(ctx)
// SELECT DISTINCT `users`.`id`, `users`.`name` FROM `users`

client.User.Query().Unique(false).Select(user.FieldName).AllX(ctx)
// SELECT `users`.`id`, `users`.`name` FROM `users`

client.User.Query().Select(user.FieldName).StringsX(ctx)
// SELECT `users`.`name` FROM `users`

client.User.Query().Unique(true).Select(user.FieldName).StringsX(ctx)
// SELECT DISTINCT `users`.`name` FROM `users`
```

Closing, but please feel free to continue the discussion or join our [Slack](https://entgo.io/docs/slack/)/[Discord](https://discord.gg/qZmPgTE6RX) if you have more questions/thoughts. Thanks 🙏

**Comment by feeops** [comment]
> ```go
> client.User.Query().Select(user.FieldName).AllX(ctx)
> ```

I use client.User.Query().Unique(true).Select(user.FieldName1,user.FieldName2).AllX(ctx)

It do not work.

Debug sql is 

SELECT DISTINCT `users`.`id`, `users`.`name` FROM `users`

But I do not want `users`.`id` field

**Comment by feeops** [comment]
> Hey @feeops 👋
> 
> All fields are selected with `DISTINCT` by default when you query nodes (e.g. `All()`). However, if you can `Scan`/`Strings`/etc, you need to set `Unique` explicitly. See:
> 
> ```go
> client.User.Query().AllX(ctx)
> // SELECT DISTINCT `users`.`id`, ... FROM `users`
> 
> client.User.Query().Select(user.FieldName).AllX(ctx)
> // SELECT DISTINCT `users`.`id`, `users`.`name` FROM `users`
> 
> client.User.Query().Unique(false).Select(user.FieldName).AllX(ctx)
> // SELECT `users`.`id`, `users`.`name` FROM `users`
> 
> client.User.Query().Select(user.FieldName).StringsX(ctx)
> // SELECT `users`.`name` FROM `users`
> 
> client.User.Query().Unique(true).Select(user.FieldName).StringsX(ctx)
> // SELECT DISTINCT `users`.`name` FROM `users`
> ```
> 
> Closing, but please feel free to continue the discussion or join our [Slack](https://entgo.io/docs/slack/)/[Discord](https://discord.gg/qZmPgTE6RX) if you have more questions/thoughts. Thanks 🙏

I find a way to do it.

`go run entgo.io/ent/cmd/ent generate --feature sql/modifier ./ent/schema `

`   xx:=db.Debug().EcsPrice.Query().Unique(false).Modify(func(s *sql.Selector) {
	   s.Select("DISTINCT region_id,instance_type_id")
   }).AllX(context.Background())

   for _,t:=range xx{
	   fmt.Println(t.RegionId)
   }`

It works now

**Comment by feeops** [comment]
> Hey @feeops 👋
> 
> All fields are selected with `DISTINCT` by default when you query nodes (e.g. `All()`). However, if you can `Scan`/`Strings`/etc, you need to set `Unique` explicitly. See:
> 
> ```go
> client.User.Query().AllX(ctx)
> // SELECT DISTINCT `users`.`id`, ... FROM `users`
> 
> client.User.Query().Select(user.FieldName).AllX(ctx)
> // SELECT DISTINCT `users`.`id`, `users`.`name` FROM `users`
> 
> client.User.Query().Unique(false).Select(user.FieldName).AllX(ctx)
> // SELECT `users`.`id`, `users`.`name` FROM `users`
> 
> client.User.Query().Select(user.FieldName).StringsX(ctx)
> // SELECT `users`.`name` FROM `users`
> 
> client.User.Query().Unique(true).Select(user.FieldName).StringsX(ctx)
> // SELECT DISTINCT `users`.`name` FROM `users`
> ```
> 
> Closing, but please feel free to continue the discussion or join our [Slack](https://entgo.io/docs/slack/)/[Discord](https://discord.gg/qZmPgTE6RX) if you have more questions/thoughts. Thanks 🙏

I find a good way.

`db.Debug().EcsPrice.Query().Unique(false).Modify(func(s *sql.Selector) {
	   s.Distinct().Select(ecsprice.FieldRegionId,ecsprice.FieldInstanceTypeId)
   }).AllX(context.Background())`

**Comment by a8m** [comment]
Hey @feeops!

> But I do not want `users`.`id` field

When using `All`/`Only`/etc. with `Select`, the ID field is also selected. The reason is - you can limit the additional fields you want to select and fill on a query, but the ID is necessary for querying edges, deletion, update, etc. For example:
```go
u := client.User.Query().Select(user.FieldName).OnlyX(ctx)
posts := u.QueryPosts().AllX(ctx)
u = u.Update().SetName(u.Name + u.Name).Select(user.FieldName).SaveX(ctx)
```

However, if you don't want to get the ID field, you can use the `Scan` API:

```go
// Selecting 1 field.
client.User.Query().Unique(true).Select(user.FieldName).StringsX(ctx)

// Scan to custom struct when having more than 1 field.
var ns []struct{Name, Address string }
client.User.Query().Unique(true).Select(user.FieldName, user.FieldAddress).ScanX(ctx, &ns)

// Scan to users.
var us []*ent.User
client.User.Query().Unique(true).Select(user.FieldName, user.FieldAddress).ScanX(ctx, &us)
```

**Comment by feeops** [comment]
> ```go
> var us []*ent.User
> ```

It do not work

Core code

`type t struct {
	RegionId    string `sql:"region_id"`
	Category    string `sql:"category"`
	StorageType string `sql:"storage_type"`
}

db := database.InitDB()
var ns []t
err := db.Debug().RDSPrice.Query().Unique(true).Select(
rdsprice.FieldRegionId, rdsprice.FieldCategory, rdsprice.FieldStorageType).Scan(context.Background(), &ns)
fmt.Println(err)
`

debug sql is
`
driver.Query: query=SELECT `aliyun_rds_price`.`region_
id`, `aliyun_rds_price`.`category`, `aliyun_rds_price`.`storage_type` FROM
 `aliyun_rds_price` args=[]
`

lost DISTINCT world
