### ISSUE TITLE
Have an easy way to get min,max,sum function with one field

### ISSUE THREAD

**Issue by feeops** [ent/ent#2242]
raw sql
```
select max(age) from users
```

with ent,core code
```
xxx..Modify(func(s *sql.Selector) {
			s.Select("Max(age)")
		}
```

Do you have an easy way?

**Comment by yonidavidson** [comment]
Hey @feeops , here is an example for min/max in one liners
```go
func TestUserDefaultValue(t *testing.T) {
	ctx := context.Background()
	c := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	c.User.Create().SetAge(38).ExecX(ctx)
	c.User.Create().SetAge(20).ExecX(ctx)
	u := c.User.Query().Order(ent.Asc(user.FieldAge)).FirstX(ctx)
	require.Equal(t, 20, u.Age)
	u = c.User.Query().Order(ent.Desc(user.FieldAge)).FirstX(ctx)
	require.Equal(t, 38, u.Age)
}

```

**Comment by feeops** [comment]
> Hey @feeops , here is an example for min/max in one liners
> 
> ```go
> func TestUserMinMax(t *testing.T) {
> 	ctx := context.Background()
> 	c := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
> 	c.User.Create().SetAge(38).ExecX(ctx)
> 	c.User.Create().SetAge(20).ExecX(ctx)
> 	u := c.User.Query().Order(ent.Asc(user.FieldAge)).FirstX(ctx)
> 	require.Equal(t, 20, u.Age)
> 	u = c.User.Query().Order(ent.Desc(user.FieldAge)).FirstX(ctx)
> 	require.Equal(t, 38, u.Age)
> }
> ```

How to do with sum?

**Comment by yonidavidson** [comment]
Based on the example [here](https://entgo.io/docs/aggregate#group-by)

```go
        ctx := context.Background()
	c := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	c.User.Create().SetAge(20).ExecX(ctx)
	c.User.Create().SetAge(20).ExecX(ctx)
	c.User.Create().SetAge(38).ExecX(ctx)
	type r struct {
		Age   int `json:"age"`
		Sum   int `json:"sum"`
		Count int `json:"count"`
	}
	var v []r
	expected := []r{{Age: 20, Sum: 40, Count: 2}, {Age: 38, Sum: 38, Count: 1}}
	c.User.Query().
		GroupBy(user.FieldAge).
		Aggregate(ent.Count(), ent.Sum(user.FieldAge)).
		ScanX(ctx, &v)
	require.EqualValues(t, expected, v)
```

**Comment by yonidavidson** [comment]
@feeops I am closing the issue, for now, create another issue or ping me on discord if you have more questions.

**Comment by a8m** [comment]
Hey! I just want to update you that the aggregation API was simplified, and you can read about it here https://twitter.com/entgo_io/status/1584091539479080960 and https://entgo.io/docs/aggregate.

Also, here's a small example:

```go
// Aggregate one field.
sum, err := client.Order.Query().
    Aggregate(
        ent.Sum(order.FieldPrice),
    ).
    Int(ctx)

// Aggregate multiple fields.
var v []struct {
    Sum, Min, Max, Count int
}
err := a8m.QueryOrders().
    Aggregate(
        ent.Sum(order.FieldPrice),
        ent.Min(order.FieldPrice),
        ent.Max(order.FieldPrice),
        ent.Count(),
    ).
    Scan(ctx, &v)
```
