### ISSUE TITLE
entgql WithWhereFilters generates invalid code

### ISSUE THREAD

**Issue by MrParano1d** [ent/ent#2248]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

entgql creates me this graphql input:

```
input MatchWhereInput {
  not: MatchWhereInput
  and: [MatchWhereInput!]
  or: [MatchWhereInput!]
  
  [...]
  hasAwayWith: [ParticipantWhereInput!]
  [...]
}
```

When I try to query with this query variables:

```
{
  "where": {
      "or": {
    	"hasAwayWith": {
            "hasUserWith": {
                "usernameContainsFold": "gophie"
      	    }
         }
      }
  }
}
```

unmarshalInputMatchWhereInput panics:

```
interface conversion: interface {} is []map[string]interface {}, not map[string]interface {}
```

the where map loks like this:
```
map[or:[map[hasAwayWith:[map[hasUserWith:[map[usernameContainsFold:gophie]]]]]]]
```

As you can see, the `or` value is a map-slice instead of a map.
`hasAwayWith`, `hasUserWith` are also map-slices instead of a maps.

entgql generates ` or: [MatchWhereInput!]` and `hasAwayWith: [ParticipantWhereInput!]` into the graphql schema and that's probably why it converts it to a map-slice instead of a simple map but gqlgen can't handle that.

## Expected Behavior 🤔

I don't see any problems with my query variables and they should be handled by entgql and gqlgen. WhereInput should be a map and not a slice-map.

## Steps to Reproduce 🕹

It's reproducable with your own repo: https://github.com/a8m/ent-graphql-example from this tutorial: https://entgo.io/docs/tutorial-todo-gql

![image](https://user-images.githubusercontent.com/7414374/147970165-daa54972-44e6-4140-9d65-7e3d19013379.png)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.9.2   |
| Database    | Postgres  |
| Driver      | https://github.com/jackc/pgx        |
| gqlgen    |  0.14.0 |

**Comment by yonidavidson** [comment]
@MrParano1d thanks for your comment.
Seems like the GraphQL clients change the type when using params.
This behavior isn't observed when used in go code like resolvers tests or in the frontend using React-Relay.

![image](https://user-images.githubusercontent.com/5472778/151249131-631c9ee4-133c-40bf-8293-58c4d4d348ff.png)

Is this not working for you in a client framework/go code ?

**Comment by MrParano1d** [comment]
Thank you for your answer. The newest playground UI seems to fix this issue and I can work with query variables again. Thanks for the help.

**Comment by MrParano1d** [comment]
Just if anyone is interested: the gqlgen 0.14.0 playground was broken and 0.15.0 fixed it with GraphiQL as the new playground.
