### ISSUE TITLE
client.BeginTx does not set transaction context

### ISSUE THREAD

**Issue by lukasbraach** [ent/ent#2253]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using the generated `ent.Client` to start a database transaction with the `BeginTx` method, the `Tx` struct's go-context field (`ctx`) does not get populated. This leads to hard-to-debug errors, as transaction commit hooks use this exact context in the `ent.CommitFunc`. The result is a nil-pointer-panic because of the missing context.

## Expected Behavior 🤔

I would expect that `BeginTx(...)` should populate the `ctx` field, ergo the same behavior as `Tx(...)`. This is not the case.

## Steps to Reproduce 🕹

```golang
var client *ent.Client
// connect to your database...

ctx := context.Background()
tx, err := client.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
if err != nil {
    panic("out of scope of this bug report...")
}

tx.OnCommit(func(next ent.Committer) ent.Committer {
    return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) (err error) {

        if ctx == nil {
            panic("this will panic.")
        }

        return next.Commit(ctx, tx)
    })
})


_ = tx.Commit()
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.5  |
| Ent         | 0.9.1   |
| Database    | Postgres   |
| Driver      | github.com/lib/pq        |

**Comment by a8m** [comment]
Thanks for reporting this issue @lukasbraach 🙏 

It looks like [Client.BeginTx](https://github.com/ent/ent/blob/master/entc/gen/template/client.tmpl#L91-L92) is not aligned with [Client.Tx](https://github.com/ent/ent/blob/master/entc/gen/template/client.tmpl#L91-L92). Do you want to send a patch to fix this? 😃

**Comment by ItsATrap48** [comment]
@a8m can I take this one on?

**Comment by ItsATrap48** [comment]
@a8m Can I take this one on?

**Comment by a8m** [comment]
Sure, go ahead.

**Comment by ItsATrap48** [comment]
@a8m I don't think I have permission to push up a new branch. Can you add permission to me or do I need to be assigned to the issue to be given permission?

**Comment by giautm** [comment]
Hey @ItsATrap48, you need to fork this project to your account. Then create a new branch on it. Later, you open a PR for the request to merge.

**Comment by Laconty** [comment]
Hello, I'd like to contribute on this one could you see my PR please? 😃 
(my first public commit, my apologies if anything wrong)
