### ISSUE TITLE
Looking for example how to use dialect.DebugWithContext

### ISSUE THREAD

**Issue by Menta2L** [ent/ent#2276]
Hello its a great project and i love it. But beyond the basic usage ther e is no documentation at all. 
I like to attach an opentracer  to trace   each query  and I assume that this is possible somehow  via dialect.DebugWithContext

Can you give me a short example please ?

**Comment by crossworth** [comment]
Hello, I think you can add tracing using two methods.

1. `database/sql` https://github.com/inkbe/opentracing-sql
2. `ent` driver (something like this https://gist.github.com/crossworth/719fada9f346767069dc903a5f429b04)

Other projects that defines drivers:
- https://github.com/ariga/entcache
- https://github.com/ariga/sqlcomment

Also check: 
- https://entgo.io/docs/sql-integration#use-opencensus-with-mysql
- https://github.com/ent/ent/issues/1232

**Comment by zeevmoney** [comment]
Hi @Menta2L,

First of all the solution that @crossworth suggested is great, but there is also a simpler solution (as you suggest in the topic), you can do something like this:

```go
import (
  "database/sql"
  "entgo.io/ent/dialect"
  "entsql "entgo.io/ent/dialect/sql"
)
// ....
db, err := sql.Open(dialect.SQLite, "file:example?mode=memory&cache=shared&_fk=1")
if err != nil {
  log.Fatal(err)
}
drv := entsql.OpenDB(dialect.SQLite, db)
drvWithContext := dialect.DebugWithContext(drv, func(ctx context.Context, i ...interface{}) {
log.Println(i)
// attach tracing here
// Example output:
// 2022/01/20 00:14:06 [Tx(4fe0fa85-1027-475b-93a8-d22c9cef287c).Query: query=SELECT COUNT(*) FROM `sqlite_master` WHERE `type` = ? AND `name` = ? args=[table ent_types]]
})
client := ent.NewClient(ent.Driver(drvWithContext))
```

**Comment by Menta2L** [comment]
Thanks @zeevmoney  that's was exactly what I was looking for :)

**Comment by zeevmoney** [comment]
@Menta2L, is there anything else I can help you with? or we can close this issue?

**Comment by a8m** [comment]
OK, I assume we can close this, but please feel free to reopen or join our Slack or Discord channel if you have any questions.

Thanks a lot, @crossworth and @zeevmoney for supporting @Menta2L.
