### ISSUE TITLE
New release uses a invalid semantic version tag

### ISSUE THREAD

**Issue by shenghui0779** [ent/ent#2282]
![image](https://user-images.githubusercontent.com/67535398/150447067-069772a0-d22d-4c4e-b634-e9d8db1c2964.png)

![image](https://user-images.githubusercontent.com/67535398/150447133-49e26184-8fe8-4f46-9186-e293a5bae461.png)

**Comment by a8m** [comment]
Thanks for reporting this @shenghui0779. I fixed it - https://github.com/ent/ent/releases/tag/v0.10.0
