### ISSUE TITLE
Can Upsert be used with Postgres?

### ISSUE THREAD

**Issue by SuzurikawaChihiro** [ent/ent#2286]
I'm building an API using ent, and when I try to implement Upsert.
It succeeds in SQLite3 and fails in Postgres.

The Upsert code looks like this.
```go
id, err := repo.DB.Sample.
	Create().
	SetAccountID(req.AccountID).
	SetName(req.Name).
	SetAge(req.Age).
	OnConflict().
	UpdateNewValues().
	ID(ctx)
```

|  | Version |
| --- | --- | 
| ent | v0.10.0 |
| PostgreSQL | 13.2 |
| go-sqlite | [github.com/mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) |

![image](https://user-images.githubusercontent.com/64934951/150725575-05b56383-6cf6-454e-8f18-11fe9d158128.png)

**Comment by crossworth** [comment]
Hello, you must provide a conflict target using `OnConflictColumns` (for Postgres).

Check the documentation below:
https://entgo.io/docs/crud/#upsert-one

**Comment by SuzurikawaChihiro** [comment]
Thank you for @crossworth .
Successfully succeeded!!
