### ISSUE TITLE
Eager loading not working when using Scan

### ISSUE THREAD

**Issue by guihouchang** [ent/ent#2287]
- [√ ] The issue is present in the latest release.
- [√ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
[https://github.com/ent/ent/issues/2283](https://github.com/ent/ent/issues/2283)

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.9.1   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by guihouchang** [comment]
https://entgo.io/zh/docs/feature-flags

**Comment by liasica** [comment]
I have same issue.

When using Modify().Scan(), Edges always nil
