### ISSUE TITLE
Atlas integration to support disabled foreign keys

### ISSUE THREAD

**Issue by naormatania** [ent/ent#2288]
## Summary 💡

You currently cannot use Atlas integration (https://entgo.io/docs/migrate/#atlas-integration) while disabling foreign key (https://entgo.io/docs/migrate#foreign-keys)

You currently get back an error `errors.New("sql/schema: WithForeignKeys(false) does not work in Atlas migration")` (https://github.com/ent/ent/blob/60e03285d018f1da56a2148967b74cd21a6d0843/dialect/sql/schema/atlas.go#L255)

## Motivation 🔦

Atlas integration is useful for many things like validating migration diffs, #1688 and more
Disabling foreign keys is good for improving performance and also for more distributed setup where each microservice controls its own schema/database

It would be great if both could work together

**Comment by a8m** [comment]
Hey @naormatania and thanks for opening this issue.

I should get to this later this week. Would you like to contribute this? It should be pretty simple to implement 😃

**Comment by naormatania** [comment]
Thanks @a8m !
I don't think I have time to contribute but I'm looking forward for this :)

**Comment by zeevmoney** [comment]
Hi @naormatania,

I just pushed a PR that adds the feature you've been asking for in here

https://github.com/ent/ent/pull/2404

**Comment by a8m** [comment]
Thanks @naormatania and @zeevmoney
