### ISSUE TITLE
Does entgo support multiple database?

### ISSUE THREAD

**Issue by abdarafi** [ent/ent#2292]
Hi Guys, i want to ask. :) 

I'm wondering if `ent.go` supports multiple data store, For example for the Read or Query operation I want to retrieve it from the `read-only` database (different host)?

Thanks :)

**Comment by cjraa** [comment]
Hi @abdarafi 

This might be what you are looking for, https://github.com/ent/ent/issues/46#issuecomment-1020003833

**Comment by abdarafi** [comment]
> Hi @abdarafi
> 
> This might be what you are looking for, [#46 (comment)](https://github.com/ent/ent/issues/46#issuecomment-1020003833)

Yeah, thanks for your help! @cjraa
