### ISSUE TITLE
Count has a different behavior in 0.10.0

### ISSUE THREAD

**Issue by washanhanzi** [ent/ent#2298]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Previous to `0.10.0`, `count` will auto add a `SELECT COUNT(DISTINCT "users"."id")` clause, as documented [here](https://entgo.io/docs/predicates/#count-the-number-of-users-whose-json-field-named-url-contains-the-scheme-key).

I can use `count` like:

```
count := client.User.
    Query().
    Where(func(s *sql.Selector) {
        s.Where(sqljson.HasKey(user.FieldURL, sqljson.Path("Scheme")))
    }).
    CountX(ctx)
```

In `0.10.0`, I beleive to fix #2036, when using `count` I must provide a `select` clause, as:

```
count := client.User.
    Query().
    Select(user.FieldID).
    Where(func(s *sql.Selector) {
        s.Where(sqljson.HasKey(user.FieldURL, sqljson.Path("Scheme")))
    }).
    CountX(ctx)
```

or the generated query will select all fields and  I will get an error:

```
"pq: function count(character varying, character varying, character varying, character varying, character varying, character varying, character varying, jsonb, jsonb, jsonb, timestamp with time zone, timestamp with time zone, character varying, character varying, jsonb, jsonb, timestamp with time zone, character varying, timestamp with time zone, jsonb, character varying, character varying, bigint, jsonb, timestamp with time zone) does not exist"
```

Maybe it is better to provide backward compability? Like when `count` without provided `select`, ent will auto add a `selet id` clause, otherwire ent will use user's `select` input.

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.10.0   |
| Database    | PostgreSQL   |
| Driver      | github.com/lib/pq        |

**Comment by giautm** [comment]
> Maybe it is better to provide backward compability? Like when count without provided select, ent will auto add a selet id clause, otherwire ent will use user's select input.

I think the PR really do that, based on bellow code:
https://github.com/ent/ent/blob/1049e874ac252bf171b4df175bf4788d43bff7f9/dialect/sql/sqlgraph/graph.go#L590-L598

**Comment by a8m** [comment]
Hey @washanhanzi, can you please provide an example to reproduce this? I just ran your example on both `master` and `v0.9.0` and got the same output:

`master`:
```
➜  json git:(master) ✗ go test -run=Postgres
2022/01/27 13:21:30 driver.Query: query=SELECT COUNT(DISTINCT "users"."id") FROM "users" WHERE "url"->'Scheme' IS NOT NULL args=[]
```

`v0.9.0`:
```
➜  json git:(e0a85ab6) ✗ go test -run=Postgres
2022/01/27 13:22:38 driver.Query: query=SELECT COUNT(DISTINCT "users"."id") FROM "users" WHERE "url"->'Scheme' IS NOT NULL args=[]
```

Thanks for the support @giautm ❤️ 🙏

**Comment by angristan** [comment]
I ran into the same issue:

```
ent: check existence: pq: function count(bigint, timestamp with time zone, timestamp with time zone, timestamp with time zone, timestamp with time zone, character varying, character varying, character varying, character varying, character varying) does not exist
```

**Comment by a8m** [comment]
Hey @angristan, please use [ent/bug](https://github.com/ent/bug) to help me reproduce this. Thanks 🙏

**Comment by angristan** [comment]
I can't manage to reproduce using this repo :(

**Comment by angristan** [comment]
Any `.Exist()` or `.Count()` query seems to fail, with the following logged on the postgresql server:

```
ERROR:  function count(bigint, timestamp with time zone, timestamp with time zone, timestamp with time zone, timestamp with time zone, character varying, character varying, character varying, character varying, character varying) does not exist at character 8
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  SELECT COUNT(DISTINCT "volumes"."id", "volumes"."creation_date", "volumes"."update_date", "volumes"."deletion_date", "volumes"."purge_date", "volumes"."project_id", "volumes"."organization_id", "volumes"."ceph_namespace", "volumes"."ceph_name", "volumes"."name") FROM "volumes" WHERE "volumes"."name" = $1
```

**Comment by angristan** [comment]
(I don't have the issue in v0.9.1, so probably related to https://github.com/ent/ent/commit/3e6c40886d55c57a57fe209b52766951c9d9c917)

**Comment by a8m** [comment]
> I can't manage to reproduce using this repo :(

Can you please paste here an example query that causes this failure?

**Comment by angristan** [comment]
Yes, simply this for instance:

```go
exists, err := b.DB.Volume.Query().Where(volume.Name(req.Name)).Exist(ctx)
if err != nil {
	return nil, err
}
```

**Comment by a8m** [comment]
Hey @angristan, did you run the code generation after updating to v0.10? If so, how do you run it?

**Comment by angristan** [comment]
Looks like I forgot to regenerate the code...

<img width="899" alt="screenshot_2022-02-02_13-09-14" src="https://user-images.githubusercontent.com/11699655/152151049-8b09597a-8793-43bc-ae60-85a13e465c2b.png">

It works now 👍 Sorry for the noise!

**Comment by a8m** [comment]
Great, we may need to add a check for this.

**Comment by washanhanzi** [comment]
I have an idea, maybe add the `entc` version info in generated file.
