### ISSUE TITLE
UUID, base64 and filtering

### ISSUE THREAD

**Issue by theprobugmaker** [ent/ent#2299]
I'm trying to integrate ent with gqlgen and I have a few questions:

1. how can I use UUID instead of a regular sequential ID?
2. how can I use base64 on the cursors? (just like the `graphql-relay-js`: (global id): https://github.com/graphql/graphql-relay-js/blob/main/src/node/node.ts#L91 - (connection): https://github.com/graphql/graphql-relay-js/blob/3796e0904fbfe0dd86e540d5b4df236330c8a5e7/src/connection/arrayConnection.ts#L132 )
3. I was following this tutorial (https://entgo.io/docs/tutorial-todo-gql-filter-input) and the generated schema has every field from the model, how can I choose which ones I want to filter from?

ent generates the code but it has the "DO NOT EDIT" and Visual Studio Code won't allow me to edit them so there's probably another way of modifying/adding those changes/features.

Thank you.

**Comment by a8m** [comment]
Hey @theprobugmaker 👋 

> How can I use UUID instead of a regular sequential ID?

Of course, and there are a few examples for this in our docs. See https://entgo.io/docs/graphql#examples

Regarding 2, and 3 - I'll answer later today or tomorrow (weekend mode 🏖️).

**Comment by theprobugmaker** [comment]
Thank you very much for the answer @a8m. Looking forward to hearing about the 2 and 3.

**Comment by crossworth** [comment]
I already have explained to @theprobugmaker but I will answer here as well to make easy to more people find about this stuff.

2 - The current implementation don't allow much control over the Cursor type/creation [1](https://github.com/ent/contrib/blob/4b15fea7816e38e880488f890bec3bdaa9983d29/entgql/template/pagination.tmpl#L446) [2](https://github.com/ent/contrib/blob/4b15fea7816e38e880488f890bec3bdaa9983d29/entgql/template/pagination.tmpl#L508), without modifying the templates files. It's [possible](https://github.com/crossworth/globalid/commit/82ef64dd49c9ee9269a48a060927ff5edd21b801) to make it use base64 (or other types), but **currently** only with templates.
3 - Is possible to skip a field using [`entgql.Skip` annotation](https://github.com/ent/contrib/blob/4b15fea7816e38e880488f890bec3bdaa9983d29/entgql/annotation.go#L37).

**Comment by theprobugmaker** [comment]
Thank you very much @crossworth.
