### ISSUE TITLE
Filtering, Ordering and Pagination Support on nested Edges

### ISSUE THREAD

**Issue by maaft** [ent/ent#2305]
Opening a new Issue to consolidate these closely related features.

## Summary 💡

Currently it is not possible to filter, order and/or paginate on nested edges in any combination possible (Related: #1329).

This is also true when using the graphql integration. Following queries are currently not possible:
```
query QueryAllZoosWithAnimalsNamed($name: String!) {
   queryZoo {
      name
      animals(filter: {name: $name}) { // filtering on nested edges is not possible
         name
       }
   }
}

query QueryAllZoosWithOrderedAnimals {
   queryZoo {
      name
      animals(orderBy: {direction: DESC, field: NAME}) { // ordering on nested edges is not possible
         name
       }
   }
}

query QueryFoldersWithPreviewThumbnail {
   queryFolder {
      name
      images(first: 1) { // pagination on nested edges currently not possible
         thumbnail
       }
   }
}
```

All of these queries (and of course combinations of these do not work currently. Of course we could always find workarounds, but they are often not desirable because they introduce additional maintenance effort (e.g. extra fields) or force the (web)client to do extra structuring work as we loose our top-down graph structure.

## Motivation 🔦

This functionality should be a top priority for a graph-based entity framework brings ent one step closer to become the one-stop-solution for a GraphQL database.

For reference: @yonidavidson

**Comment by kilianstallz** [comment]
This would be very important! Kind of a dealbreaker in my eyes.
Being able to pass parameters down to fields for pagination is a must have when working with graphs.

**Comment by frederikhors** [comment]
@a8m What priority do you have for this?

**Comment by a8m** [comment]
Hey 👋🏻 
All the three were added in the latest version of entgql. Thanks for the reminder, I think we can close thus 🙌

**Comment by marcinztipsera** [comment]
Are there any examples, documentation how to use/create a support for something like this
```
uery QueryAllZoosWithOrderedAnimals {
   queryZoo {
      name
      animals(orderBy: {direction: DESC, field: NAME}) { // ordering on nested edges is not possible
         name
       }
   }
}
```

on the server side?

**Comment by a8m** [comment]
Hey @marcinztipsera,
If you’re enabling the RelayConnection annotation to your edges/nodes, it should work. See https://entgo.io/docs/tutorial-todo-gql-paginate#add-pagination-support-for-query
