### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by bionic-ido** [ent/ent#2308]
Yesterday there was a fix here that is really important to my project: https://github.com/ent/ent/pull/2306 (done by @a8m )

And I was wondering regarding when a version that contains it would be released & what my options are.

Thanks in advance,

Ido

**Comment by crossworth** [comment]
You can always use `@master` or `@commit hash`

```
go get -d entgo.io/ent/cmd/ent@master
go get -d entgo.io/ent/cmd/ent@2e906bffa2546efad6f5daee2a604f097373ba8d
```

**Comment by bionic-ido** [comment]
I did, and just found out that this isn't exactly the same issue.
The issue that @a8m solved was if the table names in the schema are with conflicting names.
The issue I have is that json fields from 2 of my tables come from 2 different external packages with the same name ("k8s.io/api/core/v1" & "k8s.io/api/apps/v1" for example).
:(

**Comment by yonidavidson** [comment]
@bionic-ido can I close this issue? It seems that you need another issue for your problem.

**Comment by a8m** [comment]
> @bionic-ido can I close this issue? It seems that you need another issue for your problem.

Hey @yonidavidson, I think the problem here is different and we should address this. @bionic-ido, can you suggest the desired behavior for this case? Should ent choose a random prefix for the local name, or infer it somehow from the import path?

**Comment by bionic-ido** [comment]
> > @bionic-ido can I close this issue? It seems that you need another issue for your problem.
> 
> Hey @yonidavidson, I think the problem here is different and we should address this. @bionic-ido, can you suggest the desired behavior for this case? Should ent choose a random prefix for the local name, or infer it somehow from the import path?

The problem is when we have two imports like a/v1 and b/v1, so in that case infering it from the path of the package can work.
I don't know however what would start happening with paths that are simillar in more then just the name and if that should even be supported (a/a/v1 and b/a/v1 for example).

**Comment by a8m** [comment]
> Yesterday there was a fix here that is really important to my project: #2306 (done by @a8m )
> 
> And I was wondering regarding when a version that contains it would be released & what my options are.
> 
> Thanks in advance,
> 
> Ido

Closing as the version was released a long time ago. Please, feel free to reopen or ping me on our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.
