### ISSUE TITLE
Using SchemaType with composite types leads to useless ALTER TABLEs in migration in some cases

### ISSUE THREAD

**Issue by thehowl** [ent/ent#2319]
On our ent set up, we use automatic schema migrations by Ent. The migration system attempts to identify which columns have changed, and while this is correctly identified in most cases, for some composite types (for our case, `DECIMAL`), ent does not correctly identify as it being equal to the type in the schema, which leads to an ALTER TABLE which can possibly create other issues as it happened to my team in production.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

We have a schema for a `Clinic` entity, which I have simplified to this to prove my point:

```go
// Clinic holds the schema definition for the Clinic entity.
type Clinic struct {
	ent.Schema
}

// Fields of the Clinic.
func (Clinic) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.Float("latitude").Optional().SchemaType(map[string]string{
			dialect.Postgres: "decimal(11, 7)",
		}),
		field.Float("longitude").Optional().SchemaType(map[string]string{
			dialect.Postgres: "decimal(11, 7)",
		}),
	}
}
```

When running the server with debug, for each restart running Migrate with Debug activated shows that no alter tables are performed, except for this one:

```
2022/02/10 10:41:21 Tx(4f48f130-f148-4275-a9cc-64e2c71dcd3a).Query: query=SELECT "column_name", "data_type", "is_nullable", "column_default", "udt_name", "numeric_precision", "numeric_scale" FROM "information_schema"."columns" WHERE "table_schema" = CURRENT_SCHEMA() AND "table_name" = $1 args=[clinics]
... [stripped] ...
2022/02/10 10:41:21 Tx(4f48f130-f148-4275-a9cc-64e2c71dcd3a).Exec: query=ALTER TABLE "clinics" ALTER COLUMN "latitude" TYPE decimal(11, 7), ALTER COLUMN "latitude" DROP NOT NULL, ALTER COLUMN "longitude" TYPE decimal(11, 7), ALTER COLUMN "longitude" DROP NOT NULL args=[]
```

The explanation for this behaviour can be found here:

https://github.com/ent/ent/blob/60e03285d018f1da56a2148967b74cd21a6d0843/dialect/sql/schema/postgres.go#L262-L268

When parsing the column definition, ent "reconstructs" the type as `numeric(11,7)`. This is because the result of the first query returns this column definition:

```
      column_name      |        data_type         | is_nullable |    column_default     |  udt_name   | numeric_precision | numeric_scale
-----------------------+--------------------------+-------------+-----------------------+-------------+-------------------+---------------
 id                    | bigint                   | NO          |                       | int8        |                64 |             0
 name                  | character varying        | NO          |                       | varchar     |                   |
 latitude              | numeric                  | YES         |                       | numeric     |                11 |             7
 longitude             | numeric                  | YES         |                       | numeric     |                11 |             7
```

Thus ent, not understanding that in postgres numeric is an alias for decimal, instructs to perform an `ALTER TABLE` with the type defined in `SchemaType`. When changing the `SchemaType` to `numeric(11,7)`, the bug does not reproduce 

## So what?

The issue might seem useless, as in effect the `ALTER TABLE` is a no-op and does not change either the structure or the data of the table on which it acts, as it is saying to change the type with the same type. However, the issue that this cascades onto is locking.

### Our production incident

We were unlucky to have encountered this bug while one of our developers was using an open dbeaver connection to the database in production mode. Production mode wraps all the statements done to the production database inside a transaction. He made a query which used the ID of the clinic in a JOIN statement, without committing or rolling back the transaction. (He then lost the connection, and possibly for some misconfiguration of our specific database, Amazon Aurora, the transaction was kept open in spite of the connection being dropped). This meant that the transaction was maintaining a schema lock onto the `clinics` table. Thus, when the software was restarted in production for upgrading to the latest commit, running the ent migrations caused the software not to start, as it was awaiting for its schema lock onto the clinics table in order to perform the `ALTER TABLE` (even though it is effectively a no-op).

Although the core issue of our incident was the misconfiguration of the database which did not rollback transactions of dropped connections, and this issue would have arisen anyway should a legitimate `ALTER TABLE` have been performed, this has caused as you can imagine quite a bit of a headache in a real-life scenario as there was no cause-effect relation, especially as we did not expect ent to have been performing no-op alter tables at each startup of the software.

## Proposed solution

Ent should be aware of this behaviour in postgres (although I would think that this behaviour appears also in other SQL databases), and thus convert equivalent types to a common syntax, including those in the SchemaType of a schema definition.

For instance, if my SchemaType is `DECIMAL(11, 7)`, I believe ent should convert it to lowercase, remove the space, and convert the `decimal` alias to `numeric` (which is what postgres returns as the data type of the column in information_schema.columns), this way it can correctly detect when the columns have actually changed and only perform legitimate `ALTER TABLE`s.

**Comment by masseelch** [comment]
Hey @thehowl,

I think your issue would be resolved by switching over to the new migration engine based on [atlas](atlasgo.io).

For that l, just add the following to the automatic migration code snippet:

`client.Schema.Create(ctx, schema.WithAtlas(true))`

[This](https://entgo.io/blog/2022/01/20/announcing-new-migration-engine) is the announcing blog post.

**Comment by thehowl** [comment]
I saw that existed shortly after writing this issue. ;) We'll be testing it out.
