### ISSUE TITLE
ent won't work with gqlgen and federation

### ISSUE THREAD

**Issue by theprobugmaker** [ent/ent#2321]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I tried following [this repository](https://github.com/demobin8/ent-federation-example) and everything worked fine until I tried to use a feature from the Apollo Federation (that works on gqlgen) that is using the `@external` directive. It throws me an error saying:

> creating entgql extension: schema.graphql:48: Undefined directive external.
> exit status 1
> ent\generate.go:3: running "go": exit status 1

## Expected Behavior 🤔

It should generate without any errors. The directive is actually created and exists on the `generated.go` gqlgen file.

## Steps to Reproduce 🕹

You can use the repository mentioned above and just include the `@external` in a field or use the ent + gqlgen example, activate the federation, and use the `@external` directive.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.4  |
| Ent         | 0.10.0   |

**Comment by giautm** [comment]
Hey @theprobugmaker, I'm also playing with Ent + Apollo Federation. Your issue looks like another one that I fixed via this commit https://github.com/ent/contrib/pull/199, So, what is your ent-contrib version?

**Comment by theprobugmaker** [comment]
It worked, thank you @giautm

**Comment by giautm** [comment]
Hey @a8m, can you release a new version of ent-contrib?
