### ISSUE TITLE
Schema Hook cannot generate,  entc/load: load schema dir: -: import cycle not allowed

### ISSUE THREAD

**Issue by medivh-jay** [ent/ent#2329]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Unable to generate code normally

## Expected Behavior 🤔
Normal code generation

## Steps to Reproduce 🕹

Steps:
1. Download compressed files  [ent-test.zip](https://github.com/ent/ent/files/8059202/ent-test.zip)
2. Use this project
3. Execute   `ent generate .\ent\schema\`
4. Mainly three files in the schema folder

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.10.0   |
| Database    | PostgreSQL  |
| Driver      | github.com/jackc/pgx/v4/stdlib        |

I'm so sorry to bother you

**Comment by medivh-jay** [comment]
Maybe you can clone this project directly to the local computer  `https://github.com/medivh-jay/enttest`

**Comment by medivh-jay** [comment]
```
git clone https://github.com/medivh-jay/enttest.git
cd enttest
ent generate ./ent/schema/
```

I use a `schema hook` in schema/member.go.

**Comment by lyekumchew** [comment]
this issue may help you https://github.com/ent/ent/issues/892#issuecomment-717782525

**Comment by medivh-jay** [comment]
I'm sorry, this is because I defined the internal structure inside the schema package myself.
