### ISSUE TITLE
Missing unique field in query Clone()

### ISSUE THREAD

**Issue by MrParano1d** [ent/ent#2331]
The `unique` Field from a query builder is ignored when the query gets cloned.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The query template doesn't clone the `unique` field from the query.

```
// Clone returns a duplicate of the {{ $builder }} builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func ({{ $receiver }} *{{ $builder }}) Clone() *{{ $builder }} {
	if {{ $receiver }} == nil {
		return nil
	}
	return &{{ $builder }}{
		config: 	{{ $receiver }}.config,
		limit: 		{{ $receiver }}.limit,
		offset: 	{{ $receiver }}.offset,
		order: 		append([]OrderFunc{}, {{ $receiver }}.order...),
		predicates: append([]predicate.{{ $.Name }}{}, {{ $receiver }}.predicates...),
		{{- range $e := $.Edges }}
			{{ $e.EagerLoadField }}: {{ $receiver }}.{{ $e.EagerLoadField }}.Clone(),
		{{- end }}
		// clone intermediate query.
		{{ $.Storage }}: {{ $receiver }}.{{ $.Storage }}.Clone(),
		path: {{ $receiver }}.path,
	}
}
```

## Expected Behavior 🤔

When I do a `client.SomeModel.Query().Unique(false).Clone()` `unique` is `true` again.

It should be `false`.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | 0.10.0   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/jackc/pgx        |

**Comment by a8m** [comment]
Fixed with #2332, Thanks!
