### ISSUE TITLE
Create a full search postgres index

### ISSUE THREAD

**Issue by nilpntr** [ent/ent#2352]
Is it possible to create an index like this: `CREATE INDEX name ON table USING gin(column);`? I'm not sure how to prefix this part before the column name: `USING gin`

**Comment by a8m** [comment]
Hey @nilpntr 👋 

Yes! Thanks to [atlas](https://github.com/ariga/atlas), it's possible. Please see the documentation on how to enable it to your schema:

https://entgo.io/docs/schema-indexes#atlas-support
https://entgo.io/docs/migrate#atlas-integration

If you're using only PostgreSQL (and SQLite for testing), you can define your index as follows:

```go
index.Fields("c4").
    Annotations(entsql.IndexType("GIN"))
```

If your ent/schema is executed on both MySQL and PostgreSQL, and you want to configure a different index-type for each one of them, use:

```go
index.Fields("c5").
    Annotations(
        entsql.IndexTypes(map[string]string{
            dialect.MySQL:    "FULLTEXT",
            dialect.Postgres: "GIN",
        }),
    )
```

Closing, but please feel free to continue the discussion or reopen if you still need help. You're also welcome to join our [Discord](https://discord.gg/qZmPgTE6RX) and [Slack](https://entgo.io/docs/slack) channels 😎

**Comment by nilpntr** [comment]
On version v0.10.0 the options aren't included yet. Is it possible to create a new release from the current source code so I can use it?

**Comment by a8m** [comment]
> On version v0.10.0 the options aren't included yet. Is it possible to create a new release from the current source code so I can use it?

Hey @nilpntr, you can get the latest master version (it's stable) as follows:

```
go get entgo.io/ent@master  
```

**Comment by nilpntr** [comment]
Thanks!
