### ISSUE TITLE
while  using pulid, if edge field is added into schema, generated code cannot be compiled

### ISSUE THREAD

**Issue by sunil-edu** [ent/ent#2354]
without edge field in schema, everything works fine.  When edge field is added, generate code will no compile.

I followed the example from

https://github.com/ent/contrib/tree/master/entgql/internal/todopulid

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Please refer the my repo, i have 2 tables MstCustomer and MstInst. In MstInst table there is edge field "customer_id". if i remove this field and generate the code, it works fine.   

when compiled i get following error

C:\Users\SUNIL\go\src\test-code>go run start/start.go
# myeduate/ent
ent\mstcustomer_query.go:400:23: cannot use fk (type string) as type pulid.ID in map index
ent\mstinst_create.go:582:20: cannot use nodes[0] (type pulid.ID) as type string in assignment
ent\mstinst_query.go:387:23: cannot use fk (type string) as type pulid.ID in map index
ent\mstinst_query.go:388:17: cannot use fk (type string) as type pulid.ID in append
ent\mstinst_query.go:390:32: cannot use fk (type string) as type pulid.ID in map index
ent\mutation.go:2366:18: cannot use &s (type *string) as type *pulid.ID in assignment
ent\mutation.go:2375:9: cannot use *v (type pulid.ID) as type string in return argument

C:\Users\SUNIL\go\src\test-code>

## Steps to Reproduce 🕹

Yes

https://github.com/sunil-edu/myeduate

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.5  |
| Ent         | 0.10.0   |
| Database    | Postgres   |

**Comment by yonidavidson** [comment]
@sunil-edu can i close this?

**Comment by sunil-edu** [comment]
This is not related to graphql.

**Comment by crossworth** [comment]
Hello, I think you need to change the `field.String("customer_id")` from `mst_inst.go` (ent schema) to `field.String("customer_id").GoType(pulid.ID(""))`.

I pretty sure that the FK must MATCH the PK type.

**Comment by sunil-edu** [comment]
@crossworth  Thank you. I am able to compile the generated code.  Please close this issue

**Comment by sunil-edu** [comment]
I am able to compile the generated code. Please close this issue
