### ISSUE TITLE
entproto.Service(): 🐛 Error codegen field type Inet & field name conflict with golang keyword (eg. type)

### ISSUE THREAD

**Issue by luthfimasruri** [ent/ent#2383]
`entproto.Service()`: Error codegen field type `Inet` & field name conflict with golang keyword (eg. `type`)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

**Error type `Inet`:**
```
var nasNasipaddress schema.Inet
cannot use nasNasipaddress (variable of type "mify_api_radius/ent/schema".Inet) as *"mify_api_radius/ent/schema".Inet value in argument to m.SetNasipaddresscompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#IncompatibleAssign)
```
**Error field name `type` (golang keyword):**
```
--entgrpc_out: entpb/entpb_nas_service.go: unparsable Go source: 31:14: expected 'IDENT', found ':=' (and 2 more errors)
```
generated code line `31:14`:
```
   24       // toProtoNas transforms the ent type to the pb type
   25       func toProtoNas(e *ent.Nas) (*Nas, error) {
   26           v := &Nas{}
   27           id := int32(e.ID)
   28               v.Id = id
   29           nasname := e.Nasname
   30               v.Nasname = nasname
   31           type := e.Type
   32               v.Type = type
   33           return v, nil
   34       }
```
## Expected Behavior 🤔

No Errors

## Steps to Reproduce 🕹

Steps:

1. Clone this repo: [https://github.com/luthfimasruri/entproto_service_issues](https://github.com/luthfimasruri/entproto_service_issues)
2. Exec `go generate ./...`

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.8  |
| Ent         | 0.10.1   |

**Comment by a8m** [comment]
Hey @luthfimasruri 👋 

Thanks for reporting this issue. The fix for it should be simple, would you like to contribute it? @rotemtam can help with it.

**Comment by rotemtam** [comment]
Yes, should be an easy fix. @luthfimasruri, if you want to contribute this change I will be happy to support you. WDYT?

I can do it early next week otherwise.
