### ISSUE TITLE
HELP!!!  A question about SQL in entgo~

### ISSUE THREAD

**Issue by JingHonggg** [ent/ent#2384]
Anyone knows how to write dynamic SQL in entgo? Or how to implement this statement "CASE xxxxx WHEN 2 THEN 1 WHEN 3 THEN 1 WHEN 5 THEN 1 END" in ORM Model ?
Thks very much

**Comment by giautm** [comment]
Hello, why you don't do that logic in Go instead?

Btw, Github Issue is not a good place for discussion. You can join our Discord to get help quickly. https://discord.gg/eA7H4XQs

**Comment by JingHonggg** [comment]
> Hello, why you don't do that logic in Go instead?
> 
> Btw, Github Issue is not a good place for discussion. You can join our Discord to get help quickly. https://discord.gg/eA7H4XQs
