### ISSUE TITLE
Add version information to the cli program

### ISSUE THREAD

**Issue by idc77** [ent/ent#2392]
ent cli program should have version information

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

```
$ ent version
ent version 0.10.1
```

## Motivation 🔦

I have ent installed in my path. I can't tell which version it is. Is it an old version, do I have the latest version, it is a custom hash version? I don't know.
Of course I could look at when the binary was built and compare that to the tags of the releases and if it falls in one or other time frame it could be of that version, but maybe it isn't.

The ent cli program should include version information.

Could this maybe be done automatically? I don't know, is Go able to include a sha hash or git tag when building?

**Comment by a8m** [comment]
Hey @idc77 and thanks for proposing this feature to ent.

This command was proposed a few times, but it's already supported by the `go` command. See https://github.com/ent/ent/issues/1828#issuecomment-897823253

> Could this maybe be done automatically? I don't know, is Go able to include a sha hash or git tag when building?

Go 1.18 will add support for version control information using `debug/buildinfo`. It is also going to be added to `go version -m`. 

Closing, but please let me know if you have any question.
