### ISSUE TITLE
What databases are supported?

### ISSUE THREAD

**Issue by ltns35** [ent/ent#2395]
Hi, I would like to know what databases can be used with Ent, previously I've been using it with Postgres and works perfectly, but know I would like to try it with a graph database such as ArangoDB or NEO4J. 

Being Ent a graph oriented orm, it could be good to describe what databases can be used.

**Comment by kataras** [comment]
Hello @ltns35, you can navigate through the available drivers from the [dialect](https://github.com/ent/ent/tree/master/dialect) sub-package of the project. For instance: https://github.com/ent/ent/blob/a27f753bc800ce0a20d3158fc1cdb4d284e9b068/dialect/dialect.go#L18-L23
