### ISSUE TITLE
Atlas migrations add extra unique index on primary keys

### ISSUE THREAD

**Issue by ivanvanderbyl** [ent/ent#2401]
After switching to Atlas for migrations, the first migration added an additional unique index on all `id` fields, even though there is already a primary key index. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Switching to Atlas creates migrations such as:

```sql
CREATE UNIQUE INDEX "users_id_key" ON "users" ("id");
```

When `users` already has a primary key index:

```sql 
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)

```

Resulting in:

```sql
                                         Table "public.users"
       Column       |            Type             | Collation | Nullable |          Default
--------------------+-----------------------------+-----------+----------+----------------------------
 id                 | character varying           |           | not null |
Indexes:
    "users_pkey" PRIMARY KEY, btree (id)
    "users_id_key" UNIQUE, btree (id)
```

## Expected Behavior 🤔

Atlas should recognise the primary key index and not create an additional index.

## Steps to Reproduce 🕹

Usual Ent setup using custom IDs as strings.

```go
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").
			MaxLen(31).
			NotEmpty().
			Unique().
			DefaultFunc(UserIDFunc).
			Immutable(),
        ...
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | `1.18.rc1` |
| Ent         | `master`   |
| Atlas         | `master`   |
| Database    | Postgres   |

**Comment by a8m** [comment]
Thanks for reporting this @ivanvanderbyl and @hehex9 

Fixed with #2425
