### ISSUE TITLE
entoas: Read only annotation

### ISSUE THREAD

**Issue by rolandknight** [ent/ent#2402]
Is there a way to specify a field read only annotation for entoas? Immutable is supported by entoas and generates input params for only POST method but I don't see a way to suppress the POST param (ie for CreatedBy and CreatedAt fields).

**Comment by yonidavidson** [comment]
Hi @rolandknight can we close this issue ?

**Comment by rolandknight** [comment]
yes. The PRs I created for this for entoas and ogent are now merged.
