### ISSUE TITLE
How can I use versioned migrations with `goose`?

### ISSUE THREAD

**Issue by iwata** [ent/ent#2408]
I was excited to read the following article because it was a feature I had been waiting for!
[Announcing Versioned Migrations Authoring \| ent](https://entgo.io/blog/2022/03/14/announcing-versioned-migrations)

It mentions the workflow with `golang-migrate/migrate`, but apart from that, is it possible to work with [goose](https://github.com/pressly/goose)?

`goose` does not separate `Up` and `Down` files; it uses special comments to separate them within a single file. For example, the following code sample.
```sql
-- +goose Up
CREATE TABLE post (
    id int NOT NULL,
    title text,
    body text,
    PRIMARY KEY(id)
);

-- +goose Down
DROP TABLE post;
```

Is it possible to output a migration file in this format?

**Comment by iwata** [comment]
I tried replacing `migrate.DefaultFormatter` with the following code, but the result did not work. The reason is that if you use the same file name for `Up` and `Down`, they will be overwritten and only the `Down` DDL will remain.

```go
var (
	templateFuncs = template.FuncMap{
		"now": time.Now,
		"sem": ensureSemicolonSuffix,
		"rev": reverse,
	}
	gooseFormatter, _ = migrate.NewTemplateFormatter(
		template.Must(
			template.New("").
				Funcs(templateFuncs).
				Parse(`{{now.Format "20060102150405"}}_{{.Name}}.up.sql`),
		),
		template.Must(template.New("").Funcs(templateFuncs).Parse(`-- +goose Up
-- +goose StatementBegin
{{ range .Changes }}{{ println (sem .Cmd) }}{{ end }}
-- +goose StatementEnd
`)),
		template.Must(
			template.New("").
				Funcs(templateFuncs).
				Parse(`{{now.Format "20060102150405"}}_{{.Name}}.down.sql`),
		),
		template.Must(template.New("").Funcs(templateFuncs).Parse(`-- +goose Down
-- +goose StatementBegin
{{ range rev .Changes }}{{ with .Reverse }}{{ println (sem .) }}{{ end }}{{ end }}
-- +goose StatementEnd
`)),
	)
)
```

**Comment by masseelch** [comment]
Hey @iwata, thank you for this question. 

To achieve, what you want you can create a custom `Formatter` so your idea went in the right direction. The `TemplateFormatter` takes an evne number of arguments, the first one being a filename and the second one the template. 

So changing your example to this: 

```go
var (
	templateFuncs = template.FuncMap{
		"now": time.Now,
		"sem": ensureSemicolonSuffix,
		"rev": reverse,
	}
	gooseFormatter, _ = migrate.NewTemplateFormatter(
		template.Must(
			template.New("").
				Funcs(templateFuncs).
				Parse(`{{now.Format "20060102150405"}}_{{.Name}}.sql`),
		),
		template.Must(template.New("").Funcs(templateFuncs).Parse(`-- +goose Up
-- +goose StatementBegin
{{ range .Changes }}{{ println (sem .Cmd) }}{{ end }}
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
{{ range rev .Changes }}{{ with .Reverse }}{{ println (sem .) }}{{ end }}{{ end }}
-- +goose StatementEnd`)),
	)
)
```

should achieve what you need :-) Let me know if you need more help! 

I want to add that example to our docs, would you like to contribute the change?

**Comment by iwata** [comment]
@masseelch 
Thank you for taking the time to share this.

> To achieve, what you want you can create a custom Formatter so your idea went in the right direction. The TemplateFormatter takes an even number of arguments, the first one being a filename and the second one the template.

That makes sense! I retried your code sample and it worked 🎉 

With a few modifications, the final code is as follows (Hyphens were added to eliminate unnecessary line breaks).

```go
var (
	templateFuncs = template.FuncMap{
		"now": time.Now,
		"sem": ensureSemicolonSuffix,
		"rev": reverse,
	}
	gooseFormatter, _ = migrate.NewTemplateFormatter(
		template.Must(
			template.New("").
				Funcs(templateFuncs).
				Parse(`{{now.Format "20060102150405"}}_{{.Name}}.sql`),
		),
		template.Must(template.New("").Funcs(templateFuncs).Parse(`-- +goose Up
-- +goose StatementBegin
{{ range .Changes }}{{ println (sem .Cmd) }}{{ end -}}
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
{{ range rev .Changes }}{{ with .Reverse }}{{ println (sem .) }}{{ end }}{{ end -}}
-- +goose StatementEnd`)),
	)
)
```

There is one inconvenience that I would like to share. The two functions, `ensureSemicolonSuffix` and `reverse`, are unexported and cannot be used as is. It would be nice if they are improved in the future.

> I want to add that example to our docs, would you like to contribute the change?

With pleasure, of course 👍

**Comment by masseelch** [comment]
> That makes sense! I retried your code sample and it worked :tada:
:partying_face: 

> There is one inconvenience that I would like to share. The two functions, ensureSemicolonSuffix and reverse, are unexported and cannot be used as is. It would be nice if they are improved in the future.

That is true. I will change the Atlas internals soon to make sure the statements end with an semicolon, then the above function is no longer needed.

For the second part, `reverse` is a relatively simple functions and I do not think we should export, it. With generics out in the open now, a general reverse function is possible as well and my guess is, that there will be some packages (maybe even std), that provide such functionality soon.

> With pleasure, of course :+1: 

Thanks, I appreciate it! I think a good place is to add a new section under [versioned migrations docs](https://entgo.io/docs/versioned-migrations) and put it there. We can then add more examples for other frequent questions / tools :-) Let me know, if you need help. You can reach out to me on our [Discord](https://discord.gg/qZmPgTE6RX) as well for easy communication.

**Comment by iwata** [comment]
> That is true. I will change the Atlas internals soon to make sure the statements end with an semicolon, then the above function is no longer needed.

That's good news!

> For the second part, reverse is a relatively simple functions and I do not think we should export, it. With generics out in the open now, a general reverse function is possible as well and my guess is, that there will be some packages (maybe even std), that provide such functionality soon.

Agree, generics is truly gospel 👍 

> Thanks, I appreciate it! I think a good place is to add a new section under [versioned migrations docs](https://entgo.io/docs/versioned-migrations) and put it there. We can then add more examples for other frequent questions / tools :-) Let me know, if you need help. You can reach out to me on our [Discord](https://discord.gg/qZmPgTE6RX) as well for easy communication.

Got it.
BTW, I've never noticed this before on that document.
So, this feature is only available on the master branch, right? Or is it still available in v0.10.x?

**Comment by masseelch** [comment]
I think @a8m released a [hotfix version](https://github.com/ent/ent/releases/tag/v0.10.1) 2 weeks ago and versioned migrations was a part of that. However, with Ent you can consider the master branch being stable :+1:

**Comment by iwata** [comment]
@masseelch 

I sent a pull request! Could you review it?
https://github.com/ent/ent/pull/2415

**Comment by masseelch** [comment]
Thanks! I will have a look on Monday 😌

**Comment by fgm** [comment]
One reason why I use goose is its support for both `*.sql` migrations, which you mentioned, and [Go migrations](https://github.com/pressly/goose#go-migrations). Is there a way to support Go migrations too ?

**Comment by masseelch** [comment]
Hey 👋!

Yes, by the looks of it go-migrations are "just" Go code surrounding the SQL statements. Therefore you can once again create a custom `Formatter` to create the desired file format. 

I am not near a computer right now, but I can provide an example formatter later if you need one 😊

**Comment by masseelch** [comment]
@fgm, as I promised: 

```go
var (
		templateFuncs = template.FuncMap{
			"now": time.Now,
			"rev": reverse,
		}
		gooseFormatter, _ = migrate.NewTemplateFormatter(
			template.Must(
				template.New("").
					Funcs(templateFuncs).
					Parse(`{{now.Format "20060102150405"}}_{{.Name}}.go`),
			),
			template.Must(template.New("").Funcs(templateFuncs).Parse(`
package migrations

import (
	"database/sql"

	"github.com/pressly/goose/v3"
)

func init() {
	goose.AddMigration(Up, Down)
}

func Up(tx *sql.Tx) error {
	{{ range .Changes }}
		if _, err := tx.Exec("{{ .Cmd }}"; err != nil 
			return err
		}
	{{ end }}
	return nil
}

func Down(tx *sql.Tx) error {
	{{ range rev .Changes }}
		{{ with .Reverse }}
			if _, err := tx.Exec("{{ . }}"; err != nil 
				return err
			}
		{{ end }}
	{{ end }}
	return nil
}`)),
		)
	)
```

Using a formatter like the above should create a Go migration working with goose. Let me know, if you need any more help :blush:

**Comment by masseelch** [comment]
Closing. Feel free to reach out of any more questions arise!
