### ISSUE TITLE
Using Or predicate for Where condition causes sequential scan

### ISSUE THREAD

**Issue by bionic-ido** [ent/ent#2409]
Using the Or predicate in order to build a query with several different where conditions, causes sequential scans which cause it to be unoptimized and directly linked to how many entries are in the database (rather then using indexes when querying the conditions independently)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using the Or predicate in order to query several different conditions (which on their own would be indexed) (as opposed to querying them separately), We get a sequential scan in the query plan (at least in postgres), which causes the time to increase the more entries are inside the database (without a real limit).
In a case where the database is filled with a ton of entries, this causes a massive difference in performance between separate queries and using the Or predicate.

## Expected Behavior 🤔

I don't know if I would call it expected behavior, but I would ideally want to be able to use the Or predicate without experiencing such a dip in performance, or have an alternative in the Union which currently doesn't exist in ent and is a way to improve the query plan performance (at least in postgres from my manual testing).
We could make it invisible to us using the Or predicate, by adding something just before executing the query, that will be able to identify such conditions that can be transformed into unions:
Unoptimized:
`select * from table1 where table1.id in (select table1_edge1 from edge1 where table1_edge1=0) or table1.id in (select table1_edge2 from edge2 where table1_edge2=0)`
Optimized:
`select * from table1 where table1.id in ((select table1_edge1 from edge1 where table1_edge1=0) union (select table1_edge2 from edge2 where table1_edge2=0))`
Identifying the multiple "id in" with Or between them and changing it into a single one using union.

## Steps to Reproduce 🕹

https://github.com/bionic-ido/ent_or_performance_issue_repo

Steps:

(Use test from the repo I posted :))
1. Fill database with a ton of entries, in a schema that has 2 edges between 2 tables, both of which are indexed (O2M & O2O).
2. Query a set of entries out of the table that is the To side of the O2O & the One side of the O2M.
3. For each of those entries, use 2 queries - 1 for querying the O2M connection out of table2 based on the id of the table1 entry, and the other for querying the O2O connection out of table2 based on the id of table1. This should not take long, as it is an index scan in both cases.
4. For each of the entries in 2, do one query using the Or predicate, getting both the O2M connections & O2O connection of table2 entries based on table 1 id. This will be unoptimized, and the time it will take will depend & increase the more entries we have in the database (sequential scan on table2).

## Your Environment 🌎

I've experienced the bug in front of postgres 12.5. In the test repo, all versions of postgres showed this issue. I did not test it in front of mysql or maria, though it is in the repo so we can check and see if it happens there as well.

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.6  |
| Ent         | v0.10.1   |
| Database    | Postgres   |

**Comment by a8m** [comment]
Hey @bionic-ido, I just went over your repo and it looks like the query can be simplified without joins/sub-queries, but there's one small change you need to do in your schema - expose the foreign keys as fields and then use them as predicates:

```diff
// ent/schema/user.go

        return []ent.Field{
                field.Int("age"),
                field.String("name"),
+               field.Int("member_admin_id").
+                       Optional(),
+               field.Int("lead_admin_id").
+                       Optional(),
        }

 // Edges of the User.
 func (User) Edges() []ent.Edge {
        return []ent.Edge{
                edge.From("member_admin", Admin.Type).
+                       Field("member_admin_id").
                        Ref("team_members").
                        Unique(),
                edge.From("lead_admin", Admin.Type).
+                       Field("lead_admin_id").
                        Ref("team_leader").
                        Unique(),
```

Then, change your query as follows:

```diff
   client.User.Query().
           Where(
                   user.Or(
-                         user.HasLeadAdminWith(admin.ID(dbAdmin.ID)),
-                         user.HasMemberAdminWith(admin.ID(dbAdmin.ID)),
+                         user.LeadAdminID(dbAdmin.ID),
+                         user.MemberAdminID(dbAdmin.ID),
                   ),
           ).
```

**Comment by a8m** [comment]
In some cases, generated predicates can be improved, and users can use [custom predicates](https://entgo.io/docs/predicates/#custom-predicates) to replace them (including UNIONs). However, that's not the case.

I'm going to close this issue, but please feel free to reopen if you still have issues with it, or ping me on our Discord server. Thanks 🙏
