### ISSUE TITLE
Does it support distributed deployment architecture?

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#2413]
Does it support distributed deployment architecture?

**Comment by rotemtam** [comment]
Hi @CNTWDev,

Thanks for reaching out. You asked a broad question, so I will try to describe how Ent fits with general distributed systems/microservices architectures. 

1. Ent serves very well as the data layer for RPC-style microservices. For pretty much all major transport standards, you can use Ent to automatically create CRUD endpoints for gRPC, OpenAPI, and even GraphQL from your data model. If you prefer to write it yourself, the generated API is type-safe and performant (and super fun to work with, honestly). 
2. If you require horizontal-scaling on the data layer itself, Ent recently added support for @PingCAP [TiDB](https://entgo.io/blog/2022/03/17/announcing-preview-support-for-tidb/), which is part of a recent wave of NewSQL databases that take all the great stuff from distributed NoSQL databases and applies them to the guarantees and familiarity of SQL. 

I hope this answers your question. If you want to specify your use case a bit further I'm happy to provide guidance from our experience.

**Comment by a8m** [comment]
Hey @CNTWDev 👋

Thanks for the support @rotemtam! I think we can close this issue.
