### ISSUE TITLE
Can entgo support CRUD operations like gorm, according to the specified structure, now you need your own SetValues every time

### ISSUE THREAD

**Issue by Johnnysfhe** [ent/ent#2419]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by a8m** [comment]
Hey @Johnnysfhe 👋 

This question has already been answered in the issue tracker, please feel free to see my response in https://github.com/ent/ent/issues/1636#issuecomment-859424157

Closing, but please feel free to tag me if you need more help with it.
