### ISSUE TITLE
How can I reuse Set*?

### ISSUE THREAD

**Issue by wirekang** [ent/ent#2426]
```go
func setValues(m *ent.TableNameMutation,v values) {
    m.SetC(v.C)
    m.SetD(v.D)
   // ... 30 lines more
}

func upsertFoo(a,b int, v values) {
    q := TableName.Create()
    q.SetA(a).SetB(b)
    setValues(q.Mutation(),v)
    err := q.OnConflict().Update(
        func (upsert *ent.TableNameUpsert) {
                setValues(upsert.Mutation(), v)   // error, upsert has no Mutaion()
           }
    ).Exec(ctx)
}

```

In my case, I have to update columns (C....) when  index columns(A and B) conflicts.
I want to reuse ```setValues```. Is there common interface between ```ent.*Create``` and ```ent.*Upsert``` ?

**Comment by a8m** [comment]
Hey @wirekang, and sorry for the delayed response. You can use a generic interface to share common setter methods for your builders. For example:

```go
type Setter[T any] interface {
	SetName(string) T
	// ...
}

func SetValues[S Setter[S]](s S) S {
	s.SetName("name")
	// ...
	return s
}

// Use SetValues in *UserCreate and *UserUpsertOne.
SetValues(client.User.Create())
SetValues(client.User.Create().OnConflict())
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.
