### ISSUE TITLE
Nested or condition can not generate sql correct 

### ISSUE THREAD

**Issue by MikyChow** [ent/ent#2434]
Can not generate sql correctly when using nested OR condition

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.
Steps:

code:
```
ands := make([]predicate.MakerOrder, 0)
	for colAddr, tokenIDs := range tokenIDMaps {
		for _, tokenID := range tokenIDs {
			ands = append(ands, makerorder.And(makerorder.CollectionAddressEQ(colAddr), makerorder.TokenIDEQ(tokenID)))
		}
	}
	q = q.Where(makerorder.Or(ands...))
```
## Current Behavior 😯
![image](https://user-images.githubusercontent.com/5389478/160434305-f55c42c3-85f2-4ea0-8d93-c3e594620d46.png)
## Expected Behavior 🤔
(a=1 and b=1) or (a=2 and b=2) or (a=3 and b=3),but now is  ((a=1 and b=1) or (a=2 and b=2)) or (a=3 and b=3)
| Tech        | Version |
| ----------- | ------- |
| Go          | go version go1.17 darwin/amd64  |
| Ent         | 0.10.0   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @MikyChow 👋🏻
Thanks for reporting this. Can you please provide an example with ent/bug to reproduce this? Thanks

https://github.com/ent/bug
