### ISSUE TITLE
Question about multi-table join query

### ISSUE THREAD

**Issue by Mickls** [ent/ent#2436]
I created two tables, one is `base` and one is `base_info`, they are one-to-one related. I want me to return everything from both of their tables in one query, is there any way to achieve this? I looked through all the related issues and couldn't find a corresponding answer, hoping to have a good solution.
My question translated into sql probably needs to implement a one-time query like this
```sql
select * from base left join base_info on base.id=base_info.base_id
```
This is probably the operation in ent
```go
clent.Base.Query().LeftJoin(baseinfo.Table).On(baseinfo.FieldBaseID, base.FieldID).Where(xxx).Select(xxx).Scan(xxx)
```

**Comment by yonidavidson** [comment]
Hi @Mickls,
I think what you are looking for is [eager-load](https://entgo.io/docs/eager-load)
for your case you can do:
```go
bases, err := client.Base.
    Query().
    WithBaseInfo().
    All(ctx)
```

**Comment by Mickls** [comment]
> Hi @Mickls, I think what you are looking for is [eager-load](https://entgo.io/docs/eager-load) for your case you can do:
> 
> ```go
> bases, err := client.Base.
>     Query().
>     WithBaseInfo().
>     All(ctx)
> ```

Thanks a lot for your help, it's useful.

**Comment by CNTWDev** [comment]
withxxxx is used to one-to-one releated model?

**Comment by yonidavidson** [comment]
> withxxxx is used to one-to-one releated model?

It should, it's a one-to-one edge right?
