### ISSUE TITLE
support golang 1.18 workspaces

### ISSUE THREAD

**Issue by xmlking** [ent/ent#2438]
in workspace enabled repo
```
 $ go generate ./ent                                                                                                                                                                                           ☸ rancher-desktop on ☁️  
go: -mod may only be set to readonly when in workspace mode, but it is set to "mod"
        Remove the -mod flag to use the default readonly value,
        or set GOWORK=off to disable workspace mode.
```

**Comment by capyun** [comment]
oh，i have this error too!!!
when i run "go work init"

**Comment by masseelch** [comment]
You can change the line in `ent/generate.go` and remove or edit the `-mod` flag. It should work then. 

Let me know if you need more help.

**Comment by masseelch** [comment]
We support 1.17 and 1.18. Therefore no generics in Ent and no workspaces (imo).

**Comment by jordanrule** [comment]
Thanks this fixed the problem for me.

**Comment by masseelch** [comment]
Closing then. If anyone has trouble with something similar, please open a new issue.
