### ISSUE TITLE
Support Atlas HCL as a schema and code generation source

### ISSUE THREAD

**Issue by Southclaws** [ent/ent#2445]
I was reading about the new Atlas support and love Atlas - it feels like the missing part to fully replace the [dearly departed Prisma](https://github.com/prisma/prisma-client-go/issues/707) in the Go ecosystem.

I checked the blog post and docs and issues and could only find information referring to using Atlas as the migration engine. I would also like to see the schema definition language supported in Ent too.

The reason for this is, while I love declarative schemas, I find Go code a little too procedural/explicit and less declarative than a dedicated DDL like Prisma's schema language or Atlas' HCL based schemas.

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I'm not entirely sure but something along the lines of using the schema as a source to the code generation tool.

```
//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate atlas.hcl
```

Would, instead of using the regular Go code schema would load up the Atlas schema DDL and use that to generate code.

While I don't know anything about Ent's internals, I would imagine this isn't super complex - it would be a matter of mapping Atlas' AST to the Ent data model IR before running the rest of the normal code generation procedures.

## Motivation 🔦

The massive benefit here is generating a schema from an existing database easily using Atlas then using that schema to generate code.

One of the major issues I've seen with a lot of database tooling is they assume you're starting from scratch. Most real-world use-cases are existing large and complex codebases/data models looking for better tooling to increase productivity. I've got a few projects using Prisma, raw SQL and SQLBoiler that would all benefit from switching to Ent but the process of manually writing a schema to match my database is a lot of work. I did speed this up a bit by writing [Prisment](https://github.com/Southclaws/prisment) (which the Prisma Golang community may be using to migrate to Ent)

A more declarative HCL syntax is easier to read for DBAs and non-Go engineers. The benefit of being purely declarative with no possibility for writing logic into the source code means simpler schemas with no surprises (albeit less powerful - though the option of using either is great)

**Comment by janimo** [comment]
Does https://github.com/ariga/entimport help? It predates the use of Atlas though.

https://entgo.io/blog/2021/10/11/generating-ent-schemas-from-existing-sql-databases/

**Comment by rotemtam** [comment]
hey @Southclaws 
Thanks for writing this, this is such a cool question and an interesting direction. Let me just highlight that the Ent schema and the Atlas DDL operate at different layers of abstraction. Ent deals with nodes (with fields) and edges, and Atlas deals (currently) with SQL tables, schemas columns etc. 

So while you can capture any Ent schema in Atlas, you can't go the other way around. As you can see from `entimport` not all use cases are covered, and some _cannot_ be covered. For example, Ent requires that tables have a Primary Key, and Atlas does not, Ent can work with Graph databases, Atlas (currently) does not, and when it will, the DDL resources will be different.

I understand exactly how you feel about Go as being the language powering the Ent DSL, but there are a lot of powerful features in Ent that cannot be (currently) achieved in the Atlas DDL - e.g Hooks, Validation functions, privacy policies etc.

**Comment by Southclaws** [comment]
Yeah this distinction makes sense, the power you get from Ent schemas is very useful for large complex projects.

I guess I'm just on a quest to fill the gap left by Prisma - which has super nice UX and a really simple way to do things. 

> So while you can capture any Ent schema in Atlas, you can't go the other way around. 

I understand this and it makes sense. I think there are use cases where the simplicity of a purely declarative schema can go a long way. Ent schemas are powerful and give you lots of flexibility, but it's a lot of writing for simple things. One of my smaller projects uses Ent and it's awesome, but I don't make use of any of the other features, I just think it's the best schema-first codegen tool out there now so it's my default.

Perhaps (this might sound crazy) an Atlas schema can generate an Ent schema, run migrations etc. in one command. I've been experimenting with possible workflows (again, trying to replicate the UX of Prisma) here: https://github.com/Southclaws/storyden/blob/main/cmd/generate/main.go and using Ent as a library is definitely really helping here!

Thanks for the explanation though, I understand why it might not be a priority to consider something like this in the main Ent repo/toolchain. I've got some more ideas around CLI and migration which I may open another issue for, loving the direction to use Ariga's Atlas migration tooling in Ent anyway!
