### ISSUE TITLE
Edges O2O how to set foreign key and local key

### ISSUE THREAD

**Issue by loktarjugg** [ent/ent#2449]
in following struct,   how can I set the foreign key and local key of the association？

the relationship:
Link -> User O2O
User -> Link O2M

```go
User {
    Id uint64
    MobileNumber
}

Link {
   Id uint64
   MobileNumber
}

```

**Comment by a8m** [comment]
Hey @loktarjugg 👋 
Are the `Link->User` and `User->Link` the same relationship? If so, it needs to be `O2M` and `M2O`. A user has many links, and a link has only one user. Let me know if I'm correct and I can help with this example.

**Comment by loktarjugg** [comment]
@a8m  thanks for your reply, they are not exactly the same

the `User->Link` is O2M
the `Link->User` is O2O

actually, in this example, I want to achieve the relationship between`User.MobileNumber ` and `Link.MobileNumber `
in other words, I need assignable foreign and associative keys

**Comment by yonidavidson** [comment]
@loktarjugg , have you considered using a [validation hook](https://entgo.io/docs/hooks)?

**Comment by loktarjugg** [comment]
> @loktarjugg，您是否考虑过使用[验证钩子](https://entgo.io/docs/hooks)？

hooks might be another approach, but I just want to use the relationships
