### ISSUE TITLE
Can't generate entpb.pb.go and entpb_..._service.go

### ISSUE THREAD

**Issue by luthfimasruri** [ent/ent#2450]
Can't generate `entpb.pb.go` and `entpb_..._service.go` files

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I run `go generate ./ent`:
Didn't generate `entpb.pb.go` and `entpb_..._service.go` files

But when I run `go generate ./...` there's an error:
```
2022/04/06 10:29:26 internal error: package "context" without types was imported from "entgo.io/ent"
--entgrpc_out: protoc-gen-entgrpc: Plugin failed with status code 1.
ent/proto/entpb/generate.go:2: running "protoc": exit status 1
```
## Expected Behavior 🤔
Generate `entpb.pb.go` and `entpb_..._service.go` files

## Steps to Reproduce 🕹

https://github.com/luthfimasruri/generate_entproto

Steps:

1. run `go generate ./ent` or `go generate ./...`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18 |
| Ent         | 0.10.1  |

**Comment by rotemtam** [comment]
Thanks for reporting this! I'll take look at it.

**Comment by rotemtam** [comment]
This seems to be somehow related to `go1.18`, some recent changes to `ent/contrib` should resolve. 

Can you check if upgrading to the latest `ent/contrib` and installing the latest version of `protoc-gen-entgrpc` helps? 

```shell
go get entgo.io/contrib@master
go install entgo.io/contrib/entproto/cmd/protoc-gen-entgrpc
```

**Comment by luthfimasruri** [comment]
It works after upgrading `ent/contrib` to the latest version.
Thanks for your help

**Comment by luthfimasruri** [comment]
Any update on this issue:
https://github.com/ent/ent/issues/2383
