### ISSUE TITLE
Use "Policy" as a schema name

### ISSUE THREAD

**Issue by gitlawr** [ent/ent#2452]
Creating a "Policy" schema results in the following error:
```
entc/gen: create type Policy: schema name conflicts with ent predeclared identifier "Policy"
```

The word seems to be common and legit for a model name. Is there a way to workaround the conflict?

**Comment by CNTWDev** [comment]
reserved word

**Comment by gitlawr** [comment]
I am wondering if we can revisit the word reservation and use ent specific words for internal schemas. Like https://github.com/ent/ent/issues/448

**Comment by a8m** [comment]
Hey @gitlawr 👋 

As mentioned by @CNTWDev, `Policy` is a built-in type in both `entgo.io/ent` and the generated code. I don't have a simple workaround to suggest you besides naming your ent/schema differently and using the `entsql.Annotation` to name the SQL table `policies` in the database. 

```go
func (T) Annotations() []schema.Annotation {
    return []schema.Annotation{
        entsql.Annotation{Table: "policies"},
    }
}
```

See: https://entgo.io/docs/schema-annotations/#custom-table-name

Closing this issue, but please feel free to reopen or join our [Discord](https://discord.gg/qZmPgTE6RX) if you still have questions.
