### ISSUE TITLE
Allow for CGO-less sqlite dialect

### ISSUE THREAD

**Issue by wagoodman** [ent/ent#2460]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

(_The closest issue is https://github.com/ent/ent/issues/456 , as it mentions alternatives to the current sqlite implementation, but is not the exact same feature being requested._)

## Summary 💡

Today there is a `sqlite3` dialect which depends on https://github.com/mattn/go-sqlite3 (which needs CGO). There is another [`database/sql`](https://pkg.go.dev/database/sql) implementation, https://github.com/glebarez/go-sqlite , which does not require CGO 🎉 . It looks like I could not use `glebarez/go-sqlite` with a side-effect import like is done today with the `mattn/go-sqlite3` lib --I didn't investigate further as to why, but if I missed something at least a documentation update + a dilect addition (the registered dialect name is `sqlite` not `sqlite3`) would be very helpful 🙏 .

## Motivation 🔦

For folks wanting to use ent + sqlite but cannot use CGO, this would be a game changer (also should speed up builds for folks that switch from the CGO'd dependency today to the CGO-less one).

**Comment by gedw99** [comment]
Big big +1 

No cgo is a big win . 

it should also work fine on mobiles .

Based on the repo history and readme it looks like it’s a ongoing project t that will not drop dead .

**Comment by gedw99** [comment]
@wagoodman jave you used this ? Is it decent ? Saw very few issues and so hard to know if this is a stable code baae.

**Comment by wagoodman** [comment]
https://github.com/glebarez/go-sqlite is a `database/sql` wrapper for https://github.com/glebarez/go-sqlite , I've used the `gorm/driver` wrapper https://github.com/glebarez/sqlite in the anchore/grype project. All of these are small wrapper/adapter repos for the [upstream `modernc.org/sqlite` library](https://gitlab.com/cznic/sqlite) where all of the sqlite go implementation is. It looks like these `glebarez/*` wrappers were created last december, but the underlying `modernc.org/sqlite` lib is ~4 years old. 

As for tests, https://github.com/glebarez/sqlite (which wraps https://github.com/glebarez/go-sqlite , which wraps `modernc.org/sqlite`) is covered by all of GORMs 11,860 tests, which doesn't include the upstream tests found in `modernc.org/sqlite`.

**Comment by gedw99** [comment]
Thanks that’s really useful ..

interesting benchmarks . On “quasi average” the cgo free is about 30% slower than traditional SQLite ( cgo ). 

I was hoping the lack of cgo would speed things up , but i guess the cgo free SQLite is not so optimised due to the transcoding

**Comment by wagoodman** [comment]
>  On “quasi average” the cgo free is about 30% slower than traditional SQLite ( cgo ).

That makes sense --the main benefit for me is really the simplification of dependencies.

**Comment by wagoodman** [comment]
I went looking for issues in the repo without luck, but didn't look at discussions. Apparently there is a wrapper already that wraps the same `modernc.org/sqlite` implementation mentioned here on discussion https://github.com/ent/ent/discussions/1667

**Comment by gabemeola** [comment]
For google, a simplified version:

```go
package client

import (
	"database/sql"
	"fmt"
	"lib/api/db/ent"
	_ "lib/api/db/ent/runtime"
	"modernc.org/sqlite"
)

func init() {
	sql.Register("sqlite3", &sqlite.Driver{})
}

func OpenClient() (*ent.Client, error) {
	client, err := ent.Open("sqlite3", "file:./ent.db?_pragma=foreign_keys(1)&_pragma=journal_mode(WAL)")
	if err != nil {
		return nil, fmt.Errorf("error opening db: %w", err)
	}
	return client, nil
}
```
