### ISSUE TITLE
how can i order the MOM edge？

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#2463]
Dear,

When i create MOM edge, ent help me to create relation table to store the entity relation.

how can i  order the relation by creation time?

thanks

**Comment by CNTWDev** [comment]
@a8m 
Thanks a lot.

**Comment by CNTWDev** [comment]
Found a seemingly useful scheme to combine the primary key by field.ID.
But Field.ID reports an error.

**Comment by yonidavidson** [comment]
Hi @CNTWDev can https://entgo.io/docs/paging#edge-ordering help you?

**Comment by yonidavidson** [comment]
Hey @CNTWDev, any updates on the issue? Was using edge-ordering helpful for you?

**Comment by CNTWDev** [comment]
yeah, MOM model doesn't create create_at field to order by create_at..
so, how dos the offset works in edge?

**Comment by a8m** [comment]
> When i create MOM edge, ent help me to create relation table to store the entity relation.

[Edge schema](https://entgo.io/docs/schema-edges#edge-schema) (was added a few months ago) should solve this issue. Please, let me know if I can close this one. Thanks 🙏

**Comment by a8m** [comment]
Hey Charlie!

It looks like the issue was resolved. Please, feel free to reopen if you need help with this 😃
