### ISSUE TITLE
Is it possible to set table name for the relation table in m2m2type situation

### ISSUE THREAD

**Issue by ThanksSirAlex** [ent/ent#2469]
For example I've already got a relation table named `user_group_relation` and I want to use it directly. Is there any way to set it in Edges function?

**Comment by a8m** [comment]
Hey @ThanksSirAlex 👋 
You can use the [edge.StorageKey](https://entgo.io/docs/schema-edges/#storagekey) option to control the name of the join-table. 

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you need more help with this.
