### ISSUE TITLE
entproto - Support for M2M Same Type Edges

### ISSUE THREAD

**Issue by sneakykiwi** [ent/ent#2476]
Currently there is no support (or error handling) for generating proto messages that contains [M2M Same Type ](https://entgo.io/docs/schema-edges#m2m-same-type) edges.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Currently what happens is that you get an error that looks like this
```
entproto: failed generating protos: entproto: failed parsing ent graph: file "entpb\\entpb.proto" included an unresolvable reference to "User"
```

This error is caused by the fact that there is no possible way to self reference a proto message inside itself. 

i.e. this is impossible:
```proto
message User {
  repeated User followers = 1;
  repeated User following = 2;
}
```

## Expected Behavior 🤔

After taking some time to figure out that a potential solution could be that when the edge is identified as M2M Same Type it uses a different generation pattern, something that looks like this:

```proto
message User {
  repeated user_followers followers = 1;
}

message user_followers {
  User user = 1;
}
```

In a template format it should look like this:

```proto
message {SchemaName} {
 repeated {SchemaName}_{FieldName} = {FieldNumber};
}

message {SchemaName}_{FieldName} {
  {SchemaName} {SchemaName} = 1;
}
```

Some drawbacks that this method has:

- Increases protobuf and generated codebase size significantly.
- Weird naming, might confuse developers who are utilizing the api instead of building it

## Steps to Reproduce 🕹

Steps:

1. Create new ent project
2. Write a M2M Same type edge for a schema
3. Add appropriate entproto annotations
4. Try to compile 

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18 |
| Ent         | 0.10.1   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by rotemtam** [comment]
hey @sneakykiwi,

I will into this issue a bit deeper but just wanted to point out that there's no problem in doing something like this in proto:
```protobuf
syntax = "proto3";

package selfref;

option go_package = "rotemtam.com/selfref";

message Hello {
  repeated Hello hello = 1;
}
```

Running:
```
protoc --go_out=. --go_opt=paths=source_relative -I . self.proto
```
Works fine, e.g the file `self.pb.go` contains:
```go
type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello []*Hello `protobuf:"bytes,1,rep,name=hello,proto3" json:"hello,omitempty"`
}
```

**Comment by rotemtam** [comment]
Further checking, M2M same type works fine:

```go

type Person struct {
	ent.Schema
}

func (Person) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Annotations(entproto.Field(2)),
	}
}

func (Person) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("following", Person.Type).
			Annotations(
				entproto.Field(3),
			).
			From("followers").
			Annotations(
				entproto.Field(4),
			),
	}
}

func (Person) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(),
		entproto.Service(),
	}
}
```
Result:
```protobuf

message Person {
  int64 id = 1;

  string name = 2;

  repeated Person followers = 4;

  repeated Person following = 3;
}
```
Same for gRPC and the service code.

Guessing you hit some other issue, happy to help you debug in a separate issue or on Discord.

Closing this for now.
