### ISSUE TITLE
entproto: service Get - unreachable code

### ISSUE THREAD

**Issue by thmeitz** [ent/ent#2479]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I've created a proto service with `entproto`. The `func (svc *<Entity>Service) Get(ctx context.Context, req *Get<Entity>Request) (*<Entity>, error) {` in file `entpb_<Entity>_service.go` method contains unreachable code.
```go
switch {
	case err == nil:
		return toProtoServer(get)
	case ent.IsNotFound(err):
		return nil, status.Errorf(codes.NotFound, "not found: %s", err)
	default:
		return nil, status.Errorf(codes.Internal, "internal error: %s", err)
	}
	return nil, nil // <-- this line is not reachable
}
``` 

## Expected Behavior 🤔

correct code without warnings

## Steps to Reproduce 🕹

Steps:

1. generate a simple service
2. look at the last line of the Get method... 

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | v0.10.1   |
| Ent contrib| v0.2.0|

**Comment by rotemtam** [comment]
Thanks, @thmeitz for opening this issue. 

Do you want to send a fix to this issue? It should be fairly simple to fix.

**Comment by thmeitz** [comment]
done

**Comment by rotemtam** [comment]
@all-contributors please add @thmeitz for code and docs
