### ISSUE TITLE
How to extend models and builders with a custom method

### ISSUE THREAD

**Issue by kpeu3i** [ent/ent#2492]
Hi, guys! I'm going to extend my model with a custom method, also I want to have a custom Setter method.

I found these two topics in the FAQ section:
https://entgo.io/docs/faq/#how-to-extend-the-generated-models
https://entgo.io/docs/faq/#how-to-extend-the-generated-builders

But unfortunately, they did not help me to solve my issue.
The first example (about generated models) shows how to add a field but not a method. Moreover, seems like this example is broken:

![image](https://user-images.githubusercontent.com/4928584/164891515-e7e4e4db-2c6d-42ee-bf21-55c192ce74d6.png)

The second topic (about External Dependency Injection) does not give an idea of how to add a custom Setter method.

I'm new to using the Ent framework and maybe I'm doing something wrong. But I guess it would be nice to have step-by-step examples for such common cases as extending models with the custom logic (methods) and defining custom setters.

Could you please assist me with my particular cases?

**Comment by floatyun** [comment]
unfortunately, I'm having this issue as well, and it still doesn't seem like there's a reply.
