### ISSUE TITLE
versioned-migration does not provide NamedDiff

### ISSUE THREAD

**Issue by Southclaws** [ent/ent#2493]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The docs describe a workflow for naming migrations, which is pretty standard workflow and required in order for golang-migrate to work properly: https://entgo.io/docs/versioned-migrations#use-a-custom-formatter

## Expected Behavior 🤔

There's no `NamedDiff` or any other API I can find to name a plan for the `migrate.Formatter` API `Format`. I have to manually add a name to the generated files before running golang-migrate.

**Comment by masseelch** [comment]
The code generator should generate a `NamedDiff()` for you that you can use to set the name. You can extend the code to generate the file to use a flag so you can pass in a name, e.g.: 

```go
if err := m.NamedDiff(context.Background(), os.Args[1], tbls...); err != nil {
	log.Fatalln("diff:", err)
}
```

**Comment by Southclaws** [comment]
> the code generator should generate a NamedDiff()
it doesn't, that's the problem, the docs claim it does though.

> this feature is only available on master
so do the docs represent the latest latest version all the time? shall I just keep ent updated to master branch?

**Comment by rotemtam** [comment]
@Southclaws at Ariga we use Ent on the master branch. Features (and documentation) are updated regularly but tagged releases are much less frequent.

**Comment by Southclaws** [comment]
Thanks, I'll update and keep it on the latest commit!

**Comment by cameront** [comment]
Have you gotten this to work?

My go.mod indicates I'm using ent as of a commit today:

```
require (
...
	entgo.io/ent v0.10.2-0.20220619113432-abefaa7f2468
...
)
```

And I also see that my module cache has the correct template
```
cat ~/go/pkg/mod/entgo.io/ent@v0.10.2-0.20220619113432-abefaa7f2468/entc/gen/template/dialect/sql/feature/migrate_diff.tmpl
...
// NamedDiff creates a named migration file containing the statements to resolve the diff
// between the Ent schema and the connected database.
func (s *Schema) NamedDiff(ctx context.Context, name string, opts ...schema.MigrateOption) error {
    migrate, err := schema.NewMigrate(s.drv, opts...)
    if err != nil {
        return fmt.Errorf("ent/migrate: %w", err)
    }
    return migrate.NamedDiff(ctx, name, Tables...)
}
{{end}}
...
```

But my generated schema still doesn't have that function and I can't figure out why.

**Comment by cameront** [comment]
Gah. 2 seconds after sending I realized I forgot to add the `--feature sql/versioned-migration` to my generate.go. That solved it.
