### ISSUE TITLE
How can i get the random []*ent?

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#2498]
I have a scenario where data is returned randomly when certain conditions are met.
How can i do?

@a8m thx

**Comment by a8m** [comment]
Hey @CNTWDev 👋 

You can provide a custom `ORDER BY` function as follows:

```go
nodes := client.T.
	Query().
	Where( /* Condition goes here. */ ).
	Order(func(s *sql.Selector) {
		// A custom ORDER BY function. Use "RANDOM()" in SQLite.
		s.OrderBy("RAND()")
	}).
	All(ctx)
```


Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎
