### ISSUE TITLE
Postgres schema ignores Default settings for the Time field

### ISSUE THREAD

**Issue by timewarrior** [ent/ent#2501]
I am trying to create a scheme for a project backed up postgres. If a Time field has Default set as time.Now, it is ignored and there is no default value present in the schema.go.

Test database was created manually and had a default set on the date field. The migration removed the default value from the db.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

schema/user.go
```
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age").
			Positive(),
		field.Time("created_at").Default(time.Now).Immutable(),
	}
}
```

migrate/schema.go
```
// UsersColumns holds the columns for the "users" table.
UsersColumns = []*schema.Column{
        {Name: "id", Type: field.TypeInt, Increment: true},
        {Name: "age", Type: field.TypeInt},
        {Name: "created_at", Type: field.TypeTime},
}
```

## Expected Behavior 🤔

migrate/schema.go
```
// UsersColumns holds the columns for the "users" table.
UsersColumns = []*schema.Column{
        {Name: "id", Type: field.TypeInt, Increment: true},
        {Name: "age", Type: field.TypeInt},
        {Name: "created_at", Type: field.TypeTime, Default: time.Now},
}
```

## Steps to Reproduce 🕹

1. Generate for this schema.

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | 0.10.1   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx/v4 | v4.15.0       |

**Comment by yonidavidson** [comment]
Hey @timewarrior, 
`Default(time.Now)` adds a default function to the  generated `Create` Command
This will work as expected since the Default value will be created by the generated code.
For adding the default value also to the schema you can use  `entsql.Annotation`, for example :
```go
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age").
			Positive(),
		field.Time("created_at").
			Default(time.Now).
			Immutable().
			Annotations(&entsql.Annotation{
				Default: "NOW()",
			}),
	}
}
```

This will generate the following schema:
```go
// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime, Default: "NOW()"},
	}
```

**Comment by timewarrior** [comment]
This worked perfectly. Thanks a lot!
