### ISSUE TITLE
ogent - inflection rule MD5 / Uint32-Int32 type mismatch

### ISSUE THREAD

**Issue by thmeitz** [ent/ent#2505]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Case 1:
Schema
```
func (ClientTemplate) Fields() []ent.Field {
	return []ent.Field{field.Uint32("id").StorageKey("template_id"),
....
```
When generating a Uint32 (as shown in the example) the wrong type is generated. Instead of the Uint32 an Int32 is generated.

In the IDEQ predicate (in \<project\>/ent/ogent/ogent.go) I get the following error:
```
cannot use params.ID (variable of type int32) as uint32 value in argument to clienttemplate.IDEQ",
```
```go
func (h *OgentHandler) ReadClientTemplate(ctx context.Context, params ReadClientTemplateParams) (ReadClientTemplateRes, error) {
	q := h.client.ClientTemplate.Query().Where(clienttemplate.IDEQ(params.ID))
.....
``` 
Case 2:
Schema
```go
func (SoftwareUpdate) Fields() []ent.Field {
	return []ent.Field{
		field.Uint32("id").StorageKey("software_update_id"), 
		field.String("update_md5"), 
.....
``` 
generates in `oas_schemas_gen.go`

```go
type SoftwareUpdateUpdate struct {
	ID                 int32                    "json:\"id\""
	UpdateMD5          string                   "json:\"update_md5\""
```

The correct inflection type is not generated in the `responses.go` file.

```go
func NewSoftwareUpdateUpdate(e *ent.SoftwareUpdate) *SoftwareUpdateUpdate {
	if e == nil {
		return nil
	}
	var ret SoftwareUpdateUpdate
	ret.ID = int32(e.ID)
	ret.UpdateMd5 = e.UpdateMd5
```

## Steps to Reproduce 🕹

use schema as defined above.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | latest master   |

**Comment by masseelch** [comment]
Hey @thmeitz, issue one is adressed in https://github.com/ariga/ogent/pull/99.
