### ISSUE TITLE
I wish to add functionality like loading when creating the entity

### ISSUE THREAD

**Issue by TNED** [ent/ent#2508]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I think it's possible to add a function to the create entity.
```
func (pc *PostCreate) LoadPost(p *Post) (*PostCreate) {
    pc.mutation.SetTitle(p.Title).SetName(p.Name)
    return pc
}
```

## Motivation 🔦

Quickly add data replication without repeating Set operations.

**Comment by yonidavidson** [comment]
Hey @TNED, I recommend having a look at the GQL docs at the suggested [template](https://entgo.io/docs/tutorial-todo-gql-mutation-input#go-templates):

Will allow you to write code like this:
```go
func TestUserDefaultValue(t *testing.T) {
	c := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	u := c.User.Create().SetInput(
		ent.CreateUserInput{
			Age:  28,
			Name: "Yoni",
		}).SaveX(context.Background())
	require.Equal(t, "Yoni", u.Name)
	require.Equal(t, 28, u.Age)
}
```

**Comment by TNED** [comment]
I think this is a good solution.
