### ISSUE TITLE
GraphQL Pagination issue - HasNextPage and HasPreviousPage properties are not properly computed

### ISSUE THREAD

**Issue by mortezaalizadeh** [ent/ent#2531]
The generated Paginate function for any entity does not return the correct values for HasNextPage and HasPreviousPage.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Scenario 1:

When only "first" is provided and "after" value is not provided, and "first" is less than the matching number of records in the DB,  hasNextPage is returned as true and hasPreviousPage is returned as false. This is working fine.

Scenario 2:

When "first" is provided and "after" value is set to a cursor that is not the first matching record in DB, and "first" is less than the matching number of items in the DB, hasNextPage is returned as true and hasPreviousPage is returned as false. This is incorrect and hasPreviousPage must be true.

Scenario 3:

When only "last" is provided and "before" value is not provided, and "last" is less than the matching number of records in the DB,  hasNextPage is returned as false and hasPreviousPage is returned as true. This is working fine.

Scenario 4:

When "last" is provided and "before" value is set to a cursor that is not the last matching record in DB, and "last" is less than the matching number of items in the DB, hasNextPage is returned as false and hasPreviousPage is returned as true. This is incorrect and hasNextPage must be true.

## Expected Behavior 🤔

as explained above

## Steps to Reproduce 🕹

The repo I am working on at the moment is Private, but I am pasting the buggy part of the code below:

```go
func (pr *ProjectQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...ProjectPaginateOption,
) (*ProjectConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newProjectPager(opts)
	if err != nil {
		return nil, err
	}

	if pr, err = pager.applyFilter(pr); err != nil {
		return nil, err
	}

	conn := &ProjectConnection{Edges: []*ProjectEdge{}}
	if !hasCollectedField(ctx, edgesField) || first != nil && *first == 0 || last != nil && *last == 0 {
		if hasCollectedField(ctx, totalCountField) ||
			hasCollectedField(ctx, pageInfoField) {
			count, err := pr.Count(ctx)
			if err != nil {
				return nil, err
			}
			conn.TotalCount = count
			conn.PageInfo.HasNextPage = first != nil && count > 0
			conn.PageInfo.HasPreviousPage = last != nil && count > 0
		}
		return conn, nil
	}

	if (after != nil || first != nil || before != nil || last != nil) && hasCollectedField(ctx, totalCountField) {
		count, err := pr.Clone().Count(ctx)
		if err != nil {
			return nil, err
		}
		conn.TotalCount = count
	}

	pr = pager.applyCursors(pr, after, before)
	pr = pager.applyOrder(pr, last != nil)
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	if limit > 0 {
		pr = pr.Limit(limit)
	}

	if field := getCollectedField(ctx, edgesField, nodeField); field != nil {
		pr = pr.collectField(graphql.GetOperationContext(ctx), *field)
	}

	nodes, err := pr.All(ctx)
	if err != nil || len(nodes) == 0 {
		return conn, err
	}

	if len(nodes) == limit {
		conn.PageInfo.HasNextPage = first != nil
		conn.PageInfo.HasPreviousPage = last != nil
		nodes = nodes[:len(nodes)-1]
	}

	var nodeAt func(int) *Project
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Project {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Project {
			return nodes[i]
		}
	}

	conn.Edges = make([]*ProjectEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		conn.Edges[i] = &ProjectEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}

	conn.PageInfo.StartCursor = &conn.Edges[0].Cursor
	conn.PageInfo.EndCursor = &conn.Edges[len(conn.Edges)-1].Cursor
	if conn.TotalCount == 0 {
		conn.TotalCount = len(nodes)
	}

	return conn, nil
}
```

As you see this part of the code sets the values of HasNextPage and HasPrevious page regardless of the the position of cursor. This needs to consider whether there is any matching record before and after the provided cursor.

```go
	if len(nodes) == limit {
		conn.PageInfo.HasNextPage = first != nil
		conn.PageInfo.HasPreviousPage = last != nil
		nodes = nodes[:len(nodes)-1]
	}
```

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.1  |
| Ent         | 0.10.1   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx/v4/stdlib        |

**Comment by a8m** [comment]
Hey @mortezaalizadeh and thanks for opening this issue 👋 

First, I'll suggest you update `ent/contrib` to its latest version, but also join our GraphQL working group/discussion in our [Discord server](https://discord.gg/qZmPgTE6RX).

Regarding the 2 scenarios you mentioned (2 and 4). Let's take the second one as an example (hasPreviousPage` is false) - according to Relay spec, `hasPreviousPage` is set as follows:

> 1. If last is set:
>     - Let edges be the result of calling [ApplyCursorsToEdge](https://relay.dev/graphql/connections.htm#ApplyCursorsToEdges())(allEdges, before, after).
>     - If edges contains more than last elements return true, otherwise **false**.
> 2. If after is set:
>     - If the server can <ins>**efficiently**</ins> determine that elements exist prior to after, return **true**.
> 3. Return **false**.

Hence, I don't see any efficient way to determine if there are elements prior to `after`. Do you have any suggestions?

**Comment by mortezaalizadeh** [comment]
@a8m sorry for my late reply. I have been super busy the last 2~3 weeks. Here is my recommendation and how I patched it in my generated code. Based on below two truth tables:

![image](https://user-images.githubusercontent.com/3070738/170804596-e09ce601-817b-4706-abbd-d3f159d7cd4a.png)

here is how I replaced:

```go
	if len(nodes) == limit {
		conn.PageInfo.HasNextPage = first != nil
		conn.PageInfo.HasPreviousPage = last != nil
		nodes = nodes[:len(nodes)-1]
	}
```

with this:
```go
	if first != nil || after != nil || last != nil || before != nil{
		if first != nil && after != nil{
			conn.PageInfo.HasPreviousPage = true
			conn.PageInfo.HasNextPage = len(nodes) == limit
		} else if first != nil && after == nil{
			conn.PageInfo.HasPreviousPage = false
			conn.PageInfo.HasNextPage = len(nodes) == limit
		} else if first == nil && after != nil{
			conn.PageInfo.HasPreviousPage = true
			conn.PageInfo.HasNextPage = len(nodes) == limit
		} else if first == nil && after == nil{
			conn.PageInfo.HasPreviousPage = false
			conn.PageInfo.HasNextPage = false
		}

		if last != nil && before != nil{
			conn.PageInfo.HasPreviousPage = len(nodes) == limit
			conn.PageInfo.HasNextPage = true
		} else if last != nil && before == nil{
			conn.PageInfo.HasPreviousPage = len(nodes) == limit
			conn.PageInfo.HasNextPage = false
		} else if last == nil && before != nil{
			conn.PageInfo.HasPreviousPage = len(nodes) == limit
			conn.PageInfo.HasNextPage = true
		} else if last == nil && before == nil{
			conn.PageInfo.HasPreviousPage = false
			conn.PageInfo.HasNextPage = false
		}
	}

	if len(nodes) == limit {
		nodes = nodes[:len(nodes)-1]
	}
```

Remember when valid After cursor is provided, HasPrevious is always true and same goes with valid Before cursor

**Comment by mortezaalizadeh** [comment]
@a8m  my only pain now is I need to keep an eye on that generated file to apply my patches manually each time I re-generate the code

**Comment by giautm** [comment]
Sample implement for referrence: https://github.com/graphql/graphql-relay-js/blob/main/src/connection/arrayConnection.ts#L49

**Comment by a8m** [comment]
Thanks for the references @giautm and @mortezaalizadeh. I'm on it and will update soon.

**Comment by mortezaalizadeh** [comment]
@a8m  updated the code snippet above, there was a bug that is fixed now, cheers

**Comment by giautm** [comment]
hey @mortezaalizadeh, you can update the template in entgql to avoid manual patch the generated code.

**Comment by a8m** [comment]
The issue was resolved with https://github.com/ent/contrib/pull/326.

> Remember when valid After cursor is provided, HasPrevious is always true and same goes with valid Before cursor

I indeed rely on this behavior in the [PR](https://github.com/ent/contrib/pull/326.).


>  @a8m updated the code snippet above, there was a bug that is fixed now, cheers

https://github.com/ent/contrib/pull/326 contains 2 lines of changes and many test cases. You're welcome to go over it and let me know if there's something that is covered by the code snippet above and not by https://github.com/ent/contrib/pull/326.

Thanks

**Comment by a8m** [comment]
Closed with https://github.com/ent/contrib/pull/326.
