### ISSUE TITLE
sqltool does not exist when using versioned migration

### ISSUE THREAD

**Issue by Meowzz95** [ent/ent#2536]
Refer to this doc: https://entgo.io/docs/versioned-migrations/
```
// Chose one of the below.
      schema.WithFormatter(sqltool.GolangMigrateFormatter),
      schema.WithFormatter(sqltool.GooseFormatter),
      schema.WithFormatter(sqltool.FlywayFormatter),
      schema.WithFormatter(sqltool.LiquibaseFormatter),
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

sqltool does not exist.
```
go get ariga.io/atlas/sql/sqltool
go: module ariga.io/atlas@upgrade found (v0.3.7), but does not contain package ariga.io/atlas/sql/sqltool
```

## Expected Behavior 🤔

sqltool should exist

## Steps to Reproduce 🕹

Steps:

1. Follow the above doc and try to use `sqltool`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | v0.10.1   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by masseelch** [comment]
Hey @Meowzz95. The package `sqltool` was introduced post Atlas version `0.3.7`. This means you need to have the current master to have that available. If you update Ent to the latest master, it will update Atlas as well and then the package will be available. 

With both Ent and Atlas the master is well tested and can be considered stable. With the release of Ent v0.11.0 soon, this will be fixed as well (I have no ETA though).

**Comment by masseelch** [comment]
I added a note to the docs in #2537.

@Meowzz95 If you have other issues / questions, do not hesitate to ask or re-open this :-)
