### ISSUE TITLE
How to generate sql like "select count(1) as C1, sum(cc) as C2 from tableA" with ent?

### ISSUE THREAD

**Issue by MikyChow** [ent/ent#2543]
Hi team,
    In my issue,I want to query count and sum in 1 request, Does ent support?

**Comment by c2s** [comment]
Yes, when I was in the use of ent is also facing this problem, didn't find relevant documents, Is looking for a solution

**Comment by a8m** [comment]
Hey @MikyChow and @c2s 👋 

You can use SQL modifiers to generate almost any query you need. Please, see https://entgo.io/docs/feature-flags/#custom-sql-modifiers.

```go
var r []struct {
    Count int `sql:"c1"`
    Sum int `sql:"c2"`
}

client.T.Query().
    Modify(func(s *sql.Selector) {
        s.Select(
            sql.As(sql.Count("1"), "c1"),
            sql.As(sql.Sum("cc"), "c2"),
        ),
    }).
    ScanX(ctx, &r)
```


Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this.

**Comment by MikyChow** [comment]
Thanks,That's very helpful.

**Comment by a8m** [comment]
Hey! I just want to update you that the aggregation API was simplified, and you can read about it here https://twitter.com/entgo_io/status/1584091539479080960 and https://entgo.io/docs/aggregate.

Also, here's a small example:

```go
// Aggregate one field.
sum, err := client.Order.Query().
    Aggregate(
        ent.Sum(order.FieldPrice),
    ).
    Int(ctx)

// Aggregate multiple fields.
var v []struct {
    Sum, Min, Max, Count int
}
err := a8m.QueryOrders().
    Aggregate(
        ent.Sum(order.FieldPrice),
        ent.Min(order.FieldPrice),
        ent.Max(order.FieldPrice),
        ent.Count(),
    ).
    Scan(ctx, &v)
```

**Comment by till** [comment]
@a8m I have multiple `SUM()` in my query and I don't seem to be able to map them to a response.

I am using it like so:

```go
var resp []struct {
  CPU float32
  Memory int
  Hdd int
}

client.Usage.Query().
  Where(usage.AppEq("..."), usage.EntityEQ("...").
  Aggregate(
    ent.Sum(usage.FieldCPU),
    ent.Sum(usage.FieldMemoryMB),
    ent.Sum(usage.FieldHddMB)).ScanX(&v)
```

Error:

```
sql/scan: missing struct field for column: SUM(`usage`.`cpu`) (SUM)
```

The generated query is:

```sql
SELECT SUM(`usage`.`cpu`), SUM(`usage`.`memory_mb`), SUM(`usage`.`hdd_mb`) FROM `usage` WHERE `usage`.`app` = ? AND `usage`.`entity` = ?
```

I guess I am missing `SUM(usage.cpu) AS something`?

**Comment by till** [comment]
Got some help via Discord :tada:

Struct tags needed to be there and then I had to use `ent.As()` within the `Aggregate()` func:

```go
var v []struct {
  CPU float32 `sql:"cpu"`
  Memory Int `sql:"memory_mb"`
  Hdd Int `sql:"hdd_mb"`
}

client.Usage.Query().
  Where(usage.AppEq("..."), usage.EntityEQ("...").
  Aggregate(
    ent.As(ent.Sum(usage.FieldCPU), "cpu"),
    ent.As(ent.Sum(usage.FieldMemoryMB), "memory_mb"),
    ent.As(ent.Sum(usage.FieldHddMB), "hdd_mb")).ScanX(&v)
```
