### ISSUE TITLE
Failed to execute go get -d entgo.io/ent/cmd/ent

### ISSUE THREAD

**Issue by Williamzxc1996** [ent/ent#2558]
When I execute go get command in the documentation, I get
```
go get -d entgo.io/ent/cmd/ent
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: github.com/spf13/cobra@v1.3.0 requires
        github.com/spf13/viper@v1.10.0 requires
        github.com/armon/go-metrics@v0.3.10 requires
        github.com/prometheus/common@v0.9.1: verifying go.mod: github.com/prometheus/common@v0.9.1/go.mod: cannot authenticate record data in server response
```
I looked up `github.com/prometheus/common` and it does not have `v0.9.1`. I replaced it with `v0.34.0` and it's working now.

My go version
```
❯ which go
/usr/local/opt/go@1.18/bin/go
```

**Comment by a8m** [comment]
Hey @Williamzxc1996 👋 

I think getting the `@master` version will fix your issue (e.g. `go get entgo.io/ent/cmd/ent@master`) - I just tried this locally and it works. 

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎
