### ISSUE TITLE
how to print SQL statements generated by entgo?

### ISSUE THREAD

**Issue by AlexWIllBeGood** [ent/ent#2559]
Wanna record SQL statement from ENTGO but can't find it in document

**Comment by a8m** [comment]
Hey @AlexWIllBeGood 👋, I just answered this issue on our [Discord server](https://discord.gg/qZmPgTE6RX) this week, so you're welcome to join there.

For your question, something like [`WriteDriver`](https://pkg.go.dev/entgo.io/ent@v0.10.1/dialect/sql/schema#WriteDriver) can do the job here. The [Offline Mode](https://entgo.io/docs/migrate#offline-mode) is actually implemented with it. 

Closing, but please feel free to ping me if you need more help.

**Comment by LF-DevJourney** [comment]
https://github.com/ent/ent/discussions/1692

`client.Debug().User.Query().All(ctx)`
