### ISSUE TITLE
how to import the struct which needs ent  to generate  before ent  generate？

### ISSUE THREAD

**Issue by CooperXJ** [ent/ent#2576]
take a example:
```go
// scheam/adult.go
type Person struct{
      head Head
      body Body
} 

func (Adult) Fields() []ent.Field {
	return []ent.Field{
		field.JSON("person",Person{}),
	}
}

//ent/head.go  ent generated
type Head struct{
      xxxx
} 

// ent/body.go ent generated
type Body struct{
      xxxx
} 
```
the Head and Body which shoud be generated with People together 
if I import the Head or Body struct,it turns out that import cycle not allowed
Is there a good way to solve it?

**Comment by a8m** [comment]
Hey @CooperXJ 👋 

The typical approach for this is to move these structs to a different package that will be imported from both `ent/schema` and the generated `ent` package. 

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help or have questions about it 😎
