### ISSUE TITLE
Through options undefined on Edge

### ISSUE THREAD

**Issue by Faroukhamadi** [ent/ent#2583]
I have an existing database that I'm trying to create the schema for and it has a "User" and "Friendship" table, Found this example in the official docs  [friendships example](https://entgo.io/docs/schema-edges/#edge-schema) and it has a through option that doesn't exist and the go compiler is giving me this error: 
```
edge.To("friendships", User.Type).Through undefined (type *edge.assocBuilder has no field or method Through)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#MissingFieldOrMethod)
```
Am I missing something ?

**Comment by a8m** [comment]
Hey @Faroukhamadi 👋 

Updating to the latest master version should solve your issue. Please, run `go get entgo.io/ent/cmd/ent@master` and then execute go generate again. We'll release a tagged version soon. 

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎
