### ISSUE TITLE
Versioned migrations do not work with GlobalUniqueID

### ISSUE THREAD

**Issue by masseelch** [ent/ent#2587]
Suppose trying to generate versioned migrations files for a global unique id enabled schema: 

```go
client.Schema.Diff(ctx, schema.WithDir(dir), schema.WithGlobalUniqueID(true))
```

will result into the following error:

```text
insert into ent_types: Error 1146: Table 'migrate.ent_types' doesn't exist
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

There is an error.

## Expected Behavior 🤔

A new set of migration files are created that also allocate the correct ranges for the primary keys.

**Comment by masseelch** [comment]
> [...] since I do not wish to have to commit it.

The information has to be stored somewhere. With the interface @giautm proposed (with mine as well) it is relatively easy to change the location from a file in the migration directory (schema directory) to something else like a remote service, a database or in the schema itself. 

What we need to decide is what storage location to support for the offline migrations. 

@bionic-ido As I understood you prefer something schema config related?

**Comment by bionic-ido** [comment]
@masseelch The way we are currently using ent is having the schema definition files be commited into our git, while having a generation script that handles the generation of all the autogenerated files out of it.
I do not wish to have to commit all of the autogenerated files, so I would much prefer the generated ent_types be placed somewhere different\be configured alongside the schema definitions, such that I would still be able to make this distinction.
