### ISSUE TITLE
A `Ping()` method to know if the DB is ready and usable

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2590]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Coming from other ORM/engines I would like to use with Ent too an extremely useful method to ping database.

## Motivation 🔦

What I'm using right now:

```go
import (
  "github.com/uptrace/bun"
  "github.com/uptrace/bun/driver/pgdriver"
)

func New(conn string) *bun.DB {
  sqlDB := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(conn)))

  bunClient := bun.NewDB(sqlDB, pgdialect.New())

  err := Retry(retryPing(bunClient))
  // handle err

  return bunClient
}

func retryPing(bunClient *bun.DB) func() error {
  return func() error {
    err := bunClient.Ping()
    // handle err

    return nil
  }
}
```

I tried to use something easy like `SELECT 1` but I cannot found [methods described here](https://entgo.io/docs/feature-flags/#sql-raw-api) like `ExecContext`:

```go
tx, err := client.Tx(context.Background())
```

**Why?**

**Comment by a8m** [comment]
Hey @frederikhors 👋 

By default, Ent does not support executing raw statements on the database, as it aims to provide a type-safe API that reflects the entities described in the `ent/schema`.

My suggestion is to either do it on the [connection setup](https://entgo.io/docs/sql-integration) (before creating the `ent.Client`), or if you prefer to expose the raw API on the client, make sure you update Ent to the latest master (`go get entgo.io/ent/cmd/ent@master`) and enable the `sql/execquery` feature-flag.

**Comment by frederikhors** [comment]
> My suggestion is to either do it on the [connection setup](https://entgo.io/docs/sql-integration)

It works amazingly well! Thanks.

I'm starting to understand how Ent works.
