### ISSUE TITLE
If I remove the generated files before generation `entc` throws

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2597]
I'm starting to use Ent and I'm trying to organize the code in a way that reflects as much as possible the "clean architecture" structure we already use in the project.

One problem I'm running into right now is that since I use this code to generate:

```go
//go:generate rm -rf ./ent/*
//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ../adapters/ent/schema --target ./ent --feature entql,privacy
```

It first removes all (generated) files from `/ent` dir and then re-generates (the schema files are in another dir).

This works until I start to use some func like the one from [multitenancy example](https://github.com/ent/ent/blob/master/examples/privacytenant), like:

- adapters/common/ent/rule/rule.go:

```go
package rule

import (
	"context"
	"my_project/ent/predicate"
	"my_project/ent/privacy"
	"my_project/ent/tenant"
)

func FilterTenantRule() privacy.QueryMutationRule {
	type TenantsFilter interface {
		WhereHasTenantWith(...predicate.Tenant)
	}

	return privacy.FilterFunc(func(ctx context.Context, f privacy.Filter) error {
		tf, ok := f.(TenantsFilter)
		if !ok {
			return privacy.Denyf("unexpected filter type %T", f)
		}

		tf.WhereHasTenantWith(tenant.ID(VerifyTenantID(ctx)))

		return privacy.Skip
	})
}
```

Then this is the error:

```
go generate ./...

entc/load: ..\adapters\common\ent\rule\rule.go:6:2: package my_project/ent/predicate is not in GOROOT (C:\Program Files\Go\src\my_project\ent\predicate)
..\adapters\common\ent\mixin\mixin.go:4:2: package my_project/ent/privacy is not in GOROOT (C:\Program Files\Go\src\my_project\ent\privacy) ..\adapters\common\ent\rule\rule.go:8:2: package my_project/ent/tenant is not in GOROOT (C:\Program Files\Go\src\my_project\ent\tenant)

exit status 1
ent\generate.go:4: running "go": exit status 1
generate: open C:\project\ent\client.go: The system cannot find the file specified.
```

I'm removing all files because I think this is easier to remove maybe deleted models from schema instead of doing it manually.

Is there no way the generator can understand that those files it doesn't find are going to be generated right after its error?

UPDATE:

After posting this I thought that maybe there is a way but I didn't find it in the docs: **can you automatically delete files that are no longer needed after generation?**

**Comment by a8m** [comment]
> After posting this I thought that maybe there is a way but I didn't find it in the docs: can you automatically delete files that are no longer needed after generation?

I created and used `a8m/entclean` for more than a year and it worked without a problem. I moved this logic to Ent. See https://github.com/ent/ent/pull/2612

Please, update to the latest master and let me know if something is not working correctly with it.

**Comment by frederikhors** [comment]
You make my dreams come true, @a8m. :smile:

I'll try ASAP.

**Comment by frederikhors** [comment]
I can confirm it works.
