### ISSUE TITLE
[DOC] Improve for multi-tenancy using `Tenant` edge or `"tenant_id"` field

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2601]
## Summary 💡

I'm opening this to improve docs about multi-tenancy using `Tenant` edge or `"tenant_id"` field.

## Motivation 🔦

@a8m [suggested me](https://github.com/ent/ent/discussions/2585#discussioncomment-2862957) to use [Privacy Filter Rules](https://entgo.io/docs/privacy/#filter-rules) and I did but with a few issues.

**If you can confirm the code I used is OK** I'll PR to improve docs for (not very smart :smile:) people like me who will come in the future.

## Issues (with fix)

- [ ] I'm using this code for privacy rule (is it OK?):

   ```go
    func (TenantMixin) Policy() ent.Policy {
      return privacy.Policy{
        Query: privacy.QueryPolicy{
          rule.FilterTenantRule(),
        },
        Mutation: privacy.MutationPolicy{
        	rule.FilterTenantRule(),
        },
      }
    }

    func FilterTenantRule() privacy.QueryMutationRule {
      type TenantsFilter interface {
        WhereTenantID(entql.Uint64P)
      }

      return privacy.FilterFunc(func(ctx context.Context, f privacy.Filter) error {
        tf, ok := f.(TenantsFilter)
        if !ok {
          return privacy.Denyf("unexpected filter type %T", f)
        }

        tf.WhereTenantID(entql.Uint64EQ(GetTenantID(ctx)))

        return privacy.Skip
      })
    }
   ```

- [ ] To avoid always using the `.SetTenantID()` method in the `.Create()` I used a hook only for the `OpCreate` like this:

   ```go
   func (TenantMixin) Hooks() []ent.Hook {
     return []ent.Hook{
       hook.On(
         func(next ent.Mutator) ent.Mutator {
           return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
             if s, ok := m.(interface{ SetTenantID(uint64) }); ok {
               s.SetTenantID(GetTenantID(ctx))
             }

             return next.Mutate(ctx, m)
           })
         },
         ent.OpCreate,
       ),
     }
   }
   ```

## Issues (unresolved)

- [ ] If I use `WhereTenantID(uint64)` the type assertion doesn't work, why?

   ```go
    type TenantsFilter interface {
      WhereTenantID(uint64) // this doesn't work, why?
      // WhereTenantID(entql.Uint64P) // this works
    }
   ```

**Comment by a8m** [comment]
The example was improved and the website was updated according to the new changes. Please, see https://entgo.io/docs/privacy#multi-tenancy and https://github.com/ent/ent/tree/master/examples/privacytenant.

Closing
