### ISSUE TITLE
[FR] Log only failed queries

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2604]
## Summary 💡

I would like a way to log only the failed queries, [like Bun has](https://github.com/uptrace/bun/blob/master/extra/bundebug/debug.go#L27).

## Motivation 🔦

Right now I'm using this on/off classic code:

```go
func NewEnt(log_all_queries bool) *ent.Client {
	sqlClient := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(url)))

	drv := entsql.OpenDB(dialect.Postgres, sqlClient)

	client := ent.NewClient(ent.Driver(drv))

	if log_all_queries {
		client = client.Debug()
	}

	return client
}
```

but in production is very useful to read what is the problematic query.

_Thanks._

**Comment by a8m** [comment]
Hey! The `Debug` option was created to provide a convenient way to "debug statements" when working locally. It cannot replace production loggers as it does not cover many use cases.

I suggest you decorate the SQL driver with your own "logging driver" and add these options there - see the [current one](https://github.com/ent/ent/blob/master/dialect/dialect.go#L66-L74) as a reference. I actually did the same thing when I wanted to create a custom zap logger for my Ent projects.

In case of good and stable integration with an external package (e.g. gqlgen or zap), you're welcome to share it with us and we can consider adding it to `ent/contrib`.

**Comment by a8m** [comment]
Closing as there are no action items to take here. Thanks 🙏
