### ISSUE TITLE
What could be the cause of "entc/load: load schema dir: missing package information for: ./ent/schema"

### ISSUE THREAD

**Issue by micktor** [ent/ent#2611]
<img width="935" alt="Screen Shot 2022-06-04 at 10 59 05 PM" src="https://user-images.githubusercontent.com/15118016/172037629-a49e653f-6c48-4972-a134-9c47386e6211.png">

**Comment by micktor** [comment]
go version go1.18.3 darwin/arm64
ent@latest

**Comment by a8m** [comment]
Hey @micktor 👋 

Can you paste here the output of `tree ./ent`? You must have at least one schema file in `ent/schema`. Please, try to use the `init` command to set up your environment.

**Comment by micktor** [comment]
I had a file in it using `init` but it still failed. Eventually I deleted the folder and regenerated everything, works now! Thanks @a8m
