### ISSUE TITLE
Feature flag `sql/execquery` is not present using entc as package

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2616]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Feature flag `sql/execquery` is not present using entc as package:

![image](https://user-images.githubusercontent.com/41120635/172122377-22f57034-74a7-48b3-be73-c0d452963839.png)

## Expected Behavior 🤔

It is present.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.3  |
| Ent         | 0.10.1  |

**Comment by a8m** [comment]
Hey! Please, update Ent to the latest master using `go get entgo.io/ent/cmd/ent@master` and report if you still face this issue. Thanks

**Comment by frederikhors** [comment]
![image](https://user-images.githubusercontent.com/41120635/172123774-a6e7b6cc-0295-4292-8a97-1698d8e02e7c.png)

With this works now! Thanks.

**Comment by a8m** [comment]
You should upgrade `ent/contrib` version as well if you work with gqlgen 😉

**Comment by frederikhors** [comment]
Ok. I do not like to be on edge (master branch); I have been for years and now I would like some stability. Can you tell me when both packages will stabilize? With v0.11.0?

**Comment by frederikhors** [comment]
Updated contrib.
