### ISSUE TITLE
Is it possible today to navigate the schema?

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2622]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I would like to navigate the schema (to further generate other code from there).

## Motivation 🔦

Using `contrib/schemast` I could not, right?

![image](https://user-images.githubusercontent.com/41120635/172185473-a804fb75-fff6-4990-91fb-3c02d5be0cbd.png)

I would like to have methods such:

```go
var fields []schemast.Field

fiels := schemaAstLoaded.Fields()
```

to range on it and do something custom...

**Is it possible today?**

`entgo.io/contrib v0.2.1-0.20220601200333-78aa88292a62`

**Comment by frederikhors** [comment]
Yeah.

But is there a way to read schema to AST?

I do not need to use extensions because my process is external to Ent.

**Comment by a8m** [comment]
See the first example I mentioned above. Working with AST package(s) is used to edit schema files, not read them. 

```go
graph, err := entc.LoadGraph(path, &gen.Config{})
if err != nil {
	log.Fatalln(err)
}
for _, n := range graph.Nodes {
	// ...
}
```

**Comment by frederikhors** [comment]
It works. Thanks.
