### ISSUE TITLE
Confusing instructions for "Migration To Edge Fields​"

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2625]
I think the instructions on this section are quite confusing or they don't respect what happens (at least with versions: `entgo.io/contrib v0.2.1-0.20220601200333-78aa88292a62`, `entgo.io/ent v0.10.2-0.20220606082056-dd4519f935a6`).

![image](https://user-images.githubusercontent.com/41120635/172367586-9d24efb4-14ef-4784-85fd-f353f345dfe3.png)

If I use what you say:

```go
func (Player) Fields() []ent.Field {
  return []ent.Field{
    field.String("name"),
    field.Int("author_id"),
  }
}

func (Player) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("author", User.Type).
      Field("author_id").
      StorageKey(edge.Column("player_author")).
      Unique().
      Required(),
  }
}
```

I'm still getting the column `player_author` instead of `author_id`.

**Comment by a8m** [comment]
The comment in https://github.com/ent/ent/issues/548#issuecomment-643636090 explained the motivation for this naming. The section about "migration to edge fields" describes how to migrate to this feature for applications that didn't use it before, have tables in the existing database, and want to point an existing column (with an old name) to the new struct field with a different name (can be any name). 

In your case, you can omit the `edge.Column` option.

**Comment by frederikhors** [comment]
I'm using this code instead to get the `author_id`.

```go
func (Player) Fields() []ent.Field {
  return []ent.Field{
    field.String("name"),
    field.Int("author_id"),
  }
}

func (Player) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("author", User.Type).
      Field("author_id").
      Unique().
      Required(),
  }
}
```

**Is it correct?**
