### ISSUE TITLE
entgql: mixed id types must be type string or implement the graphql.Marshaller/graphql.Unmarshaller interfaces

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2638]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Can I ask you why this error is happening on my project?

```
running ent codegen error="execute template \"client\": template: node.tmpl:377:16: executing \"client/fields/additional\" at <gqlIDType (filterNodes $.Nodes (skipMode \"type\")) $.IDType>: error calling gqlIDType: entgql: mixed id types must be type string or implement the graphql.Marshaller/graphql.Unmarshaller interfaces"
```

I'm trying to have some entities with `id` `Uint64` and others with `id` `String` and I'm trying to use `entgql`.

The `uint64` with default:

```go
IDType: &field.TypeInfo{Type: field.TypeUint64},
```

The `string` one with code like:

```go
field.String("id").NotEmpty().Unique().Immutable(),
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.3  |
| Ent         | entgo.io/contrib v0.2.1-0.20220601200333-78aa88292a62, entgo.io/ent v0.10.2-0.20220606082056-dd4519f935a6   |
| Database    | PG   |
| Driver      | pgdriver        |

**Comment by frederikhors** [comment]
I updated with the code I'm using.

This is REALLY a blocking issue for use right now. We are mixed ids because the DB is like this now unfortunately. We need to adapt to the DB.

Can you find the reason for this error? Do you already know how to fix it? Is it a quick thing?

Can you tell me how to work-around?

**Comment by frederikhors** [comment]
This and https://github.com/ent/ent/discussions/2631 are blocking our migration from Bun. So sad 😢

**Comment by a8m** [comment]
> This is REALLY a blocking issue for use right now. We are using mixed ids because the DB is like this now unfortunately. We need to adapt to the DB.
> 
> Can you find the reason for this error? Do you already know how to fix it? Is it a quick thing?

As described in the returned error, I'm pretty sure you can wrap your integer type with a custom type that implemented the `graphql.Marshaler` interface (you can use the standard gqlgen ones). 

> This and https://github.com/ent/ent/discussions/2631 are blocking our migration from Bun. So sad 😢

I didn't see it yet tbh. I'll give it a look later.

**Comment by crossworth** [comment]
Hello @frederikhors, I'm pretty sure [this example](https://github.com/giautm/workspace-entgo/blob/1a8231e5841889dba35dc1c97cacc8ee1066853b/ent/schema/pulid/pulid.go#L35) from @giautm should help you get started.

**Comment by a8m** [comment]
Thanks, @crossworth ❤️.

I think this example can also help - https://github.com/ent/contrib/pull/332. The `entgql/internal/todogotype` package contains multiple node types with different ID types and most of them implement the `graphql.Marshaller` interface.

I think we can support this use case without custom implementation btw, it will just make the codegen a bit messy, but it will work.

**Comment by frederikhors** [comment]
@crossworth @a8m thank you both.

I think I convinced the team to use strings for each ID, even though your suggestion worked.

I am also considering the use of ULID (since UUID 6,7,8) are still in RFC.

I would like to ask you if you know what the prefix that @giautm is using here is for: https://github.com/giautm/workspace-entgo/blob/main/ent/schema/pulid/mixin.go#L25.

**Comment by giautm** [comment]
It's called prefixed ULID, you can see the example in contrib repo: https://github.com/ent/contrib/blob/bea889a722a805cf78e25ebb939cc10636558d82/entgql/internal/todopulid/ent/schema/todo.go#L32-L33

**Comment by frederikhors** [comment]
Ok. Are you using this prefix because of the [UNIVERSAL ID](https://entgo.io/docs/migrate/#universal-ids) problem?

**Comment by frederikhors** [comment]
Am I right?

**Comment by a8m** [comment]
Prefix-based is a common way to extract the GraphQL type from the ID value in case you're using the Node API. It can be something else like base64 encoded with the type inside, but a query like `node(id: $id) { ... }` (in entgql, and in general) needs some indication of what table it needs to query in case you're using a database that does not support "global ids" (e.g. SQL).

**Comment by frederikhors** [comment]
Ok. Thanks, I'd got it right.

> I think we can support this use case without custom implementation btw

@a8m, do you think we have to close this or leave it open for the sentence you wrote?

**Comment by a8m** [comment]
> @a8m, do you think we have to close this or leave it open for the sentence you wrote?

I'm fine with closing it atm because I think this use case is not that common, especially when working with Node API. There are issues that can provide more value to the users (like https://github.com/ent/ent/issues/2600) and we prefer to focus on them for the next versions. So, closing this now, and we can consider adding it in the future in case it will be requested again. 

Thanks ❤️

**Comment by petrovskiborislav** [comment]
Hi there
I get the same error: 
`Error: failed running ent codegen: execute template "client": template: node.tmpl:377:16: executing "client/fields/additional" at <gqlIDType (filterNodes $.Nodes (skipMode "type")) $.IDType>: error calling gqlIDType: entgql: mixed id types must be type string or implement the graphql.Marshaller/graphql.Unmarshaller interfaces`
I have use case where some of the ids needs to be **ints** and others **uuids**:
```go
// Fields of the User.
func (User) Fields() []ent.Field {
	timestamptzType := map[string]string{
		dialect.Postgres: "TIMESTAMPTZ",
	}
	varchar256Type := map[string]string{
		dialect.Postgres: "VARCHAR(256)",
	}

	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New),
		field.Time("created_at").SchemaType(timestamptzType).Default(time.Now),
		field.String("display_name").SchemaType(varchar256Type),
		field.String("email").SchemaType(varchar256Type),
		field.String("user_external_id").SchemaType(varchar256Type).Optional(),
		field.Bool("activated").Default(false),
		field.String("activation_code").SchemaType(varchar256Type).Optional(),
	}
}
```

and 

```go
// Fields of the Role.
func (Role) Fields() []ent.Field {
	serialType := map[string]string{
		dialect.Postgres: "SERIAL",
	}
	varchar256Type := map[string]string{
		dialect.Postgres: "VARCHAR(256)",
	}
	return []ent.Field{
		field.Int64("id").SchemaType(serialType),
		field.String("name").SchemaType(varchar256Type).Unique(),
		field.String("display_name").SchemaType(varchar256Type).Default(""),
	}
}
```
I don't know if i am doing something wrong or i missed something or i am just writing something stupid.
