### ISSUE TITLE
How can I know if a field is `nil` (because .`Optional()`) or empty?

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2653]
Now that I am about to finish my migration from Bun, I have discovered a terrible problem!

Given this schema:

```go
type Player struct{ ent.Schema }

func (Player) Fields() []ent.Field {
  return []ent.Field{
    field.String("nick"),
    field.String("description").Optional(),
  }
}
```

If I get player from DB with:

```go
player, err := tx.Player.Query().Where(entPlayer.ID(id)).First(ctx)
// handle err
```

though `description` is correctly `NULL` in the DB Ent instead of using `*string` for it on `player` uses `""` an empty string!

This is a big, huge problem because our domain entities are using `*string` for this (like gqlgen) and in our adapters from/to domain we need to check nillness on ent structs, like:

```go
func convertEntPlayerToDomain(entPlayer *ent.Player) *domain.Player {

  // I cannot do this:
  if entPlayer.Description != nil {
    //doSomething...
  }

  return domain.UnmarshalPlayerFromRepo(
    entPlayer.ID,
    entPlayer.CreatedAt,
    entPlayer.UpdatedAt,
    entPlayer.Nick,
    entPlayer.Description, // domain.Player.Description is *string, ent.Player.Description is string instead
  )
}
```

**How can I know if `ent.Player.Description` is `nil` or an empty string?**

**Comment by a8m** [comment]
Hey! Set the field to be both `Optional()` and `Nillable()`. This will solve your issues. 
See: https://entgo.io/docs/schema-fields#nillable

**Comment by a8m** [comment]
Closing, but please open it if you still need help. Thanks 😎

**Comment by frederikhors** [comment]
Yeah. I think it works. How many things to set!

**Comment by frederikhors** [comment]
Thanks!
