### ISSUE TITLE
entproto: Invalid template defined

### ISSUE THREAD

**Issue by scraymondjr** [ent/ent#2654]
Generating service implementation fails with error 
```
--entgrpc_out: template: service.tmpl:28: function "break" not defined
```

## Steps to Reproduce 🕹

Steps:

1. Generate protobuf from an annotated ent schema enabled with `entgql.Service()`
2. Run `go generate ./...`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Entcontrib | v0.2.1-0.20220609194656-bea889a722a8|

**Comment by rotemtam** [comment]
hey @scraymondjr 
fixed with https://github.com/ent/contrib/pull/337 can you `go get entgo.io/ent/contrib@master` and try again?
thanks
