### ISSUE TITLE
[FR] Custom error for `violates foreign key constraint`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2658]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I would like to have an error for something like:

```
error="tx: delete: ERROR: update or delete on table \"players\" violates foreign key constraint \"cars_players_player\" on table \"cars\" (SQLSTATE 23503)"
```

## Motivation 🔦

Now I can only find these custom errors:

![image](https://user-images.githubusercontent.com/41120635/174252316-d2ba600a-4cdc-4fc4-a6ee-8f4e3a323751.png)

I tried

```go
if ent.IsConstraintError(err) {...}
```

but it doesn't work.

**Comment by a8m** [comment]
Hey @frederikhors! Just to make sure I understand the issue. 
You get a constraint error and you want to return back to the user a different error? `ent.IsConstraintError` does not return `true` for the error mentioned above?

**Comment by frederikhors** [comment]
> `ent.IsConstraintError` does not return true for the error mentioned above?

Nope.

> You get a constraint error and you want to return back to the user a different error?

Yep.

**Comment by frederikhors** [comment]
I'm using pgx now.

**Comment by a8m** [comment]
Can you please create a small example that reproduces this issue with https://github.com/ent/bug? Thanks 🙏

**Comment by frederikhors** [comment]
It would also be amazing to have the `ID` of the entity blocking the update/delete so I can query it and show user info about.

**Comment by frederikhors** [comment]
> Can you please create a small example that reproduces this issue with https://github.com/ent/bug? Thanks 🙏

Yeah. I'll try, I don't have much time now.

But if you have an app right now you can try delete one entity you're already using with a FK and you can see that `ent.IsConstraintError` is not returning true.

**Comment by frederikhors** [comment]
Done! https://github.com/frederikhors/ent-iss-2658

If you debug the test it will print https://github.com/frederikhors/ent-iss-2658/blob/master/bug_test.go#L70.

**Comment by a8m** [comment]
Fixed with https://github.com/ent/ent/pull/2664. Thanks for the example repository 🙏
