### ISSUE TITLE
enttest.Open is not goroutine-safe

### ISSUE THREAD

**Issue by tmc** [ent/ent#2662]
Concurrent calls to `enttest.Open()` (which you might encounter when parallelizing test runs via `t.Parallel()`) encounter a data race in the lazy/unsychronized initialization of t.columns in `func (m *Migrate) setupTable(t *Table) {`.

**Comment by a8m** [comment]
Hey @tmc and thanks for reporting this. I can work around this by either adding a lock to the migration or copying the tables.  I think the latter is preferred but requires more work. 

I'll give it a try and update you.
