### ISSUE TITLE
change id type to string failed

### ISSUE THREAD

**Issue by wenerme** [ent/ent#2666]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```go
type IDMixin struct {
	mixin.Schema
}

func (IDMixin) Fields() []ent.Field {
	return []ent.Field{
		field.String("id").DefaultFunc(func() string {
			return stdx.Must(ulids.New()).String()
		}).Unique().Immutable().Annotations(
			&entsql.Annotation{
				Default: "public.generate_ulid()",
			},
		),
	}
}
```

migration failed with

```
ERROR: invalid input syntax for type bigint: "public.generate_ulid()"
```

the executed sql

```
ERROR:  invalid input syntax for type bigint: "public.generate_ulid()" at character 55
STATEMENT:  SELECT nextval('service_accounts_id_seq'::regclass) = 'public.generate_ulid()'
```

the column become **bigint**

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.?  |
| Ent         | latest - v0.10.2-0.20220620053230-311d76067960   |
| Database    | postgres   |
| Driver      | pgx      |

**Comment by a8m** [comment]
Hey @wenerme and great to see you here again 👋 

Can you elaborate on what do you mean by "changing the id type"? What was the `id` type (SQL type) before the migration? Also, how do you run the migration, do you use the `WithAtlas` option or the old migration engine? Thanks

**Comment by wenerme** [comment]
Hi @a8m the migration is

```go
err = client.Schema.Create(ctx,
		schema.WithAtlas(true),
		schema.WithDir(dir),
		schema.WithSumFile(),
	)
```

the migrations only contain a `generate_ulid` function.

"change id type to string" I mean with the with the `IDMixin`, I can make a repro tomorrow.

**Comment by wenerme** [comment]
sorry, my mistake, the gorm code is not cleaned up.
