### ISSUE TITLE
Migrations not generated if only annotations change

### ISSUE THREAD

**Issue by hut8** [ent/ent#2671]
Generally, when I change something in the schema, a migration can be performed. I'm using SQLite. So, when I change a column to be nullable, the migration will fail (which I expect) because SQLite does not support changing a column from NULL to NOT NULL and vice versa. But I recently changed my schema using an annotation so that an existing foreign key became `ON DELETE CASCADE`:

It was:

```go
edge.To("jobs", Job.Type)
```

Then I changed it to:

```go
edge.To("jobs", Job.Type).Annotations(entsql.Annotation{OnDelete: entsql.Cascade}), 
```

I did these things:

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

* I made the above change
* I re-run the code generator with `ent generate --feature sql/upsert ./ent/schema && go build`
* I start the program, which run the migrations with: `client.Schema.Create(context.Background())`
* The sqlite schema remains exactly the same. The program goes to delete something that refers to a `Job`, and it fails because of a foreign key constraint.
* Suffering ensues, but as the Buddha is often misquoted as saying, life is suffering.

*however*

* If I delete the database and run the program, the cascade is added and works fine. So the `ent` migrator doesn't add the `CASCADE` to an existing foreign key.

## Expected Behavior 🤔

If the underlying database supports changing the `ON DELETE` action for a foreign key, then it should do that. If it doesn't, then I should get an error telling me that `ent` can't apply such a change (sqlite falls into this category of databases whose ALTER TABLE can't do this).

## Steps to Reproduce 🕹

See above

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | v0.10.1   |
| Database    | sqlite   |
| Driver      | https://github.com/mattn/go-sqlite3        |

Thanks for making such an amazing project! It's really improved my life overall.

**Comment by a8m** [comment]
Closing because the suggestion above should solve the issue, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎
