### ISSUE TITLE
[FR] Global `Annotations(entgql.Unbind())`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2675]
Using ent & gqlgen with no layers in between it is very useful to have `Annotations(entgql.Bind())` by default as it is now.

Using ent & gqlgen with a "domain" layer (with adapters/converters etc.) like I'm doing right now I found very wasteful to have `Bind()` where it is not needed by the queries (maybe because some parents are not requested or needed).

So I'm using dataloaders for this case or custom queries and I'm using `Annotations(entgql.Unbind())` everywhere.

I would like to have some "mixin"/"global" `Unbind()`.

What do you think?

**Comment by a8m** [comment]
> Using ent & gqlgen with a "domain" layer (with adapters/converters etc.) like I'm doing right now I found very wasteful to have Bind() where it is not needed by the queries (maybe because some parents are not requested or needed).

`Bind` collects only GraphQL fields (in this case, edges) that were requested in the Query.

> So I'm using dataloaders for this case or custom queries and I'm using Annotations(entgql.Unbind()) everywhere.

In case you are using `entgql.Unbind()` everywhere, you can attach this annotation to all edges using a custom codegen hook. See: https://entgo.io/docs/code-gen#code-generation-hooks
