### ISSUE TITLE
`.Paginate()` doesn't take `query.Where()` into account

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2676]
## Current Behavior 😯

If I use this code:

```go
func PlayersQuery(
  ctx context.Context,
  input app.PlayersInput,
) (*ent.PlayerConnection, error) {
  query := db.Player.Query()

  query.Where(entPlayer.TrackableType("TRACKABLE_TYPE_NAME"))

  res, err := query.Paginate(
    ctx,
    input.After,
    input.First,
    input.Before,
    input.Last,
    ent.WithPlayerOrder(input.Order),
    ent.WithPlayerFilter(input.Where.Filter),
  )
  // handle err

  return res, nil
}
```

the final query doesn't take `query.Where(entPlayer.TrackableType("TRACKABLE_TYPE_NAME"))` into account.

If I don't use `.Paginate()` and use `.All()` it works.

## Expected Behavior 🤔

I think `.Paginate()` should work both with `.Where()` and `Input.Where` predicates.

## Your Environment 🌎

| Tech     | Version                                                                                                   |
| -------- | --------------------------------------------------------------------------------------------------------- |
| Go       | 1.18.3                                                                                                    |
| Ent      | entgo.io/contrib v0.2.1-0.20220623093601-df0921394080, entgo.io/ent v0.10.2-0.20220622152053-3bb5292c83bf |
| Database | PG                                                                                                        |
| Driver   | pgx                                                                                                       |

**Comment by a8m** [comment]
Hey! It's supposed to work because I used it myself.

Please, provide a small example to reproduce this and I can check it. Thanks 🙏

**Comment by frederikhors** [comment]
I'm investigating this and maybe I'll create reproduction.
