### ISSUE TITLE
Broken logo image in ent doc footer

### ISSUE THREAD

**Issue by roger2hk** [ent/ent#2677]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

<img width="716" alt="image" src="https://user-images.githubusercontent.com/2505465/175293471-9fdd0af4-87d5-47f9-95de-6872cf9ae3c0.png">

## Expected Behavior 🤔

<img width="695" alt="image" src="https://user-images.githubusercontent.com/2505465/175293402-55a0eaac-c969-4437-8919-6a894111844f.png">

## Steps to Reproduce 🕹

Steps:

1. Visit https://entgo.io/docs/getting-started/.
2. Scroll to the bottom.

## Steps to Fix

Fix the broken logo image by removing `https://docusaurus.io`.
https://github.com/ent/ent/blob/9e4660f10448152680fdde4a506f5fe9836ad4fc/doc/website/docusaurus.config.js#L213

**Comment by a8m** [comment]
Hey @roger2hk! It's great to see you here again 😎 

Fixed with #2678. Closing
