### ISSUE TITLE
Validation issues with GRPC when using uppercase values in enums.

### ISSUE THREAD

**Issue by hartmamt** [ent/ent#2681]
Running into an issue with protoc-gen-entgrpc and enums.  There is a conversion happening that is lower casing enum values causing a validation error.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Given a schema like this:

```golang
field.Enum("device_type").
  Values("GLOWY9000", "SPEEDY300").
  Default("GLOWY9000").
  Annotations(
    entproto.Field(10),
    entproto.Enum(map[string]int32{
      "GLOWY9000": 0,
      "SPEEDY300": 1,
    }),
  ),
```

It generates a proto file field like this:

```protobuf
  enum DeviceType {
    GLOWY9000 = 0;

    SPEEDY300 = 1;
  }
```

So far so good, but when I try to call the create through GRPC, I get back the following message:

```
internal error: entgenerated: validator failed for field "HeelyDevice.device_type": heelydevice: invalid enum value for device_type field: "speedy300"
```

It seems that there is a ToLower in the plugin's template that is causing the issue. The toEnt function below is returning the lowercase value of the enum.

```golang
func toEntHeelyDevice_DeviceType(e HeelyDevice_DeviceType) heelydevice.DeviceType {
    if v, ok := HeelyDevice_DeviceType_name[int32(e)]; ok {
        return heelydevice.DeviceType(strings.ToLower(v))
    }
    return ""
}
```

I'm not sure why this function wants to lower the enum value, but that causes a validation error later on when the object is trying to be saved to the database:

```golang
// DeviceTypeValidator is a validator for the "device_type" field enum values. It is called by the builders before save.
func DeviceTypeValidator(dt DeviceType) error {
    switch dt {
    case DeviceTypeGLOWY9000, DeviceTypeSPEEDY300:
        return nil
    default:
        return fmt.Errorf("heelydevice: invalid enum value for device_type field: %q", dt)
    }
}
```

## Expected Behavior 🤔

The Create function in the generated GRPC service should not fail validation when an uppercase value is used as part of a enum field.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.9.?   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by hartmamt** [comment]
I can try to add to this later if needed, including a reproduction of the issue. I just need some more time to pull that together. @rotemtam

**Comment by rotemtam** [comment]
@hartmamt,
Thanks for reporting this!
I'm looking into this and will update.
