### ISSUE TITLE
Is there a way to validate a field based on another field?

### ISSUE THREAD

**Issue by micnncim** [ent/ent#2682]
I want to validate a field using another field like the following:

```go
func (Foo) Fields() []ent.Field {
	return []ent.Field{
		field.Int("value").
			Validate(func(i int) error {
				if i < minValue || maxValue < i {
					return fmt.Errorf("value must be between (%d, %d)", minValue, maxValue)
				}
				return nil
			}),
		field.Int("min_value").
			Validate(func(i int) error {
				if i > maxValue {
					return fmt.Errorf("minValue must be less than %d", maxValue)
				}
				return nil
			}),
		field.Int("max_value").
			Validate(func(i int) error {
				if i < minValue {
					return fmt.Errorf("maxValue must be greater than %d", minValue)
				}
				return nil
			}),
	}
}
```

Is it possible to get other fields' values inside there?

**Comment by a8m** [comment]
Hey @micnncim 👋 

Yes, the way to do it in Ent is mutation hooks. See [schema hooks](https://entgo.io/docs/hooks#schema-hooks) as an example. You can also configure a hook to be executed only if a specific field or more were changed by the mutation.

Please, let me know if you need help with it or I can close this issue. Thanks

**Comment by micnncim** [comment]
Thanks @a8m,

Hooks would work well for me. However, I've found `XXXFunc` under the `<project>/ent/hook` package is unavailable under the `<project>/ent` package since the hook package imports the `<project>/ent` package. Any idea to avoid this issue?

**Comment by a8m** [comment]
Defining **schema hooks** with typed mutations use the generated API, and therefore, you need to follow [this guide](https://entgo.io/docs/hooks#hooks-registration) in order to use them.

Other alternatives, are to register hooks on runtime (e.g. `client.Use` or `client.T.Use`) or use untyped-mutations in hooks (i.e. `ent.Mutation`). 

```go
func (Card) Hooks() []ent.Hook {
	return []ent.Hook{
		// A hook that does not import the generated "ent" package.
		func(next ent.Mutator) ent.Mutator {
			return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
				num, ok := m.Field(card.FieldName)
				if !ok {
					return nil, fmt.Errorf("missing card name value")
				}
				// Validator in hooks.
				if len(num.(string)) < 4 {
					return nil, fmt.Errorf("card name is too short")
				}
				return next.Mutate(ctx, m)
			})
		},
		// A hook that uses the "ent/hook" helper package.
		func(next ent.Mutator) ent.Mutator {
			return hook.CardFunc(func(ctx context.Context, m *gen.CardMutation) (ent.Value, error) {
				if _, ok := m.Name(); !ok {
					m.SetName("unknown")
				}
				return next.Mutate(ctx, m)
			})
		},
	}
}
```

**Comment by micnncim** [comment]
Thank you, I missed that. Closing this issue as I confirmed it works for me.
