### ISSUE TITLE
403 Access Denied for blog subscription

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2684]
I tried to subscribe to blog using RSS or ATOM but I get errors.

Manually opened links and I get 403: https://entgo.io/blog/rss.xml | https://entgo.io/blog/atom.xml.

**Comment by kidlj** [comment]
Same issue here.

**Comment by kidlj** [comment]
This issue was fixed by somebody, thank you.

**Comment by a8m** [comment]
I guess by me when I upgraded [Docusarous](https://docusaurus.io/). Can we close the issue then?
