### ISSUE TITLE
Timezone different from the DB one

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2692]
Right now I'm using this field:

```go
field.Time("used_at"),
```

The column created in Postgres is:

```sql
used_at timestamp with time zone NOT NULL,
```

The value in Postgres is saved without timezone:

```
2022-06-30 22:49:03.970913+00
```

even if I expect it to be `GMT+2` but I'm using PG in Docker and using the PG query:

```sql
show timezone
```

I get:

```
Etc/UTC
```

So OK.

But the strange thing is I get from Ent query (a simple `.First(ctx)`) the value:

```
2022-07-01T00:49:03.970913+02:00
```

This is a mess on the clients (where an UTC value is expected).

I think Ent is adding the timezone based on the PC I'm currently developing, but this is not right.

Using Bun I get the UTC value from DB.

Am I wrong somewhere?

I honestly don't know what's right to do here.

**Comment by a8m** [comment]
Hey @frederikhors, what database drivers do you use, `pg` or `pgx`?

**Comment by a8m** [comment]
In most drivers, there are options to set up the location for `time.Time` values. This changes the connection/client behavior and not the database configuration. I hope it helps.

**Comment by frederikhors** [comment]
I'm using `pgx`. I think this is the cause. I'll update this issue in a few moments.

**Comment by frederikhors** [comment]
This has nothing to do with Ent. [It's a pgx quirk](https://github.com/jackc/pgx/issues/1195) unfortunately.

SO answer: https://stackoverflow.com/questions/72771272/how-to-setup-pgx-to-get-utc-values-from-db.

They suggest a custom type. More code, more issues!
