### ISSUE TITLE
Migrations with DiffHooks failing when setting a Schema Name

### ISSUE THREAD

**Issue by ks2211** [ent/ent#2695]
Migrations with DiffHooks failing when setting a Schema Name #2695

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I run a migrations with atlas and DiffHooks, specifically setting a Schema Name in the DiffHook, the migration fails.
It fails trying to create `table_b` that references `table_a` (for a foreign key) with the error that `<schema_name>.table_a` does not exist. 
When running the migration with the DiffHook, it seems to be creating the tables out of order so tables that reference other tables will fail on create because that table being referenced does not exist.

```
2022/06/27 15:58:52 Tx(71ca12c4-8ba5-48df-8d6d-c169cbcfee82).Exec: query=CREATE SCHEMA IF NOT EXISTS "blah" args=[]
2022/06/27 15:58:52 Tx(71ca12c4-8ba5-48df-8d6d-c169cbcfee82).Exec: query=CREATE TABLE "blah"."table_abc" ("id" uuid NOT NULL, "version" character varying NOT NULL, "current" boolean NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id")) args=[]
2022/06/27 15:58:52 Tx(71ca12c4-8ba5-48df-8d6d-c169cbcfee82).Exec: query=CREATE TABLE "blah"."table_def" ("id" uuid NOT NULL, "directive" character varying NOT NULL, "address" character varying NOT NULL, "created_at" timestamptz NOT NULL, "company_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "table_def_c_faa098166ef8f3370efc5aa8cea6a82c" FOREIGN KEY ("company_id") REFERENCES "blah"."table_primary" ("id") ON DELETE CASCADE) args=[]
2022/06/27 15:58:52 Tx(71ca12c4-8ba5-48df-8d6d-c169cbcfee82): rollbacked
[2022-06-27T15:58:52-04:00] FATAL migrations sql/schema: create "table_def" table: pq: relation "blah.table_primary" does not exist
```

## Expected Behavior 🤔

When the migration with DiffHooks runs, it should create the tables in order to avoid the `table does not exist` error when its being referenced.

## Steps to Reproduce 🕹

https://github.com/ks2211/ent-migrations-bug

Steps:

1. Clone the repo `https://github.com/ks2211/ent-migrations-bug`
2. Go into the `cmd` directory and run `go build`
3. Run `./cmd` to run the compiled binary to see the migration fail

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.1  |
| Ent         | master (latest)   |
| Database    | Postgres   |
| Driver      | github.com/lib/pq       |

**Comment by a8m** [comment]
Hey @ks2211 and thanks for reporting this.

Just a quick question before I continue investigating it. What database do you use, SQLite or PostgreSQL? (issue mentions PostgreSQL, but the repo uses SQLite).

**Comment by a8m** [comment]
I just ran the previous version of the code without any issues. See results:

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/7413593/176263922-660c49c3-e32b-4957-9ced-3f58e4a19b46.png">

A modified version of your code:

```go
func main() {
	client, err := ent.Open("postgres", "...")
	if err != nil {
		log.Fatalf("failed opening connection to sqlite: %v", err)
	}
	defer client.Close()
	if err := MigrationsWithSchema(client); err != nil {
		log.Fatalf("failed migration with schema %v", err)
	}
}

func MigrationsWithSchema(client *ent.Client) error {
	return client.Schema.Create(context.Background(),
		migrate.WithDropIndex(true),
		migrate.WithDropColumn(true),
		schema.WithAtlas(true),
		schema.WithDiffHook(func(next schema.Differ) schema.Differ {
			return schema.DiffFunc(func(current, desired *atlas.Schema) ([]atlas.Change, error) {
				changes, err := next.Diff(current, desired)
				if err != nil {
					return nil, err
				}
				changes = append([]atlas.Change{
					&atlas.AddSchema{
						S: atlas.New("mytestschema").
							AddAttrs(desired.Attrs...).
							AddTables(desired.Tables...).
							SetCharset("utf8"),
						Extra: []atlas.Clause{&atlas.IfNotExists{}},
					},
				}, changes...)
				return changes, nil
			})
		}),
	)
}

```

**Comment by ks2211** [comment]
hey @a8m thanks for that snippet. I used that and this is what I saw in the debug logs
```
2022/06/29 09:59:53 Tx(f56a2e8c-d930-45c0-8687-b855f9288ce3).Exec: query=CREATE SCHEMA IF NOT EXISTS "mytestschema" args=[]
2022/06/29 09:59:53 Tx(f56a2e8c-d930-45c0-8687-b855f9288ce3): committed
```

when I do a `\dt *.*` in psql, I don't see those tables (the schema exists). I get a relation does not exist for `\d+ "mytestschema"."tenants"`


I also added an http server to see what happens when I try the migrations that way and it was the same as above. It created the schema but not the table migrations.

My changes are pushed up to my repo (including that snippet above)

**Comment by a8m** [comment]
Hey! I just ran it again on a **fresh database container**, and this is the debug output:

```console
2022/06/29 17:07:43 Tx(9787fbe9-4fa0-4963-b269-6d0a801e6ad2).Exec: query=CREATE SCHEMA IF NOT EXISTS "mytestschema" args=[]
2022/06/29 17:07:43 Tx(9787fbe9-4fa0-4963-b269-6d0a801e6ad2).Exec: query=CREATE TABLE "mytestschema"."tenants" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id")) args=[]
2022/06/29 17:07:43 Tx(9787fbe9-4fa0-4963-b269-6d0a801e6ad2).Exec: query=CREATE TABLE "mytestschema"."users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "age" bigint NOT NULL, "name" character varying NOT NULL, "tenant_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "users_tenants_users" FOREIGN KEY ("tenant_id") REFERENCES "mytestschema"."tenants" ("id") ON DELETE CASCADE) args=[]
```

It works as expected. I verified it both by connecting to the database and querying the information schema, and also ran `atlas inspect` on the container. Both tests show correct result:

```console
go run ariga.io/atlas/cmd/atlas@master schema inspect -u "postgres://postgres:pass@0.0.0.0:5434/test?sslmode=disable" 
```

```hcl
table "tenants" {
  schema = schema.mytestschema
  column "id" {
    null = false
    type = bigint
    identity {
      generated = BY_DEFAULT
    }
  }
  column "name" {
    null = false
    type = character_varying
  }
  primary_key {
    columns = [column.id]
  }
}
table "users" {
  schema = schema.mytestschema
  column "id" {
    null = false
    type = bigint
    identity {
      generated = BY_DEFAULT
    }
  }
  column "age" {
    null = false
    type = bigint
  }
  column "name" {
    null = false
    type = character_varying
  }
  column "tenant_id" {
    null = false
    type = bigint
  }
  primary_key {
    columns = [column.id]
  }
  foreign_key "users_tenants_users" {
    columns     = [column.tenant_id]
    ref_columns = [table.tenants.column.id]
    on_update   = NO_ACTION
    on_delete   = CASCADE
  }
}
schema "mytestschema" {
}
schema "public" {
}
```

**Comment by ks2211** [comment]
Thanks! 

I think when I run the TenantMigrations in my code (in my private repo), it's using the `public` schema to migrate the tables from instead of creating tables from scratch in my new schema. 

Here's the current work flow (working on updating my example code to follow this workflow):

1. In `main.go` I can run a `TenantMigration` with no issues. It creates the schema + tables. 
There are 6 tables in my private repo, in the `DiffFunc`, I see len(changes) as 6, len(current.Tables) as 0, len(desired.Tables) as 6 so all good here. The desired.Tables shows the correct table names.

2. I have a http handler that first does a lookup on the `public.tenants` schema before doing the `TenantMigration` to create the schema if the `public.tenants` does not return anything/record not found. 
In the `DiffFunc` here, it shows len(changes) as 1, len(current.Tables) as 2, len(desired.Tables) as 6....it should be 6 changes, 0 current, 6 desired. The table names also don't match, it only shows the tables from the public schema and not the ones I need it to create.

**Comment by ks2211** [comment]
I was able to resolve my issue using a little bit of hacky code (I replied in the slack thread). The tldr is I use the CreateFunc in a schema Hook to grab all of the generated *migrate.Tables and pass that to the next.Create(). 
Then in the schema DiffHook, I set these tables as the desired Tables in the Schema to be created.

This seems to resolve my issue so I will close this issue
