### ISSUE TITLE
sql/upsert wrong

### ISSUE THREAD

**Issue by youngkai** [ent/ent#2702]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/16010993/176413412-0e8a1400-716a-4029-a75d-fdb60e4b47e6.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/16010993/176413524-75128b06-6d7d-4399-812c-7b5c3ada4c53.png">
<img width="509" alt="image" src="https://user-images.githubusercontent.com/16010993/176413577-dde3bea2-7f29-4da1-a95f-b8419e53f45a.png">

**Comment by youngkai** [comment]
All ints will be like this

**Comment by a8m** [comment]
Hey @youngkai and thanks for reporting this.

What version do you use? Can you try to test it on the latest master version? Thanks 🙏 
```
go get entgo.io/ent@master
```

**Comment by youngkai** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/16010993/176416348-e3349e5a-982a-4a60-9124-1774b9a2776c.png">

not work

**Comment by youngkai** [comment]
ent v0.10.0  is perfect  thx @a8m
