### ISSUE TITLE
error: foreign-keys: field edge cannot be immutable

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2706]
## Current Behavior 😯

I'm trying to use this code to setup a Foreign Key for `tenant_id` column:

```go
type TenantMixin struct {
  mixin.Schema
}

func (TenantMixin) Fields() []ent.Field {
  return []ent.Field{
    field.String("tenant_id").Immutable(),
  }
}

func (TenantMixin) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("tenant", Tenant.Type).Field("tenant_id").Unique().Required(),
  }
}
```

but on generation ent throws with:

```
error="generateEnt: entc.Generate: entc/gen: set \"Player\" foreign-keys: field edge \"tenant_id\" cannot be immutable"
```

**Why?**

## Expected Behavior 🤔

I need `.Immutable()` to avoid wrong changes using those structs in code.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.3  |
| Ent         | entgo.io/contrib v0.2.1-0.20220623093601-df0921394080, entgo.io/ent v0.10.2-0.20220622152053-3bb5292c83bf   |
| Database    | PG   |
| Driver      | pgx        |

**Comment by a8m** [comment]
Hey @frederikhors 👋 

Supporting immutable edges is something I wanted to add a while ago. I'll add it to my upcoming tasks and you're welcome to track its progress at https://github.com/ent/ent/issues/900. Thanks for raising up this issue.

**Comment by a8m** [comment]
Thanks for the proposal @frederikhors, the issue was addressed with https://github.com/ent/ent/pull/2876.
