### ISSUE TITLE
`ent.NotSingularError` error on using `Only()` with `limit(1)`

### ISSUE THREAD

**Issue by seyedmmousavi** [ent/ent#2710]
Following query results `ent.NotSingularError` error whereas the query is limited and certainly returns JUST ONE result.
```
		sym.QueryReports().
		Where(generalreport.MetaReportTypeEQ(reportType), generalreport.PeriodEQ(_period), generalreport.MetaHasMoreCorrectionEQ(false)).
		Order(ent.Desc(generalreport.FieldMetaUpdateTime)).
		Limit(1).    // here I limited it
		Only(DbCtx)
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹
Create a query and use `Limit(1)` with `Only()`. This causes to rise `ent.NotSingularError` error.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.1  |
| Ent         | 0.10.1   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @seyedmmousavi 👋 

`Only` was not meant to work with `Limit`. If you want to get one record, use `First` instead and you'll get a `NotFoundError` in case of no matches.

Closing, but please feel free to continue the discussion if you still have questions or join our [Discord server](https://discord.gg/qZmPgTE6RX).
