### ISSUE TITLE
How to import the version with the latest commit in the github repository?

### ISSUE THREAD

**Issue by iarunsaragadam** [ent/ent#2715]
Hi Everyone,

I am new to golang and this might be a very basic question and I am probably missing something very obvious. 

I am trying to follow the documentation of entgo.io and some of the features like
```Through``` are not available in the ```latest``` version. I looked at some examples and got a version like this
entgo.io/ent v0.10.2-0.20220512043615-f2e0bef7a803

For ```Through``` to work, I need another commit. How do I achieve that? Is there a standard process to include it in my go.mod file.

I am guessing the last part of the string is commit and numbers are apparently timestamp in yyyymmddHH:MM:SS (or some other format)

Thanks in advance.

**Comment by a8m** [comment]
Hey @iarunsaragadam 👋🏻

Master branch is always stable. You can get the latest master version using the following command:

~~~
go get entgo.io/ent@master
~~~

Please, feel free to join our Discord server if you need any help with it. Thanks 😎

**Comment by iarunsaragadam** [comment]
Thanks @a8m so much for the swift response. I tried to join the slack channel, but I was not allowed and couldn't find the details of the discord server :-(

**Comment by a8m** [comment]
You’re welcome 🙂

https://discord.gg/qZmPgTE6RX
