### ISSUE TITLE
[FR] unexported edge column, can we export them?

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2716]
If I use this code:

```go
func (Player) Fields() []ent.Field {
  return []ent.Field{
    field.String("name"),
  }
}

func (Player) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("team", Team.Type).Unique().Required(),
    edge.To("coach", Coach.Type).Unique().Required(),
  }
}
```

ent creates this struct:

```go
type Player struct {
  CreatedAt             time.Time
  player_team           *uint64
  player_coach          *uint64
  Name                  string
}
```

Do you see `player_team` & `player_coach` are not exported?

Why?

Can we export them?

I need them when I convert from ent to domain structs.

**Comment by a8m** [comment]
Hey @frederikhors,
I think you already know about [edge fields](https://entgo.io/docs/schema-edges#edge-field). Setting the `team_id` (or `player_team`) and `coach_id` as edge fields should solve the issue.

But note, in case it's an existing table with records, you want to map to the previous name using the `StorageKey` option in case you decide to use `team_id` instead of `player_team`. See the full docs for it [here](https://entgo.io/docs/schema-edges#migration-to-edge-fields).

**Comment by frederikhors** [comment]
You're right. Sorry for the issue. I think my question was about this:

can we avoid to write that code for each field? Can we have an `.ExportField()` or `.ExportFK()` or something similar or just export those fields?

I like the default name `player_team` instead of `team_id`. I just need to get that from outside.

**Comment by a8m** [comment]
> Can we have an .ExportField() or .ExportFK() or something similar or just export those fields?
> 
> I like the default name player_team instead of team_id. I just need to get that from outside.

There's already a method for that called `Field`. The [`Field` option](https://entgo.io/docs/schema-edges/#edge-field) also gives you the option to configure this field with additional modifiers like all other fields (e.g. struct tags, annotations, etc). Hence, I don't think we need a degraded version of it. @masseelch, @giautm, and @rotemtam - your thoughts, please.

**Comment by masseelch** [comment]
> can we avoid to write that code for each field? 

Yes, if you have too many schemas and you want to this for every single edge field, you can add a codegen hook to add the annotation as described by @a8m for every schema as part if the code generation. 

I agree with @a8m, we don't need an extra option as your issue can be resolved. I don't see any value gained by adding sth like `ExposeFK()`.
