### ISSUE TITLE
proposal: compare index with both index names and fields when doing schema migration

### ISSUE THREAD

**Issue by oclld** [ent/ent#2717]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.
## Summary
i get a problem when doing schema migration with `migrate.WithDropIndex(true)` setted `true` just like below.  
```
// Run migration.
err = client.Schema.Create(
    ctx, 
    migrate.WithDropIndex(true),
    migrate.WithDropColumn(true), 
)
if err != nil {
    log.Fatalf("failed creating schema resources: %v", err)
}
```
```
func (User) Indexes() []ent.Index {
    return []ent.Index{
        index.Fields("field1", "field2").
            StorageKey("custom_index"),
    }
}
```
Custom index name is configured using `StorageKey()`,  but when i add a field to the index without change the custom index name, the index will not be considered to be changed. this will not happen without `StorageKey` because the default index name is constructed with fields connected by `_`  and any change of fields will change the index name.

i try to figure out what happens and get this in `schema/migrate.go`.
```
func (m *Migrate) txCreate(ctx context.Context, tx dialect.Tx, tables ...*Table) error {
    ...
	change, err := m.changeSet(curr, t)
	if err != nil {
	    return fmt.Errorf("creating changeset for %q: %w", t.Name, err)
	}
    ...
}
```
```
// changeSet returns a changes object to be applied on existing table.
// It fails if one of the changes is invalid.
func (m *Migrate) changeSet(curr, new *Table) (*changes, error) {
    ...
	// Add or modify indexes.
	for _, idx1 := range new.Indexes {
	    switch idx2, ok := curr.index(idx1.Name); {
	    ...
        }
    ...
}
```
```
// index returns a table index by its name.
func (t *Table) index(name string) (*Index, bool) {
	for _, idx := range t.Indexes {
		if name == idx.Name || name == idx.realname {
			return idx, true
		}
		// Same as below, there are cases where the index name
		// is unknown (created automatically on column constraint).
		if len(idx.Columns) == 1 && idx.Columns[0].Name == name {
			return idx, true
		}
	}
	// If it is an "implicit index" (unique constraint on
	// table creation) and it wasn't loaded in table scanning.
	c, ok := t.column(name)
	if !ok {
		// Postgres naming convention for unique constraint (<table>_<column>_key).
		name = strings.TrimPrefix(name, t.Name+"_")
		name = strings.TrimSuffix(name, "_key")
		c, ok = t.column(name)
	}
	if ok && c.Unique {
		return &Index{Name: name, Unique: c.Unique, Columns: []*Column{c}, columns: []string{c.Name}}, true
	}
	return nil, false
}
```
`index()` method of Table struct only compares the name and the realname. i think it is better to compare whether the fields are changed.

## Motivation
I only get the problem when i try to set the name of index. Actually, i am not sure whether this is designed for, if so, it is better to clarify this in docs.

**Comment by a8m** [comment]
Hey @oclld 👋 

> Custom index name is configured using `StorageKey()`, but when i add a field to the index without change the custom index name, the index will not be considered to be changed.

Using the new [Atlas migration engine](https://entgo.io/docs/migrate#atlas-integration) on the latest master should solve the problem. Please, run the migration with it and report if we can close this issue. Thanks

**Comment by oclld** [comment]
Thanks you @a8m , atlas migration works for this situation. i will close this issue.
