### ISSUE TITLE
Return empty values when querying

### ISSUE THREAD

**Issue by garrettlove8** [ent/ent#2720]
I have a number of columns on a user table that aren't immediately populated with data due to my app's on boarding processes.

For example, after a user signs up with Facebook the data might look like this:

|**Column**|**Value**|
|------|-----|
|first_name|"Garrett"|
|about|""|
|show_walkthrough|true|
|has_onboarded|false|

When I query this data within my `getUser` endpoint, Ent is omitting any columns it deems to be empty (null, false, "", 0, and maybe some others I haven't come across).

So in continuing with our example, it will return:
|**Column**|**Value**|
|------|-----|
|first_name|"Garrett"|
|show_walkthrough|true|

For now, my solution is to store things as string values so Ent will think they exist. However, this is a very poor solution.

The closest documentation I could find on querying specific columns was [this](https://entgo.io/docs/crud#field-selection) from Ent's website, however it doesn't work with "empty" values.

How anyone come across this?

**Comment by a8m** [comment]
Hey @garrettlove8 👋 

What do you mean by omitting? If you mean on JSON marshaling, you can either set the fields to pointers using the [Nillable](https://entgo.io/docs/schema-fields#nillable) option or drop the `omitempty` using the `StructTag` option.

```go
func (T) Fields() []ent.Field {
    return []ent.Field{
        field.String("name").
            StructTag(`json:"name"`), // Override the JSON tag without omitempty. 
    }
}
```

**Comment by garrettlove8** [comment]
@a8m Yup, Nillable did the trick. Thank you so much for responding so quickly!
