### ISSUE TITLE
Now how can I implement the soft delete function more elegantly?

### ISSUE THREAD

**Issue by gmars** [ent/ent#2729]
- [Yes ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Although I really like the overall design idea of ENT. However, there is still a lot of confusion in the selection, can the client initialization by passing in the form of parameters to set the soft delete? Physical deletion of every piece of data by the user is very dangerous, which is not conducive to data recovery and the recording of data traces.

## Motivation 🔦

Although I saw in issue that someone implemented this feature in the form of a custom template. But this is not very convenient to use, and raises the threshold of using ENT. There's a lot of confusion, consistency confusion for the team.

**Comment by mirusky** [comment]
I'm trying the same thing, look at what I did as so far: #2850

**Comment by a8m** [comment]
Hey all! Interceptors were added to Ent, and you can implement something like soft-delete with a shared Mixin in your project. Please, check out https://entgo.io/docs/interceptors#soft-delete and feel free to join our [Discord](https://discord.gg/qZmPgTE6RX) and ping me if you have any troubles with it.

**Comment by lgcshy** [comment]
`return []ent.Hook{
        hook.On(
            func(next ent.Mutator) ent.Mutator {
                return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
                    // Skip soft-delete, means delete the entity permanently.
                    if skip, _ := ctx.Value(softDeleteKey{}).(bool); skip {
                        return next.Mutate(ctx, m)`
undefined: hook
---------------------------------------
`mx, ok := m.(interface {
                        SetOp(ent.Op)
                        Client() *gen.Client
                        SetDeleteTime(time.Time)
                        WhereP(...func(*sql.Selector))
                    })`

undefined: gen.Client
