### ISSUE TITLE
Versioned Migration: Error in executing the NamedDiff for migration generation.

### ISSUE THREAD

**Issue by kingzbauer** [ent/ent#2731]
As per the documentation here: https://entgo.io/docs/versioned-migrations/#generating-versioned-migration-files, when this is run as is, after the first run, subsequent runs fail with such an error:
`2022/07/08 16:57:31 failed generating migration file: sql/migrate: execute: executing statement "DROP TABLE `item_tags`;" from version "20220708104627": Error 1051: Unknown table 'ent_dev.item_tags'`

- [ x] The issue is present in the latest release *(master branch)*
- [ x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
The following error is encountered: `2022/07/08 16:57:31 failed generating migration file: sql/migrate: execute: executing statement "DROP TABLE `item_tags`;" from version "20220708104627": Error 1051: Unknown table 'ent_dev.item_tags'`

## Expected Behavior 🤔

Subsequent executions of `go run -mod=mod main.go` after the initial execution, as per the documentation attached above: in the event I have added new schema entities, 2 new migration files should be created in my migration directory. For both adding the changes (`up`) and reversing  (`down`)

## Steps to Reproduce 🕹

Steps:

1. Make sure you have at least one entity specified
2. Follow the instruction for setting up versioned migrations from here: https://entgo.io/docs/versioned-migrations/
3. Execute `go run -mod=mod main.go` as per this section: https://entgo.io/docs/versioned-migrations/#with-entc-package
4. Make sure a set of sql files are generated in the specified migrations file
5.  rerun `go run -mod=mod main.go`
6. You should encounter the error above

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.2  |
| Ent         | v0.4.3-0.20220630091711-40a31231fd1a  |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by masseelch** [comment]
Hey @kingzbauer, thank you for reporting this! I will send a fix ASAP! Sorry for any inconvenience. :bow:

**Comment by masseelch** [comment]
Hey @kingzbauer, I just created #2732 to adsress your issue and I will merge once it got approved.

**Comment by kingzbauer** [comment]
Thank you @masseelch this is of great help. Versioned Migration is something I've been really looking forward to. Much appreciated
