### ISSUE TITLE
[Question] Working with exists postgres array column with default value.

### ISSUE THREAD

**Issue by zw963** [ent/ent#2744]
Hi, we have a exists golang project switching from gorm to ent, because some reason, we are use ruby on rails for db migration solution.

 we have a users table, which exist a `roles` column, which create use ruby on rails migration like this:

```rb
t.text   :roles, array: true, default: []
```

or when use with gorm, roles column schema is this:

```
Roles                        pq.StringArray `gorm:"type:text[]"`
```

When dump to the db schema, it raw format present as this:

```
roles text[] DEFAULT '{}'::text[],
```

Because there is default value, so, in our db, exists maybe records which roles like this.

```
=> ["{}", "{}", "{}", "{}", "{admin}"] 
```

We are try to wrap this column use ent schema, but no luck.

Following is attempts

```go
field.Other("roles", &pgtype.ArrayType{}).
			SchemaType(map[string]string{
				dialect.Postgres: "ARRAY",
			}),
```

when use with above config, we always get error message like this:

```
sql/schema: unsupported default type: other default to "{}"
```

Could you please help on how to fix this? what i mean is, how to read/save and present array data in the view correctly.

Thank you.

**Comment by a8m** [comment]
Hey @zw963 👋 

What version do you use? Can you please update to the latest master and report if you still get this issue? 

```console
go get entgo.io/ent@master
```

If you need faster support, please free to join our [Discord server](https://discord.gg/qZmPgTE6RX) and ping me there.

**Comment by zw963** [comment]
> What version do you use? Can you please update to the latest master and report if you still get this issue?

We are use v0.10.1 before, i follow you guides update to @master,  v0.10.2-0.20220712151345-6c8a1308ec2d

get following error from my another table.

```
reverse alter table "licenses": unexpected attribute change (expect IDENTITY): []
```

Any idea? thank you.

**Comment by a8m** [comment]
Are you able to reproduce it using an exmaple schema? see https://github.com/ent/bug

**Comment by zw963** [comment]
Okay, the correct fields schema for above roles should be:

```go
field.Other("roles", &pgtype.TextArray{}).
			SchemaType(map[string]string{
				dialect.Postgres: "text[]",
			}).Default(&pgtype.TextArray{}),
```

Even, the display output of this column still not correct, it output `{[{admin 2}] [{1 1}] 2}` instead `["admin"]`, but, this probably another issue i still don't know how to resolve, thank you.

**Comment by gmhafiz** [comment]
@zw963 Hey I solved it using lib/pq library instead


```go
import "github.com/lib/pq"

field.Other("tags", &pq.StringArray{}).
	SchemaType(map[string]string{
		dialect.Postgres: "text[]",
	}).
	Default(&pq.StringArray{}).
	Optional(),
```
