### ISSUE TITLE
M2M edge fails during data migration using string id in PostgreSQL

### ISSUE THREAD

**Issue by petrovskiborislav** [ent/ent#2753]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

`failed creating schema resources: sql/schema: create foreign keys for "organizational_unit_specialties": pq: foreign key constraint "organizational_unit_specialties_organizational_unit_id" cannot be implemented`

```go
// OrganizationalUnit holds the schema definition for the OrganizationalUnit entity.
type OrganizationalUnit struct {
	ent.Schema
}

// Fields of the OrganizationalUnit.
func (OrganizationalUnit) Fields() []ent.Field {
	timestamptzType := map[string]string{dialect.Postgres: "TIMESTAMPTZ"}
	varchar256Type := map[string]string{dialect.Postgres: "VARCHAR(256)"}
	uuidType := map[string]string{dialect.Postgres: "uuid"}

	return []ent.Field{
		field.String("id").MaxLen(16).Default(uuid.NewString()).SchemaType(uuidType),
		field.String("display_name").SchemaType(varchar256Type).Default(""),
		field.Time("created_at").SchemaType(timestamptzType).Default(time.Now),
		field.Time("deleted_at").SchemaType(timestamptzType).Optional(),
		field.String("parent_id").SchemaType(uuidType).Optional(),
		field.JSON("metadata", []string{}).Default([]string{}),
		field.String("type_id").SchemaType(uuidType),
	}
}

// Edges of the OrganizationalUnit.
func (OrganizationalUnit) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("children", OrganizationalUnit.Type).
			From("parent").Field("parent_id").Unique(),
		edge.From("organizational_unit_type_id", OrganizationalUnitType.Type).
			Ref("organizational_units").Field("type_id").Unique().Required(),
		edge.To("specialties", Specialty.Type),
	}
}

// Specialty holds the schema definition for the Specialty entity.
type Specialty struct {
	ent.Schema
}

// Fields of the Specialty.
func (Specialty) Fields() []ent.Field {
	varchar256Type := map[string]string{dialect.Postgres: "VARCHAR(256)"}
	uuidType := map[string]string{dialect.Postgres: "uuid"}

	return []ent.Field{
		field.String("id").MaxLen(10).Default(uuid.NewString()).SchemaType(uuidType),
		field.String("name").Unique().SchemaType(varchar256Type),
	}
}

// Edges of the Specialty.
func (Specialty) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("organizational_units", OrganizationalUnit.Type).
			Ref("specialties"),
	}
}

```

**Comment by a8m** [comment]
Hey @petrovskiborislav and thanks for reporting this 🙏 

What version do you use? Can you please check if you get this on the latest version (v0.11.1)?

**Comment by petrovskiborislav** [comment]
@a8m i updated to latest (v0.11.1) but got the same error

**Comment by a8m** [comment]
Please, create a reproducible example using https://github.com/ent/bug and I'll give it a look ASAP. Thanks

**Comment by a8m** [comment]
@petrovskiborislav, I appreciate the help with the example repository! It helped me to find the issue.

In short, the join table didn't use the right `SchemaType` you configured on the `id` fields. This happened because you used a `field.String` with a custom `uuid` schema type (instead of `field.UUID`) for these primary keys. It was solved with https://github.com/ent/ent/pull/2760, and I tested it on your repository and it works as expected. 

Please, update your project to the latest master to pull these changes. Thanks again 🙏

**Comment by petrovskiborislav** [comment]
@a8m i updated the example repo first with the master version then regenerated the code but got the same error when i ran the test :disappointed:. Is there something else i should do?

**Comment by a8m** [comment]
Make sure you on the latest master commit. If it’s still not working, paste here the version in your go.mod.  Thanks 🙏🏻

**Comment by petrovskiborislav** [comment]
Thank you :bow: that worked! I was not getting the latest commit

**Comment by petrovskiborislav** [comment]
@a8m just one quick question. Is it okay to use string type for **IDs** as UUID since i can't use UUID type because i have mixed id types like **ints**?

**Comment by a8m** [comment]
Yes.
