### ISSUE TITLE
Calling same relay connection with different aliases is not working

### ISSUE THREAD

**Issue by amrnt** [ent/ent#2755]
For example, if I have this edge on `Post`

```golang
        edge.To("comments", Comment.Type).
            Annotations(entgql.RelayConnection()),
```

When I call this query, the results for both `publishedComments` and `draftComments` will be same as `publishedComments`.

```graphql
node(id: "xxx") {
  ... on Post {
    title
    body

    publishedComments: comments(where: { status: PUBLISHED }) {
      edges {
        node {
          id
          status
        }
      }
    }

    draftComments: comments(where: { status: DRAFT }) {
      edges {
        node {
          id
          status
        }
      }
    }
  }
}
```

I think this issue was mentioned briefly by @a8m here: https://github.com/ent/contrib/pull/344#pullrequestreview-1020415004

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | master  |
| Database    | Postgtres   |
| Driver      | pgx  |

**Comment by a8m** [comment]
Thanks for reporting this, @amrnt 🙏 

We currently have a limitation in entql's fields-collection where it expects only one GraphQL field per edge. @giautm and I discussed this and we thought about adding some API to Ent (enabled by a FF) that can be integrated to entgql and solve this issue:

```go
posts, err := client.Post.Query().
    WithNamedComments("published", func(q *ent.CommentQuery) {
        q.Where(comment.StatusEQ(comment.StatusPublished))
    })
    WithNamedComments("draft", func(q *ent.CommentQuery) {
        q.Where(comment.StatusEQ(comment.StatusDraft))
    }).
    Paginate(...)
    
// Then, get each named loaded edge as follows:
for _, p := range posts {
    published, err := p.Edges.NamedComments("published")
    // ...
    draft, err := p.Edges.NamedComments("draft")
    // ...
}
```

This API should be transparent to entgql users and a query like the one above should be loaded correctly in an efficient way.

**Comment by a8m** [comment]
Thanks @amrnt for the great bug report. The issue was addressed both in ent and ent/contrib.

Closed with https://github.com/ent/contrib/pull/355
