### ISSUE TITLE
Postgres SERIAL type causes error on generation if not put in the ID field.

### ISSUE THREAD

**Issue by xKakima** [ent/ent#2759]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
After generation, it returns this error
```
failed creating schema resources: sql/schema: modify "<schema>" table: pq: syntax error at end of input
```

## Expected Behavior 🤔
It should build as normal

## Steps to Reproduce 🕹

Steps:

1. Create a schema with these fields
```
field.UUID("id", uuid.UUID{}).Default(uuid.New),
field.Int("xid").
         SchemaType(map[string]string{
	dialect.Postgres: postgres.TypeBigSerial,
	}),
```
2.  Run `go generate`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | 0.11 |
| Database    | Postgres   |
| Driver      | https://github.com/lib/pq        |

**Comment by a8m** [comment]
Hey @xKakima 👋 

Please, update to the latest master version and report if you still have issues with it. Thanks 🙏

**Comment by xKakima** [comment]
Still having issues when running the auto migration

```
2022/07/15 15:37:36 Tx(77033dc8-a397-46d1-8ca7-713cb28f1e53).Exec: query=ALTER TABLE "organizations" ALTER COLUMN "xid" TYPE bigserial args=[]

2022/07/15 15:37:36 Tx(77033dc8-a397-46d1-8ca7-713cb28f1e53): rollbacked

2022/07/15 15:37:36 failed creating schema resources: sql/schema: modify "organizations" table: pq: type "bigserial" does not exist
```

**Comment by a8m** [comment]
You can't change a type of an existing column to serial, because it's not a real type (it's a shortcut for `integer not null default nextval(...)`). I still plan to add support for this in Atlas today (create a sequence, attach it column, etc). 

Do you have an existing column that you try to change to serial? What its type currently? If you don't have any data there yet, simply drop the column and add it back with Ent to solve the issue.

**Comment by xKakima** [comment]
Yes, there's currently an existing one. Dropped the whole schema and just regenerated the tables. Works perfectly fine now
