### ISSUE TITLE
ent generates invalid code when resolving the pkg name to Go map type

### ISSUE THREAD

**Issue by ivanvanderbyl** [ent/ent#2761]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

After upgrading from 0.10.1 to 0.11.1, when I regenerate my app I get this weird output in the dependency imports of some files e.g. `<T>_delete.go`:

```go
import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"
		"github.com/airheartdev/api/ent/predicate"
			map[string]models "github.com/airheartdev/api/internal/models"
			"github.com/airheartdev/api/internal/models"
			"github.com/airheartdev/api/internal/models"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/schema/field"
		stdsql "database/sql"

)
```

This seems to be a result of having a JSON field that uses a map type that has a value in another pkg, for example:

```go
field.JSON("occupancy_pricing", map[string]models.OccupancyPricing{})
```

I've bisected all the commits and this regression was introduced with https://github.com/ent/ent/pull/2686

## Expected Behavior 🤔

It generates the correct pkg import name.

## Workaround

A quick workaround for anyone else coming across this: define a custom map type:

```go
type OccupancyPricingMap map[string]OccupancyPricing
```

cc @a8m

**Comment by a8m** [comment]
Thanks for reporting this @ivanvanderbyl 🙏 

Updating to the latest master should solve the issue.

**Comment by ivanvanderbyl** [comment]
Thanks for the quick fix @a8m
