### ISSUE TITLE
Very, very strange issue cause copying files in the same directory of `entgql.WithConfigPath`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2762]
## Current Behavior 😯

After hours of debugging I found out the "cause" of this very strange issue.

I'm generating with Ent programmatically using this code:

```go
var wg sync.WaitGroup

wg.Add(1)

go func() {
  defer wg.Done()

  copySomeFiles()
}()

wg.Add(1)

go func() {
  defer wg.Done()

  if err := GenerateEnt(); err != nil {
    //handle err
  }
}()

wg.Wait()
```

with:

```go
func GenerateEnt() error {
  gqlEx, err := entgql.NewExtension(
    entgql.WithWhereInputs(true),
    entgql.WithConfigPath("./internal/gqlgen/gqlgen.yml"),
    entgql.WithSchemaPath(path.Join("./internal/ent/ent.graphql")),
  )
  //handle err

  opts := []entc.Option{
    entc.Extensions(gqlEx),
  }

  config := &gen.Config{
    Target: internalEntPath,
    IDType: &field.TypeInfo{Type: field.TypeString},
    Features: []gen.Feature{
      gen.FeaturePrivacy,
      gen.FeatureEntQL,
      gen.FeatureExecQuery,
      gen.FeatureUpsert,
    },
  }

  if err := entc.Generate("./internal/ent/schema", config, opts...); err != nil {
    //handle err
  }

  return nil
}
```

and:

```go
func copySomeFiles() error {
  if errWalk := fs.WalkDir(Files, ".", func(path string, info fs.DirEntry, err error) error {
    //...logic

    fileContent, err := Files.ReadFile(filesDirName + "/" + path)
    //handle err

    if err := os.WriteFile(path, fileContent, os.ModePerm); err != nil {
    //handle err
    }

    return nil
  }); errWalk != nil {
    //handle err
  }

  return nil
}
```

### The issue

Each file of `copySomeFiles()` is copied in `./internal/gqlgen` instead of other dirs.

**If I comment out the below line everything works!**

```go
entgql.WithConfigPath("./internal/gqlgen/gqlgen.yml"),
```

Can you suggest a fix for this?

## Your Environment 🌎

| Tech     | Version                                       |
| -------- | --------------------------------------------- |
| Go       | 1.18.4                                        |
| Ent      | entgo.io/contrib v0.3.0, entgo.io/ent v0.11.1 |
| Database | PG                                            |
| Driver   | pgx                                           |

**Comment by a8m** [comment]
Hey @frederikhors,
I'm pretty sure it isn't an Ent issue but more like a gqlgen thing. See https://github.com/99designs/gqlgen/pull/1511, that unfortunately was reverted.

My suggestion is not to run the 2 tasks in parallel because entgql restores the working directory after gqlgen changes it. See https://github.com/ent/contrib/blob/master/entgql/extension.go#L87-L91.

**Comment by frederikhors** [comment]
I answered you there. You're really great @a8m.
