### ISSUE TITLE
Disable the ID full capital letters

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2768]
Is there an option / a way to disable the `ID` to be in capital letters in full?

Example: in my code all the structs have IDs like:

```go
type Player struct {
  Id string
  TeamId string
  TeamIds []string
}
```

and this forces me to change many templates to be able to call ent's `.[name]ID()` methods.

**Comment by amrnt** [comment]
https://github.com/golang/lint/issues/124 😁 

Ent is using these rules to define what would be capitalized: https://github.com/ent/ent/blob/4a26cab7347abe01b77107560a4117ced3fad9eb/entc/gen/func.go#L288-L292

**Comment by a8m** [comment]
Hey! There's no way to delete acronyms/abbreviations, but there's a way to add some, see: https://github.com/ent/ent/blob/master/entc/gen/func.go#L296.

If you're interested in this, you're welcome to send a small patch to add the `DeleteAcronym` option, but tbh, I don't think it's really needed. The acronyms/abbreviations in this list are the common ones used almost by all linting tools. Closing 🙏
