### ISSUE TITLE
Create(): Force mandatory fields / advice at compile time

### ISSUE THREAD

**Issue by stonymahony** [ent/ent#2775]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

ent strives to be as typesafe and explicit as possible, which has been achieved to a great extent.

However, I lack some support in the use of Create().  The following example is the schema for a user. All fields are required. 

```
// Fields of the user.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.Int("age"),
        field.String("name"),
        field.String("username").
            Unique(),
        field.Time("created_at").
            Default(time.Now),
    }
}
```

The following Create() does not contain all required fields. There is no compile error, ent does not complain. At runtime, the query leads to an SQL exception. 

```
a8m, err := client.User. 
    Create(). 
    SetName("a8m"). 
    Save(ctx)
```

Is there a way to make ent force all required fields to be set in Create(), with compile errors if fields are missing?

## Motivation 🔦

This could help to avoid simple errors and reduce the effort of keeping schemas and queries in sync.

**Comment by rotemtam** [comment]
Hey @stonymahony 
Thanks for reaching out.
I totally understand where you're coming from. This type of error isn't usually caught at compile time, and is instead commonly verified with unit tests.

It would be technically possible to write a linter that is aware of the entity schema and check that every invocation to Create is followed by setting all required fields, but as the decision on which fields to set is often made at runtime I'm not sure it's the correct way to go.

What do you think ?

**Comment by a8m** [comment]
>  but as the decision on which fields to set is often made at runtime I'm not sure it's the correct way to go.

One common flow is that fields are set in hooks, making it impossible to implement.

When we developed Ent, I thought about defining the methods signature of the builders this way:

```go
Create(requiredField1, requiredField2, ..., optionalFields...)

User.Create(SetName("Ariel"), SetUserName("a8m"), /* Optional builders */)
``` 

But the approach above was too limited to work with (impossible to pass builders, share mutation objects, set fields in hooks, etc.), and we ended up with the current implementation, which I like a lot 😃

**Comment by a8m** [comment]
Closing, but please feel free to continue the discussion on our [Discord server](https://discord.gg/qZmPgTE6RX) 😎

**Comment by stonymahony** [comment]
Thank you for the quick answers and your explanations, these are important arguments that explain why this feature does not exist in this form for a good reason😄

The current implementation should definitely be kept, the flexibility is indeed great. 

Inspired by @a8m discarded approach, how about offering this as a 2nd builder, e.g. CreateComplete(....), as an alternative to the existing Create(..)? 

Would that be an elaborate feature?

However, I could also fully understand if this does not correspond to your philosophy for ent and is rather undesirable🙂

**Comment by a8m** [comment]
Something I wrote in the issue-tracker some time ago and I think it's true for this case as well: https://github.com/ent/ent/issues/1027#issuecomment-741843635

> ...
>
> I tend to agree with alexsn, especially because I'm working atm on moving stuff to feature-flags to make the base codegen assets much smaller.
>
> Regarding this new API, since it doesn't require any runtime-specific logic, I think it's better to create a plugin for it in a different repository for now (and maybe mention it on our website) and possibly add it to the core features if we'll see big adoption for this.
>
> I encourage our internal users (at Meta) to go through the same process as well. They start with custom templates for such proposals and we consider adding them to the framework only after we have some experience with it - because once you add it, you can't go back.

If you want to work on such an extension for Ent and I'll be happy to help, and I'm available on our [Discord server](https://discord.gg/qZmPgTE6RX) 😎
