### ISSUE TITLE
Matching column orders of bulk inserts and inserts

### ISSUE THREAD

**Issue by minje0206** [ent/ent#2779]
Dear, 

Hi! I'm just getting started with Ent and have had a very positive experience so far.

I use `ent` to my project, and I got a question as below.  
When I use `sqlmock` for test, I noticed that the column order of create and create bulk are different.

```
//example of insert
INSERT INTO `tags` (`created_at`, `updated_at`, `key`, `value`) VALUES (?, ?, ?, ?)

// example of bulk insert
INSERT INTO `tags` (`created_at`, `key`,  `updated_at`, `value`) VALUES (?, ?, ?, ?), (?, ?, ?, ?)

// schema
func (Tag) Mixin() []ent.Mixin {
	return []ent.Mixin{
		TimeMixin{},
	}
}

// Fields of the Tag.
func (Tag) Fields() []ent.Field {
	return []ent.Field{
		field.String("key").MaxLen(128),
		field.String("value").MaxLen(256),
	}
}
```

I checked the `sqlgraph` of the dialect and found out that the columns are ordered by column name.
So, I wanna ask How about ordering the bulk insert in the same order as create?

For example
```
	columns := make(map[string]struct{})
	sorted := []string{}
	values := make([]map[string]driver.Value, len(c.Nodes))
	for i, node := range c.Nodes {
                                         .
                                         .
		err := setTableColumns(node.Fields, edges, func(column string, value driver.Value) {
			if _, ok := columns[column]; !ok {
				columns[column] = struct{}{}
				sorted = append(sorted, column)
			}
			values[i][column] = value
		})
                                        .
                                        .
	}
```

Cheers.

**Comment by a8m** [comment]
Hey @minje0206 and thanks for the kind feedback 🙏 

The "bulk insert" operation is ordered by column names because there are multiple builders and we want to make sure their values have consistent order. For single insert (one list of values), we can avoid the ordering as it's not needed. I'd prefer to avoid this extra computation if it's not required.

**Comment by minje0206** [comment]
Hi, thanks for your answer! :D
