### ISSUE TITLE
Can we query from multiple schemas present on the same database using ent?

### ISSUE THREAD

**Issue by carlos0202** [ent/ent#2782]
I have multiple schemas on my database and want to use this package to query data joining between schemas to produce queries like the following:
```
SELECT schemaA.TableA.colA
    , schemaB.TableB.colA
FROM schemaA.TableA
JOIN schemaB.TableB ...
```

Is it possible with the current `ent` package version?

**Comment by a8m** [comment]
Hey @carlos0202 👋 

I think the [`sql/schemaconfig`](https://entgo.io/docs/feature-flags#schema-config) feature flag should help you here. See also a [usage example](https://github.com/ent/ent/blob/master/entc/integration/multischema/multischema_test.go#L38-L43) in our integration tests.

In case you need it only for one or a few queries, you can also use [query modifiers](https://entgo.io/docs/feature-flags#custom-sql-modifiers) to inject this custom logic.

**Comment by a8m** [comment]
Closing, but please reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with it. Thanks 🙏

**Comment by carlos0202** [comment]
After a few conversations on Discord server and some trial and error I've found out that the current [sql/schemaconfig](https://entgo.io/docs/feature-flags#schema-config) does not fully work for my use case. Actually, I need a solution that can help automatic migration to generate the tables under the desired schemas when setting up from scratch (on tests, for instance) with also the possibility to use those tables from multiple schemas (not databases) from the same ent client. Can we have a way to tell our models by default a schema to use on all operations? Thanks in advance for all the help provided!

**Comment by a8m** [comment]
I created an example for this use case, see: https://github.com/ent/ent/pull/2804. It covers ~all the things mentioned here.

I hope it helps :pray:
