### ISSUE TITLE
Does ent support geometry type?

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#2783]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by CNTWDev** [comment]
@a8m thx

**Comment by a8m** [comment]
Hey @CNTWDev 👋 

Yes. Please, see [this example](https://entgo.io/docs/faq#how-to-define-a-spatial-data-type-field-in-mysql) and let us know if you need any further help with it.
