### ISSUE TITLE
ScanX() JSON field error when use function Modify() to customize join query. (v0.11.1)

### ISSUE THREAD

**Issue by BeatsKitano** [ent/ent#2789]
I hope to customize join quey,  the table has jsonb type field, ent can generate correct query SQL, but ScanX() function got a ERROR. 
```bash
unsupported Scan, storing driver.Value type []uint8 into type *schema.JsonbData
```

## Expected Behavior 🤔

Scan() function can scan data to struct correctly

### 1. Schema
```golang

type JsonbData struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Price     string `json:"price"` 
}

// Fields of the Foo.
func (Foo) Fields() []ent.Field {
	return []ent.Field{ 
		field.Time("create_time"),

		field.JSON("data", JsonbData{}).
			SchemaType(map[string]string{
				dialect.Postgres: "jsonb",
			}),
	}
}

type Bar struct {
	ent.Schema
}

// Fields of the Bar.
func (Bar) Fields() []ent.Field {
	return []ent.Field{
		field.String("ip"),
		field.Int32("port"), 
	}
}

```

### 2. Custom JOIN

```golang
type CustomJoin struct {
    ID         int                           `sql:"id"`
    CreateTime time.Time        `sql:"create_time"`
    Data       schema.JsonbData `sql:"data" json:"data"` 
    IP         string                      `sql:"bars.ip"`
    Port       int32                   `sql:"bars.port"` 
}

        var customJoins []CustomJoin
	
postgre.Foo.Query().Select(foo.FieldID, foo.FieldCreateTime, foo.FieldData).
		Order(db.Desc(foo.FieldID)).
		Where(
			foo.IDEQ(3456),
		).
		Modify(func(s *sql.Selector) {
			bars := sql.Table(bar.Table)

			s.Join(bars).On(
				s.C(foo.FieldID),
				bars.C(bar.FieldID),
			).AppendSelect( 
				sql.As(bars.C(bar.FieldIP), "bars.ip"),
				sql.As(bars.C(bar.FieldPort), "bars.port"), 
			). 
				Offset(0).Limit(10)
		}).
		ScanX(ctx, &customJoins)
```

### 3. Got Error

```bash
unsupported Scan, storing driver.Value type []uint8 into type *schema.JsonbData
```
 
## Your Environment 🌎
 
| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.4  |
| Ent         | 0.11.1   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx/v4/stdlib     |

**Comment by a8m** [comment]
Hey @BeatsKitano 👋🏻
You can implement the Scanner interface for JsonbData. Please, see the examples in our integration tests. https://github.com/ent/ent/blob/master/entc/integration/ent/schema/fieldtype.go#L469

**Comment by BeatsKitano** [comment]
Thanks, I tried to look at the documentation, but there is still a lot I don't know.  After that, I will write the experience as a blog and contribute to ent to help more people understand the details of using ent.  Thanks again for your reply, sorry for the inconvenience

**Comment by a8m** [comment]
No worries, and contribution is welcomed :)
