### ISSUE TITLE
What about handling this automagically? Or is it already possible and I don't know how?

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2791]
I'm having hard time understanding if and how the below is possible (_and I'm really sorry if this is obvious but I have come back to this after so many days on other technologies 24/7_).

I have this schema:

```graphql
extend type Query {
  playerByID(id: ID!): Player!
}

type Player {
  id: ID!
  name: String!
}
```

Everything works good using this code:

```go
func (r db) PlayerByID(ctx context.Context, tx *ent.Tx, id string) (*ent.Player, error) {
  query := tx.Player.Query().Where(entPlayer.ID(id))

  _, err := query.CollectFields(ctx)
  // handle err

  res, err := query.First(ctx)
  // handle err

  return res, nil
}
```

Now I need to use this schema instead:

```graphql
extend type Query {
  playerByID(id: ID!): Player!
}

type Player {
  id: ID!
  name: String!
  teams(direction: OrderDirection!, field: TeamOrderField!): [Teams!]
}

enum OrderDirection {
  ASC
  DESC
}

enum TeamOrderField {
  CREATED_AT
  NAME
}
```

And I'm wondering how to do.

I think I can create a new resolver with `gqlgen` adding in `gqlgen.yml`:

```yml
Player:
  fields:
    teams:
      resolver: true
```

and then I can call ent in the new resolver, as usual:

```go
func (r *playerResolver) Teams(ctx context.Context, obj *gqlgen.Player, direction gqlgen.Direction, field: gqlgen.TeamOrderField) ([]*gqlgen.Team, error) {
  // call Ent here
}
```

1. Am I right?

1. **What do you think about an alternative way to do this, instead of creating new resolvers each time? Can we have a method like `CollectFields(ctx)` that handle all this automagically?**

What do you suggest?

**Comment by a8m** [comment]
Hey @frederikhors 👋 

Why not use the [Node API](https://entgo.io/docs/tutorial-todo-gql-node/) for getting nodes by their IDs? It already handles the field collection for you in an efficient way. 

In case your app does not support "global unique ids", you can still implement this resolver (`<T>ByID`) with a static `NodeType` as an argument:

```go
func (r *queryResolver) Node(ctx context.Context, id string) (ent.Noder, error) {
	return r.client.Noder(ctx, id, ent.WithFixedNodeType(player.Table))
}
```
See example [here](https://github.com/ent/contrib/blob/master/entgql/internal/todouuid/ent.resolvers.go#L29-L35).

**Comment by frederikhors** [comment]
I'm not understanding.

Does this apply to my case, to the query I posted?

**Comment by a8m** [comment]
Yes. There's a generic function named `Node(s)` used to get any node by its id. 

I also recommend to use only one `node` query field in your GraphQL schema instead of `<Type>byID` for each type, but it's not mandatory, you can still use `Node` with any type.

**Comment by frederikhors** [comment]
I think I cannot use all this Relay style for now, unfortunately. Also because I think it's a breaking change for graphql schema already in production.

So to answer my questions, apart from this Relay style, there is no other way besides creating a specific resolver for each array I want to sort/filter? Right?

**Comment by a8m** [comment]
You don't need to use Relay in your GraphQL for this. Use the API described in https://github.com/ent/ent/issues/2794#issuecomment-1193837844. It will solve both cases.

**Comment by frederikhors** [comment]
I think I'll study what you're suggesting, I already found https://dev.to/zth/the-magic-of-the-node-interface-4le1.

**Comment by a8m** [comment]
As mentioned above, you can use your existing GraphQL schema with the Go Node API generated by Ent.

Closing as there are no action items for us here. Thanks ❤️
