### ISSUE TITLE
If I add filters/ordering to a query after `.CollectFields()` it's query is lost forever; would be amazing to merge those queries

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2794]
I just found an "issue" I cannot fix, a "limitation" I cannot resolve.

I'm using `gqlgen` and `entGql` and this below code:

```go
func (r db) TeamByID(
  ctx context.Context,
  tx *ent.Tx,
  id uint64,
) (*ent.Team, error) {
  query := tx.Team.Query().Where(entTeam.ID(id))

  _, err := query.CollectFields(ctx)
  // handle err

  // Here is the problem, I need to order players (only if requested by graphql, like .CollectFields() checks and does)
  // by their age field. If I use the below code I loose the .WithCoach() call that .CollectFields() adds
  // and I'm always querying players even if not requested
  query.WithPlayers(func(q *ent.PlayerQuery) {
    q.Order(ent.Asc(player.FieldAge))
  })

  res, err := query.First(ctx)
  // handle err

  return res, nil
}
```

The graphql query I'm using is:

```graphql
query teamByID($id: ID!) {
  teamByID(id: $id) {
    id
    code
    players {
      id
      firstname
      coach {
        id
        name
      }
    }
  }
}
```

The issue is explained in the Go code:

> // Here is the problem, I need to order players (only if requested by graphql, like .CollectFields() checks and does) by their age field. If I use the below code I loose the .WithCoach() call that .CollectFields() adds and I'm always querying players even if not requested

**Is there a way to "merge" the `.CollectFields()`'s query with my own?**

I don't wanna loose the automagically query produced by `.CollectFields()` but I need to add custom filters/order if **AND ONLY IF** some fields are requested.

Maybe something like:

```go
if query.HasPlayersRequested() {
  query.OrderPlayers(ent.Asc(player.FieldAge))
}
```

Is it already possible?

**Comment by giautm** [comment]
Can you use the default order in GraphQL? Another way, you can use the Ent template to extends the TeamQuery object to add the function:
```go
func (tq *TeamQuery) WithPlayersAgeOrder() *GroupQuery {
	if tq.withPlayers != nil {
		tq.withPlayers.Order(Asc(player.FieldAge))
	}
	return tq
}
```

**Comment by frederikhors** [comment]
> Can you use the default order in GraphQL?

What do you mean? I don't understand...

**Comment by frederikhors** [comment]
I think the second way (`Ent template`) is really difficult, I have tons of them...

**Comment by giautm** [comment]
> > Can you use the default order in GraphQL?
> 
> What do you mean? I don't understand...

It's mean in your GQL scheme default the default value for the `orderBy` field. Then, if someone query that edge, it will be the default for sorting.

**Comment by frederikhors** [comment]
This is the issue I opened for https://github.com/ent/ent/issues/2791. I would like to avoid a new resolver each time.

My query is:

```graphql
query teamByID($id: ID!) {
  teamByID(id: $id) {
    id
    code
    players {
      id
      firstname
      coach {
        id
        name
      }
    }
  }
}
```

and my schema is:

```graphql
type Team {
  id: ID!
  code: String!
  players: [Player!]
}

type Player {
  id: ID!
  firstname: String!
  coach: Coach
}

type Coach {
  id: ID!
  name: String!
}
```

What are you suggesting?

Where should I add the default order? In the schema? How?

Like this?

```graphql
type Team {
  id: ID!
  code: String!
  players(orderBy: SomethingHere): [Player!]
}
```

**Comment by giautm** [comment]
like this, in the schema.
```gql
players(orderBy: {field: AGE, direction: DESC}): [Player!]
```

**Comment by frederikhors** [comment]
I added it. But it doesn't work.

And it doesn't work because obviously how does `.CollectFields()` figure out that `orderBy` is what I want to do?

**Comment by a8m** [comment]
Hey! All the complexity of this query can be solved with one API call mentioned in https://github.com/ent/ent/issues/2791:

```go
node, err := r.client.Noder(ctx, id, ent.WithFixedNodeType(team.Table))
if err != nil{
    return nil, ent.MaskNotFound(err)
}
return node.(*ent.Team), nil
```


Just note that the recommendation is to create one `node` query instead of creating a query field for each type (`teamByID`, `playerByID`, etc). See: https://entgo.io/docs/tutorial-todo-gql-node/

**Comment by frederikhors** [comment]
@a8m thank for your hint on using `Node API`.

I studied about it and added `node()` and `nodes()` to my project using the docs tutorial and reading from examples.

Now I'm trying to use it in my code but I'm still unable to retrieve the correct data.

Given the Go code [in the first post](https://github.com/ent/ent/issues/2794#issue-1316035695) I think my issue cannot be resolved by Node API.

At least that's what I understand so far.

If all I get from the client is an `ID` and a type `Team` how can the code you writed help me?

> ```go
> node, err := r.client.Noder(ctx, id, ent.WithFixedNodeType(team.Table))
> if err != nil{
>     return nil, ent.MaskNotFound(err)
> }
> return node.(*ent.Team), nil
> ```

This works and gives me a `Team`, OK. But what I need is the

```graphql
players: [Player!]
```

ordered by `Age`.

**What am I doing wrong?**

**Comment by a8m** [comment]
The issue was resolved on our Discord server. See https://discord.com/channels/885059418646003782/885059419107360779/1001212955599310911

Please, let us know if you need any help with creating such a [template](https://entgo.io/docs/templates) and @giautm or I can help with it. Something like `MutatePlayer<E>` that accepts a callback and changes the preload:

```go
query.MutatePlayerEdge(func(...) {
    // ...
})
```

A template code for this will roughly look as follows:

```go
{{- range $e := $.Edges }}
	{{ $ebuilder := $e.Type.QueryName }}
	{{ $func := print "Mutate" $e.StructField "Edge" }}
	func ({{ $receiver }} *{{ $builder }}) {{ $func }}(fn func(*{{ $ebuilder }})) *{{ $builder }} {
		fn({{ $receiver }}.{{ $e.EagerLoadField }})
		return {{ $receiver }}
	}
{{- end }}
```

I hope you'll move to auto-bind at some point because it will save you time, code, and queries on the database. Thanks and sorry for the inconvenience ❤️

**Comment by frederikhors** [comment]
Thank you very much. You are truly unique, not just rare. In the open source world all this dedication and kindness are increasingly unavailable.

You are two treasures.

Thanks so much.
