### ISSUE TITLE
Is there any ways to split schemas to different subdirectories?

### ISSUE THREAD

**Issue by seamory** [ent/ent#2795]
there are many schemas in ent/schema directory because the project is expanding. is there any ways to split the schemas to different subdirectories?
for example, the schemas about users save to a independent directroy in ent/schema. and other schemas save to they related directory.

**Comment by seamory** [comment]
I had try some ways to do this, but limit by golang not support cycle reference, this work is failed.
edge back reference will cause cycle reference between different directory.

**Comment by a8m** [comment]
Hey @seamory 👋 

> I had try some ways to do this, but limit by golang not support cycle reference, this work is failed.
> edge back reference will cause cycle reference between different directory.

Exactly! That's an issue and this is one the reasons we don't support it in Ent.

My suggestion is when a project grows, you can keep multiple ent/schemas of the same subject in the same file. For example, a file named `group.go` can hold `Group`, `GroupConfig`, `GroupMembership`, etc.

Another approach is when you want to reuse a schema from a different project (and override some edges or fields), you can import and embed it as a mixed-in schema. See example in [ent/contrib](https://github.com/ent/contrib/blob/master/entgql/internal/todouuid/ent/schema/group.go#L31-L35).

Closing and I hope it helped. Please, you're welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) and talk to us if you need more help 😎

**Comment by seamory** [comment]
> Hey @seamory 👋
> 
> > I had try some ways to do this, but limit by golang not support cycle reference, this work is failed.
> > edge back reference will cause cycle reference between different directory.
> 
> Exactly! That's an issue and this is one the reasons we don't support it in Ent.
> 
> My suggestion is when a project grows, you can keep multiple ent/schemas of the same subject in the same file. For example, a file named `group.go` can hold `Group`, `GroupConfig`, `GroupMembership`, etc.
> 
> Another approach is when you want to reuse a schema from a different project (and override some edges or fields), you can import and embed it as a mixed-in schema. See example in [ent/contrib](https://github.com/ent/contrib/blob/master/entgql/internal/todouuid/ent/schema/group.go#L31-L35).
> 
> Closing and I hope it helped. Please, you're welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) and talk to us if you need more help 😎

Thanks, very useful suggestions.
