### ISSUE TITLE
[docs] Improve about `WithUniversalID()`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2797]
I'm studying the Global Object Identification with Ent.

i found this [in docs](https://entgo.io/docs/migrate#universal-ids):

> If you only have one deployment or all deployments have the exact same data in the ent_types table, you can use WithUniversalID instead. This will enable a file based type range store instead of a database-table as source of truth.

Is `WithUniversalID()` still a thing?

I cannot find anything for it in the entire repo:

![image](https://user-images.githubusercontent.com/41120635/180767629-e225cf8a-d7a0-4f8c-9542-b6bf6a58133b.png)

**How should I use it?**

**Comment by a8m** [comment]
Hey! Please see https://entgo.io/docs/migrate#universal-ids.

**Comment by a8m** [comment]
Hey! Use the `WithGlobalUniqueID` option. `ent_types` file was started as an experimental solution and was deleted. Thanks and sorry for the inconvenience.

**Comment by frederikhors** [comment]
Ok. Should be update the docs?

**Comment by a8m** [comment]
Doc was updated. Thanks for reporting this <3
