### ISSUE TITLE
How to generator complex relationship of objets use ent?

### ISSUE THREAD

**Issue by hhstu** [ent/ent#2802]
Here is the objects such as  user、 group and role

![user_role_group](https://user-images.githubusercontent.com/55697154/181174947-14e0a91a-4231-4bbb-86bf-9f319e4dd390.jpg)

I need help Is there any way to code it ?  The intermediate table is associated with three objects

**Comment by a8m** [comment]
Hey @hhstu 👋. You can use edge schemas for this. Please, see https://entgo.io/docs/schema-edges#edge-schema.

There's also an example of something similar to this in our integration tests - https://github.com/ent/ent/blob/master/entc/integration/edgeschema/ent/schema/relationship.go.

```go
// UserGroup holds the schema definition for the UserGroup entity.
type UserGroup struct {
	ent.Schema
}

func (UserGroup) Annotations() []schema.Annotation {
	return []schema.Annotation{
		field.ID("user_id", "relative_id"),
	}
}

// Fields of the UserGroup.
func (UserGroup) Fields() []ent.Field {
	return []ent.Field{
		field.Time("created_at").
			Default(time.Now),

		// Edge fields for the fields that compose this edge.
		// They also function as the primary key of the table.
		field.Int("user_id"),
		field.Int("group_id"),

		// An edge field to external node that holds
		// additional information about this edge.
		field.Int("role_id").
			Optional(),
	}
}

// Edges of the UserGroup.
func (UserGroup) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("user", User.Type).
			Unique().
			Required().
			Field("user_id"),
		edge.To("group", Group.Type).
			Unique().
			Required().
			Field("group_id"),

		// An optional edge to an entity that holds
		// information about the role.
		edge.To("role", Role.Type).
			Field("role_id").
			Unique(),
	}
}
```

Closing, but please feel free to join our [Discord server](https://discord.gg/qZmPgTE6RX) if you need more help with this example. Thanks 🙏

**Comment by hhstu** [comment]
it may not work for me.   example:  user1 in group1 has role1, user1 in group1 has role2,   but (now user_id  unique group_id) is  @a8m
