### ISSUE TITLE
Mysql char type is TypeOther, which causes an error when my field has a default value and the character type is changed from CHAR to VARCHAR

### ISSUE THREAD

**Issue by mistory816** [ent/ent#2812]
Mysql char type is TypeOther, which causes an error when my field has a default value and the character type is changed from CHAR to VARCHAR

`>FATAL msg=failed creating schema resources: sql/schema: mysql: unsupported default type: other default to "aaaa"` 

https://github.com/ent/ent/blob/f5568d2825c45db0f50e1e2bb56ac6ca7a5accc9/dialect/sql/schema/mysql.go#L490

**Comment by a8m** [comment]
Hey @mistory816 👋 
What version do you use? Can you please update Ent to the latest master and report if you still face this issue? Thanks

**Comment by mistory816** [comment]
sorry，My version is v0.10.1  
It works fine for  v0.11.0
