### ISSUE TITLE
To update the GraphQL documentation to reflect the latest changes in the entgql

### ISSUE THREAD

**Issue by Albert-Gao** [ent/ent#2814]
Doc:
https://entgo.io/docs/tutorial-todo-gql-paginate

Needs to add the usage of `entgql.RelayConnection` in terms of:

1. What does the Relay Connection look like?
2. How much spec can `entgql.RelayConnection()` cover? 
3. How to customise the pieces (I guess the only piece that needs potential customisation is the orderBy field)?

**Comment by a8m** [comment]
Thanks for opening this @Albert-Gao. Solved with #2915
