### ISSUE TITLE
entc/load: load schema dir: missing package information for: ./schema ?

### ISSUE THREAD

**Issue by shumintao** [ent/ent#2815]
- go version

```
╰─± go version 
go version go1.18 darwin/arm64
```

- ent version

```
go install entgo.io/ent/cmd/ent@latest
```

- create ent 

```
ent init User
-------------
╰─± tree ./ent 
./ent
├── generate.go
└── schema
    └── user.go

1 directory, 2 files
```

- cause error 

```
╰─± ent generate ./ent 
entc/load: load schema dir: missing package information for: ./ent
```

No matter how you create it, keep getting this error?

-  After downloading the source code and compiling ent, it will report an error?
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/26895243/181918083-d01fed6e-12c3-4b0c-a18f-5a7e82794134.png">

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/26895243/181918199-492b820c-0fc6-4e00-b7a3-4750ce7d5018.png">

**Comment by shumintao** [comment]
this problem has been solved, I found that I need to add `sudo` on mac m1.
otherwise the file cannot be read.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/26895243/181918808-c3178612-c4cc-47e3-ac2c-f843897ae130.png">

**Comment by a8m** [comment]
Thanks for reporting this @shumintao 🙏 

I think we can close this as it was resolved and not really an Ent issue. Please, feel free to join our [Discrod server](https://discord.gg/qZmPgTE6RX) if you need more help with this.

**Comment by freedomy** [comment]
I have the save problem on windows10,  ent version v0.11.3, but when i  go back to the verison v0.10.1, it works. I think there must be some differences between the two versions and cause the problem.
