### ISSUE TITLE
Versioned migrate option `WithDialect` is not working

### ISSUE THREAD

**Issue by Pranc1ngPegasus** [ent/ent#2818]
I am adding the `WithDialect` option to the sample code as shown.
This result is `sql/sqlclient: no opener was register with name \"postgresql\"`.
`schema.MigrateOption` seems to be applied at here. https://github.com/ent/ent/blob/5df06f49c14060d34a8d9469ad25a527735ac598/dialect/sql/schema/atlas.go#L84-L86
`WithDialect` option must be applied at here, but my sample code applied DSN scheme because error message showed that dialect is`postgresql`.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior 🤔

Migrations files should be created with DSN which has `postgresql` scheme.

## Steps to Reproduce 🕹

```go
package main

import (
    "context"
    "log"

    "<project>/ent/migrate"

    "ariga.io/atlas/sql/sqltool"
    "entgo.io/ent/dialect"
    "entgo.io/ent/dialect/sql/schema"
    _ "github.com/lib/pq"
)

func main() {
    ctx := context.Background()
    dir, err := sqltool.NewGolangMigrateDir("migrations")
    if err != nil {
        log.Fatalf("failed creating atlas migration directory: %v", err)
    }

    opts := []schema.MigrateOption{
        schema.WithDir(dir),
        schema.WithMigrationMode(schema.ModeReplay),
        schema.WithDialect(dialect.Postgres),
    }

    err = migrate.NamedDiff(ctx, "postgresql://user:pass@localhost:5432/my_database?sslmode=disable", "my_migration", opts...)
    if err != nil {
        log.Fatalf("failed generating migration file: %v", err)
    }
}
```

Steps:

1. run PostgreSQL on your local environment.
2. go run ./path/to/main.go

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | 0.11.1   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/lib/pq        |

**Comment by a8m** [comment]
Hey @Pranc1ngPegasus 👋 
Your code imports `mysql` driver instead of `postgres`. Please, do the following change:

```diff
+    _ "github.com/lib/pq"
-    _ "github.com/go-sql-driver/mysql"
```

**Comment by Pranc1ngPegasus** [comment]
> Hey @Pranc1ngPegasus 👋 Your code imports `mysql` driver instead of `postgres`. Please, do the following change:
> 
> ```diff
> +    _ "github.com/lib/pq"
> -    _ "github.com/go-sql-driver/mysql"
> ```

@a8m Thank you for your comments. My sample code was wrong and now it fixed.

**Comment by a8m** [comment]
Great. I guess we can close it then. Please, feel free to join our cur Discord community: https://discord.gg/qZmPgTE6RX

**Comment by Pranc1ngPegasus** [comment]
@a8m Please wait for close this issue. My sample code only at PR description was wrong. My local code imports `github.com/lib/pq` perfectly.

**Comment by a8m** [comment]
Please, add also the following import and report if that solves the issue:

```
_ "ariga.io/atlas/sql/postgres"
```

**Comment by Pranc1ngPegasus** [comment]
@a8m 
The result is same`sql/sqlclient: no opener was register with name \"postgresql\"`.
My code is now as shown.

```go
package main

import (
	"context"

	"<project>/ent/migrate"
	"go.uber.org/zap"

	_ "ariga.io/atlas/sql/postgres"
	"ariga.io/atlas/sql/sqltool"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/schema"
)

func main() {
	app, err := initialize()
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	dir, err := sqltool.NewGolangMigrateDir("migrations")
	if err != nil {
		app.logger.Error("Failed creating atlas migration directory", zap.Error(err))

		return
	}

	opts := []schema.MigrateOption{
		schema.WithDir(dir),
		schema.WithMigrationMode(schema.ModeReplay),
		schema.WithDialect(dialect.Postgres),
	}

	err = migrate.NamedDiff(ctx, app.config.DSN, "migrations", opts...)
	if err != nil {
		app.logger.Error("Failed generating migration file", zap.Error(err))

		return
	}
}
```

**Comment by Pranc1ngPegasus** [comment]
@a8m Thank you for describe clearly.
My code is now as shown. But problem is now solved again.

```go
package main

import (
	"context"

	"<project>/ent/migrate"
	"go.uber.org/zap"

	_ "ariga.io/atlas/sql/postgres"
	"ariga.io/atlas/sql/sqltool"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/schema"
	_ "github.com/lib/pq"
)

func main() {
	app, err := initialize()
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	dir, err := sqltool.NewGolangMigrateDir("migrations")
	if err != nil {
		app.logger.Error("Failed creating atlas migration directory", zap.Error(err))

		return
	}

	opts := []schema.MigrateOption{
		schema.WithDir(dir),
		schema.WithMigrationMode(schema.ModeReplay),
		schema.WithDialect(dialect.Postgres),
	}

	err = migrate.NamedDiff(ctx, app.config.DSN, "migrations", opts...)
	if err != nil {
		app.logger.Error("Failed generating migration file", zap.Error(err))

		return
	}
}
```

**Comment by Pranc1ngPegasus** [comment]
When using `postgres` then it solved.
