### ISSUE TITLE
FilterFunc does not get executed on M2M edges

### ISSUE THREAD

**Issue by Albert-Gao** [ent/ent#2827]
First thing first, thanks for this awesome library! Totally love it!

I currently have a problem. I am wondering why this privacy is NOT get executed at all on the tenant entity.

![image](https://user-images.githubusercontent.com/18282328/182698305-3fcd1660-5ddb-4c80-9292-d987b44f7b1f.png)

I am doing a graphql query to `user {profiles{} tenants{}}`

the filtering rule for profiles works great, but the same setup with a different filter function like (rules.FilterTenantRule()) skips completely on the tenant during the above graphQL query, and the code does not execute at all

Might found the problem, in the generated code, the profiles are using query.All(), but the tenants are using query.sqlAll() which might bypass all the privacy. the user-tenants edge is a M2M on both ends, is it caused the generated code to be sqlAll().

![image](https://user-images.githubusercontent.com/18282328/182698415-d08821ef-a301-4e27-a834-7009973b1edd.png)

## I put together a repo for reproducing this: https://github.com/Albert-Gao/ent-reproduce

Thanks again for this awesome, let me see what I can do more to make it better! :)

**Comment by a8m** [comment]
Thanks for reporting this @Albert-Gao. It's a bug that was introduced with the latest eager-loading change. Thanks 🙏
