### ISSUE TITLE
I want to update items use orderBy  with entgo

### ISSUE THREAD

**Issue by houko** [ent/ent#2830]
what should I do with entogo?
for example:
`UPDATE t SET id = id + 1 ORDER BY id DESC;
`

`client.User.Update().SetId(id+1).Exec();`

I can't find `Order` func

**Comment by syssam** [comment]
why need add order by on the update statement

**Comment by houko** [comment]
company’s businesses logic

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by a8m** [comment]
Hey @houko and thanks for opening this issue.

Since this is a MySQL thing and it's really rarely used, we can support this with custom modifiers. Let me know if you need help with this.

**Comment by houko** [comment]
> Hey @houko and thanks for opening this issue.
> 
> Since this is a MySQL thing and it's really rarely used, we can support this with custom modifiers. Let me know if you need help with this.

yes, I want to know how to do it, thank you very much

**Comment by a8m** [comment]
Please, update Ent to the latest master and use the `sql/modifier` feature flag for this. See: https://entgo.io/docs/feature-flags#modify-example-6

**Comment by houko** [comment]
@a8m  I am sorry about that `sql/modifier` add `Modify` method to query, but I want to update my data with orderBy

**Comment by a8m** [comment]
Please, see the examples in the link:

~~~go
client.User.Update().
    Modify(func(u *sql.UpdateBuilder) {
        u.Set(user.FieldID, sql.ExprFunc(func(b *sql.Builder) {
            b.Ident(user.FieldID).WriteOp(sql.OpAdd).Arg(1)
        }))
        u.OrderBy(sql.Desc(user.FieldID))
    }).
    ExecX(ctx)
~~~

**Comment by houko** [comment]
> Please, see the example in the link above:
> 
> ```go
> client.User.Update().
>     Modify(func(u *sql.UpdateBuilder) {
>         u.Set(user.FieldID, sql.ExprFunc(func(b *sql.Builder) {
>             b.Ident(user.FieldID).WriteOp(sql.OpAdd).Arg(1)
>         }))
>         u.OrderBy(sql.Desc(user.FieldID))
>     }).
>     ExecX(ctx)
> ```

thank you for your reply .
But I did it just generated the Modify function in the query, may I miss some operation?

entgo 0.11.1

<img width="525" alt="image" src="https://user-images.githubusercontent.com/12625278/183345377-fe426eab-c683-4a1b-bdca-bd8aff7fdc6c.png">

**Comment by a8m** [comment]
Please, upgrade to the latest master: go get entgo.io/ent@master

**Comment by houko** [comment]
@a8m yes,I can do it. 
thank you very much.
