### ISSUE TITLE
Doesn't `field.Other` support default annotation?

### ISSUE THREAD

**Issue by knight7024** [ent/ent#2837]
I'm trying to bind MySQL `DATETIME` with formatted string(yyyy-MM-dd hh:mm:ss). So I made a custom type and implemented `ValueScanner`, and fortunately it almost works.

However, it does not work even though I specified the default expression for `field.Other`. I upload the code I wrote and the generated query, so please help me.

`Mixin`
```go
// Fields of the DateTimeMixin.
func (DateTimeMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Other("created_at", util.Datetime("")).
			Annotations(&entsql.Annotation{
				Default: "CURRENT_TIMESTAMP",
			}).
			SchemaType(map[string]string{
				dialect.MySQL:    "DATETIME",
				dialect.SQLite:   "DATETIME",
				dialect.Postgres: "TIMESTAMP",
			}).
			Immutable().Default(util.NowDatetime),
		field.Other("updated_at", util.Datetime("")).
			Annotations(&entsql.Annotation{
				Default: "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
			}).
			SchemaType(map[string]string{
				dialect.MySQL:    "DATETIME",
				dialect.SQLite:   "DATETIME",
				dialect.Postgres: "TIMESTAMP",
			}).
			Immutable().Default(util.NowDatetime),
	}
}
```

`Custom type`
```go
type Datetime string

func (d *Datetime) Scan(src interface{}) error {
	if src == nil {
		*d = TimeToDatetime(time.Now())
		return nil
	}
	switch src := src.(type) {
	case string:
		*d = Datetime(src)
		return nil
	case time.Time:
		*d = TimeToDatetime(src)
		return nil
	}

	return fmt.Errorf("cannot scan %T", src)
}

func (d Datetime) Value() (driver.Value, error) {
	return d, nil
}

func NowDatetime() Datetime {
	return TimeToDatetime(time.Now())
}

// TimeToDatetime converts `time` to `yyyy-MM-dd hh:mm:ss` formatted string
func TimeToDatetime(time time.Time) Datetime {
	return Datetime(time.Format("2006-01-02 15:04:05"))
}
```

`Generated Query`
```sql
BEGIN;
CREATE TABLE `projects` (`id` bigint NOT NULL AUTO_INCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `deleted_at` datetime NULL, `deleted_by` varchar(255) NULL, 
`project_name` varchar(128) NOT NULL, `project_id` varchar(255) NOT NULL, `credentials` blob NOT NULL, `user_id` bigint NOT NULL, PRIMARY KEY (`id`), CONSTRAINT `projects_users_projects` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) 
ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_bin;
COMMIT;
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.11.2   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @knight7024 and thanks for reporting this. Please, see [this example](https://github.com/ent/ent/blob/master/entc/integration/ent/schema/fieldtype.go#L102-L107) and let me know what's not working besides the `ON_UPDATE` clause.

**Comment by giautm** [comment]
Hey @knight7024, you may not need to use a custom type to format/parse MySQL time. Do you try `parseTime=true` yet?

https://github.com/go-sql-driver/mysql#parsetime

**Comment by knight7024** [comment]
@giautm Thank you for your answer. I tried it but what I just want is return `yyyy-MM-dd hh:mm:ss` formatted string when the REST API called. So I solved it by below code. Is there any better solution?

```go
		field.Time("created_at").
			Annotations(&entsql.Annotation{
				Default: "CURRENT_TIMESTAMP",
			}).
			SchemaType(map[string]string{
				dialect.MySQL:    "DATETIME",
				dialect.SQLite:   "DATETIME",
				dialect.Postgres: "TIMESTAMP",
			}).
			GoType(util.Datetime("")).
			Immutable().Default(util.NowDatetime),
```

**Comment by a8m** [comment]
The solution looks good. However, I'm not sure the `SchemaType` is needed. 

Closing as the issue was resolved. Thanks, and please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) 😎
