### ISSUE TITLE
interface conversion: interface {} is string, not *entgen.Cursor when doing GraphQL Relay connection query

### ISSUE THREAD

**Issue by Albert-Gao** [ent/ent#2838]
### reproduce repo: https://github.com/Albert-Gao/ent-reproduce/tree/gql

When doing a GraphQL call with a cursor for Relay spec connection, throws error

For example

**This one works**

```graphql
query user {
  node(id: "user_2D8MrI9P39N18Xq5RBc0F45HYVw") {
    ... on User {
      id
      profiles {
        edges {
          node {
            id
            ownerID
            tenantID
          }
        }
      }
    }
  }
}
```

**This one NOT works**

```graphql
query user {
  node(id: "user_2D8MrI9P39N18Xq5RBc0F45HYVw") {
    ... on User {
      id
      profiles(first: 50, after: "profile_2D8MrHIsrHobAOCXaAtoF13ahIJ") {
        edges {
          node {
            id
            ownerID
            tenantID
          }
        }
      }
    }
  }
}
```

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/18282328/183754788-46ce1071-695d-4fe8-9865-e96a65607455.png">

**Comment by amrnt** [comment]
This is same as this: https://github.com/ent/ent/issues/2839
For solution: https://github.com/ent/ent/issues/2839#issuecomment-1210279400
