### ISSUE TITLE
'go generate ./ent' fails on table with multiple foreign keys to same foreign table

### ISSUE THREAD

**Issue by damdai** [ent/ent#2843]
It seems a table is not allowed to have more than 1 foreign key to the same foreign table.

For example, consider the following database consisting of 2 tables, players and matches:
```
players {
  id
}

matches {
  id
  p1_id //FK to players
  P2_id //FK to players
}
```

Using `entimport` to generate ent schemas for this db generates the following for the matches table:
```
func (Match) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int32("p1_id").Optional(), field.Int32("p2_id").Optional()}
}
func (Match) Edges() []ent.Edge {
	return []ent.Edge{edge.From("player", Player.Type).Ref("matches").Unique().Field("p1_id"), edge.From("player", Player.Type).Ref("matches").Unique().Field("p2_id")}
}
```

Next step is to run `go generate ./ent` which fails with the following error: `entc/gen: Match schema contains multiple "Player" edges`

**Comment by shota-hizawa** [comment]
Hi, @damdai 

```go
type Player struct {
	ent.Schema
}

type Match struct {
	ent.Schema
}

func (Match) Fields() []ent.Field {
	return []ent.Field{
		field.Int("p1_id").Optional(),
		field.Int("p2_id").Optional(),
	}
}

func (Match) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("p1", Player.Type).
			Field("p1_id").
			Unique(),
		edge.To("p2", Player.Type).
			Field("p2_id").
			Unique(),
	}
}
```

Maybe you can achieve what you want by this.

**Comment by damdai** [comment]
That appears to have worked, thanks! 
So this is more an issue with `entimport`'s code generation I suppose.

**Comment by a8m** [comment]
> That appears to have worked, thanks! So this is more an issue with `entimport`'s code generation I suppose.

Closing it then. Thank for the support @shota-hizawa and thanks for reporting this @damdai.
