### ISSUE TITLE
storing versions with mutation hook?

### ISSUE THREAD

**Issue by shota-hizawa** [ent/ent#2844]
I want to store the historical information of one table in another table.
For example, I want to store the history of table `settings` in history table `setting-versions`.

To do this, I am thinking of using the schema mutation hook, but is there any way to insert a record to another schema within the mutation hook for a particular schema like below?

```go
func (Setting) Hooks() []ent.Hook {
	return []ent.Hook{
		func(next ent.Mutator) ent.Mutator {
			return hook.SettingFunc(func(ctx context.Context, m *gen.SettingMutation) (ent.Value, error) {
                                 // get create/update mutation information for `Setting`, or query old data  of the schema here
                                 // then, do some operations to insert version data to `SettingVersion` schema here. However, I have no idea to do this.
				return next.Mutate(ctx, m)
			})
		},
	}
}
```

Or if there is a better way, I would like to know.

**Comment by rotemtam** [comment]
Hey @shota-hizawa 
Thanks for reaching out.
You can read about our approach to the problem in this blog post:

https://entgo.io/blog/2022/04/07/how-twitter-can-implement

In the post you'll find a link to an example repo with some code examples. 

We will most likely work on open sourcing an official Ent extension for enthistory in the future, but in the meantime this can get you started.

**Comment by a8m** [comment]
Hey @shota-hizawa 👋 
Like Rotem mentioned, `enthisotry` is a great reference for such an implementation. But for your question, this can be implemented as follows:

```go
h := hook.SettingFunc(func(ctx context.Context, m *gen.SettingMutation) (ent.Value, error) {
	tx, err := m.Tx() // Or, m.Client()
	if err != nil {
		// Fail if the operation is not running within a transaction.
		return nil, err
	}
	// Save another record in the setting-versions table.
	if err := tx.SettingVersion.Create().Set...().Exec(ctx); err != nil {
		return nil, err
	}
	return next.Mutate(ctx, m)
})
```

Please, let me know if you need more help or we can close this issue. Thanks 🙏

**Comment by a8m** [comment]
Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎

**Comment by shota-hizawa** [comment]
Hi, @rotemtam @a8m 
I appreciate your quick reply.

These sample codes really helped me!
I am also looking forward to `enthisotry` feature will be released☺

Thank you.
