### ISSUE TITLE
ent.Open() does not throw an error on connection error

### ISSUE THREAD

**Issue by kompetenzlandkarte** [ent/ent#2863]
Hi folks,

after calling `ent.Open(dialect.Postgres, "host=<host> port=<port> user=<user> dbname=<database> password=<pass>")` I don't get an error besides the fact that the database is offline/ not reachable.

Is there maybe another way to check if the connection was made successfully?

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

see above

## Expected Behavior 🤔

Error object containing `connection timeout error`.

## Steps to Reproduce 🕹

```golang
client, err := ent.Open(dialect.Postgres, "host=<host> port=<port> user=<user> dbname=<database> password=<pass>")
	if err != nil {
		log.Fatal(err)
	}
```
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.11.2   |
| Database    | MySQL/ Postgres   |
| Driver      | https://github.com/go-sql-driver/mysql  /     github.com/lib/pq (tried both)  |

**Comment by a8m** [comment]
Hey @kompetenzlandkarte and thanks for opening this issue 🙏 

The underlying implementation calls `sql.Open` (see [dialect/sql.Open](https://github.com/ent/ent/blob/master/dialect/sql/driver.go#L30)). That means, there's no special call to `Ping` or something as this is the default behavior of `sql.DB` (opens a connection when it's needed). 

In case you're interested in something like "pinging the database" at the start of the application, I'll suggest you using [`sql.DB` with Ent](https://entgo.io/docs/sql-integration#configure-sqldb).

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎
