### ISSUE TITLE
Inconsistent and quoted schema generation for Default annotation

### ISSUE THREAD

**Issue by hackinteach** [ent/ent#2870]
When I want to add `DEFAULT NULL` statement in the generated SQL migration files, the output is `'NULL'` (null-string) for the int field but `"NULL"` (with double quote) for time field. 
Edit: disclaimer: I was trying to replicate a DDL and came after this issue although knowing that `DEFAULT NULL` might have no effect on the nullable column anyway. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Field with type time has `DEFAULT "NULL"` append to the migration script while 
![Screen Shot 2565-08-19 at 15 41 43](https://user-images.githubusercontent.com/2115896/185580547-2abd19fc-7c81-4a7a-b040-3ca5d88016dd.png)

## Expected Behavior 🤔
The expected behavior should be `DEFAULT NULL`, actual NULL value for the migration file.

![Screen Shot 2565-08-19 at 15 34 27](https://user-images.githubusercontent.com/2115896/185579126-23fdc3eb-d453-482f-ab95-09ef2eaf51c1.png)

## Steps to Reproduce 🕹

add these fields into one of the model
```go
// File: ent/schema/sample.go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/field"
)

type Sample struct {
	ent.Schema
}

func (Sample) Fields() []ent.Field {
	return []ent.Field{
		field.Time("start_datetime").
			Optional().
			SchemaType(map[string]string{
				dialect.MySQL: "datetime",
			}).
			Annotations(&entsql.Annotation{Default: "NULL"}),
		field.Int("hours_window").
			Optional().
			Annotations(&entsql.Annotation{Default: "NULL"}),
	}
}
```
then run `go generate ./ent`

Steps:

1. Add code above in the ent/schema/sample.go file
2. Add following features to entc.go: `FeatureVersionedMigration` and `FeatureUpsert`
3. Run `go generate ent/`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.4  |
| Ent         | 0.11.1 |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by masseelch** [comment]
Hey @hackinteach, thank you for reporting this. 

First of all, all of the following SQL statements are semantically the same:

1. `DATETIME NULL`
2.` DATETIME DEFAULT NULL`
3. `DATETIME NULL DEFAULT NULL`

This means, that in your case simply defining your schema like this, is enough: 

```go
// File: ent/schema/sample.go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/field"
)

type Sample struct {
	ent.Schema
}

func (Sample) Fields() []ent.Field {
	return []ent.Field{
		field.Time("start_datetime").
			Optional().
			SchemaType(map[string]string{
				dialect.MySQL: "datetime",
			}),
		field.Int("hours_window").
			Optional(),
	}
}
```

The `Default` field of the `entsql.Annotation` struct is meant to be used for literal default values, that you want to set at database level. I hope this answer helps you, if not, please write me again.
