### ISSUE TITLE
How to regenerate ent subdirs

### ISSUE THREAD

**Issue by realcp1018** [ent/ent#2883]
https://entgo.io/docs/getting-started
Hi, I create a user schema with `go run -mod=mod entgo.io/ent/cmd/ent init User`, then run `go generate ./ent` and get a lot of subdirs in ./ent .
After some tests I changed the Fields() definition in `ent/schema/user.go`(add some new fields), and delete all other files except `ent/schema/user.go`, then I rerun  `go generate ./ent`  but nothing happened.
Q1: What can I do to recreate all the generated code?
Q2: What should I do if I want to modify fields after  `go generate ./ent`?

**Comment by realcp1018** [comment]
Q2 pass, no need to delete files after user.go changed, just rerun `go generate ./ent`.

**Comment by masseelch** [comment]
Hey @realcp1018, thank you for being here.

> Q1: What can I do to recreate all the generated code?

The `go run -mod=mod entgo.io/ent/cmd/ent init User` command creates a whole set of files. The most important ones being: `ent/schema/*.go` and `ent/generate.go`. The latter contains a `//go:generate` directive, that executes the code generation when calling `go generate ./ent`. You should not delete that file. You can simply re-create that file and paste the following:

```go
package ent

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema
```

> Q2: What should I do if I want to modify fields after go generate ./ent?

You answered this yourself correctly: run `go generate ./ent`.
