### ISSUE TITLE
`.Not().Where()` not working for `sqljson.HasKey` in `sqlite`

### ISSUE THREAD

**Issue by meain** [ent/ent#2886]
I was trying to do something like below to get all rows with json objects that does not have a specific key but I am not getting any output.

``` go
sql.Dialect(dialect.SQLite).
    Select("*").
    From(sql.Table("test")).Not().
    Where(sqljson.HasKey("j", sqljson.DotPath("a.*.c")))
```

SQLite debug session:
``` sql
SQLite version 3.39.2 2022-07-21 15:24:47
Enter ".help" for usage hints.
sqlite> create table user(name,phone);
sqlite> insert into user (name, phone) values("oz", json('{"cell":"+491765", "home":"+498973"}'));
sqlite> insert into user (name, phone) values("oz", json('{"cell":"+491765"}'));
sqlite> select * from user;
oz|{"cell":"+491765","home":"+498973"}
oz|{"cell":"+491765"}
sqlite> SELECT * FROM `user` WHERE (JSON_EXTRACT(`phone`, "$.home") IS NOT NULL OR JSON_TYPE(`phone`, "$.home") = 'null');
oz|{"cell":"+491765","home":"+498973"}
sqlite> SELECT * FROM `user` WHERE NOT ((JSON_EXTRACT(`phone`, "$.home") IS NOT NULL OR JSON_TYPE(`phone`, "$.home") = 'null')); # ent generates this
sqlite> SELECT * FROM `user` WHERE NOT (JSON_EXTRACT(`phone`, "$.home") IS NOT NULL OR JSON_TYPE(`phone`, "$.home") = 'null');
sqlite> SELECT * FROM `user` WHERE NOT (JSON_EXTRACT(`phone`, "$.home") IS NOT NULL);
oz|{"cell":"+491765"}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Returns 0 zero when calling `Count` on the query with the data above.

## Expected Behavior 🤔

Return 1 zero when calling `Count` on the query with the data above.

## Steps to Reproduce 🕹

Steps:

``` diff
diff --git a/dialect/sql/sqljson/sqljson_test.go b/dialect/sql/sqljson/sqljson_test.go
index 83ebf709..bbcbd0bd 100644
--- a/dialect/sql/sqljson/sqljson_test.go
+++ b/dialect/sql/sqljson/sqljson_test.go
@@ -70,6 +76,13 @@ func TestWritePath(t *testing.T) {
                                Where(sqljson.HasKey("j", sqljson.DotPath("a.*.c"))),
                        wantQuery: "SELECT * FROM `test` WHERE (JSON_EXTRACT(`j`, \"$.a.*.c\") IS NOT NULL OR JSON_TYPE(`j`, \"$.a.*.c\") = 'null')",
                },
+               {
+                       input: sql.Dialect(dialect.SQLite).
+                               Select("*").
+                               From(sql.Table("test")).Not().
+                               Where(sqljson.HasKey("j", sqljson.DotPath("a.*.c"))),
+                       wantQuery: "SELECT * FROM `test` WHERE (JSON_EXTRACT(`j`, \"$.a.*.c\") IS NOT NULL OR JSON_TYPE(`j`, \"$.a.*.c\") = 'null')",
+               },
                {
                        input: sql.Dialect(dialect.SQLite).
```

1. Run test with above patch applied (`wantQuery` is incorrect as of now, I'm not sure what the correct one should be in this case)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.5 |
| Ent         | 0.11.2   |
| Database    | SQLite   |
| Driver      | github.com/mattn/go-sqlite3        |

**Comment by a8m** [comment]
Hey @meain and thanks for reporting this issue. https://github.com/ent/ent/pull/2887 should fix this issue. 

I found out that the SQLite `HasKey` implementation could be simpler and I fixed it. See: https://www.sqlite.org/json1.html#jtype

> The json_type(X,P) function returns the "type" of the element in X that is selected by path P. If the path P in json_type(X,P) selects an element that **does not exist** in X, then this function **returns NULL**.

I'll close this issue once https://github.com/ent/ent/pull/2887  is merged, but please, you're more than welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) 😎
