### ISSUE TITLE
Empty array after upgrade from ent/contrib `v0.3.0` to `v0.3.1`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2889]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I just discovered something that made me tremble with fear.

I'm upgrading from:

```
entgo.io/contrib v0.3.0
entgo.io/ent v0.11.1
```

to:

```
entgo.io/contrib v0.3.1
entgo.io/ent v0.11.2
```

and one query (via graphql) that previously returned:

```json
{
  "gamesList": {
    "edges": [
      {
        "cursor": "gqF21/8Tt2ygYw1JoKFpoTE",
        "node": {
          "id": 1,
          "createdAt": "2022-08-30T01:20:00.082697+02:00",
          "authorID": "77423a4b-e2c6-4a4c-b03b-0f721ec8402f",
          "categoryID": 4,
          "turn": {
            "id": 1,
            "createdAt": "2022-08-30T01:20:00.110627+02:00",
            "authorID": "77423a4b-e2c6-4a4c-b03b-0f721ec8402f",
            "gameID": 1,
            "invoice": {
              "id": 1,
              "createdAt": "2022-08-30T01:20:00.179638+02:00",
              "authorID": "77423a4b-e2c6-4a4c-b03b-0f721ec8402f",
              "state": "APPROVED",
              "turnID": 1,
              "amount": 5200,
              "steps": [
                {
                  "id": 1,
                  "state": "DONE",
                  "dueDate": "2022-09-01T01:20:00.081438+02:00",
                  "invoiceID": 1,
                  "payment": {
                    "id": 1,
                    "createdAt": "2022-08-30T01:20:00.230178+02:00",
                    "amount": 2200,
                    "__typename": "Payment"
                  },
                  "__typename": "InvoiceStep"
                },
                {
                  "id": 2,
                  "state": "DONE",
                  "dueDate": "2022-09-06T01:20:00.081438+02:00",
                  "invoiceID": 1,
                  "payment": {
                    "id": 2,
                    "createdAt": "2022-08-30T01:20:00.283035+02:00",
                    "amount": 3000,
                    "__typename": "Payment"
                  },
                  "__typename": "InvoiceStep"
                }
              ],
              "__typename": "Invoice"
            },
            "__typename": "Turn"
          },
          "__typename": "Game"
        },
        "__typename": "GameEdge"
      }
    ],
    "pageInfo": {
      "hasNextPage": false,
      "hasPreviousPage": false,
      "startCursor": "gqF21/8YSt9AYw1JoKFpoTY",
      "endCursor": "gqF21/8Tt2ygYw1JoKFpoTE",
      "__typename": "PageInfo"
    },
    "__typename": "GameConnection"
  }
}
```

now returns:

```json
{
  "gamesList": {
    "edges": [
      {
        "cursor": "gqF21//ZmtkgYw1IB6FpoTE",
        "node": {
          "id": 1,
          "createdAt": "2022-08-30T01:13:11.912701+02:00",
          "authorID": "35fa749a-658a-48d6-9f01-5564fb273764",
          "categoryID": 3,
          "turn": {
            "id": 1,
            "createdAt": "2022-08-30T01:13:11.95851+02:00",
            "authorID": "35fa749a-658a-48d6-9f01-5564fb273764",
            "gameID": 1,
            "invoice": {
              "id": 1,
              "createdAt": "2022-08-30T01:13:12.081993+02:00",
              "authorID": "35fa749a-658a-48d6-9f01-5564fb273764",
              "state": "APPROVED",
              "turnID": 1,
              "amount": 5200,
              "steps": [], // ----------------> THIS IS EMPTY NOW!
              "__typename": "Invoice"
            },
            "__typename": "Turn"
          },
          "__typename": "Game"
        },
        "__typename": "GameEdge"
      }
    ],
    "pageInfo": {
      "hasNextPage": false,
      "hasPreviousPage": false,
      "startCursor": "gqF21//hvaxAYw1IB6FpoTY",
      "endCursor": "gqF21//ZmtkgYw1IB6FpoTE",
      "__typename": "PageInfo"
    },
    "__typename": "GameConnection"
  }
}
```

Note the empty `"steps": []`.

The code is the same: I only regenerated after the upgrade.

I don't have time now to dig deeper, but do you think you already know what it could be?

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.0  |
| Ent         | entgo.io/contrib v0.3.1, entgo.io/ent v0.11.2  |
| Database    | PG   |
| Driver      | github.com/jackc/pgx/v4 v4.17.1       |

**Comment by a8m** [comment]
Thanks for reporting this @frederikhors. Can you please paste here the GraphQL query?

These are the changes between the 2 versions:
https://github.com/ent/contrib/compare/v0.3.0...v0.3.1, https://github.com/ent/ent/compare/v0.11.1...v0.11.2

**Comment by giautm** [comment]
Hello @frederikhors, can you help us a bit, by upgrading one by one to find where the issue happen? In Ent or EntGQL

**Comment by frederikhors** [comment]
Ok. I have had more time now and after only updating ent from `v0.11.1` to `v0.11.2` **it works**.

The issue is with `entgo.io/contrib v0.3.1` (from `v0.3.0`).

**Comment by frederikhors** [comment]
I tried the commits one by one from https://github.com/ent/contrib/compare/v0.3.0...v0.3.1.

The issue starts from [6af48f80535367b485d99fa25f63daea5caa5d64](https://github.com/ent/contrib/commit/6af48f80535367b485d99fa25f63daea5caa5d64).

**Comment by frederikhors** [comment]
The code is this:

```go
func (db Repo) gameListQuery(ctx context.Context, input query.GameListInput) (*query.GameConnection, error) {
  que := db.Game.Query()

  out, err := que.Paginate(ctx,
    input.Pagination.After,
    input.Pagination.First,
    input.Pagination.Before,
    input.Pagination.Last,
    ent.WithGameInvoice(input.Invoice),
    ent.WithGameFilter(input.Where.Filter),
  )
  //handle err

  return out, nil
}
```

the query is:

```graphql
query gameList($input: GameListInput!) {
  gameList(input: $input) {
    edges {
      cursor
      node {
        id
        createdAt
        authorID
        categoryID
        turn {
          ...TURN
          invoice {
            ...INVOICE
            steps {
              id
              state
              dueDate
              invoiceID
              ...PAYMENT
            }
          }
        }
      }
    }
    pageInfo {
      ...PAGE_INFO
    }
  }
}
```

**Comment by a8m** [comment]
Thanks for the help @frederikhors. @giautm and I will give it a look

**Comment by giautm** [comment]
Hello @frederikhors , can you share the code of steps resolver?

**Comment by a8m** [comment]
> Hello @frederikhors , can you share the code of steps resolver?

No need @frederikhors. We think we found the issue. We're on it now 😎

**Comment by frederikhors** [comment]
> Hello @frederikhors , can you share the code of steps resolver?

I did: https://github.com/ent/ent/issues/2889#issuecomment-1231423758.

**Comment by giautm** [comment]
Hello @frederikhors, This PR may fix your issue. Can you try it? I'm unable to create a test case yet. But do it soon.

https://github.com/ent/contrib/pull/373

**Comment by frederikhors** [comment]
How can I go get it?

**Comment by giautm** [comment]
Use the commit ID `go get entgo.io/contrib@354f83`

**Comment by frederikhors** [comment]
Oh. I didn't think it was possible with PR too (not master branch).

I'm trying right now.

**Comment by frederikhors** [comment]
I'm trygin with 6ebd2e1430a0e5ec1f7277dac0306ffd2edea28d.

**Comment by frederikhors** [comment]
Ok. I can confirm you that with https://github.com/ent/contrib/pull/373/commits/6ebd2e1430a0e5ec1f7277dac0306ffd2edea28d **it doesn't work**. 😢

**Comment by frederikhors** [comment]
> Did you run code generation after updating contrib?

😄 yep! I'm an expert now...

**Comment by giautm** [comment]
> > Did you run code generation after updating contrib?
> 
> 
> 
> 😄 yep! I'm an expert now...
> 
> 
> 
> 

Do you see any change in the code gen of ent?

**Comment by frederikhors** [comment]
Yeah. Plenty of them!

**Comment by a8m** [comment]
@frederikhors, can you paste here the generated code exist in gql_edge.go for loading the Steps() (search for the Steps() method)?

**Comment by frederikhors** [comment]
Before:

```go
func (o *Invoice) Steps(ctx context.Context) ([]*InvoiceStep, error) {
  result, err := o.Edges.StepsOrErr()
  if IsNotLoaded(err) {
    result, err = o.QuerySteps().All(ctx)
  }
  return result, err
}
```

after:

```go
func (o *Invoice) Steps(ctx context.Context) ([]*InvoiceStep, error) {
  result, err := o.NamedSteps(graphql.GetFieldContext(ctx).Field.Alias)
  if IsNotLoaded(err) {
    result, err = o.QuerySteps().All(ctx)
  }
  return result, err
}
```

**Comment by giautm** [comment]
@frederikhors Yes, the changes look correct. Is the issue still happening?

**Comment by frederikhors** [comment]
Yep. From that commit the steps array is empty.

Even with that PR commit.

How can I help you more?

**Comment by giautm** [comment]
> Yep. From that commit the steps array is empty.
> 
> Even with that PR commit.
> 
> How can I help you more?

Wow, Do you have any template that overrides the ent template/or EntGQL template? Can you share it with me (PM via Discord/Telegram/Twitter...)

**Comment by frederikhors** [comment]
Nope. No custom template. All default.

**Comment by giautm** [comment]
> Nope. No custom template. All default.

I'm out of ideas, I need a reproducing repo to debug it. Or can you invite me to your repo? I can sign any confidentiality agreement if you want.

cc @a8m

**Comment by rotemtam** [comment]
@frederikhors, may I suggest that you create a minimal repro of your bug using https://github.com/ent/bug ?

**Comment by frederikhors** [comment]
I don't have time right now. Is not a simple task. I'll as soon as possible.

**Comment by a8m** [comment]
Closing as the issue was resolved a long time ago, and we forgot to close it. Please reopen if you still have any issues with it. Thanks 🙏
