### ISSUE TITLE
Performance problem of `.Exist()` method?

### ISSUE THREAD

**Issue by QuantumGhost** [ent/ent#2891]
Now ent [translate `*ent.FooQuery.Exist()` method into a `COUNT(*)` query](https://github.com/ent/ent/blob/master/entc/gen/template/dialect/sql/query.tmpl#L251-L257). 

However, this may cause performance problem. I'm wondering why not translate it into `.First` and check `ent.IsNotFound(err)`. Is there any particular consideration?

**Comment by a8m** [comment]
Hey @QuantumGhost and thanks for the suggestion, it sounds like a great improvement for Ent.

We can query only the ID field using the `FirstID` API. Would you like contributing it? I’m available in our Discord if you have any question.

**Comment by QuantumGhost** [comment]
Ok. I'll submit a PR later.

**Comment by Aagosh10** [comment]
hello @QuantumGhost @a8m I have created a PR for this - https://github.com/ent/ent/pull/2896. PTAL.

**Comment by a8m** [comment]
Fixed with https://github.com/ent/ent/pull/2896. Thank you both for the suggestion and the fix 🙏 ❤️
