### ISSUE TITLE
about the MySQL 'point' type got garbled

### ISSUE THREAD

**Issue by wonderfate** [ent/ent#2893]
Reproduce : [ent-test-spatial](https://github.com/wonderfate/ent-test-spatial)

The `coords` field is garbled !!!

![image](https://user-images.githubusercontent.com/43459833/187760626-b33db4a9-e372-4f18-8715-03159329c212.png)

```sql
CREATE TABLE `locations` (
	`id` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_bin',
	`coords` POINT NOT NULL,
	`location_children` BIGINT(19) NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `locations_locations_children` (`location_children`) USING BTREE,
	CONSTRAINT `locations_locations_children` FOREIGN KEY (`location_children`) REFERENCES `test`.`locations` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
```

**Comment by a8m** [comment]
Hey @wonderfate 👋 

> The coords field is garbled

That's because the example there uses [WKB](https://github.com/paulmach/orb/tree/master/encoding/wkb) (binary) format. If you don't want to store it as text, use the [WKT](https://github.com/paulmach/orb/tree/master/encoding/wkt) package instead. 

Closing, as it works as expected. Thanks 🙏

**Comment by a8m** [comment]
Some code pointers that may help you:
https://github.com/wonderfate/ent-test-spatial/blob/master/ent/schema/point.go#L24
https://github.com/wonderfate/ent-test-spatial/blob/master/ent/schema/point.go#L34
https://github.com/wonderfate/ent-test-spatial/blob/master/ent/schema/point.go#L41

**Comment by wonderfate** [comment]
> Hey @wonderfate 👋
> 
> > The coords field is garbled
> 
> That's because the example there uses [WKB](https://github.com/paulmach/orb/tree/master/encoding/wkb) (binary) format. If you don't want to store it as text, use the [WKT](https://github.com/paulmach/orb/tree/master/encoding/wkt) package instead.
> 
> Closing, as it works as expected. Thanks 🙏

ohh I see.  thank you so much !!!!

**Comment by wonderfate** [comment]
Hi @a8m  I tried WKT but it still seems to be garbled.

Can you help me, please. If you have free. 

```go
// Scan implements the Scanner interface.
func (p *Point) Scan(value interface{}) error {
	bin, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("invalid binary value for point")
	}

	op, err := wkt.UnmarshalPoint(string(bin))
	if err != nil {
		return err
	}

	fmt.Println(string(bin))
	fmt.Println(op)

	p[0], p[1] = op.X(), op.Y()
	return nil
}

// Value implements the driver Valuer interface.
func (p Point) Value() (driver.Value, error) {
	op := orb.Point{p[0], p[1]}

	val := wkt.Marshal(op)

	return val, nil
}

// FormatParam implements the sql.ParamFormatter interface to tell the SQL
// builder that the placeholder for a Point parameter needs to be formatted.
func (p Point) FormatParam(placeholder string, info *sql.StmtInfo) string {
	if info.Dialect == dialect.MySQL {
		return "ST_GeomFromText(" + placeholder + ")"
	}
	return placeholder
}

// SchemaType defines the schema-type of the Point object.
func (Point) SchemaType() map[string]string {
	return map[string]string{
		dialect.MySQL: "POINT",
	}
}

```
