### ISSUE TITLE
Any ideas to distinguish read/write query for read-replicas?

### ISSUE THREAD

**Issue by dakimura** [ent/ent#2894]
I have 1 primary DB instance and 1 read-replica DB instance for my service, and implemented the load balancing by extending `dialect.Driver` interface like the [example in the official FAQ page](https://entgo.io/docs/faq/#how-to-configure-two-or-more-db-to-separate-read-and-write).

Then I noticed that `Query` function of the interface can be called for write operations, like [this example.](https://github.com/ent/ent/blob/2c63d1d70e6c9ed7648abd1fbfdbfc5a84ff5362/dialect/sql/sqlgraph/graph.go#L1418)
(Note that the `tx` of `c.tx.Query()` can be `nopTx{multiDriver}`, so `c.tx.Query()` can be  = `multiDriver.Query()` = `readReplica.Query()` )

So it can cause `insert XXX: create bulk XXX: insert nodes to table "XXX": pq: cannot execute INSERT in a read-only transaction` error. Any suggestion to avoid this issue?
Let me know if I'm missing anything, any advice is helpful 🙇

**Comment by a8m** [comment]
Hey @dakimura and thank you for raising this issue.

> Note that the tx of c.tx.Query() can be nopTx{multiDriver}

The example in the FAQ page uses the "writer" connection pool for opening the transaction, so in case you want to have `nopTx` you should use the [`dialect.NopTx(d.w)`](https://github.com/ent/ent/blob/master/dialect/dialect.go#L62) when a `Tx` is opened to ensure all read statements (queries) go to the same writer connection pool.


```go
func (d *multiDriver) Tx(ctx context.Context) (dialect.Tx, error) {
    return dialect.NopTx(d.w)
}
```

**Comment by dakimura** [comment]
Thank you for the quick response!! 🙇🙇🙇🙇🙇
Let me close the issue and try your suggestion, I'll re-open this issue if it doesn't solve my issue.
