### ISSUE TITLE
edge-fields (foreign-key columns) do not accept default value

### ISSUE THREAD

**Issue by wonderfate** [ent/ent#2895]
Hi there.

The default value don't work,  I don't know what I'm doing wrong.

## Current Behavior 😯

https://github.com/wonderfate/ent-test-edges/blob/5cfbce566bdc70d00cdd0cc395bbcdb63a250e60/ent/schema/pet.go#L19

https://github.com/wonderfate/ent-test-edges/blob/5cfbce566bdc70d00cdd0cc395bbcdb63a250e60/ent/migrate/schema.go#L14

![image](https://user-images.githubusercontent.com/43459833/188108965-bd7fb174-9728-4120-ac2b-b8405e651439.png)

## Expected Behavior 🤔

![image](https://user-images.githubusercontent.com/43459833/188109275-002f5fd1-36f1-4617-a54f-0ef44262050f.png)

**Comment by a8m** [comment]
Hey @wonderfate and thanks for raising this issue. 

The `Default` value `0` is not valid for foreign-key columns as it violates the foreign-key constraint. An improvement we can add here is to add check/report this in the codegen phase, but not sure it's really needed.

**Comment by wonderfate** [comment]
e.g.  The pets table insert some info when pets at the pet shop. Update the perts table `user_id` after the customer buys pet

**Comment by a8m** [comment]
OK. Setting this field as `Optional` is the way to go (`NULL`able in the database). This way you can query all pets with/out owners, etc.

**Comment by wonderfate** [comment]
Actually I don't want to set to `NULL` in the database, just want to set `DEFAULT 0 NOT NULL`  (It might be like you said it violates the foreign-key constraint)

Do you have any suggestions?

**Comment by a8m** [comment]
It looks like you want to make it optional on creation, but the edge is `Required`. These 2 are mutually exclusive, because `0` ID is not allowed as `DEFAULT` value. If it's a `Required()` edge it must be set on the creation with a real value, not `0` because again, it violates the foreign-key constraint.

**Comment by a8m** [comment]
I think we can close this. If you still need help or want to discuss this, I'm available on our [Discord server](https://discord.gg/qZmPgTE6RX) for any questions.
