### ISSUE TITLE
how to update field with variable

### ISSUE THREAD

**Issue by houko** [ent/ent#2901]
for example, I have the sql as below:
```
SET @i=1;
UPDATE playlist SET `index`=(@i:=@i+1) WHERE playlist_id=1 AND `index`>=1 ORDER BY `index`;
```
I don't know how to do with entgo

thank you very much~

**Comment by a8m** [comment]
Hey @houko 👋 
I just added support for prefixig `UPDATE` statements with custom queries/statements. Please, feel free to update to the latest master and check out the example I added in https://github.com/ent/ent/pull/2904.

**Comment by houko** [comment]
thanks again for quickly reply.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by houko** [comment]
@a8m sorry, I want to know how to enable this feature.
I have updated the version to `v0.11.3-0.20220906143453-1773fc465eed`

**Comment by a8m** [comment]
See the SQL modifiers feature flag: https://entgo.io/docs/feature-flags/#modify-example-6

For your specific example, you can do something as follows:

```go
client.Playlist.Update().
    Where(...).
    Modify(func(u *sql.UpdateBuilder) {
        u.Prefix(sql.Expr("SET @i = 1;"))
        u.Set(playlist.FieldIndex, Expr("(@i:=@i+1)"))
        u.OrderBy(sql.Desc(playlist.FieldIndex))
    }).
    ExecX(ctx)
```

**Comment by houko** [comment]
> See the SQL modifiers feature flag: https://entgo.io/docs/feature-flags/#modify-example-6
> 
> For your specific example, you can do something as follows:
> 
> ```go
> client.Playlist.Update().
>     Where(...).
>     Modify(func(u *sql.UpdateBuilder) {
>         u.Prefix(sql.Expr("SET @i = 1;"))
>         u.Set(playlist.FieldIndex, Expr("(@i:=@i+1)"))
>         u.OrderBy(sql.Desc(playlist.FieldIndex))
>     }).
>     ExecX(ctx)
> ```

that's good, I did it. thank you very much
