### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by shahriarshimul** [ent/ent#2902]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.9.?   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by shahriarshimul** [comment]
There's no need to comment again due to the data compliance mode as long as new file or data is planned to be executed.

**Comment by a8m** [comment]
Hey! Can you elaborate on what the bug is?

**Comment by a8m** [comment]
Hey! I'm not sure what I see here, but please elaborate on what the bug is and how to reproduce it. Thanks 🙏
