### ISSUE TITLE
Add an Index annotation for Postgres INCLUDE clause

### ISSUE THREAD

**Issue by ivanvanderbyl** [ent/ent#2905]
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Add an annotation to support declaring additional fields that should be included in the index, but not indexed. Example:

```
CREATE INDEX idx
    ON sales ( subsidiary_id )
     INCLUDE ( eur_value )
```

More concrete docs: https://www.postgresql.org/docs/current/indexes-index-only-scans.html

## Motivation 🔦

Covering indexes allow the database to answer queries without reading from the backing table for certain queries that it can answer using data only from the index.

**Comment by a8m** [comment]
Hey @ivanvanderby! Happy to see you here again 😎 

Let me check if we can address this quickly.

**Comment by a8m** [comment]
Addressed with https://github.com/ent/ent/pull/2912. Thanks again for suggesting this ❤️
