### ISSUE TITLE
How to get mutation with Schema hooks when using OpUpdate?

### ISSUE THREAD

**Issue by chokoGtr** [ent/ent#2927]
I want to use Schema hooks to store information.
In doing so, when I try to get the mutation with OpUpdate as follows, I get a value of `ent.Value(int)` for val.

``` go
func (User) Hooks() []ent.Hook {
	return []ent.Hook{
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return hook.UserFunc(func(ctx context.Context, m *gen.UserMutation) (ent.Value, error) {
					val, err := next.Mutate(ctx, m)
					if err != nil {
						return nil, err
					}
					// store the historical information of one table in another table.
					// newUser, ok := val.(*gen.User)
					// query := tx.UserVersion.Create()
					// ......
					// err = query.Exec(ctx)
					// if err != nil {
					// 	return nil, errMsgFn(err)
					// }
					return val, nil
				})
			},
			ent.OpUpdate,
		),
	}

```
Perhaps I got the number of hits to the predicate of update.

When I used OpUpdateOne, I could get the value after update by the above method.
If I use OpUpdate, how can I get the value after update?

**Comment by a8m** [comment]
Hey @chokoGtr 👋 

> If I use OpUpdate, how can I get the value after update?

Can you elaborate on what value you want to get? The actual entity(ies)?

**Comment by a8m** [comment]
Use the `ID`/`IDs` method on the `Mutation` object to get the IDs of the nodes/objects that were affected by this mutation. If you want to get the actual entities, use `Mutation.Client()` to get the client from the mutation and query these IDs.

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.
