### ISSUE TITLE
how to query data from multiple table?

### ISSUE THREAD

**Issue by houko** [ent/ent#2930]
for example, now I have two tables. `user` and `preference`.

# user
```
id, username,preference_id
```

# prefenerce
```
id, data
```

the tables relationship is 1O1, that means one user only have one preference.then, I want to query data from two tables.
for example:

```
SELECT
	p.id,
	p.preference_id,
	p.created_at,
	o.data
FROM
	USER p
	INNER JOIN preference o ON p.preference_id = o.id
```

so, what should I do with entgo?

thank you very much.

**Comment by a8m** [comment]
Hey @houko and thanks for opening this issue. 
I'd say that the way to do it in Ent is with [eager-loading](https://entgo.io/docs/eager-load), and you can `Select` specific fields that you want to load.

```go
client.User.Query().
	Select(user.FieldPreferenceID, user.FieldCreatedAt).
	WithPreference(func(q *ent.PreferenceQuery) {
		q.Select(preference.FieldData)
	}).
	All(ctx)
```
However, if you still want to use `JOIN` and scan the result to a custom struct, you can use query modifiers: https://entgo.io/docs/feature-flags#custom-sql-modifiers. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this 😎

**Comment by houko** [comment]
https://discord.com/channels/885059418646003782/885059419107360779/1020165742114644048

I send a message to discord too.
maybe my shema have some mistake.
