### ISSUE TITLE
[HELP] A Field which type is JSON, how to use JSON_ARRAY_APPEND() when executing Update()

### ISSUE THREAD

**Issue by BERZERKCOOLeST** [ent/ent#2941]
- This is the field : `field.JSON("info", &Info{}).Optional()`
- Target sql:  Update `tmp_info` SET `info` = JSON_ARRAY_APPEND(`info`, '$', '1');
- DB: mysql.

Thanks.

**Comment by a8m** [comment]
Hey @BERZERKCOOLeST 👋 
Thanks for opening this issue. The `Append` operation was added for JSON array fields, and you can use the built-in mutation operation: `Append<F>(values...)`. However, in case you want to update nested array values, you can use custom modifiers as described in this example: https://entgo.io/docs/feature-flags#modify-example-7

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.
