### ISSUE TITLE
bug: [entgql] panic because of nil pointer dereference 

### ISSUE THREAD

**Issue by hsblhsn** [ent/ent#2946]
This code snippets below can cause panic when `FieldContext` is `nil`.

```go
func (o *Org) Members(ctx context.Context) ([]*User, error) {
	result, err := o.NamedMembers(graphql.GetFieldContext(ctx).Field.Alias)
	if IsNotLoaded(err) {
		result, err = o.QueryMembers().All(ctx)
	}
	return result, err
}
```

The issue is on the second line. And it's causing by this template https://github.com/ent/contrib/blob/462c4e5698731377eb38f5a61b16518bb7295341/entgql/template/edge.tmpl#L23

A simple fix for this will be:

```diff
func (o *Org) Members(ctx context.Context) ([]*User, error) {
++	fieldAlias := ""
++	if fieldCtx := graphql.GetFieldContext(ctx); fieldCtx != nil {
++		fieldAlias = fieldCtx.Field.Alias
++	}
++	result, err := o.NamedMembers(fieldAlias)
--	result, err := o.NamedMembers(graphql.GetFieldContext(ctx).Field.Alias)
	if IsNotLoaded(err) {
		result, err = o.QueryMembers().All(ctx)
	}
	return result, err
}
```

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | v0.11.3  |
| EntContrib    | v0.3.2   |
| GQLgen      | v0.17.20        |

**Comment by hsblhsn** [comment]
@a8m can you have a look into this? 🙏

**Comment by giautm** [comment]
Hello, can you explain your usecase with the members function? It is intent for using with graphql as the field resolver

**Comment by hsblhsn** [comment]
Thank @giautm! But surprisingly the empty string is working fine for me 😕 
I will update it to use the edge name though!

**Comment by hsblhsn** [comment]
I just pushed the changes!

Now the generated code looks like:

```go
func (o *Org) Members(ctx context.Context) ([]*User, error) {
	gqlAlias := "members"
	if fctx := graphql.GetFieldContext(ctx); fctx != nil {
		gqlAlias = fctx.Field.Alias
	}
	result, err := o.NamedMembers(gqlAlias)
	if IsNotLoaded(err) {
		result, err = o.QueryMembers().All(ctx)
	}
	return result, err
}
```

And this also working fine 🪄

**Comment by giautm** [comment]
I still think the changes are not necessary because you should test the resolver via the GQL client, rather than call it directly.

If you still want to change, please update this line too: https://github.com/ent/contrib/blob/462c4e5698731377eb38f5a61b16518bb7295341/entgql/template/edge.tmpl#L70

cc @a8m, wdyt?

**Comment by hsblhsn** [comment]
Aha! Got it!
I should test it like the way you mentioned instead. It would be better to add this to avoid panics in such scenarios. Still it's kinda unnecessary.

I think this issue and PR can be closed!

**Comment by a8m** [comment]
Thanks for the feedback, @hsblhsn. I actually agree with @giautm, as there are many parts in Ent runtime that relies on correct initializations.

I think we can close this and maybe document GraphQL/entgql testings to avoid misconfiguration.

**Comment by hsblhsn** [comment]
Thank @a8m, closing this 🙏

**Comment by gsoec** [comment]
temporary workaround
```go
import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/vektah/gqlparser/v2/ast"
)

func Test(ctx context.Context) {
	fc := &graphql.FieldContext{
		Field: graphql.CollectedField{
			Field: &ast.Field{},
		},
	}
	ctx = graphql.WithFieldContext(ctx, fc)
        m,err:=org.Members(ctx)
}
```

**Comment by a8m** [comment]
Hey all,
The issue was resolved with https://github.com/ent/contrib/pull/385. Please update to the latest version to get the fix. Thanks
