### ISSUE TITLE
bug: there are 2 unique indexes in the migration file when combining IndexWhere and Unique

### ISSUE THREAD

**Issue by dodangquan** [ent/ent#2949]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- There are 2 unique indexes in the migration file when combining `IndexWhere` and `Unique`
- https://github.com/ent/ent/issues/1472
- https://github.com/ent/ent/pull/2944

## Expected Behavior 🤔

- Only one unique index is generated

## Steps to Reproduce 🕹

- The schema code

```go
func (Pet) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("abc_id").Unique().
			Annotations(
				entsql.IndexWhere(`(((status)::text = 'STATUS_1'::text) OR ((status)::text = 'STATUS_99'::text))`),
			),
	}
}
```

- The migration file is generated
```sql
-- create index "pet_abc_id" to table: "pets"
CREATE UNIQUE INDEX "pet_abc_id" ON "pets" ("abc_id") WHERE (((status)::text = 'STATUS_1'::text) OR ((status)::text = 'STATUS_99'::text));
-- create index "pets_abc_id_key" to table: "pets"
CREATE UNIQUE INDEX "pets_abc_id_key" ON "pets" ("abc_id");
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.1  |
| Ent         | v0.11.3-0.20220922085605-0f5cba6144c7   |
| [atlas](https://github.com/ariga/atlas)         | v0.7.1-0.20220922152615-58d4f7e4f6d3   |
| Database    | Postgres   |
| Driver      | https://github.com/lib/pq/releases/tag/v1.10.7        |

**Comment by a8m** [comment]
Hey @dodangquan, can you please provide a complete example using https://github.com/ent/bug?
