### ISSUE TITLE
Missing column Error on double edge traverse

### ISSUE THREAD

**Issue by vitorfalcaor** [ent/ent#2955]
I am running into an issue when doing a double edge traversal. I have a data model where a User owns multiple Order and Share. I am trying to run the following query: order.QueryUser().QueryShares().Where(share.Symbol(order.Symbol)).Only(ctx), inside a hook. I am getting the following error: `ERROR: could not determine data type of parameter $1 (SQLSTATE 42P18)`. So what I did was to run the query using "Debug": c.Debug().Order.QueryUser(order).QueryShares().All(ctx), which output:

```
SELECT DISTINCT 
	"users"."id",
	"users"."create_time",
	"users"."update_time",
	"users"."name", 
	"users"."email", 
	"users"."password" 
FROM "users" JOIN (
	SELECT
		"shares"."user_shares" 
	FROM "shares" JOIN (
		SELECT
			"users"."id" 
		FROM "users" JOIN (
			SELECT 
				"user_orders" 
			FROM "orders" 
			WHERE "id" = $1
		) AS "t1" 
			ON "users"."id" = "t1"."user_orders"
	) AS "t1" 
		ON "shares"."user_shares" = "t1"."id"
) AS "t1" 
	ON "users"."id" = "t1"."user_shares" LIMIT 2 
```

When I copy this output above and paste it on psql, the query executes normally and returns the expected result, including the create_time column. I am using the entgo doc TimeMixin on all my schemas. I also tried dropping the entire db and re-running the migration, but that didn't work either.

I found out that this error goes away when I remove all of my privacy policies by commenting the `Policy()` declaration in the only schema that currently has a privacy policy: Share

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I get an error saying `ERROR: could not determine data type of parameter $1 (SQLSTATE 42P18)`.

## Expected Behavior 🤔

Query should execute normally, regardless of the privacy policy being enabled.

## Steps to Reproduce 🕹
https://github.com/vitorfalcaor/reInvest-Debug

1. `go run ./server`
2. Go to localhost:8081/graphiql
3. Register:
```
mutation {
	register(input: {name:"Name", email: "your@mail.com", password: "password"}, confirmPassword: "password")
}
```
4. Login:
```
mutation {
	login(email:"your@email.com", password:"password") {
 	  id
	}
}
```
5. Register an Order:
```
mutation {
  registerOrder(symbol:"SYMBOL", type: BUY, date: "2016-01-20T12:43:01.000Z", quantity: 2.0, price: 15.0, currency: USD, brokerage:"Brokerage") {
		id
	}
}
```
6. Check the terminal where you launched prints the error: `ERROR: could not determine data type of parameter $1 (SQLSTATE 42P18)`. The error happens on `schema/Order.go:82`

If you comment out the `Privacy` policy from the `Share` schema, the error goes away.

**Comment by a8m** [comment]
Thanks for reporting this, @vitorfalcaor 🙏 
I'll give it a look and update you.

**Comment by a8m** [comment]
Hey @vitorfalcaor! A quick update on this issue - I found that in your privacy rules, you use the actual query builders for executing queries instead of cloning them. For example: 

```diff
- owner, _ := shareQuery.QueryUser().Only(ctx)
+ owner, _ := shareQuery.Clone().QueryUser().Only(ctx)
```

We maybe can reject this in the builder, but for now, it looks like the issue comes from your privacy rules rather than the engine. Also, I would suggest you to always pass `privacy.DecisionContext(ctx, privacy.Allow)` to queries that go out from the privacy rules to avoid circular privacy checks. 

Closing, but please feel free to reopen or ping me if you still have troubles with it. Thanks 🙏

**Comment by vitorfalcaor** [comment]
Hey @a8m thank you for quickly checking it. I wasn't aware of `query.Clone()`, I'll play around with it today. Thank you for all the support!
