### ISSUE TITLE
Does privacy work with Graph Traversal?

### ISSUE THREAD

**Issue by gsoec** [ent/ent#2957]
In the [examples](https://github.com/ent/ent/tree/master/examples)/[privacytenant](https://github.com/ent/ent/tree/master/examples/privacytenant), When i query
```go
g, _ := ent.User.
    Query().
    Where(user.HasGroupWith(
        group.NameEQ("GroupOne"),
    )).
    First(ctx)
```
And the generated sql
```sql
SELECT 
  user.id,
  user.name 
FROM 
  user 
WHERE 
  user.id IN (
    #This select does not trigger privacy, and group.tenant_id = 1 doesn't apply to the query.
    SELECT 
      group.user_id 
    FROM 
      group
    Where
      group.name = 'GroupOne'
  )
  And  user.tenant_id = 1;
```

**Comment by a8m** [comment]
Hey @gsoec 👋 
Predicates do not trigger privacy rules as they are used only for filtering the traversal/query. i.e., the privacy rules are applied on the query builders to filter or block the potentially returned entities. 

Closing, but please reopen if you found any issue in Ent or you still have questions. You are also welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) and ping me there if want to discuss.

**Comment by gsoec** [comment]
@a8m Thank you for the quick reply.
According to your guidance, i change my code to
```go
g, _ := ent.User.
    Query().
    Where(user.HasGroupWith(
        // Add this line to each use of predicate.
        group.TenantIDEQ(1),
        group.NameEQ("GroupOne"),
    )).
    First(ctx)
```
Without adding `group.TenantIDEQ(1)` to predicates, ent will query groups from all tenants.
Do we need a mechanism similar to `hook` for predicates? 
or clarify in the documentation that predicate dose not work with privacy and hook.
In case for anyone run into this situation, could wrap predicates into a generic function.
```go
func eq(ctx context.Context, s *sql.Selector) *sql.Predicate {
	tenant := tenant.FromContext(ctx)
	if tenant == nil {
		panic("missing tenant in context")
	}
	return sql.EQ(s.C("tenant_id"), tenant.ID)
}

type Predicate interface {
	~func(s *sql.Selector)
}

func Has[T Predicate](ctx context.Context, preds ...T) T {
	eq := T(func(s *sql.Selector) {
		s.Where(eq(ctx, s))
	})
	preds = append(preds, eq)

	and := T(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range preds {
			p(s1)
		}
		s.Where(s1.P())
	})
	return and
}

g, _ := ent.User.
    Query().
    Where(user.HasGroupWith(
        // Connect to the tenant in context.
        Has(
          ctx,
          group.NameEQ("GroupOne"),
        ),
    )).
    First(ctx)
```
