### ISSUE TITLE
Edge fields without unique constraint?

### ISSUE THREAD

**Issue by frostycodez** [ent/ent#2964]
In the User/Tweet/Like examples for edge schemas the generator expects a Unique() and Required() constraint on the Like schema and automatically creates a database index 'like_user_id_tweet_id' to enforce the constraint. However, I need for a User to be able to make multiple likes on a single tweet (with a created_at field on the Like schema). If I remove the Unique() constraint the generator will not let me create the relationship:

`set "Like" foreign-keys: edge "tweet" has a field "tweet_id" but it is not holding a foreign key`

Is it possible to create this relationship without Unique()? I'm still trying to grok how entities map to SQL. Thx.

```
edge.To("user", User.Type).Unique().Required().Field("user_id"),
edge.To("tweet", Tweet.Type).Unique().Required().Field("tweet_id"),
```

**Comment by a8m** [comment]
Hey @frostycodez 👋 
If I understand your use case correctly, it looks like you have an M2M relationship, but with duplicate edges/connections.

If that's the case, I think you can define this relationship table manually and add edges to the target entities - like an edge-schema, but not as an M2M relationship

**Comment by frostycodez** [comment]
Makes sense thx!
