### ISSUE TITLE
How to order custom types 

### ISSUE THREAD

**Issue by ramonmedeiros** [ent/ent#2971]
Have the following table:

Users
name
age
file string (custom type)

This custom type will always return "", even when SQL is null. 

In this example, I will create 3 Users, one with file nil, other with "" and other with "aaaa".

When asking for ORDER_BY file ASC, I got the following result:

first ""
second "aaaa"
third ""

^This happen because SQL by default show null in the end.

Is it possible to ask ent to orderBy using the custom type modification? I would like to have nil and "" be together

https://github.com/ramonmedeiros/bug

**Comment by crossworth** [comment]
Hello, what database are you using?

If you are using Postgres you can use [`NULLS { FIRST | LAST }`](https://www.postgresql.org/docs/current/queries-order.html), if you are using MySQL there are [ways to solve as well](https://www.designcise.com/web/tutorial/how-to-order-null-values-first-or-last-in-mysql), for SQLite [check this link](https://www.sqlite.org/lang_select.html#the_order_by_clause).

Example for Postgres:
```go
users := client.User.Query().Order(func(selector *sql.Selector) {
	selector.OrderExpr(sql.Expr(user.FieldFile + " NULLS FIRST")) // or NULLS LAST
}).AllX(ctx)
```

But maybe the easier way is to change the schema removing the optional and adding a default value:
```go
field.String("file").GoType(bug.File("")).Default(""),
```

This simplifies the problem and you don't need custom order options or tricks to handle null values.
