### ISSUE TITLE
Atlas Versioned Migration not removing or renaming a field if it's been removed or renamed

### ISSUE THREAD

**Issue by nilpntr** [ent/ent#2986]
I would expect Atlas to remove a field if I remove it from the ent definition or if I rename a field I expect Atlas to rename it in the generated sql file to.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Atlas just adds a new field and ignores the renamed or deleted field so you will end up with duplicated fields.

## Expected Behavior 🤔

I would expect Atlas to remove a field if I remove it from the ent definition or if I rename a field I expect Atlas to rename it in the generated sql file to.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.11.3   |
| Database    | PostgreSQL   |
| Driver      | github.com/lib/pq & github.com/jackc/pgx/v4        |

**Comment by giautm** [comment]
Hello @nilpntr, thank for reporting the issue.

There is an option to asking migration engine generate SQL for drop resource. Do you have seen this?
https://entgo.io/docs/migrate#drop-resources

**Comment by nilpntr** [comment]
> Hello @nilpntr, thank for reporting the issue.
> 
> There is an option to asking migration engine generate SQL for drop resource. Do you have seen this? https://entgo.io/docs/migrate#drop-resources

Thanks totally forgot that those options also applied to versioned migrations. Will close the issue!

**Comment by giautm** [comment]
No problem, if you have any other issue. Please reopen it needs. <3
