### ISSUE TITLE
Allow for dynamic queries on arbitrary tables using SQL modifiers

### ISSUE THREAD

**Issue by DeluxeOwl** [ent/ent#2993]
- #1990 might be related

## Motivation 🔦

I was thinking about building an application that lets users generate tables, while still having some tables managed by ent in the compiled Go code, and running operations on the user generated tables (similar to how pocketbase allows you to CRUD generated tables).

I was thinking about having a generic client or allowing the client to specify the table it is selecting from, **while** still having access to sql modifiers and predicates.

## Examples 
1. The closest example I found was this, but not sure how I would do it (`sql.Table` takes a `string` as argument)
```go
users := client.User.Query().
Where(func(s *sql.Selector) {
	t := sql.Table(car.Table)
	s.Where(
		sql.In(
			s.C(user.FieldID),
			sql.Select(t.C(user.FieldID)).From(t).Where(sql.EQ(t.C(car.FieldModel), "Tesla")),
		),
	)
}).
AllX(ctx)
```

A workaround might be having an _emtpy schema_ and using `sql.Table` somehow to get the user generated table? Not sure how that would look in code. 

3. Here, changing the `User` to an arbitrary table name would be nice.
```go
client.User.
    Query().
    Modify(func(s *sql.Selector) {
        s.Select(
            sql.As(sql.Count("*"), "count"),
            sql.As(sql.Sum("price"), "price"),
            sql.As("DATE(created_at)", "created_at"),
        ).
        GroupBy("DATE(created_at)").
        OrderBy(sql.Desc("DATE(created_at)"))
    }).
    ScanX(ctx, &v)
```

**Comment by a8m** [comment]
Hey @DeluxeOwl 👋 
Do these tables have a pre-defined structure defined in the Ent schema? If not, why the `dialect/sql` package is not enough for this case?

If there's a need to change the SQL table on runtime, I'd love to get a proposed design for it in https://github.com/ent/ent/issues/1990 and close this issue. Thanks 🙏

**Comment by DeluxeOwl** [comment]
No, they're arbitrary tables that aren't under ent's control.

I was thinking about having the query builder available on these tables, something like:
```go
t := sql.Table("my_custom_table")
s.Where(
sql.In(
	s.C("userId"),
	sql.Select(t.C("userId")).From(t).Where(sql.EQ(t.C("car_model"), "Tesla")),
),
)
```

Does `dialect/sql` allow this? Is there an example somewhere?
