### ISSUE TITLE
Doc is outdated, sqlite supports dropping or modifying resources when Atlas as default migration engine

### ISSUE THREAD

**Issue by aaftio** [ent/ent#2997]
https://github.com/ent/ent/blob/713828b3116bfeb8d9dc04d5fa1ceceb9ca6d83a/doc/md/dialects.md?plain=1#L26-L30

My poor english can help nothing, so this issue up.

**Comment by a8m** [comment]
Thanks for reporting this, @aaftio. I'll send a patch to fix this.

**Comment by a8m** [comment]
Fixed! Thanks again, and please, feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) ❤️
