### ISSUE TITLE
do we have any tool can parse json or struct to ent.Schema

### ISSUE THREAD

**Issue by godcong** [ent/ent#2998]
like i said,if i have a struct or json:
User
```json
{
  "id":1,
}
```
or
```go
type User struct {
  ID int 
}
```

we can parsed to a schema file:
```go
package schema

import (
    "time"

    "entgo.io/ent"
    "entgo.io/ent/schema/field"
)

// User schema.
type User struct {
    ent.Schema
}

// Fields of the user.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.Int("id"),
    }
}
```

I searched the documentation, but I couldn't find any relevant content

**Comment by a8m** [comment]
Hey @godcong, and thanks for raising up this issue. 

Can you please elaborate on the use case? The input is a JSON or a struct before marshaling, but what is the output? A generated Ent schema? If so, you can construct and print/write one using [contrib/schemast](https://github.com/ent/contrib/tree/master/schemast). [entimport](https://github.com/ariga/entimport) also uses this package.

**Comment by godcong** [comment]
@a8m 

Because I need to convert the data from the previous orm.
Before that I was using xorm, which uses the struct definition.
The `entimport`  one you recommended is also available.
Thanks.

PS: This is my finnally wanted, a `user.go` file in the schema
```go
package schema

import (
    "time"

    "entgo.io/ent"
    "entgo.io/ent/schema/field"
)

// User schema.
type User struct {
    ent.Schema
}

// Fields of the user.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.Int("id"),
    }
}
```
