### ISSUE TITLE
sqlgraph generated query not always the same

### ISSUE THREAD

**Issue by garrettlove8** [ent/ent#3012]
Hey,

So I'm following the tests in the sqlgraph package. Currently, this is my expectation:
`mock.ExpectExec(escape("INSERT INTO 'patient' ('first_name', 'last_name', 'id') VALUES (?, ?, ?)")).`

However the generated SQL from sqlgraph seems to not always be the same.

I.e. Sometimes it comes out like this (or other variations), which causes my tests to fail
`mock.ExpectExec(escape("INSERT INTO 'patient' ('last_name', 'first_name', 'id') VALUES (?, ?, ?)")).`

Is there a way to generate the SQL which guarantees the same query every time, or test it differently?

**Comment by a8m** [comment]
Hey @garrettlove8 👋 
Is it the same case as https://github.com/ent/ent/issues/2779#issuecomment-1191201783? If not, can you please provide a small example that explains the use case?

 > Is there a way to generate the SQL which guarantees the same query every time, or test it differently?

In general, I recommend that you use `enttest` to test your code and not assert on the executed SQL queries. In some cases, like #2600, we may change the generated SQL to improve performance, causing to such tests to fail.

**Comment by a8m** [comment]
Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.
