### ISSUE TITLE
M2M in nested JSON field

### ISSUE THREAD

**Issue by waltcow** [ent/ent#3014]
Hello, I want to know if it is possible to load **edges** with custom mapping logic in subquery (nested JSON Ids array)  in following case

```go
//SysUser
func (SysUser) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id"),
		field.JSON("role_ids", []uint64{}),
                ...
        }

func (SysUser) Edges() []ent.Edge {
    return []ent.Edge{
	edge.To("roles", SysRole.Type) 
   }
}

// SysRole

func (SysRole) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("id"),
		field.String("name"),
                ...
	}
}

```

> 
```go
client := NewTestClient(t)
	user, err := client.SysUser.Query().
		WithRoles().	
		Where(sysuser.ID(2)).
		First(context.Background())

```

**Comment by a8m** [comment]
Hey @waltcow 👋🏻
Yes, you can filter the loaded edges with a custom JSON predicate. See:
https://entgo.io/docs/predicates#json-predicates
https://entgo.io/docs/eager-load

**Comment by waltcow** [comment]
I have enabled `gen.FeatureNamedEdges` in generator flag, but `SysRole` table have back reference to `SysUser`. How can i skip this ? @a8m 

![image](https://user-images.githubusercontent.com/3941174/195806239-5169f28b-cc11-489f-9235-0c89f6f804de.png)

**Comment by a8m** [comment]
In O2M relation, the foreign-key is stored on the “many” side, even if it’s not visible in the generated code. _“Many roles point to a single user”._

If you wish to change it to M2M (a join table), please see: https://entgo.io/docs/schema-edges#m2m-two-types

**Comment by a8m** [comment]
Closing, as it looks like the issue was resolved, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX)  if you need more help with this.

**Comment by waltcow** [comment]
M2M relationship must have a `user_role` table. I want to provide a `WithRoles`  method to load roles that related to user without joining table, but use its nested json (ints) field `roles_ids` to query @a8m
