### ISSUE TITLE
Update can not use limit

### ISSUE THREAD

**Issue by foreverrice** [ent/ent#3017]
It will cause many security problems.

**Comment by a8m** [comment]
Thanks for opening this issue, @foreverrice.
I added support for the `LIMIT` clause in https://github.com/ent/ent/pull/3018, but note that PostgreSQL does not support it, and SQLite needs to be built with the [`SQLITE_ENABLE_UPDATE_DELETE_LIMIT`](https://www.sqlite.org/compile.html#enable_update_delete_limit) option to support it. 

You can update Ent to the latest master using `go get entgo.io/ent@master`, enable the modifiers feature-flags as described [here](https://entgo.io/docs/feature-flags#custom-sql-modifiers), and use the `LIMIT` option as described in this link: https://entgo.io/docs/feature-flags#modify-example-6.

**Comment by foreverrice** [comment]
don't use modify, cann't add support?
