### ISSUE TITLE
invalid memory address or nil pointer dereference if I declare a Hook

### ISSUE THREAD

**Issue by seyedmmousavi** [ent/ent#3020]
Hi dear Ent team,  
Before anything I want to thank you for great `Ent` ORM.  It has an exceptional architecture and I hope to see the first production release soon.  
  
I have a model named `GeneralReport` and other one named `Problem` like follow:
```
func (GeneralReport) Fields() []ent.Field {
	return []ent.Field{
		//...
		field.Time("meta_update_time").Default(time.Now).UpdateDefault(time.Now),  //<--- Error is about this field
		//...
	}
}
```

```
func (Problem) Fields() []ent.Field {
	return []ent.Field{
		//...
		field.String("data").Immutable().MaxLen(128 * 1024),
		field.String("data_hash").Immutable(),
		//...
	}
}
```
I declared a hook in order to compute data hash automatically like this:   
```
func (Problem) Hooks() []ent.Hook {
	return []ent.Hook{
		ComputeHash(),
	}
}
```
and I implemented this hook in a file inside schema folder named `hooks.go` like this:
```
package schema

import (
	_ent "myproject/model/v2/ent"
	_hook "myproject/model/v2/ent/hook"
	"context"
	"crypto/sha1"
	"encoding/hex"
	"entgo.io/ent"
)

func ComputeHash() ent.Hook {
	hk := func(next ent.Mutator) ent.Mutator {
		return _hook.ProblemFunc(func(ctx context.Context, mutation *_ent.ProblemMutation) (ent.Value, error) {
			d, exists := mutation.Data()
			if exists {
				sum := sha1.Sum([]byte(d))
				mutation.SetDataHash(hex.EncodeToString(sum[:]))
			}
			return next.Mutate(ctx, mutation)
		})
	}
	return _hook.On(hk, ent.OpCreate)
}
```
Please note that the `Problem` has not any edge and no entity connected to it.  
I used `sql/execquery` generator option as follow:
```
go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/execquery ./ent/schema
```

## The Problem
Whenever I want to update a `GeneralReport` record without any access to the `Problem` entity, a panic error raises:  
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x163b476]

goroutine 26 [running]:
testing.tRunner.func1.2({0x17e7f80, 0x1e51640})
	/usr/local/opt/go/libexec/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/opt/go/libexec/src/testing/testing.go:1392 +0x39f
panic({0x17e7f80, 0x1e51640})
	/usr/local/opt/go/libexec/src/runtime/panic.go:838 +0x207
myproject/model/v2/ent.(*GeneralReportUpdateOne).defaults(0xc00007e9c0)
	/Users/mousavi/go/src/myproject/model/v2/ent/generalreport_update.go:1442 +0x36
myproject/model/v2/ent.(*GeneralReportUpdateOne).Save(0xc00007e9c0, {0x19e6cd8, 0xc00011e008})
	/Users/mousavi/go/src/myproject/model/v2/ent/generalreport_update.go:1378 +0x57
myproject/model/v2.(*GeneralReport).Update(0xc0000dafc0, 0x1e65230, 0xc0001d60f0)
	/Users/mousavi/go/src/myproject/model/v2/general_report.go:373 +0xfbc
```

## Source of Error
The error will be fixed if I remove the only `Problem` hook!  
So, the question is how can I fixed it?

## Environment
| Key | Value |
|-------|-------|
| OS | MacOS |
| Go | v1.18.1 |
| ent | v0.11.3 |

**Comment by a8m** [comment]
Hey @seyedmmousavi 👋🏻
I am quite sure that importing the `ent/runtime` package will solve your issue. Please, see https://entgo.io/docs/hooks#hooks-registration and let me know if we can close this issue 🙏🏻

**Comment by a8m** [comment]
Just saw the compliment. Thanks for the kind words and you are welcome to join our [Discord community ](https://discord.gg/qZmPgTE6RX) ❤️

**Comment by a8m** [comment]
Note that if you use `ent/enttest`, this should be imported automatically. See: https://github.com/ent/ent/blob/master/entc/integration/hooks/ent/enttest/enttest.go#L14

**Comment by seyedmmousavi** [comment]
> Note that if you use `ent/enttest`, this should be imported automatically. See: https://github.com/ent/ent/blob/master/entc/integration/hooks/ent/enttest/enttest.go#L14

I didn't know it. Thank you.
