### ISSUE TITLE
[Question] How can i use sum function without group by Aggregate?

### ISSUE THREAD

**Issue by yrzs** [ent/ent#3026]

**Comment by a8m** [comment]
Hey @yrzs 👋 

You can use [custom modifiers](https://entgo.io/docs/feature-flags#modify-example-1) to achieve this. For example:

```go
client.Pet.
    Query().
    Modify(func(s *sql.Selector) {
        s.Select("SUM(LENGTH(name))")
    }).
    IntX(ctx)
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

**Comment by yrzs** [comment]
> 

thank you! I will try the "--feature sql/modifier"

**Comment by a8m** [comment]
Hey! I just want to update you that the aggregation API was simplified, and you can read about it here https://twitter.com/entgo_io/status/1584091539479080960 and https://entgo.io/docs/aggregate.

Also, here's a small example:

```go
// Aggregate one field.
sum, err := client.Order.Query().
    Aggregate(
        ent.Sum(order.FieldPrice),
    ).
    Int(ctx)

// Aggregate multiple fields.
var v []struct {
    Sum, Min, Max, Count int
}
err := a8m.QueryOrders().
    Aggregate(
        ent.Sum(order.FieldPrice),
        ent.Min(order.FieldPrice),
        ent.Max(order.FieldPrice),
        ent.Count(),
    ).
    Scan(ctx, &v)
```

**Comment by ehdgua01** [comment]
Hi, How can I use this feature?
I updated ent packages and re-generate code but I couldn't find `Table.Query().Aggregate()` method

**Comment by a8m** [comment]
Hey @ehdgua01 👋🏻
Please, update to the latest master version and rerun codegen.

**Comment by ehdgua01** [comment]
Hi, I have another question
How I can sort by aggregation result(like an `ent.Sum`)?
