### ISSUE TITLE
bug: [entproto]  Failed generating protobuf after overiding builtin id type

### ISSUE THREAD

**Issue by vietdoan** [ent/ent#3027]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
After changing the type of `id` field in ent schema as below.
```go
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Uint32("id").StorageKey("user_id").Annotations(entproto.Field(1)),
	}
}
```
I got this error while generating an implementation of the gRPC service.
```console
entproto: failed generating protos: entproto: failed parsing ent graph: entproto: list method does not support schema "User" id 
type "uint64"
```
It is weird as there've been test case `TestMessageWithId` that cover this case for generating protobuf definiton.

## Expected Behavior 🤔
Should work for generation of gRPC services

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18 |
| Ent         | 0.11.4   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by rotemtam** [comment]
closed by https://github.com/ent/contrib/pull/394
