### ISSUE TITLE
Cannot generate a new migration with `ModeReplay` 

### ISSUE THREAD

**Issue by IzumiSy** [ent/ent#3033]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I cannot generate a new migration with `ModeReplay`.

`ent/schema/user.go`
```golang
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").NotEmpty(),
		field.String("job").NotEmpty(),
		field.Int("age").Positive(),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return nil
}
```
`ent/generate.go`
```golang
package ent

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/versioned-migration ./schema
```
`ent/migrate/main.go`
```go
//go:build ignore

package main

import (
	"context"
	"log"
	"os"

	_ "ariga.io/atlas/sql/sqlite"
	_ "github.com/mattn/go-sqlite3"

	"atlas-sqlite-modereplay/ent/migrate"

	atlas "ariga.io/atlas/sql/migrate"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/schema"
)

func main() {
	if len(os.Args) != 2 {
		log.Fatalln("migration name is required. Use: 'go run -mod=mod ent/migrate/main.go <name>'")
	}

	// Create a local migration directory able to understand Atlas migration file format for replay.
	dir, err := atlas.NewLocalDir("ent/migrate/migrations")
	if err != nil {
		log.Fatalf("failed creating atlas migration directory: %v", err)
	}

	// Migrate diff options.
	opts := []schema.MigrateOption{
		schema.WithDir(dir),
		schema.WithMigrationMode(schema.ModeReplay),
		schema.WithDialect(dialect.SQLite),
		schema.WithFormatter(atlas.DefaultFormatter),
	}

	ctx := context.Background()
	if err := migrate.NamedDiff(ctx, "sqlite3://main.db?_fk=1", os.Args[1], opts...); err != nil {
		log.Fatalf("failed generating migration file: %v", err)
	}
}
```

Running migration at first works fine.
```shell
$ go run -mod=mod ariga.io/atlas/cmd/atlas@master migrate apply --dir="file://ent/migrate/migrations" --url="sqlite3://main.db?_fk=1"
Migrating to version 20221024083708 (2 migrations in total):

  -- migrating version 20221024083312
    -> CREATE TABLE `users` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` text NOT NULL);
  -- ok (133.214826ms)

  -- migrating version 20221024083708
    -> ALTER TABLE `users` ADD COLUMN `age` integer NOT NULL;
  -- ok (132.619177ms)

  -------------------------
  -- 266.676089ms
  -- 2 migrations
  -- 2 sql statements
```
Genearating a new migration then says a strange error. It should generate a migration for `job` field added in User schema, though.
```shell
$ go run -mod=mod ent/migrate/main.go add_job
2022/10/24 17:49:30 failed generating migration file: sql/migrate: connected database is not clean: found table "atlas_schema_revisions"
exit status 1
```
I can generate a new migration when I delete `main.db` or with `ModeInspect`.

## Expected Behavior 🤔
A new migration should be generated with `ModeReplay` migration.

## Steps to Reproduce 🕹
This is a repo to reproduce this issue.
https://github.com/IzumiSy/ent-migration-modereplay

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.2  |
| Ent         | 0.11.3   |
| Database    | SQLite3   |
| Driver      | github.com/mattn/go-sqlite3 |

**Comment by bodokaiser** [comment]
In the past, I had the same problem. Now, I get `failed creating named schema diff: validating migration directory: checksum file not found`. Maybe these are related.

MVP can be found at [bodokaiser/entgo-migrate-diff#atlas](https://github.com/bodokaiser/entgo-migrate-diff/tree/atlas). Steps to reproduce:

1. `git clone -b atlas https://github.com/bodokaiser/entgo-migrate-diff`
2. `cd entgo-migrate-diff`
3. `go run main.go --url=postgres://postgres@localhost --name=initial`

**Comment by amaneshi** [comment]
@IzumiSy Guess you misunderstood something. From your description migrations DB and DB itself - same sqlite file (`sqlite3://main.db?_fk=1`). But for this migrations type they should be different.
For migration `ModeReplay` you need always provide connection url to `CLEAN` db, as it work like this:
1. Check if DB is `clean`
2. Apply all migrations from directory
3. Compare states and generate diff (same step as for inspect mode)
4. Cleanup provided DB (to be reusable, related to p.1)
5. Generate migration files

So when you applied migrations - your DB is not `clean` anymore, and migration generation is failing after this.

**Comment by IzumiSy** [comment]
I think this is just my misunderstanding. Thanks for correcting me!
