### ISSUE TITLE
Mysql field comment haven't generate

### ISSUE THREAD

**Issue by foreverrice** [ent/ent#3036]
When I try add comment to schema, the comment of field cann't generate. 
![image](https://user-images.githubusercontent.com/33533816/197750027-5df35d41-1cce-4243-8811-b4271205cb81.png)
![image](https://user-images.githubusercontent.com/33533816/197750380-748e9fda-ecea-4506-8af1-12d00e05a52d.png)

**Comment by a8m** [comment]
Hey @foreverrice, and thanks for opening this issue 👋 

Comments are added to the Go structs but are not updated in the database. However, you can change this using [Diff/Apply Hooks](https://entgo.io/docs/migrate#atlas-integration).

Closing it as it's a duplicate issue, and we plan to get to it at some point. See: https://github.com/ent/ent/issues/1546

**Comment by a8m** [comment]
The issue was resolved with: https://entgo.io/docs/schema-annotations#database-comments.

Update your Ent version to master, and check out this tweet to see an example: https://twitter.com/entgo_io/status/1607394587009589248?s=46&t=lnMIxsxQpGOTMCpsp0yPBg
