### ISSUE TITLE
how to remove field collate

### ISSUE THREAD

**Issue by foreverrice** [ent/ent#3037]
when i create table, always have a collate. i want to remove the collate of field.
![image](https://user-images.githubusercontent.com/33533816/197755000-81dfa927-7f53-4523-8652-5b0b0cbcc9f6.png)

**Comment by foreverrice** [comment]
For example
<img width="317" alt="image" src="https://user-images.githubusercontent.com/33533816/197918694-553a430d-2811-48bb-9775-7b756c886e9d.png">
I want to set default '' in mysql and no collate.But I see the code:
![image](https://user-images.githubusercontent.com/33533816/197919177-db89568f-2c03-4880-b53f-2a2b734af26a.png)
I can not change a specific column.

**Comment by a8m** [comment]
The `DEFAULT <> ""` is for the annotation. You can set `Default("")` on your field builder.

For the collation, you can control the table collation also using the `entsql.Annotation`. Let me know if you need help with it.
