### ISSUE TITLE
Support for Postgres operator class on indexes

### ISSUE THREAD

**Issue by crossworth** [ent/ent#3041]
Hello, I'm trying to use Postgres `pg_grgm` extension with Ent to create an index but I'm having trouble creating and managing the index with Ent schema, seems like I must define an `operator class` for the index.

- [x] I have [searched the](https://github.com/ent/ent/issues?q=gin_trgm_ops) [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
I propose that we add support for [Operator class](https://www.postgresql.org/docs/current/indexes-opclass.html) on [Atlas](https://github.com/ariga/atlas) first and then maybe we could implement something like the code below on Ent:

```go
index.Fields("type").Annotations(
	entsql.IndexType("GIN"),
	entsql.IndexOpClass("gin_trgm_ops"),
),
```

NOTE: I'm not proposing that we add support for `opclass_options` at this time, I think we could wait and see if there is a need for it first.

## Motivation 🔦

It's possible to [speed up a few queries that uses `LIKE` and `ILIKE`](https://www.cybertec-postgresql.com/en/postgresql-more-performance-for-like-and-ilike-statements/) using `pg_grgm`, this is specially true for cases when using wildcards, where Postgres will not use `btree` index in a few cases.

[Explain Analyze with `btree` and `hash` index](https://app.pgmustard.com/#/explore/a3846e21-b7a5-425d-b721-32cf75fe1e2e) - **no index is used**.
[Explain Analyze with `gin (gin_trgm_ops)`](https://app.pgmustard.com/#/explore/b247730d-ae38-4edb-b2f8-0a4de7ba573f) - **the index is used**.
Query used: `explain (analyze, buffers, verbose, format json) select * from users where email ilike '%@hotmail.com'`

It's worth noting that [PgHero](https://github.com/ankane/pghero) recommends an index with an operator class as well if we only use `btree` or `hash` index.
 
![image](https://user-images.githubusercontent.com/1251151/197930218-c81121cb-3466-4b8a-b5e2-a5d2f45db69c.png)

Example creating the index:
```
-------------------------------------------------VVVVVVVVVVVV
CREATE INDEX idx_name ON table USING gin (column gin_trgm_ops);
```

Error returned during migration if we don't provide the `gin_trgm_ops`:  `data type character varying has no default operator class for access method "gin" (SQLSTATE 42704)`

## Alternatives

For now we can create the index using migration hooks:
```go
func CreateUserEmailIdx(db *sql.DB) schema.MigrateOption {
	return schema.WithHooks(func(next schema.Creator) schema.Creator {
		return schema.CreateFunc(func(ctx context.Context, tables ...*schema.Table) error {
			err := next.Create(ctx, tables...)
			if err != nil {
				return err
			}

			_, err = db.ExecContext(ctx, `CREATE INDEX IF NOT EXISTS user_email_idx ON users USING gin (email gin_trgm_ops);`)
			if err != nil {
				return fmt.Errorf("could not create user_email_idx: %w", err)
			}
			return nil
		})
	})
}
```

**Comment by a8m** [comment]
Thanks for suggesting this, @crossworth ❤️
