### ISSUE TITLE
Scan does't work correctly when use with camelCase json sturct tags

### ISSUE THREAD

**Issue by ehdgua01** [ent/ent#3045]
Hi,
```go
var dtos []struct {
	Id              uuid.UUID `json:"id"`
	Title           string    `json:"title"`
	TotalCharacters int       `json:"totalCharacters"`  // sql:"totalcharacters"
}

client.Story.Query().
	Where(story.AuthorIDEQ(authorId)).
	GroupBy(
		story.FieldID,
		story.FieldTitle,
	).
	Aggregate(
		func(s *sql.Selector) string {
			t := sql.Table(story.ChaptersTable)
			s.Join(t).On(s.C(story.FieldID), t.C(story.ChaptersColumn))
			return sql.As(sql.Sum(t.C(chapter.FieldMinCharacters)), "totalCharacters")
		},
	).
	ScanX(context.Background(), &dtos)
```
It will raise an error which `sql/scan: missing struct field for column: totalCharacters (totalcharacters)`
I know to use sql struct tag`sql:"totalcharacters"` as a workaround

**Comment by a8m** [comment]
Thanks for reporting this, @ehdgua01 🙏 

The issue was resolved with https://github.com/ent/ent/pull/3048. Please, feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case something is not working or you need help with this ❤️

**Comment by a8m** [comment]
It will be tagged in the upcoming days. But note that `master` is always stable. You can update to the latest master using `go get entgo.io/ent@master`.

**Comment by jakeslee** [comment]
@a8m The fix is not working in camelcase field name and snakecase storage key.
