### ISSUE TITLE
Panic when querying against schema w/ composite primary key

### ISSUE THREAD

**Issue by adayNU** [ent/ent#3047]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I am getting a panic `runtime error: invalid memory address or nil pointer dereference` which is occurring [here](https://github.com/ent/ent/blob/master/dialect/sql/sqlgraph/entql.go#L261) (specifically `e.context.ID` is nil because of the composite primary key). 

## Expected Behavior 🤔

Does not panic!

## Steps to Reproduce 🕹

I have a schema defined as follows:
```go
func (OpportunityCallLink) Annotations() []schema.Annotation {
	return []schema.Annotation{
		// ...
		field.ID("call_id", "opportunity_id"),
	}
}

func (OpportunityCallLink) Fields() []ent.Field {
	return []ent.Field{
		field.String("call_id").
			StructTag(`json:"callId`),
		field.String("opportunity_id").
			StructTag(`json:"opportunityId"`),
		// ...
	}
}

// Edges of the OpportunityCallLink.
func (OpportunityCallLink) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("call", Call.Type).
			Required().
			Unique().
			Field("call_id"),
		edge.To("opportunity", Opportunity.Type).
			Required().
			Unique().
			Field("opportunity_id"),
		// Technically added via a Mixin but same difference.
		edge.To("customer", Customer.Type).
			Unique().
			Required(),
	}
}
```

We then have a privacy filter that enforces that a query can only return data from the customer the request is associated with:

```go
// FilterCustomerRule is a query rule that filters out entities that don't belong to the customer.
func FilterCustomerRule() privacy.QueryMutationRule {
	type CustomerFilter interface {
		WhereHasCustomerWith(...predicate.Customer)
	}
	return privacy.FilterFunc(func(ctx context.Context, f privacy.Filter) error {
		var cf, ok = f.(CustomerFilter)
		if !ok {
			return privacy.Denyf("unexpected filter type %T", f)
		}

		cust, ok := GetCustomerOk(ctx)
		if !ok {
			return ErrNoCustomerCtx
		}

		// Make sure that a tenant is able to read only entities that
		// has an edge to it.
		cf.WhereHasCustomerWith(
			customer.ID(cust.ID),
		)

		// Skip to the next privacy rule (equivalent to return nil).
		return privacy.Skip
	})
}
````

When poking around by using my local ent repo it definitely appears that the NPE comes from traversing to the customer edge.

I authored [this change](https://github.com/adayNU/ent/commit/00880c80bb47869cf8d5ca8ddd1485b21ca250b7) which appeared to resolve the NPE (but i'm not 100% sure that it's correct). Would love a second set of eyes - if it makes sense I can put up a PR.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go1.18.5 darwin/arm64  |
| Ent         | v0.11.3   |
| Database    | Postgres   |
| Driver      | https://github.com/lib/pq       |

**Comment by a8m** [comment]
Hey @adayNU, and thanks for reporting this. Would you mind testing your codebase/tests on this PR: https://github.com/ent/ent/pull/3051, or let me know if something there is missing?

I don't mind accepting your PR, but note that we can't accept loading any edge in case of an edge schema with composite ID. Thanks 🙏

**Comment by a8m** [comment]
Fixed with https://github.com/ent/ent/pull/3051.
