### ISSUE TITLE
entoas docs

### ISSUE THREAD

**Issue by niwla23** [ent/ent#3053]
Where can I find documentaion for entoas? The blog post is referring to the entoas README which itself links to godoc and the ent docs. I can't find any information on how to setup the generator to include edges.

**Comment by a8m** [comment]
Hey 👋 
Please, see the project [README](https://github.com/ent/contrib/blob/master/entoas/README.md), the [GoDoc](https://pkg.go.dev/entgo.io/contrib/entoas) and [these examples](https://github.com/ent/contrib/tree/master/entoas/internal) in our repository. 

Feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎 

cc @masseelch

**Comment by masseelch** [comment]
> Where can I find documentaion for entoas? The blog post is referring to the entoas README which itself links to godoc and the ent docs. I can't find any information on how to setup the generator to include edges.

Edges are included by using serialization groups. You specify via an struct annotation `entoas.ReadGroups()` etc. which groups to serialize and with another field/edge annotation `entoas.Groups` for which serialization groups the field/edge should be included. Example:

```
fun(T) Fields() {
  return []ent.Field{
    field.String("field").Annotations(
      entoas.Groups("type.read"),
    )
  }
}

func (T) Annotations() {
  return []schema.Annotation{
    entoas.ReadOoerarion(entoas.OperationGroups("type.read", "type2.read"))
  }
}
```

Additionally, you have the serialization policy you can define.
