### ISSUE TITLE
Is there any way to print the execution time of SQL, can you give an example?

### ISSUE THREAD

**Issue by issone** [ent/ent#3055]
Here is part of my code, I want to print the consumption time of each SQL statement.
Currently this only prints the executed SQL statements, but not the time consumed by the corresponding statements, is there a way to get the consumption time?

drv, err := sql.Open("mysql", source)
	if err != nil {
		log.Fatalf("failed opening connection to mysql: %v", err)
	}
	drvWithContext := dialect.DebugWithContext(drv, func(ctx context.Context, i ...interface{}) {
		log.WithContext(ctx).Debug(i)
	})
	db := drv.DB()
	db.SetMaxIdleConns(50)
	db.SetMaxOpenConns(5)
	db.SetConnMaxLifetime(time.Hour)
	client := ent.NewClient(ent.Driver(drvWithContext), ent.Log(log.Debug))

**Comment by a8m** [comment]
Hey @issone!
You can implement a custom driver that handles this for you. For example:  

```go
// DebugDriver is a driver that logs all driver operations.
type DebugDriver struct {
	Driver                               // underlying driver.
	log    func(context.Context, ...any) // log function. defaults to log.Println.
}

// Exec logs its params and calls the underlying driver Exec method.
func (d *DebugDriver) Exec(ctx context.Context, query string, args, v any) error {
	start := time.Now()
	err := d.Driver.Exec(ctx, query, args, v)
	d.log(ctx, fmt.Sprintf("driver.Exec: query=%v args=%v time=%v", query, args, time.Since(start)))
	return err
}

// ...
```
Please, see the full example [here](https://github.com/ent/ent/blob/master/dialect/dialect.go) and feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

**Comment by issone** [comment]
Thanks, it solved my problem


> Hey @issone! You can implement a custom driver that handles this for you. For example:
> 
> ```go
> // DebugDriver is a driver that logs all driver operations.
> type DebugDriver struct {
> 	Driver                               // underlying driver.
> 	log    func(context.Context, ...any) // log function. defaults to log.Println.
> }
> 
> // Exec logs its params and calls the underlying driver Exec method.
> func (d *DebugDriver) Exec(ctx context.Context, query string, args, v any) error {
> 	start := time.Now()
> 	err := d.Driver.Exec(ctx, query, args, v)
> 	d.log(ctx, fmt.Sprintf("driver.Exec: query=%v args=%v time=%v", query, args, time.Since(start)))
> 	return err
> }
> 
> // ...
> ```
> 
> Please, see the full example [here](https://github.com/ent/ent/blob/master/dialect/dialect.go) and feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

Thanks, it solved my problem
