### ISSUE TITLE
How to execute raw SQL statements in ent, any examples?

### ISSUE THREAD

**Issue by issone** [ent/ent#3062]

**Comment by a8m** [comment]
Hey! Please, use `client.Debug()` for this. For example:

```go
client.Debug().T.
    Query().
    All(ctx)

client.Debug().T.
    Create().
    SetF(v).
    Save(ctx)
```

Closing, but please feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

**Comment by issone** [comment]
> Hey! Please, use `client.Debug()` for this. For example:
> 
> ```go
> client.Debug().T.
>     Query().
>     All(ctx)
> 
> client.Debug().T.
>     Create().
>     SetF(v).
>     Save(ctx)
> ```
> 
> Closing, but please feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎




Thanks, but I don't want to depend on model,  For example：

select A.id, name from table1  A join (select uid as id from table2) B on A.id=B.id order by A.id desc;

I want the implementation to be what is written above， Where should this raw sql be placed

**Comment by a8m** [comment]
Oh, sorry. I misread the question above. Please, see the custom modifiers: https://entgo.io/docs/feature-flags#custom-sql-modifiers
