### ISSUE TITLE
quality of life: handle GoTypes() that implement encoding.Unmarshal{Binary,Text} & encoding.Marshal{Binary,Text}

### ISSUE THREAD

**Issue by devnode** [ent/ent#3064]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

```go
// continue checking if GoType(V{}) implements this
type ValueScanner interface {
	driver.Valuer
	sql.Scanner
}

// but if not, and if field of type {Bytes,Other,String,Text}, then check if V implements
type TextEncoder interface {
	encoding.TextMarshaler
	encoding.TextUnmarshaler
}

// if it does, then just regurgitate something like this:
type TextValueScanner[V TextEncoder] struct {
	value V
}

func (s *TextValueScanner[V]) Scan(in interface{}) error {
	switch v := in.(type) {
	case string:
		return s.value.UnmarshalText([]byte(v))

	case []byte:
		return s.value.UnmarshalText(v)

	default:
		return fmt.Errorf("invalid type: %T", in)
	}
}

func (s *TextValueScanner[V]) Value() (driver.Value, error) {
	return s.value.MarshalText()
}

// or whatever you want to call it
func (s *TextValueScanner[V]) ToFieldValue() V {
	return s.value
}

// then plumb it up to the generated struct
```

- https://pkg.go.dev/encoding#pkg-types
- https://pkg.go.dev/net/netip
- https://pkg.go.dev/math/big#Float (and others...)
- https://pkg.go.dev/cloud.google.com/go/civil

## Motivation 🔦

- to reduce the amount of code consumers of `ent` have to write
- and to just avoid the gymnastics of having to type wrap fairly common types

**Comment by a8m** [comment]
Hey @devnode, and thanks for proposing this issue. I was thinking about adding another option for setting the Value/Scan functions (handlers) as an additional option. This way, it will be possible to override it for all types. The `Binary`/`Text` helpers can be added to the Ent stdlib to simplify the usage. e.g.:

```go
field.String("t").
    ValueScanner(Tokenizer{})

field.String("url").
    GoType(&url.URL{}).
    ValueScanner(sql.BinaryCodec[*url.URL]{})
```

Thoughts?
