### ISSUE TITLE
[contrib] entgql generates invalid schema while using field.Bytes

### ISSUE THREAD

**Issue by nicolasparada** [ent/ent#3065]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Define a ent schema with a bytes value `field.Bytes("example")` and then integrate the entgql extension to generate the graphql schema. It generates a gql type of `[]bytes!`

## Expected Behavior 🤔

It should generate a valid gql schema. Maybe `String!`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.?  |
| Ent         | 0.11.?   |
| Database    | Cockroach   |
| Driver      | https://github.com/lib/pq        |

**Comment by giautm** [comment]
Hello, thank you for opening the issue. For the `[]byte` field, you should use `entgql.Type('String')` to let EntGQL which is the type for the field.

You can use any scalar type here, for support encode/decode from the correct binary format. If you still have a question, please let me know.

**Comment by nicolasparada** [comment]
Thanks. I just noticed that right now and was about to update the issue.

**Comment by a8m** [comment]
Thanks for the support, @giautm. Closing, but feel free to reopen it if you still need help.
