### ISSUE TITLE
how to change entity's struct filed name generated by ent?

### ISSUE THREAD

**Issue by shuaiyy** [ent/ent#3076]
I defined a string field `gpu` in schema file,  got a go struct field `Gpu`, but I want a `GPU`.

what should I do, need a help.

**Comment by a8m** [comment]
Hey @shuaiyy 👋 

You can either call [entc/gen.AddAcronym("GPU")](https://github.com/ent/ent/blob/master/entc/gen/func.go#L296), or define you field as:

```go
field.String("GPU").
    StorageKey("gpu") // Make it lowercase in the database.
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎
