### ISSUE TITLE
ent is support sql regexp?

### ISSUE THREAD

**Issue by dybxin** [ent/ent#3077]
the following is my table:

```go
package schema

import (
    "time"

    "entgo.io/ent"
    "entgo.io/ent/schema/field"
)

// Example schema.
type Example struct {
    ent.Schema
}

// Fields of the Example.
func (Example) Fields() []ent.Field {
    return []ent.Field{
        field.Int("name"),
        field.String("value"),
        field.String("overview").
            Unique(),
        field.Time("created_at").
            Default(time.Now),
    }
}
```
the table's data :

|  name   | value  |overview  |
|  ----  | ----  | ----  |
| project_1_viewer  | project_1_viewer | test |
| task_2_viewer  | task_20_viewer | test |
| project_3_viewer  | project_3_viewer | test |
| test_4_viewer  | test_4_viewer | test |
| task_5_viewer  | task_500_viewer | test |

i want to query all name like  `project_{num}_viewer` , the num can be understood as self-incrementing ids. how do i query？

**Comment by a8m** [comment]
Hey @dybxin! You can use custom predicates with `LIKE` operator (or `glob`). For example: 

```go
nodes := client.Example.
    Query().
    Where(func(s *sql.Selector) {
        s.Where(sql.Like(example.FieldName, "..."))
    }).
    AllX(ctx)
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎
