### ISSUE TITLE
How do we add a field that the database does not exists?

### ISSUE THREAD

**Issue by gsoec** [ent/ent#3096]
```go
type User struct {
    ent.Schema
}

func (User) Fields() []ent.Field {
    return []ent.Field{
        // this field only exists in user table in some databases.
        field.Int("old_user_id"),
    }
}
```
The reason to add fields like that is because our project has multiple database schema with a few fields differences, 
and we need to create a ent schema that compatible with multiple database in one codebase.

**Comment by a8m** [comment]
Hey @gsoec! The Ent schema is usually represents on database schema, so my suggestion to you is to create an Ent schema per project/database, but share the same "base" `User` structure with them using [Mixin](https://entgo.io/docs/schema-mixin). There's an example for it in our `ent/contrib` repository, where an Ent schema is embedded as Mixin in a different schema. See:
- https://github.com/ent/contrib/blob/master/entgql/internal/todouuid/ent/schema/group.go#L33
- https://github.com/ent/contrib/blob/master/entgql/internal/todouuid/ent/schema/todo.go#L33

In case you still want to use the same Ent schema in different projects, my other suggestion is to use [DiffHooks](https://entgo.io/docs/migrate/#diff-hook-example) to filter out (or add) the extra columns in migration, and use field selection ([`<T>Query.Select`](https://entgo.io/docs/crud#field-selection)) to select the relevant fields per service in the code.

Closing, but please feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) and ping me there in case you need more help with this 😎
