### ISSUE TITLE
How to get data without 'edges' tag name?

### ISSUE THREAD

**Issue by ppxb** [ent/ent#3098]
Hello there,
when i use edge's features, the query data will return like below:

``` go
{
    created_at: "0001-01-01T00:00:00Z",
    edges: {
        ... other children items
  },
    id: 5,
    name: "Main project",
    updated_at: "0001-01-01T00:00:00Z",
    uuid: "f8a5aff3-9fb1-4c69-b0d2-03cc9008997c",
}
```

but sometimes i want to get the directly children items like this:

```
{
    created_at: "0001-01-01T00:00:00Z",
    children: {
        ... children items
  },
    id: 5,
    name: "Main project",
    updated_at: "0001-01-01T00:00:00Z",
    uuid: "f8a5aff3-9fb1-4c69-b0d2-03cc9008997c",
}
```

how should i do or there is a way to solve it by setting some options?
thanks so much.

**Comment by a8m** [comment]
Hey @ppxb, and thanks for raising this issue. The way to do it is to either add a custom `MarshalJSON` method to all generated entities using [templates](https://entgo.io/docs/templates/) or create a custom struct that embeds these edges and pass it to `json.Marshal`:

```go
// Option 1:
func MarshalUser(u *ent.User) ([]byte, error) {
	uu := struct {
		*ent.User
		Pets []*ent.Pet `json:"pets,omitempty"`
	}{
		User: u,
		Pets: u.Edges.Pets,
	}
	return json.Marshal(uu)
}

// Option 2:
func MarshalUser(u *ent.User) ([]byte, error) {
	uu := struct {
		ID   int        `json:"id"`
		Name string     `json:"name"`
		Pets []*ent.Pet `json:"pets,omitempty"`
	}{
		ID:   u.ID,
		Name: u.Name,
		Pets: u.Edges.Pets,
	}
	return json.Marshal(uu)
}
```

Note that if you want to drop the `edges` tags completly from the JSON marshaling, you need to override it using the [`StructTag` annotation](https://github.com/ent/ent/blob/master/schema/edge/annotation.go#L19). 

Closing, but please feel free to join our [Discord community](https://discord.gg/zZ6sWVg6NT) in case you need more help with this 😎

**Comment by gsumo** [comment]
> If someone ever wants to do this, here is the clear answer on how to do it properly https://entgo.io/docs/faq#how-to-configure-jsonmarshal-to-inline-the-edges-keys-in-the-top-level-object

This does not appear to work:

n.Annotations.Set undefined (type gen.Annotations has no field or method Set)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#MissingFieldOrMethod)

n.Annotations.Set(tag.Name(), tag)

**Comment by a8m** [comment]
Hey @gsumo, please update your Ent version to the latest master. It should work then.

**Comment by ppxb** [comment]
@a8m thanks for your hard working.i will check this feature in latest ent version.
thanks again.
