### ISSUE TITLE
.NotIn queries as the last element of .Where can generate invalid SQL

### ISSUE THREAD

**Issue by chrisseto** [ent/ent#3107]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate. (Seems related but distinct from https://github.com/ent/ent/issues/3007)

## Current Behavior 😯

Ent can generate invalid SQL if `NotIn` is given a slice with length zero AFTER another predicate.

```go
client.Model.Delete().Where(
    model.FieldEQ("bar"),
    model.IDNotIn([]int{}),
)

// Results in the SQL: DELETE FROM model WHERE field = 'bar' AND
// Error message: ERROR: at or near "and": syntax error (SQLSTATE 42601)
```

## Expected Behavior 🤔

`NotIn` queries should not result in invalid SQL, either by generating valid SQL or by alerting the user of an invalid query.

```go
client.Model.Delete().Where(
    model.FieldEQ("bar"),
    model.IDNotIn([]int{}),
)

// Results in the SQL: DELETE FROM model WHERE field = 'bar'
```

## Steps to Reproduce 🕹

There aren't really any steps besides making the above query.

There's an early return in `NotIn` if `len(args) == 0`. If a previous function had tacked on an `AND` clause, the early return would result in invalid SQL. 

```go
// NotIn appends the `Not IN` predicate.
func (p *Predicate) NotIn(col string, args ...interface{}) *Predicate {
	if len(args) == 0 {
		return p
	}
	return p.Append(func(b *Builder) {
		b.Ident(col).WriteOp(OpNotIn)
		b.Nested(func(b *Builder) {
			if s, ok := args[0].(*Selector); ok {
				b.Join(s)
			} else {
				b.Args(args...)
			}
		})
	})
}
```

~It's possible to mitigate this issue by simply swapping the ordering of your queries:~
Whoops, spoke too soon. Swapping also results in a similar issue.

```go
client.Model.Delete().Where(
    model.IDNotIn([]int{}),
    model.FieldEQ("bar"),
)

// Results in the SQL: DELETE FROM model WHERE AND field = 'bar'
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.2  |
| Ent         | 0.11.1   |
| Database    | CockroachDB   |
| Driver      | https://github.com/jackc/pgx/       |

**Comment by giautm** [comment]
Hello, can you please upgrade to the master branch and try again? I believe it already fixed via: https://github.com/ent/ent/commit/b00e549c88a5dcf9b0e7c9b193cebafa0841ace8

**Comment by chrisseto** [comment]
Upgrading to `0.11.4` fixed it. Thanks @giautm!
