### ISSUE TITLE
I don't want ID auto increment, do I have an API to cancel it?

### ISSUE THREAD

**Issue by StarkSim** [ent/ent#3109]
## Background

- I'm using Postgresql and Snowflake ID
- I used to use Django ORM, it doesn't generate `sequence` in db if I overwrite the id field
```python
id = models.BigIntegerField(primary_key=True, help_text='雪花 ID')
```
- However, I overwrite the id field in ent, I still got useless generated `sequence` in db
```go
return []ent.Field{
    field.Int64("id").Unique().Immutable().DefaultFunc(func() int64 {
        return tools.GenSnowflakeID()
    }),
}
```
![image](https://user-images.githubusercontent.com/67146986/202962388-5fe36846-4946-47c2-bba7-545c36488433.png)

## Question

- May I cancel `auto increment` in go file, instead of delete it in db

**Comment by giautm** [comment]
Hi @StarkSim, can you try disable it via the annotation?
```
	incrementalEnabled := false
	return []ent.Field{
		field.Int64("id").
			Unique().Immutable().
			Annotations(entsql.Annotation{
				Incremental: &incrementalEnabled,
			}).
			DefaultFunc(func() int64 {
				return tools.GenSnowflakeID()
			}),
```

**Comment by a8m** [comment]
The `SchemaType` option should also help here. Check this out and let us know if you still have troubles with it. See: https://entgo.io/docs/schema-fields/#database-type

**Comment by StarkSim** [comment]
Thank you! They both worked. 👍
It can't remove the existing `sequence`, but it's good enough since this is an initial work.
