### ISSUE TITLE
Create Bulk doesn't return an error

### ISSUE THREAD

**Issue by davidjwilkins** [ent/ent#3120]
If you use the `.CreateBulk` function, it doesn't return an error even when the create fails.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If I create an insert that fails due to a foreign key constraint, it does not return an error when the insert was performed using `client.CreateBulk`.

## Expected Behavior 🤔

If the insert fails, an error should be returned.
 

## Steps to Reproduce 🕹

Create a O2M entity relationship, e.g.

```
// Fields of the LineItem.
func (LineItem) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New),
		field.UUID("line_item_group_id", uuid.UUID{}),
	}
}

// Edges of the LineItem.
func (LineItem) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("lineItemGroup", LineItemGroup.Type).
			Ref("lineItems").
			Unique().Field("line_item_group_id").Required()
	}
}
```

and 

```
// Fields of the LineItemGroup.
func (LineItemGroup) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Default(uuid.New),
	}
}

// Edges of the LineItemGroup.
func (LineItemGroup) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("lineItems", LineItem.Type),
	}
}

```

Write a test for an insert of a line item with a line item group that does not exist:

```
client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
defer client.Close()
_, err := client.LineItem.
			Create().
			SetLineItemGroupID(uuid.New()).
			
assert.Error(t, err)
```

as expected, this fails.

Now, do the same test using `BulkCreate`:

```
_, err = client.LineItem.CreateBulk(client.LineItem.
			Create().
			SetLineItemGroupID(b.LineItemGroupID)).Save(ctx)
assert.Error(t, err)
```

This one fails, as there is no error.

## Your Environment 🌎

| Tech            | Version                                             |
| ---------------- | ---------------------------------------------- |
| Go                | go version go1.19 linux/amd64  |
| Ent               | v0.11.4                                             |
| Database    | sqlite3                                              |
| Driver          | "github.com/mattn/go-sqlite3"  |

**Comment by crossworth** [comment]
Hello @davidjwilkins, I have checked and `Create` and `CreateBulk` return the correct error related to the foreign key constraint, on your example the error is not returned because the conflict is solved (you are setting the `LineItemGroupID`).

Please try the example below:

```go
_, err := client.LineItem.Create().SetLineItemGroupID(uuid.New()).Save(ctx)
require.Error(t, err)
_, err = client.LineItem.CreateBulk(client.LineItem.Create().SetID(uuid.New())).Save(ctx)
assert.Error(t, err)
```

**Comment by a8m** [comment]
Thanks for the help, @crossworth. 

Closing! @davidjwilkins, you're more than welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😃

**Comment by LBeernaertProton** [comment]
I just wanted to add that we experienced a similar issue where `CreateBulk` will not return error if there is a constraint in the table that is not satisfied. 

In our particular case, we had 2 unique constraints on two separate columns A & B. Attempts to create a new row with a new unique value for A but with an existing value B would cause the the operation to not return any errors. 

We are using v0.11.8 with an SQLite database.
