### ISSUE TITLE
go1.19  ent/entc/gen/template/ent.tmpl Unwrap panic is error

### ISSUE THREAD

**Issue by 184104489** [ent/ent#3129]
go1.19  
ent v0.11.4
go run entgo.io/ent/cmd/ent generate

ent/entc/gen/template/ent.tmpl 
Unwrap() panic is error

**Comment by a8m** [comment]
Hey! I can't reproduce this, so I'll appreciate it if you could create a bug report using https://github.com/ent/bug.

**Comment by a8m** [comment]
Closing, but please reopen or join our [Discord](https://discord.gg/qZmPgTE6RX) if you need help and we can support you in this 😃
