### ISSUE TITLE
Hooks for query

### ISSUE THREAD

**Issue by PalanQu** [ent/ent#3130]
According to the https://entgo.io/docs/hooks, there are hooks for mutate action, but there is no hooks for query, I want to add a opentelemetry tracer to auto-record the span of all actions to database like following 
``` golang
client.Use(func(next ent.Mutator) ent.Mutator {
        return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	        opType := m.Op().String()
	        tablesName := m.Type()
	        spanName := fmt.Sprintf("%s-%s", tablesName, opType)
                // tracer is `trace.Tracer` of "go.opentelemetry.io/otel/trace"
	        newCtx, span := tracer.Start(ctx, spanName)
	        span.SetAttributes(
		        attribute.String("table", tablesName),
		        attribute.String("operation", opType),
	        )
	        defer span.End()
	        return next.Mutate(newCtx, m)
        })
})
```

- [ x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦
It is hard to record each span manually in the service, so I want wrap the trace span in the hooks.

**Comment by a8m** [comment]
Hey @PalanQu 👋 
Did you see https://entgo.io/docs/sql-integration#use-opencensus-with-mysql?

We do not support read hooks on the client atm (but you can add it on the `dialect.Driver`), but this is expected to be added soon. Let me know if we can close this, as this is a duplicate of #833. Thanks 🙏

**Comment by PalanQu** [comment]
Thanks for your reply, I will close the issue

**Comment by a8m** [comment]
Closed with https://entgo.io/docs/interceptors 😃
