### ISSUE TITLE
How to join table with custom join condition by ent api?

### ISSUE THREAD

**Issue by codeReaper2001** [ent/ent#3133]
I have two tables in mysql:
① socs:
+----+--------+-------+--------+
| id | soc_id | sr_id | tac_id |
+----+--------+-------+--------+
|  1 | Soc-1  | SR-1  | TAC-1  |
|  2 | Soc-2  | SR-2  | NULL   |
+----+--------+-------+--------+
② flows:
+----+---------+-------+
| id | jira_id | data  |
+----+---------+-------+
|  1 | SR-1    | data1 |
|  2 | TAC-1   | data2 |
|  3 | SR-2    | data3 |
+----+---------+-------+
I want to execute the sql: 
```sql
SELECT * FROM socs 
INNER JOIN flows 
    ON socs.sr_id = flows.jira_id OR socs.tac_id = flows.jira_id
```
but I don't know how to do it by ent api

**Comment by a8m** [comment]
Hey @codeReaper2001 👋🏻
I just answered this question on Discord 😉. Please, let’s continue the discussion there: https://discord.com/channels/885059418646003782/885059419107360779/1047547072829734912
