### ISSUE TITLE
Generate migrations using Atlas

### ISSUE THREAD

**Issue by ducnguyen96** [ent/ent#3137]
![image](https://user-images.githubusercontent.com/47471616/205251511-5c37ae45-772c-4ac7-85ca-9cb4cd2e4bdc.png)

How can I achieve similar thing here with write driver using `Postgres` dialect

Using `Postgres` dialect here cause this error: query is not supported by the WriteDriver

Version: v0.11.4 using golang-migrate/migrate main.go

**Comment by a8m** [comment]
Thanks for reporting this, @ducnguyen96. The issue should be solved with #3162
