### ISSUE TITLE
Multiple GraphQL Files and Relay

### ISSUE THREAD

**Issue by sanketplus** [ent/ent#3140]
Premise:
  - Ent generates `ent.graphql` with definitions derived from schema
  - I want to add another root query
  - Since `ent.graphql`'s file is not supposed to be edited, create new `schema.graphql` file with `extend type Query { new_root_query }`
  - Relay's compiler does not support multiple schema files

Problem:
  - Since relay compiler does not support multiple schema file, generate one schema file by concatenating `ent.graphql` and `schema.graphql`
  - The combined file has both `type Query { ... }` and `extend type Query { ... }` declarations
  - Now using `new_root_query` in any graphql query will instruct relay to generate a client side query. The query using `new_root_query`  will never result in a network call

This is also part relay compiler issue. But IMO it's also because ent's design forcing to extend Query type.

**Comment by giautm** [comment]
Hello @sanketplus, we already facing the same case as you when we develop our services.

We write a small script to combine those files into a single schema and then put it in the frontend directory for Relay to use. The script basically uses [`@graphql-tools/merge`](https://www.npmjs.com/package/@graphql-tools/merge) to combine files.

However, you can do it with a more simple script. Let's take a directory with 3 files: `schema/foo.gql`, `schema/bar.gql` and `schema/ent.gql`. Then you can combine it with the `cat` command.

```sh
cat schema/*.gql > ui.gql 
```

Please note each file should have an EOF character. (`\n`). ;)

If you need more help, please let me know. I'm happy to support you.

**Comment by sanketplus** [comment]
Thanks @giautm for the tip to merge files and pointing the small EOF gotcha :D Does the  [@graphql-tools/merge](https://www.npmjs.com/package/@graphql-tools/merge) also combine/merge the extended definitions? Ie: `type Query` and `extend type Qurey` gets merged into one? Because that issue persisted even after concatenating the files, and it also breaks the whole app.

**Comment by giautm** [comment]
Which version of Relay are you using? Relay able to handle the extend keyword without any error. Can you share the error you have?

**Comment by sanketplus** [comment]
Relay version: 14.1

There's no issue with merging. But I think it's a special case when merging `type Query`? 

The query:
```
const GetDevices = graphql`
  query DashboardGetDevicesQuery {
    devices {
    ...
```

The query def where the `devices` root field is now in `extend type Query` instead of `type Query` which generates this diff in the generated relay file (it changes from the concreteRequest to ClientRequest) which results into no network call being made. So likely a bug for relay-compiler? (or I do not understand the schematics enough behind the extended types and how relay is supposed to work)
```
- import { ConcreteRequest, Query } from 'relay-runtime';
+ import { ClientRequest, ClientQuery } from 'relay-runtime';
```


Anyway, I am trying the merge lib as you suggested. Will update back soon :)

**Comment by giautm** [comment]
```
  schema: './schema.graphql',
  schemaExtensions: ['./src/schema'],
```
@sanketplus: please double check the relay.config.js, do you have the `schemaExtensions` here? It's the option to let relay known the type is local.

**Comment by sanketplus** [comment]
tried that too @giautm but the afaik the fact is that the `extend type Query` is not local? Relay may be mistaking any `extend type` as local but extending Query should not be?

**Comment by sanketplus** [comment]
Also the module does the trick, ie: merges the type and extended type defs. leaving the script here for future ref :)

```
#!/usr/bin/env node

const { loadFilesSync } = require('@graphql-tools/load-files')
const { mergeTypeDefs } = require('@graphql-tools/merge')
const { print } = require('graphql')
const fs = require('fs')

const loadedFiles = loadFilesSync(`${__dirname}/*.graphql`)
const typeDefs = mergeTypeDefs(loadedFiles)
const printedTypeDefs = print(typeDefs)
fs.writeFileSync('joined.graphql', printedTypeDefs)
```

#thanks @giautm a ton for a pointer to the library :)
