### ISSUE TITLE
Why the template of HasEdge and HasEdgeWith differs in the sqlgrph.To target table?

### ISSUE THREAD

**Issue by Epsirom** [ent/ent#3143]
In the latest commit and the earliest sqlgraph commit of entc/gen/template/dialect/sql/predicate.tmpl:

https://github.com/ent/ent/blob/2c63d1d70e/entc/gen/template/dialect/sql/predicate.tmpl#L60
https://github.com/ent/ent/blob/f7ce61fc3c/entc/gen/template/dialect/sql/predicate.tmpl#L67

The `HasEdge` implements with `sqlgraph.To` `TableConstant` in the condition `!HasCompositeID`, but the `HasEdgeWith` use `InverseTableConstant` in the same condition.

The implementation keeps a long time (3 years), which confuses me whether I have misunderstood, or it is a bug?

**Comment by a8m** [comment]
Hey @Epsirom 👋 
Just to ensure, do you mean why the `dialect/sql/predicate/edge/has` template was changed? It was modified a few months ago to add support for [Edge Schemas](https://entgo.io/docs/schema-edges#edge-schema).

Do you mean the difference between these 2:
https://github.com/ent/ent/blob/master/entc/gen/template/dialect/sql/predicate.tmpl#L58-L64
https://github.com/ent/ent/blob/master/entc/gen/template/dialect/sql/predicate.tmpl#L94-L100

**Comment by Epsirom** [comment]
> Hey @Epsirom 👋 Just to ensure, do you mean why the `dialect/sql/predicate/edge/has` template was changed? It was modified a few months ago to add support for [Edge Schemas](https://entgo.io/docs/schema-edges#edge-schema).
> 
> Do you mean the difference between these 2: https://github.com/ent/ent/blob/master/entc/gen/template/dialect/sql/predicate.tmpl#L58-L64 https://github.com/ent/ent/blob/master/entc/gen/template/dialect/sql/predicate.tmpl#L94-L100

Thanks for your reply.
I figure out that it is my mistake. I wrote an additional `has` template for soft deletion, which adds a `sqlgraph.HasNeighborsWith` to the sqlgraph step. The addition generates `SELECT` SQL in the same table and confused me.

Thank you again for your work.

**Comment by a8m** [comment]
I submitted https://github.com/ent/ent/pull/3144 to clarify that `Has<E>` does not need the `sqlgraph.To` option.
