### ISSUE TITLE
ent entity create_time in mysql  less than current local time(Asia/Shanghai) 8 hour

### ISSUE THREAD

**Issue by minicloudsky** [ent/ent#3146]
I use ent to to generate my entity,however, the column create_time in my mysql database table is 8h less than My current timezone(Asia/Shanghai) local time,how to config to use my local time

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
mysql time less than my localtime time 8 hour

## Expected Behavior 🤔
the create time is equals my local time

## Steps to Reproduce 🕹

golang code in my project mixin.go
```
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/mixin"
	"time"
)

// -------------------------------------------------
// Mixin definition

// TimeMixin implements the ent.Mixin for sharing
type TimeMixin struct {
	// We embed the `mixin.Schema` to avoid
	// implementing the rest of the methods.
	mixin.Schema
}

func (TimeMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Time("create_time").SchemaType(map[string]string{
			dialect.MySQL: "datetime",
		}).Default(time.Now).
			Annotations(
				entsql.Annotation{
					Default: "CURRENT_TIMESTAMP",
				},
			),
		field.Time("update_time").SchemaType(map[string]string{
			dialect.MySQL: "datetime",
		}).Default(time.Now).UpdateDefault(time.Now).
			Annotations(
				entsql.Annotation{
					Default: "CURRENT_TIMESTAMP",
					Options: "ON UPDATE CURRENT_TIMESTAMP",
				},
			),
	}
}

```

golang code in my project instance.go
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

// Instance holds the schema definition for the Instance entity.
type Instance struct {
	ent.Schema
}

// Annotations of the Instance.
func (Instance) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{
			Table: "t_db_instance",
		},
	}
}

// Mixin of the Instance.
func (Instance) Mixin() []ent.Mixin {
	return []ent.Mixin{
		TimeMixin{},
	}
}

// Fields of the Instance.
func (Instance) Fields() []ent.Field {
	return []ent.Field{
		field.String("env").NotEmpty(),
		field.String("instance_type").NotEmpty().Default(""),
		field.String("engine").NotEmpty().Default(""),
	}
}

// Edges of the Instance.
func (Instance) Edges() []ent.Edge {
	return nil
}

```
## Your Environment 🌎
entgo.io/ent v0.11.4
mysql 8.0
my mysql timezone
<img width="601" alt="image" src="https://user-images.githubusercontent.com/32286819/205486951-6e6c2ee0-2a46-4f1f-a5e7-8273e5aaaeb6.png">

| Tech        | Version |
| ----------- | ------- |
| Go          | go1.18.2 darwin/amd64|
| Ent         | 0.11.4   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |
|DataSource | root:root@tcp(127.0.0.1:3306)/mydb?parseTime=True|

**Comment by a8m** [comment]
Hey @minicloudsky, you can set the location time using the `loc` option. See: https://github.com/go-sql-driver/mysql#loc

**Comment by a8m** [comment]
Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by minicloudsky** [comment]
> https://github.com/go-sql-driver/mysql#loc

ok,I gotta it，thanks brother for your kindness help~
