### ISSUE TITLE
Please add Driver() method for get the driver of Client/Tx

### ISSUE THREAD

**Issue by piyongcai** [ent/ent#3147]
Please add Driver() method for get the driver of Client/Tx.
```go
// entc/gen/template/client.tmpl

// Driver returns the driver of tx.
func (tx *Tx) Driver() dialect.Driver {
	return tx.driver
}

// ---------------------------------

// entc/gen/template/tx.tmpl
// Driver returns the driver of client.
func (c *Client) Driver() dialect.Driver {
	return c.driver
}
```

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

sometimes, you must user Multiple shema written using ent/ent, such as user/role, order, payment, etc., in order to operations with multiple scheme in one transaction, you must get the Dirver in the transaction to build the Client. eg
```go
import (
  "entgo.io/ent/dialect"
  entSql "entgo.io/ent/dialect/sql"

  orderEnt ".../order/ent"
  payEnt ".../pay/ent"
)

func main(){
    var ctx = context.Background()
    var dsn = "postgresql://postgres:123@127.0.0.1/postgres"
    db, err := sql.Open("pgx", dsn)
    if err != nil {
      // handler error
    }
    drv := entSql.OpenDB(dialect.Postgres, db)

    orderClient := orderEnt.NewClient()

    // begin trans
    orderTx, err := orderClient.Tx(ctx)
    if err != nil {
       // handler error
    }
    // order op, eg create order etc...
    ....

    var orderDrv =  orderTx.Driver()                 // <---------- HERE get the hold transtion Driver of orderTx
    payClient := orderEnt.NewClient(payEnt.Driver(orderDrv )) // <---------- HERE user the orderDrv
    // payments op, eg: create payments log, payments records.... etc

    // commit or rollback
    orderTx.Commit()   // orderTx.Rollback()
}
```

just add Driver() method for return driver of the Client/Tx

**Comment by nzlov** [comment]
https://entgo.io/docs/transactions

**Comment by piyongcai** [comment]
> https://entgo.io/docs/transactions

in my case,  orderEnt and payEnt as two ent projects from different projects，and have different client，
orderEnt->orderEnt.Client payEnt->payEnt.Client

```text
orderEnt ".../order/ent"
payEnt ".../pay/ent"
```

**Comment by nzlov** [comment]
add `txextra.tmpl` in `ent/templates`:
```
{{/* gotype: entgo.io/ent/entc/gen.Graph */}}

{{ define "txextra" }}

{{/* Add the base header for the generated file */}}
{{ $pkg := base $.Config.Package }}
{{ template "header" $ }}

func (tx *Tx) Driver() dialect.Driver {
	return tx.driver
}


{{ end }}
```

add `--template ./templates` in `ent/generate.go`.

re-generate.

**Comment by nzlov** [comment]
add `extra.tmpl` in `ent/templates`:
```
{{/* gotype: entgo.io/ent/entc/gen.Graph */}}

{{ define "extra" }}

{{/* Add the base header for the generated file */}}
{{ $pkg := base $.Config.Package }}
{{ template "header" $ }}

func (tx *Tx) Driver() dialect.Driver {
	return tx.driver
}

func (c *Client) Driver() dialect.Driver {
	return c.driver
}

{{ end }}

```

add `--template ./templates` in `ent/generate.go` and `re-generate`

**Comment by nzlov** [comment]
@a8m  you may not have understood this issue.

eg:

```
projecta
-    ent
- -      schema
- - -        user.go
- -      client.go

projectb
-    ent
- -      schema
- - -        role.go
- -      client.go


projectc
-    main.go
```

How to update `user` and `role` in `main.go` using one transaction

**Comment by piyongcai** [comment]
> @a8m you may not have understood this issue.
> 
> eg:
> 
> ```
> projecta
> -    ent
> - -      schema
> - - -        user.go
> - -      client.go
> 
> projectb
> -    ent
> - -      schema
> - - -        role.go
> - -      client.go
> 
> 
> projectc
> -    main.go
> ```
> 
> How to update and in using one transaction`user``role``main.go`


yes, This is a correct example

**Comment by a8m** [comment]
Got it. Thanks for explaining, @nzlov. 

@piyongcai, @nzlov's example should work for you. Using templates in Ent is quite common. This helps you extend Ent for your needs.

Let me know if we can close this issue.  You're also welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by piyongcai** [comment]
@a8m @nzlov 

thanks. @nzlov's example should work for me.
you can close it.
