### ISSUE TITLE
Annotations entgql.Type Map got issue

### ISSUE THREAD

**Issue by oaktreecode** [ent/ent#3151]
`
field.JSON("extra_data1", []map[string]interface{}{}).
			Annotations(
				entgql.Type("Map"),
			).
			Optional().
			Comment("extra"),
`

but got the Graphql  schema   not []Map

extraData1  Map 

I want to get the "extraData1  []Map "

 

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.9.?   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by giautm** [comment]
Hello @oaktreecode, can you try to use `entgql.Type("[]Map")` as @nzlov suggests? It should resolve your issue. If not, please let me know. I'm happy to support you.

**Comment by giautm** [comment]
@oaktreecode hello, this issue was fixed in v0.3.4 of entgql. Please do an upgrade to fix
