### ISSUE TITLE
Nested Transactions

### ISSUE THREAD

**Issue by tiago-monteiro-anchorage** [ent/ent#3154]
Hey all,

I came into the following issue when I try to open a new transaction with an already created transaction
`ent: cannot start a transaction within a transaction`

The error looks correct but I would like to know if there is a way to return the existing open transaction instead of returning this error and if it makes sense.

Cheers

**Comment by a8m** [comment]
Hey @tiago-monteiro-anchorage 👋 

I assume you use the [Transactional Client
](https://entgo.io/docs/transactions/#transactional-client) to open a new transaction, so there is code that already calls `Client` on this transaction. If you're using [entgql](https://entgo.io/docs/tutorial-todo-gql-tx-mutation), you can get `TxFromContext` instead.

> The error looks correct but I would like to know if there is a way to return the existing open transaction instead of returning this error and if it makes sense.

No way, but you can use custom templates to add logic. 

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
