### ISSUE TITLE
what's the code meaning?

### ISSUE THREAD

**Issue by marol1210** [ent/ent#3174]
thks advance for help!

I am new to ent.   when i readed source code ,  i found method `Type` of  `Interface`  that  not in  Schema. 

Question:  Why is Type method  not in Schema ?
 
type Schema struct {
	[Interface](https://pkg.go.dev/entgo.io/ent#Interface)
}

![image](https://user-images.githubusercontent.com/7519301/208075835-bcab21d9-1384-447e-8403-f56061d1bdd4.png)

**Comment by a8m** [comment]
Hey @marol1210 👋 
The purpose of this "meta" function is to get the type name in edge declarations. For example:

```go
edge.To("pets", Pet.Type)

edge.From("owner", User.Type).
    Ref("pets")
```

Closing, but feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) and continue the discussion there.
