### ISSUE TITLE
GQL Possible to clear edges and then add (or override all edges e.g. setGroupIDs(ids...))

### ISSUE THREAD

**Issue by diazoxide** [ent/ent#3175]
On update mutation need to set whole value of edges.

Right now EntGQL provides only add and remove methods for not unique edges.

e.g. 
### this is what I need
```
mutation ($input: UpdateSitemapInput!, $id: ID!) {
  updateSitemap(input:{
    setGroupIDs: ["some_id", "some_id"]
  }){
    id
  }
}
```

### but also we can handle it like this
```
mutation ($input: UpdateSitemapInput!, $id: ID!) {
  updateSitemap(input:{
    clearGroupIDs: true,
    addGroupIDs: ["some_id", "some_id"]
  }){
    id
  }
}
```

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by diazoxide** [comment]
@a8m I'm amazed how fast you work 😮

**Comment by a8m** [comment]
Thanks, @diazoxide 🙏 

Feel free to update your entgql version to master to get it.
