### ISSUE TITLE
how can i do to optimize the performance?

### ISSUE THREAD

**Issue by CNTWDev** [ent/ent#3177]
i have a scene to get a result by rand.
it is slow when i use function "rand".
now i change it to use offset,but it is also slow, while offset is large.

so how can i do ,thanks.
@a8m

**Comment by a8m** [comment]
Hey @CNTWDev 👋 
Sorry that I can't help with this. This is a general SQL question and not specific to Ent, and I'm sure you'll find better answers than mine on StackOverflow - I searched, and it's a common question. 

> now i change it to use offset,but it is also slow, while offset is large.

That makes sense. These 2 links might help you: https://entgo.io/blog/2021/12/09/contributing-my-first-feature-to-ent-grpc-plugin#keyset-pagination, https://use-the-index-luke.com/sql/partial-results/fetch-next-page.

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) and someone might be able to help you with this 😎
