### ISSUE TITLE
How create a custom field for file handling

### ISSUE THREAD

**Issue by linuxluigi** [ent/ent#3189]
Hey, how to create a custom field for file handling. So that a User can upload a file via a generated gRPC service and the content of the file will be stored on a local file path. While a User create a get request on a field resource, he will get the content of the file with same metadata like name & hash.

As orientation I like the way, how Django did this: <https://docs.djangoproject.com/en/3.2/_modules/django/db/models/fields/files/>

Currently, I'm kind lost and do not know where to start. My end goal, would be to store the file on a S3 service.

Thanks for any help.

**Comment by a8m** [comment]
Hey @linuxluigi 👋 

- What do you expect to store in Ent, the path to file? 
- What do you use for client/server? GraphQL, REST, or gRPC? In GraphQL, there's a way to extend the type with a custom field and then customize the field resolver. That's similar to your use case - when API and the database entities are not identical.

**Comment by linuxluigi** [comment]
Hey @a8m 👋,

thanks for your fast response 😊

- Yeah, I want to store the path of the file.
- For now, I just want to use gRPC. Thanks for the tip with GraphQL, I also through to do it with GraphQL.

**Comment by rotemtam** [comment]
This can be done using hooks, see this blog post:

https://entgo.io/blog/2021/11/1/sync-to-external-data-systems-using-hooks

**Comment by linuxluigi** [comment]
Thanks @rotemtam  & @a8m, this help me to get a starting 🙂
