### ISSUE TITLE
add a custom field helper for schema with gqlgen

### ISSUE THREAD

**Issue by sahmadreza** [ent/ent#3196]
I use `gqlgen` to make `GraphQL`  service with `ent` framework

**Question**
how can I add a custom field that the database does not exist?

**Example**
for example, I have user schema like this 

`ent/schema/user.go`
```go
type User struct {
	ent.Schema
}
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id"),
		field.String("username"),
		field.String("role").Sensitive(),
	}
}
```

ent generated `ent.graphql` 
```graphql
type User {
  id: ID!
  username: String!
}
```
Now I want to add a field helper with the name `isAdmin` in `graphql`
```graphql
type User {
  ...
  isAdmin: Boolean! // check if user role == "admin"
}
```

**My try**
I try to create a custom `template` for adding `additional fields` for `user` like that but that's not working and generated `ent.graphql`  have no change.

`ent/template/user_additional.go`
```go
{{ define "model/fields/additional" }}
    {{- if eq $.Name "User" }}
        // IsAdmin defined by template.
        isAdmin bool `json:"isAdmin,omitempty" gqlgen:"isAdmin"`
    {{- end }}
{{ end }}
```

`ent/entc.go`
```go
func main() {
ex, err := entgql.NewExtension(
		entgql.WithConfigPath("./gqlgen.yml"),
		entgql.WithSchemaGenerator(),
		entgql.WithSchemaPath("./ent.graphql"),
		entgql.WithWhereInputs(true),
	)
opts := []entc.Option{
		entc.TemplateDir("./ent/template"),
		entc.Extensions(ex),
	}

	if err := entc.Generate("./ent/schema", &gen.Config{
		Templates: entgql.AllTemplates,
	}, opts...); err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}

}
```

**Comment by giautm** [comment]
hello @sahmadreza, you can extend the type generated by ent by using extend keyword in another GQL file. GQLGen will generate a resolver for any missing property from the type. Or you can generate the field via the template and gqlgen will auto mapping it

```gql
extend type User {
  isAdmin: Boolean!
}
```

**Comment by sahmadreza** [comment]
Hi @giautm ,

Your suggestion worked well.

**Solution**

1. create a new GQL file and add to `gqlgen.yml`

`./custom.graphql` :
```graphql
extend type User {
  isAdmin: Boolean!
}
```

`gqlgen.yml` :
```yml
...
schema:
  -  ./custom.graphql
  -  ./ent.graphql
 ...
```

2. add a new template for user additional fields 

`./ent/template/user_additional.tmp` :
```go
{{ define "user_additional" }}
    {{/* Add the base header for the generated file */}}
    {{ $pkg := base $.Config.Package }}

    {{ template "header" $ }}

    // return true if user is admin
    func (m *User) IsAdmin() bool {
            return m.Role == "admin"
    }
    
{{ end }}
```
