### ISSUE TITLE
Graphql "OR" predicate not working right with ID field

### ISSUE THREAD

**Issue by diazoxide** [ent/ent#3202]
I noticed that on Graphql when using or predicate and put in or section ID field, it's like ID field is skipping.
I only checked Graphql, so maybe on code all is right.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

### This example is getting <=0 result
```graphql
{
  "where": {
    "or": {
      "someStr": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed",
      "someStr2": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed",
      "id": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed"
    }
  }
}
```

### This example is getting >=1 result
```graphql
{
  "where": {
      "id": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed"
  }
}
```
## Expected Behavior 🤔

So or field should support ID fields too.

## Steps to Reproduce 🕹

Steps:

1.  Run any query with or predicate
2. Use ID field on `or` section
3. Compare result with direct ID field filter result

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | master |
| Database    | Postgresql   |

**Comment by a8m** [comment]
Thanks for reporting this, @diazoxide.
Can you please reproduce this with a simple test case in entgql repository: https://github.com/ent/contrib/blob/master/entgql/internal/todo/todo_test.go? 🙏

**Comment by diazoxide** [comment]
I think this is just wrong query representation.

I correct my query so `or` field should be array of maps instead of map

```
{
  "where": {
    // Wrong
    "or": {
      "someStr": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed",
      "someStr2": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed",
      "id": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed"
    },
     // Right
    "or": [
      {"someStr": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed"},
      {"someStr2": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed"},
      {"id": "0208e28b-cbfd-5a71-bb06-0e9d79d327ed"}
    ]
  }
}
``` 

So I'm closing the issue.
