### ISSUE TITLE
Running go generate nondeterministically changes generated code

### ISSUE THREAD

**Issue by jdhenke** [ent/ent#3208]
Running `go generate` nondeterministically changes the generated code that ent produces.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
# running generation the first time produces a diff
$ go generate -x ./services/index/internal/ent
go run -mod=mod entgo.io/ent/cmd/ent generate ./schema --feature sql/upsert
$ git diff -- services/index/internal/ent/ent.go
diff --git a/services/index/internal/ent/ent.go b/services/index/internal/ent/ent.go
index 6da39c7..e824fbd 100644
--- a/services/index/internal/ent/ent.go
+++ b/services/index/internal/ent/ent.go
@@ -11,6 +11,7 @@ import (
        "entgo.io/ent"
        "entgo.io/ent/dialect/sql"
        "entgo.io/ent/dialect/sql/sqlgraph"
+
        entfield "gitlab.com/adyton/platform/services/index/internal/ent/field"

# re-running generation produces a different output which this time happens to match what's checked in, so no diff
$ go generate -x ./services/index/internal/ent  
go run -mod=mod entgo.io/ent/cmd/ent generate ./schema --feature sql/upsert
$ git diff -- services/index/internal/ent/ent.go
$ grep entgo.io go.mod
        entgo.io/ent v0.11.5-0.20230102205927-542f36d4abda

```

## Expected Behavior 🤔

Code generation should be deterministic and not result in any changes.

## Steps to Reproduce 🕹

See above.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go version go1.19.4 darwin/amd64  |
| Ent         | entgo.io/ent v0.11.5-0.20230102205927-542f36d4abda   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/lib/pq       |

**Comment by a8m** [comment]
Hey @jdhenke 👋 
As discussed on Discord, can you please provide an example that reproduces it using https://github.com/ent/bug? Thanks 🙏

**Comment by jdhenke** [comment]
@a8m reproduced here: https://github.com/jdhenke/ent-3208/pull/1

I'm guessing it has to do with creating an entity called `Field` which forces a named import which hits an edge case in the code generation that makes the output non-deterministic.

```
ent-3208 (repro=)$ go run entgo.io/ent/cmd/ent describe ./ent/schema 
Field:
        +-------+------+--------+----------+----------+---------+---------------+-----------+---------------------+------------+---------+
        | Field | Type | Unique | Optional | Nillable | Default | UpdateDefault | Immutable |      StructTag      | Validators | Comment |
        +-------+------+--------+----------+----------+---------+---------------+-----------+---------------------+------------+---------+
        | id    | int  | false  | false    | false    | false   | false         | false     | json:"id,omitempty" |          0 |         |
        +-------+------+--------+----------+----------+---------+---------------+-----------+---------------------+------------+---------+
        
User:
        +-------+--------+--------+----------+----------+---------+---------------+-----------+-----------------------+------------+---------+
        | Field |  Type  | Unique | Optional | Nillable | Default | UpdateDefault | Immutable |       StructTag       | Validators | Comment |
        +-------+--------+--------+----------+----------+---------+---------------+-----------+-----------------------+------------+---------+
        | id    | int    | false  | false    | false    | false   | false         | false     | json:"id,omitempty"   |          0 |         |
        | age   | int    | false  | false    | false    | false   | false         | false     | json:"age,omitempty"  |          0 |         |
        | name  | string | true   | false    | false    | false   | false         | false     | json:"name,omitempty" |          0 |         |
        +-------+--------+--------+----------+----------+---------+---------------+-----------+-----------------------+------------+---------+
        

```

**Comment by a8m** [comment]
Thanks a lot for the example repo, @jdhenke. It helped me to reproduce this issue.

This was fixed with https://github.com/ent/ent/issues/3208, and I verified it with the following command:

```bash
repeat 50 { go generate ./... && git --no-pager diff }
```

Please, update Ent to the latest master and let me know if there are any issues with it.

**Comment by jdhenke** [comment]
Amazing, thanks @a8m ! Verified this works for me, good to close 👍

Also, for any future readers here, I'd note that it's actually #3209 with the fix.

**Comment by migmartri** [comment]
Hi, first of all thanks for reporting this issue and releasing a patch!

But I am afraid that the fix [does not seem to be working](https://github.com/migmartri/ent-gen-troubleshoot-example) for me.

I believe that indeed the issue is when a named import is present as @jdhenke mentioned before.

I have created a [sample repository](https://github.com/migmartri/ent-gen-troubleshoot-example) where you could potentially reproduce the issue. Let me know if I am missing something orhow I could help with.

Thanks,
Miguel

**Comment by migmartri** [comment]
@jdhenke jfyi

I saw that you mentioned here https://github.com/ent/ent/issues/3208#issuecomment-1370372185  an issue with named imports. 

I reported https://github.com/ent/ent/issues/3340 that the issue was present even in the latest release  but @a8m just merged a fix (thanks!)

**Comment by jdhenke** [comment]
Thanks for the heads up @migmartri and the fix @a8m! 🙏
