### ISSUE TITLE
How to do multi conditional query?

### ISSUE THREAD

**Issue by noahge** [ent/ent#3210]
Like

if Current != 0 {
    db.Query.Offset(Current)
} 

if PageSize != 0 {
    db.Query.Limit(PageSize)
}

if ......

**I want to assemble different query conditions to finally query the desired result.**

What should I do?

**Comment by khanakia** [comment]
Check this
```
curr := 1
page := 2

query := client.User.Query()

if curr != 1 {
	query.Offset(curr)
}

if page != 1 {
	query.Limit(page)
}

users, err := query.All(ctx)

fmt.Println(users, err)
```

**Comment by a8m** [comment]
Thanks for the help, @khanakia. 

Closing. @noahge, please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
