### ISSUE TITLE
[Question] M2M same type with additional field

### ISSUE THREAD

**Issue by sahmadreza** [ent/ent#3213]
**Question**
How can I add an additional field to m2m (same type)?

for **example**, following-followers with a time field

**ent/schema/user.go**
```go
func (User) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("following", User.Type).
            From("followers"),
    }
}
```

**Comment by a8m** [comment]
Hey @sahmadreza 👋🏻
You can use the edge-schema option for this: https://entgo.io/docs/schema-edges#edge-schema

**Comment by sahmadreza** [comment]
> Hey @sahmadreza 👋🏻 You can use the edge-schema option for this: https://entgo.io/docs/schema-edges#edge-schema

Hi @a8m
Thank you for your advice

I did the following example
How can I get the followers and followings of a user, how should the query be written?

`ent/schema/user.go`
```go
func (User) Edges() []ent.Edge {
    return []ent.Edge{
		edge.To("following", User.Type).
			Through("follow", Follow.Type),
    }
}
```

`ent/schema/follow.go`
```go
// Fields of the Follow.
func (Follow) Fields() []ent.Field {
	return []ent.Field{
		field.Int("user_id"),
		field.Int("following_id"),
		field.Time("confirmed_at").
			Optional().
			Nillable(),
		field.Time("created_at").
			Default(time.Now),
	}
}

// Edges of the Follow.
func (Follow) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("user", User.Type).
			Required().
			Unique().
			Field("user_id"),
		edge.To("following", User.Type).
			Required().
			Unique().
			Field("following_id"),
	}
}
```

**Comment by a8m** [comment]
The API is the same regular edges. You can call both QueryFollowing/Followers and query the join-table as well. This directory contains many edge-schema examples: https://github.com/ent/ent/tree/master/entc/integration/edgeschema

Closing, but join our Discord server in case you need more help with this.
