### ISSUE TITLE
UpdateDefault function not generated

### ISSUE THREAD

**Issue by winterssy** [ent/ent#3217]
UpdateDefault function not generated if there is no default or other validators

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Like the code belows, the UpdateDefault function of `updated_at` filed not geneated

```go
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.Int("count"),
		field.Time("created_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			),
		field.Time("updated_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			).
			UpdateDefault(time.Now),
	}
}
```

but if we add a Default function, it works

```go
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.Int("count"),
		field.Time("created_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			),
		field.Time("updated_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			).
			Default(time.Now). // add default function
			UpdateDefault(time.Now),
	}
}
```

and if we add a default value on another field, it also works

```go
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.Int("count").Default(0), // add default value
		field.Time("created_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			),
		field.Time("updated_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			).
			UpdateDefault(time.Now),
	}
}
```

or add a validator, it also works

```go
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.Int("count").Positive(), // add validator
		field.Time("created_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			),
		field.Time("updated_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			).
			UpdateDefault(time.Now),
	}
}
```

## Expected Behavior 🤔

The code belows should genreate the `UpdateDefaultUpdatedAt` function

```go
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.Int("count"),
		field.Time("created_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			),
		field.Time("updated_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			).
			UpdateDefault(time.Now),
	}
}
```

## Steps to Reproduce 🕹

Steps:

1. `go mod init entdemo`
2. `go run -mod=mod entgo.io/ent/cmd/ent init Product`
3. edit the file `ent/schema/product.go`

```go
// Fields of the Product.
func (Product) Fields() []ent.Field {
	return []ent.Field{
		field.Int("count").Positive(),
		field.Time("created_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			),
		field.Time("updated_at").
			Nillable().
			Optional().
			Annotations(
				entsql.Default("CURRENT_TIMESTAMP"),
			).
			UpdateDefault(time.Now),
	}
}
```

4. `go generate ./ent` , there is no error, but no `UpdateDefaultUpdatedAt` function was generated.

5. since no `UpdateDefaultUpdatedAt` function was generated, `go build` will failed.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.4  |
| Ent         | v0.11.6-0.20230108132740-19670ad4b555   |
| Database    | PostgreSQL   |
| Driver      | https://github.com/lib/pq        |

**Comment by crossworth** [comment]
Hello @winterssy, great report, I was able to find the problem and [created a PR](https://github.com/ent/ent/pull/3276).

Thanks again for the report.
