### ISSUE TITLE
Generate clobbering method receiver when schema struct name starts with "N"

### ISSUE THREAD

**Issue by mavericksy** [ent/ent#3222]
https://github.com/ent/ent/blob/34bd0b7b6f72a93022998be2cc1ca6e9bd97113b/entc/gen/template/dialect/sql/update.tmpl#L25

In both the update and create templates, the $ret variable defaults to "n" for an int return when not a single return.
This breaks the update and create sqlSave functions when the ent.Schema struct is named with the first letter being "N".
Essentially clobbering its own method receiver variable.
ie:
![Screenshot from 2023-01-09 14-01-01](https://user-images.githubusercontent.com/8345181/211303498-9d289753-f43f-4779-aefa-cd29f67ca369.png)

![Screenshot from 2023-01-09 14-03-24](https://user-images.githubusercontent.com/8345181/211303831-bcf84820-365f-4767-b09d-9575d55db7e4.png)

![Screenshot from 2023-01-09 14-04-29](https://user-images.githubusercontent.com/8345181/211304201-9459a785-da1c-4c97-aa17-f071beaf43c9.png)

![Screenshot from 2023-01-09 14-04-51](https://user-images.githubusercontent.com/8345181/211304254-4fcfea5d-7f73-45f3-aede-ad819f4b927b.png)

Renaming the struct to something other than starting with an "N" resolves the issue.

**Comment by a8m** [comment]
Thanks for reporting this, @mavericksy 🙏 

This should be fixed with https://github.com/ent/ent/pull/3227.
