### ISSUE TITLE
How to set a field or property on edge?

### ISSUE THREAD

**Issue by allochi** [ent/ent#3223]
I really tried to understand the documentation, but I couldn't figure out how to set a  property on the edge.

For example, let's say I have some `Beverage` entities and these are `SoldIn` some `CoffeeShops`, how can I attach a `price` on the edge `SoldIn`? like this

`Tea` -`SoldIn (price: 3)`-> `Starbucks`
`Tea` -`SoldIn (price: 1)`-> `Boreal`

`Tea` has two edges to two different `CoffeeShops`, and in each it has a different `price`.

Would appreciate the help, as I'm trying to evaluate `ent` for our use, thanks :)

**Comment by a8m** [comment]
Hey @allochi 👋🏻
You can use edge schemas for creating M2M edges with additional fields. See: https://entgo.io/docs/schema-edges#edge-schema

**Comment by allochi** [comment]
Thanks a lot for your reply, it's still unclear for me, so I followed the instructions and have

```go
// ---------- Beverage 

// Beverage holds the schema definition for the Beverage entity.
type Beverage struct {
	ent.Schema
}

// Fields of the Beverage.
func (Beverage) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").NotEmpty().Unique(),
	}
}

// Edges of the Beverage.
func (Beverage) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("CoffeeShops", CoffeeShop.Type).Through("SoldIn", SoldIn.Type),
	}
}

// ---------- CoffeeShop 

// CoffeeShop holds the schema definition for the CoffeeShop entity.
type CoffeeShop struct {
	ent.Schema
}

// Fields of the CoffeeShop.
func (CoffeeShop) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").NotEmpty().Unique(),
	}
}

// Edges of the CoffeeShop.
func (CoffeeShop) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("Beverages", Beverage.Type).Ref("CoffeeShops").Through("SoldIn", SoldIn.Type),
	}
}

// ---------- SoldIn 

// SoldIn holds the schema definition for the SoldIn entity.
type SoldIn struct {
	ent.Schema
}

func (SoldIn) Annotations() []schema.Annotation {
	return []schema.Annotation{
		field.ID("beverage_id", "coffee_shop_id"),
	}
}

// Fields of the SoldIn.
func (SoldIn) Fields() []ent.Field {
	return []ent.Field{
		field.Float("price").Default(0),
		field.Int("beverage_id"),
		field.Int("coffee_shop_id"),
	}
}

// Edges of the SoldIn.
func (SoldIn) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("Beverage", Beverage.Type).
			Unique().
			Required().
			Field("beverage_id"),
		edge.To("CoffeeShop", CoffeeShop.Type).
			Unique().
			Required().
			Field("coffee_shop_id"),
	}
}
```

but then how to I add a `SoldIn`? the generated code only include `AddCoffeeShops`, is there a complete example you can link?

**Comment by a8m** [comment]
If you add `Beverage ` to `CoffeeShops`, the `SoldIn` edge is created automatically (with default values set in the schema). However, if you want to create `SolidIn` separately and have more control over its fields, use the `SolidIn` builder. There are no extra statements to the database here, because instead of writing to the join table in from `Beverage`, you do it from `SolidIn`. Here's an example:

```go
client.SolidIn.Create().
	SetPrice(...)
	SetBeverageID(...).
	SetCoffeeShopID(...).
	Exec(ctx)
```
