### ISSUE TITLE
Can I use UUID as binary in MySQL?

### ISSUE THREAD

**Issue by yuta-hidaka** [ent/ent#3225]
Hi there.

Thank you for providing your great package.
I'm using this with MySQL.

Now I'm trying to use UUID as PK.

Using UUID with char(36) in MySQL, we need to consider indexing performance.

So I would like to use UUID as binary.

It can be for this package?

For now, I'm just putting the UUID field in my code.

```
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New),
		field.Int("age").
			Positive(),
		field.String("name").
			Default("unknown"),
	}
}

```

And DB structure was char(36).
So I would like to use binary instead of str(36).
Is this possible in ent package?

<img width="996" alt="image" src="https://user-images.githubusercontent.com/46583585/211528333-a95693b3-24db-4ad2-9cd3-8735ca15d095.png">

**Comment by a8m** [comment]
Hey @yuta-hidaka 👋 
You can configure the underlying database type using the [`SchemaType`](https://entgo.io/docs/schema-fields/#database-type) option. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by yuta-hidaka** [comment]
@a8m 
Thanks for the tip!

I tried like this.
```
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent. Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New).
            SchemaType(map[string]string{
                dialect.MySQL:    "binary(16)",   // Override MySQL.
            }),
	}
}
```

but I got an error.

`failed creating user: Error 1406 (22001): Data too long for column 'id' at row 1`

Of course because of the wrong type between DB and going so next question is, how can I handle binary in ent?

I saw in your code, you look like care about UUID in MySQL https://github.com/ent/ent/blob/891fc8fecf4106966489caab7095575d0fac6c6b/dialect/sql/schema/mysql.go#L281, So if don't mind could you provide some example using UUID as binary?🙇

Sorry for bothering you ...

**Comment by a8m** [comment]
You can create a custom type and override the way the arg is formatted (with `UUID_TO_BIN`). See this example: https://github.com/a8m/entspatial/blob/master/ent/schema/point.go#L41
