### ISSUE TITLE
"Api" Schema, generage type As "APIClient", but use as "ApiClient"

### ISSUE THREAD

**Issue by piyongcai** [ent/ent#3230]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

"Api" Schema, generage type As "APIClient", but use as "ApiClient"

## Expected Behavior 🤔

keep name as ApiClient

## Steps to Reproduce 🕹

Steps:

1. define api Schema
```golang
   package schema

import "entgo.io/ent"

// Api holds the schema definition for the Api entity.
type Api struct {
	ent.Schema
}

// Fields of the Api.
func (Api) Fields() []ent.Field {
	return nil
}

// Edges of the Api.
func (Api) Edges() []ent.Edge {
	return nil
}  
```

2. and run generate
3. check  client.go, you can find APIClient, but other code named as "ApiClient"
```golang
//  .....
type APIClient struct {   <------ define as APIClient
	config
}

// ....

type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Api is the client for interacting with the Api builders.
	Api *ApiClient    <-------------- but using as ApiClient
}

// using as ApiClient
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.?  |
| Ent         | 0.11.5   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by khanakia** [comment]
It's default expected behavior so Api becomes API because of this code https://github.com/ent/ent/blob/master/entc/gen/type.go#L800

It's also according to the GOLANG standards for **acronyms** https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Comment by piyongcai** [comment]
@a8m 
I think the 0.11.4 version in a better way because the name is determined by the coder, not by the ent framework.
If upgrade ent,  named by by the ent framework will cause the previous code will not run.

`version 0.11.4, client.tmpl, line 147`
```text
{{ range $n := $.Nodes }}
{{ $client := print $n.Name "Client" }}                                  // LINE: 147, client named by coder
// {{ $client }} is a client for the {{ $n.Name }} schema.
type {{ $client }} struct {
	config
}
```

`version 0.11.5, client.tmpl, line 168`
```text
{{ range $n := $.Nodes }}
{{ $client := $n.ClientName }}                                 // LINE: 168, client named by ent framework.
// {{ $client }} is a client for the {{ $n.Name }} schema.
type {{ $client }} struct {
	config
}
````

**Comment by a8m** [comment]
Fixed with https://github.com/ent/ent/pull/3233. Thanks @khanakia, for the support ❤️
