### ISSUE TITLE
function pascalwords breaking Client code with underscore in schema struct name

### ISSUE THREAD

**Issue by mavericksy** [ent/ent#3241]
![Screenshot from 2023-01-13 16-39-30](https://user-images.githubusercontent.com/8345181/212351644-bbfa32cb-8c31-4cb7-8ac5-7e3291350f36.png)

### Underscore in schema struct name:

![Screenshot from 2023-01-13 16-41-50](https://user-images.githubusercontent.com/8345181/212346787-acd6b139-8266-4ed5-baef-250cf636438a.png)

### Results in a mismatched Name and ClientName due to underscore being removed by `pascalwords`: 
https://github.com/ent/ent/blob/25021635a0181b344d435e979afc02b3dc5a3e7c/entc/gen/func.go#L148
https://github.com/ent/ent/blob/236cd2920c99f0f19767466931a492d4132e54d9/entc/gen/template/client.tmpl#L18
https://github.com/ent/ent/blob/236cd2920c99f0f19767466931a492d4132e54d9/entc/gen/template/client.tmpl#L169

### The above creates a situation where the config client is looking for the `{{ $n.Name }}`
![Screenshot from 2023-01-13 16-44-47](https://user-images.githubusercontent.com/8345181/212348619-16748143-a510-4dd4-b6cb-212676039f9f.png)

### but the generator creates the `{{ $client := $n.ClientName }}` instead
![Screenshot from 2023-01-13 16-42-51](https://user-images.githubusercontent.com/8345181/212348888-f8b0d165-2838-47b5-9458-7cd3f1bc7e98.png)

The underscore is removed in clientname:
https://github.com/ent/ent/blob/542f36d4abda2c679d74217932491c28362e3257/entc/gen/type.go#L801

Not having an underscore in the schema struct name resolves the issue.

**Comment by khanakia** [comment]
Are you using the latest master version ? 
This is what i see and seems to be working correctly
<img width="325" alt="Screenshot 2023-01-14 at 2 29 25 AM" src="https://user-images.githubusercontent.com/2174170/212417997-4dd3c20b-2698-44c6-97c6-5ec35c0aa420.png">

**Comment by mavericksy** [comment]
> Are you using the latest master version ? This is what i see and seems to be working correctly <img alt="Screenshot 2023-01-14 at 2 29 25 AM" width="325" src="https://user-images.githubusercontent.com/2174170/212417997-4dd3c20b-2698-44c6-97c6-5ec35c0aa420.png">

I'm using tag `v0.11.5` and the issue is present. 
Will note exactly the version used when generating. I will debug a little further and confirm.
So far it stands as is.

**Comment by khanakia** [comment]
Install it from master `go get entgo.io/ent@master` and then test

**Comment by a8m** [comment]
Fixed with #3233. Please, upgrade to `@master` as suggested by @khanakia.

Thanks, @khanakia for the support 🙏
