### ISSUE TITLE
Does ent support multi mysql connection?

### ISSUE THREAD

**Issue by surjit** [ent/ent#3245]
I just wondering, If ent support multi mysql connection like Laravel. I have multiple sqlite databases with couple of tables I want to query between those database tables.

Like in laravel we can define/set connection for each model/entity.

**Comment by a8m** [comment]
Hey @surjit 👋 
You can use the [SchemaConfig](https://entgo.io/docs/feature-flags#schema-config) feature flag to work against multiple MySQL databases/schemas in Ent. 

> Like in laravel we can define/set connection for each model/entity.

In Ent, it looks this way:

```go
c, err := ent.Open(dialect, conn, ent.AlternateSchema(ent.SchemaConfig{
    User: "usersdb",
    Car: "carsdb",
}))
c.User.Query().All(ctx) // SELECT * FROM `usersdb`.`users`
c.Car.Query().All(ctx)  // SELECT * FROM `carsdb`.`cars`
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
