### ISSUE TITLE
Support column type XML (Postgres)

### ISSUE THREAD

**Issue by till** [ent/ent#3247]
I'd love to be able to use the column type `xml` (without defining a custom type, etc.).

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Allow defining a column of type `xml` to be able to tap into Postgres features such as input checks and searching (using xpath):
https://www.postgresql.org/docs/9.1/datatype-xml.html

## Motivation 🔦

Less custom code, and utilizing the features of the RDBMS.

**Comment by a8m** [comment]
Hey @till 👋 

You can implement this today using the [`SchemaType`](https://entgo.io/docs/schema-fields/#database-type) option. [Atlas migration](https://github.com/ariga/atlas) knows how to handle it.

There are many examples in the integration tests; check it out and feel free to reopen or join our [Discord](https://discord.gg/qZmPgTE6RX) in case you need more help with this: https://github.com/ent/ent/blob/master/entc/integration/ent/schema/fieldtype.go#L94-L153
