### ISSUE TITLE
How to use coalesce in ent query?

### ISSUE THREAD

**Issue by ramonmedeiros** [ent/ent#3248]
Hi guys,

I'm trying to use coalesce in a query, but I'm not able to substitute the select clause, only append.

Here is my try:

```go
 entClient.Table.
		Query().
		Modify(func(s *sql.Selector) {
	            s.AppendSelectExpr(sql.Column(table.FieldNAME).
			WriteString("COALESCE(").
			Ident(table.FieldNAME).
			Comma().
			//Argf("?", int64(0)).
			WriteString("0)"))
				}
			}
		}).
		Paginate(ctx,
			after,
		......
```

This results in a query like `SELECT field1,field2, COALESCE(field1,0) FROM table`

How can I remove `field1` and keep only `COALESCE(field1,0)`?

**Comment by a8m** [comment]
Hey @ramonmedeiros 👋 
You can use the `SelectExpr` instead. Here's an example:

```go
client.User.Query().
	Modify(func(s *sql.Selector) {
		s.SelectExpr(
			sql.ExprFunc(func(b *sql.Builder) {
				b.WriteString("COALESCE(").Ident(user.FieldAge)
				b.Comma().WriteString("0)")
			}),
		)
	}).
	IntsX(ctx)
```

Also, don't use `sql.Column`. Pass a `sql.ExprFunc` or `sql.Expr` instead.

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by a8m** [comment]
In this case, you can get the selected columns using the following method and manipulate the Selector based on your needs: https://github.com/ent/ent/blob/master/dialect/sql/builder.go#L2230
