### ISSUE TITLE
Publicize more that ent is a Linux Foundation project

### ISSUE THREAD

**Issue by ohkinozomu** [ent/ent#3250]
I didn't know until recently that ent is a project of The Linux Foundation.
That fact should be more publicized as it will facilitate adoption.
I think it is good to have that indicated in the README or on the website.

**Comment by a8m** [comment]
Hey @ohkinozomu, and thanks for the suggestion 😃 

I announced it both on our blog and the LF blog. I plan to create additional materials for the website and README in the future, but I need to find the time to do so 🤷‍♂️
