### ISSUE TITLE
Interceptor doesn't work for Eager Loading M2M edges

### ISSUE THREAD

**Issue by sisterdong** [ent/ent#3252]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

1. Interceptors are only used in `All()`, `Count()` and `Scan()` query
https://github.com/ent/ent/blob/a85377846f75d58a21129aed9d28fedea7202387/entc/gen/template/builder/query.tmpl#L201-L209

2. All of the above three functions are not being used when generating code of eager loading M2M edges. But `All()` is used in other circumstances (like O2M) and works fine.
https://github.com/ent/ent/blob/a85377846f75d58a21129aed9d28fedea7202387/entc/gen/template/dialect/sql/query.tmpl#L98-L164

## Expected Behavior 🤔

Interceptor also works for Eager Loading M2M edges

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.3  |
| Ent         | v0.11.5   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this, @sisterdong 🙏 
I'll give it a look.
