### ISSUE TITLE
How can I use the `entgo.io/ent/dialect/sql` to build a CASE WHEN selection?

### ISSUE THREAD

**Issue by carlos0202** [ent/ent#3254]
I'm trying to do a custom value selection using [CASE](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-case/) of a field using the `entgo.io/ent/dialect/sql` selector to build a manual query, but couldn't find any documentation available to do it. 

Is is possible right now? If so, how can I do it?

Thanks in advance for the help!

**Comment by a8m** [comment]
Hey @carlos0202 👋 
It looks like this question was answered by Aman: https://gophers.slack.com/archives/C01FMSQDT53/p1674063007090949

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
