### ISSUE TITLE
Support Subqueries in Selector.From()

### ISSUE THREAD

**Issue by agratta-silo** [ent/ent#3261]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Given a custom function `calculate_score`, I'd like to run a query of the form
```
SELECT * 
FROM (SELECT *, calculate_score(users.name, 'searchString') as score FROM users)
WHERE score > 1
ORDER BY score
```

I'm imagining we'd write this in ent as follows
```
s.Select("*").From(
	sql.SelectExpr(sql.Raw(fmt.Sprintf("*, calculate_score(users.name, '%s') AS score", searchString))).
	From(sql.Table("users"))).
Where(sql.ExprP("score > 1")).
OrderBy("score desc")
```

The existing Selector.From method has the signature `func (s *Selector) From(t TableView) *Selector`
The `TableView` parameter can be a `Selector`, `TableSelector`, or `View`.
However, if you attempt to pass in a `Selector` here, the query will panic as the builder attempts to cast it to a `TableSelector`.

## Motivation 🔦
Using a custom SQL function demands that we use a subquery or CTE (at least in Postgres)
I can't currently do this with ent, so I need to write the entire query as raw SQL.
Ideally I could abstract this logic into a custom predicate and do something like
`ent.Users.Query().Where(user.NameFuzzilyMatches(searchString)).All(ctx)`

**Comment by crossworth** [comment]
Hi @agratta-silo , if you don't need the score, you can handle it quit easily, like the example below:

```go
ScoreGT := func(searchString string, val int) func(s *sql.Selector) {
	return func(s *sql.Selector) {
		f := sql.P()
		f.WriteString("calculate_score")
		f.Wrap(func(b *sql.Builder) {
			b.WriteString(s.C(user.FieldName))
			b.Comma()
			b.WriteString("'" + searchString + "'")
		})
		s.Where(sql.GT(f.String(), val))
	}
}
users := client.Debug().User.Query().Where(ScoreGT("input", 1)).AllX(ctx)
```

See that I avoid the subquery, but lost the result of the function, if you need the result you can use the [Custom SQL Modifiers feature flag](https://entgo.io/docs/feature-flags/#custom-sql-modifiers).

In that case you can use something like this:

```go
searchString := "input"
val := 1
var result []struct {
	ent.User
	Score int
}
err = client.Debug().User.Query().Modify(func(s *sql.Selector) {
	f := sql.P()
	f.WriteString("calculate_score")
	f.WriteString("calculate_score")
	f.Wrap(func(b *sql.Builder) {
		b.WriteString(s.C(user.FieldName)).Comma().WriteString("'" + searchString + "'")
	})
	s.AppendSelectExprAs(sql.Raw(f.String()), "score")
	s.Where(sql.GT(f.String(), val))
	s.OrderBy(sql.Asc(f.String()))
}).Scan(ctx, &result)
```

Again, we don't use a subquery here, Postgres should optimize the function calls most of the time (for more information see: [Postgres Function Volatility](https://www.postgresql.org/docs/current/xfunc-volatility.html)), in my examples I used a `calculate_score` that can return different results given the same input.

If you really want to use subqueries, we can implement using it as well:

```go
searchString := "input"
val := 1
var result []struct {
	ent.User
	Score int
}
err = client.Debug().User.Query().Modify(func(s *sql.Selector) {
	f := sql.P()
	f.WriteString("calculate_score")
	f.Wrap(func(b *sql.Builder) {
		b.WriteString(s.C(user.FieldName)).Comma().WriteString("'" + searchString + "'")
	})
	u := sql.Table(user.Table)
	subquery := sql.Select("*").AppendSelectExprAs(sql.Raw(f.String()), "score").From(u).As("user_with_score")

	s.Select("*").From(subquery)
	s.Where(sql.GT(subquery.C("score"), val))
	s.OrderBy(sql.Asc(subquery.C("score")))
}).Scan(ctx, &result)
```

This generates the following SQL: 
```text
query=SELECT * FROM (SELECT *, (calculate_score("users"."name", 'input')) AS "score" FROM "users") AS "user_with_score" WHERE "user_with_score"."score" > $1 ORDER BY "user_with_score"."score" ASC args=[1]
```

On all the examples above, I used `calculate_score` as defined below:
```sql
create or replace function calculate_score(name varchar, searchString varchar)
    returns int
    language plpgsql STABLE
as
$$
declare
begin
    return floor(random() * 10 + 1)::int;
end;
$$
```

I'm pretty sure we can use a `JOIN` and `CTE` to solve this problem as well, but I don't think it will make the code simpler.

**Comment by a8m** [comment]
Fixed with https://github.com/ent/ent/pull/3274. Thanks for reporting this, @agratta-silo.
