### ISSUE TITLE
Import Cycles and Examples

### ISSUE THREAD

**Issue by sanketplus** [ent/ent#3263]
Using the examples have resulted in two different instances of import cycles and has been troublesome to debug. 

What is happening?
- The `ent` package is depending on `ent/schema`. Which is not supposed to happen? (source: a comment from @a8m on Discord, this was very important and very hidden discovery)
- This caused circular import issues when enabling privacy framework (there may be other features/use-cases which may trigger this)

What are those examples?
1. Custom GoTypes as field. If the type is defined in schema file, there's an `ent->ent/schema` dependency
2. PULID: the package in example is created under `ent/schema/pulid` causing same import dependency

What can be done?
- Not having explored much of internals of the framework itself, I can only think of documentation updates as of now.

I will try raising at least a doc change PR over the weekend. Happy to hear thoughts :)

**Comment by a8m** [comment]
Thanks for the suggestion, @sanketplus. Please, see https://github.com/ent/ent/pull/3266 and feel free to add to the docs additional information that you think can help here.
