### ISSUE TITLE
[Question] Additional Struct Fields and scan values

### ISSUE THREAD

**Issue by sahmadreza** [ent/ent#3264]
I add `TotalLikes` field to `post` type with [Additional Struct Fields](https://entgo.io/docs/schema-fields#additional-struct-fields) template

```go
{{ define "model/fields/additional" }}
	{{- if eq $.Name "Post" }}
        // TotalLikes defined by template.
        TotalLikes int `json:"totalLikes,omitempty" gqlgen:"totalLikes"`
    {{- end }}
{{ end }}
```

And I update the Post type in the GraphQL schema
```graphql
extend type Post {
	totalLikes: Int!
}
```

`TotalLikes` field is not stored in the database but I added it with [custom SQL Modifiers](https://entgo.io/docs/feature-flags/#custom-sql-modifiers) in query like that

```go
client.Post.Query().
		Modify(func(s *sql.Selector) {
			t := sql.Table(likes.Table)

			s.LeftJoin(t).
				On(
					s.C(post.FieldID),
					t.C(likes.FieldPostID),
				).
				AppendSelect(
					sql.As(sql.Count(t.C(likes.FieldUserID)), "total_likes"),
				).
				GroupBy(s.C(post.FieldID))
		}).All(ctx)

```

But when I use this query in GraphQL, the following error is displayed:

```
unexpected column \"total_likes\" for type Post
```

How can I add the `TotalLikes` custom field in `Post` type scan values?

**Comment by a8m** [comment]
Hey @sahmadreza 👋 
First, if you need to get the `totalCount` of entities, you can get it without any additional code using our [Relay Connection integration](https://entgo.io/docs/tutorial-todo-gql-paginate). There's an example here: https://github.com/ent/contrib/tree/master/entgql/internal/todo.

If you still need to extend the GraphQL schema with additional fields, you can create another schema file (non-generated) and use the `extend` keyword to extend objects. Then, gqlgen will generate resolvers for these extra fields. Check our this example: https://github.com/ent/contrib/blob/master/entgql/internal/todo/todo.graphql#L13

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
