### ISSUE TITLE
nil panic on `<>.ctx.Fields` in 0.11.6

### ISSUE THREAD

**Issue by edulop91** [ent/ent#3265]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1. I upgraded from 0.11.5 -> 0.11.6 and reran the code generation.
2. Sarted getting `nil` pointer derefs in my unit tests.
3. Chased one down to https://github.com/ent/ent/commit/ef0427550fcb4a0c725672e29bf4bf004a8169a0#diff-03f26b72c6015596e5f7b8c1b27e582d515c00e674670af481f887dd5fb785e5R443 with the debugger. `foo.ctx` is `nil` here!

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.?  |
| Ent         | 0.11.6   |
| Database    | Postgres   |
| Driver      | pgx       |

**Comment by giautm** [comment]
Please upgrade to latest entgql, this issue was fixed in latest commit

**Comment by edulop91** [comment]
worked, thank you!

**Comment by asonawalla** [comment]
👋 hey folks, we ran into this as well yesterday after our most recent dependency upgrade since `go get -u` pulls in v0.3.4 by default.  If you have a moment, would you mind tagging a new release?  Thanks!

**Comment by a8m** [comment]
Done. Thanks for the reminder, @edulop91 🙏
