### ISSUE TITLE
Ent selects `id` when it does not exists in the schema

### ISSUE THREAD

**Issue by gmhafiz** [ent/ent#3267]
Ent assumes each schema has an `id ` column even when it does not exist either in the schema or database.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

/ent/schema/league_certificate_type.go
```go
func (LeagueCertificateType) Fields() []ent.Field {
	return []ent.Field{
		field.Uint64("league_id"),
		field.Uint64("certificate_type_id"),
	}
}
```

bug_test.go
```go
wlc, err := client.Debug().LeagueCertificateType.Query().All(ctx)
assert.Equal(t, err, nil)
t.Log(wlc)
```

`Debug()` shows that it selects non-existent `id`

```
=== RUN   TestBugMySQL/56
2023/01/23 09:09:09 driver.Query: query=SELECT DISTINCT `league_certificate_type`.`id`, `league_certificate_type`.`league_id`, `league_certificate_type`.`certificate_type_id` FROM `league_certificate_type` args=[]
```

## Expected Behavior 🤔

Ent should not select id column

```
SELECT DISTINCT `league_certificate_type`.`league_id`, `league_certificate_type`.`certificate_type_id` FROM `league_certificate_type`
```

## Steps to Reproduce 🕹

```sh
git clone https://github.com/gmhafiz/m2m
cd m2m
docker-compose up -d
go test -v bug_test.go
```

## Your Environment 🌎

| Tech     | Version                                                                                  |
|----------|------------------------------------------------------------------------------------------|
| Go       | 1.19.5                                                                                   |
| Ent      | 0.11.6                                                                                   |
| Database | MySQL , Postgres , sqlite                                                                |
| Driver   | https://github.com/go-sql-driver/mysql , github.com/lib/pq , github.com/mattn/go-sqlite3 |

**Comment by a8m** [comment]
Hey @gmhafiz 👋 
I actually tested it, and it works as expected. All schemas have an `id` field defined except for _edge schemas_ with the `field.ID` annotation. Please, see a full example here: https://entgo.io/docs/schema-edges#user-likes-example (the `Like` schema).

Closing, but please reopen or ping me on our Discord if you found anything else with it.

**Comment by gmhafiz** [comment]
Copy-pasting from discord:

regarding https://github.com/ent/ent/issues/3267#event-8355330972, I think you misunderstood the issue. We already have a database made using migrations in laravel. I define ent schema without an ID because the original table does not have one.  However the ent query tries to select id which is not present in the table. 
original sql schema:

```sql
create table league_certificate_type
(
    league_id           bigint unsigned not null,
    certificate_type_id int unsigned    not null,
    -- <redacted> composite key
    -- <redacted> FKs
);
```

ent schema 
```go
func (LeagueCertificateType) Fields() []ent.Field {
    return []ent.Field{
        field.Uint64("league_id"),
        field.Uint32("certificate_type_id"),
    }
}
```

ent query
`result, err := client.Debug().LeagueCertificateType.Query().All(ctx)`

generates sql query with non-existent id
```sql
SELECT DISTINCT `league_certificate_type`.`id`, `league_certificate_type`.`league_id`, `league_certificate_type`.`certificate_type_id` FROM `league_certificate_type
                                           ^
                                           |
                             should not select this
```

I am not trying to do a `Through`, I just want to make a simple `select *`. The `All(ctx)` will always return an error because the table does not have an id column.

**Comment by Mickls** [comment]
If you don't want to use ent's auto-generated ID, you can use the WithoutFields method in the ent.Schema function to exclude the "id" field and manually specify a different field as the primary key.
For example:
```golang
func (MyTable) Schema() ent.Schema {
    return table.Schema(
        field.WithoutFields(ent.FieldInt("id")),
        field.Int("my_table_id").
            StructTag(`json:"id"`).
            Positive(),
        ...
    )
}
```

**Comment by gmhafiz** [comment]
@a8m To make this issue clearer, I have created a new repo containing only the relevant stuffs

https://github.com/gmhafiz/not_ID/blob/master/bug.md

**Comment by gmhafiz** [comment]
thanks @a8m. resolved using https://github.com/gmhafiz/not_ID/commit/4865320a83ee6c2402ca5f03eb3cffefe21c4b25
