### ISSUE TITLE
v0.11.6 Checksum Mismatch

### ISSUE THREAD

**Issue by joshrendek** [ent/ent#3272]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

It looks like someone pushed and changed the hashes for v0.11.6:

entgo.io/ent@v0.11.6/go.mod: verifying module: checksum mismatch
	downloaded: h1:ericBi6Q8l3wBH1wEIDfKxw7rcQEuRPyBfbIzjtxJ18=
	sum.golang.org: h1:d4yUWiwY3NQtjGvINzAhUyypopfeEKOxcxLN7D5yM7o=

## Expected Behavior 🤔

Checksum should match

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.5 |
| Ent         | 0.11.6  |

**Comment by a8m** [comment]
Thanks for reporting this, @joshrendek. That was me, but I thought it was OK since I tested it right after.

Anyway, I pushed a new tag (with additional bug fixes) and you can install v0.11.7 instead.
