### ISSUE TITLE
internal error: package "context" without types was imported from "entgo.io/ent"

### ISSUE THREAD

**Issue by OldSmokeGun** [ent/ent#3292]
## Current Behavior 😯

Upgrade golang to 1.20

## Expected Behavior 🤔

Run go generate success

## Steps to Reproduce 🕹

1. Upgrade golang to 1.20
2. Run go:generate ent generate ./ent/schema

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.120  |
| Ent         | 0.11.7   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by giautm** [comment]
Hello, can you provide a runnable reproduce to easy testing? You can use https://github.com/ent/bug to setup.

**Comment by OldSmokeGun** [comment]
I solve the problem with "go generate" instead "ent generate"
