### ISSUE TITLE
Hooks After DB Insert

### ISSUE THREAD

**Issue by dudu78** [ent/ent#3307]
Hello,

I tried different types of hooks according to the doc : https://entgo.io/docs/hooks
but on the client.Create, I am unable to get IDs because it seems hooks are only called before the operation in the Database.
Is there a way to call a hook after the Creations in the database ?

Thank's for your reply !

**Comment by a8m** [comment]
Hey @dudu78 👋 
A hook is like middleware. You can execute code before and after the database operation. For example:

```go
hook.On(
	func(next ent.Mutator) ent.Mutator {
		return hook.UserFunc(func(ctx context.Context, m *ent.UserMutation) (ent.Value, error) {
			// Code before the statement execution.
			usr, err := next.Mutate(ctx, m)
			if err != nil {
				return nil, err
			}
			// Code after database execution.
			return usr, nil
		})
	},
	// Execute this hook only on user creation.
	ent.OpCreate,
)
```

> I am unable to get IDs because it seems hooks are only called before the operation in the Database.

Do you have an example?

**Comment by dudu78** [comment]
Thanks ! I will try this it should work ;)
for now I'm just trying to print the IDs

**Comment by a8m** [comment]
Great, closing then.

Please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
