### ISSUE TITLE
How to set col size? 

### ISSUE THREAD

**Issue by it512** [ent/ent#3312]
func (XAIDPk) Fields() []ent.Field {
|   return []ent.Field{
|   |   ID("id"),
|   }

}

func ID(colname string) XAIDField {
|   return field.String(colname).
|   |   MaxLen(xaid.Length).       // < -------------------- MaxLen is 27
|   |   SchemaType(map[string]string{
|   |   |   dialect.Postgres: "char",
|   |   |   dialect.MySQL:    "char",
|   |   }).
|   |   GoType(xaid.Nil).
|   |   Annotations(
|   |   |   entsql.Annotation{Size: 27},  //.  <----------------- I want to set col size ( char (27))
|   |   )
}

rum migrate

                                                      Table "public.orders"
   Column    |           Type           | Collation | Nullable |   Default   | Storage  | Compression | Stats target | Description 
-------------+--------------------------+-----------+----------+-------------+----------+-------------+--------------+-------------
 id          | character(1)             |           | not null |             | extended |             |              | 
 ^^^^^^^^^^^^^^^^^^^^

col id size is 1 ? why ? 

How to set col size ?

Thank you !

**Comment by a8m** [comment]
Hey @it512 👋 
The default size for `char` is 1. i.e.,`char(1)`. If you already use `SchemaType`, you can pass the size there as well: `char(27)`.


Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
