### ISSUE TITLE
pulid noder query error

### ISSUE THREAD

**Issue by haoval** [ent/ent#3317]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```graphql
query {
	node(id: "AA01GS8DGEWS5B5CMFB04Q5A3R2R") {
		... on User {
			name
		}
	}
}
```

## Error Occurred 🤔

```json
{
  "errors": [
    {
      "message": "pulid: expected a string",
      "path": [
        "node"
      ]
    }
  ],
  "data": {
    "node": null
  }
}
```

## My Temp Solution 🕹

```diff go
// https://github.com/ent/contrib/blob/master/entgql/internal/todopulid/ent/schema/pulid/pulid.go

func (u *ID) Scan(src interface{}) error {
	if src == nil {
		return fmt.Errorf("pulid: expected a value")
	}
	s, ok := src.(string)
	if !ok {
+		if id, exist := src.(ID); exist {
+			*u = id
+			return nil
+		}
		return fmt.Errorf("pulid: expected a string")
	}
	*u = ID(s)
	return nil
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.3  |
| Ent         | 0.11.8   |
| Database    | - |
| Driver      |  - |

**Comment by giautm** [comment]
@haoval: Thank you for reporting the issue. We updated the example to be comparable with the latest ent version. Thank so much!
