### ISSUE TITLE
When Aggregating a field of type time.Time with GroupBy, is it possible to Aggregate it with Year and Month?

### ISSUE THREAD

**Issue by chokoGtr** [ent/ent#3318]
When Aggregating a field of type time.Time with GroupBy, is it possible to Aggregate it with Year and Month?

For example, assuming the ent schema is named "Task" and the execution date and time field is "ExecutedAt":
```go
records, err := client.Task.Query().
        GroupBy(task.ExecutedAt).
        All(context.Background())
```

I would like to do the following like the [MySQL date and time functions](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_month), but
```go
records, err := client.Task.Query().
        GroupBy(task.ExecutedAt.Year(), task.ExecutedAt.Month()).
        All(context.Background())
```
Since only a string can be specified, an invalid field error occurs.

Is there a better way?

**Comment by a8m** [comment]
Hey @chokoGtr 👋 
You can do it with a custom aggregation function: https://entgo.io/docs/aggregate#aggregation

```go
var v []struct {
	Month int `sql:"month"`
}
client.Task.Query().
	Aggregate(func(s *sql.Selector) string {
		const by = "MONTH(executed_at)"
		s.GroupBy(by)
		return sql.As(by, "month")
	}).
	// Add another aggregation if needed.
	ScanX(ctx, &v)
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
