### ISSUE TITLE
how to generate id field into gql mutation input

### ISSUE THREAD

**Issue by tsingsun** [ent/ent#3328]
Currently, in entgql mutation input, the primary key field  is ignored. what can I add the id field and set it nullable?

i expect id value can be passed on mutation. or auto generate by default function.
 ```
....
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").
			Default("Anonymous"),
	}
}
...
```
expect 
```
type CreateUserInput {
  id: ID
  name: String!
}
input UpdateUserInput {
  id: ID!
  name: String!
}
type Mutation{
  createUser(input: CreateUserInput!)
 updateUser(input: UpdateUserInput!)
}
```

**Comment by tsingsun** [comment]
on doc [Mutation Inputs](https://entgo.io/docs/tutorial-todo-gql-mutation-input)

The idea is to insert the data into the associated table and then update it. If I can determine the ID beforehand, then I can just use the Insert methoda and reduce sql execution

**Comment by a8m** [comment]
Hey @tsingsun 👋 
You can extend the generated mutation input types with your fields as follows: 

```graphql
extend input CreateTodoInput {
  id: ID
}
```

See this example: https://github.com/ent/contrib/blob/master/entgql/internal/todo/todo.graphql#L36-L38

**Comment by tsingsun** [comment]
thx ,it is a way. but i must resolve id myself because go struct "CreateTodoInput" has not id field.
SoI try to override gql_mutation_input.tmpl,generate code like:
```
type CreateUserInput struct {
   ID: *int
   Name: string
}
```
Will you consider adding an option to add the id field to the mutation input struct and ent.graphql?

**Comment by amphiphile** [comment]
Hi @tsingsun ! How did you manage to add the ID field to CreateInput?
I'm struggling to set primary key from input. Cannot figure out the right approach.
