### ISSUE TITLE
[feature request] support sqlite3 with non-cgo driver

### ISSUE THREAD

**Issue by kmahyyg** [ent/ent#3332]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

To keep golang program "compile once, run everywhere", I would like to deprecate cgo. But current supported driver for sqlite, is: https://github.com/mattn/go-sqlite3 , There's a better driver without cgo: https://modernc.org/sqlite , driver name changed from `sqlite3` to `sqlite`.

## Motivation 🔦

> compile once, run everywhere

**Comment by kmahyyg** [comment]
Also the `mattn/go-sqlite3` itself cannot be compiled with clang compiler which is shipped by default in MacOS. Also, when you try to download requested legacy version of GCC, brew will tell you unsupported on ARM system. So Let's deprecate fxxking CGO.

**Comment by mutsuki333** [comment]
I thought about the same thing and succeed with this:

```go
package main

import (
	"database/sql"
	"database/sql/driver"

	"modernc.org/sqlite"
)

type sqlite3Driver struct {
	*sqlite.Driver
}

type sqlite3DriverConn interface {
	Exec(string, []driver.Value) (driver.Result, error)
}

func (d sqlite3Driver) Open(name string) (conn driver.Conn, err error) {
	conn, err = d.Driver.Open(name)
	if err != nil {
		return
	}
	_, err = conn.(sqlite3DriverConn).Exec("PRAGMA foreign_keys = ON;", nil)
	if err != nil {
		_ = conn.Close()
	}
	return
}

func init() {
	sql.Register("sqlite3", sqlite3Driver{Driver: &sqlite.Driver{}})
}
```

Also hope that ent would support adding custom drivers/dialects someday!!

**Comment by kmahyyg** [comment]
@mutsuki333 so all I need to do is just register a driver to name `sqlite3` and override the default `mattn` one? Am I correct?

**Comment by a8m** [comment]
Yes. Please, see also https://github.com/ent/ent/issues/2460#issuecomment-1095210972 and https://github.com/ent/ent/discussions/1667#discussioncomment-1132296.

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by kmahyyg** [comment]
> Yes. Please, see also [#2460 (comment)](https://github.com/ent/ent/issues/2460#issuecomment-1095210972) and [#1667 (comment)](https://github.com/ent/ent/discussions/1667#discussioncomment-1132296).
> 
> Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

In fact, there's a more important problem that `mattn` one cannot successfully compiled on my M1 Macbook.
