### ISSUE TITLE
How does ent  support multiple database connections in a project ?

### ISSUE THREAD

**Issue by minicloudsky** [ent/ent#3333]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
I have two ent entity which in different mysql instance, so  i had created two different data sources, the problem is how can i specify the data sources for two different entities.
for example:

entity `User` in my mysql instanceA, mapping to `biz`.`user` table.
entity `Car` in my mysql instanceB, mapping to `biz2`.`car` table.
User  and Car doesn't have any Edge relations，they are independent business used in my project.

how can i specify the table position in a specific mysql instance when ent creating schemas, for instance,to specify entity `User` mapping table generate at  mysql instanceA's `biz`.`user` table

I had Googled and found [schema -config](https://entgo.io/docs/feature-flags/#schema-config),however, it seems not for my case,How can i solve this problem or any interfaces ent has satisfied my case ? thanks in advance ~

**Comment by a8m** [comment]
Hey @minicloudsky, and thanks for raising this issue. 
Currently, Ent does not provide an out-of-the-box solution for querying or mutating multiple databases on the same `ent.Client`. However, a custom driver can be implemented for this use case only if no edges or graph traversals cross the database boundaries. 

Would you mind elaborating more on the use case? e.g., why do these entities reside on the same Ent schema? Is it a client-side sharing logic? Do you have any relations or traversals that involve the two databases? If they reside on separate graphs, why not store them in separate Ent schemas? How do you manage schema migrations for this schema, etc.? 

Thanks, and sorry for all these questions. I'd like to make sure it's feasible before I propose my help with a solution.

**Comment by minicloudsky** [comment]
> Hey @minicloudsky, and thanks for raising this issue. Currently, Ent does not provide an out-of-the-box solution for querying or mutating multiple databases on the same `ent.Client`. However, a custom driver can be implemented for this use case only if no edges or graph traversals cross the database boundaries.
> 
> Would you mind elaborating more on the use case? e.g., why do these entities reside on the same Ent schema? Is it a client-side sharing logic? Do you have any relations or traversals that involve the two databases? If they reside on separate graphs, why not store them in separate Ent schemas? How do you manage schema migrations for this schema, etc.?
> 
> Thanks, and sorry for all these questions. I'd like to make sure it's feasible before I propose my help with a solution.

thanks for reply~
In my case, I mutating multiple databases  on the different ent.Client, so I created two different clients.
clientA , for User entity, uses mysql instanceA in database A
clientB ,for Car entity, uses mysql instanceB  in database B

In my project, because all my entity in the same  Directory(project_root/ent), User and Car entity defined in `project_root/ent/schema/`

my problem is, when I run `clientA.Schema.Create()` and `clientB.Schema.Create()`, how can i ensure `clientA only creates User entity in mysql instanceA's database A` and `clientB only creates Car entity in mysql instanceB's database B` ,this is my problem, how can i slove it，thanks ~

**Comment by minicloudsky** [comment]
> > Hey @minicloudsky, and thanks for raising this issue. Currently, Ent does not provide an out-of-the-box solution for querying or mutating multiple databases on the same `ent.Client`. However, a custom driver can be implemented for this use case only if no edges or graph traversals cross the database boundaries.
> > Would you mind elaborating more on the use case? e.g., why do these entities reside on the same Ent schema? Is it a client-side sharing logic? Do you have any relations or traversals that involve the two databases? If they reside on separate graphs, why not store them in separate Ent schemas? How do you manage schema migrations for this schema, etc.?
> > Thanks, and sorry for all these questions. I'd like to make sure it's feasible before I propose my help with a solution.
> 
> thanks for reply~ In my case, I mutating multiple databases on the different ent.Client, so I created two different clients. clientA , for User entity, uses mysql instanceA in database A clientB ,for Car entity, uses mysql instanceB in database B
> 
> In my project, because all my entity in the same Directory(project_root/ent), User and Car entity defined in `project_root/ent/schema/`
> 
> my problem is, when I run `clientA.Schema.Create()` and `clientB.Schema.Create()`, how can i ensure `clientA only creates User entity in mysql instanceA's database A` and `clientB only creates Car entity in mysql instanceB's database B` ,this is my problem, how can i slove it，thanks ~

@a8m how can i solve the above problem, I would appreciate if any reply，thanks for updating~

**Comment by lishuangquan1987** [comment]
@minicloudsky do you solve your problem? I have the sampe problem.

**Comment by SKKUGoon** [comment]
For my case I separated the directory and created 2 ent client. So for your case, I would have `<project>/ent/A` and `<project>/ent/B`, each containing separate *ent.Client. Then I created a generic wrapper function that takes `client` variable that can be boat clientA or clientB at times. You can pass clientA or clientB on demand - which would ensure clientA accessing only database A, and clientB accessing only database B
