### ISSUE TITLE
Non-deterministic code generation for named imports

### ISSUE THREAD

**Issue by migmartri** [ent/ent#3340]
Hi!

Generating code that contains named imports in the schema (i.e for custom Go-types in the schema) causes a non-deterministic code generation.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

There is possibly a duplicated but it's no longer open https://github.com/ent/ent/issues/3208

## Current Behavior 😯

See below an example where the import order gets changed (arbitrarily) after running `go generate ./...` 
 
```diff
diff --git a/ent/user.go b/ent/user.go
index aedb17f..2345b5a 100644
--- a/ent/user.go
+++ b/ent/user.go
@@ -7,9 +7,8 @@ import (
        "strings"

        "entgo.io/ent/dialect/sql"
-       "github.com/migmartri/ent-gen-troubleshoot-example/ent/user"
-
        v1 "github.com/migmartri/ent-gen-troubleshoot-example/api/v1"
+       "github.com/migmartri/ent-gen-troubleshoot-example/ent/user"
 )
```
Consecutive runs might cause different changes in this or other generated files that rely on named imports.

## Expected Behavior 🤔

Deterministic code generation

## Steps to Reproduce 🕹

I've created a repository https://github.com/migmartri/ent-gen-troubleshoot-example where you can reproduce the issue.  

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.1  |
| Ent         | v0.11.8 |

**Comment by a8m** [comment]
Thanks for reporting this, @migmartri.

The issue should be resolved with https://github.com/ent/ent/pull/3344. I cloned your repository and checked this as follows:
```shell
repeat 50 { go generate ./... && git --no-pager diff }
```

Once PR is merged, you can `go get entgo.io/ent@master` to update your project 🙏

**Comment by migmartri** [comment]
I can confirm that this fixes my issue! 

Thanks a lot for the quick action!
