### ISSUE TITLE
Is there a way to configure multischema versioned migrations with atlas?

### ISSUE THREAD

**Issue by wheissd** [ent/ent#3343]
Hi!

Recently, I searched ent docs, atlas docs, issues, google and haven't found anything relevant except this automigration example https://github.com/ent/ent/blob/d01a4111c6479a57e9ff668b00cb8382bf4e76c9/entc/integration/multischema/multischema_test.go

and this, but it seems incompatible while using atlas with ent https://atlasgo.io/atlas-schema/sql-resources/#schema

**Comment by htwatanabe** [comment]
Hello.

I faced a similar problem and found one solution.

However, as far as I can find, this method is not mentioned in the official documentation and I am not sure if the developers here expect to operate this way or not.
To clarify this, I would like to ask the developers for their opinion on this matter.

The solution is as follows.
Create a new schema directory using the `--target` option, such as `ent new --target entv1/schema User Group`.
Then, under the `entv1/` directory, manage the auto-generated code of ent and the migration files created by atlas as a separate package. That way, if we add `./entv1/generate.go` file, `go generate ./entv1` command can be executed.
After that, we can also use the atlas command by replacing the file path as follows
```
atlas migrate diff migration_name \
  --dir "file://entv1/migrate/migrations" \
  --to "ent://entv1/schema" \
  --dev-url "docker://mysql/8/ent"
```

Also, at least in the `entgo.io/ent v0.12.3` environment, we can see `ent new` help as follows, which leads me to believe that there are multiple schemes coexisting in one environment (like v1, v2) in this example.
```
initialize a new environment with zero or more schemas

Usage:
  ent new [flags] [schemas]

Examples:
  ent new Example
  ent new --target entv1/schema User Group
  ent new --template ./path/to/file.tmpl User

Flags:
  -h, --help              help for new
      --target string     target directory for schemas (default "ent/schema")
      --template string   template to use for new schemas
```

**Comment by a8m** [comment]
Hey! This feature has been added to Atlas: https://entgo.io/docs/multischema-migrations.

Closing this issue, as Atlas natively supports Ent schemas using the `ent://` scheme.
