### ISSUE TITLE
How do I get fields added through mixin

### ISSUE THREAD

**Issue by lky1937** [ent/ent#3348]
Hi All, I use the built-in mixin.Time, but I don't know how to select the create_time field 
```go
func (Instance) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixin.Time{},
	}
}
```

**Comment by a8m** [comment]
Hey @lky1937 👋🏻
All fields are selected by default. If you want to select specific fields, see: https://entgo.io/docs/crud#field-selection

**Comment by lky1937** [comment]
> Hey @lky1937 👋🏻 All fields are selected by default. If you want to select specific fields, see: https://entgo.io/docs/crud#field-selection

Thank you. That's very helpful
