### ISSUE TITLE
how to get null from mysql data

### ISSUE THREAD

**Issue by dengao123** [ent/ent#3352]

**Comment by godcong** [comment]
Field set with `nullable`, you can get the null value with client get.

**Comment by a8m** [comment]
As @godcong commented. You can define fields as [Nillable](https://entgo.io/docs/schema-fields/#nillable).

Thanks for supporting for the help, @godcong 🙏

**Comment by a8m** [comment]
@dengao123, check out the docs and feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by dengao123** [comment]
@a8m tks，I've set nillable for the column which have null value。but whent i use API like this
`clinet.User.Query().Where(entUser.ID(id)).First(ctx)` the null column return nil。and after marshal the column will miss.
This is not what I expected。What I want is that the data returned to the front contains this field and the value is null.

**Comment by dengao123** [comment]
tks，i get it
