### ISSUE TITLE
Is DeleteOne with condition missing?

### ISSUE THREAD

**Issue by hbagdi** [ent/ent#3357]
I'm using ent 0.11.4 and I don't see Where() is possible on DeleteOneID: https://entgo.io/docs/crud/#delete-one-with-condition. Is that a bug?

I tried to look around if the user has to opt-in for this feature but I didn't find anything in the documentation.

**Comment by a8m** [comment]
Hey @hbagdi 👋🏻
This option was added a few weeks ago. See: https://github.com/ent/ent/pull/3271

Please update your ent version and run codegen to get it working:
```
go get entgo.io/ent@master
```

**Comment by a8m** [comment]
Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
