### ISSUE TITLE
creating seeds file the output result  is unexpected

### ISSUE THREAD

**Issue by yuta-hidaka** [ent/ent#3362]
I'm creating a migration seed file.

And the DDL is not the expected format.

I'm create this seed code.
```
// SeedUsers add the initial users to the database.
func SeedUsers(dir *migrate.LocalDir) error {
	w := &schema.DirWriter{Dir: dir}
	client := ent.NewClient(ent.Driver(schema.NewWriteDriver(dialect.MySQL, w)))

	client.User.CreateBulk(
		client.User.Create().SetID(ulid.MustNew("")).SetEmail("hohoho").SetCreatedAt(time.Now()).SetType(user.TypePartner),
	).Exec(context.Background())

	return w.FlushChange(
		"seed_partner_users",
		"Add the initial partner users to the database.",
	)
}
```

And run in main.go
```
package main

import (
	"my-api/internal/pkg/ent/migratedata"

	atlas "ariga.io/atlas/sql/migrate"
)

func main() {
	dir, _ := atlas.NewLocalDir("ent/migrate/migrations")
	migratedata.SeedUsers(dir)
}

```

Then DDL is this.
```
-- Add the initial partner users to the database.
INSERT INTO `users` (`created_at`, `email`, `id`, `type`, `updated_at`) VALUES ({{ TIME_VALUE }}, 'hohoho', {{ VALUE }}, {{ VALUE }}, {{ TIME_VALUE }});
```

The DDL should replace all of the template data such as {{ TIME_VALUE }}, {{ TIME_VALUE }}.

**Comment by a8m** [comment]
Thanks for reporting this, @yuta-hidaka. `ulid` was not handled by the `WriteDriver`, but I added support for `fmt.Stringer` in https://github.com/ent/ent/pull/3366. However, for `{{ TIME_VALUE }}`, this is really driver-specific, and you should replace these placeholders with the necessary values (e.g., `= NOW()`).

**Comment by qindj** [comment]
@a8m 

Are there any suggestions to auto replace these placeholders such as {{TIME_VALUE}}?
