### ISSUE TITLE
Please consider releasing version 1.0

### ISSUE THREAD

**Issue by djensen47** [ent/ent#3372]
Hi, just wanted to say, Ent is fantastic! The quality speaks for itself in the shear volume of developers using it in production.

Therefore is super strange, and inconvenient, that ent does not have a 1.0 version.

Looking at the roadmap for v1, which was started 4 years ago, the remaining items look like 1.1 or 2.0 features. We could easily have a 1.0 version today. All you have to do is change that number and send out a release. 😉 The problem with 0.11 is that 0.12 can be a breaking change so we all have to be super, extra careful when upgrading even if all we want is that small bug fix. 

Please consider moving to 1.0 soon and using semver for future releases.

**Comment by a8m** [comment]
Hey @djensen47 👋 
Thanks for the kind words and for suggesting this. I actually 100% agree with this, especially because Ent has kept backward compatibility since the day it was released. 

@rotemtam, @giautm, @masseelch, and I will prepare a release in the upcoming weeks and do it.

**Comment by djensen47** [comment]
That's great news! Thank you.
