### ISSUE TITLE
entgql: Duplicate import present in `gql_where_input.go`

### ISSUE THREAD

**Issue by Adam-Mustafa** [ent/ent#3373]
When using entgql, the same import appears on multiple times in the `gql_where_input.go` generated file. 

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using entgql, the same import appears on multiple times in the `gql_where_input.go` generated file. This causes compilations to fail. 

## Expected Behavior 🤔

Each import should only appear once. 

## Steps to Reproduce 🕹

Create a series of schemas that require the same external import. For example, use an enum from another package in multiple fields on different tables. 

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.?  |
| Ent         | master   |
| Entgql    | master + 0.3.5 |

**Comment by a8m** [comment]
Thanks for reporting this and for the contribution, @Adam-Mustafa ❤️. See my comment on the PR: https://github.com/ent/contrib/pull/452/files#r1129643282
