### ISSUE TITLE
I'm finding myself in a similar situation, but with a O2M Edge field.

### ISSUE THREAD

**Issue by ji21** [ent/ent#3381]
I ran "go generate ./ent"  and got this error: set "App" foreign-keys: edge "creator" has a field "creator_id" but it is not holding a foreign key

The Code:

ent/schema/user.go
`
package schema

import (
    "entgo.io/ent"
    "entgo.io/ent/schema/field"
	"entgo.io/ent/schema/edge"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("email").Unique(),
		field.Ints("created_apps_ids"),
	}
}

// Edges of the User.
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("created_apps", App.Type).Field("created_apps_ids"),
	}
}

`

ent/schema/app.go

`
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/edge"
)

// App holds the schema definition for the App entity.
type App struct {
	ent.Schema
}

// Fields of the App.
func (App) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.Int("creator_id"),
	}
}

// Edges of the App.
func (App) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("creator", User.Type).Ref("created_apps").Field("creator_id"),
	}
}
`

This only happened when I set the field on the edge.

_Originally posted by @ji21 in https://github.com/ent/ent/issues/1417#issuecomment-1461384613_

**Comment by a8m** [comment]
Hey @ji21 👋 
Setting the `"creator"` edge to be unique will solve this issue. Please, check out this example: https://github.com/ent/ent/blob/master/entc/integration/edgefield/ent/schema/pet.go

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by ji21** [comment]
Hey @a8m , thanks for the reply. The error went away but a new one came up:

set "User" foreign-keys: edge "created_apps" has a field "created_apps_ids" but it is not holding a foreign key

I think I might be misunderstanding how edges work, how can I fix this? Thanks!
