### ISSUE TITLE
The function "lower" not defined  in entinit template.

### ISSUE THREAD

**Issue by oaktreecode** [ent/ent#3395]
Hi

1. I got the template https://github.com/ent/ent/blob/master/examples/entcpkg/ent/template/entinit.tmpl 
2.  cmd: -> 
` ent init Test --target=./ent/schema --template=./ent/template/entinit.tmpl`
the func "**lower**" in the tmpl
 `// {{ . }} holds the schema definition for the {{ lower . }} entity.`
4. got the error : 
`ent/init: could not parse template template: entinit.tmpl:15: function "lower" not defined
`

Many thanks!

**Comment by oaktreecode** [comment]
Thank you for responding to my message so quickly! , by the way ,   The template will be written in a file named  xxx.go ,  but how can I name it to xxx.graphql?

**Comment by giautm** [comment]
@oaktreecode: what ent version are you using? I think it already add Ent's function in template

**Comment by oaktreecode** [comment]
@giautm  Hi, I am using the 
```
entgo.io/contrib v0.3.5
entgo.io/ent v0.11.10
```
