### ISSUE TITLE
How to use the group by with entgql Paginate?

### ISSUE THREAD

**Issue by oaktreecode** [ent/ent#3404]
I got the Paginate, but I want to use the key "group by".
```
Query().
	Paginate(ctx, after, first, before, last,
		ent.WithCustomerOrder(orderBy),
		ent.WithCustomerFilter(where.Filter),
	)
```

**Comment by a8m** [comment]
Hey @oaktreecode,
Can you please elaborate on what you mean by using group-by in Relay pagination? A GraphQL query example can help
