### ISSUE TITLE
How to solve NULL  columns query?

### ISSUE THREAD

**Issue by yantao1995** [ent/ent#3406]
![image](https://user-images.githubusercontent.com/40712505/227140485-790b5090-a54f-4c4f-bf60-5edf291788ea.png) 

Like the test above.

When the query condition filtering behavior is 0, the aggregated value is NULL, and then what should be done when an SQL error is reported. I want to achieve a return result of 0 and nil.

**Comment by a8m** [comment]
> @yantao1995 what did you do in the end?

You can scan nullable rows to a sql.NullInt64.

**Comment by yantao1995** [comment]
> @yantao1995 what did you do in the end?

Modify(func(s *entsql.Selector) {
			s.Select("IFNULL(SUM(`amount`),0)")
}).
