### ISSUE TITLE
[Feature request] request ncruces/go-sqlite3 support

### ISSUE THREAD

**Issue by ystyle** [ent/ent#3408]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

[ncruces/go-sqlite3](https://github.com/ncruces/go-sqlite3): Go bindings to SQLite using Wazero（wasm runtime）

**Comment by a8m** [comment]
Hey, @ystyle 👋 

I just checked this repository, and it looks like its driver implementation uses the same name as used by Ent. i.e., you should be able to use it instead without any problems. Ent uses `sql.Open` under the hood, which makes drivers independent for it. 

For more info, see: https://github.com/ncruces/go-sqlite3/blob/main/driver/driver.go#L41 and https://pkg.go.dev/github.com/ncruces/go-sqlite3/driver#example-package.


Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
