### ISSUE TITLE
Uint32 fields are translated to integer values on postgres causing an overflow error

### ISSUE THREAD

**Issue by mrg0lden** [ent/ent#3409]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior

I get the following error
unable to encode 0x82c58f98 into binary format for int4 (OID 23): 2193985432 is greater than maximum value for int4

## Expected Behavior

Since Postgres doesn't support unsigned integers, IDK if it's possible to encode them into byte arrays, but then we'll lose the ability to order by numbers I believe 🤔 . So maybe just disallow unsigned integers with Postgres

## Steps to Reproduce 🕹

 

Steps:

1. Create an entity with a field of Uint32 or Uint64
2. Insert a value that overflows Int32 or Int64 but not Uint32 nor Uint64
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.1  |
| Ent         | v0.11.10   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx        |

**Comment by a8m** [comment]
Thanks for raising this issue, @mrg0lden. 

Although PostgreSQL does not support unsigned integers, I believe using this type can still be convenient in some cases to reduce type conversion. If you want to control the database type, you can use the [`SchemaType`](https://entgo.io/docs/schema-fields/#database-type) option - one example is the [`uint` extension](https://github.com/petere/pguint). 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by netixx** [comment]
I had the same issue, I believe that the default postgresql type should be "bigint" for uint32 fields.

I solved it using the following (using @a8m  comment):
```
SchemaType(map[string]string{
  dialect.Postgres: "bigint", // avoid overflows with integer
})
```
