### ISSUE TITLE
CreateBulk doesn't error on unique constraint

### ISSUE THREAD

**Issue by oSethoum** [ent/ent#3412]
CreateBulk doesn't error nor insert data on unique constraint when used with SQLite.
update: 
When using createBulk with custom id function for example: 
```go 
field.String("id").DefaultFunc(xid.New().String)
```
the bulk of data you trying to insert gets the same id. 

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹
reproduction repo [here](https://github.com/oSethoum/ent-constraint-sqlite-bug)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.2  |
| Ent         | 0.11.8   |
| Database    | SQLite |
| Driver      | https://github.com/mattn/go-sqlite3 |

**Comment by a8m** [comment]
Thanks a lot for reporting this, @oSethoum. The issue was fixed with https://github.com/ent/ent/pull/3415.
