### ISSUE TITLE
entproto: failed generating protos: entproto: failed parsing ent graph: proto: message field "entpb.Blog.posts" cannot resolve type: "*.Post" not found

### ISSUE THREAD

**Issue by idc77** [ent/ent#3413]
The generate.go is in /generate.go instead of /ent/generate.go

```go
package main

//go:generate go run -mod=mod ./ent/entc.go
//go:generate go run -mod=mod github.com/99designs/gqlgen
//go:generate go run -mod=mod entgo.io/contrib/entproto/cmd/entproto -path ./ent/schema
```

entc does the graphql stuff.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
go generate ./...
2023/03/26 15:00:02 entproto: failed generating protos: entproto: failed parsing ent graph: proto: message field "entpb.Blog.posts" cannot resolve type: "*.Post" not found
exit status 1
generate.go:5: running "go": exit status 1
```

## Expected Behavior 🤔

No error...

## Steps to Reproduce 🕹

I could probably create a repo and make it public but it would require to invalidate the oidc secrets...
The blog.go and post.go types could probably also be stripped to the bare minimum necessary.
But I think it's obvious what the problem is.

`edge.To("posts", Post.Type).Annotations(entproto.Field(9)),`
why can it not resolve the type "*.Post" and what does that even mean?
Is it because it's 1 level above the ent dir?
Do I need a separate generate.go in ent?

schema/blog.go
```go
package schema

import (
	"code.icod.de/dalu/blogsql/ent/hook"
	"code.icod.de/dalu/blogsql/hooks"
	"entgo.io/contrib/entgql"
	"entgo.io/contrib/entproto"
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"time"
)

// Blog holds the schema definition for the Blog entity.
type Blog struct {
	ent.Schema
}

// Fields of the Blog.
func (Blog) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Annotations(
			entsql.Annotation{Default: "gen_random_uuid()"},
			entproto.Field(1),
		).Unique(),
		field.Time("create_time").Default(time.Now).Immutable().Annotations(entgql.OrderField("CREATE_TIME")).Annotations(entproto.Field(2)),
		field.Time("update_time").Default(time.Now).UpdateDefault(time.Now).Optional().Annotations(entgql.OrderField("UPDATE_TIME")).Annotations(entproto.Field(3)),
		field.Text("title").Annotations(entproto.Field(4)),
		field.Text("slug").MaxLen(1900).Unique().Optional().Annotations(entproto.Field(5)),
		field.Text("description").Optional().Annotations(entproto.Field(6)),
		field.Text("tagline").Optional().Annotations(entproto.Field(7)),
		field.Bool("featured").Default(false).Optional().Annotations(entproto.Field(8)),
	}
}

// Edges of the Blog.
func (Blog) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("posts", Post.Type).Annotations(entproto.Field(9)),
		edge.To("pages", Page.Type).Annotations(entproto.Field(10)),
		edge.To("comments", Comment.Type).Annotations(entproto.Field(11)),
		edge.To("categories", Category.Type).Annotations(entproto.Field(12)),
		edge.To("tags", Tag.Type).Annotations(entproto.Field(13)),
		edge.From("owner", Profile.Type).Ref("owning").Unique().Annotations(entproto.Field(14)),
		edge.From("authors", Profile.Type).Ref("authoring").Annotations(entproto.Field(15)),
		edge.From("subscribers", Profile.Type).Ref("subscribed").Annotations(entproto.Field(16)),
	}
}

func (Blog) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.RelayConnection(),
		entgql.QueryField(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
		entproto.Message(),
	}
}

func (Blog) Hooks() []ent.Hook {
	return []ent.Hook{
		hook.On(hooks.BlogCreateHook, ent.OpCreate),
	}
}
```

```go
package schema

import (
	"code.icod.de/dalu/blogsql/ent/hook"
	"code.icod.de/dalu/blogsql/ent/privacy"
	"code.icod.de/dalu/blogsql/hooks"
	"code.icod.de/dalu/blogsql/rules"
	"entgo.io/contrib/entgql"
	"entgo.io/contrib/entproto"
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"time"
)

// Post holds the schema definition for the Post entity.
type Post struct {
	ent.Schema
}

// Fields of the Post.
func (Post) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).Annotations(
			entsql.Annotation{Default: "gen_random_uuid()"},
			entproto.Field(1),
		).Unique(),
		field.Time("create_time").Default(time.Now).Immutable().Annotations(entgql.OrderField("CREATE_TIME"), entproto.Field(2)),
		field.Time("update_time").Default(time.Now).UpdateDefault(time.Now).Optional().Annotations(entgql.OrderField("UPDATE_TIME"), entproto.Field(3)),
		field.Text("slug").MaxLen(1900).Unique().Annotations(entproto.Field(4)),
		field.Enum("status").Values("published", "draft", "private").Default("draft").Annotations(entgql.OrderField("STATUS"), entproto.Field(5)),
		field.Text("title").Annotations(entgql.OrderField("TITLE"), entproto.Field(6)),
		field.Text("body").Annotations(entproto.Field(7)),
	}
}

// Edges of the Post.
func (Post) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("categories", Category.Type).Annotations(entproto.Field(8)),
		edge.To("tags", Tag.Type).Annotations(entproto.Field(9)),
		edge.To("comments", Comment.Type).Annotations(entproto.Field(10)),
		edge.To("reactions", PostReaction.Type).Annotations(entproto.Field(11)),
		edge.From("blog", Blog.Type).Ref("posts").Unique().Annotations(entproto.Field(12)),
		edge.From("author", Profile.Type).Ref("posts").Unique().Immutable().Annotations(entproto.Field(13)),
	}
}

func (Post) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.RelayConnection(),
		entgql.QueryField(),
		entgql.Mutations(entgql.MutationCreate(), entgql.MutationUpdate()),
		entproto.Message(),
	}
}

// Policy of the Post.
func (Post) Policy() ent.Policy {
	return privacy.Policy{
		Mutation: privacy.MutationPolicy{
			// privacyrules.PrintQueryToken(),
			rules.DenyIfNoToken(),
			rules.PostDenyIfNotOwner(),
			privacy.AlwaysDenyRule(),
		},
		Query: privacy.QueryPolicy{
			// privacyrules.PrintQueryToken(),
			privacy.AlwaysAllowRule(),
		},
	}
}

// Hooks of the Post.
func (Post) Hooks() []ent.Hook {
	return []ent.Hook{
		hook.On(hooks.PostCreateHook, ent.OpCreate),
	}
}
```

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | go version go1.20.2 linux/amd64 |
| Ent         | v0.11.10, contrib v0.3.5   |
| Database    | PG   |
| Driver      | github.com/jackc/pgx/v5 v5.3.1 |

**Comment by whmeitzler** [comment]
I ran into the same problem and would like to do a bit better than  [DenverCoder](https://xkcd.com/979/). 
**Your enum types are under-defined**

You must specify a mapping of enum values to numbers, i.e.
```
field.
	Enum("status").
	Values("published", "draft", "private").
	Default("draft").
	Annotations(
		entgql.OrderField("STATUS"),
		entproto.Field(5),
		entproto.Enum(map[string]int32{
			"draft":0,
			"published":1 ,
		         "private":2,
		})),
	),
```

You also must ensure that the value marked as "default" has the key `0` to conform to Protobuf semantics

I was able to find this out by modifying `entgo.io/contrib@v0.3.5/entproto/adapter.go:110`(ish) as follows:
```
	for _, genType := range a.graph.Nodes {
		messageDescriptor, err := a.toProtoMessageDescriptor(genType)

		// store specific message parse failures
		if err != nil {
			fmt.Println("gen", genType.Name, " ERROR ", err)//EDIT
			a.errors[genType.Name] = err
			continue
		}
		...
```

Once those errors printed, I had enough information to discover and fix my issue. 

```

**Comment by idc77** [comment]
:) Yeah yeah, my life from 2000-now. Let's not get too nostalgic but I remember the time from 1995-2000, where one could actually find information, quality information that solves the problem, without having to dive through heaps of half-truths and, yes, many such posts were found. Also many with "solved it" and no further comment.
In void space no one can hear your scream ;)

On topic:
This does solve it for enums which have a Default(), but doesn't seem to work with enums which don't.
Btw I can only imagine how difficult it was to find this.

```go
		field.Enum("expression").
			Values("up", "down", "smile", "laugh", "cry", "surprised", "confused", "angry").
			Annotations(entgql.OrderField("EXPRESSION"), entproto.Field(2), entproto.Enum(map[string]int32{
				"up":        0,
				"down":      1,
				"smile":     2,
				"laugh":     3,
				"cry":       4,
				"surprised": 5,
				"confused":  6,
				"angry":     7,
			})),
```

https://protobuf.dev/programming-guides/proto3/#enum
Reading the protobuf page about enums and the "style guide", the default value is = 0 even if there is no default.
This means I need to filter if the value is "none" on the client (by prepending a "none":0 and .Default("none")).
I'm not sure if this field can be nil or nullable. I mean that would translate to
```proto
enum Expression {
  UP = 0;
  DOWN = 1;
  //...
}

message Post {
  optional Expression expression = 1;
}
```
if I'm not mistaken.

Only one way to find out.
Nope, you can set it to be .Nillable() but it needs a .Default() value.

What does that mean on the database level?
... I can't say, because there's a new stopper.

```go
		field.Enum("status").Values("published", "draft", "private").Default("draft").
			Annotations(entgql.OrderField("STATUS"), entproto.Field(5), entproto.Enum(map[string]int32{
				"draft":     0,
				"published": 1,
				"private":   2,
			})),
```

results in
```
2023/04/06 22:50:22 entproto: failed generating protos: entproto: failed parsing ent graph: proto: enum "entpb.Post.STATUS_PUBLISHED" using proto3 semantics must have zero number for the first value
exit status 1
generate.go:5: running "go": exit status 1
```

It's very pedantic, the order must be preserved.
Aligning Values order with the map order fixes that, as you have written.

Ok so what does that mean on the databases level?
... another stopper

Since I generate from /generate.go
the resulting generated generate.go in `proto/entpb/generate.go` has this content
```go
package entpb

//go:generate protoc -I=.. --go_out=.. --go-grpc_out=.. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --entgrpc_out=.. --entgrpc_opt=paths=source_relative,schema_path=../../schema entpb/entpb.proto
```
where it should had
```go
package entpb

//go:generate protoc -I=.. --go_out=.. --go-grpc_out=.. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --entgrpc_out=.. --entgrpc_opt=paths=source_relative,schema_path=../../ent/schema entpb/entpb.proto
```
There should be a way to set the absolute root directory of the project or, why not, the absolute path to ent/schema.

I'm afraid if I regenerate after having changed anything, the problem will come up again. I guess it's best to create a generate.go in /ent/generate.go only for the grpc stuff.

On the database level it means:
If a record is inserted the default value is "up", Nillable() has no effect on either the database or the generated .proto file.
I removed Nillable again, deleted the proto dir and it has no effect.
I moved the generate.go for proto into ent/generate.go again, and no error on generation.

I think this can be closed, cheers Will.

**Comment by idc77** [comment]
Another gotcha:
```go
edge.From("author", Profile.Type).Ref("posts").Unique().Annotations(entproto.Field(13)),
```
can't be Immutable() or the post.SetAuthorID() won't be generated.

**Comment by whmeitzler** [comment]
> Reading the protobuf page about enums and the "style guide", the default value is = 0 even if there is no default.
This means I need to filter if the value is "none" on the client (by prepending a "none":0 and .Default("none")).
I'm not sure if this field can be nil or nullable. I mean that would translate to

The default state of enums is one of the more...ragged...edges of `proto3`. In effect, I've found it forcing me to add an UNDEFINED value to each enum definition. IIRC, it's a side effect of the wire format of the enum itself.

>  Btw I can only imagine how difficult it was to find this.
Surprisingly not bad, as long as you're willing to overcome the hurdle of modifying code in ~/go/mod
It's all just Go code after all. Just remember to delete any changed packages and `go get` canonical ones before building for prod :) 

Regarding entproto, I've come to the sad realization that I've put much more time and effort into figuring out how to use entproto to generate 10 or so messages than if I'd just sat down and written the dang proto file by hand[1]. 

My last nags about the generated code is that there is no generated mapping between `ent.Client` generated structs and proto generated, so I still have to manually write adapters between the two, which is by far the task I would most want automated. There is also no path forward to augment the generated services if I want to generate any service semantics other than the fairly basic primitives that the tooling creates. I'm not sure how better developer ergonomics could be defined while still flowing through `protoc` though. These seem to be issues to be dealt with by higher-level DSL concepts such as [Aphrodite](https://aphrodite.sh/)

The future is bright...

[1]  [Automation bit you again? Ah! Well then...](https://xkcd.com/1319/)
