### ISSUE TITLE
how to add metric for operation get

### ISSUE THREAD

**Issue by shuaiyy** [ent/ent#3416]
Hello, I'm following this [blog-building-observable-ent-application-with-prometheus](https://entgo.io/blog/2021/08/12/building-observable-ent-application-with-prometheus/) ,  use `MutateFunc` hook, it works for **OpCreate**, 

but l also want to collect metric for **OpGet** or **OpList**, need some help, thanks.

**Comment by a8m** [comment]
Hey, @shuaiyy 👋 
You can use interceptors for this (see, https://entgo.io/docs/interceptors/), or define a custom `dialect.Driver` as defined here: https://github.com/ent/ent/blob/master/dialect/dialect.go#L67

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by a8m** [comment]
Update your Ent version to the latest: `go get entgo.io/ent@latest`. Then, run the codegen command again.
