### ISSUE TITLE
entproto generation fails for 02M same type edge

### ISSUE THREAD

**Issue by gr8web** [ent/ent#3424]
Not sure if this is a bug(in case I might have missed something)...
I was assuming that this type of edge should be supported, the question is whether I did something wrong or my expectation is wrong.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`go generate ./... ` fails with the error `entproto: failed generating protos: entproto: failed parsing some schemas: entproto: failed extracting proto field number annotation: entproto: edge "parent" does not have an entproto.Field annotation
exit status 1` 

## Expected Behavior 🤔

entproto generation works

## Steps to Reproduce 🕹

Steps:

1. checkout https://github.com/gr8web/ent-contrib/tree/edge-protogen-fail
2. run `go generate ./... `

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20  |
| Ent         | 0.11.10   |
| entgo.io/contrib         | 0.3.5  |

**Comment by kbumsik** [comment]
I also faced the same issue. It throws an error for O2M same type edge in entproto.

As a workaround, I added entproto.Skip for such edges.

**Comment by rotemtam** [comment]
Hey @kbumsik  and @gr8web 

This should be supported, please notice that the way you defined the O2O same type edges is actually a shorthand syntax for defining two different edges:

![Screen Shot 2023-04-11 at 11 19 30](https://user-images.githubusercontent.com/1522681/231099981-76c04b6d-3683-4d1a-8a6f-6f36cc1e8253.png)

As such, you need to annotate both sides with an `entproto.Field` number. Something like: 

```go
func (Node) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("parent", Node.Type).
			Unique().
			Annotations(entproto.Field(4))
			From("subinstances").
			Annotations(entproto.Field(5)),
	}
}

```

I'm closing this, please let me know if you run into more issues.

**Comment by kbumsik** [comment]
That's right! I defined the annotation on only one side. Annotating both sides resolved the issue for me.
