### ISSUE TITLE
query edges  limit not working

### ISSUE THREAD

**Issue by alex9968** [ent/ent#3427]
db.User.Query().
		WithBelong(func(query *ent.MomentQuery) {
			query.Limit(10)
                 }).All(ctx)

**Comment by a8m** [comment]
Hey @alex9968 👋🏻

Calling `Limit` inside eager-loading limits the entire query result. If you want to limit the number of records/edges per node (like we have in our [GraphQL integration](https://entgo.io/docs/tutorial-todo-gql-paginate)), you can use window functions as follows: https://github.com/ent/ent/blob/master/entc/integration/integration_test.go#L2003
