### ISSUE TITLE
Provide a option to disable `RETURNING`  clause

### ISSUE THREAD

**Issue by Zxilly** [ent/ent#3430]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I am working on [`dqlite`](https://github.com/canonical/go-dqlite) with entgo. It seems everything work right except `RETURNING`. For some reason, it didn't be implement properly in `dqlite`.

After read some code. I noticed this clause is also not supported by MySQL, thus entgo has already have some alternative for `RETURNING` such as

https://github.com/ent/ent/blob/27bc0470ebd3ddff01c7eaac6e5dbabbd6880f53/dialect/sql/sqlgraph/graph.go#L1871-L1883

But it seems only change behavior follow the dialect type. I wonder is that possible to add a option to disable `RETURNING` even on other dialect.

## Motivation 🔦

Add an option to make ent behavior like `RETURNING` not supported.

**Comment by a8m** [comment]
Thanks for proposing this, @Zxilly. The `RETURNING` clause was added to SQLite more than two years ago. Unfortunately, we don't plan to support additional dialects in Ent at this stage, but we aim to make it more extensible in the future.

My suggestion to you is to implement the `dialect.Driver` for dqlite and patch this logic outside Ent. 

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
