### ISSUE TITLE
Optimism lock

### ISSUE THREAD

**Issue by QZAiXH** [ent/ent#3462]
I have a Mixin with a version field in it, which I defined for optimistic locking. What can I do to make the final sql of ent: update table set version=version+1

```go
// TimeMixin holds the schema definition for the TimeMixin entity.
type TimeMixin struct {
    ent.Schema
}

// Fields of the TimeMixin.
func (TimeMixin) Fields() []ent.Field {
    return []ent.Field{
        field.Int64("version").SchemaType(map[string]string{
            dialect.MySQL: "int", // Override MySQL.
        }).Default(1),

        field.Time("created_at").SchemaType(map[string]string{
            dialect.MySQL: "datetime", // Override MySQL.
        }).Default(time.Now),

        field.Time("updated_at").SchemaType(map[string]string{
            dialect.MySQL: "datetime", // Override MySQL.
        }).Default(time.Now).UpdateDefault(time.Now),
    }
}

// Edges of the TimeMixin.
func (TimeMixin) Edges() []ent.Edge {
    return nil
}
```

**Comment by a8m** [comment]
Hey @QZAiXH 👋 
You can call `AddVersion(1)` to increment the `version` field by one. But here are two additional links that might help you:
1. Optimistic locking example in our repo: https://github.com/ent/ent/tree/master/examples/version
2. _Database Locking Techniques with Ent_ blog post: https://entgo.io/blog/2021/07/22/database-locking-techniques-with-ent/

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
