### ISSUE TITLE
entgql: schema with no fields and only inverse edges creates code that fails to compile

### ISSUE THREAD

**Issue by jogly** [ent/ent#3464]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1476969/231007017-e52e99b8-a7c9-4def-a4db-9a0d1defc7dd.png">

## Expected Behavior 🤔

No problems.

## Steps to Reproduce 🕹

Define a schema with no fields, and an inverse edge from another schema, i.e. `edge.From(...)`, and code is generated with compilation errors.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.3  |
| Ent         | 0.12.0   |
| entgql | 0.4.0 |
| Database    | PostGRES   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this, @jogly 🙏 

@Adam-Mustafa, please see https://github.com/ent/contrib/pull/475#pullrequestreview-1378458246 and add a simple test case for it. Once that's done, I can merge your contribution. I truly appreciate your help ❤️

**Comment by a8m** [comment]
Fixed with v0.4.1. Thank you both!
