### ISSUE TITLE
intercept: unexpected query type *intercept.query[

### ISSUE THREAD

**Issue by ernado** [ent/ent#3478]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
panic: unexpected query type *intercept.query[*entgo.io/bug/ent.UserQuery,entgo.io/bug/ent/predicate.User,entgo.io/bug/ent/user.Order] [recovered]
	panic: unexpected query type *intercept.query[*entgo.io/bug/ent.UserQuery,entgo.io/bug/ent/predicate.User,entgo.io/bug/ent/user.Order]
```

## Expected Behavior 🤔

No error.

## Steps to Reproduce 🕹

https://github.com/ernado/ent-interceptor-err

https://github.com/ernado/ent-interceptor-err/blob/master/bug_test.go#L17-L43

```
gen.FeatureIntercept
```
```go
func TestBugSQLite(t *testing.T) {
	tracer := trace.NewNoopTracerProvider().Tracer("")

	client := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&cache=shared&_fk=1")
	t.Cleanup(func() {
		_ = client.Close()
	})

	// Instrument reads.
	interceptor := ent.InterceptFunc(func(next ent.Querier) ent.Querier {
		return ent.QuerierFunc(func(ctx context.Context, query ent.Query) (ent.Value, error) {
			// Get a generic query from a typed-query.
			ctx, span := tracer.Start(ctx, "Query",
				trace.WithSpanKind(trace.SpanKindClient),
			)
			defer span.End()
			q, err := intercept.NewQuery(query)
			if err != nil {
				return nil, err
			}
			return next.Query(ctx, q)
		})
	})
	client.Intercept(interceptor)

	test(t, client)
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.3  |
| Ent         | v0.12.0   |

**Comment by a8m** [comment]
Hey, @ernado! It's great to see you here again 😃 

Sorry for the inconvenience, but it looks like you pass the wrong `ent.Query` to the `next` querier - you didn't get a compilation error because `ent.Query` can be anything (`any`) and I expect to improve this in the future.

In short, the `intercept.NewQuery` returns a generic `intercept.Query` object that lets you work on multiple types of `ent.<T>Query` with the same API. However, the underlying querier expects the real `<T>Query`. i.e., you need to change your code as follows:

```diff
	interceptor := ent.InterceptFunc(func(next ent.Querier) ent.Querier {
		return ent.QuerierFunc(func(ctx context.Context, query ent.Query) (ent.Value, error) {
			// Get a generic query from a typed-query.
			ctx, span := tracer.Start(ctx, "Query",
				trace.WithSpanKind(trace.SpanKindClient),
			)
			defer span.End()
			q, err := intercept.NewQuery(query)
			if err != nil {
				return nil, err
			}
			// Mutate the generic query. e.g.,
			q.Limit(10)
-			return next.Query(ctx, q)
+			return next.Query(ctx, query)
		})
	})
```

**Comment by ernado** [comment]
Oh, thank you!
