### ISSUE TITLE
Add `.Query()` & `sql.Scan*` combined method on *sql.Selector

### ISSUE THREAD

**Issue by Liooo** [ent/ent#3479]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

When building queries manually, I often find myself doing the following:

```go
// run query then error check
q, args := sql.Select(<brah>).From(<brah>).Query()
rows, err := entclient.QueryContext(q, args...)
if err != nil {
    <brah brah>
}
defer rows.Close()

// scan the result then error check
value, err := sql.ScanInt(rows)
if err != nil {
    <brah brah>
}
```

instead, it'd be nice if I could write:

```go
// add `.Query<Type>()` equivalent to `sql.Scan<Type>()`,
// or make it `.<some prefix>.Int()` and be stingy with exposing additional API
value, err := sql.Select(<brah>).From(<brah>).QueryInt()
if err != nil {
    <brah brah>
}


```

## Motivation 🔦

For the sheer utility purpose, aiming to reduce keyboard typing and code volume in possibly commonly encountered situations.
 Adding methods that merely does what's been possible by combination of others, and messing the exposed API sounds not cool in general, but as long as the scenario is fairly common, I believe it's not bad. 

What do you think?

**Comment by Liooo** [comment]
@a8m what do you think? I'm happy to send a PR if it sounds good, otherwise I'll just close the issue.

**Comment by Liooo** [comment]
sorry my stupid misunderstanding, the entclient is necessary for execution and the suggested api wasn't making sense. Closing anyhow

**Comment by a8m** [comment]
Hey! No worries, I just saw this issue 😄
