### ISSUE TITLE
v0.12.0 creates duplicate functions when an entity has a field named order

### ISSUE THREAD

**Issue by jimlackas** [ent/ent#3481]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

In v0.12.0, when generating code for an entity that has a field named `order`, two functions named `Order` are created in the same package. One is in `<entityname>/<entityname>.go` and the other in `<entityname>/where.go`. As a result, the code does not compile.

## Expected Behavior 🤔

Prior to v0.12.0, having a field named `order` worked without issue. 

Is there a way to avoid this function duplication without renaming the column in the database?

## Steps to Reproduce 🕹

Steps:

1. Create an entity with a field named `order`.
2. Generate code using v0.11.10 or earlier. No compilation errors.
3. Generate code using v0.12.0. Compilation fails due to duplicate function names.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.7  |
| Ent         | 0.12.0   |
| Database    | PostgresSQL   |

**Comment by a8m** [comment]
Hey, @jimlackas 👋🏻
The issue was fixed with https://github.com/ent/ent/pull/3468. A new patch will be released later this week, and you can install the `master` version to solve this issue atm. 
```
go get entgo.io/ent@master
```
