### ISSUE TITLE
Setting a session variable before executing a SQL query

### ISSUE THREAD

**Issue by hbagdi** [ent/ent#3488]
Hello there,

Thank you for creating an maintaining this project.
I'm working with Postgres and using Row-Level-Security (RLS) to implement some security requirements.
The code needs to execute a "SET LOCAL foo='bar'" statement before any query is executed. This will essentially set the tenant appropriately.

Is there a way to perform this in ent? Or is this something that the driver needs to take care of?

**Comment by a8m** [comment]
Hey, @hbagdi 👋 

> The code needs to execute a "SET LOCAL foo='bar'" statement before any query is executed

My assumption is that you want to attach this to a specific query and not execute this separately, right? Because Ent uses `sql.DB` under the hook which holds a connection pool. We can't control the picked sessions unless we call `Tx` or `Conn` explicitly. 

Can you share more details about the flow and what you expect/plan to use this? I'm available on our Discord if you prefer.

**Comment by hbagdi** [comment]
I think this is going to be for all queries that go via ent.
I've implemented multi-tenancy using RLS in Postgres where Postgres allows the query to work on a subset of data based on the tenant ID. I need to set a session variable for each query that executes and if the session variable is not present, then the query fails.

My 'foo' in the above query maps to the tenant ID.

You are right that this will need to be set before each query to ensure that each query is executing in the appropriate tenant.
Or, a connection pool can be made tenant aware, which will be less efficient for other reasons.

Happy to talk in more detail.
I'll try to set up discord on my end.

**Comment by a8m** [comment]
> I've implemented multi-tenancy using RLS in Postgres where Postgres allows the query to work on a subset of data based on the tenant ID.

Got it. In case you didn't see this, Ent has a privacy layer and we have a specific example for this use case. Check out: https://entgo.io/docs/privacy#multi-tenancy

>  I need to set a session variable for each query that executes and if the session variable is not present, then the query fails.

Does it mean you open a client per tenant, or the tenant is changing dynamically based on the request context? 
@masseelch added an example in [Discord](https://discord.com/channels/885059418646003782/1098081689768562748/1098114368564109502) for the first case, but the second case can be implemented by reading this info from the context - let me know the use case and I can try to help with this.

What about mutations? INSERT, UPDATE, or DELETE statements? 

> Or, a connection pool can be made tenant aware, which will be less efficient for other reasons.

Can you elaborate on why it's less efficient? We work with database schema per tenant architecture, and we manage a pool of `ent.Client`s that each is connected to a different `sql.DB`.

**Comment by hbagdi** [comment]
> Ent has a privacy layer and we have a specific example for this use case. Check out: https://entgo.io/docs/privacy#multi-tenancy

I checked it out but the docs are pretty sparse.
I will take a look at it once again to get a better understanding of it.

> Does it mean you open a client per tenant, or the tenant is changing dynamically based on the request context?
@masseelch added an example in [Discord](https://discord.com/channels/885059418646003782/1098081689768562748/1098114368564109502) for the first case, but the second case can be implemented by reading this info from the context - let me know the use case and I can try to help with this.

Yes, that comment in discord made a lot of sense and can be worked out. I need to figure out how to make sure that the SET statement is always executed and that the pattern doesn't introduce a security issue. Basically, it needs to be 100% reliable and correct. 

> What about mutations? INSERT, UPDATE, or DELETE statements?

They also always need to be isolated based on tenant in the context.
The RLS policy in Postgres depends on a tenant column that is present in each table. I have to figure out how populate the column for inserts. Perhaps, adding a hook for INSERT mutation would be sufficient. And I'll mark the column as immutable.
What do you think?


> > Or, a connection pool can be made tenant aware, which will be less efficient for other reasons.

> Can you elaborate on why it's less efficient?

Connection utilization can drop significantly if you have a lot of active tenants that have relatively low activity. This leads to increased memory pressure on the database server because each open connection costs you memory.

> We work with database schema per tenant architecture, and we manage a pool of ent.Clients that each is connected to a different sql.DB.


Interesting. That is another approach that I've been considering but the overhead of managing thousands of tens of thousands of database schemas, their backup, migration is too daunting of a task at this point.

**Comment by dangngoctam00** [comment]
Hello @a8m, when trying to add `schema (postgres term)` or `database name (others RDBMS term)` to implement multi-tenant query, I see that the predefined `NodeSpec` have `Schema` field, but I cannot set value to this field based on context of request. I think if we can set value to this field, we can have dynamic query based on tenant context instead of this approach:
>  We work with database schema per tenant architecture, and we manage a pool of ent.Clients that each is connected to a different sql.DB.

How do you think? Thanks.
