### ISSUE TITLE
entgql - inet type postgres

### ISSUE THREAD

**Issue by waszi** [ent/ent#3491]
I am using custom inet type from FAQ.

Unfortunately all custom type fields require resolvers. Is there way to handle this like builtin types ?

```
/ IP is the resolver for the ip field.
func (r *userResolver) IP(ctx context.Context, obj *ent.User) (string, error) {
	panic(fmt.Errorf("not implemented: IP - ip"))
}

// IP is the resolver for the ip field.
func (r *userWhereInputResolver) IP(ctx context.Context, obj *ent.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IP - ip"))
}

// IPNeq is the resolver for the ipNEQ field.
func (r *userWhereInputResolver) IPNeq(ctx context.Context, obj *ent.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IPNeq - ipNEQ"))
}
```

**Comment by a8m** [comment]
Hey, @waszi 👋 
You need to implement the `UnmarshalGQL`/`MarshalGQL` methods (see [example](https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/schema/durationgql/durationgql.go#L27-L48)), then tell gqlgen about this binding in `gqlgen.yml` (see [example](https://github.com/ent/contrib/blob/master/entgql/internal/todo/gqlgen.yml#L27-L29)).

If you use the GraphQL schema generator of entgql, you should use the `entgql.Type` annotation as well. See: https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/schema/category.go#L67

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this - we have a specific channel for GraphQL 😃
