### ISSUE TITLE
entc.Generate causes import package incorrect

### ISSUE THREAD

**Issue by deanchou** [ent/ent#3493]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I tried using entc.go to generate files. 
My schema is not in the ent directory.
The file under ent can be successfully generated, but the import package is incorrect. example:
```
// wrong
"xxx/data/predicate"
// right
"xxx/data/ent/predicate"
```

The entc.go file, like this:
```
func main() {

	opts := []entc.Option{
	}

	if err := entc.Generate("./data/schema", &gen.Config{
		Target:  "./data/ent",
		Features: []gen.Feature{
		},
	}, opts...); err != nil {
		log.Fatal("running ent codegen:", err)
	}
}
```
But when I run this command, I get the correct result
```
go run -mod=mod entgo.io/ent/cmd/ent generate ./data/schema --target ./data/ent
```

I found this file `entgo.io/ent/cmd/internal/base/packages.go`  are crucial.

## Expected Behavior 🤔

Use the entc.go file to obtain the correct results

## Steps to Reproduce 🕹

Steps:

1. create file ./data/schema/user.go
2. create file ./data/entc.go
3. run ./data/entc.go
4. check if the import package of the file in the ent directory is correct

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.3  |
| Ent         | 0.12.0   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey, @deanchou 👋 

You can set the `Config.Package` to your desired package path. Check out: https://pkg.go.dev/entgo.io/ent@v0.12.2/entc/gen#Config

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
