### ISSUE TITLE
Question: Does ent support Field level privacy? (e.g. set/get policies)

### ISSUE THREAD

**Issue by jakebolam** [ent/ent#3500]
We have Query/Mutation privacy policies, is it possible to have set/get policies on fields?

A simple example: user has a date of birth on their profile, but we don’t want to share with anyone who can load the ent, but only their close friends

A similar question came up on #494 cc @kkom and @a8m

**Comment by a8m** [comment]
Hey, @jakebolam 👋 

There is currently no simple way for implementing field/edge-level privacy. However, we do have an internal solution that we're using and plan to open-source (it's quite similar to the Hack version). It just requires some final API design adjustments. Would you like to join our [Discord](https://discord.com/invite/qZmPgTE6RX) and discuss your use case? It may help us push it faster.

**Comment by jakebolam** [comment]
Hey @a8m - Sounds good! For sure I'll join, see you there!

**Comment by jakebolam** [comment]
Closing this - as the current answer is not yet

In order to support this:
1. We could add some version that "hides" fields if you don't pass privacy policies (this would silently fail)
2. We would have to re-architecture the way gets work, to not use structs and instead use methods so we can check privacy and throw exceptions
