### ISSUE TITLE
Is there any way to use other engine than InnoDB?

### ISSUE THREAD

**Issue by lifthus** [ent/ent#3509]
For example, if I wanna use memory engine to manage users' session data,

can I use memory engine other than InnoDB or else for the table?

**Comment by a8m** [comment]
Hey @lifthus 👋 

You can achieve this using the [`entgql.Annotation`](https://github.com/ent/ent/blob/master/dialect/entsql/annotation.go#L76-L82) option. For example:

```go
// Annotations of the User.
func (User) Annotations() []schema.Annotation {
    return []schema.Annotation{
        entsql.Annotation{
            Options: "ENGINE = INNODB",
        },
    }
}
```

A [`Mixin`](https://entgo.io/docs/schema-mixin) can be useful here to not repeat the same configuration for every entity definition. 


Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by lifthus** [comment]
Thanks! 👍
