### ISSUE TITLE
multiple delete_time fields appear in the where condition when using soft-delete mixin

### ISSUE THREAD

**Issue by withrjp** [ent/ent#3521]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

multiple delete_time fields appear in the where condition when using [soft-delete mixin](https://entgo.io/docs/interceptors/#soft-delete),

run:
```golang
func TestQueryWithSoftDelete(t *testing.T) {
	ctx := context.Background()
	client := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&_fk=1").Debug()
	defer client.Close()

	query := client.Pet.Query()
	_, err := query.All(ctx)
	require.NoError(t, err)

	_, err = query.Count(ctx)
	require.NoError(t, err)
}
```

output:
```shell
=== RUN   TestQueryWithSoftDelete
2023/05/05 16:18:38 driver.Query: query=SELECT `pets`.`id`, `pets`.`delete_time`, `pets`.`name` FROM `pets` WHERE `pets`.`delete_time` IS NULL args=[]
2023/05/05 16:18:38 driver.Query: query=SELECT COUNT(`pets`.`id`) FROM `pets` WHERE `pets`.`delete_time` IS NULL AND `pets`.`delete_time` IS NULL args=[]
--- PASS: TestQueryWithSoftDelete (0.00s)
PASS
```

## Expected Behavior 🤔

`delete_time IS NULL` occurs only once

## Steps to Reproduce 🕹

Steps:

1. Pull the ent repo
2. Add the above code to entc/integration/hooks/hooks_test.go
3. Run test

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | v0.12.3   |
| Database    | sqlite   |
| Driver      | http://github.com/mattn/go-sqlite3       |

**Comment by a8m** [comment]
Hey, @withrjp 👋 
The query builder is not immutable. i.e., you need to call `query.Clone()` before reusing it. 

```diff
func TestQueryWithSoftDelete(t *testing.T) {
	ctx := context.Background()
	client := enttest.Open(t, dialect.SQLite, "file:ent?mode=memory&_fk=1").Debug()
	defer client.Close()

	query := client.Pet.Query()
-	_, err := query.All(ctx)
+	_, err := query.Clone().All(ctx)
	require.NoError(t, err)

	_, err = query.Count(ctx)
	require.NoError(t, err)
}
```

Please, feel free to reopen if you have any other issues with it.
