### ISSUE TITLE
Unable to do "Quick Introduction"

### ISSUE THREAD

**Issue by earljwagner** [ent/ent#3522]
"go generate ./ent" fails in this section: https://entgo.io/docs/getting-started#create-your-first-schema

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
go generate ./ent
panic: template: decode.tmpl:19: unexpected " " in in {{continue}}

goroutine 1 [running]:
entgo.io/ent/entc/gen.MustParse(...)
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/template.go:339
entgo.io/ent/entc/gen.initTemplates()
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/template.go:225 +0x73b
entgo.io/ent/entc/gen.(*Graph).templates(0xc00046e240)
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:879 +0x36
entgo.io/ent/entc/gen.generate(0xc00046e240)
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:225 +0x3f
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x1?, 0x1?)
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:143 +0x1f
entgo.io/ent/entc/gen.(*Graph).Gen(0xc00046e240)
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/gen/graph.go:216 +0x96
entgo.io/ent/entc.generate({0x7ffd74fb783f, 0x8}, 0x50?)
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/entc.go:389 +0x92
entgo.io/ent/entc.Generate({0x7ffd74fb783f, 0x8}, 0xc0000da600, {0xc0003a3cd0, 0x2, 0x0?})
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/entc/entc.go:86 +0x21f
entgo.io/ent/cmd/internal/base.GenerateCmd.func1(0xc0004b5200?, {0xc0000908b0, 0x1, 0x1?})
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/cmd/internal/base/base.go:190 +0x2af
github.com/spf13/cobra.(*Command).execute(0xc0004b5200, {0xc000090880, 0x1, 0x1})
	/home/wag/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004b4900)
	/home/wag/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/wag/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/home/wag/go/pkg/mod/entgo.io/ent@v0.12.3/cmd/ent/ent.go:24 +0xc5
exit status 2
ent/generate.go:3: running "go": exit status 1

## Expected Behavior 🤔
Files are produced as described in the section.

## Steps to Reproduce 🕹
See above.

go.mod and go.sum files below (renamed for upload)
[go.mod.txt](https://github.com/ent/ent/files/11405142/go.mod.txt)
[go.sum.txt](https://github.com/ent/ent/files/11405133/go.sum.txt)

**Comment by earljwagner** [comment]
Nevermind - this was using the stock Go 1.18 on Ubuntu 22.04 LTS
Upgrading to Go 1.20 solved this.

**Comment by guowei001** [comment]
使用windowns也遇到同样的问题，升级到1.20后解决
