### ISSUE TITLE
Is it possible to call create on struct have data?

### ISSUE THREAD

**Issue by surjit** [ent/ent#3528]
```
func main() {
	// Usage
	jsonStr := `{
"Name": "John"
}`

	contact := &ent.Contact{}
	err := UpdateUserFromJSON(jsonStr, contact )
	if err != nil {
		fmt.Printf("err %#v\n", err)
	}

	fmt.Printf("%#v\n", contact .Name)
}
```

Instead of calling each field with Set function like this 
`_, _ = client.Contact.Create().SetName(contact.Name).Save(ctx)`

Isn't possible to just call create from contact := &ent.Contact{} or pass contact on client.Contact.Create() 

Thanks,

**Comment by a8m** [comment]
Hey, @surjit 👋 
Please check out the docs on how to implement this: https://entgo.io/docs/faq#how-to-create-an-entity-from-a-struct-t


Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
