### ISSUE TITLE
Can we decouple DBDriver from Atlas migration dialect?

### ISSUE THREAD

**Issue by jakebolam** [ent/ent#3536]
## Context
Our DB password rotates every 24 hours, in order to account for this I'm adding a custom SQLDriver
<img width="759" alt="Screenshot 2023-05-13 at 8 00 01 AM" src="https://github.com/ent/ent/assets/3534236/f4551e8d-1c07-4a6f-9d7f-f28cbfaecb1c">

I then use this when setting up the DB connection
<img width="410" alt="Screenshot 2023-05-13 at 8 00 44 AM" src="https://github.com/ent/ent/assets/3534236/06c3efc1-e019-4821-aa04-ae0efd714d07">

The problem with this is when I run the schema migration `client.Schema.Create()` it panics with:
```
panic: sql/schema: unsupported dialect "my-mysql"
```

Is it possible to update schema migrations so they can still use the MySQL atlas schema migration? (even if it has a custom sql adapter). Have an example of something we could do (e.g. instead of exact string, look for string contains - #3537 - this diff fixes my problem)

**Comment by a8m** [comment]
Hey, @jakebolam 👋🏻
You can use `sql.Open` + `entsql.OpenDB` to open a MySQL driver with a different underlying driver. Check out this `pgx` example, and let me know if you need any help with this: https://entgo.io/docs/sql-integration#use-pgx-with-postgresql

**Comment by jakebolam** [comment]
Hey @a8m.

Beautiful this works perfectly, thank you!
