### ISSUE TITLE
Support for One to Many API using Ent and ogent

### ISSUE THREAD

**Issue by madugula007** [ent/ent#3543]
Team,

Thanks for creating this framework.

Trying to create  one to many relationship API to be  auto generated from ogent.
Didn't find any docs for this as such requested here.

The example is taken from gorm project to explain the scenario

We have one order struct and item struct . Order to Item it is having One to Many relation.
The details are given below:

type Order struct {
    // gorm.Model
    OrderID      uint      `json:"orderId" gorm:"primary_key"`
    CustomerName string    `json:"customerName"`
    OrderedAt    time.Time `json:"orderedAt"`
    Items        []Item    `json:"items" gorm:"foreignkey:OrderID"`
}

type Item struct {
    // gorm.Model
    LineItemID  uint   `json:"lineItemId" gorm:"primary_key"`
    ItemCode    string `json:"itemCode"`
    Description string `json:"description"`
    Quantity    uint   `json:"quantity"`
    OrderID     uint   `json:"-"`
}

The expected payload for the API in such case will be as follows:

'{"orderedAt":"2019-11-09T21:21:46+00:00",
"customerName":"Tom Jerry",
"items":[{"itemCode":"123","description":"IPhone 10X","quantity":1}]}

How do I achieve using ent and if API to be autogenerated through ogent

**Comment by masseelch** [comment]
Hey @madugula007, first of all thank you for the kind words. 

Setting up a One-to-Many relation with Ent, is really straight forward and is covered very well in [our docs](https://entgo.io/docs/schema-edges#o2m-two-types).

Both `entoas`/`ogent` are extensions to Ent, you can find a good tutorial in the [announcing blog post](https://entgo.io/blog/2022/02/15/generate-rest-crud-with-ent-and-ogen).

However, the API you are describing does not exist in ogent. The call you have there creates both an entity alongside its children and that is not covered by the autogenerated CRUD. You'd have to set up that endpoint by yourself.

Closing, but don't hesitate to re-open if things are not clear. Note, that our community in Discord is quite active and we have many users who will answer any type of question that might arise. [Feel invited to join!](https://discord.gg/qZmPgTE6RX)
