### ISSUE TITLE
[Question] How can I use mysql 'GROUP_CONCAT' in a GroupBy Aggregate sentence?

### ISSUE THREAD

**Issue by yrzs** [ent/ent#3544]
wanna struct:
```golang
	var v []struct {
		UserId uint32   `json:"user_id"`
		Date   string   `json:"date"`
		Hours  float32  `json:"hours"`
		State  []uint32 `json:"state"`
		Count  int
	}
```
in mysql like this:
```sql
SELECT user_id, date, SUM(hours) as hours, GROUP_CONCAT(state) as state, COUNT(*) as count
FROM project_process_hours
GROUP BY user_id, date
ORDER BY user_id ASC
LIMIT 10 OFFSET 0;
```

**Comment by a8m** [comment]
Hey, @yrzs! You can append those selections using custom aggregation functions or modifiers. See, these examples https://entgo.io/docs/feature-flags#custom-sql-modifiers, https://github.com/ent/ent/blob/master/entc/integration/integration_test.go#L1342-L1348. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
