### ISSUE TITLE
Error in migration version when following simple-cms-with-ent tutorial

### ISSUE THREAD

**Issue by sspringg** [ent/ent#3546]
I have been following `https://entgo.io/blog/2023/02/23/simple-cms-with-ent` and receive an error when running `atlas migrate diff ...`
The migration file looks like below
```
-- Drop schema named "public"
DROP SCHEMA "public" CASCADE;
-- Add new schema named ""
CREATE SCHEMA;
-- Create "users" table
...
```
and when I try to migrate I receive the error
```
 -> DROP SCHEMA "public" CASCADE;
 -> CREATE SCHEMA;
 pq: syntax error at or near ";"
...
execute: executing statement "CREATE SCHEMA;" from version "20230518011158": pq: syntax error at or near ";":
...
```

I presume this is because `CREATE SCHEMA` requires a `schema_name`  but ours is empty.  It seems  like I can create a `templates/schema.go` file. However, this feels like something that should work by default without having to override.

Any advice on how to resolve?

**Comment by a8m** [comment]
Hey, @sspringg 👋🏻
What Atlas version are you using? You can run `atlas version` to get this. 

Also, what’s the dev-url you used in the `migrate diff` command?

**Comment by sspringg** [comment]
I should have been more specific! 
I am trying to use Postgres:15.3 instead of mysql

```
$ atlas version
atlas version v0.11.1-d40ca69-canary
https://github.com/ariga/atlas/releases/latest
```

I followed all steps until creating the docker container

```
>$ atlas migrate diff add_users_posts --dir "file://ent/migrate/migrations"  --to "ent://ent/schema" --dev-url "docker://postgres/15/ent"

>$ atlas migrate apply --dir file://ent/migrate/migrations --url postgres://postgres:secret@localhost:5432/ent?sslmode=disable
```

**Comment by sspringg** [comment]
I don't know what I did differently :( but eventually it started working
