### ISSUE TITLE
query `OR`

### ISSUE THREAD

**Issue by shenghui0779** [ent/ent#3547]
## Current Behavior 😯

```sql
SELECT `job`.`id` FROM `job` WHERE `job`.`standard_id` = ? AND ((`job`.`suit_obj` = ? OR (`job`.`suit_obj` = ? AND `job`.`obj_id` = ?)) OR (`job`.`suit_obj` = ? AND `job`.`obj_id` = ?))
```

## Expected Behavior 🤔

```sql
SELECT `job`.`id` FROM `job` WHERE `job`.`standard_id` = ? AND ((`job`.`suit_obj` = ?) OR (`job`.`suit_obj` = ? AND `job`.`obj_id` = ?) OR (`job`.`suit_obj` = ? AND `job`.`obj_id` = ?))
```

## Steps to Reproduce 🕹

```go
ent.DB.Job.Query().Unique(false).Select(job.FieldID).Where(
    job.StandardID(1),
    job.Or(
	job.And(job.SuitObj(0)),
	job.And(
	    job.SuitObj(1),
	    job.ObjID("model_code"),
	),
	job.And(
	    job.SuitObj(2),
	    job.ObjID("tower_id"),
	),
    ),
).All(ctx)
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.4  |
| Ent         | 0.12.3   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey, @shenghui0779 👋 
These two statements represent the same query and return the same results. Apart from being less readable, what is the issue with the first one? 

The current predicates implementation is not aware of the entire WHERE clause and might add extra parens when multiple conjunctions/disjunctions are used.

**Comment by shenghui0779** [comment]
I see, 3Q!
