### ISSUE TITLE
Fatal error in the generated file  When there is field 'op' in the schema file

### ISSUE THREAD

**Issue by aesoper101** [ent/ent#3548]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the schema I created has the field op, I get a fatal error in the generated file.

The schema file:
```go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"time"
)

// Barrier holds the schema definition for the Barrier entity.
type Barrier struct {
	ent.Schema
}

// Fields of the Barrier.
func (Barrier) Fields() []ent.Field {
	return []ent.Field{
		//field.Int64("id").Positive().Unique(),
		field.String("trans_type").MaxLen(45).Default(""),                   
		field.String("gid").MaxLen(128).Default(""),                         
		field.String("branch_id").MaxLen(128).Default(""),                  
		field.String("op").MaxLen(45).Default(""),                          
		field.String("barrier_id").MaxLen(45).Default(""),                   
		field.String("reason").MaxLen(45).Default(""),                      
		field.Time("create_time").Default(time.Now).Immutable(),             
		field.Time("update_time").Default(time.Now).UpdateDefault(time.Now), 
	}
}

// Edges of the Barrier.
func (Barrier) Edges() []ent.Edge {
	return nil
}

// Indexes of the Barrier.
func (Barrier) Indexes() []ent.Index {
	return []ent.Index{
		// unique index.
		index.Fields("gid", "branch_id", "op", "barrier_id").Unique(),
		index.Fields("create_time"),
		index.Fields("update_time"),
	}
}

```
In the generated `barrier_create ` file, a fatal error occurred.

![image](https://github.com/ent/ent/assets/6196769/a04bdf9e-a4c3-4fc1-b697-4f82d217dbc6)

## Expected Behavior 🤔

![image](https://github.com/ent/ent/assets/6196769/00cce2ec-64c2-428c-96ed-769f48f33184)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.1 |
| Ent         | 0.11.0  |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Thanks for reporting this, @aesoper101. I'll give this a look.
