### ISSUE TITLE
entsql.IndexWhere queries for partial indexes are not escaped, resulting in wrong go code 

### ISSUE THREAD

**Issue by karelbilek** [ent/ent#3558]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```
index.Fields("a").
    Annotations(
        entsql.IndexWhere(`"b" AND "c" > 0`),
    )
```

results in wrong go code. It generates this in schema.go:

```
				Annotation: &entsql.IndexAnnotation{
					Where: ""b" AND "c" > 0",
				},
```

which is not a valid go, which leads to weeping and gnashing of teeth.

## Expected Behavior 🤔

```
				Annotation: &entsql.IndexAnnotation{
					Where: "\"b\" AND \"c\" > 0",
				},
```

Or, maybe better
```
				Annotation: &entsql.IndexAnnotation{
					Where: `"b" AND "c" > 0`,
				},
```

The bug might be on this line

https://github.com/ent/ent/blob/master/entc/gen/template/migrate/schema.tmpl#L183

**Comment by a8m** [comment]
Thanks for reporting this, @karelbilek 🙏.

The issue was resolved with https://github.com/ent/ent/pull/3578.
