### ISSUE TITLE
What is the behavior on ID field?

### ISSUE THREAD

**Issue by flymop** [ent/ent#3561]
Hello,
  I'm seeking clarification on the ID field override configuration. I have been reviewing the [documentation](https://entgo.io/docs/schema-fields#id-field) but I couldn't find any reference to the auto-increment feature.

From what I understand, even override the id field config, as the 'id' field is kept as an 'int' type, the auto-increment feature still seems to be active. Could you elaborate on how the ID field is constructed, or perhaps direct me to the relevant section in the code?

Thank you for your help.

**Comment by a8m** [comment]
Hey, @flymop 👋🏻

> From what I understand, even override the id field config, as the 'id' field is kept as an 'int' type, the auto-increment feature still seems to be active.

Defining an (int) ID field in the schema will let you set it on creation, but it still create it as incremental column to set it a default in case if was not set. However, you can disable it using the entsql.Annotation. 

> Could you elaborate on how the ID field is constructed, or perhaps direct me to the relevant section in the code?

Can you elaborate on what you try to achieve, and what database you use?

**Comment by flymop** [comment]
> Hey, @flymop 👋🏻
> 
> > From what I understand, even override the id field config, as the 'id' field is kept as an 'int' type, the auto-increment feature still seems to be active.↳
> 
> Defining an (int) ID field in the schema will let you set it on creation, but it still create it as incremental column to set it a default in case if was not set. However, you can disable it using the entsql.Annotation.↳
> 
> > Could you elaborate on how the ID field is constructed, or perhaps direct me to the relevant section in the code?↳
> 
> Can you elaborate on what you try to achieve, and what database you use?↳

Thanks for your reply, I'm currently use postgresql.

**Comment by a8m** [comment]
Can we close this issue then? You can feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by flymop** [comment]
sure.
