### ISSUE TITLE
elided  omitempty field

### ISSUE THREAD

**Issue by wujiang41105631** [ent/ent#3564]
just as the code 
`AddPortrait int `json:"add_portrait,omitempty"``
after execute  'go generate ./ent' , code 'omitempty' has been added by default, how can I config ent  can elided it?

**Comment by a8m** [comment]
Hey, @wujiang41105631 👋🏻

You can achieve this using codegen hooks. See my answer for this question in the issue tracker: https://github.com/ent/ent/issues/1354#issuecomment-802717547

> There's no option to remove the `omitempty` tag using configuration, but you can use [codegen hooks](https://entgo.io/docs/code-gen/#code-generation-hooks) to modify all fields globally as follows:
> 
> ```go
> // +build ignore
> 
> package main
> 
> func main() {
> 	err := entc.Generate("./schema", &gen.Config{
> 		Hooks: []gen.Hook{TagFields("json")},
> 	}, opts...)
> 	if err != nil {
> 		log.Fatalf("running ent codegen: %v", err)
> 	}
> }
> 
> // TagFields tags all fields defined in the schema with the given struct-tag.
> func TagFields(name string) gen.Hook {
> 	return func(next gen.Generator) gen.Generator {
> 		return gen.GenerateFunc(func(g *gen.Graph) error {
> 			for _, node := range g.Nodes {
> 				for _, field := range node.Fields {
> 					field.StructTag = fmt.Sprintf("%s:%q", name, field.Name)
> 				}
> 			}
> 			return next.Generate(g)
> 		})
> 	}
> }
> ```
> 
> I added a working example to our repository #1356. 

Closing, but please feel free to reopen if you need further help with this.

**Comment by wxmeng04** [comment]
If you want to maintain part of the struct tag, you can also use blow:
```
//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
)

func main() {
	err := entc.Generate("./schema", &gen.Config{
		Hooks: []gen.Hook{TagFields("json")},
	})
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}

// TagFields tags all fields defined in the schema with the given struct-tag.
func TagFields(name string) gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			for _, node := range g.Nodes {
				for _, field := range node.Fields {
					if field.StructTag == `json:"-"` {
						continue
					}
					field.StructTag = fmt.Sprintf("%s:%q", name, field.Name)
				}
			}
			return next.Generate(g)
		})
	}
}
```
