### ISSUE TITLE
edges and field's "order by" generated conflict

### ISSUE THREAD

**Issue by syssam** [ent/ent#3565]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```

func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("follower_count").Default(0),
		field.Int("following_count").Default(0),
	}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("following", User.Type).Through("user_following", UserFollowing.Type),
		edge.From("followers", User.Type).Through("user_followers", UserFollowing.Type).Ref("following"),
	}
}


// ByFollowingCount orders the results by the following_count field.
func ByFollowingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFollowingCount, opts...).ToFunc()
}
```
It will generate 2 times ByFollowingCount
## Expected Behavior 🤔

It will generate 1 time and different name ByFollowingCount for edges and fields

## Steps to Reproduce 🕹

Steps:

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19.?  |
| Ent         |  latest   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey, @syssam 👋 
Using the same "edge schema" in multiple edge definitions is not supported. Please, use this definition instead: https://entgo.io/docs/schema-edges#m2m-same-type 

Closing, but please let's continue the discussion on [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by syssam** [comment]
code for someone's reference
```
edge.To("following", User.Type).Annotations(entgql.RelayConnection()).Through("user_following", UserFollowing.Type).From("followers").Annotations(entgql.RelayConnection()),
```

**Comment by syssam** [comment]
@a8m here is second part conflict with edge and field
```
// ByFollowingCount orders the results by following count.
func ByFollowingCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFollowingStep(), opts...)
	}
}

// ByFollowingCount orders the results by the following_count field.
func ByFollowingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFollowingCount, opts...).ToFunc()
}
```
