### ISSUE TITLE
[Feature request] Add Only Skip Graphql Schema

### ISSUE THREAD

**Issue by syssam** [ent/ent#3567]
Please add entgql.SkipGraphqlSchema

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦
Sometimes will hide some graphql schema, but can call on internal

**Comment by a8m** [comment]
Hey! The `Skip` option allow selecting specific types (mutations, nodes, filters, etc). If you need a custom editing, you can use schema hooks as described here: https://github.com/ent/ent/issues/3173#issuecomment-1359338499

**Comment by syssam** [comment]
@a8m I want to don't generate graphql schema, but generate golang
