### ISSUE TITLE
Tag supported for go 1.17

### ISSUE THREAD

**Issue by chauhan17nitin** [ent/ent#3568]
Want to use this in a project which uses go 1.17, using the latest tag gives error module requires Go 1.20

Can anyone tell how can i find the tag which is supported for go 1.17

**Comment by a8m** [comment]
Hey, @chauhan17nitin 👋🏻

Ent supports the latest Go versions. Currently, Go 1.19 and 1.20.

Go 1.17 was supported in version v0.10/v0.10.1 which I won’t recommend to use, as many bugs were fixed since then.
