### ISSUE TITLE
collate

### ISSUE THREAD

**Issue by ruan-xb-63** [ent/ent#3569]
how to set collate

**Comment by a8m** [comment]
Hey, @ruan-xb-63 👋 

You can use the [Collation/Charset](https://github.com/ent/ent/blob/master/dialect/entsql/annotation.go#L21-L36) annotations to configure it to your schema. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
