### ISSUE TITLE
How to solve merge conflict on generated ent code.

### ISSUE THREAD

**Issue by badsector998** [ent/ent#3571]
Hello everyone,

I'd like to ask a question about how I can solve merge conflict on generated ent code. The scenario is my colleague is working on branch A and has merge it to branch `dev` and I was working on branch B based on previous `dev` branch. I want to update my current working B branch with the updated `dev` branch. But it has many conflicts on generated ent code.

On both branches `dev` and B there are new schemas introduced. So we ended up with different generated ent code. I know we can't edit them manually. But I have a hunch I can solve the conflict on schema part. I tried to do accept both changes on schemas and leave the generated ent code to either incoming change or current change. But when I re-generate the ent code it returns many errors.

Is there a way we can solve this merge conflict? I tried to google around and hasn't yet come into conclusion how can I solve this.

ps. I tried to rebase the `dev` branch onto branch B. But it's only moving the git tree of branch B on top of updated `dev` branch while nothing changes on the code on branch B.

Thank you.

**Comment by a8m** [comment]
Hey, @badsector998 👋🏻
There is a feature-flag specifically for this problem. Check it out and reopen if you still face issues with it.
https://entgo.io/docs/feature-flags#auto-solve-merge-conflicts

**Comment by badsector998** [comment]
thanks for the fast response. sure, will check it first 😄
