### ISSUE TITLE
Should `count()` return uint64 ?

### ISSUE THREAD

**Issue by shenghui0779** [ent/ent#3574]
If a table has a large amount of data, is returning `int` enough?

**Comment by a8m** [comment]
Hey, @shenghui0779 👋 

I assume you forgot this, but I answered (you) this question 18 months ago 😅 

Here's my answer: https://github.com/ent/ent/issues/2213#issuecomment-991617437:

> Hey @shenghui0779 👋 It does make sense that `Count` will return `uint64` instead of `int`, but we can't change the API atm, and you're welcome to override this part using [custom template](https://entgo.io/docs/templates/) if it cause you any issues. Also, I think most (if not all) ent users use 64-bits systems, and `int` has the range of int64, so using `int` is safe and also reduce redundant conversions.
> 
> Closing, but please feel free to continue the discussion or join our [Slack](https://entgo.io/docs/slack/)/[Discord](https://discord.gg/qZmPgTE6RX) if you have more questions/thoughts. Thanks 🙏

Did you face any issues with it since then?

**Comment by shenghui0779** [comment]
Thanks! I see.
