### ISSUE TITLE
Direct access to sql.Tx

### ISSUE THREAD

**Issue by fsaintjacques** [ent/ent#3583]
Is it possible to extract the underlying sql.Tx transaction from a ent.Tx?

**Comment by a8m** [comment]
Hey, @fsaintjacques 👋🏻

The `dialect.Driver` can be decorated multiple times. Can you elaborate on why do you need access to the underlying sql.Tx, or what problem you try to solve with it? Thanks

**Comment by fsaintjacques** [comment]
I have some library that uses `sql.Tx` directly, mostly via ExecContext, QueryContext, and QueryRowContext. [sqlboiler](https://github.com/volatiletech/sqlboiler/blob/master/boil/db.go#L16-L22) exposes something similar.

**Comment by a8m** [comment]
The `sql.Driver/sql.Tx` implements the `ExecQuerier` as defined [here](https://github.com/ent/ent/blob/2c63d1d/dialect/sql/driver.go#L78-L93). You can type-assert `dialect.Tx` to `dialect/sql.Tx`. We actually use the same interface in Atlas.

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by wxmeng04** [comment]
> The `sql.Driver/sql.Tx` implements the `ExecQuerier` as defined [here](https://github.com/ent/ent/blob/2c63d1d/dialect/sql/driver.go#L78-L93). You can type-assert `dialect.Tx` to `dialect/sql.Tx`. We actually use the same interface in Atlas.
> 
> Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

It's not clear. If I create a transaction via ent.Client. You can neither type-assert it to sql.Tx nor sql.ExecQuerier acutally.
```
var cli ent.Client
tx, err := sqlCli.Tx(ctx)
newTx = sql.ExecQuerier(tx) // it doen't work as tx doesn't implement the interface.
```

**Comment by advdv** [comment]
We needed this for use with: https://riverqueue.com and was looking for something like: https://riverqueue.com/docs/gorm. I'm not sure this method is the best or the only way but we had implemented a custom ent driver + ent tx anyway so from there it was fairly straightforward. You can find the place where we cast to the sql.Tx over here: https://github.com/advdv/stdgo/blob/v0.0.115/stdent/wtx.go#L57
