### ISSUE TITLE
NoSQL support

### ISSUE THREAD

**Issue by pulkitbhardwaj** [ent/ent#3587]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by a8m** [comment]
Hey, @pulkitbhardwaj 👋 

NoSQL databases are on our roadmap, you can follow this on https://github.com/ent/ent/issues/2247. 

Closing as it's a duplicate of #2247. Feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you have more questions or thoughts on this subject 😎
