### ISSUE TITLE
Make builder a reserved keyword

### ISSUE THREAD

**Issue by ivanvanderbyl** [ent/ent#3591]
Creating a node called `Builder` seems to conflict with internal names used by the code generator.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior 🤔

Creating a node called `Builder` should either error or be allowed, not fail with invalid code.

## Steps to Reproduce 🕹

```
ent new Builder
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.2  |
| Ent         | v0.12.3   |
| Database    | Postgres   |

**Comment by a8m** [comment]
Hey, @ivanvanderbyl, it's great to see you here 😃 

Thanks for reporting this. The issue was resolved with https://github.com/ent/ent/pull/3593.
