### ISSUE TITLE
How to make the delete_time field generated by mixin appear at the end of the table in the database in the soft delete example in the interceptors section?

### ISSUE THREAD

**Issue by febelery** [ent/ent#3596]
How to make the delete_time field generated by mixin appear at the end of the table in the database in the soft delete example in the [interceptors section](https://entgo.io/docs/interceptors#soft-delete)?

# mixin
```golang
// SoftDeleteMixin implements the soft delete pattern for schemas.
type SoftDeleteMixin struct {
    mixin.Schema
}

// Fields of the SoftDeleteMixin.
func (SoftDeleteMixin) Fields() []ent.Field {
    return []ent.Field{
        field.Time("delete_time").
            Optional(),
    }
}
```

# user
```golang
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int("age"),
	}
}

func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SoftDeleteMixin{},
	}
}

```

# generate column

| id         | int       |
| :-----|:----|
| deleted_at | time.Time |
| age        | int       |

# the order I need

| id         | int       |
| :-----|:----|
| age        | int       |
| deleted_at | time.Time |

**Comment by a8m** [comment]
Hey, @febelery 👋 

You can use [code generation hooks](https://entgo.io/docs/code-gen#code-generation-hooks) to move the field to the end of the list. 

```
func EnsureStructTag(name string) gen.Hook {
    return func(next gen.Generator) gen.Generator {
        return gen.GenerateFunc(func(g *gen.Graph) error {
            for _, node := range g.Nodes {
                // Iterate over "node.Fields" and move "deleted_at" to the end of the fields list.
            }
            return next.Generate(g)
        })
    }
}
```
Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by syssam** [comment]
@a8m Edge fields not working
