### ISSUE TITLE
Is it possible to trace the time cost of internal function in ent

### ISSUE THREAD

**Issue by ThanksSirAlex** [ent/ent#3606]
I have a very simple sql `select * from table where ***`and another one `select * from table where ***  Limit 100` . The only difference is `Limit 100` but the second one is 10 time slower than the first one. I’m now certain that these sql are not slow query. Is there any method that can help me find out why the second one is slow and where times are used in ent.

**Comment by a8m** [comment]
Hey @ThanksSirAlex 👋 

There are a few options to achieve something like this:
- Interceptors: Check out the docs for this: https://entgo.io/docs/interceptors
- Decorate the underlying driver with a custom one that records and prints queries' executions. Please take a look at the DebugDriver as an example: https://github.com/ent/ent/blob/master/dialect/dialect.go#L67-L70. 
- Use something like OpenTelemetry or OpenCensus as explained here: https://entgo.io/docs/sql-integration#use-opencensus-with-mysql

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
