### ISSUE TITLE
Multiple Postgres Schema Migration

### ISSUE THREAD

**Issue by Najidnadri** [ent/ent#3608]
I guess this question is an extended version of this issue [#633](https://github.com/ent/ent/issues/663).

Currently, in EntGo, way to connect to multiple postgres schema is to enable the `sql/schemaconfig` and use it with your client like this :-
```go
schemas := ent.AlternateSchema(ent.SchemaConfig{
User:                    "public",
Tag:                     "sys",
})
// Create an ent.Driver from `db`.
drv := entsql.OpenDB(dialect.Postgres, db)
return ent.NewClient(ent.Driver(drv), schemas), nil
```

But this wont work with the automatic migrations. The `Tag` table will still be created in the `public` schema. My current workaround is to create a hook like this :-
```go
func sysHook(next schema.Applier) schema.Applier {
	return schema.ApplyFunc(func(ctx context.Context, conn dialect.ExecQuerier, plan *atlasMigrate.Plan) error {
		// Iterate over the migration script
		for _, change := range plan.Changes {
			if strings.Contains(change.Cmd, "CREATE TABLE \"tag\"") {
				change.Cmd = "CREATE SCHEMA IF NOT EXISTS sys; " + change.Cmd
			}
			change.Cmd = strings.ReplaceAll(change.Cmd, "\"tag\"", "\"sys\".\"tag\"")
		}

		return next.Apply(ctx, conn, plan)
	})
}
```

However, when I change anything in the `Tag` schema later on, and do the automatic migration, the desired schema will only be compared to the `public` postgres. Hence, it will then try to create a new `tag` table. I tried to solve with the `diff` hook but no progress has been made.

Is there any other workaround to do migrations to multiple schemas in postgres?

**Comment by htwatanabe** [comment]
I made a comment related to this issue here #3343. If you would like to check it out, please do so. I would also appreciate it if you could let me know if you have any opinions.

**Comment by a8m** [comment]
Hey! This feature has been added to Atlas: https://entgo.io/docs/multischema-migrations.

Closing this issue, as Atlas natively supports Ent schemas using the `ent://` scheme.
