### ISSUE TITLE
M2M Two types Via Through like M2M Same Type. 

### ISSUE THREAD

**Issue by wahello** [ent/ent#3621]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by a8m** [comment]
Hey 👋🏻 
There are plenty of examples in the `integration/edgeschema` package, but this specific User<>Group involves two types: https://github.com/ent/ent/blob/master/entc/integration/edgeschema/ent/schema/user.go#L30
