### ISSUE TITLE
missing go.sum entry for module providing package

### ISSUE THREAD

**Issue by gaoyusongcn** [ent/ent#3638]
Hello, I get an error when I use the code generation package.
Could you please take a look at it for me? [My code](https://github.com/gaoyusongcn/testent)

error:
```
rror while importing entgo.io/ent/entc: missing go.sum entry for module providing package golang.org/x/tools/go/ast/astutil (imported by entgo.io/ent/entc/load); to add:
	go get entgo.io/ent/entc/load@v0.12.3compiler
error while importing entgo.io/ent/entc: missing go.sum entry for module providing package golang.org/x/tools/go/packages (imported by entgo.io/ent/entc); to add:
	go get entgo.io/ent/entc@v0.12.3compiler
error while importing entgo.io/ent/entc: missing go.sum entry for module providing package golang.org/x/tools/imports (imported by entgo.io/ent/entc/gen); to add:
	go get entgo.io/ent/entc/gen@v0.12.3compiler
Package entc provides an interface for interacting with entc (ent codegen) as a package rather than an executable.
```
![image](https://github.com/ent/ent/assets/43459833/4fdd3f4c-72f9-4407-a57b-e635d3f821e8)

**Comment by a8m** [comment]
Hey @gaoyusongcn 👋 

Running `go run` with `-mod=mod` should solve this issue.

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by till** [comment]
@a8m (I already posted on discord yesterday)

I wanted to know why `go run -mod=readonly` does not work. It seems like, I require `ent/ent@v0.12.4` and I have a `generate.go` and `entc.go` setup in my code base. Is there a way to use `readonly` at all?

**Comment by till** [comment]
When I switch to `-mod=mod` I am stuck in a loop where a `go generate ./...` keeps adding dependencies to my `go.sum` and then my CI fails that I have to run `go mod tidy`.

E.g. golang-ci complains about that, etc. or go test fails with:

```
go: updates to go.mod needed; to update it:
	go mod tidy
```

It seems to have started when I upgraded to `v0.12.4`.

When I do `-mod=readonly`, then code generation is broken (see above).

**Comment by zikaeroh** [comment]
As far as I'm concerned, both `go run -mod=readonly` and `go run -mod=mod` are incorrect; the right way to approach this problem is to have a `tools.go` in your project:

```go
//go:build tools
// +build tools

package tools

import (
	_ "entgo.io/ent/cmd/ent"
)
```

Then invoke it as:

```go
//go:generate go run entgo.io/ent/cmd/ent
```

This ensures that your `go.mod`/`go.sum` are always clean.

Eventually https://github.com/golang/go/issues/48429 will encode this behavior in Go itself, meaning people will just write:

```go
//go:generate go tool ent
```

And Go will handle the rest.
