### ISSUE TITLE
JSON field's Default() unable to do database migration

### ISSUE THREAD

**Issue by itviewer** [ent/ent#3639]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
when create a JSON field like this
```
field.JSON("dirs", []http.Dir{}).Default([]http.Dir{"/tmp"}),
```
There are no default values set in the generated database DDL.  The following error is reported when migrating the database:
```
Cannot add a NOT NULL column with default value NULL
```
## Expected Behavior 🤔

After add new JSON field wtih Default() , database migration should not report errors

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.2  |
| Ent         | 0.12.3   |
| Database    | Sqlite   |
| Driver      | github.com/mattn/go-sqlite3       |

**Comment by itviewer** [comment]
I find the problem at here https://github.com/ent/ent/blob/c46cf6317b25707f86bd568acbaefd083c2c175f/entc/gen/type.go#L1551
I had to use both Default function and Annotations to achieve creating and migrating default JSON data at the same time.

**Comment by AlbinoDrought** [comment]
Example annotations:

```go
field.JSON("dirs", []http.Dir{}).Default([]http.Dir{"/tmp"}).Annotations(entsql.Default(`["/tmp"]`))
```

```go
field.Strings("dirs").Default([]string{}).Annotations(entsql.Default("[]"))
```

Related: https://github.com/ent/ent/pull/3081
