### ISSUE TITLE
import cycle in v0.12.3

### ISSUE THREAD

**Issue by dengao123** [ent/ent#3646]
- [√ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
```html
        imports sigma_third_service/database/seeds/internal
        imports sigma_third_service/internal/data/ent
        imports sigma_third_service/internal/data/ent/schema
        imports sigma_third_service/internal/data/ent/schema/schematype
        imports sigma_third_service/internal/data/ent: import cycle not allowed
```

Steps:

1.  add softDelete in schema/schematype/softdelete.go
```go
// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

package schematype

import (
	"context"
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/mixin"
	gen "sigma_third_service/internal/data/ent"
	"sigma_third_service/internal/data/ent/hook"
	"sigma_third_service/internal/data/ent/intercept"
)

type SoftDeleteMixin struct {
	mixin.Schema
}

func (SoftDeleteMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Time("deleted_at").Nillable().
			Optional(),
	}
}

type softDeleteKey struct{}

// SkipSoftDelete returns a new context that skips the soft-delete interceptor/mutators.
func SkipSoftDelete(parent context.Context) context.Context {
	return context.WithValue(parent, softDeleteKey{}, true)
}

func (d SoftDeleteMixin) Interceptors() []ent.Interceptor {
	return []ent.Interceptor{
		intercept.TraverseFunc(func(ctx context.Context, q intercept.Query) error {
			// Skip soft-delete, means include soft-deleted entities.
			if skip, _ := ctx.Value(softDeleteKey{}).(bool); skip {
				return nil
			}
			d.P(q)
			return nil
		}),
	}
}

func (d SoftDeleteMixin) Hooks() []ent.Hook {
	return []ent.Hook{
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
					// Skip soft-delete, means delete the entity permanently.
					if skip, _ := ctx.Value(softDeleteKey{}).(bool); skip {
						return next.Mutate(ctx, m)
					}
					mx, ok := m.(interface {
						SetOp(ent.Op)
						Client() *gen.Client
						SetDeleteTime(time.Time)
						WhereP(...func(*sql.Selector))
					})
					if !ok {
						return nil, fmt.Errorf("unexpected mutation type %T", m)
					}
					d.P(mx)
					mx.SetOp(ent.OpUpdate)
					mx.SetDeleteTime(time.Now())
					return mx.Client().Mutate(ctx, m)
				})
			},
			ent.OpDeleteOne|ent.OpDelete,
		),
	}
}

func (d SoftDeleteMixin) P(w interface{ WhereP(...func(*sql.Selector)) }) {
	w.WhereP(
		sql.FieldIsNull(d.Fields()[0].Descriptor().Name),
	)
}

```
3.  add MixIn in scheme/*.go like below
```golang
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"sigma_third_service/internal/data/ent/schema/schematype"
)

// AIWeatherDistrict holds the schema definition for the AIWeatherDistrict entity.
type AIWeatherDistrict struct {
	ent.Schema
}

// Fields of the AIWeatherDistrict.
func (AIWeatherDistrict) Fields() []ent.Field {
	return []ent.Field{
		field.String("city").Nillable(),
		field.String("district").Nillable(),
		field.String("area_code").Nillable(),
		field.String("district_code").Nillable(),
		field.String("city_geocode").Nillable(),
		field.String("nmc_code").Nillable(),
	}
}

// Edges of the AIWeatherDistrict.
func (AIWeatherDistrict) Edges() []ent.Edge {
	return nil
}

// Annotations of the AIWeatherDistrict.
func (AIWeatherDistrict) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{Table: "ccp_ai_weather_districts"},
	}
}

// Mixin of the AIWeatherDistrict.
func (AIWeatherDistrict) Mixin() []ent.Mixin {
	return []ent.Mixin{
		schematype.Time{},
	}
}

```
3. run go generate
4. use cient.AIWeatherDistrict.Create()...

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20  |
| Ent         | v0.12.3  |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

`In version v0.12.2, there is no problem. In version v0.12.3, writing the code from ent/runtime/runtime. go to ent/runtime. go will cause a problem. What should I do?`

**Comment by a8m** [comment]
Hey @dengao123 👋 

Please follow the instructions described here: https://entgo.io/docs/hooks#import-cycle-error

**Comment by dengao123** [comment]
I solved this problem by moving func init() from ent/runtime. go  to ent/runtime/runtime. go
ent/runtime.go
`// Code generated by ent, DO NOT EDIT.

package ent

import (
	"sigma_third_service/internal/data/ent/aiweatherdistrict"
	"sigma_third_service/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	aiweatherdistrictMixin := schema.AIWeatherDistrict{}.Mixin()
	aiweatherdistrictMixinFields0 := aiweatherdistrictMixin[0].Fields()
	_ = aiweatherdistrictMixinFields0
	aiweatherdistrictFields := schema.AIWeatherDistrict{}.Fields()
	_ = aiweatherdistrictFields
	// aiweatherdistrictDescCreatedAt is the schema descriptor for created_at field.
	aiweatherdistrictDescCreatedAt := aiweatherdistrictMixinFields0[0].Descriptor()
	// aiweatherdistrict.DefaultCreatedAt holds the default value on creation for the created_at field.
	aiweatherdistrict.DefaultCreatedAt = aiweatherdistrictDescCreatedAt.Default.(func() time.Time)
	// aiweatherdistrictDescUpdatedAt is the schema descriptor for updated_at field.
	aiweatherdistrictDescUpdatedAt := aiweatherdistrictMixinFields0[1].Descriptor()
	// aiweatherdistrict.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	aiweatherdistrict.DefaultUpdatedAt = aiweatherdistrictDescUpdatedAt.Default.(func() time.Time)
	// aiweatherdistrict.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	aiweatherdistrict.UpdateDefaultUpdatedAt = aiweatherdistrictDescUpdatedAt.UpdateDefault.(func() time.Time)
}
`
ent/runtime/runtime. go
`// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in sigma_third_service/internal/data/ent/runtime.go

const (
	Version = "v0.12.2"                                         // Version of ent codegen.
	Sum     = "h1:Ndl/JvCX76xCtUDlrUfMnOKBRodAtxE5yfGYxjbOxmM=" // Sum of ent codegen.
)
`

**Comment by it512** [comment]
copy On HasOp If ... func to your softdelete.go file

func on(hk ent.Hook, op ent.Op) ent.Hook {                                                                              
 97 |   return iif(hk, hasOp(op))                                                                                           
 98 }                                                                                                                       
 99                                                                                                                         
100 func hasOp(op ent.Op) condition {                                                                                       
101 |   return func(_ context.Context, m ent.Mutation) bool {                                                               
102 |   |   return m.Op().Is(op)                                                                                            
103 |   }                                                                                                                   
104 }                                                                                                                       
105                                                                                                                         
106 func iif(hk ent.Hook, cond condition) ent.Hook {                                                                        
107 |   return func(next ent.Mutator) ent.Mutator {                                                                         
108 |   |   return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {                            
109 |   |   |   if cond(ctx, m) {                                                                                           
110 |   |   |   |   return hk(next).Mutate(ctx, m)                                                                          
111 |   |   |   }                                                                                                           
112 |   |   |   return next.Mutate(ctx, m)                                                                                  
113 |   |   })                                                                                                              
114 |   }                                                                                                                   
115 }                                                                                                                       
116                                                                                                                         
117 type condition func(context.Context, ent.Mutation) bool      


to avoid use <proj>/ent/hook

**Comment by a8m** [comment]
It looks like the issue was resolved.

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
