### ISSUE TITLE
FR: Provide a way to serialize Edges on the struct's root level

### ISSUE THREAD

**Issue by idc77** [ent/ent#3652]
Right now edges are a separate field with children.
Instead of having a JSON serialized result like (simple post/comment example)
```json
{
  "id": "4f54caff-5e67-4f99-8e2d-655b3562c270",
  "title": "hello world",
 "edges": {
    "comments": [
      {"id": "2644a913-04c3-440a-9883-afb38c4bc1ee", "body":"1st"},
      {"id": "378a5a7e-6b1a-4f33-a72c-9e84744e7365", "body":"2nd"},
    ]
  }
}
```
there should be a way to have normalizable structs/json responses.
That means moving edges to the root level.
Instead of the above, the result would look like
```json
{
  "id": "4f54caff-5e67-4f99-8e2d-655b3562c270",
  "title": "hello world",
  "comments": [
      {"id": "2644a913-04c3-440a-9883-afb38c4bc1ee", "body":"1st"},
      {"id": "378a5a7e-6b1a-4f33-a72c-9e84744e7365", "body":"2nd"},
    ]
}
```
Why not manually marshalling and iterating over the resulsts?
Because, obviously, lower performance and at least double memory usage vs natively supported way to render/serialize those structs.

For gqlgen there's this helper function that renders resulsts as a RelayModel (I forgot the exact name).

Instead of Post and Comment those structs could be called PostRoot or CommentRoot or NormalizablePost or NormalizableComment or just NPost or NComment or PostN/CommentN

Instead of having
```go
// Post is the model entity for the Post schema.
type Post struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Status holds the value of the "status" field.
	Status post.Status `json:"status,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	Edges         PostEdges `json:"edges"`
	blog_posts    *uuid.UUID
	profile_posts *uuid.UUID
	selectValues  sql.SelectValues
}

// PostEdges holds the relations/edges for other nodes in the graph.
type PostEdges struct {
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// Reactions holds the value of the reactions edge.
	Reactions []*PostReaction `json:"reactions,omitempty"`
	// Blog holds the value of the blog edge.
	Blog *Blog `json:"blog,omitempty"`
	// Author holds the value of the author edge.
	Author *Profile `json:"author,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
	// totalCount holds the count of the edges above.
	totalCount [6]map[string]int

	namedCategories map[string][]*Category
	namedTags       map[string][]*Tag
	namedComments   map[string][]*Comment
	namedReactions  map[string][]*PostReaction
}
```

It could look like
```go
// Post is the model entity for the Post schema.
type PostN struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Status holds the value of the "status" field.
	Status post.Status `json:"status,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostQuery when eager-loading is set.
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// Reactions holds the value of the reactions edge.
	Reactions []*PostReaction `json:"reactions,omitempty"`
	// Blog holds the value of the blog edge.
	Blog *Blog `json:"blog,omitempty"`
	// Author holds the value of the author edge.
	Author *Profile `json:"author,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
	// totalCount holds the count of the edges above.
	totalCount [6]map[string]int

	namedCategories map[string][]*Category
	namedTags       map[string][]*Tag
	namedComments   map[string][]*Comment
	namedReactions  map[string][]*PostReaction

	blog_posts    *uuid.UUID
	profile_posts *uuid.UUID
	selectValues  sql.SelectValues
}
```
essentially dissolving the ModelEdge struct.

Why?
Quite frankly, to be able to normalize those JSON responses on the client side.
For instance Vuex-ORM or Pinia-ORM exists, which are able to normalize those kinds of responses into their corresponding types, in this case Post and Comment.
I'm pretty sure in other frameworks or languages that's also something desirable.
How would one define a Dart class with Edges? Sounds near impossible, or at least with a considerable effort.
Because of this, ent can't be used in any regular REST API.
The tooling for root level edges already exists, but there is none for separate edges.
You can't expect the whole client world to bend over backwards to accomodate ent, it must be the other way around.

For this same reason I'm considering to no longer use ent, even if I like it very much, but it seems it's only good for graphql servers.

If I'm missing something, please correct.
Again iterating over each result and marshalling into a custom type can't be the solution, as it costs extra cpu power and memory and effort. It must be supported natively.

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

```go
client.Post.Query().WithComments().GetNormalizable() // or GetN()
client.Post.Query().WithComments().GetNormalizableX() // or GetNX()
```
## Motivation 🔦

Being able to normalize responses in various clients over a REST API.

**Comment by a8m** [comment]
Hey @idc77,
Please see this example: https://entgo.io/docs/faq#how-to-configure-jsonmarshal-to-inline-the-edges-keys-in-the-top-level-object

**Comment by idc77** [comment]
Awesome, thanks so much :) Big headache removed.

**Comment by irg1008** [comment]
Sorry to write here again, but should I just create the `entc.go` file and paste the snippet provided in the docs? It doesn't seem to work

**Comment by a8m** [comment]
There's a full example in this file: https://github.com/ent/ent/blob/master/examples/jsonencode/ent/entc.go

**Comment by irg1008** [comment]
Yeah I am pasting the exact code, generating, and still get "edges" object. I am probbably missing something

**Comment by irg1008** [comment]
Okay I copied the `entc.go` but forgot to change the generate comment in `generate.go`

This is probbably me just starting with the library but this is not really that clear in the docs or repo Readme. Probabbly something like "If you want this extension just copy entc and generate in yor ent folder"?
