### ISSUE TITLE
failed generating protos

### ISSUE THREAD

**Issue by KaptinLin** [ent/ent#3658]
When use entproto
```
go run entgo.io/contrib/entproto/cmd/entproto -path ./schema
```

## Current Behavior 😯

It trigger error below

```
entproto: failed generating protos: entproto: failed generating generate.go file for "proto\\entpb\\entpb.proto": Rel: can't make  relative to D:\app\internal\proto\entpb
```

## Expected Behavior 🤔

no errror

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21  |
| Ent         | 0.12.3   |

**Comment by rotemtam** [comment]
Fixed in https://github.com/ent/contrib/pull/521
```
go get -u entgo.io/ent/contrib@master
```
