### ISSUE TITLE
[building bug] entc/gen: set "Device" foreign-keys: edge "user_owner" has a field "UserID" but it is not holding a foreign key

### ISSUE THREAD

**Issue by Locter9001** [ent/ent#3666]
- [ x ] The issue is present in the latest release.
- [ x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
```shell
entc/gen: set "Device" foreign-keys: edge "user_owner" has a field "UserID" but
it is not holding a foreign key
```

## Expected Behavior 🤔

success!

## Steps to Reproduce 🕹
```golang

func (Device) Fields() []ent.Field {
	return []ent.Field{
		field.Int("ProductID").Immutable(),
	}
}

func (Device) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("product_owner", Product.Type).Ref("product_devices").Field("ProductID"),
		edge.From("user_owner", User.Type).Ref("user_devices").Field("UserID"),
		edge.To("events", DeviceEvent.Type),
		edge.To("logs", DeviceLog.Type),
		edge.To("monitors", MonitorFile.Type),
	}
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.2  |
| Ent         | 0.12.3  |
| Database    | PostgresQL   |

**Comment by a8m** [comment]
Hey @Locter9001 👋🏻

Only schemas the hold foreign-keys can use the `Field` option. Changing these two edges to `Unique` should solve the problem.

**Comment by Locter9001** [comment]
> Hey @Locter9001 👋🏻
> 
> Only schemas the hold foreign-keys can use the `Field` option. Changing these two edges to `Unique` should solve the problem.

okay, it's worked, but I found another error.


uhm, I just don't want the foreign keys to work in a weird way, is there a better document that explains ent's foreign key work mode? I'm seeing a lot of extra messed up fields in the created database file
