### ISSUE TITLE
Proposal: third-party schema integrations (swagger, grpc) 

### ISSUE THREAD

**Issue by covrom** [ent/ent#367]
With schema we can generate swagger specification.

**Comment by a8m** [comment]
Hey @covrom, and thanks for raising up this issue. 
We had discussion about it before, and I'd be happy to see such integration.  However, this issue belongs to `ent-contrib` and directly to `entc. See [my comment](https://github.com/facebookincubator/ent/issues/357#issuecomment-590079537) about gqlgen integration.

I'll move this issue to the new repo once it's out.

**Comment by aca** [comment]
@covrom 
As ent schema generates struct type. You might want to check [kin-openapi](https://github.com/getkin/kin-openapi).
Example, https://github.com/aca/go-restapi-boilerplate/blob/master/spec/ent_to_components.go

**Comment by nemith** [comment]
Is there a way to generate non-go files (i.e. protobufs) with the template engine (or at least iterate through the nodes and edges to do manual generation?)

**Comment by a8m** [comment]
Hey Brandon! Nice to see you again 😃 

> Is there a way to generate non-go files (i.e. protobufs) with the template engine (or at least iterate through the nodes and edges to do manual generation?)

Yes, as I commented in https://github.com/facebook/ent/issues/780#issuecomment-695038170, you can do something as follows:

```go
package main

import (
	"log"
	"os"
	"text/template"

	"github.com/facebook/ent/entc"
	"github.com/facebook/ent/entc/gen"
)

var tmpl = template.Must(template.New("prototmpl").
	Parse(`
{{ range $n := $.Nodes }}
	message {{ $n.Name }} {
		{{- range $i, $f := $n.Fields }}
			// TODO: use func to covert a field-type to a proto-type.
			// {{ $f.Type }} {{ $f.Name }} = {{ $i }}
		{{- end }}
	}
{{ end }}
`))

func main() {
	path := "./ent/schema"
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	graph, err := entc.LoadGraph(path, &gen.Config{})
	if err != nil {
		log.Fatalln(err)
	}
	// Custom codegen logic goes here:
	if err := tmpl.Execute(os.Stdout, graph); err != nil {
		log.Fatalln(err)
	}
}
```

Of course, this is just a toy example, so let me know if you need help with implementing such thing.

**Comment by rotemtam** [comment]
I've started working on a suggestion for proto/grpc interop with ent. Documenting my thoughts in #1283. Will appreciate feedback @covrom @nemith

**Comment by masseelch** [comment]
With having `entoas` and `entproto` in [ent/contrib](https://github.com/ent/contrib) and [`ogent`](https://github.com/ariga/ogent) I feel like this issue can be closed.

Feel free anyone, if you think otherwise.
