### ISSUE TITLE
`strconv.Atoi: parsing "conversation": invalid syntax` upon item creation

### ISSUE THREAD

**Issue by Breigner01** [ent/ent#3674]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Basically, when I try to create an object in my database, it gives me the following error `strconv.Atoi: parsing "conversation": invalid syntax`

## Expected Behavior 🤔

I would expect the object to be created.

## Steps to Reproduce 🕹

conversation schema:
```go
package schema

import (
    "entgo.io/ent"
    "entgo.io/ent/schema/edge"
    "entgo.io/ent/schema/field"
    "time"
)

// Conversation holds the schema definition for the Conversation entity.
type Conversation struct {
    ent.Schema
}

// Fields of the Conversation.
func (Conversation) Fields() []ent.Field {
    return []ent.Field{
        field.Time("created_at").
            Default(time.Now),
        field.Time("updated_at").
            Default(time.Now),
    }
}

// Edges of the Conversation.
func (Conversation) Edges() []ent.Edge {
    return []ent.Edge{
        edge.From("users", User.Type).
            Ref("conversations"),
        edge.To("chats", Chat.Type),
    }
}
```
chat schema:
```go
package schema

import (
    "entgo.io/ent"
    "entgo.io/ent/schema/edge"
    "entgo.io/ent/schema/field"
    "time"
)

// Chat holds the schema definition for the Chat entity.
type Chat struct {
    ent.Schema
}

// Fields of the Chat.
func (Chat) Fields() []ent.Field {
    return []ent.Field{
        field.Text("message").
            MaxLen(1024),
        field.Time("created_at").
            Default(time.Now),
    }
}

// Edges of the Chat.
func (Chat) Edges() []ent.Edge {
    return []ent.Edge{
        edge.From("conversation", Conversation.Type).
            Ref("chats").
            Unique(),
        edge.From("sender", User.Type).
            Ref("sent_chats").
            Unique(),
    }
}
```
I fetch a conversation like so:
```go
        client.Conversation.
        Query().
        Where(conversation.ID(id)).
        WithUsers().
        Only(context.Background())
```
And when I try to create a chat with the fetched conversation like so:
```go
        client.Chat.
        Create().
        SetSender(sender).
        SetConversation(conversation).
        SetMessage(message).
        Save(context.Background())
```
I get the following error:
```
strconv.Atoi: parsing "conversation": invalid syntax
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.20.7  |
| Ent         | 0.12.3  |
| Database    | PostgreSQL   |
| Driver      | github.com/lib/pq |

**Comment by a8m** [comment]
Hey @Breigner01 👋🏻

Can you please provide a reproducible example using https://github.com/ent/bug? Thanks

**Comment by Breigner01** [comment]
After 2 days trying to reproduce this bug, I cannot manage to reproduce it.
This is what I did: [Atoi Failed Bug Reproduction](https://github.com/InstantIT/atoi-error)

If you can tell me what stuff I may have done wrong to cause this issue I would be really appreciative but this is as close as I could get to what I have in my program without including the whole gin part.

So I'm kinda at a loss there getting frustrated alone because I can't reproduce a bug even when copy pasting the code that I use.

**Comment by Breigner01** [comment]
By the way,
I don't know if this is relevant but my program is running in docker.
In theory in shouldn't change anything but idk at this point, I'm trying to find the one thing that's causing this issue and this is one of the differences with the attempted bug reproduction.
I'll dockerize it right away to try it out but I'm not hoping it'll fix anything.

**Comment by Breigner01** [comment]
Well the small test code had been dockerized but it doesn't reproduce the error, so I guess that was for nothing.

**Comment by Breigner01** [comment]
So, I just found where the bug is.
It actually comes from a hook that I didn't setup correctly.
