### ISSUE TITLE
Doc doesn't explain setters for nillable fields

### ISSUE THREAD

**Issue by willfaught** [ent/ent#3677]
For a nillable field X, apparently a SetNillableX method is generated, but that's not specified in the doc. I assumed SetX(*T) was generated. If there's a SetNillableX(*T), then is there a SetX(T) too?

See https://github.com/ent/ent/blob/91c7fcc685042647263d190dda08587246e2a4e7/doc/md/schema-fields.mdx#L576-L581

**Comment by a8m** [comment]
Hey @willfaught 👋🏻

There are many other methods that are also not mentioned in the doc, but still generated by the codegen. However, all public methods are generated with godoc comments. 

`SetNillable<F>` were added to reduce the amount of nil checks in create/update builders for optional fields (or some with default values) when receiving dynamic inputs from clients (e.g., GraphQL mutations).

Check out the godoc for how to use this: https://github.com/ent/ent/blob/master/examples/start/ent/car_create.go#L47

**Comment by willfaught** [comment]
Right, so part of this issue is a suggestion to document what methods are generated in the website documentation.
