### ISSUE TITLE
Doc: Unique method name on edges is confusing

### ISSUE THREAD

**Issue by willfaught** [ent/ent#3678]
https://github.com/ent/ent/blob/91c7fcc685042647263d190dda08587246e2a4e7/doc/md/schema-edges.mdx#L109-L110

There's a Unique method on fields that adds a unique constraint, but the Unique method on edges does something entirely different. This is confusing. This should at least be called out more here, but I think ideally a different name should be used, like Single().

**Comment by a8m** [comment]
Hey! Thanks for the feedback, @willfaught.

Unfortunately, this name is not going to change, as it’s used by numerous amount of projects these days. For simple guides on to model the different traditional relationships, use this section: https://entgo.io/docs/schema-edges#relationship

**Comment by willfaught** [comment]
Could it be changed in the next major version?

**Comment by a8m** [comment]
Not really. Ent maintains backwards compatible API since its first version.
