### ISSUE TITLE
Sensitve() not working with time types

### ISSUE THREAD

**Issue by irg1008** [ent/ent#3683]
Hi just a quick question, maybe I am missing something.

I am trying to hide a `field.Time` in my fields with Sensible() like I am able to do with string fields.
It says is not implemented and using `StructTag("-")` does not work either.

So I am wondering if it's not related to end and It's something not available in general.

Example:

```Go
// Fields of the User.
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("email").Unique(),
		field.String("password").Sensitive(),
		//                     ↘️ Undefined for `field.Time`
		field.Time("created_at").Sensitive().Default(time.Now).Immutable(),
	}
}
``` 

Thank you and sorry if it comes a bit as a noob question (new to Go) 💖

**Comment by a8m** [comment]
Hey, @irg1008! The `StructTag` should be set to specific tag. In your case, `json`. 
```go
StructTag(`json:"-"`)
```

**Comment by irg1008** [comment]
First of all, thank you for the fast reply

As I mentioned:
> It says is not implemented and using StructTag("-") does not work either.

It does not work whe using StructTag instead of Sensitive. That's why I am wondering whre the issue may lay.

**Comment by irg1008** [comment]
OMG I am an idiot. Forgot to generate the schemas.

Yep, sorry to lose your time
