### ISSUE TITLE
"default" with a reference to "id'

### ISSUE THREAD

**Issue by wxmeng04** [ent/ent#3687]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I create a `User` table with an autoincremented `id`. In the same table, there is a column `created_by` defaults to the `id` at the same row. The SQL in Postgres looks like below. It's not complicated, but seems difficult to implement in ent.
```
CREATE SEQUENCE "user_id_seq" AS int8;
CREATE TABLE "user" (
	"id" int8 NOT NULL DEFAULT nextval('user_id_seq'::regclass),
	"name" VARCHAR(23) DEFAULT 'user name' NOT NULL,
	"create_time" TIMESTAMPTZ(6) DEFAULT now() NOT NULL,
	"update_time" TIMESTAMPTZ(6) DEFAULT now() NOT NULL,
	"is_deleted" BOOL DEFAULT false NOT NULL,
	"created_by" INT8 NOT NULL DEFAULT currval('user_id_seq'),
	"updated_by" INT8 NOT NULL DEFAULT currval('user_id_seq'),
	CONSTRAINT "pk_user" PRIMARY KEY ("id")
);
ALTER SEQUENCE "user_id_seq" OWNED BY "user"."id";
```
## Motivation 🔦
I just want to use a basic autoincremented column and then have an reference to it when insert a row. Do I have to insert a record first and then update the `create_at` field?

**Comment by wxmeng04** [comment]
Take the `updated_by` column for example. It's quite useful when the user information can be updated by an administrator. It seems `sequence` is not supported.

**Comment by a8m** [comment]
Hey @wxmeng04 👋 

You can use the `entsql.DefaultExpr` annotation to set this. See: https://github.com/ent/ent/blob/master/dialect/entsql/annotation.go#L195

**Comment by a8m** [comment]
Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by wxmeng04** [comment]
Unfortunately, the problem is still not solved. I tried to write the expression like below.
**case 1**
```
		field.Int64("created_by").
			Annotations(
				entsql.DefaultExpr("currval('user_id_seq'::regclass)"),
			).
			Immutable(),
```
** case 2**
```
		field.Int64("created_by").
			Annotations(
				entsql.DefaultExpr("id"),
			).
			Immutable(),
```
The same error appears with a message:
```
schema creation failed: {"error": "sql/schema: create \"user\" table: ERROR: cannot use column reference in DEFAULT expression (SQLSTATE 0A000)"}
```
Is there any special syntax of the DefaultExpr?

**Comment by a8m** [comment]
It looks like it is not supported by the database engine. What `CREATE` statement do you want to generate?

**Comment by wxmeng04** [comment]
I found the problem. I forgot to update another reference to column `id`. The column is not allowed to be referenced directly but sequence is allowed. The below code works but have to rely on some default behavior of the database. It's assumed the sequence used by `id` is named as `user_id_seq`.  Normally I will declare the sequence explicitly. It would be more user-friendly to document some examples like this.
```
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.Int64("id").
			Immutable(),
		field.Time("create_time").
			Default(time.Now).
			Immutable(),
		field.Time("update_time").
			Default(time.Now).
			UpdateDefault(time.Now),
		field.Int64("created_by").
			Annotations(
				entsql.DefaultExpr("currval('user_id_seq'::regclass)"),
			).
			Immutable(),
		field.Int64("updated_by").
			Annotations(
				entsql.DefaultExpr("currval('user_id_seq'::regclass)"),
			),
		field.Bool("is_deleted").
			Default(false),
	}
```

**Comment by wxmeng04** [comment]
New problem: 
When the program reachs below during restart, error occures.
```
if err = csql.Schema.Create(context.Background()); err != nil {
```
Below is the error:
```
"sql/schema: ERROR: currval of sequence \"user_id_seq\" is not yet defined in this session (SQLSTATE 55000)"
```
The engine I'm using is "github.com/jackc/pgx/v5/stdlib"

**Comment by hicker-kin** [comment]
@a8m  your [Discord community](https://discord.gg/qZmPgTE6RX) unable to accept invitation
