### ISSUE TITLE
How to create edge without using database foreign key ?

### ISSUE THREAD

**Issue by minicloudsky** [ent/ent#3691]
I want to use ent manage my entity without using Edges generated database foreign key,How can I define my entity ?

- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

User、Car、UserCar
```go
// Fields of the User.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.Int("age").
            Positive(),
        field.String("name").
            Default("unknown"),
    }
}

// Fields of the Car.
func (Car) Fields() []ent.Field {
    return []ent.Field{
        field.String("model"),
        field.Time("registered_at"),
    }
}

// t_user_car
func (UserCar) Fields() []ent.Field {
    return []ent.Field{
        field.Int("user_id").
            Positive(),
        field.Int("car_id").
            Positive(),
    }
}
```
I hope to create a UserCar Model as Edges, not use the following Edges
```go
// Edges of the User.
func (User) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("cars", Car.Type),
    }
}
```
what should I do to slove the problem ? foreign keys in mysql is negative when inserting、updating、deleting，so i hope to Use the middle table t_user_car manage the relationship between Use and Car, Is it possible in Ent ?

**Comment by wxmeng04** [comment]
As far as I know, ent must depend on the foreign key for edges. Just remove the `Edges` in your code in the schema definition. And then implement the logic in your own code. This is what I do currently.

**Comment by Amenomori** [comment]
May refer to [migrate/#foreign-keys](https://entgo.io/docs/migrate/#foreign-keys)?

**Comment by minicloudsky** [comment]
> migrate/#foreign-keys

thanks，I will try it  by self implement foreign key logics ~

**Comment by wxmeng04** [comment]
> > migrate/#foreign-keys
> 
> thanks，I will try it by self implement foreign key logics ~

That's it. However it may be execellent to auto-generate codes implementing logics without foreign keys, cascading ... It must be difficult as well to implement in ORM.

**Comment by minicloudsky** [comment]
> > > migrate/#foreign-keys
> > 
> > 
> > thanks，I will try it by self implement foreign key logics ~
> 
> That's it. However it may be execellent to auto-generate codes implementing logics without foreign keys, cascading ... It must be difficult as well to implement in ORM.

yes, auto-generate perhaps have standard mappings, for example, generate from table name to a middle table ,with two unique keys table_name_a_id, table_name_b_id
