### ISSUE TITLE
BETWEEN & NOT BETWEEN

### ISSUE THREAD

**Issue by mkohlhaas** [ent/ent#3700]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

`dialect/sql/sql.go` does not provide `Between` and `NotBetween` selectors for fields.

Should behave like the corresponding standard SQL statements.

## Motivation 🔦

Necessary to find records for which a field is not in a number range.

**Comment by wxmeng04** [comment]
You can use the Where function like below:
```
	projs, err := sqlCli.Project.Query().Where(
		project.And(project.OwnerIDGT(1),
			project.OwnerIDLT(100),
			project.OwnerIDNotIn(20, 30),
		),
	).All(context.Background())
```

**Comment by mkohlhaas** [comment]
Was more thinking of something like:

```golang
n, err := client.Post.
    Query().
    Where(post.NumComments.Between(1,10)).
    All(ctx)
```

**Comment by wxmeng04** [comment]
> Was more thinking of something like:
> 
> ```go
> n, err := client.Post.
>     Query().
>     Where(post.NumComments.Between(1,10)).
>     All(ctx)
> ```

As far as I know, it's not supported. If you can use other condition to implement the same logic, don't spend too much time on this. It makes no difference of runtime efficiency.

**Comment by mkohlhaas** [comment]
I don't care too much about runtime performance. More about code readability.
