### ISSUE TITLE
Prisma schema support

### ISSUE THREAD

**Issue by listepo** [ent/ent#3713]
It would be nice to be able to use a [Prisma schema](https://www.prisma.io/docs/concepts/components/prisma-schema) for code generation as an alternative way to describe a schema.
Original support is either not planned or with a very low priority.

**Comment by a8m** [comment]
Hey @listepo 👋 

Thanks for the proposal, but unfortunately we don't plan to support this as we don't have any use case or a need for this. However, this can be implemented externally using the [codegen extensions/plugins](https://entgo.io/docs/extensions). 

You're welcome to join our [Discord](https://discord.gg/qZmPgTE6RX) if you need help or guidance on how to implement such thing.

**Comment by listepo** [comment]
Hey @a8m, thanks for the feedback
