### ISSUE TITLE
Config file for code generation

### ISSUE THREAD

**Issue by wxmeng04** [ent/ent#3716]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
It would be convenient if there is a configuration file for code generation.

## Motivation 🔦
I found many function have to be acheived by righting extra code. For example, it requires to write codes to elide the `omitempty`. The code is not long but you have to find where to place the codes and how to make it work. Another exampe is that you must denote using postgres here and there by `b := sql.Dialect(dialect.Postgres)`. This actualy can be globally specified and also applied to `ent.Client`. In most use cases, you are going to play with one type of database.
Is it possible to have a default global configuration file generated in `/ent/schema` directory after excution of `ent init xxxx`? Users may or may not change the default configuration file after. The code can be generated based on the global setting without writing extra in business codes. User can also check which is configurable by reviewing the default configuration file. It will make the ORM much easier to study and more efficeintly to work with. 
Just some suggestion from user point of view. It may be difficult to acheive and a disaster for the project maintainer.

I have been using `ent` for two weeks. Thanks for the community's contribution!

**Comment by a8m** [comment]
Hey @wxmeng04 👋🏻
We use Go for configuration, both for the schema or codegen. See: https://entgo.io/docs/code-gen#use-entc-as-a-package

Regarding the dialect - custom predicates or modifiers don’t need to set the dialect. If you still create builders that need to be configured, the dialect is exposed on the root query using the `Dialect()` method - it is a runtime parameter, and not a config parameter.

**Comment by wxmeng04** [comment]
Noted. I will try to learn configuring with `Hook`. Frankly speeking I will try to avoid using `Hook` if there is other way out.
