### ISSUE TITLE
conversion between ent.Tx and dialect.Tx 

### ISSUE THREAD

**Issue by wxmeng04** [ent/ent#3728]
How can I convert ent.Tx to dialect.Tx and vice versa? I tried to convert as below but failed due to interface not compatible. I found a similar issue #3583 but it seems not resolved.
```
       var cli *ent.Client
       var sqlDrv *sql.Driver
	tx, err := cli.Tx(ctx)
	tx1, err := sqlDrv.BeginTx(ctx,nil)
        // if any one of below works, it's ok!
	tx2 := tx.(sql.Tx)                                          // report interface not implemented
	execQuerier := tx.Client().(sql.ExecQuerier)                        // report interface not implemented
	execQuerier1 := tx.(sql.ExecQuerier)                                  // report interface not implemented
       // or can derive tx from tx1
```
How can I mix usage of ent.Tx and dialect.Tx in the same transaction?

**Comment by crossworth** [comment]
Hello, I think you are getting things mixed up.

- `ent.Tx` is a transactional client.
- `dialect.Tx` is what is returned when you start a transaction with `dialect.Driver`, it represents what should be present in the struct returned when starting a transaction.

Now if you look at the source code, it will see that `dialect.Driver`, `dialect.Tx` are interfaces and are only used by the **driver** of the client.

If you want to handle the operations manually, you need to get the driver first (and handle all possible edge cases, like drivers that wrap another drivers and difference between drivers). To get to the driver you can add a new file on the ent directory (in your project).

See this link for more info: https://github.com/ent/ent/issues/3147#issuecomment-1339423938

With all that said, this seems to be a [XY Problem](https://xyproblem.info/), seems like you want to access the database to do operations on `Exec` and `Query`, Ent has a feature flag for it, [SQL Raw API](https://entgo.io/docs/feature-flags/#sql-raw-api).

For most of the cases it should be enough, I think you will only need to work with drivers when implementing a new dialect, doing custom query inspections or caching strategies.

Please, ask questions like this on [Ent Discord](https://discord.com/invite/qZmPgTE6RX), there are many more people that use discord and monitor it that are able to help you there.

**Comment by wxmeng04** [comment]
> Hello, I think you are getting things mixed up.
> 
> * `ent.Tx` is a transactional client.
> * `dialect.Tx` is what is returned when you start a transaction with `dialect.Driver`, it represents what should be present in the struct returned when starting a transaction.
> 
> Now if you look at the source code, it will see that `dialect.Driver`, `dialect.Tx` are interfaces and are only used by the **driver** of the client.
> 
> If you want to handle the operations manually, you need to get the driver first (and handle all possible edge cases, like drivers that wrap another drivers and difference between drivers). To get to the driver you can add a new file on the ent directory (in your project).
> 
> See this link for more info: [#3147 (comment)](https://github.com/ent/ent/issues/3147#issuecomment-1339423938)
> 
> With all that said, this seems to be a [XY Problem](https://xyproblem.info/), seems like you want to access the database to do operations on `Exec` and `Query`, Ent has a feature flag for it, [SQL Raw API](https://entgo.io/docs/feature-flags/#sql-raw-api).
> 
> For most of the cases it should be enough, I think you will only need to work with drivers when implementing a new dialect, doing custom query inspections or caching strategies.
> 
> Please, ask questions like this on [Ent Discord](https://discord.com/invite/qZmPgTE6RX), there are many more people that use discord and monitor it that are able to help you there.

Thank you so much!

**Comment by wxmeng04** [comment]
Just summary how I solved the problem.
I added `gen.FeatureExecQuery` in the generate opts.
```
	err := entc.Generate(
		"./schema",
		&gen.Config{
			Hooks: []gen.Hook{
				JsonTag,
				RedisTag,
			},
			Features: []gen.Feature{
				gen.FeatureUpsert,
				gen.FeatureExecQuery,
			},
			Templates: []*gen.Template{
				gen.MustParse(
					gen.NewTemplate("txdriver").
						ParseFiles("template/txdriver.tmpl"),
				),
			},
		},
	)
```

Now I can exec sql via below two functions and Meantime I can use `tx.User.Create(), tx.User.Update() ...` as well.
```
tx.QueryContext()
tx.ExecContext()
```
