### ISSUE TITLE
Postgres 16 removed lc_collate and lc_ctype

### ISSUE THREAD

**Issue by Gebes** [ent/ent#3750]
Postgres 16 removed two system read only parameters, causing the setup to error on the master branch:

postgres: unexpected number of rows: 1

During the setup following query is causing the issue:
```sql
SELECT name,setting FROM pg_settings WHERE name IN ('lc_collate', 'lc_ctype', 'server_version_num', 'crdb_version') ORDER BY name DESC
```

https://www.postgresql.org/docs/current/release-16.html
> Remove read-only server variables lc_collate and lc_ctype (Peter Eisentraut)

What is the state on this?

**Comment by a8m** [comment]
Thanks for reporting this, @Gebes.
