### ISSUE TITLE
Atlas Inspect Schema Throwing Error

### ISSUE THREAD

**Issue by vrajeshprakhya** [ent/ent#3759]
Trying to run this command to inspect ent schema: 
atlas schema inspect   -u "ent://ent/schema/"   --dev-url "sqlite://file?mode=memory&_fk=1"   --format '{{ sql . "  " }}'

I am getting this error: 
Error: template: format:1:3: executing "format" at <sql . "  ">: error calling sql: create table "events": sqlite: unsupported type: ""

Anyonee know what the root cause might be ?

This is how my schema for events.go looks:

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/proj/ent-api/utils"
)

// Event holds the schema definition for the Event entity.
type Event struct {
	ent.Schema
}

// Fields of the Event.
func (Event) Fields() []ent.Field {
	return []ent.Field{
		field.String("title").
			Default(""),
		field.Other("duration", utils.Duration(0)).
			SchemaType(map[string]string{
				dialect.Postgres: "bigint",
			}),
		field.String("description").
			Default(""),
		field.String("location").
			Default("Remote"),
		field.Bool("allDay").
			Default(false),
		field.Int("views").
			Default(0).
			Min(0),
		field.Int("uses").
			Default(0).
			Min(0),
	}
}

// Edges of the Event.
func (Event) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("metadata", Post.Type).
			Ref("events").
			Unique().
			Required(),
		edge.From("user", user.Type).
			Ref("components"),
		edge.To("schedulings", Scheduling.Type),
	}
}

**Comment by crossworth** [comment]
Hello, I think your field `duration` does not have a `SchemaType` for SQLite, try define it:

```go
field.Other("duration", utils.Duration(0)).
	SchemaType(map[string]string{
		dialect.Postgres: "bigint",
		dialect.SQLite:   "bigint",
	}),
```

**Comment by a8m** [comment]
@crossworth is right. Alternatively, you can use `docker://postgres` dev-url for inspection. 

Closing, but feel free to reopen if you still need help.
