### ISSUE TITLE
Question: Order by edge field

### ISSUE THREAD

**Issue by fitzix** [ent/ent#378]
This may be a duplicate question, but I didn't find any useful help in #227.

The join table operation is a very common and useful function of the database.The order by edge field requires the join table, but ent does not support this operation.

For example, users and cards have O2O relationship. How can I query the user list 
`WHERE user.name LIKE %keyword% ORDER BY card.created_at ASC LIMIT 10`.

Is there any good suggestions? Maybe I should use raw sql.

```go
// Fields of the user.
func (User) Fields() []ent.Field {
    return []ent.Field{
        field.Int("age"),
        field.String("name"),
}

// Edges of the user.
func (User) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("card", Card.Type).
            Unique(),
    }
}

// Fields of the card.
func (Card) Fields() []ent.Field {
    return []ent.Field{
        field.String("name"),
        field.Time("created_at").Default(time.Now),
    }
}

// Edges of the Card.
func (Card) Edges() []ent.Edge {
    return []ent.Edge{
        edge.From("owner", User.Type).
            Ref("card").
            Unique().
            Required(),
    }
}
```

**Comment by a8m** [comment]
> The join table operation is a very common and useful function of the database.The order by edge field requires the join table, but ent does not support this operation.

`ent` doesn't provide an API for joining and scanning results into arbitrary structures. 

Maybe we want to add this (or maybe not), but we need to propose and discuss about it before. `ORDER BY` is just another option in this new functionality. 

IMO, if we ever decide to provide such API, it should be an extension of the SQL dialect, and not something global.

Right now, we are focused on V1, so I'm not sure how much capacity we have for this.

**Comment by a8m** [comment]
Hey @fitzix, I added 2 sections on the doc about how to order by an edge or a custom-logic if the first one is not enough.
Please see [edge-ordering](https://entgo.io/docs/paging/#edge-ordering) and [custom-ordering](https://entgo.io/docs/paging/#custom-ordering) in our website.

Closing, and thanks for opening this issue.
