### ISSUE TITLE
Error while generating schema: panic: template: decode.tmpl:19: unexpected " " in in {{continue}}

### ISSUE THREAD

**Issue by tidyrisetools** [ent/ent#3781]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

We migrated from version 0.11.5 to 0.12.4 and post migration, schema generation if failing with following error:

go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/upsert ./ent/schema
panic: template: decode.tmpl:19: unexpected " " in in {{continue}}

goroutine 1 [running]:
entgo.io/ent/entc/gen.MustParse(...)
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/gen/template.go:339
entgo.io/ent/entc/gen.initTemplates()
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/gen/template.go:225 +0x670
entgo.io/ent/entc/gen.(*Graph).templates(0x140005c4d00)
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/gen/graph.go:879 +0x2c
entgo.io/ent/entc/gen.generate(0x140005c4d00)
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/gen/graph.go:225 +0x30
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x5?, 0x8?)
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/gen/graph.go:143 +0x2c
entgo.io/ent/entc/gen.(*Graph).Gen(0x140005c4d00)
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/gen/graph.go:216 +0xa0
entgo.io/ent/entc.generate({0x16bddf51f, 0xc}, 0x140001925a0?)
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/entc.go:389 +0x84
entgo.io/ent/entc.Generate({0x16bddf51f, 0xc}, 0x140001d0600, {0x140003e9cb8, 0x2, 0x0?})
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/entc/entc.go:86 +0x1ac
entgo.io/ent/cmd/internal/base.GenerateCmd.func1(0x140004a9200?, {0x140004ab020, 0x1, 0x3?})
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/cmd/internal/base/base.go:190 +0x238
github.com/spf13/cobra.(*Command).execute(0x140004a9200, {0x140004aaf90, 0x3, 0x3})
        /Users/xyz/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5dc
github.com/spf13/cobra.(*Command).ExecuteC(0x140004a8900)
        /Users/xyz/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/xyz/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /Users/xyz/go/pkg/mod/entgo.io/ent@v0.12.4/cmd/ent/ent.go:24 +0xc0
exit status 2

## Expected Behavior 🤔

Schema has to be generated without any issues

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18  |
| Ent         | 0.12.4   |
| Database    | PostgreSQL

**Comment by a8m** [comment]
Hey @tidyrisetools,
Ent supports the latest two Go versions. Currently, 1.20 and 1.21. Please, upgrade your local Go version and reopen this issue if you still encounter any problems.
