### ISSUE TITLE
High memory usage when compiling ent-generated files.

### ISSUE THREAD

**Issue by udit9576** [ent/ent#3814]
## Current Behavior 😯
When Ent generates models/entities for the schema, it creates them in a single directory and the go compiler compiles the same in a single process. When the ent-generated files are being compiled, it takes a lot of memory and time.

Having defined schema for around 300 tables, no. of files generated is proportionally large and the go compiler takes a lot of time and memory to compile, even causing the server to go out of memory sometimes.

## Your Environment 🌎
Current Server Configuration: 8Gib RAM

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.19  |
| Ent         | 0.12.3   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql       |

**Comment by a8m** [comment]
Hey @udit9576 👋 

> Having defined schema for around 300 tables, no. of files generated is proportionally large and the go compiler takes a lot of time and memory to compile, even causing the server to go out of memory sometimes.

Thanks for reporting this. I haven't encountered such a failure before, even though we built Ent for projects with more than this number of schemas (and actually used it). But I guess that in some environments it's possible, especially when the number of dependencies is high. 

I have plans to support one `generated.go` file for the `ent/` directory, but it's not on my desk atm. To unblock yourself, you can use/write a codegen hook to process the files and squash them into one file. See: https://entgo.io/docs/code-gen#code-generation-hooks

**Comment by udit9576** [comment]
Tried squashing the generated files into one generated.go file, but I am still facing the same issue. Can you please provide me with an alternative solution for the same.

**Comment by mkraft** [comment]
@udit9576 Did you ever resolve your issue?
