### ISSUE TITLE
Code generation fails with error "error calling TableSchemas: atlas: missing schema annotation for node "XXXX" "

### ISSUE THREAD

**Issue by mortezaalizadeh** [ent/ent#3831]
I have been using entgo version 0.12.4 for a while until this morning when I upgraded to the latest version 0.12.5 and since then code generation has been failing with the following error:

2023/11/16 19:34:16 running ent codegen: execute template "client": template: client.tmpl:498:6: executing "client" at <xtemplate $tmpl $>: error calling xtemplate: template: schemaconfig.tmpl:204:15: executing "dialect/sql/config/options/multischema" at <$.TableSchemas>: error calling TableSchemas: atlas: missing schema annotation for node "BillingCustomer"
exit status 1
generate.go:3: running "go": exit status 1

![image](https://github.com/ent/ent/assets/3070738/79fcf5c2-de29-41b3-a005-bf5f361fa2be)

It looks like the recent change introduced in this PR is a breaking change: https://github.com/ent/ent/pull/3821

https://github.com/ent/ent/blob/77eedb01ddc9e44e660b25434460224c76b0f1f1/entc/gen/storage.go#L190

Any idea how to fix this? Thank you.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Should generate code as it used to

## Expected Behavior 🤔

It is failing to generate code

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| OS          | Linux PopOS 22.04  |
| Go          | 1.21.3  |
| Ent         | 0.12.5   |
| Database    | Postgres   |
| Driver      | https://github.com/jackc/pgx/v5        |

**Comment by a8m** [comment]
Hey @mortezaalizadeh, what feature-flags do you currently use in your project?

**Comment by mortezaalizadeh** [comment]
All of them

![image](https://github.com/ent/ent/assets/3070738/860d3daf-fd74-4eb6-972a-bf80a766a891)

**Comment by a8m** [comment]
Thanks for the info. Can you please update to the `@master` version and report if that resolves your issue?

**Comment by mortezaalizadeh** [comment]
@a8m  that definitely fixed the issue, cheers
