### ISSUE TITLE
Website: Typo in the simple-cms-with-ent (https://entgo.io/blog/2023/02/23/simple-cms-with-ent)

### ISSUE THREAD

**Issue by jeasoft** [ent/ent#3836]
Hi everyone! Thanks for your job working in this excellent library/package. I'm relatively new in Go and Ent (like 3 hours XD).

## Current Behavior 😯
Well, while following a post published in the website I checked the is a typo in the https://entgo.io/blog/2023/02/23/simple-cms-with-ent#step-1-setting-up-the-database-schema, specifically in the post.go source code where the function for the posts edges is commented.   

The function has to be uncommented and be a part of the actual code.

## Steps to Reproduce 🕹
Because is part of the website you can see this behavior in the website right now: https://entgo.io/blog/2023/02/23/simple-cms-with-ent#step-1-setting-up-the-database-schema

Well, I think do a PR to help with this, hopefully, this can help other guys who are beginning to use Ent in the future without issues. 
cc @rotemtam

**Comment by a8m** [comment]
Thanks for reporting and feel free to send a patch to fix this 🙏🏻
