### ISSUE TITLE
Move away from the non-free Calibre font

### ISSUE THREAD

**Issue by CyrilBrulebois** [ent/ent#3845]
Hi,

While your project comes under a free license, it ships proprietary fonts under `doc/website/src/font/`. I'm not familiar with font-related topics but a quick search suggests [Carlito](https://fonts.google.com/specimen/Carlito/about?query=carlito) could be a suitable replacement.

Thanks for considering!

Cyril.

**Comment by a8m** [comment]
Hey @CyrilBrulebois 👋 

This font comes with Docusaurus, so I'd be surprised if it's a non-free font. Do you have any official information about this?

**Comment by CyrilBrulebois** [comment]
OK, let me backpedal a bit.

It seems like I managed to fumble my search for Calibre information and got Calibri instead (and Carlito as a possible replacement), sorry about that.

Calibre-with-an-e is not a Microsoft font (which would be covered by their restrictive font FAQ), but can apparently be found here: https://klim.co.nz/retail-fonts/calibre/ and it doesn't seem like any of the options at https://klim.co.nz/faqs/#licensing is free.

Since I'm still not a font expert, I've looked at various tools handling the WOFF format, and converting via `woff2sfnt` led me to those strings:

> http://www.klim.co.nz/licensing.php
> © 2011 Klim Type Foundry. All rights reserved.
> Calibre is either a registered trademark or a trademark of 2011 Klim Type Foundry in New Zealand and/or other countries.

This can also be checked by opening one of the font files in FontForge.
![Element > Font Info](https://github.com/ent/ent/assets/8861145/6a28f137-51b4-4d2e-8f05-9c998528f7e9)

**Comment by a8m** [comment]
Thank you for the comment, @CyrilBrulebois. I rechecked and found that this was actually added by us as part of the Meta (Facebook) homepage design, as we had (and they have today) a license for this font. I have decided to remove it, as it's not needed in my opinion and I no longer have access to this license. Thanks!

**Comment by a8m** [comment]
Closed with https://github.com/ent/ent/pull/3846

**Comment by CyrilBrulebois** [comment]
Thank you, @a8m!
