### ISSUE TITLE
I hope the Count api can be modified to be elegant and flexible like this: err := query.Count(ctx, *int)

### ISSUE THREAD

**Issue by miaojinsing** [ent/ent#3872]
I hope the Count api can be modified to be elegant and flexible like this: err := query.Count(ctx, *int)

- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by miaojinsing** [comment]
![image](https://github.com/ent/ent/assets/84968993/c0e95bd0-6d1a-4f67-8836-7c67d90d1ff9)

**Comment by a8m** [comment]
Thanks for the suggestion @miaojinsing, but the API can't be changed. You can use the `Select`+`Scan` / modifiers API to scan the count result into a different variable type.
