### ISSUE TITLE
How to retrieve all columns from all tables

### ISSUE THREAD

**Issue by jeanh0w** [ent/ent#3888]
![CleanShot 2024-01-05 at 20 10 52](https://github.com/ent/ent/assets/25869212/48ab9a75-0f81-4e3f-8e1e-6d52b4b32bfe)

The result type is ent.NetDeviceOperation, so I can only retrieve the NetDeviceOperation values. How can I retrieve the values of all columns from all tables?

**Comment by a8m** [comment]
Use eager-loading. See: https://entgo.io/docs/eager-load

Please, use the Discord community for such questions: https://discord.com/invite/qZmPgTE6RX
