### ISSUE TITLE
panic: go generate ./ent

### ISSUE THREAD

**Issue by gopherhiro** [ent/ent#3900]
panic: template: setter.tmpl:41: unexpected " " in in {{break}}

goroutine 1 [running]:
entgo.io/ent/entc/gen.MustParse(...)
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/gen/template.go:341
entgo.io/ent/entc/gen.initTemplates()
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/gen/template.go:227 +0x73b
entgo.io/ent/entc/gen.(*Graph).templates(0xc0000324c0)
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/gen/graph.go:905 +0x36
entgo.io/ent/entc/gen.generate(0xc0000324c0)
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/gen/graph.go:228 +0x3f
entgo.io/ent/entc/gen.GenerateFunc.Generate(0x1?, 0x1?)
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/gen/graph.go:143 +0x1f
entgo.io/ent/entc/gen.(*Graph).Gen(0xc0000324c0)
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/gen/graph.go:219 +0x96
entgo.io/ent/entc.generate({0x7ff7bfeff639, 0x8}, 0x50?)
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/entc.go:389 +0x92
entgo.io/ent/entc.Generate({0x7ff7bfeff639, 0x8}, 0xc0000de6c0, {0xc00041fcd0, 0x2, 0x0?})
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/entc/entc.go:86 +0x21f
entgo.io/ent/cmd/internal/base.GenerateCmd.func1(0xc00052d200?, {0xc00052e6b0, 0x1, 0x1?})
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/cmd/internal/base/base.go:190 +0x2af
github.com/spf13/cobra.(*Command).execute(0xc00052d200, {0xc00052e680, 0x1, 0x1})
	/Users/work/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00052c900)
	/Users/work/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/work/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	/Users/work/go/pkg/mod/entgo.io/ent@v0.12.5/cmd/ent/ent.go:24 +0xc5
exit status 2
ent/generate.go:3: running "go": exit status 1

**Comment by a8m** [comment]
Hey! Please see this: https://github.com/ent/ent/issues/3781#issuecomment-1752790604

> Ent supports the latest two Go versions. Currently, 1.20 and 1.21. Please, upgrade your local Go version and reopen this issue if you still encounter any problems.

**Comment by gopherhiro** [comment]
okk~ thanks！i will try ~
