### ISSUE TITLE
Codegen is creating duplicate functions

### ISSUE THREAD

**Issue by thegeekywanderer** [ent/ent#3911]
When defining edge schema as given below codegen is creating duplicate functions in create.go, update.go and mutation.go causing compile errors. Removing them manually makes the code work as expected. 

#### Edge Schemas
```go
// Edges of the Deployment.
func (Deployment) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("parent", Deployment.Type).
			Field("parent_id").
			Required().
			Unique().
			From("children"),
		edge.To("dependency", Deployment.Type).
			Through("dependencies", Dependency.Type),
		edge.To("artifact", Artifact.Type).
			Unique(),
		edge.To("cloud", Cloud.Type).
			Unique().
			Field("cloud_id").
			Required(),
	}
}
```

```go
// Edges of the Dependency.
func (Dependency) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("deployment", Deployment.Type).
			Required().
			Unique().
			Field("deployment_id"),
		edge.To("dependency", Deployment.Type).
			Required().
			Unique().
			Field("dependency_id"),
	}
}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

#### Generated duplicate functions:
- **deployment_create.go**
```go
// AddDependencyIDs adds the "dependencies" edge to the Dependency entity by IDs.
func (dc *DeploymentCreate) AddDependencyIDs(ids ...int) *DeploymentCreate {
	dc.mutation.AddDependencyIDs(ids...)
	return dc
}
```

- **deployment_update.go**
```go
// RemoveDependencyIDs removes the "dependencies" edge to Dependency entities by IDs.
func (duo *DeploymentUpdateOne) RemoveDependencyIDs(ids ...int) *DeploymentUpdateOne {
	duo.mutation.RemoveDependencyIDs(ids...)
	return duo
}
```
```go
// AddDependencyIDs adds the "dependencies" edge to the Dependency entity by IDs.
func (duo *DeploymentUpdateOne) AddDependencyIDs(ids ...int) *DeploymentUpdateOne {
	duo.mutation.AddDependencyIDs(ids...)
	return duo
}
```
```go
// RemoveDependencyIDs removes the "dependencies" edge to Dependency entities by IDs.
func (du *DeploymentUpdate) RemoveDependencyIDs(ids ...int) *DeploymentUpdate {
	du.mutation.RemoveDependencyIDs(ids...)
	return du
}
```
```go
// AddDependencyIDs adds the "dependencies" edge to the Dependency entity by IDs.
func (du *DeploymentUpdate) AddDependencyIDs(ids ...int) *DeploymentUpdate {
	du.mutation.AddDependencyIDs(ids...)
	return du
}
```
- **mutation.go**
```go
// AddDependencyIDs adds the "dependencies" edge to the Dependency entity by ids.
func (m *DeploymentMutation) AddDependencyIDs(ids ...int) {
	if m.dependencies == nil {
		m.dependencies = make(map[int]struct{})
	}
	for i := range ids {
		m.dependencies[ids[i]] = struct{}{}
	}
}
```
```go
// RemoveDependencyIDs removes the "dependencies" edge to the Dependency entity by IDs.
func (m *DeploymentMutation) RemoveDependencyIDs(ids ...int) {
	if m.removeddependencies == nil {
		m.removeddependencies = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.dependencies, ids[i])
		m.removeddependencies[ids[i]] = struct{}{}
	}
}
```
## Expected Behavior 🤔

If there is a logical mistake in my schema then codegen should throw an error instead of generating errored code. 

## Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.3  |
| Ent         | 0.12.5  |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by krisatverbidio** [comment]
Unless I'm missing something, the "duplicate" functions really aren't duplicate. They're receiver functions attached to different structs. For example, there is a `AddDependencyIDs` function for each of `DeploymentCreate`, `DeploymentUpdateOne`, `DeploymentUpdate`, and `DeploymentMutation`. While the code in the functions  is very similar or duplicate, they're working on different structs.

**Comment by thegeekywanderer** [comment]
There are two AddDependencyIDs in the same deployment update package. Which is what causes a compile time error. Similarly for the deployment create package there are again two AddDependencyIDs functions.

**Comment by krisatverbidio** [comment]
I'm still not seeing the duplicate. I see four in your copy and paste, and
they're attached to different receivers in the same package.

func (dc *DeploymentCreate) AddDependencyIDs(ids ...int) *DeploymentCreate {
func (du *DeploymentUpdate) AddDependencyIDs(ids ...int) *DeploymentUpdate {
func (duo *DeploymentUpdateOne) AddDependencyIDs(ids ...int)
*DeploymentUpdateOne {
func (m *DeploymentMutation) AddDependencyIDs(ids ...int) {

**Comment by krisatverbidio** [comment]
I'm still not seeing the duplicate. I see four in your copy and paste, and
they're attached to different receivers in the same package.

```
func (dc *DeploymentCreate) AddDependencyIDs(ids ...int) *DeploymentCreate {
func (du *DeploymentUpdate) AddDependencyIDs(ids ...int) *DeploymentUpdate {
func (duo *DeploymentUpdateOne) AddDependencyIDs(ids ...int)
*DeploymentUpdateOne {
func (m *DeploymentMutation) AddDependencyIDs(ids ...int) {
```

**Comment by thegeekywanderer** [comment]
Oh that is because I didn't add the duplicated functions here. I just mentioned which functions were duplicated. 
Anyways there might have been something wrong with my environment because now that I run it again go is not throwing errors at me pointing out duplicate functions.

**Comment by Aurelienbr96** [comment]
@thegeekywanderer I actually the same issue on my project. Do you remember the steps you have been through to solve this?
I guess it has to do with how I declared my Edges

**Comment by anryangelov** [comment]
@Aurelienbr96 This can happen if you forget to add .Field() in where discribe From edges
