### ISSUE TITLE
Create a record without needing to write every field line by line

### ISSUE THREAD

**Issue by Gantushig77** [ent/ent#3912]
When I create a database record I have to go through every field and write them down like this : 

![Screenshot 2024-01-20 at 11 27 49](https://github.com/ent/ent/assets/41037611/564c3146-4e5a-4087-81a0-b0c70b17752b)

I don't want to specify every field like this. Because I already validated all the possible field before the data reaches the CreateRecord function. I just want to pass all the data in a single variable and pass them to the function. Ent has update function that accepts a whole struct variable, I want something like that with the Create function. When using MongoDB, the mongoose have this kind of function that accepts a whole object. If it's possible, please implement this kind of function with SQL (Currently I am using PostgreSQL). 

![Screenshot 2024-01-20 at 11 28 10](https://github.com/ent/ent/assets/41037611/3bd04939-876a-4109-b9bc-41fbb57d2cd3)

- [ * ]  I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

Creating a record without writing down every field with the generated methods could save time. 

## Summary 💡

Ent is an amazing ORM. I would like to use it more in the future. The ent team did a great job. And I would like to see the it improving. And the feature I am requesting would greatly improve developer experience, I believe.

**Comment by rotemtam** [comment]
Solution documented here:

https://entgo.io/docs/faq#how-to-create-an-entity-from-a-struct-t

Closing, feel free to re-open if needed.

**Comment by Gantushig77** [comment]
Thank you.
