### ISSUE TITLE
table COMMENT Annotations will be automatically migrated and overwritten

### ISSUE THREAD

**Issue by coverthesea** [ent/ent#3926]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

func (Test) Annotations() []schema.Annotation {
    return []schema.Annotation{
        entsql.Annotation{
            Table:   "test",
            Options: "COMMENT = 'test table COMMENT '",
        },
    }
}

Now,My first run migrate table will  has COMMENT ,My second run migrate table will   does not COMMENT.

## Expected Behavior 🤔

test table has COMMENT  'test table COMMENT '
No matter how many times it is executed, it is normal

## Steps to Reproduce 🕹
Steps:

1.create schema file 
2. go run -mod=mod entgo.io/ent/cmd/ent generate 
3. run migrate
l.svcCtx.DB.Debug().Schema.Create(l.ctx)
4. I checked the database, test table has COMMENT  'test table COMMENT '
5. run migrate
6. I checked the database, test table does not has COMMENT 

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.5  |
| Ent         | 0.12.5   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey! Please use the standard annotation for defining table comments: https://entgo.io/docs/schema-annotations#database-comments

Feel free ton reopen if you still have issues with it.
