### ISSUE TITLE
Optional JSON field can't be set to SQL NULL, only JSON null

### ISSUE THREAD

**Issue by NickDubelman** [ent/ent#3952]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using an `Optional` `JSON` field, there doesn't seem to be any way to have the field be NULL. It always uses JSON `null` (even when using a `entsql.DefaultExpr` or `entsql.Default`). 

## Expected Behavior 🤔

An unset optional JSON field should have some mechanism for setting it to regular SQL NULL. 

## Steps to Reproduce 🕹

Define a JSON field on an entity.

I've tried:
1. `.Default(nil)` on the field (codegen fails)
2. Passing `nil` to `fields.JSON` instead of `&nil` (codegen fails)
3. Using annotation `entsql.DefaultExpr("NULL")` and `entsql.Default("NULL")` (codegen passes but it still uses JSON `null`)

I think this behavior is a reasonable default, but it seems like the `entsql.DefaultExpr` should be usable to override it.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.3  |
| Ent         | 0.12.2   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
If the column is optional (nullable), you don’t need to set it a default. It will be NULL if nothing was inserted to it.

If order to unset the value in a column (set to NULL), use the Clear<F> modifier.

Closing, but feel free to join our Discord in case you need more help with this.

**Comment by NickDubelman** [comment]
Thanks @a8m! I figured out that in my situation, it was because I had something like:

```go
var someMap := map[string]string{}
...
someMap = nil

Ent.Foo.Create().SetSomeJSONColumn(someMap)
...
```

Even though the _value_ is `nil`, the underlying _type_ is a `map`. This causes the DB row to get a JSON `null`. Whereas if you don't call `SetSomeJSONColumn` at all (or you pass a literal untyped `nil`), the row will have a SQL `NULL`.

Would you say this is expected/desired behavior?

**Comment by a8m** [comment]
Yes

**Comment by NickDubelman** [comment]
I can see why it is expected (how Go treats nil.. nil != nil), but do you mind explaining why it is desired behavior?
