### ISSUE TITLE
Schema.Create fails with Postgres 16 due to querying removed database settings

### ISSUE THREAD

**Issue by adamdspringer** [ent/ent#3971]
Schema.Create fails with Postgres 16 due to querying no longer existing database settings.
Downgrading to Postgres 15 works fine.  The issue is that 'lc_collate' and 'lc_ctype' were removed in Postgres 16.
This is the generated query that fails:  SELECT setting FROM pg_settings WHERE name IN ('lc_collate', 'lc_ctype', 'server_version_num', 'crdb_version') ORDER BY name DESC

- [X ] The issue is present in the latest release.
- [ X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Schema.Create fails (loops unsuccessfully)
## Expected Behavior 🤔
Schema.Create with the same code works in Postgres 14 and 15.

Schema.Create should succeed
## Steps to Reproduce 🕹
Define a simple test schema in Ent.  
My test case uses the "Use pgx with PostgreSQL" example code to connect to Postgres. Start Postgres then run the entgo. 
The same code works fine in Postgres 14 and 15, but fails with Postgres 16.

Steps:

1.Define a simple test schema in Ent.  Define Postges connection string, my test case uses the "Use pgx with PostgreSQL" Ent documentation example code to connect to Postgres. 
2. run "go generate ./..." from root directory
3. Start Postgres then run the entgo. 
4. Run your entgo program "go run cmd/main.go"
5.  Observe Postgres log that shows error

## Your Environment 🌎
MacOS Ventura

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.7?  |
| Ent         | 0.12.2?   |
| Database    | Postgres 16   |
| Driver      | https://github.com/jackc/pgx/v5 v5.5.4       |

**Comment by mayuresh82** [comment]
Is there a solution to this or is ENT only going to continue supporting until postgres 15 ? @a8m

**Comment by a8m** [comment]
Hey! This issue was resolved last year. See: https://github.com/ent/ent/issues/3752
