### ISSUE TITLE
How to add fields or comments to generated bridging table?

### ISSUE THREAD

**Issue by ttc0419** [ent/ent#3974]
Using the user and group example from the official documentation:
```go

/* user.go */
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.From("groups", Group.Type).Ref("users"),
	}
}

/* group.go */
func (Group) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("users", User.Type),
	}
}
```
Both includes:
```go
func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.WithComments(true),
	}
}
```
Ent will generate a bridging table called ```group_users``` for the schema, however, I did not see a way to add fields or comments to the fields. How to do that?

**Comment by kissIce** [comment]
i also have same question

**Comment by AlphaNecron** [comment]
https://entgo.io/docs/schema-edges, scroll down to Friendship section.

**Comment by ttc0419** [comment]
Thanks, it's described in https://entgo.io/docs/schema-edges/#edge-schema
