### ISSUE TITLE
Why can't fields be automatically filled in when creating?

### ISSUE THREAD

**Issue by myadream** [ent/ent#3975]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Case：

```go
user := User{
  Name: "one",
  Email: "1@1.com"
}

ent.User.Create().Fill(user).Save()
```

or 

```go
user := map[string]string{
"Name": "one",
"Email": "1@1.com"
}

ent.User.Create().Fill(user).Save()
```

## Motivation 🔦

In part of the business, by passing the struct parameter type, it is necessary to keep repopulating it each time it is created or modified.

**Comment by agratta-silo** [comment]
the GQL extension has a feature like this. If you aren't using GQL you can reference the template to create your own custom implementation.

```
type CreateAddressInput struct {
	Street1                string
	Street2                *string
        ...
}


func (c *AddressCreate) SetInput(i CreateAddressInput) *AddressCreate {
	i.Mutate(c.Mutation())
	return c
}
```

**Comment by rotemtam** [comment]
The answer and workaround is documented in the FAQ:

https://entgo.io/docs/faq#how-to-create-an-entity-from-a-struct-t
