### ISSUE TITLE
Shrink the generated code

### ISSUE THREAD

**Issue by willfaught** [ent/ent#4010]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The generated code is too large. I have a couple dozen schema files, and when compiled, the ent package is over 120 MB. Maybe use more shared code/types?

## Motivation 🔦

Smaller binaries, smaller codebases.

**Comment by a8m** [comment]
Hey! Actually, a smaller codebase doesn't mean smaller binaries - that's one thing we noticed while we added generics to some parts of the generated code, which led to longer symbols and therefore larger binaries.

There's a continuous effort on this; unfortunately, it requires a bit of reflection. However, this discussion fits better in our Discord server and not in an issue, as there's no immediate action to take here. Thanks for the feedback 🙏
