### ISSUE TITLE
New Migration Failed [ Migration ]

### ISSUE THREAD

**Issue by Hovo-Dev** [ent/ent#4024]
I am running the first version migration with atlas apply. 
```
atlas migrate apply --dir file://ent/migrate/migrations --url postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(HOST):$(PORT)/$(DB_NAME)?sslmode=disable
```
It works fine to me the new entity changes updates in the database, but when I have make new entity changes and trying to attempt second migration I run the following command to add new migration.
```
atlas migrate diff $(name) --dir "file://ent/migrate/migrations" --to "ent://ent/schema" --dev-url "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(HOST):$(PORT)/$(DB_NAME)?search_path=public&sslmode=disable"
```
Then, It throws the following error
```atlas migrate diff  --dir "file://ent/migrate/migrations" --to "ent://ent/schema" --dev-url "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(HOST):$(PORT)/$(DB_NAME)?search_path=public&sslmode=disable"
Error: sql/migrate: connected database is not clean: found table "patients" in connected schema
make: *** [diff] Error 1
```

Unlike version migration the automigration of ent works after new entity changes, but version migration doesn't allow to add new migration after each new changes and requires to clean Database.

E-mail: hovhannes.baghdasaryan.03@gmail.com
OS: MacOS Sonoma 14.4.1 M3 pro chip
GO: go1.22.2 darwin/arm64

**Comment by a8m** [comment]
Hey @Hovo-Dev,
For the `--dev-url`, please use: `docker://postgres/15/dev?search_path=public`. Alternatively, you can create a separate database specifically for Atlas' work and use it instead. You can read what dev-database is in this link: https://atlasgo.io/concepts/dev-database

Please, join our Discord in case you need more help with this: https://discord.gg/zZ6sWVg6NT
