### ISSUE TITLE
`Clone()` does not clone modifiers (via `Modify()`) to the new query

### ISSUE THREAD

**Issue by liamg** [ent/ent#4026]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I use `Modify()` on a query, and then `Clone()` that query, the cloned query does not include any of the modifiers.

## Expected Behavior 🤔

The clone and the original should be identical, including changes made by `Modify()`

## Steps to Reproduce 🕹

Steps:

1. Create a query
2. Make a change via `Modify()` e.g. join another table.
3. `Clone()` the query.
4. Compare the two queries - the original will have the modification, the clone will not.

## Your Environment 🌎

| Tech        | Version  |
| ----------- | -------- |
| Go          | 1.22.2   |
| Ent         | 0.12.5   |
| Database    | Postgres |
| Driver      | https://github.com/jackc/pgx        |

**Comment by nlhuykhang** [comment]
I and using Ent `v0.13.1` which has the same problem, is this expected behaviour or never considered?

**Comment by godcong** [comment]
`Modify()` return a `Select` from `Query` and `Clone()` is the method from `Query`.
This could be the reason for the omission

**Comment by nlhuykhang** [comment]
@godcong `modifiers` is a field of `Query` struct though
