### ISSUE TITLE
The schema enumeration type is set to Nillable(), and the generated String() method expects to return a pointer type string

### ISSUE THREAD

**Issue by XiaoK29** [ent/ent#4035]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

**Comment by henrywoody** [comment]
Can you explain in more detail (ideally with some code examples)? From what I can tell this sounds like the expected behavior.

**Comment by XiaoK29** [comment]
> Can you explain in more detail (ideally with some code examples)? From what I can tell this sounds like the expected behavior.

Schema

```go
field.Enum("gender").Optional().Nillable().Values("male", "female")
```

GenCode

```go
Gender *user.Gender `json:"gender,omitempty"`
```

GenEnum

```go
type Gender string

// Gender values.
const (
	GenderMale   Gender = "male"
	GenderFemale Gender = "female"
)

func (ge Gender) String() string {
	return string(ge)
}
```

Use

```go
// got string
// want *string
user.Gender.String() 
```

**Comment by XiaoK29** [comment]
> 这似乎是 Ent 的正确行为。调用的方法`String`应该返回`string`，没有`*string`很多其他代码依赖于这个约定。如果您愿意，您可以添加自己的方法`(Gender) NilString() *string`。
> 
> 但尚不清楚为什么您需要`*string`而不是`string`.如果您需要检查该值是否`nil`在服务器逻辑内部，您只需检查性别字段本身是否`nil`在，而不是转换`*string`为然后检查`nil`.如果您正在管理自己的 API（例如 REST API），那么您可以使用`omitempty`struct 标记。听起来这可能是 XY 问题。
> 
> `String`您需要返回的原因是什么`*string`？

Gender is not a mandatory field, so I need the optional of * string and proto be used together,It is also feasible to package (Gender) NilString() * string by oneself

**Comment by henrywoody** [comment]
If the Gender field is not mandatory you should be fine because it is already a pointer type (`*Gender`). The `String` method only needs to be used when representing the field in some other context (like the API or database).
