### ISSUE TITLE
v2: rename edge method Unique to Single or One

### ISSUE THREAD

**Issue by willfaught** [ent/ent#4074]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

`edge.From("course_item", CourseItem.Type).Unique()` looks like there's a unique constraint on the field. Call it something else, like Single or One.

## Motivation 🔦

It looks like you're declaring an index or unique constraint, not specifying what the cardinality is.

**Comment by a8m** [comment]
Hey! Please see my response here: https://github.com/ent/ent/issues/3678#issuecomment-1666018765

Closing, as this was answered in the past.

**Comment by willfaught** [comment]
Whoops! You’re right. Although, there, you said you would never break compatibility, whereas here the proposal is for major version 2, where compatibility is broken by definition. This is actually what I meant in the other one.
