### ISSUE TITLE
How can I customize entsql.Default's annotation per dialect?

### ISSUE THREAD

**Issue by marwan-at-work** [ent/ent#4100]
Hi there 👋🏼 
I have the following field: 

```golang
field.Time("date_of_birth").Default(time.Now).Annotations(
	entsql.Default("NOW()"),
),
```

However, this only works for Postgres since MySQL requires `entsql.Default("CURRENT_TIMESTAMP")`.

I looked around in the docs but I couldn't find something where you can customize the Annotation per dialect like we can do with SchemaType.

Thanks!

**Comment by a8m** [comment]
Yes. See: https://github.com/ent/ent/blob/master/dialect/entsql/annotation.go#L84

**Comment by marwan-at-work** [comment]
Thank you 🙏🏼
