### ISSUE TITLE
how to change ID default type to uint64? 

### ISSUE THREAD

**Issue by kissIce** [ent/ent#4117]
### like title, how to change default ID type to uint64.  now default type is int. but i find some descrtion in docs tell me can change ID type by codegen option. but this text link in docs can'ot  find how to change it.     who can tell me how to change it ?  tnks

<img width="1083" alt="image" src="https://github.com/ent/ent/assets/18099374/a8fe2597-17ee-4d3d-ae74-804c25e89723">

**Comment by eiixy** [comment]
gqlgen.yaml
```
models:
  # Defines the ID field as Go 'int'.
  ID:
    model:
      - project/internal/pkg/gql/scalars.Int64
```

project/internal/pkg/gql/scalars/int64.go
```
package scalars

import (
	"encoding/json"
	"fmt"
	"github.com/99designs/gqlgen/graphql"
	"github.com/spf13/cast"
	"io"
)

func MarshalInt64(t int64) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		_, _ = io.WriteString(w, fmt.Sprintf(`"%d"`, t))
	})
}

func UnmarshalInt64(v interface{}) (int64, error) {
	switch v := v.(type) {
	case string, int, uint, int64, uint64:
		return cast.ToInt64E(v)
	case json.Number:
		return v.Int64()
	default:
		return 0, fmt.Errorf("%T is not an int64", v)
	}
}
```

**Comment by a8m** [comment]
Hey, @kissIce! Please, see: https://entgo.io/docs/schema-fields#id-field

Closing, but feel free to join our Discord server in case you need more help with it.
