### ISSUE TITLE
How to declare M2M relation with additional values?

### ISSUE THREAD

**Issue by nawa** [ent/ent#4153]
I have to store few additional fields with many2many relation

The best mapping that I'd like to have in SQL is

```
user_group
------------
user_id     INT
group_id  INT
record_date DATETIME
```

Is it possible to achieve that with Ent schema or could you propose any another feasible way?

```go
func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("groups", Group.Type).Annotations(entsql.OnDelete(entsql.Cascade)),
	}
}
```

**Comment by a8m** [comment]
Hey! See the EdgeSchema option: https://entgo.io/docs/schema-edges#edge-schema

If you still need support, join our Discord server please.
