### ISSUE TITLE
Issue with Unavailable Methods in ent

### ISSUE THREAD

**Issue by call-81192** [ent/ent#4163]
I encountered the following issues while using ent for database operations:

Methods OnConflict, OnConflictColumns, and UpdateNewValues Are Unavailable
Despite referencing ent official documentation and examples, I am unable to find these methods in my code.

Methods Not Found in Generated Code
I attempted to verify the presence of these methods in the generated code (under the ent directory), but I could not locate them.

ent Version Issue
The version of ent I am using is v0.14.1, but the functionality seems to be unavailable in this version.

Dependency Not Updated
I tried updating ent and its related dependencies, but the issue persists.

Steps to Reproduce:

Attempt to execute an insert operation with conflict handling using the following code:

err := client.User.
    Create().
    SetName("Ariel").
    OnConflictColumns(user.FieldName).  // Method used to handle conflict
    UpdateNewValues().                  // Method used to update values
    Exec(ctx)
Check the generated code files to verify if these methods are present.

Refer to the [ent version release notes](https://github.com/ent/ent/releases) and documentation to understand supported features.

Expected Behavior:

The methods OnConflict, OnConflictColumns, and UpdateNewValues should be available to handle database conflicts.
These methods should be present in the ent generated client code and function as expected.
Actual Behavior:

The methods OnConflict, OnConflictColumns, and UpdateNewValues are not found in the code.
These methods are not present in the generated code files.
Version v0.14.1 of ent does not seem to support these functionalities.
Additional Context:

Ensure that ent and its related tools are up to date, and that code generation has been completed successfully.
Provided an official documentation example to confirm the usage of these methods.
Suggested Fix:

Verify whether the ent version in use supports these methods and review the documentation for the relevant version.
If these methods are not supported in the current version, consider upgrading to a version that supports these features.
Ensure that the code generation step is error-free and that the generated code files are complete.

**Comment by krakowski** [comment]
Hi, did you specify the `--feature sql/upsert` feature flag? Please see the [documentation](https://entgo.io/docs/feature-flags#upsert). I use `v.0.14.0` (there is no `v0.14.1`).

**Comment by a8m** [comment]
Thanks @krakowski for supporting @call-81192 🙏 

Closing, but please feel free to join our Discord server in case you need more help with this.
