### ISSUE TITLE
MaxLen Validator is not working as intended.

### ISSUE THREAD

**Issue by fullgukbap** [ent/ent#4179]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
I configured the user table with the following code.
```go
// ./ent/schema/user.go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

// Avatar holds the schema definition for the Avatar entity.
type Avatar struct {
	ent.Schema
}

// Fields of the Avatar.
func (Avatar) Fields() []ent.Field {
	return []ent.Field{
		field.Enum("sex").
			Values(
				"male",
				"female",
			),

		field.Time("birthday"),

		field.String("mbti").
			MaxLen(4).
			Optional().
			Nillable(),

		field.String("picture").
			NotEmpty(),

		field.String("nickname").
			MinLen(4).
			MaxLen(12).
			NotEmpty(),
	}
}

```

I configured the environment related to ent development with the `go generate` command, and wrote the following code for testing.
```go
// main.go
...

client.User.Create().
		SetNickname("장충동왕족발보쌈").
		SaveX(context.Background())

```

Here are the errors that Golang tells you about after execution

- panic: ent: validator failed for field "User.nickname": value is greater than the required length

The important thing to note here is that the error occurs even though the length of the argument to the SetNickname function is 8. (When we defined the table, the nickname field had a character count range of 4 to 12 characters).

## Expected Behavior 🤔

So my expected behavior is that it works fine, no panic!

## Steps to Reproduce 🕹

I don't think this issue is self-explanatory, so I won't reproduce it. 

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.22.5  |
| Ent         | 0.14.0  |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

## An additional note.

Further speculation as to why this is happening could be due to something specific about the len function.

In the example above, the string '장충동왕족발보쌈' is Hangul(Korean).  In the Go language, Hangul is represented by 3 bytes in UTF-8.

So if the MaxLne function internally uses the len function to perform validation, then the string “안녕하세요” consists of 5 characters, but since each character takes up 3 bytes, the byte length of the entire string would be 15 bytes. Therefore, len(“안녕하세요”) returns 15 instead of 5, so we can cautiously speculate that the MaxLen function is not working as intended.

**Comment by noamcattan** [comment]
@fullgukbap I would suggest to write a custom validator like this:
```go
// ./ent/schema/user.go
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/field"
	"errors"
	"unicode/utf8"
)

// Avatar holds the schema definition for the Avatar entity.
type Avatar struct {
	ent.Schema
}

// Fields of the Avatar.
func (Avatar) Fields() []ent.Field {
	return []ent.Field{
		field.Enum("sex").
			Values(
				"male",
				"female",
			),

		field.Time("birthday"),

		field.String("mbti").
			MaxLen(4).
			Optional().
			Nillable(),

		field.String("picture").
			NotEmpty(),

		field.String("nickname").
			Validate(func(s string) error {
				switch l := utf8.RuneCountInString(s); {
				case l < 4:
					return errors.New("nickname is too short")
				case l > 12:
					return errors.New("nickname is too long")
				}
				return nil
			}).
			NotEmpty(),
	}
}
```
