### ISSUE TITLE
max connection

### ISSUE THREAD

**Issue by hicker-kin** [ent/ent#4214]
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

how can i set max connections on postgresql or mysql??

**Comment by a8m** [comment]
See: https://entgo.io/docs/sql-integration#configure-sqldb

**Comment by hicker-kin** [comment]
> See: https://entgo.io/docs/sql-integration#configure-sqldb

thk u, get it
