### ISSUE TITLE
`Client interface` and implement it on `Tx struct` and `Client struct`

### ISSUE THREAD

**Issue by afifurrohman-id** [ent/ent#4230]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

We want to `Client` and `Tx` have general interface.
do we don't have any duplicate code like this
```go
func Create(client *ent.Client, ctx context.Context, input *CreateInput) (*model.Foo, error) {
        foo, err := client.Foo.
		Create().
		SetID(uuid.New()).
		SetName(input.Name).
		Save(ctx)
}

func CreateWithTx(client *ent.Tx, ctx context.Context, input *CreateInput) (*model.Foo, error) {
        foo, err := client.Foo.
		Create().
		SetID(uuid.New()).
		SetName(input.Name).
		Save(ctx)
}
```

## Motivation 🔦

This helps especially if we want to use either using Tx or not, where we don't care about the `Client` or `Tx`

**Comment by a8m** [comment]
You can use "transactional clients" for this. Read more here: https://entgo.io/docs/transactions#transactional-client

If you need more help, you're welcome to join our Discord server.
