### ISSUE TITLE
Create has no field or method OnConflict

### ISSUE THREAD

**Issue by sanfuyee** [ent/ent#4272]
Create has no field or method OnConflict

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

<img width="289" alt="Screenshot 2024-12-10 at 11 16 18" src="https://github.com/user-attachments/assets/0c03e5d4-9271-4a9d-b1bc-1079841b1912">

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.23.3|
| Ent         | 0.12.5   |
| Database    | Postgres   |
| Driver      | https://github.com/go-sql-driver/mysql v1.7.1|

**Comment by sanfuyee** [comment]
I have referenced the document https://entgo.io/docs/crud/#upsert-one , but why it doesn't work in my source code

**Comment by sanfuyee** [comment]
@rotemtam hi, could you help me?

**Comment by godcong** [comment]
![image](https://github.com/user-attachments/assets/b6e23533-f641-4f76-a3ae-4a073efb7536)
Do you add the feature flag when generating?
