### ISSUE TITLE
possibility to omit fields from graphql mutations

### ISSUE THREAD

**Issue by liron-navon** [ent/ent#4275]
I have a struct that uses the time mixin, so it includes a "created_at" and "updated_at", I use the graphql generation tools (which are great ❤️), but I don't want anyone to be able to update/set these field as they are used for database management and ordering only.

would be nice to have an annotation to omit some fields

I do not want to make them sensitive as that would make them hidden also from queries and orderBy, where they are actually quite useful.

- [X ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

maybe something like adding options to the Mutation functions in entgql?

```go
func (Profile) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.RelayConnection(),
		entgql.Mutations(
			entgql.MutationCreate(&entgql.MutationCreateOptions{
				IgnoreFields: []string{"created_at", "updated_at"},
			}),
			entgql.MutationUpdate(&entgql.MutationUpdateOptions{
				IgnoreFields: []string{"created_at", "updated_at"},
			}),
		),
	}
}
```

Or something like this at the field level:

```go
func (CommonMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Time("create_time").
			Default(time.Now).
			Immutable().
			Annotations(
				entgql.IgnoreFieldInUpdateMutation(),
				entgql.IgnoreFieldInCreateMutation(),
				entgql.OrderField("CREATE_TIME"),
			),
		field.Time("update_time").
			Default(time.Now).
			UpdateDefault(time.Now).
			Annotations(
				entgql.IgnoreFieldInUpdateMutation(),
				entgql.IgnoreFieldInCreateMutation(),
				entgql.OrderField("UPDATE_TIME"),
			),
		field.UUID("id", uuid.Nil).
		Default(UUIDV7DefaultFn),
	}
}
```

## Motivation 🔦

Trying to work with the graphql generation tool, but this is something that is quite important to me, yet I have to manually handle it in the resolver, but still these fields exist in the schema, which makes the schema confusing as I do not really want users to mess with these fields

**Comment by a8m** [comment]
Hey! Thanks for the kind words.

Use the `entgql.Skip` annotation. For example:

```go
func (T) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixin.AnnotateFields(
			mixin.Time{},
			entgql.Skip(entgql.SkipMutationCreateInput|entgql.SkipMutationUpdateInput),
		),
	}
}
```

**Comment by a8m** [comment]
It won't help to complain; we don't do refunds :D
