### ISSUE TITLE
Question: granularity of the future privacy layer

### ISSUE THREAD

**Issue by kkom** [ent/ent#494]
Hey, I have a question about the plans for the planned privacy layer, specifically - what's in scope?

I can imagine the following features:

1. Blocking mutations – I assume you can be very flexible here, defining arbitrary rules based on what exactly is the mutation
2. Blocking reads – how granular is the plan for it? are we talking just ent-level visibility policies, or also field-level / edge-level?

Thanks for working on it - excited to see how it pans out!

**Comment by a8m** [comment]
Hey @kkom, in the current (experimental) implementation we provide the option to reject/change mutations/queries. We (want and) plan to add another level for edge privacy, but we don't have any design for it yet. 

About more granularity, like field-level, I'd like to hear what do you mean? To be able to filter out some of the fields? 

One of the things I'm working on at the moment is a "generic" query language for ent (entql), so I expect that some of the things in the current API might change. For example, to be able to write generic privacy rules.

**Comment by kkom** [comment]
> in the current (experimental) implementation we provide the option to reject/change mutations/queries

Could you point to some places in the code that’ll show me how to use it? I don’t mind that it’s experimental, so is my app at the moment.

> To be able to filter out some of the fields?

Yes — exactly that. Simplest example: user has a date of birth on their profile, but we don’t want to share with enough who can load the ent, but only friends.

Can you achieve control like this with the current framework or with any of the changes you’re immediately planning?

My feeling is that currently it’s not possible, as fields are represented as members of struct, so there is no way to abstract accessing them and inject any privacy rules.

> For example, to be able to write generic privacy rules.

Could you elaborate on this? Are you talking about writing one rule that applies to multiple ent types?

Could ent ql introduce the layer of abstraction needed to block access to certain fields?

**Comment by a8m** [comment]
> Could you point to some places in the code that’ll show me how to use it? I don’t mind that it’s experimental, so is my app at the moment.

Sure, see [this example](https://github.com/facebookincubator/ent/blob/cdd855c/entc/integration/privacy/ent/schema/planet.go#L43) and its [tests](https://github.com/facebookincubator/ent/blob/cdd855c8c9ec295eb1a9721b97eb4bb014cdcb55/entc/integration/privacy/privacy_test.go). But please note, that this API might change in the near future and it's not stable until we'll update the docs (in entgo.io). 

> Yes — exactly that. Simplest example: user has a date of birth on their profile, but we don’t want to share with anyone who can load the ent, but only their close friends.
> 
> Can you achieve control like this with the current framework or with any of the changes you’re immediately planning?
> 
> My feeling is that currently it’s not possible, as ent fields are accessed as raw struct fields, so there is no way to abstract accessing them and inject any privacy rules.

Interesting case. We didn't think about it. Maybe we should add a privacy option to schema fields as well. 

> Could you elaborate on this? Are you talking about writing one rule that applies to multiple ent types?

I wrote about it in a different [issue](https://github.com/facebookincubator/ent/issues/277#issuecomment-622316098). Once entql will be added to the framework, the Mutation and the Query interfaces will support this and it'll make it easier to write Mixin with policies or just some rules that can be added to multiple schemas.

**Comment by kkom** [comment]
Thanks for the pointers @a8m!

On entql, I guess I'll need to play with the framework a little more to understand the use cases here, but I'm sure it will become obvious later on.

Do you want to keep this issue open for the field privacy rules? I fear it might introduce some complications, e.g. not sure if `gqlgen` autobinding will work as well, etc.

**Comment by a8m** [comment]
> Once entql will be added to the framework, the Mutation and the Query interfaces will support this and it'll make it easier to write Mixin with policies or just some rules that can be added to multiple schemas.

The issue was resolved a long time ago. Closing, but feel free to reopen in case it's needed. Thanks <3
