### ISSUE TITLE
Adding support for fields/edges dialect-specific DDLs

### ISSUE THREAD

**Issue by nilpntr** [ent/ent#562]
Would you like to add support for ddl's to add default values for the time fields?

**Comment by a8m** [comment]
Pasting here my comment from #558:

> I've landed 3e7481c3a015400fd5f407aba1c57f35731601dc that ignores the MySQL default values for time fields, and it should not apply any changes for the second time the migration runs.
> 
> However, it won't work with the current way you declare the schema, because you add additional parameters to the schema datatype (the create/update default values).
> 
> I suggest to close this issue and open a new one for adding support for fields/edges dialect-specific DDLs. For example:
> 
> ~~~go
> // Add abstraction for common DDLs.
> field.Time("create_time").
>     DDL(
>         field.Default("CURRENT_TIMESTAMP"),
>         field.OnUpdate("CURRENT_TIMESTAMP")
>     )
> 
> // Add additional information for the given column. The EXTRA in the
> // INFORMATION_SCHEMA table. For example, the "ON UPDATE" clause.
> field.Time("update_time").
>     SchemaDef(map[string]string{
>         MySQL: "DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",
>     })
> 
> // Completely override the ent-migration column definition.   
> field.Time("create_time").
>     SchemaDef(map[string]string{
>         MySQL: "TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL",
>     })
> ~~~
> 

Feedback or thoughts are welcome.

**Comment by sj8m** [comment]
That syntax would be nice :)

**Comment by a8m** [comment]
Closing, as this was implemented by [entsql.Annotation](https://pkg.go.dev/entgo.io/ent/dialect/entsql). Thanks 🙏
