### ISSUE TITLE
FirstOrUpdate, FirstOrCreate...

### ISSUE THREAD

**Issue by shellbear** [ent/ent#685]
Hello,

How can we execute functions such as **FirstOrUpdate**, **FirstOrCreate** with ent like is it possible with Gorm (http://gorm.io/docs/query.html#FirstOrCreate)? Does this feature is currently missing from the API?

Thank you!

**Comment by stark-sim** [comment]
Hi, I'm looking for this too, may I ask any solutions you had found, why close this issue that fast?
