### ISSUE TITLE
proposal: provide tool for generating codes from ddl

### ISSUE THREAD

**Issue by day-dreams** [ent/ent#783]
what about provide a cmd tool, read ddl files (or get ddl from database) as inputs,  and then generate ent/schema/* as outputs ?

if we have such a tool,   we can refactor applications easily with entc.

and it is also convinient for people who prefer to write sql ddl first, but not write golang code (entc schema definations) .

**Comment by a8m** [comment]
Hey @day-dreams and thanks for proposing this issue.
I actually did such an experiment ~1 year ago, and decided to not go with it. However, if someone wants to write something like this as a separate project, I'll be happy to help. We may add it to [ent-contrib](https://github.com/facebookincubator/ent-contrib) if we'll find it useful for other users.

**Comment by masseelch** [comment]
There now is [entimport](https://github.com/ariga/entimport) which does this. I am closing this issue, but feel free to re-open, if you think it should stay open.
