### ISSUE TITLE
Hooks for Read Operations

### ISSUE THREAD

**Issue by asonawalla** [ent/ent#833]
Reading the docs and code, it looks like ent exposes the ability to register hooks in mutating operations, but not on reads.  The use case I'm trying to solve for is one in which sensitive data is encrypted before being persisted to a database and then decrypted on subsequent reads, assuming the caller provides the appropriate keys/metadata.  Given the lack of read hooks, the approaches to this problem today seem to be limited to (1) encrypting in a mutation hook and decrypting in the application or (2) moving all encryption / decryption to the application.  (1) is less than ideal because of divergent and arguably non-intuitive implementations and (2) opens up a greater possibility of accidentally circumventing the rules.

Is there another approach to this scenario I'm not seeing?  If not, would the ent authors consider either adding this or accepting a contribution that adds this?

**Comment by a8m** [comment]
Hey @asonawalla and thanks for raising up this issue! I'll answer about it briefly and add more details about it tomorrow (it's a holiday evening atm here).

The only place for hooking into queries is the privacy layer (you won't find in the website, because docs is in progress). However, @alexsn and I just discussed about it yesterday, and agreed that we want to add support for read-hooks/interceptors. We thought about naming it as `Interceptor`s, but we're not sure about the end design. So, you're welcome to start the discussion here and propose  the API (implementation should be simple).  Once we add this, the privacy layer will be migrated to this generic layer as well.

**Comment by asonawalla** [comment]
Perfect, I'll get a bit familiar with the privacy layer and circle back with any thoughts on API.  Enjoy your evening!

**Comment by dilipkk-foyernet** [comment]
This is needed feature for us also, we want to inject some params to both read and write apis based user context. This is useful for security and customisation.

**Comment by a8m** [comment]
Hey, the privacy doc is available now in [entgo.io/docs/privacy](https://entgo.io/docs/privacy/).

**Comment by asonawalla** [comment]
I've been thinking through my use case and the ideal API a bit more.  For symmetric encryption, defining a `ReadHooks()` method in the schema which has access to field getters and setters will be able to convert persisted ciphertext into plaintext once the query has been run.  Unfortunately modifying fields in this way would break the ability to use that field in a query predicate, e.g. it wouldn't be straightforward to look up a user based on an API key that's hashed in the DB but passed plain in the application.

This is very likely out of scope for this issue, but maybe the ideal solution to this problem is to offer even more granular hook capabilities that are evaluated independently of the DB?  Something that might compile to roughly:

```
type Entity struct {
  myField string // value that gets persisted
}

func (e *Entity) MyField() string {
  // optional custom getter logic e.g. decryption
}

func (e *Entity) SetMyField(v string) {
  // optional custom setter logic e.g. encryption
}
```

**Comment by yuvalt7** [comment]
@a8m Is there an equivalent of a global hook in the privacy layer (i.e global privacy rule)?
AFAICT privacy rules are per-table, which makes it hard to use privacy layer as a means of keeping track of general DB query accesses (e.g for metrics)

this is obviously a misuse of the privacy layer, but its a workaround until  read-hooks are ready :P

**Comment by yuvalt7** [comment]
> @a8m Is there an equivalent of a global hook in the privacy layer (i.e global privacy rule)?
> AFAICT privacy rules are per-table, which makes it hard to use privacy layer as a means of keeping track of general DB query accesses (e.g for metrics)
> 
> this is obviously a misuse of the privacy layer, but its a workaround until read-hooks are ready :P

a temporary workaround - wrapping *sql.DB in a custom dialect.Driver interface implementation that intercepts the Query function

**Comment by a8m** [comment]
Hey @yuvalt7, you can define a global privacy rule using a mixed-in schema. See [this example](https://entgo.io/docs/privacy/#multi-tenancy) in the doc.

I'm still working on designing the API for interceptors (read-hooks), but suggestions are welcome.

**Comment by cliedeman** [comment]
Also interested in this

Could possibly implement something simliar too [ef core global filters](https://docs.microsoft.com/en-us/ef/core/querying/filters)

e.g. by default only retrieve active records

```
// will only retrieve active users
u, err := client.User.
        Query().
        Only(ctx)

// Remove default filters
u, err := client.User.
        Query().
        ClearGlobalFilters()
        Only(ctx)
```

**Comment by gqgs** [comment]
@a8m An issue with the privacy layer workaround is not being able to defer a function call to the end of the query evaluation.
Is there another way to handle the query tracing use case?
It seems an API similar to hooks but for queries should work for this specific case.

```go
client.Intercept(func(next ent.Query) ent.Query {
    return ent.QueryFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
        start := time.Now()
        defer func() {
            log.Printf("Time=%s\tConcreteType=%T\n", time.Since(start), q)
        }()
        return next.Query(ctx, q)
    })
})
```

**Comment by rr-tomas-henriquez** [comment]
> I've been thinking through my use case and the ideal API a bit more. For symmetric encryption, defining a `ReadHooks()` method in the schema which has access to field getters and setters will be able to convert persisted ciphertext into plaintext once the query has been run. Unfortunately modifying fields in this way would break the ability to use that field in a query predicate, e.g. it wouldn't be straightforward to look up a user based on an API key that's hashed in the DB but passed plain in the application.
> 
> This is very likely out of scope for this issue, but maybe the ideal solution to this problem is to offer even more granular hook capabilities that are evaluated independently of the DB? Something that might compile to roughly:
> 
> ```
> type Entity struct {
>   myField string // value that gets persisted
> }
> 
> func (e *Entity) MyField() string {
>   // optional custom getter logic e.g. decryption
> }
> 
> func (e *Entity) SetMyField(v string) {
>   // optional custom setter logic e.g. encryption
> }
> ```

I agree that for your specific use case, getter/setter approach seems to be more explicit and simple than read hooks

**Comment by jejayhe** [comment]
@gqgs did you figure it out how to add read hooks

**Comment by tonybase** [comment]
We need to convert ent error to framework error, like this::
```go
client.Use(func(next ent.Mutator) ent.Mutator {
        return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
            v, err := next.Mutate(ctx, m)
            return v, convertError(err)
        })
    })

// https://github.com/go-kratos/kratos/blob/main/errors/types.go
func convertError(err error) error {
	if err == nil {
		return nil
	}
	if ent.IsNotFound(err) {
		return errors.NotFound("DATA", err.Error())
	}
	return errors.InternalServer("DATA", err.Error())
}
``

**Comment by kcmvp** [comment]
any update about this feature?

**Comment by renjun0106** [comment]
+1

**Comment by renjun0106** [comment]
@gqgs hooks for tracing can look https://github.com/qustavo/sqlhooks

**Comment by a8m** [comment]
Hey! A quick update on this issue: the feature was implemented in https://github.com/ent/ent/pull/3157 and will be merged in the upcoming days. You're welcome to share your feedback or thoughts on the PR.

**Comment by a8m** [comment]
Closed with https://entgo.io/docs/interceptors 😃
