### ISSUE TITLE
proposal: Check if migrations Needed

### ISSUE THREAD

**Issue by cliedeman** [ent/ent#866]
Use Case:
I am using ent with a [external migration tool](https://github.com/golang-migrate/migrate) for sql that ent does not currently support.

I would like to know if Migrations _need_ to be run as a way to check if the external created schema matches what ent expects.

**Comment by a8m** [comment]
Hey (again) @cliedeman and thanks for proposing this issue 😃 
I actually want to add support  for this, and it should be easy. I'll add more details about it in the upcoming days.

**Comment by cliedeman** [comment]
@a8m Thanks, I looked over the code briefly. I think would just need to refactor the migration code int a plan and apply phases and this feature should be very easy to implement after that. Also somewhat related to offline migrations

**Comment by cliedeman** [comment]
pretty sure this is superseded by atlas
