### ISSUE TITLE
proposal: add an optional to load edge-ids (foreign-keys) in query builder

### ISSUE THREAD

**Issue by aight8** [ent/ent#869]
Maybe this is a uniqueness of relational DB's. But edge ID's are a part of a row (Assuming the foreign key is on the side of the rows table).
However this has big benefits:
- You can generally check if a relation exists
- I can use the relation ID for various things (where the ID only is enough, links/actions/other ID only deterministic things like loading an image, and the ID is a hash)

Is it possible somehow?

When not, maybe it would be nice to make this accessible. If graph DB's don't support this, maybe behind a function. Mostly those are 5 int/varchar fields to also select in a simple query. I really missing this one.

**Comment by a8m** [comment]
Hey @aight8 and thanks for proposing this issue. 
It was actually raised before in the issue tracker a few times, so I think we need to address this.

I have a few ideas how such API should look like (and I'll write them later), but you're welcome to write here your suggestions as well.

**Comment by aight8** [comment]
huck, sry I posted this issue by mistake... I wrote it as part of my other "Feedback" issue.

**Comment by errorhandler** [comment]
I've run into this while moving an existing codebase to ent. Here are some ideas for how this could be solved.

## 1. Exposing the foreign keys

I believe being able to access the foreign key values is important so I would suggest exporting the foreign key values

```go
type Pet struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PetQuery when eager-loading is set.
	Edges     PetEdges `json:"edges"`
	UserPets *int
	UserTeam *int
}
```

## 2. Match nilability in struct

As far as I understand, all FKs in the generated struct are pointers as they are `nil` until the edges are eager-loaded. To make 1. actually usable I believe it should match the edge'se required state.

## 3. Expose predicates for querying foreign keys

1. and 2. are an approach to solve the read path I believe. The only way I've found to do the equivalent of:

```sql
SELECT * FROM `pets` WHERE user_pets = ?
```

is as follows:

```go
client.Pet.Query().Where(func(selector *sql.Selector) {
		selector.Where(sql.EQ(selector.C(pet.OwnerColumn), ownerID))
}).All(ctx)
```

I think there is value in adding generated predicates so you can write the following:

```go
client.Pet.Query().Where(pet.HasOwnerWithID(ownerID)).All(ctx)
```

As with @aight8 I haven't looked into how ent handles Gremlin so I'm not sure if this suggestion has any issues with it.

**Comment by errorhandler** [comment]
> I've run into this while moving an existing codebase to ent. Here are some ideas for how this could be solved.
> 
> ## 1. Exposing the foreign keys
> I believe being able to access the foreign key values is important so I would suggest exporting the foreign key values
> 
> ```go
> type Pet struct {
> 	config `json:"-"`
> 	// ID of the ent.
> 	ID int `json:"id,omitempty"`
> 	// Name holds the value of the "name" field.
> 	Name string `json:"name,omitempty"`
> 	// Edges holds the relations/edges for other nodes in the graph.
> 	// The values are being populated by the PetQuery when eager-loading is set.
> 	Edges     PetEdges `json:"edges"`
> 	UserPets *int
> 	UserTeam *int
> }
> ```
> 
> ## 2. Match nilability in struct
> As far as I understand, all FKs in the generated struct are pointers as they are `nil` until the edges are eager-loaded. To make 1. actually usable I believe it should match the edge's required state.
> 
> ## 3. Expose predicates for querying foreign keys
> 1. and 2. are an approach to solve the read path I believe. The only way I've found to do the equivalent of:
> 
> ```sql
> SELECT * FROM `pets` WHERE user_pets = ?
> ```
> 
> is as follows:
> 
> ```go
> client.Pet.Query().Where(func(selector *sql.Selector) {
> 		selector.Where(sql.EQ(selector.C(pet.OwnerColumn), ownerID))
> }).All(ctx)
> ```
> 
> I think there is value in adding generated predicates so you can write the following:
> 
> ```go
> client.Pet.Query().Where(pet.HasOwnerWithID(ownerID)).All(ctx)
> ```
> 
> As with @aight8 I haven't looked into how ent handles Gremlin so I'm not sure if this suggestion has any issues with it.

**Comment by a8m** [comment]
Hey @errorhandler and thanks for writing this - I missed it somehow.

> As with @aight8 I haven't looked into how ent handles Gremlin so I'm not sure if this suggestion has any issues with it.

This shouldn't be a problem, because ent generates codegen based on the storage-type.

These options can be added using feature flags. I can start pushing this in the upcoming days, but if you want to contribute these changes, let me know and I can guide you.

**Comment by errorhandler** [comment]
Great to hear @a8m! I've done 3 with a template for my use case so I'm happy to expand this work and contribute. I'll have a go making what I believe are the required changes and follow up with any questions I may have.

**Comment by a8m** [comment]
Closing with #1213 

See https://entgo.io/docs/schema-edges/#edge-field for full docs. 

Thanks @errorhandler and @aight8 for pushing this.
