### ISSUE TITLE
My Experience & Feedbacks

### ISSUE THREAD

**Issue by aight8** [ent/ent#870]
I have wrote down some notes while using ent on daily basis since month. I wrote a lot custom templates.
I want to share those notes/thoughts now in a single post quickly before it lands in nirvana.

### Edge Field:

- Rename ```Unique()``` to ```Single()```, since a ```Unique()``` method is also used for indexes to mark it "uniqueness", it always confuses me at the first sight. Another idea were explicit functions like: ```One()```, ```Many()``` - those would help to understand/read the code easier.

### Schema Models

- All the field builders are private. I use helper functions to build several fields, but I must copy them because I cannot return a private builder in my own code.
- Edge fields are named like ```node1_node2``` however I really prefer ```node2_id``` in 90% of the cases when it's possible. I rename the FK field with ```edge.To("node2", Node2.Type).Unique().StorageKey(edge.Column("node2_id")),``` - It really bloats my schema files up. It's smaller, more explaining and easier to use in trigger functions etc. Maybe some ideas? An idea: a ```generator function``` for edge column names
- Possibility to define keywords which should generate upper cased words when it stands alone (all kind of units, currencies).

### Node Creation

- Create Node By Required field method - don't want missing this function, because on model change, i have direct a feedback that something could be wrong.
  https://gist.github.com/aight8/ac072ad3bb76c945ee3fdbedb9d50658

### Node Model / Edge
- Access of edge node ID's if it's available in the node props without querying the edge (github.com/facebook/ent/issues/869 - I created an issue for that one because it's a performance blocker for me)
- There is the method ```node.QueryEdgeName()``` and ```node.Edges.EdgeNameOrErr()```. A combination of this function where nice and could be a kind of self managed lazy loading (```node.EdgeName()``` maybe, or with a suffix, dont find a nice one for now). So when you need an edge it's queried on-demand if the edge is not already loaded. However I don't checked all possible cases for this one - how it affects transactions etc.

### Error Handling
- I use ```ent.MaskNotFound()``` heavily. It were nice to have it integrated in the ```X``` functions or e separate bunch of methods. When the first return value (the found object) is nil, it's logical for me that it's not found. It's more readable than extracting this case from the returned error every time. How I see now the ```FirstX``` panicking only on not NotFound errors.

**Comment by a8m** [comment]
Hey (again) @aight8 and thanks for taking the time to post it here 😃 

Let me know when it's no longer WIP, and I'll go over it.

**Comment by kidlj** [comment]
> Edge fields are named like node1_node2 however I really prefer node2_id in 90% of the cases when it's possible. I rename the FK field with edge.To("node2", Node2.Type).Unique().StorageKey(edge.Column("node2_id")), - It really bloats my schema files up. It's smaller, more explaining and easier to use in trigger functions etc. Maybe some ideas?

Yeah this feature prohibits me from using ent in my production project recently, as I once reported at issue #548, it causes confusion, and it's hard to migrate to plain sql or other ORMs once such tables created using ent.

I really hope that in the future when adding edge migration feature, we can reconsider this design, and make foreign key columns named by following `From` edges again.

As @a8m said in issue #548 , `From` edges are optional and could be dropped by user, then the foreign key column name must be changed. But with the future support of edge migrations, I think these cases can be handled:

- For O2O2types, O2M2types and M2M2types, the Ref edges should not be dropped. The migration tool should report a warning or fail in this situation.
- O2O2types -> O2M2typs auto migration should be supported, and needs no table and data change. The reverse migration is not possible. 
- O2O2types -> M2M2types auto migration should be supported, and a new relation table should be created and populated with existing data. The reverse migration is not possible.
- O2M2types -> M2M2types auto migration should be supported, and a new relation table should be created and populated with existing data. The reverse migration is not possible.
- O2ORecurisve -> M2MRecursive auto migration should be supported, and a new relation table should be created and populated with existing data. The reverse migration is not possible.
- O2OBidirection -> M2MBidirection auto migration should be supported, and a new relation table should be created and populated with existing data. The reverse migration is not possible.
- All other kinds of edge change/migrations are not supported and should produce a warning or fail.

Maybe I have made some mistakes here, so I appreciate any guidance on this topic.

**Comment by masseelch** [comment]
@a8m I don't know if you ever went over this, if not, this is a reminder.

@kidlj Ent now has support for the [Atlas](https://atlasgo.io/) migration engine ([docs](https://entgo.io/docs/migrate#atlas-integration)) and that solves what you have mentioned. 

I close this issue, feel to re-open, if you think it should stay open.

**Comment by kidlj** [comment]
@masseelch Sure, I'm gonna check the docs, thank you.
