### ISSUE TITLE
question: Spatial Data Types for MySQL

### ISSUE THREAD

**Issue by xbassols** [ent/ent#871]
Hello!

I've been trying to find this in the documentation without luck. Is there a way to use the MySQL Spatial Data Types?

If there is none, what approach should I follow in order to use them keeping compatibility with ent?

Best,

**Comment by a8m** [comment]
Hey @xbassols, can you please comment here what MySQL you try to use, and how do you use it in Go (the Go type)? I want to check this by myself. Thanks

**Comment by xbassols** [comment]
I would like to use the geometry type field so I can use the ST_ functions in MySQL. I don't exactly know how I would parse that in Go but probably as the JSON type converting the data from [WKT](https://dev.mysql.com/doc/refman/5.7/en/gis-data-formats.html#gis-wkt-format) to GeoJSON.

**Comment by masseelch** [comment]
@xbassols you can use the [`GoType`]()https://entgo.io/docs/schema-fields#go-type or [`Other`](https://entgo.io/docs/schema-fields#other-field) field type to aacomplish this. Let me know, if you need more help with this.
