### ISSUE TITLE
proposal: make entc commands accessible via a package 

### ISSUE THREAD

**Issue by masseelch** [ent/ent#879]
Make the commands of the `entc` cli available to use as package (it already is possible with the `generate` command).

I'd like to wrap the `describe` and `init` commands in my own command. I am currently working on a skeleton generator for new go apps (they all follow a common pattern).

**Comment by masseelch** [comment]
I am happy to contribute, if you want.

**Comment by a8m** [comment]
Hey @masseelch and thanks for your proposal.

I'm actually thinking about renaming `entc` to `ent` and just expose the following commands:

```
ent init
ent describe 
ent generate
```

If we want to make some commands like `init` and `describe` accessible via a package, we need to create a different package(s) for this (and not `cmd`), like we have provide today with [`entc`](https://entgo.io/docs/code-gen/#use-entc-as-a-package).

So, the summarize it, the proposal sounds good to me, and let's start discussing on the implementation.

**Comment by masseelch** [comment]
I'd welcome the rename to `ent`. Cobra for example has the cli named `cobra` too. 

I'd actually rewrite the `cmd` package to follow the cobra convention (the way the cobra generator generates the commands). We can add `describe` and `init` functions to `entc` like you already did with `generate`.

**Comment by masseelch** [comment]
I additionally like to have a command to print the graph. Maybe we could construct a representation of the graph in the dot-language.
