### ISSUE TITLE
proposal: Add support for immutable edges

### ISSUE THREAD

**Issue by dilipkk-foyernet** [ent/ent#900]
I couldn't find a option to make edge relation immutable. @a8m can you please help me with this?

**Comment by a8m** [comment]
Hey @dilipkk-foyernet!

There's no such option in ent. However, you can add a hook for enforcing this logic by yourself.

**Comment by dilipkk-foyernet** [comment]
@a8m ok sure thanks for your response, should I keep the issue open as you marked as **Feature request**?

**Comment by a8m** [comment]
> @a8m ok sure thanks for your response, should I keep the issue open as you marked as **Feature request**?

Yes, keep it open for now, and let's wait for more feedbacks before we continue with it.

**Comment by ORBAT** [comment]
I'd definitely find immutable edges useful, and it feels funny that you can make fields immutable but not edges

**Comment by cliedeman** [comment]
Just found a use case for this. 

When combined with [Edge Fields](https://entgo.io/docs/schema-edges/#edge-field) if you use an immutable the generated code will not compiled do so the setter method not being generated



```go
field.Int("organisation_id").Immutable(),

...

edge.From("organisation", Organisation.Type).Ref("profiles").Required().Unique().Field("organisation_id"),

...

// SetOrganisation sets the "organisation" edge to the Organisation entity.
func (opuo *OrganisationProfileUpdateOne) SetOrganisation(o *Organisation) *OrganisationProfileUpdateOne {
	return opuo.SetOrganisationID(o.ID) // unresolved reference SetOrganisationID
}
```

**Comment by a8m** [comment]
Thanks for reporting this @cliedeman. I added a check to reject this until immutable edges will be supported.

I want to add the `Immutable()` option for edges. Do you think we should add this for all edge types, or only for unique edges?

**Comment by cliedeman** [comment]
Hi @a8m I don't see any reason not to add it for all edges.

**Comment by adayNU** [comment]
+1 for this feature. For us, the only need is for unique fields.

**Comment by Antonboom** [comment]
+1

**Comment by a8m** [comment]
Thank you all for the feedback. The issue was addressed with https://github.com/ent/ent/pull/2876. Please, update to the latest master, give it a try and update me if there's any issue with it.
