### ISSUE TITLE
auto-migration with column dropping silently deletes data when transitioning from O2M edge to M2M edge

### ISSUE THREAD

**Issue by DeedleFake** [ent/ent#939]
I decided recently to adjust an edge in my database from O2M to M2M, but, much to my surprise, the auto-migration just silently deleted the existing edges with no warning. To get around this, I'm now in the process of moving to a, potentially partially, manual migration system, but it seemed odd that it silently deleted data. I would have expected it to at least complain about it.

And yes, I was using `migrate.WithDropColumns(true)`.

**Comment by a8m** [comment]
Hey @DeedleFake and thanks for raising up this issue.

Sorry to hear this, but yeah, this kinda one of the limitations we have in the migration at the moment, but it's going to be changed soon as part of https://github.com/facebook/ent/issues/866. 

I'm going to add support for the 2 following features:
1. Manage ent-schema versions and complain (or warning) when a change is not valid or trivial. For example, changing a field from int to string, or one like yours - There will be another option for comparing the schema in the feature-branch against one in a master/main branch (in cases like ours, where we run migration on every schema change). 
2. Provide an incremental version upgrades with up/down options. Mainly, for integrating with tools like golang-migrate/migrate (more details will be added soon). 

For now (if you still use ent-migrate), you can use the [offline migration mode](https://entgo.io/docs/migrate/#offline-mode) for getting the schema-changes before you execute them on the database. Especially in a drop-mode (we use this as well).

**Comment by masseelch** [comment]
This should now work correctly with the [atlas migration engine](https://entgo.io/docs/migrate#atlas-integration) and [versioned migrations](https://entgo.io/docs/versioned-migrations). 

Feel freee to re-open, if you think otherwise.
