### ISSUE TITLE
proposal: generate graphql schema

### ISSUE THREAD

**Issue by napei** [ent/ent#974]
I recently tried to add graphql to my existing ent project, but failed miserably because I both didn't understand the documentation for both, and also need to learn GraphQL :joy:

So, from what I can tell, `gqlgen` is schema first, as is `ent` (I think). So, would it be at all possible that graphql intergation can be done purely through generation using `entql`? That would be the schemas and config for gqlgen all nicely packaged into another sub-folder under `/ent`?

Perhaps I'm missing something though.

**Comment by a8m** [comment]
Hey @napei, nice to see you here again 😃 

> So, from what I can tell, gqlgen is schema first, as is ent (I think). So, would it be at all possible that graphql intergation can be done purely through generation using entql? That would be the schemas and config for gqlgen all nicely packaged into another sub-folder under /ent?

That's definitely the plan, and not only for GraphQL, but for other API layers as well (e.g. OpenAPI, Protobuf, etc).

The idea is to create another annotation in `entgql` that will tell the codegen to generate a GraphQL schema, and then it will execute the `gqlgen` codegen.
My plan it is to finish work on the migration and upsert API in the upcoming weeks, and then to start focusing on API integrations (GraphQL will be the 1st).

Let's leave it open for getting feedback and suggestions for the API.

**Comment by napei** [comment]
That's great to hear 😊

I've been busy using ent in production for e-commerce and I'm pleased so far. Keep up the good work

**Comment by wenerme** [comment]
recently done generate gql schema and gql resolver, but it's hard to decide which graphql schema pattern to follow.
I used five generate to achieve this

```go
pflag.StringVar(&conf.entSchema, "ent-schema", "", "Schema")
pflag.StringVar(&conf.entTarget, "ent", "", "target")
pflag.StringVar(&conf.entPackage, "ent-pkg", "", "package")
pflag.StringVar(&conf.gqlTarget, "gql", "", "graph")
pflag.BoolVar(&conf.genEnt, "gen-ent", false, "ent")
pflag.BoolVar(&conf.genEntExt, "gen-entx", false, "ent ext")
pflag.BoolVar(&conf.genGqls, "gen-gqls", false, "graphql schema")
pflag.BoolVar(&conf.genGql, "gen-gql", false, "graphql")
pflag.BoolVar(&conf.genGqlResolver, "gen-gqlr", false, "graphql resolver")
pflag.BoolVar(&conf.genAll, "gen-all", false, "all")
```

current ent generate should be more extendable, so can make `gen-entx` and `gen-gql` as external feature.
But gqlgen's generator is worse than ent's, can not inject resolver code, so, have to write a go code rewriter to modify the generated code, the `gen-gqlr` phase.

The final result is like

schema

```gql
extend type Mutation {
	createUser(input: CreateUserInput!): CreateUserPayload
	updateUser(input: UpdateUserInput!): UpdateUserPayload
	deleteUser(input: DeleteUserInput!): DeleteUserPayload
}

extend type Query {
        // query and sort is customized field
	users(query: [String!] = [], sort: String! = "", after: Cursor, first: Int, before: Cursor, last: Int, orderBy: UserOrder): UserConnection
}
```

resolvers

```go
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.CreateUserPayload, error) {
	return r.Client.User.Create().CreateFromInput(ctx, &input)
}

func (r *mutationResolver) UpdateUser(ctx context.Context, input ent.UpdateUserInput) (*ent.UpdateUserPayload, error) {
	return r.Client.User.UpdateOneID(input.ID).UpdateFromInput(ctx, &input)
}

func (r *mutationResolver) DeleteUser(ctx context.Context, input ent.DeleteUserInput) (*DeleteUserPayload, error) {
	err := r.Client.User.DeleteOneID(input.ID).Exec(ctx)
	return &DeleteUserPayload{ClientMutationID: input.ClientMutationID}, err
}
```
 I hope I have time to put this input ent contrib.

**Comment by a8m** [comment]
The issue was resolved with https://entgo.io/docs/tutorial-todo-gql-schema-generator.

Please, let @giautm or myself know if anything there can be improved.
