### ISSUE TITLE
Using string IDs generates invalid code

### ISSUE THREAD

**Issue by ivanvanderbyl** [ent/ent#995]
When using string IDs in the generator setup, the associated SQL handling code produced still assumes an int64 ID: 

```go
l.ID = string(value.Int64)
```

<details>
 <summary><code>ent/list.go</code></summary>

Generated code:

```go
func (l *List) assignValues(values ...interface{}) error {
	if m, n := len(values), len(list.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	l.ID = string(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field title", values[0])
	} else if value.Valid {
		l.Title = value.String
	}
	return nil
}
```

</details>

<details>
 <summary><code>ent/list_create.go</code></summary>

Generated code:

```go
func (lc *ListCreate) sqlSave(ctx context.Context) (*List, error) {
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = string(id)
	return _node, nil
}

```

</details>

<details>
 <summary><code>ent/cmd/entc.go</code></summary>

Custom `entc` command:

```go

func main() {
	err := entc.Generate("./ent/schema", &gen.Config{
		Templates: entgql.AllTemplates,
		Features: []gen.Feature{
			gen.FeaturePrivacy,
		},
		IDType: &field.TypeInfo{Type: field.TypeString},
	})
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}

```

</details>

**Versions**

```
github.com/facebook/ent v0.5.0
github.com/facebookincubator/ent-contrib v0.0.0-20201101132939-7984b86acfa0
```

**Comment by a8m** [comment]
Hey @ivanvanderbyl!

Since string IDs don't have default configuration in ent (in the database), you need to define the ID field (as string) in the `Fields` configuration. Please see example [here](https://entgo.io/docs/schema-fields/#id-field) and let me know if you still have issue with it.

**Comment by ivanvanderbyl** [comment]
@a8m thanks for that. I eventually figured that out from an example. Even though that code never runs, `go vet` complains about it so I figure it's still an issue.
